### ISSUE TITLE
Use chained config

### ISSUE THREAD

**Issue by JunTaoLuo** [aspnet/Hosting#1004]
Use the wrapped config in https://github.com/aspnet/Configuration/issues/630 once it's ready.

**Comment by muratg** [comment]
Closing this as won't fix. (cc @HaoK)

**Comment by HaoK** [comment]
So does this mean you no longer want https://github.com/aspnet/Configuration/issues/630 as well?

**Comment by Tratcher** [comment]
aspnet/Configuration#630 is still a valid feature, but Hosting doesn't need it right now. It's unfortunate it keeps getting cut without first party consumers.

**Comment by HaoK** [comment]
Ok I'll just add it since it should be relatively cheap and now is a lull :)
