### ISSUE TITLE
Replace ConfigureLogging(Action<ILoggerFactory>) from IWebHostBuilder

### ISSUE THREAD

**Issue by JunTaoLuo** [aspnet/Hosting#1007]
This method needs to be replaced with ConfigureLogging(Action<LoggerFactory>) after https://github.com/aspnet/Hosting/pull/978. This is still a breaking change since the interface was updated but should not break existing usage of the ConfigureLogging().

**Comment by JunTaoLuo** [comment]
Users are expected to use the alternatives UseLoggerFactory(Func<WebHostBuilderContext, ILoggerFactory> createLoggerFactory) and ConfigureLogging<T>(Action<T> configureLogging) where T : ILoggerFactory. Note that this depends on and may be combined with #1015

**Comment by muratg** [comment]
Adding @cesarbs, and re-triaging to preview1 based on our discussion.

**Comment by JunTaoLuo** [comment]
Will create announcement.
