### ISSUE TITLE
Anyway to pass command line parameters to testhost.dll when running via xUnit?

### ISSUE THREAD

**Issue by RTodorov** [aspnet/Hosting#1009]
Hello there,

Is is possible to pass parameters to testhost.dll when running my tests via xUnit (``dotnet test``)?

The idea is to be able to retrieve the parameters via ``Environment.GetCommandLineArgs()``

Thank you!

**Comment by muratg** [comment]
Please file an issue on microsoft/vstest repo. This is not a Hosting concept.
