### ISSUE TITLE
Add WebHostBuilderContext to ConfigureLogging<T> and remove UseLoggerFactory(this IWebHostBuilder hostBuilder, Action<WebHostBuilderContext, LoggerFactory> configure)

### ISSUE THREAD

**Issue by JunTaoLuo** [aspnet/Hosting#1015]
ConfigureLogging<T>(Action<T> configureLogging) is missing the WebHostBuilderContext and cannot handle logging configuration that may be dependent on configuration for example.

Remove the overload of UseLoggerFactory since it provides little additional benefit compared to just using UseLoggerFactory(Func<WebHostBuilderContext, ILoggerFactory> createLoggerFactory) 

cc @glennc

**Comment by glennc** [comment]
Also `ConfigureLogging<LoggerFactory>(Action<LoggerFactory> configureLogging)` and `ConfigureLogging<LoggerFactory>(Action<Context, LoggerFactory> configureLogging)`  extension method, fill in the `T`. That way code like this works:

```csharp
builder.ConfigureLogging(loggerFactory => loggerFactory.AddConsole());
```
```csharp
builder.ConfigureLogging((context, factory) => factory.AddFileLogger(context.Configuration["LogFileName"]));
```

Right?

**Comment by JunTaoLuo** [comment]
Thanks @glennc for the pr https://github.com/aspnet/Hosting/pull/1020
