### ISSUE TITLE
StopAsync cancellationToken chaining

### ISSUE THREAD

**Issue by Tratcher** [aspnet/Hosting#1016]
In https://github.com/aspnet/Hosting/pull/995/files we added `IWebHost.StopAsync(CancellationToken)` and an extension method `StopAsync()`. The extension method does not have access to the WebHostOptions to get the timeout, so it can only specify CancellationToken.None. In the real implementation we check if the token passed in can be cancelled, and if not then we create a new one using the timeout. This is not the most intuitive so I've filed this bug for followup design.

Prior art: HttpClient has a default timeout and SendAsync also accepts cancellationTokens. SendAsync creates a linked CTS using both the cancellationToken and the timeout.

**Comment by muratg** [comment]
@glennc What are your thoughts on this?

**Comment by BrennanConroy** [comment]
https://github.com/aspnet/Hosting/commit/c7bac3133f01aeea5c4e2c084159c5850440a9f8
