### ISSUE TITLE
Restore `dotnet run` argument separator

### ISSUE THREAD

**Issue by mikeharder** [aspnet/Hosting#1018]
The argument separator for `dotnet run` was removed in https://github.com/aspnet/Hosting/commit/5f9fa5c009f84633aeec07655fad53e491843f45 to workaround "dotnet run no longer passes additional arguments to application" (dotnet/sdk#1118).  This change should be reverted when dotnet/sdk#1118 is fixed.

**Comment by mikeharder** [comment]
Skip commit: https://github.com/aspnet/Mvc/commit/c69e48f06b0c141e26bc560e37bb19d32e89c377

**Comment by kichalla** [comment]
7d0770b0e4aefd414cca64ed2afd35870182243c
