### ISSUE TITLE
Add WaitForShutdown method

### ISSUE THREAD

**Issue by davidfowl** [aspnet/Hosting#1022]
This makes it easy to start the server and wait for a signal (Ctrl+c/sigint by default).

**Comment by Tratcher** [comment]
Do you mean Run without the console writeline output?

**Comment by davidfowl** [comment]
And without calling start

**Comment by muratg** [comment]
@davidfowl Are you doing this?

**Comment by muratg** [comment]
@JunTaoLuo keeping this in 2.0.0
