### ISSUE TITLE
Flaky: WebHostTests.WebHostShutsDownWhenTokenTriggers

### ISSUE THREAD

**Issue by Tratcher** [aspnet/Hosting#1024]
```
Assert.Equal() Failure
Expected: 1
Actual:   0
   at Microsoft.AspNetCore.Hosting.WebHostTests.WebHostShutsDownWhenTokenTriggers() in C:\BuildAgent\work\2b0c8ce712895332\.r\Hosting\test\Microsoft.AspNetCore.Hosting.Tests\WebHostTests.cs:line 162
```

## Repros
Win2012-Universe 24421
Win8-Universe 1812, 1806
Win7-Universe 19392
4/24/17: http://aspnetci/viewLog.html?buildId=207791&tab=buildResultsDiv&buildTypeId=Lite_UniverseTest
4/25/17: http://aspnetci/viewLog.html?buildId=208071&tab=buildResultsDiv&buildTypeId=Lite_UniverseTest

**Comment by kichalla** [comment]
Just FYI...I have hit this when building Hosting repo on my desktop (Win10)

**Comment by JunTaoLuo** [comment]
I saw this on travis ubuntu as well.

**Comment by muratg** [comment]
@JunTaoLuo / @kichalla if you see this again, feel free to disable for preview1.

**Comment by mikeharder** [comment]
Another repro: http://aspnetci/viewLog.html?buildId=208071&tab=buildResultsDiv&buildTypeId=Lite_UniverseTest

**Comment by muratg** [comment]
@JunTaoLuo let's just disable for now, and keep the bug open for fixing this in preview2.

**Comment by BrennanConroy** [comment]
https://github.com/aspnet/Hosting/commit/b6f558d60b130d7f8892bed7d1a5b72f575fdc28
