### ISSUE TITLE
Remove Test Logging from IntegrationTesting

### ISSUE THREAD

**Issue by anurse** [aspnet/Hosting#1026]
And replace with https://github.com/aspnet/Logging/pull/601 when it merges.

**Comment by muratg** [comment]
@anurse Are you able to this today/tomorrow?  (i.e. is this preview1 or preview2?)

**Comment by anurse** [comment]
Should be done today

**Comment by anurse** [comment]
Well, I'm going to wait for tomorrow to merge all the PRs because I don't want to break the build and then leave for the evening ;)
