### ISSUE TITLE
Add API to configure shutdown timeout

### ISSUE THREAD

**Issue by davidfowl** [aspnet/Hosting#1031]
Seems we only read it from configuration now.

**Comment by Tratcher** [comment]
There's also `StopAsync(this IWebHost host, TimeSpan timeout)`

**Comment by davidfowl** [comment]
Yea, there is, we should add a top level method for configuring options. Just like prefer hosting urls.

**Comment by muratg** [comment]
Related to #1016.

**Comment by BrennanConroy** [comment]
What do we want to name the extension method?
`public static IWebHostBuilder UseShutdownTimeout(this IWebHostBuilder hostBuilder, TimeSpan timeout)`
Or
`public static IWebHostBuilder ConfigureShutdownTimeout(this IWebHostBuilder hostBuilder, TimeSpan timeout)`
Or
`public static IWebHostBuilder SetShutdownTimeout(this IWebHostBuilder hostBuilder, TimeSpan timeout)`

**Comment by Tratcher** [comment]
UseShutdownTimeout would be the most consistent.
https://github.com/aspnet/Hosting/blob/b6f558d60b130d7f8892bed7d1a5b72f575fdc28/src/Microsoft.AspNetCore.Hosting.Abstractions/HostingAbstractionsWebHostBuilderExtensions.cs#L139

**Comment by davidfowl** [comment]
I want to kill all of these extension methods and do this instead https://github.com/aspnet/Hosting/issues/1042

**Comment by BrennanConroy** [comment]
https://github.com/aspnet/Hosting/commit/03bdb40f8a07427bbd83c89154c02da2ec92aea9
