### ISSUE TITLE
Remove workaround : executable permission for published app on cross plat OSes

### ISSUE THREAD

**Issue by kichalla** [aspnet/Hosting#1037]
Once this is fixed: https://github.com/dotnet/cli/issues/6286

revert: https://github.com/aspnet/Hosting/commit/51f77ea7f3b4a704691d0def9dd746fe0e32d5dc

**Comment by muratg** [comment]
@kichalla Do we still need the workaround?

**Comment by kichalla** [comment]
I am still able to repro it with latest CLI..looks like the NuGet fix isn't part of the CLI yet https://github.com/NuGet/Home/issues/4424#issuecomment-301510977

**Comment by kichalla** [comment]
https://github.com/aspnet/Hosting/commit/9f49d34c17ee7d55273bfe13cf7c6c3e014b36e9
