### ISSUE TITLE
Expose WebHostOptions as a first class way to configure the IWebHostBuilder

### ISSUE THREAD

**Issue by davidfowl** [aspnet/Hosting#1042]
Today we have special extension methods that configure settings on the `IWebHostBuilder` with various options, `PreferHostingUrls`, `CaptureStartupErrors` etc. Instead, we should expose `WebHostOptions` and a method `ConfigureOptions(Action<WebHostOptions>)` that lets you programmatically set configuration. This win over an configuration based logic.

**Comment by JosephWoodward** [comment]
This would be awesome 👍 Can think of a lot of great use cases for such an extension.

**Comment by muratg** [comment]
@davidfowl If we want this in 2.0.0, it needs to be designed this week.

**Comment by muratg** [comment]
@davidfowl will do the investigation

**Comment by muratg** [comment]
cc @glennc

**Comment by davidfowl** [comment]
This is low value so I'm going to close this.
