### ISSUE TITLE
Allowing Configure method to be inherited by Startup class

### ISSUE THREAD

**Issue by matthewhancock** [aspnet/Hosting#105]
I'm going to have multiple web applications sharing base code and it would be great if the Startup class could inherit the Configure method from a parent class. Otherwise, I'm going to have to copy and paste the same boilerplate.

e.g. this wouldn't fail

```c#
    public class Startup : StartupTemplate
    {
        public override async Task ProcessRequestAsync(HttpContext Context)
        {
            await Context.Response.WriteAsync("Hello World");
        }
    }
    public abstract class StartupTemplate
    {
        public void Configure(IApplicationBuilder app)
        {
            app.Run(ProcessRequestAsync);
        }
        public abstract Task ProcessRequestAsync(HttpContext Context);
    }
```

This returns the basic Configure not found error:

```
    System.Exception: TODO: ConfigureDevelopment or Configure method not found
    at Microsoft.AspNet.Hosting.Startup.StartupLoader.LoadStartup(String applicationName, String environmentName, IList`1 diagnosticMessages)
```

It looks like the update would need to be here: https://github.com/aspnet/Hosting/blob/dev/src/Microsoft.AspNet.Hosting/Startup/StartupLoader.cs

```c#
    var methodInfo = startupType.GetTypeInfo().GetDeclaredMethod(methodNameWithEnv)
    ?? startupType.GetTypeInfo().GetDeclaredMethod(methodNameWithNoEnv);
```

Could GetDeclaredMethod be replaced with [GetMethod(String, BindingFlags)](http://msdn.microsoft.com/en-us/library/05eey4y9%28v=vs.110%29.aspx)?

**Comment by dtkujawski** [comment]
I ran into this same issue and also believe that not requiring declared methods is a good idea so that we can derive the Startup.cs file from a base class.

Changing the line method above to the following would be nice:
```C#
var methodInfo = startupType.GetTypeInfo().GetMethod(methodNameWithEnv, BindingFlags.Public | BindingFlags.Instance)
        ?? startupType.GetTypeInfo().GetMethod(methodNameWithNoEnv, BindingFlags.Public | BindingFlags.Instance);
```

**Comment by glennc** [comment]
We are ok with taking this change if either of you guys want to submit a pull request, see the instructions if you haven't done it before.

**Comment by dtkujawski** [comment]
My first time doing a pull request, so let me know if I did it wrong:  https://github.com/aspnet/Hosting/pull/153

**Comment by Eilon** [comment]
https://github.com/aspnet/Hosting/pull/153 fixed this.
