### ISSUE TITLE
Modify UseConfiguration to support configuration section

### ISSUE THREAD

**Issue by mcm-ham** [aspnet/Hosting#1056]
I'd like to be able to store hosting configuration under a section in appsettings but UseConfiguration does not currently support this. e.g.

appsettings.json
```json
{
    "Hosting": {
        "Urls": "https://*:5000"
    }
}
```

Program.cs
```cs
var config = new ConfigurationBuilder()
    .AddJsonFile("appsettings.json")
    .build();

var host = new WebHostBuilder()
    .UseConfiguration(config.GetSection("Hosting"))
```

I think the only change needed is this:

https://github.com/aspnet/Hosting/blob/873a0e7/src/Microsoft.AspNetCore.Hosting.Abstractions/HostingAbstractionsWebHostBuilderExtensions.cs#L24
```cs
    foreach (var setting in configuration.AsEnumerable())
```
To
```cs
    foreach (var setting in configuration.GetChildren())
```

**Comment by davidfowl** [comment]
That's a breaking change though.

**Comment by mcm-ham** [comment]
How come? Existing apps will have a settings file looking like this:

```
{
  "Urls": "https://*:5000"
}
```

And with this test code:

```cs
var config = new ConfigurationBuilder()
    .AddJsonFile("appsettings.json")
    .Build();

foreach (var setting in config.AsEnumerable())
{
    Console.WriteLine($"Before - Key: {setting.Key}, Value: {setting.Value}");
}

foreach (var setting in config.GetChildren())
{
    Console.WriteLine($"After - Key: {setting.Key}, Value: {setting.Value}");
}
```

I get this output:

```
Before - Key: Urls, Value: https://*:5000
After - Key: Urls, Value: https://*:5000
```

So we get the same behaviour before and after change. The `UseConfiguration` method has argument of type `IConfiguration` so we're not needing to change the method signature from `IConfigurationRoot` to `IConfiguration`.

**Comment by mcm-ham** [comment]
Actually this is a dupe of #839.
