### ISSUE TITLE
Asp.NET Core have pure behavior when await

### ISSUE THREAD

**Issue by bnayae** [aspnet/Hosting#1058]
When I compare ASP.NET and ASP.NET Core Web API (over IIS Express).
It's seem that even those I'm awaiting Task.Delay it doesn't handle the next request and behave like 
having Thread Pool starvation.

the following code work great on ASP.NET and poor on ASP.NET Core

```C#
public async Task<string> Get(int id)
{
    Debug.Write(".");
    await Task.Delay(TimeSpan.FromSeconds(2));
    return $"#{id:00}";
}
```

I was testing it with the following code (using 50 concurrent request):

```C#
        private static async Task CallAsync(int times)
        {
            var sw = Stopwatch.StartNew();
            using (var http = new HttpClient())
            {
                var tasks = from i in Enumerable.Range(0, times)
                            let url = $"{BASE_URL}/{i}"
                            select InvokeAsync(http, url);
                string[] responses = await Task.WhenAll(tasks);
            }
            sw.Stop();
            Console.WriteLine($"\r\n\r\nTOTAL DURATION: {sw.Elapsed.TotalSeconds:N3} seconds");
        }

        private static async Task<string> InvokeAsync(HttpClient http, string url)
        {
            var latency = Stopwatch.StartNew();
            Console.Write("-");
            string response = await http.GetStringAsync(url);
            latency.Stop();
            Console.Write($"{latency.Elapsed.TotalSeconds:0.0}, ");
            return response;
        }
 ```

**Comment by davidfowl** [comment]
It probably doesn't have anything to do with thread pool starvation, it sounds like it could just be the amount of allowed concurrent http requests per domain. A few things to try:

- Use a single http client instance. Don't create a new one per request.
- Try upping the number of concurrent requests per domain using `new HttpClient(new HttpClientHandler() { MaxConnectionsPerServer=100 })`.

**Comment by benaadams** [comment]
I think IIS Express and IIS on a desktop OS (rather than server) have limits on active inbound requests

**Comment by davidfowl** [comment]
That's right, but it affects both ASP.NET and ASP.NET Core. It's a windows limitation on client OS...

**Comment by bnayae** [comment]
I was also testing it on Docker deployment (with VS 2017 docker support) and It was behaving the same.
As for the HttpClient I was using the same client for all Http calls.
MaxConnectionsPerServer=100 also don't help with the issue.

**Comment by davidfowl** [comment]
Closing this since it;s now open on kestrel
