### ISSUE TITLE
Change Hosting to target netcoreapp2.0 and remove reference to System.Runtime.Loader

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Hosting#1059]
According to https://github.com/dotnet/corefx/issues/18849#issuecomment-298692251, `System.Runtime.Loader 4.3.0` cannot be used in `netstandard` targeting projects (it's an API of `netcoreapp`). We need to remove this reference (https://github.com/aspnet/Hosting/blob/6d42b2fe86b7620f372cedeef494dd63aeb0df1a/src/Microsoft.AspNetCore.Hosting/Microsoft.AspNetCore.Hosting.csproj#L38) and cross-compile the project for `netstandard1.3` and `netcoreapp2.0`.

**Comment by pranavkm** [comment]
cc @davidfowl

**Comment by Eilon** [comment]
@pranavkm - is this something we need for Preview1?

**Comment by pranavkm** [comment]
Perhaps? Applications targeting net461 or higher might be broken in preview1. This was part of the reason why they are.

**Comment by Eilon** [comment]
Closing because this is now covered by https://github.com/aspnet/Coherence-Signed/issues/492.
