### ISSUE TITLE
Microsoft.Extensions.Hosting.Abstractions should target netstandard1.x, not netcoreapp2.0

### ISSUE THREAD

**Issue by Eilon** [aspnet/Hosting#1067]
This is an MS.Extensions package, not part of ASP.NET Core, so it should target `netstandard1.x`, not `netcoreapp2.0`.

https://github.com/aspnet/Hosting/blob/dev/src/Microsoft.Extensions.Hosting.Abstractions/Microsoft.Extensions.Hosting.Abstractions.csproj#L7

cc @glennc @davidfowl @bradwilson

**Comment by natemcmaster** [comment]
Now targets netstandard2.0. Good enough?

**Comment by bradwilson** [comment]
Why not 1.3 as it was originally? It needs nothing (and thus gains nothing) from 2.0.

**Comment by Tratcher** [comment]
@DamianEdwards

**Comment by Tratcher** [comment]
Extensions will now all target 2.0. https://github.com/aspnet/Announcements/issues/249
