### ISSUE TITLE
Discussion: ConfigureLogging(Action<ILoggerFactory>) removed from IWebHostBuilder

### ISSUE THREAD

**Issue by JunTaoLuo** [aspnet/Hosting#1069]
Discussion for https://github.com/aspnet/Announcements/issues/241.

**Comment by CoskunSunali** [comment]
Is there a chance an example of using the following method can be provided?

`IWebHostBuilder.UseLoggerFactory(Func<WebHostBuilderContext, ILoggerFactory> createLoggerFactory)`

And may be some details regarding the technical differences and the different scenarios we may want to pick a choice between using the following two:

```
.UseLoggerFactory(hostingContext => {
    var factory = new CustomLoggerFactory() // just create an instance of CustomLoggerFactory here and return it?
    
    factory.UseConfiguration(hostingContext.Configuration.GetSection("Logging"));
    factory.AddConsole();

    return factory;
})
```

```
.UseLoggerFactory(new CustomLoggerFactory())
.ConfigureLogging<CustomLoggerFactory>((hostingContext, factory)  => 
    {
         factory.UseConfiguration(hostingContext.Configuration.GetSection("Logging"));
         factory.AddConsole();
    })
```

**Comment by kierenj** [comment]
I was using a custom logger factory such that I could intercept log events and add contextual information to logged events (could be something from ASP.NET Core context, thread-local stuff, attributes from the call site's method/class).

I know it's a weird use case, but, I was using it.  Is there another way I can achieve this w/ASP.NET Core?

I quite liked @CoskunSunali's suggestion, and this ties in with the bigger question around using an already-existing DI container, in terms of ASP.NET Core plugging into something bigger.  @JunTaoLuo

**Comment by kierenj** [comment]
What's the deal with `ILoggerFactory` vs `ILoggingBuilder`? 

"An alternative would be to use the newly added extension ConfigureLogging(Action<LoggerFactory>) to configure the default LoggerFactory implementation"

I don't see one, only something that uses `ILoggingBuilder`?

The XML documentation also refers to `LoggerFactory`.. (https://github.com/aspnet/Hosting/blob/70a3017b12b4e9648f65acea2c9ad37e383763b0/src/Microsoft.AspNetCore.Hosting/WebHostBuilderExtensions.cs#L127)

In terms of my original point, what was the solution to @davidfowl's query with App Insights (https://github.com/aspnet/Hosting/issues/1071#issuecomment-301295044) ?

**Comment by davidfowl** [comment]
> Is there a chance an example of using the following method can be provided?

Why? You can just add a logger factory to the container. That's what serilog does, see https://github.com/serilog/serilog-aspnetcore.

> I was using a custom logger factory such that I could intercept log events and add contextual information to logged events (could be something from ASP.NET Core context, thread-local stuff, attributes from the call site's method/class).

Did you do it in a factory so that you could send the same data to all providers? You might be better off using something like Serilog enrichers to do this instead of attempting to write a custom logger factory.

> I quite liked @CoskunSunali's suggestion, and this ties in with the bigger question around using an already-existing DI container, in terms of ASP.NET Core plugging into something bigger. 

Handing an existing DI container to the hosting is incompatible with how the host works. I honestly don't ever see this working. If you have suggestions that don't add any new features to the DI system, I'm all ears.

> What's the deal with ILoggerFactory vs ILoggingBuilder?

ILoggingBuilder is the new DI friendly way to wire up logger providers. If your logger provider needs services, then you can use this to add them. We intended it to completely replace ILoggerFactory.AddProvider but we didn't end up deprecating it in 2.0 so now we have to ways to add providers which is unfortunate.

**Comment by kierenj** [comment]
Thanks, in fact I was already adding a logger factory to the container with 1.1.  Is there any implication - if I simply don't call ConfigureLogging, the factory will still be used?

I wasn't aware of Serilog but will check it out.

I edited in a point about the EventLog logger, it seems to want an `ILoggerFactory`, 

(I know the 'existing DI container' issue is bigger than me.  I'm not up-to-date on all the host stuff)

**Comment by CoskunSunali** [comment]
> I quite liked @CoskunSunali's suggestion, and this ties in with the bigger question around using an already-existing DI container, in terms of ASP.NET Core plugging into something bigger.

@kierenj Is it possible that you mentioned me by mistake? I don't remember making a suggestion around this issue. :)

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
