### ISSUE TITLE
Best way to avoid logging requests/exceptions twice when using DiagnosticSource and ILogger?

### ISSUE THREAD

**Issue by cwe1ss** [aspnet/Hosting#1072]
Everyone who tracks requests through DiagnosticSource events and also listens for ILogger events (like Application Insights, my hopefully-one-day-to-be-released OpenTracing library) has the problem that requests would show up twice (see [StartActivity](https://github.com/aspnet/Hosting/blob/dev/src/Microsoft.AspNetCore.Hosting/Internal/HostingApplicationDiagnostics.cs#L54) and [LogRequestStarting](https://github.com/aspnet/Hosting/blob/dev/src/Microsoft.AspNetCore.Hosting/Internal/HostingApplicationDiagnostics.cs#L79)).

Would you recommend just hard-coding a ILogger filter for `Microsoft.AspNetCore.Hosting` with a logLevel of `Error` (to at least still get Startup/Shutdown exceptions) or should I use the [Hosting Logger Event Ids](https://github.com/aspnet/Hosting/blob/dev/src/Microsoft.AspNetCore.Hosting/Internal/LoggerEventIds.cs) and exclude `LoggerEventIds.RequestStarting` and `LoggerEventIds.RequestFinished`?

Same issue for tracking exceptions with aspnet/Diagnostics. However in that case the logging statement [doesn't even use an EventId](https://github.com/aspnet/Diagnostics/blob/dev/src/Microsoft.AspNetCore.Diagnostics/ExceptionHandler/ExceptionHandlerMiddleware.cs#L49) right now so I'd probably have to completely exclude the `Microsoft.AspNetCore.Diagnostics` category.

/cc @SergeyKanzhelev

**Comment by muratg** [comment]
@cwe1ss In general, Diagnostic tracing and Logging serve different purposes. If you'd like filter out certain types of errors from Logging (because you get them in the Diagnostics reports) filtering things out is a reasonable idea.  

For the missing EventId's in diagnostics -- could you please file a bug there to plug the holes?  Thanks for bringing that up!

**Comment by cwe1ss** [comment]
I ended up setting the minimum level for this logger category to Warning. 

As requested, I created https://github.com/aspnet/Diagnostics/issues/393 regarding the missing EventIds.

Thanks.
