### ISSUE TITLE
Harden hosting startup

### ISSUE THREAD

**Issue by glennc** [aspnet/Hosting#1074]
- Aggressively force loading of dependencies in our own implementations of IHostingStartup to avoid delayed load exceptions
 - Ensure VS doesn't attempt to enable hosting startup for AppInsights if application already depends on it explicitly, or that enabling app insights is completely idempotent and we are ok with it being done all the time.

**Comment by Tratcher** [comment]
Does this hardening belong in Hosting or in the individual light-up packages? I would think they would be better equipped to understand their own dependencies.

**Comment by glennc** [comment]
Each lightup package probably, depends on the plan. Your right this should probably move to AzureIntegration, I blindly put it here because it had hosting in the name.

**Comment by Tratcher** [comment]
https://github.com/aspnet/Hosting/issues/1075

**Comment by Tratcher** [comment]
Offline notes:
- Fix #1075
- Lightup packages should touch their primary dependencies from with HostingStartup.
- Make sure lit up components are idempotent (don’t double register services, middleware, etc..)
- Many WebHostBuilder methods register callbacks that are executed later, outside of the HostingStartup catch block. If these are the first thing to touch a dependency, they also need to be wrapped. See ConfigureServices, ConfigureLogging, ConfigureAppConfiguration, etc..
- It's not just 3rd party dependencies that are the problem. An app may deploy and load an earlier version of ASP.NET libraries (e.g. Json config), so when the lightup tries to load the current version it may fail.

Aside from, most of the changes need to be made in the lightup packages. @muratg this need triaging, #1075 is the most critical fix and the only one that will fit in preview2.

**Comment by muratg** [comment]
We did the planned work for preview2. There's a few follow-up items that we'll need to talk about and plan for preview3.

**Comment by muratg** [comment]
@DamianEdwards do we want to invest time in `detectoid` work in 2.0.0 RTM?

**Comment by DamianEdwards** [comment]
No, I don't think it's critical for release.

**Comment by muratg** [comment]
Closing as we think what we currently have is good enough.
