### ISSUE TITLE
Consider adding a "Test" environment

### ISSUE THREAD

**Issue by cwe1ss** [aspnet/Hosting#1077]
Right now, we have "Development", "Staging" and "Production" as built-in environment keys. 

[The docs](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/environments) define them as follows:
* Development: This should be the environment used when developing an application.
* Staging: By convention, a Staging environment is a pre-production environment used for final testing before deployment to production. Ideally, its physical characteristics should mirror that of production, so that any issues that may arise in production occur first in the staging environment, where they can be addressed without impact to users.

So I'd use "Development" for developer machines (with local databases etc) and "Staging" for an Azure Web App slot (with settings very similar to production).

However, I'm missing the environment that sits logically between these two - a "test" system that is connected to a test database and is used by testers etc.

I know that I can always use my own environment keys but I thought that this might be common enough to consider it as a built-in feature?!

PS: Sorry if this was already discussed and declined.

**Comment by hishamco** [comment]
IMHO the `Development`, `Staging` & `Production` are the common environments names, of course there are other environments used by other such as Integration, Testing .. etc, 

While [`EnvirnmentName`](https://github.com/aspnet/Hosting/blob/dev/src/Microsoft.AspNetCore.Hosting.Abstractions/IHostingEnvironment.cs#L17) is a string, nothing will stop you to define your custom once and pass them in `UseEnvironment()` method, also you can check them easily using [IsEnvironment()](https://github.com/aspnet/Hosting/blob/dev/src/Microsoft.AspNetCore.Hosting.Abstractions/HostingEnvironmentExtensions.cs#L65) method

**Comment by cwe1ss** [comment]
I know. As I've said, this issue is just here to discuss if there should be another built-in environment.

**Comment by muratg** [comment]
@DamianEdwards thoughts on this one?

**Comment by DamianEdwards** [comment]
I'm a little hesitant to add anymore as it gets very specific to each person's set up. I'd rather we stick with the existing small list and continue to recommend any other names are added in the application (or shared dependency) by customers.

**Comment by cwe1ss** [comment]
Fair enough! I'm just surprised that not more people want this - so I'm curious:
* Do you all use "Development" for local developer boxes AND shared test systems?
* Do you use "Staging" for the test system?
* Don't you have a shared test system?
* Do you use custom environment names anyway?

**Comment by nemanja-djordjevic-pamet** [comment]
I also think, that in real scenarios, Test environment is always used. 
During my career as software developer, every project had Test environment. Sometimes Staging was never used.
At current customer there is DEV (Development), PROD (Production), UAT (Test) and MNT (Maintenance).
I think that Test environment is so common that it should be included as built-in environment.

**Comment by neman** [comment]
I also think, that in real scenarios, Test environment is always used.
During my career as software developer, every project had Test environment. Sometimes Staging was never used.
At current customer there is DEV (Development), PROD (Production), UAT (Test) and MNT (Maintenance).
I think that Test environment is so common that it should be included as built-in environment.

**Comment by AlanBarber** [comment]
In most places I've been there are 4 separate deployment scenarios:

1) Local Developer
2) QA / Test
3) UAT / Staging
4) Production

1 & 2 have ASPNETCORE_ENVIRONMENT set to "Development" and 3 & 4 have ASPNETCORE_ENVIRONMENT set to "Production" since a staging system should be running the exact same code that prod does.

IMO if you find yourself needing more environment names, that's a code smell that you have too much custom environment specific code that needs to be refactored to external config files.

**Comment by neman** [comment]
Same code, but not the same database, logging environments, file storage and other settings.
Dev should not pollute testing data.

**Comment by snebjorn** [comment]
I sure could use something like this :)

```c#
if (!env.IsTesting())
{
    app.UseSwagger();
    app.UseSwaggerUI();
}
```

**Comment by cwe1ss** [comment]
There hasn't been much demand for this so I'm totally fine with this being closed if you want.

**Comment by hishamco** [comment]
I'm waiting for `Property Extensions` to make this happen without touch the core APIs

**Comment by muratg** [comment]
@cwe1ss agreed, thanks.
