### ISSUE TITLE
Resolve IServer in IWebHost.Start

### ISSUE THREAD

**Issue by davidfowl** [aspnet/Hosting#1081]
We should resolve the `IServer` in IWebHost.Start to avoid unnecessarily configuring the server if it's never going to be started.

/cc @Tratcher @halter73

**Comment by muratg** [comment]
@davidfowl punting this one to backlog. If you think we have to do this in 2.0.0 (we can't do it in 2.1) ping me and we need to prioritize this with other items.

**Comment by davidfowl** [comment]
We ended up doing this.
