### ISSUE TITLE
ApplicationDeployer should restore with RID for standalone apps when needed

### ISSUE THREAD

**Issue by JunTaoLuo** [aspnet/Hosting#1082]
https://github.com/aspnet/Hosting/blob/dev/src/Microsoft.AspNetCore.Server.IntegrationTesting/Deployers/ApplicationDeployer.cs#L54

We should add an additional step before this to restore the project with/without a RID for Standalone/Portable deployments.

**Comment by muratg** [comment]
Won't fix in 2.1. We may revisit later.
