### ISSUE TITLE
SelfHostDeployer logs debug regardless of parent process log level

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/Hosting#1087]
This causes a lot of useless spew inside logs for repositories like Universe (whose log files are currently 50mb+, ~50% of which comes from SelfHostDeployer) and hides more important log messages among it.

**Comment by muratg** [comment]
Won't fix.

**Comment by muratg** [comment]
@ryanbrandenburg if you want a fix, please take a look :)
