### ISSUE TITLE
[IntegrationTesting] Dynamic Port Allocation sometimes doesn't release the port

### ISSUE THREAD

**Issue by anurse** [aspnet/Hosting#1093]
Our logic to dynamically allocate a port doesn't always release the port fast enough for the server to use it when it start up. The OS seems to keep the port number reserved after we dispose our socket.

To resolve this, we could use the following logic:

1. For Kestrel only: The deployer passes down `localhost:0` as the URL, which causes Kestrel to bind to any free port. The deployer already sniffs the resulting URL out of stdout, so this should just work
2. For WebListener and IIS Express, which don't support port 0 binding, we pick a random port from a wide range, attempt to start the server, detect if it fails because of an address in use error and if it does, retry with a new random port.

**Comment by jkotalik** [comment]
@anurse 
Do you happen to know which tests are occasionally failing? Also is this issue purely with our integration tests? I see this logic here for finding a port for IISExpress, is this what you are referencing? https://github.com/aspnet/Hosting/blob/dev/src/Microsoft.AspNetCore.Server.IntegrationTesting/Deployers/IISExpressDeployer.cs#L92-L96

**Comment by anurse** [comment]
It's not consistent which tests fail. The big problem is that for WebListener and IIS Express, we have to pick a port number in advance (for Kestrel, we can use port `0` and the OS will pick a free port for us that is guaranteed not to have any conflicts).

So for WL and IIS we use this helper: https://github.com/aspnet/Hosting/blob/dev/src/Microsoft.AspNetCore.Server.IntegrationTesting/Common/TestUriHelper.cs#L38 which uses port `0` to bind a socket, causing the OS to pick a free port for us. Then we get the port number, shut down our socket and pass it along to WL/IIS. Unfortunately, even though we close the socket, sometimes the OS leaves the underlying socket allocated for a while, so when WL/IIS goes to bind to the socket, it fails because the port is already in use. I'm not sure how to resolve that, it may be something we can't avoid.

One thing we could consider for WL/IIS, is binding to GUID-named hostnames instead of random ports. HTTP.sys allows multiple processes to share port 80 as long as they're on different hostnames/ports. We could use something like [localtest.me](http://readme.localtest.me/), which is a DNS that forwards all subdomains to `127.0.0.1` and then bind each test to `[testname]_[guid].localtest.me` or something (perhaps using a port other than `80` to avoid Admin permissions, but still a well-known single port that doesn't have conflict issues). Thoughts @Tratcher ? That would avoid port conflicts altogether, assuming we can make the necessary bindings happen.

**Comment by jkotalik** [comment]
@anurse I'll go ahead and prototype that. Testing will be interesting as these are sporadic errors.

**Comment by Drawaes** [comment]
I wonder what is really going on here. I have made this in a loop of a million  ( create socket get port, dispose socket and create again straight away on that port) and never hit the problem..  I wonder if the machines that are running the tests are defaulting to address reuse false? Or some linger setting?

**Comment by jkotalik** [comment]
Were you making a separate process to obtain the same port? Ex spawn a child process, passing in the port as a param,and obtain the same socket?

**Comment by Drawaes** [comment]
This was my test

https://gist.github.com/Drawaes/d22401a6379bbbe6503e0c62152fe882

**Comment by anurse** [comment]
Looks like you're testing it the same way I suggested @jkotalik test it ;). So yeah, I'm not sure we're going to be able to nail down a problem. It's also possible it's some other machine state interfering. It's extremely hard to reproduce, it seems to be a very rare race condition. We've definitely seen it happen in the wild (our build system has hit it a few times), but I don't think I've ever been able to reproduce it in a controlled environment.

Might just be something we put aside for now. @ryanbrandenburg are we seeing port in use errors in our build failures with any kind of frequency right now? My understanding is that it's a very rare occurrence.

**Comment by Drawaes** [comment]
Maybe throw a 
socket.Close() after you get the port... just in case, it can't hurt right?

**Comment by anurse** [comment]
Yeah, tried that. Also tried `.Shutdown` and a bunch of LingerState options. It's super weird...

**Comment by Drawaes** [comment]
Yeah I did that. And tried exclusive address use, binding to All and to a real ip, udp looking at the sockets with sys internals... go figure

**Comment by jkotalik** [comment]
@ryanbrandenburg _ping_

**Comment by ryanbrandenburg** [comment]
I'm unable to find any recent examples. I would be fine with closing this for now, we can re-open if it resurfaces.
