### ISSUE TITLE
Disposing host in WebHostService may raise unhandled exception 

### ISSUE THREAD

**Issue by strongtigerman** [aspnet/Hosting#1100]
Disposing host in WebHostService may raise unhandled exception when Kestrel receives new requests.
In such case Windows Service hangs and no longer responds to system requests. The only way to stop the service is to delete the task by TaskManager.
```
protected sealed override void OnStop()
        {
            _stopRequestedByWindows = true;
            OnStopping();
            _host?.Dispose();
            OnStopped();
        }
```

**Comment by davidfowl** [comment]
> Disposing host in WebHostService may raise unhandled exception when Kestrel receives new requests.

What unhandled exception? Do you have an example?

**Comment by strongtigerman** [comment]
> What unhandled exception? Do you have an example?

[https://stackoverflow.com/questions/44324864/unable-to-stop-asp-net-core-windows-service-when-kestrel-receives-requests
](https://stackoverflow.com/questions/44324864/unable-to-stop-asp-net-core-windows-service-when-kestrel-receives-requests)



> Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvException: Error -4082 EBUSY resource busy or locked
> in Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.Libuv.loop_close(UvLoopHandle handle) in Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvLoopHandle.ReleaseHandle() in System.Runtime.InteropServices.SafeHandle.InternalDispose() in System.Runtime.InteropServices.SafeHandle.Dispose(Boolean disposing)
> in System.Runtime.InteropServices.SafeHandle.Dispose() in Microsoft.AspNetCore.Server.Kestrel.Internal.KestrelThread.ThreadStart(Object parameter)
> 
> in Microsoft.AspNetCore.Server.Kestrel.Internal.KestrelThread.d__51.MoveNext() in System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken) in Microsoft.AspNetCore.Server.Kestrel.Internal.KestrelEngine.Dispose()
> in Microsoft.AspNetCore.Server.Kestrel.KestrelServer.Dispose() in Microsoft.Extensions.DependencyInjection.ServiceProvider.Dispose()
> in Microsoft.AspNetCore.Hosting.Internal.WebHost.Dispose()
> 
> Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvException: Error -4082 EBUSY resource busy or locked in Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.Libuv.loop_close(UvLoopHandle handle) in Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvLoopHandle.ReleaseHandle() in System.Runtime.InteropServices.SafeHandle.InternalDispose() in System.Runtime.InteropServices.SafeHandle.Dispose(Boolean disposing)
> in System.Runtime.InteropServices.SafeHandle.Dispose() in Microsoft.AspNetCore.Server.Kestrel.Internal.KestrelThread.ThreadStart(Object parameter)
> 
> в Microsoft.AspNetCore.Server.Kestrel.Internal.KestrelThread.d__51.MoveNext()

**Comment by muratg** [comment]
Dup of https://github.com/aspnet/KestrelHttpServer/issues/1883
