### ISSUE TITLE
If the same Startup assembly is specified multiple times it is being executed multiple times

### ISSUE THREAD

**Issue by moozzyk** [aspnet/Hosting#1108]
If the same Startup assembly is specified more than once I think it would be better to execute it once and print a warning.

**Comment by muratg** [comment]
We should consider making loading idempotent.

**Comment by khellang** [comment]
The same would be true if you have multiple `HostingStartupAttribute` defined (with the same type). Is there a reason why multiple attributes in the same assembly is allowed?

**Comment by halter73** [comment]
I tested using multiple HostingStartupAttributes defined with the same time. `Assembly.GetCustomAttributes<HostingStartupAttribute>()` already dedupes identical attributes with identical arguments, so that isn't an issue.

Specifying the same assembly multiple times in ASPNETCORE_HOSTINGSTARTUPASSEMBLIES do cause that assembly's hosting startup classes to be executed multiple times though.

**Comment by khellang** [comment]
> `Assembly.GetCustomAttributes<HostingStartupAttribute>()` already dedupes identical attributes with identical arguments, so that isn't an issue.

Ah, interesting. Didn't know about that behavior. Is that related to `TypeId`? (I've always wondered what that property is for...)

**Comment by jkotalik** [comment]
So from what I can tell, there are two scenarios we need to check here:
- in UseStartup<Type>()
- in ASPNETCORE_HOSTINGSTARTUPASSEMBLIES 
@moozzyk were there any other places where you saw duplicate startup assemblies being specified?

**Comment by moozzyk** [comment]
@jkotalik - yes, I think this is it. 

(Not sure how you are going to identify duplicates but on Windows paths/file names are not case sensitive.)

**Comment by jkotalik** [comment]
Right now I think we have to check in [WebHostBuilder.UseSetting](https://github.com/aspnet/Hosting/blob/dev/src/Microsoft.AspNetCore.Hosting/WebHostBuilder.cs#L83-L87), as UseStartup is an extension method on WebHostBuilder. It would be odd to expose a set containing the assemblies being used.

**Comment by Tratcher** [comment]
Deduplicate at the point of execution, not where the properties are set.

**Comment by Tratcher** [comment]
Here: https://github.com/aspnet/Hosting/blob/a2962d54f18dece7ec57ee42f3e565f3727168e1/src/Microsoft.AspNetCore.Hosting/WebHostBuilder.cs#L198

**Comment by jkotalik** [comment]
This would mean calling UseStartup() multiple times on the same startup would not cause a log message, as it would overwrite the option in UseSetting. Is this fine?

**Comment by Tratcher** [comment]
That's fine, it's unrelated to this issue. This issue is about executing assemblies multiple times.
