### ISSUE TITLE
Remove NETStandard.Library.NETFramework dependency from Hosting.WindowsServices package

### ISSUE THREAD

**Issue by muratg** [aspnet/Hosting#1109]
Remove the following line: 

https://github.com/aspnet/Hosting/blob/dev/src/Microsoft.AspNetCore.Hosting.WindowsServices/Microsoft.AspNetCore.Hosting.WindowsServices.csproj#L15

This shouldn't be in the csproj per discussions with .NET folks.

cc @mikeharder

**Comment by muratg** [comment]
@mikeharder Are we able to do this in dev branches now?

**Comment by mikeharder** [comment]
I believe so.  I think the next step is to start trying this in some repos, and if nothing fails then assume it's correct.

**Comment by muratg** [comment]
This is done.
