### ISSUE TITLE
Consistent startup experience for non-web apps.

### ISSUE THREAD

**Issue by dazinator** [aspnet/Hosting#1119]
I propose having a consistent startup experience for applications that are non Web Applications, I.e so we can still use the startup class approach, but not be tied to anything that is "web" oriented.

For example, in my xamarin app, which targets `NETStandard` the concept of a host is very useful, as the host can either be Android or Ios or a Uwp host. I can already create the startup class itself, that registers services, creates an `IServiceProvider` etc as that stuff is not web specific at all.

```
public class Startup
{
  public void RegisterServices(IServiceCollection services)
  {
            services.AddEntityFrameworkSqlite();           
            services.AddDbContext<TodoItemDatabase>();
            services.AddTransient<NavigationPage>((a) =>
            {
                var todolistpage = a.GetRequiredService<TodoListPage>();
                return new NavigationPage(todolistpage);
            });
            services.AddTransient<TodoListPage>();
            services.AddTransient<TodoItemPage>();            
  }
}
```

I can also derive an `IHostingEnvironment` to represent the host. However that does seem to have some web specific properties:

```
 public class HostEnvironment : IHostingEnvironment
    {

        public HostEnvironment()
        {

        }
        public string EnvironmentName { get; set; }
        public string ApplicationName { get; set; }
        public string WebRootPath { get => throw new NotImplementedException(); set => throw new NotImplementedException(); }
        public IFileProvider WebRootFileProvider { get => throw new NotImplementedException(); set => throw new NotImplementedException(); }
        public string ContentRootPath { get; set; }
        public IFileProvider ContentRootFileProvider { get; set; }

    }

```

Believe it or not, having an `IHostingEnvironment` abstraction for xamarin projects that run on potentially multiple hosts is useful. Also, having a `ContentRootFileProvider` is brilliant because it abstracts the fact that each platform must have a different root directory and provides a common abstraction for accessing files whether you are running on android or ios etc. Configuring Services on startup is also a common requirement of xamarin applications today built using DI. So as far as I can see if we could remove the web specifics, having a similar startup experience for non web apps to abstract away the host is very useful and allows greater code share between for example, services used within the website that use IHostingEnvironment and IFileProvider, can be re-used within your xamarin apps, adopting the same dependencies.

I don't like breaking changes but it would be better if the current `IHostingEnvironment` interface was named `IWebHostingEnvironment` so we could derive it from an `IHostingEnvironment` which would not have any web specific properties...

You may be able to tell where this is headed..

We could then derive `WebHostBuilder` from an `HostBuilder` - and allow `HostBuilder` to be used from non-web applications - i.e so that startup class approach could still be used - but there would be no middleware options. Essentially, all I can think it would need to do, is resolve the right startup class and invoke it.

Thoughts?

**Comment by dazinator** [comment]
Here is a branch in my sample repro where I would be looking to add a HostBuilder into the mix: https://github.com/dazinator/XamarinTodo/tree/morenetcore

**Comment by davidfowl** [comment]
Nice! Yes we have plans to do something like this but not for Xamarin applications. The intent was to decouple the host from *web* completely. We ran out of time doing this for 2.0.0 and will revisit for 2.1.0. The goal is to use it as the base for a couple of new things we want to do (like our non http story). 

Here's the current prototype: https://github.com/dotnet-architecture/Messaging/tree/dev/src/Microsoft.Extensions.Hosting

As for reusing the interfaces, we won't make breaking changes to them at this point (since we're mostly past 2.0.0). We'll likely introduce a set of parallel types without derivation then in 3.0.0 try to consolidate.

**Comment by dazinator** [comment]
Ah cool, glad to see it's already on the horizon. I like the look of it too, registering a delegate to participate in ConfigureServices seems fine and eliminates the need for a startup class as like you say, there is no middleware to configure, only services. I'll continue to watch this space then.

**Comment by dazinator** [comment]
> Yes we have plans to do something like this but not for Xamarin applications. 

As long as the new host builder stuff targets `NETStandard`, I think we should be able to use it from xamarin without you needing to add any explicit support in anywhere.. But I guess we shall see!
