### ISSUE TITLE
Deployment parameters should use IDictionary instead of IList for environment variables

### ISSUE THREAD

**Issue by JunTaoLuo** [aspnet/Hosting#1123]
https://github.com/aspnet/Hosting/blob/dev/src/Microsoft.AspNetCore.Server.IntegrationTesting/Common/DeploymentParameters.cs#L106 and https://github.com/aspnet/Hosting/blob/dev/src/Microsoft.AspNetCore.Server.IntegrationTesting/Common/DeploymentParameters.cs#L111 should be changed to be an `IDictionary<string,string>`.

This came out of a discussion from https://github.com/aspnet/Hosting/pull/1114#discussion_r124685631

**Comment by muratg** [comment]
@davidfowl will merge.
