### ISSUE TITLE
IWebHost breaking change

### ISSUE THREAD

**Issue by grahamehorner** [aspnet/Hosting#1124]
the change 62f74d5be0b1f8091742d2d8a3e88f3fdbd05ab2 to IWebHost interface is breaking change; including service-fabric-aspnetcore, please consider re-adding Start() and Stop() to the interface to remain backwards compatible with service-fabric and other code; marking them as obsolete but with out error.

These could simply call the StartAsync, StopAsync under the hood  
https://github.com/Azure/service-fabric-aspnetcore/issues/21

**Comment by Tratcher** [comment]
@DamianEdwards

**Comment by davidfowl** [comment]
We've decided to fix this.

**Comment by davidfowl** [comment]
@grahamehorner Have you tried service fabric with the latest build?

**Comment by grahamehorner** [comment]
I have tried with
 
Service Fabric SDK 2.6.220
Service Fabric Runtime 5.6.220

but I'm still having issues, even the template generated code wont run inside service fabric when targeting ASP.NET Core 2.0

however the expectation with regard IWebHost.Start() is no longer shown?

**Comment by grahamehorner** [comment]
Ok, now tried with both Service Fabric Stable nugget 2.6.220 & ASPNETCORE 2.0 preview 3
and Service Fabric 2.7.0-preview5718 and the service fails to start :'(  service shows the following

Error event: SourceId='System.FM', Property='State'.
Partition is below target replica or instance count.
fabric:/Application1/Web2 1 1 8b4e8ca4-a8ca-4f1b-9d49-6d7f102a79d1
  IB _Node_1 Up 131435483798573745
  (Showing 1 out of 1 replicas. Total available replicas: 0.)

**Comment by grahamehorner** [comment]
still having issues, so I've created a GitHub repo so you can see my experience of hosting ASPNETCORE 2.0 preview3 inside of Service Fabric; not sure where the root issue is yet; 

https://github.com/grahamehorner/ServiceFabric.ASPNETCORE2
