### ISSUE TITLE
Backport request: Add ConfigureAwait to prevent xunit hangs 

### ISSUE THREAD

**Issue by aensidhe** [aspnet/Hosting#1127]
Hi.

Can [this fix](https://github.com/aspnet/Hosting/pull/1019) be bckported to netcoreapp1.0 and/or 1.1 somehow? 

Thanks.

**Comment by davidfowl** [comment]
Add it where exactly?

**Comment by aensidhe** [comment]
Oh. I'm sorry then. Closing issue, thanks for clarification.
