### ISSUE TITLE
Service Fabric & ASP.NET Core 2.0 fails to run/start site

### ISSUE THREAD

**Issue by grahamehorner** [aspnet/Hosting#1128]
when creating a Service Fabric application using a ASP.NET Core 2.0 Stateless template,
the site fails to run under service fabric.

https://github.com/aspnet/Hosting/issues/1124
github repo https://github.com/grahamehorner/ServiceFabric.ASPNETCORE2.git

**Comment by campersau** [comment]
I think this is a Service Fabric issue.
See `Partition is below target replica or instance count.` https://github.com/Azure/service-fabric-issues/issues/39

**Comment by grahamehorner** [comment]
@campersau it may be, however I'm only seeing this when attempting to host ASPNET Core 2.0 applications; ASPNET Core 1.1 work fine; and the source code is exactly the same only expectation is that newer nugget packages having been referenced.

**Comment by benaadams** [comment]
Are you using the `All` package? Do you have the 2.0 runtime store installed on the nodes?

**Comment by grahamehorner** [comment]
@benaadams I'm running the ServiceFabric on a local developer install using a temple generated, then updated the nugget packages to preview3

**Comment by grahamehorner** [comment]
@campersau @benaadams I can confirm that ASPNET Core 1.1 template generated Stateless Web Applications work with Service Fabric using the Service Fabric v2.7-preview5718 and the issues I'm seeing are when using the ASPNET Core 2.0 preview2-final & preview3-latest, I've also added the Microsoft.NETCore.All   

I think this could be a result of a silent exception 

System.TypeLoadException: 'Method 'StartAsync' in type 'Microsoft.AspNetCore.Server.WebListener.MessagePump' from assembly 'Microsoft.AspNetCore.Server.WebListener, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' does not have an implementation.'

**Comment by grahamehorner** [comment]
more info switched to KestrelCommunicationListener and UseKestral and ServiceFabric reports the node
Error event: SourceId='System.FM', Property='State'.
Partition is below target replica or instance count.
fabric:/UtiliteamGB.Xanadu/ManagementPortal 1 1 da376ff5-82b5-45f2-b026-77544628f081
  IB _Node_3 Up 131435715660293288
  (Showing 1 out of 1 replicas. Total available replicas: 0.) 

however running the code as a Kestral console application gives 

Exception thrown: 'System.IO.IOException' in mscorlib.dll
An unhandled exception of type 'System.IO.IOException' occurred in mscorlib.dll
Failed to bind to address http://127.0.0.1:5000: address already in use.

as it is running in service fabric

**Comment by grahamehorner** [comment]
Debug output shows

Creating application...

...
The application has started.
Service Status:
fabric:/.. is not ready, 1 partitions remaining.

Service Status:
fabric:/... is ready.

The application is ready.
Finished executing script 'Get-ServiceFabricApplicationStatus'.
Time elapsed: 00:00:02.7763707
'ManagementPortal.exe' (CLR v4.0.30319: DefaultDomain): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_64\mscorlib\v4.0_4.0.0.0__b77a5c561934e089\mscorlib.dll'. Symbols loaded.
'...' (CLR v4.0.30319: DefaultDomain): Loaded 'C:\SfDevCluster\Data\_App\_Node_3\...'. Symbols loaded.
**The program '[14208] ...' has exited with code 0 (0x0).**
'...' (CLR v4.0.30319: DefaultDomain): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_64\mscorlib\v4.0_4.0.0.0__b77a5c561934e089\mscorlib.dll'. Symbols loaded.
'...' (CLR v4.0.30319: DefaultDomain): Loaded 'C:\SfDevCluster\Data\_App\_Node_3\...'. Symbols loaded.
The program '[12804] ManagementPortal.exe' has exited with code 0 (0x0).
'...' (CLR v4.0.30319: DefaultDomain): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_64\mscorlib\v4.0_4.0.0.0__b77a5c561934e089\mscorlib.dll'. Symbols loaded.
'...' (CLR v4.0.30319: DefaultDomain): Loaded 'C:\SfDevCluster\Data\_App\_Node_3\...'. Symbols loaded.

is interesting because a Thread.Sleep(Timeout.Infinite) shouldn't allow the application to exit ?

**Comment by benaadams** [comment]
> Failed to bind to address http://127.0.0.1:5000: address already in use.

You want to pass the address/port/FQDN that SF gives you and listen on that, not 127.0.0.1:5000 (hence port clashes)

**Comment by grahamehorner** [comment]
@benaadams yes; it does, it code is take the url, but still can't get the service to run? has anyone got a project running with ASPNET Core 2 ? using the template generated code ?

```
        protected override IEnumerable<ServiceInstanceListener> CreateServiceInstanceListeners()
        {
            return new ServiceInstanceListener[]
            {
                new ServiceInstanceListener(serviceContext =>
                {
                    return new  WebListenerCommunicationListener(serviceContext, "ServiceEndpoint", (url, listener) =>
                    {
                        ServiceEventSource.Current.ServiceMessage(serviceContext, $"Starting WebListener on {url}");
                        return new WebHostBuilder()
                            // .UseWebListener()
                            .UseHttpSys()
                            .ConfigureServices(
                                services => services
                                    .AddSingleton<StatelessServiceContext>(serviceContext))
                            .UseContentRoot(Directory.GetCurrentDirectory())
                            .UseStartup<Startup>()
                            .UseServiceFabricIntegration(listener, ServiceFabricIntegrationOptions.None)
                            .UseUrls(url)
                            .Build();
                    });
                })
            };
        }
```
        protected override IEnumerable<ServiceInstanceListener> CreateServiceInstanceListeners()
        {
            return new ServiceInstanceListener[]
            {
                new ServiceInstanceListener(serviceContext =>
                {
                    return new  WebListenerCommunicationListener(serviceContext, "ServiceEndpoint", (url, listener) =>
                    {
                        ServiceEventSource.Current.ServiceMessage(serviceContext, $"Starting WebListener on {url}");
                        return new WebHostBuilder()
                            // .UseWebListener()
                            .UseHttpSys()
                            .ConfigureServices(
                                services => services
                                    .AddSingleton<StatelessServiceContext>(serviceContext))
                            .UseContentRoot(Directory.GetCurrentDirectory())
                            .UseStartup<Startup>()
                            .UseServiceFabricIntegration(listener, ServiceFabricIntegrationOptions.None)
                            .UseUrls(url)
                            .Build();
                    });
                })
            };
        }

**Comment by grahamehorner** [comment]
this is a bit odd as I've not specified the port 5000 ?! anywhere

**Comment by grahamehorner** [comment]
Q: is there a symbol server for ASPNET Core 2.0 ?

**Comment by grahamehorner** [comment]
@benaadams @DamianEdwards @davidfowl The issue seems to be that Start, StartAsync doesn't run the service; however Run, RunAsync works?

**Comment by grahamehorner** [comment]
Just updated to the ASP.NET Core 2.0.0-preview3-26054 packages; and this looks to have resolved whatever the root cause was ?

**Comment by grahamehorner** [comment]
@benaadams @davidfowl @DamianEdwards I spoke too soon :'( trying to findout why with no code changes this broke this morning ?

**Comment by codematrix** [comment]
@grahamehorner did you get this running in ASP.NET Core 2.0? I'm having the same issue as you. I update my SF runtime with the latest and installed the .NET Core 2.0 Runtime & SDK.

I'm getting the following exception when trying to create the WebListener:

Method 'StartAsync' in type 'Microsoft.AspNetCore.Server.WebListener.MessagePump' from assembly 'Microsoft.AspNetCore.Server.WebListener, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' does not have an implementation.

  ```
 protected override IEnumerable<ServiceInstanceListener> CreateServiceInstanceListeners()
        {
            return new ServiceInstanceListener[]
            {
                new ServiceInstanceListener(serviceContext =>
                    new WebListenerCommunicationListener(serviceContext, "ServiceEndpoint", (url, listener) =>
                    {
                        ServiceEventSource.Current.ServiceMessage(serviceContext, $"Starting WebListener on {url}");
                        return new WebHostBuilder()
                                    .UseWebListener()
                                    .ConfigureServices(
                                        services => services
                                            .AddSingleton<StatelessServiceContext>(serviceContext))
                                    .UseContentRoot(Directory.GetCurrentDirectory())
                                    .UseStartup<Startup>()
                                    /* .UseApplicationInsights() */
                                    .UseServiceFabricIntegration(listener, ServiceFabricIntegrationOptions.None)
                                    .UseUrls(url)
                                    .Build();
                    }))
            };
        }
```

**Comment by jkotalik** [comment]
UseWebListener has been renamed to UseHttpSys. It seems that you are still referencing WebListener 1.0.0. See if that fixes anything?

**Comment by grahamehorner** [comment]
@jkotalik @codematrix yes, I managed to get everything working with some help for the team; it was some changes in the hosting packages that broke a few things, all good now.

BTW I'm personally using kestrel as this is now the default in the newer templates.

**Comment by codematrix** [comment]
@jkotalik @grahamehorner Awesome! UseHttpSys did the trick. UseKestrel() works just as well and will be using instead if this is the default.

Thanks for the speedy response. Much appreciated.

codematrix

**Comment by jkotalik** [comment]
Yeah, both Kestrel and HttpSys have the ups and downsides. I'd recommend checking out [this](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/?tabs=aspnetcore2x) to understand the difference between HttpSys and Kestrel.

**Comment by jkotalik** [comment]
Currently if neither UseKestrel or UseHttpSys is called, we default to UseKestrel.

**Comment by codematrix** [comment]
Hey @jkotalik thanks for the link. It's always good to understand the differences be web service implementations.

**Comment by apryiomka** [comment]
This is still an issue with Microsoft.AspNetCore.Server.WebListener, Version=1.1.2.0:
System.TypeLoadException: 'Method 'StartAsync' in type 'Microsoft.AspNetCore.Server.WebListener.MessagePump' from assembly 'Microsoft.AspNetCore.Server.WebListener, Version=1.1.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' does not have an implementation.'

**Comment by benaadams** [comment]
`Method does not have an implementation.` generally means you have mixed versions of libs; so for example Hosting is expecting a different version than the Server

**Comment by grahamehorner** [comment]
@codematrix @jkotalik the link has some old information with regards Kestrel and will no doubt be updated soon; kestrel is has been hardened so is now supported as for edge servers; it is also going to be allowed to run inside IIS (inproc) and will support HTTP2 (@DamianEdwards) tonights #live.asp.net

**Comment by apryiomka** [comment]
I am using the package Microsoft.ServiceFabric.AspNetCore.WebListener v 2.7.198 and it has dependency on
Microsoft.AspNetCore.Server.WebListener >= v 1.0.0. It doesn't work with neither 1.0.0 nor with 1.1.2.0. It is exactly the same error folks reported above.

**Comment by apryiomka** [comment]
Why is this thread closed if the issue has not been resolved? It seems an apparent bug to me.

**Comment by grahamehorner** [comment]
inside my ServiceFabric projects .csproj file is the following 
```
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore" Version="2.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc" Version="2.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Razor.ViewCompilation" Version="2.0.0" PrivateAssets="All" />
    <PackageReference Include="Microsoft.AspNetCore.StaticFiles" Version="2.0.0" />
    <PackageReference Include="Microsoft.ServiceFabric" Version="5.7.198" />
    <PackageReference Include="Microsoft.ServiceFabric.AspNetCore.Kestrel" Version="2.7.198" />
    <PackageReference Include="Microsoft.ServiceFabric.AspNetCore.WebListener" Version="2.7.198" />
    <PackageReference Include="Microsoft.ServiceFabric.Data" Version="2.7.198" />
    <PackageReference Include="Microsoft.ServiceFabric.Services" Version="2.7.198" />
    <PackageReference Include="Microsoft.VisualStudio.Web.BrowserLink" Version="2.0.0" />
  </ItemGroup>
```
I'm able to run both using Kestrel and WebListerner without any issues

**Comment by apryiomka** [comment]
Below is mine:
`
 <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore" Version="2.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc" Version="2.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Razor.ViewCompilation" Version="2.0.0" PrivateAssets="All" />
    <PackageReference Include="Microsoft.AspNetCore.StaticFiles" Version="2.0.0" />
    <PackageReference Include="Microsoft.Cloud.InstrumentationFramework" Version="3.0.6.52" />
    <PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="2.0.0" />
    <PackageReference Include="Microsoft.ServiceFabric" Version="5.7.198" />
    <PackageReference Include="Microsoft.ServiceFabric.AspNetCore.Kestrel" Version="2.7.198" />
    <PackageReference Include="Microsoft.ServiceFabric.AspNetCore.WebListener" Version="2.7.198" />
    <PackageReference Include="Microsoft.ServiceFabric.Data" Version="2.7.198" />
    <PackageReference Include="Microsoft.ServiceFabric.Services" Version="2.7.198" />
    <PackageReference Include="Microsoft.VisualStudio.Web.BrowserLink" Version="2.0.0" />
  </ItemGroup>
`
I can run Kastrel, but not WebListener:
`
//this works
return new WebHostBuilder()
                            .UseKestrel()
                            .ConfigureServices(
                                services => services.AddSingleton(serviceContext))
                            .UseContentRoot(Directory.GetCurrentDirectory())
                            .UseServiceFabricIntegration(listener, ServiceFabricIntegrationOptions.None)
                            .UseStartup<Startup>()
                            .UseUrls(url)
                            .Build();
                        }))
//this fails
return new WebHostBuilder()
                            .UseWebListener()
                            .ConfigureServices(
                                services => services.AddSingleton(serviceContext))
                            .UseContentRoot(Directory.GetCurrentDirectory())
                            .UseServiceFabricIntegration(listener, ServiceFabricIntegrationOptions.None)
                            .UseStartup<Startup>()
                            .UseUrls(url)
                            .Build();
`

**Comment by Tratcher** [comment]
@apryiomka WebListener was renamed to HttpSys in 2.0.

**Comment by muratg** [comment]
@apryiomka In 2.0.0 wave, WebListener is not HttpSys. The issue is resolved in 2.0.

**Comment by apryiomka** [comment]
HttpSys is a separate package. What do you "renamed"?
https://www.nuget.org/packages/Microsoft.AspNetCore.Server.HttpSys/

**Comment by apryiomka** [comment]
There is no 2.0 version for WebListener https://www.nuget.org/packages/Microsoft.AspNetCore.Server.WebListener/ v1.1.2 is the latest

**Comment by muratg** [comment]
@apryiomka @Tratcher and I are talking about our webserver rename. Please see https://github.com/aspnet/Announcements/issues/211 for the rename.

The problem seems to be with the package `Microsoft.ServiceFabric.AspNetCore.WebListener` (this is the specific ServiceFabric package).

@glennc Do you know if ServiceFabric folks plan to release a 2.0.0 version with HttpSys support?

@apryiomka are you able to use Kestrel instead?

**Comment by apryiomka** [comment]
@muratg, can i use Kestrel with internet facing app/service? It works locally with my local cluster, but doesn't seem to work when i deploy to azure cluster. If i remote the node, i can access it from the node directly and local ip address (127.0.0.1:9012), but if i try http://clustername.centralus.cloudapp.azure.com:9012, it doesn't work. I am more than happy with stick with Kestrel, but i don't seem to be able to access it from the internet.

**Comment by grahamehorner** [comment]
@apryiomka @codematrix @muratg I think some confusion here is due to the naming of the package; but the team are aware of this https://github.com/Azure/service-fabric-aspnetcore/issues/15

**Comment by RyanElfman** [comment]
I can successfully use Kestrel as well.

**Comment by raviganesan** [comment]
Two Changes Needed to resolve it:

1. Use this package Microsoft.AspNetCore.Server.HttpSys  (I used version 2.0.2)
2. In WebHostBuilder, replace .UseWebListener() with .UseHttpSys()

I hope you already know how to configure ApplicationManifest.xml and ServiceManifest.xml to bind SSL policy. if not see this link which has old implementations but the xml configs are still same : https://dzimchuk.net/setting-up-https-endpoints-in-asp-net-core-services-in-service-fabric/
