### ISSUE TITLE
ASPNET Core 2.0 - ServiceFabric IPv6

### ISSUE THREAD

**Issue by grahamehorner** [aspnet/Hosting#1131]
building a ASPNET Core 2.0 Stateless Web App/API to shows the binds http://[::]:8868 as the endpoint; clicking the service fabric link fails to connect to the App/API, no IPv4 is shown, using IPv4 & localhost:8868 and 127.0.0.1:8868 works as expected.  Issue is that using ASPNET Core 2.0 has impacted the ServiceFabric explorer UI in that  endpoint link don't work as excpeted

**Comment by Tratcher** [comment]
How is this an ASP.NET Core issue as opposed to a ServiceFabric issue?

**Comment by grahamehorner** [comment]
@Tratcher this is an issue where ASP.NET Core 2.0 behaves differently to previous release when running under ServiceFabric using the same ServiceFabric SDK.

**Comment by davidfowl** [comment]
I'm looking into this. I can reproduce it. It's a combination of things. The way we report addresses via the `IServerAddressesFeature` is different in kestrel.

**Comment by vturecek** [comment]
https://github.com/Azure/service-fabric-aspnetcore/blob/develop/src/Microsoft.ServiceFabric.AspNetCore/AspNetCoreCommunicationListener.cs#L152

So it doesn't return "http://+" anymore when you open on http://+? What do you get now, IP/host?

**Comment by davidfowl** [comment]
@vturecek yea I took a look at this and we return `[::]` now from kestrel. How hard would it be to ship a new version that fixed this?

**Comment by davidfowl** [comment]
Thinking about this some more I think we should make this more generally robust.

**Comment by davidfowl** [comment]
Let's discuss this on https://github.com/Azure/service-fabric-aspnetcore/issues/6
