### ISSUE TITLE
Setting applicationName (and therefore UseStartup) does not work in IHostingStartup.Configure

### ISSUE THREAD

**Issue by moozzyk** [aspnet/Hosting#1140]
The following HostingStartup class:

```C#
    public class HostingStartup : IHostingStartup
    {
        public void Configure(IWebHostBuilder builder)
        {
            builder.UseStartup(typeof(Startup));
        }
    }
```
is not enough to configure the Startup: 
```
System.ArgumentException : A valid non-empty application name must be provided.
Parameter name: applicationName
	at Microsoft.AspNetCore.Hosting.Internal.HostingEnvironmentExtensions.Initialize(IHostingEnvironment hostingEnvironment, String applicationName, String contentRootPath, WebHostOptions options)
	at Microsoft.AspNetCore.Hosting.WebHostBuilder.BuildCommonServices(AggregateException& hostingStartupErrors)
        at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
	at Microsoft.AspNetCore.SignalR.Tests.Common.ServerFixture.StartServer()
	at Microsoft.AspNetCore.SignalR.Tests.Common.ServerFixture..ctor()
```

The issue is the options are created before the startup assemblies are being called. This is also when `WebHostOptions.ApplicationName` is initialized meaning that changing/setting the applicationName in IHostingStartup.Configure has no effect. This renders UseStartup in IHostingStartup.Configure unusable.

**Comment by kierenj** [comment]
I'm getting this message after an upgrade to 2.0 (my approach was working in 1.0/1.1).  For anyone else wondering the upgrade path for if you didn't need to do this before, refer to David's comment here:

https://github.com/aspnet/Hosting/issues/1137#issuecomment-323234886

To set this manually, it's: `.UseSetting(WebHostDefaults.ApplicationKey, typeof(AspNetCoreStartup).GetTypeInfo().Assembly.FullName)`

**Comment by JunTaoLuo** [comment]
This exception should no longer occur after https://github.com/aspnet/Hosting/issues/1137 as we now fallback to the entry assembly name if none is specified. However, the fallback may not be entirely accurate as the Startup type may originate from a different assembly. As noted above, we resolve the `ApplicationName` using the host configuration before startup assemblies are called. One approach we could try is to re-examine the assembly name in the host configuration after the startup assemblies are executed and update the `ApplicationName` property on the `WebHostOptions` if it is different. Throughts @davidfowl @Tratcher ?

**Comment by JunTaoLuo** [comment]
The main issue here is that the value of `ApplicationName` on the `HostingEnvironment` in the DI container does not have the correct value if `UseStartup` is called from a startup assembly.

The host and application configuration has the correct value but since the `HostingEnvironment` is constructed with the `WebHostOption` that was created before startup assemblies are called, it does not have the correct value. To avoid requiring the user to call `.UseSetting` explicitly on the `WebHostBuilder` we can automatically update the application name after hosting startups here: https://github.com/aspnet/Hosting/blob/dev/src/Microsoft.AspNetCore.Hosting/WebHostBuilder.cs#L237 by adding a line like:
```
_hostingEnvironment.ApplicationName = _config[WebHostDefaults.ApplicationKey];
```

Thoughts @Tratcher ?

**Comment by davidfowl** [comment]
I’m pretty sure we don’t care about fixing this bug. There’s no real scenario here.

**Comment by Tratcher** [comment]
I agree with Fowler, there's no compelling user scenario to fix this for.

**Comment by jstensved** [comment]
There is a user scenario in unit testing.

This is really annoying when doing unit tests. If you have a Startup with mocks you want to register an instance of Startup (not the type) to be able to see if certain services where called.

**Comment by davidfowl** [comment]
This specific issue has nothing to do with IStartup, this is about another feature we have that really isn't user facing at all.

@jstensved you should file another bug with specifics.
