### ISSUE TITLE
WebHost Events

### ISSUE THREAD

**Issue by deinok** [aspnet/Hosting#1147]
Is there any way to add events to a WebHost?
I want to detect the change of state of the server. Run some actions when the server has been initialized, started, disconnected, etc...

**Comment by davidfowl** [comment]
You can use `IApplicationLifetime` to get lifetime events https://github.com/aspnet/Hosting/blob/f08d1934890785798b03134e8fbceeb3d4448791/src/Microsoft.AspNetCore.Hosting.Abstractions/IApplicationLifetime.cs.

**Comment by deinok** [comment]
Thanks @davidfowl I have searched for this but didnt see anything. Closing this.
