### ISSUE TITLE
Q: WebHostBuilder

### ISSUE THREAD

**Issue by grahamehorner** [aspnet/Hosting#1149]
Is there a way to find out which listener the developer is using prior to calling the WebHostBuilder's build?
I would like to determine the listener so my code can under some conditions branch or do specific actions.

**Comment by davidfowl** [comment]
> Is there a way to find out which listener the developer is using prior to calling the WebHostBuilder's build?

Extension methods can do whatever they want. You can look at the `IServer` in the `IServiceCollection` but that's just a hack.

> I would like to determine the listener so my code can under some conditions branch or do specific actions.

Why?

**Comment by grahamehorner** [comment]
I'm looking at building sites/services that can easily be deployed to a physical host (dev), docker, service fabric and without the need to change any code, given service fabric requires a wrapper in the from of WebListenerCommunicationListener, KestrelCommunicationListener etc. it would be good to know which listener(s) the developer selected, so many library can do the necessary marshalling/wrapping of the listener to service fabric.

**Comment by grahamehorner** [comment]
also I'm really a fan of the Thread.Sleep(Timeout.Infinite); in the Main() for ServiceFabric TBH

**Comment by davidfowl** [comment]
There's no good way to know that.

**Comment by grahamehorner** [comment]
😭 it would be a good feature to have in my opinion, what are your thoughts is it at all possible to do?

**Comment by davidfowl** [comment]
I think it's a bad feature overall, the entire point of having a server abstraction is so that library authors never need to know which server is running. It's unfortunate that service fabric has specific libraries for WebListener and Kestrel.

**Comment by grahamehorner** [comment]
I did raise an issue with regards exactly that with the ServiceFabric team, however it got closed 😭 was hoping to try and solve it myself or at least try and suggest some solution that didn't require ServiceFabric to know which listeners explicitly

**Comment by cwe1ss** [comment]
@grahamehorner Not sure if I fully understand your request but maybe this helps: I built a separate SF hosting library some time ago that makes SF registration optional on startup - so you can start it with `dotnet run` and http://localhost:5000 while you're developing and when you deploy to SF, it will get the URL from SF. [You can find more details here](https://github.com/c3-ls/ServiceFabric-Http/wiki/Stateless-ASP.NET-Core-Host).

But of course, this only works as long as you don't require any SF functionality in your app (e.g. a stateful service, etc)
