### ISSUE TITLE
Logging instances are no longer shared between "HostingServices" and "ApplicationServices"

### ISSUE THREAD

**Issue by cwe1ss** [aspnet/Hosting#1150]
Due to the logging DI changes, the ILoggerFactory instance is no longer shared between the "HostingServices" and "ApplicationServices" service providers. Instead they both create their own instances.

One visible problem of this is, when the `ILoggerFactory` is passed to the constructor of a Startup-class as this [uses "HostingServices"](https://github.com/aspnet/Hosting/blob/dev/src/Microsoft.AspNetCore.Hosting/Internal/WebHost.cs#L169). 

`Startup.Configure` however [is resolved from "ApplicationServices"](https://github.com/aspnet/Hosting/blob/dev/src/Microsoft.AspNetCore.Hosting/Internal/WebHost.cs#L179) so you will even get two different instances for the ctor and this method with the following example:

```csharp
public class Program
{
    public static void Main(string[] args)
    {
        new WebHostBuilder()
            .UseKestrel()
            .UseContentRoot(Directory.GetCurrentDirectory())
            .UseStartup<Program>()
            .Build()
            .Run();
    }

    private readonly ILoggerFactory _loggerFactory;

    public Program(ILoggerFactory loggerFactory)
    {
        _loggerFactory = loggerFactory;

        // This only configures the instance from "HostingServices"
        _loggerFactory.AddConsole(includeScopes: true);
    }

    public void Configure(IApplicationBuilder app, ILoggerFactory loggerFactory)
    {
        if (loggerFactory != _loggerFactory)
            throw new InvalidOperationException("Different instances");

        app.Run((context) =>
        {
            // This would not be written as the instance from "ApplicationServices" has not been configured.
            var logger = loggerFactory.CreateLogger<Program>();
            logger.LogInformation("Hello World");
            return Task.CompletedTask;
        });
    }
}

**Comment by BrennanConroy** [comment]
@pakrym

**Comment by cwe1ss** [comment]
Given that providers can now inject services with DI, I think that logging instances can only be created from "ApplicationServices". Imagine a logger provider that injects `IHttpContextAccessor` to enrich logs with request data. If the logger were created from "HostingServices", it would never actually get the HttpContext as it would work with a separate singleton.

How about the following solution?
* Do NOT call "services.AddLogging" [in BuildCommonServices](https://github.com/aspnet/Hosting/blob/dev/src/Microsoft.AspNetCore.Hosting/WebHostBuilder.cs#L255)
* Instead, call it in "[AddApplicationServices](https://github.com/aspnet/Hosting/blob/dev/src/Microsoft.AspNetCore.Hosting/WebHostBuilder.cs#L303)"
* Ensure that no internal code tries to resolve any logging types from "HostingServices" (maybe there's none anyway)

This would mean, that it's no longer possible to inject logging types into `Startup`-constructors as they are no longer registered with "HostingServices". It's somehow logical as providers could need types that are set up in `ConfigureServices`. 

This would be a runtime breaking change for people who used this but it would fail immediately. The fix would be to instead inject the type into `Startup.Configure`.

**Comment by cwe1ss** [comment]
Just a quick ping. I think this is important for 2.0 since everyone who's accessing a logging component in the `Startup` constructor will run into this issue. Not sure how many these are, but there's even [documentation](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/startup#services-available-in-startup) that says that these components are available in the constructor.

**Comment by pakrym** [comment]
Unfortunately this would not make it into 2.0, we are to far in release process at this point.

**Comment by Cassaba** [comment]
After upgrade to net core 2.0 from 1.1, I cannot get any log information into command window now.
is it due to the logging DI changed?

`public static void Main(string[] args)
        {
            BuildWebHost(args).Run();
        }

        public static IWebHost BuildWebHost(string[] args) =>
            WebHost.CreateDefaultBuilder(args)
                .UseStructureMap()
                .UseStartup<Startup>()                
                .Build();`

**Comment by cwe1ss** [comment]
@Cassaba AFAIU the fix is to NOT inject `ILoggerFactory` into your Startup-constructor. Instead you should use the new `IWebHostBuiler.ConfigureLogging` method in your Program.cs to configure your logging providers. If you need an `ILogger` instance in your `Startup`, you can inject `ILoggerFactory` (or `ILogger<...>`) into your `Startup.Configure` method - there it will be resolved from the correct service provider.
(Note that this means that you currently can not write logs in your Startup-constructor /Startup.ConfigureServices code)

**Comment by muratg** [comment]
cc @Tratcher @davidfowl

**Comment by pakrym** [comment]
@cwe1ss there are things that might run in hosting level, run after hosting container was created and want to log (IServers IHostingStartup implementations etc.) so completely disabling it might not be the best solution.

**Comment by cwe1ss** [comment]
True. Maybe it’s best to try to resolve this with the new generic host?!

**Comment by pakrym** [comment]
@cwe1ss new generic host has only one container instance so this problem should not happen there.

**Comment by pakrym** [comment]
@muratg no work here for 2.X

**Comment by muratg** [comment]
Closing this one per the discussion.

**Comment by kevinlo** [comment]
I am using the ASP.NET Core 2.1, but I still see the ILoggerFactory passed to the Startup constructor is different from the one passed to Configure.

@Could you please tell where that 

>

**Comment by Rinsen** [comment]
@kevinlo
But that's not valid for the WebHost as I understand the problem. I don't think this can be fixed in any easy way as one di container is used for bootstrap and one for running services.

**Comment by kevinlo** [comment]
@Rinsen Thanks for your reply.  I thought it is fixed as this issue is closed.

So, I still need to add my ILoggerProvider at both places then.

**Comment by Rinsen** [comment]
Send it in via the configure method instead of ctor to have just one, that's the solution I decided to take at least as suggested by @cwe1ss
