### ISSUE TITLE
Microsoft.AspNetCore.TestHost v1.1.2 encoding forward slash makes no difference

### ISSUE THREAD

**Issue by PawelTroka** [aspnet/Hosting#1155]
It was already shortly discussed in https://github.com/aspnet/Mvc/issues/2826 where @davidfowl suggested that the issue I am encountering is only happening on TestHost. And yes, he is right - it works correctly when hosted and invoked through web browser or any web client for that matter. 

It is failing however in my integration tests where I am using Microsoft.AspNetCore.TestHost v1.1.2 and Microsoft.AspNetCore.WebUtilities v1.1.2. Please notice that my WebApi and WebApi.IntegrationTests are AspNetCore 1.1 but are targeting net461 (due to some of my libraries not yet ported).

Repro:
Unit test:
https://github.com/PawelTroka/Computator.NET/blob/master/Computator.NET.WebApi.IntegrationTests/CalculateApiTests.cs#L49
Should go through route:
real/{equation}/{x} from method:
https://github.com/PawelTroka/Computator.NET/blob/master/Computator.NET.WebApi/Controllers/CalculateController.cs#L32
But because encoding forward slash makes no difference it is going through different route:
real/{equation}/{x}/{customFunctionsCode} from the same method

In images:
When run through browser everything is ok:
![image](https://user-images.githubusercontent.com/11928766/28869021-a7dc70ac-777b-11e7-914a-cda7eddf54f4.png)
![image](https://user-images.githubusercontent.com/11928766/28868995-934b15a8-777b-11e7-9b47-5edbfea9680a.png)

But when run on TestHost, encoding forward slash really makes no difference:
![image](https://user-images.githubusercontent.com/11928766/28869103-f6594174-777b-11e7-857d-61a99ac2d914.png)

**Comment by Tratcher** [comment]
Here's the code causing the un-escaping:
https://github.com/aspnet/Hosting/blob/44272ca2ba7082dd31c3de0ef9d5b5a400db1b78/src/Microsoft.AspNetCore.TestHost/ClientHandler.cs#L140
https://github.com/aspnet/HttpAbstractions/blob/057fc816fab1062700959cdaad2a32e9d85efca6/src/Microsoft.AspNetCore.Http.Abstractions/PathString.cs#L191
I'll move this bug over to HttpAbstrations. There should be a better way to unescape everything but %2F.

**Comment by Tratcher** [comment]
This issue was moved to aspnet/HttpAbstractions#912
