### ISSUE TITLE
ASP.Net 1.1 Core app - HTTP Error 502.5 - Process Failure - Sub application(.NET Framework) under .Net Core root site won't run

### ISSUE THREAD

**Issue by ToMakeSense** [aspnet/Hosting#1156]
I have an ASP.Net Core application running as the root site, and I want to add an ASP.NET Framework WebApi  application as the sub site, but it doesn't work. I don't know if it's possible.

**Error page content in the browser**
> Common causes of this issue:
The application process failed to start
The application process started but then stopped
The application process started but failed to listen on the configured port

**Error log under Eventlog**
> Application 'MACHINE/WEBROOT/APPHOST/Site name/Application Alias name' with physical root 'C:\{PATH}\' failed to start process with commandline '"dotnet" .\application.dll', ErrorCode = '0x80004005 : 80008081.

I had read topic under this link [Host on Windows with IIS](https://docs.microsoft.com/en-us/aspnet/core/publishing/iis), but didn't find the solution.

**Comment by Tratcher** [comment]
It can work. The trick is that web.config settings are inherited from the root site so in the sub application's web.config you have to remove the aspnetcore handler.
@shirhatti this is becoming an FAQ that should get doc'd.

**Comment by ToMakeSense** [comment]
@Tratcher Sorry, I am not get you very much, I know little about the deployment with IIS, I am out of work, will check it tomorrow. thanks in advance!

**Comment by Tratcher** [comment]
Try this:
```
<configuration>
  <system.webServer>
    <handlers>
      <remove name="aspNetCore" />
    </handlers>
  </system.webServer>
</configuration>
```

**Comment by shirhatti** [comment]
https://docs.microsoft.com/en-us/aspnet/core/publishing/iis#configuration-of-sub-applications

**Comment by ToMakeSense** [comment]
@shirhatti  In fact I attached the parent link of yours at the beginning of this issue request. but topic about **configuration-of-sub-applications** is not enough. thanks anyway, you are very kind.

**Comment by ToMakeSense** [comment]
@Tratcher thanks, It works!!! And I test **the opposite of my issue**, that is to say, ASP.NET Framework WebApi  running as a root site, and ASP.Net Core application as a sub site, it works too.

**Comment by ToMakeSense** [comment]
I 'd like add more about this, hope it will help to other people who had the same problem.

- ASP.NET Core application runs as the root site, ASP.NET Framework application as the sub site
> web.config in ASP.NET Core application
`<system.webServer>
<handlers>
  <add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModule" resourceType="Unspecified" />
</handlers>
<aspNetCore processPath="dotnet" arguments=".\XXX.dll" stdoutLogEnabled="false" stdoutLogFile=".\logs\stdout" />
</system.webServer>`

> web.config in ASP.NET Framework application
`<system.webServer>
<handlers>
  <remove name="aspNetCore"/>
  <remove name="ExtensionlessUrlHandler-Integrated-4.0" />
  <remove name="OPTIONSVerbHandler" />
  <remove name="TRACEVerbHandler" />
  <add name="ExtensionlessUrlHandler-Integrated-4.0" path="*." verb="*" type="System.Web.Handlers.TransferRequestHandler" preCondition="integratedMode,runtimeVersionv4.0" />
</handlers>
</system.webServer>`

- ASP.NET Framework application runs as the root site, ASP.NET Core application as the sub site
> web.config in ASP.NET Framework application
`<system.webServer>
<handlers>
  <remove name="ExtensionlessUrlHandler-Integrated-4.0" />
  <remove name="OPTIONSVerbHandler" />
  <remove name="TRACEVerbHandler" />
  <add name="ExtensionlessUrlHandler-Integrated-4.0" path="*." verb="*" type="System.Web.Handlers.TransferRequestHandler" preCondition="integratedMode,runtimeVersionv4.0" />
</handlers>
</system.webServer>`

> web.config in ASP.NET Core application
`<system.webServer>
  <handlers>
    <remove name="ExtensionlessUrlHandler-Integrated-4.0" />
    <add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModule" resourceType="Unspecified" />
  </handlers>
  <aspNetCore processPath="dotnet" arguments=".\XXX.dll" stdoutLogEnabled="false" stdoutLogFile=".\logs\stdout" />
</system.webServer>`

**Comment by ToMakeSense** [comment]
@Tratcher Get more meaningful information on wikipedia -- [Internet Information Services](https://en.wikipedia.org/wiki/Internet_Information_Services), Quoted below:

> IIS 7.0 has a modular architecture. **Modules, also called extensions, can be added or removed individually so that only modules required for specific functionality have to be installed.** IIS 7 includes native modules as part of the full installation. These modules are individual features that the server uses to process requests and include the following

It makes me understand the word **module** deeper, In addition, I think it's kind of bug of the solution above. as I found, a sub-site(Application) has it's own application pool. when the root-site visit the sub-site, IIS should switch the module based on the setting  of  sub-site's application pool.
