### ISSUE TITLE
[Q] Using Microsoft.AspNetCore.TestHost.TestServer for purposes other than integration testing

### ISSUE THREAD

**Issue by BadriL** [aspnet/Hosting#1157]
Is it okay to use `Microsoft.AspNetCore.TestHost.TestServer` for purposes other than integration testing? I want to run `HttpRequestMessage` through an ASP.NET Core pipeline like so, from an Azure function. 

```csharp
var ts = new TestServer(new WebHostBuilder().UseStartup<Startup>());
var client = ts.CreateClient();
var resp = await client.SendAsync(req);
```
The above code can run in parallel by multiple threads but I'm not sharing `TestServer` instance.

**Comment by davidfowl** [comment]
Thats pretty cool! The test host is a test host though, it's not optimized at all and not meant to be used in a production environment. There's likely bugs around error handling and missing features (like ip address).
