### ISSUE TITLE
Microsoft.AspNetCore.Hosting.Abstractions not supported on Android

### ISSUE THREAD

**Issue by lennoncork** [aspnet/Hosting#1158]
We have an application that we are building for both windows (.NET Framework) and android (using .NETStandard and Xamarin) and we would like to use ASP NET Core to produce a REST interface. Understand there is work to be done, but the current issue is that the Hosting.Abstraction nuget is not supported on android/mono. 

> Error Exception while loading assemblies: System.IO.FileNotFoundException: Could not load assembly 'Microsoft.AspNetCore.Hosting.Abstractions, Version=1.1.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. Perhaps it doesn't exist in the Mono for Android profile?
> File name: 'Microsoft.AspNetCore.Hosting.Abstractions.dll'
>    at Java.Interop.Tools.Cecil.DirectoryAssemblyResolver.Resolve(AssemblyNameReference reference, ReaderParameters parameters)
>    at Java.Interop.Tools.Cecil.DirectoryAssemblyResolver.Resolve(AssemblyNameReference reference)
>    at Xamarin.Android.Tasks.ResolveAssemblies.AddAssemblyReferences(DirectoryAssemblyResolver resolver, ICollection`1 assemblies, AssemblyDefinition assembly, Boolean topLevel)
>    at Xamarin.Android.Tasks.ResolveAssemblies.Execute(DirectoryAssemblyResolver resolver)	App.Android

**Comment by davidfowl** [comment]
I'm not familiar with what the issue here might be. Are you running on a version of Xamarin that supports .NET Standard?

**Comment by JonDouglas** [comment]
@lennoncork Can you please file this issue in Xamarin's Bugzilla?

https://bugzilla.xamarin.com/enter_bug.cgi?product=Android

Please include the minimal reproduction steps or a sample project that demonstrates the issue.

You'll also want to include your current [version information](https://developer.xamarin.com/guides/cross-platform/troubleshooting/questions/version-logs/#version-information).

If you need further help on reporting this issue, see our [bug writing guidelines](https://bugzilla.xamarin.com/page.cgi?id=bug-writing.html).

As a quick test, I was able to successfully include the NuGet to a Xamarin.Android project running 15.2. However this issue might be at runtime which I haven't tried to invoke any code from the NuGet:

https://www.nuget.org/packages/Microsoft.AspNetCore.Hosting.Abstractions/

Thank you!

**Comment by lennoncork** [comment]
@JonDouglas Thank you for the quick reply, my problem was assuming that a project reference would result in the android application inheriting the nuget dependencies of an intermediate netstandard library. I had to add nuget packages manually to the Android app until eventually trying "Microsoft.AspNetCore.Mvc.ViewFeatures" which has a dependency (somewhere down the line) on "Microsoft.Win32.Registry".

**Comment by marek-safar** [comment]
That still means there is Microsoft.Win32.Registry dependency bug in .nuspec (don't know which nuget needs it and it can be somewhere deep in dependency tree)
