### ISSUE TITLE
HttpContext.ApplicationServices should always be set

### ISSUE THREAD

**Issue by davidfowl** [aspnet/Hosting#116]
Today we only set it if the ContainerMiddleware sets it. It should be set to IApplicationBuilder.ApplicationServices by default.

**Comment by glennc** [comment]
@davidfowl Is this still an issue?

**Comment by davidfowl** [comment]
Yes it is

**Comment by davidfowl** [comment]
Yes it is

**Comment by HaoK** [comment]
This should get fixed as part of the auto scoping change I believe
