### ISSUE TITLE
Question: Request-Id, X-Request-Id and CorrelationId

### ISSUE THREAD

**Issue by kimbell** [aspnet/Hosting#1164]
When browsing through the code, I see that you look for the Request-Id in the HTTP headers and assign this value to the CorrelationId value that gets logged as part of structured event logging. 

Why are you using different names?

When searching for information related to correlation id's, the headers 'X-Request-Id' and 'X-Correlation-Id' come up a lot. Why are you not looking for those headers?

**Comment by davidfowl** [comment]
> When searching for information related to correlation id's, the headers 'X-Request-Id' and 'X-Correlation-Id' come up a lot. Why are you not looking for those headers?

The feature that was done as part of 2.0 was flowing a specific request id that HttpClient flows. See more details here:

https://github.com/dotnet/corefx/blob/master/src/System.Diagnostics.DiagnosticSource/src/ActivityUserGuide.md

**Comment by kimbell** [comment]
Interesting, that opened up a whole new world of potential possibilities. 

Where in the ASP.NET Core framework are you using Activities? From my exploring, I've only found usage in the Hosting repository. Could give us some idea of the typical use-cases. There seems to be a number of things that need setting up, so it might be overkill for some scenarios.

**Comment by davidfowl** [comment]
It's only used in the hosting repository and built into the .NET Core HTTP Client. 

Hosting - https://github.com/aspnet/Hosting/blob/456957bf57901da81d943166fb7f0b4725e7b45e/src/Microsoft.AspNetCore.Hosting/Internal/HostingApplicationDiagnostics.cs
HTTP Client - https://github.com/dotnet/corefx/blob/3e72ee5971db5d0bd46606fa672969adde29e307/src/System.Net.Http/src/System/Net/Http/DiagnosticsHandler.cs

Here's another document about how it works with HTTP Client - https://github.com/dotnet/corefx/blob/c082d21361608e3cc2ea3cddd90c2a0306828002/src/System.Net.Http/src/HttpDiagnosticsGuide.md

Here's a document about the correlation protocol - https://github.com/dotnet/corefx/blob/master/src/System.Diagnostics.DiagnosticSource/src/HttpCorrelationProtocol.md

The end to end experience that was delivered in 2.0 was distributed tracing application insights. If you use ASP.NET Core with the app insights SDK outbound HTTP calls will be correlated between your ASP.NET services by default. It's possible to wire things to other systems but it is a bit involved.

What are you trying to do?

**Comment by kimbell** [comment]
I'm currently working for a client that has a system that has evolved over many years. On the .NET side, it's a true history of .NET; there are still a lot of ASMX services in use. There are also various generations of Java services, so it's not a Microsoft only solution. 

The current architecture contains a front end layer mostly written in various .NET technology (MVC and WebForms). This layer calls 'the big magic bus' written i Java that basically orchestrates calls to other services to get the data required. The bus calls other CRUD based services to access data; a lot of these are written in legacy .NET technology. 

The decision has been made to modernize this solution, both from a business and technology standpoint. So far the company has been focusing on Europe, but are spreading out into the world. The idea is to chip away at the bus and move things over to a micro-service model. In time parts of the solution will be moved into the cloud to become geographically nearer to the customers. 

As part of this work, we have started looking into how we can standardize HTTP headers so that we can trace information through the whole stack. From the UI perspective, there may be one business operation that results in multiple calls to different services. Some of these services may act as orchestrators in that they call other services again. 

We need multiple types of correlation id's in order to match the requests over multiple systems. I remember you guys mentioning logging av Correlation id at NDC Oslo, so I wanted to see how it was implemented. What can we get out of the box and what do we have to set up ourselves. We have the Java angle also to consider, so that might affect things. 

It's still early days, we have just started talking about these things. 

From a logging perspective I'm leaning towards the ILogger.BeginScope() to augment all entries with common data. We are using Serilog with the ELK stack at the moment. 

Haven't done that much research into how we pass input information to child calls, the Activity.Baggage system might be something we can use.

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
