### ISSUE TITLE
ASP.NET Core 2 IWebHostBuilder.BuildWebHost throws FileNotFound Exception Due to Dependency Version

### ISSUE THREAD

**Issue by WilliamWsyHK** [aspnet/Hosting#1167]
In `Main.cs`, we have the the following method since this is generated from ASP.NET Core 2.0 codegen.
``` CSharp
public static IWebHost BuildWebHost(string[] args) =>
        WebHost.CreateDefaultBuilder(args)
            .UseStartup<Startup>()
            .Build();
```

But it throws exception,
``` CSharp
發生 System.IO.FileLoadException
  HResult=0x80131040
  Message=Could not load file or assembly 'System.Diagnostics.DiagnosticSource, Version=4.0.2.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
  Source=Microsoft.AspNetCore.Hosting
  StackTrace: 
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.BuildCommonServices(AggregateException& hostingStartupErrors)
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at Project.Program.BuildWebHost(String[] args) in C:\path\Program.cs:line 27
   at Project.Program.Main(String[] args) in C:\path\Program.cs:line 23

```

This worst thing is that this WebHosting is calling `System.Diagnostics.DiagnosticSource` of version `4.0.2.1`, while in NuGet I saw the version should be `4.4.1`, link https://preview.nuget.org/packages/Microsoft.AspNetCore.Hosting/.

The version this project is using is `Microsoft.AspNetCore.All` 2.0.0 (just released a few days ago!)

Also there is a unresolved SO question out there, [ref] link https://stackoverflow.com/questions/45464126/signalr-core-w-asp-net-core-2-0-in-vs-2017-15-3-could-not-load-file-or-assembly.

**Comment by WilliamWsyHK** [comment]
Also found some clues at SignalR repo, aspnet/SignalR#690, and it requires an preview version of ASP.NET Core 2.1, which I don't want to use preview for that. Any suggestions?

**Comment by davidfowl** [comment]
Wait a little bit.

**Comment by WilliamWsyHK** [comment]
Actually I don't use SignalR, but just the original `Microsoft.AspNetCore.All.dll` `2.0.0`.

**Comment by davidfowl** [comment]
What exactly is conflicting then? What other things are you referencing? Are you targeting .NET Core 2.0?

**Comment by WilliamWsyHK** [comment]
`System.Management.Automation` `6.0.0-beta.5` (from myget)
`Microsoft.AspNetCore.All` `2.0.0` (from nuget)

What I want this project to do is targeting ASP.NET Core 2 with Windows Auth, and enable to use PowerShell inside.

**Comment by davidfowl** [comment]
Show your entire project file and all project files it references. Also, if you could grab obj/project.assets.json and put that in a gist, it would be good. That way we can see what you're actually referencing

**Comment by WilliamWsyHK** [comment]
project.assets.json: https://gist.github.com/WilliamWsyHK/2241c6e374cbe3d5234a5cc6bb5c7bb3

**Comment by davidfowl** [comment]
Looking at your assets file, it's likely a mismatch between the Microsoft.NETCore.App and ASP.NET Core 2.0.0. 

```
"Microsoft.NETCore.App": {
            "target": "Package",
            "version": "2.0.0-preview2-25407-01",
            "autoReferenced": true
          },
          "Microsoft.AspNetCore.All": {
            "target": "Package",
            "version": "2.0.0"
          }
```

You need to wait until the 2.0.0 SDK is released, or go download a newer preview version from https://github.com/dotnet/core-setup#daily-builds.

**Comment by WilliamWsyHK** [comment]
Tried, thanks.
But that is weird that ASP.NET Core released earlier than .NET Core.
