### ISSUE TITLE
AddEnvironmentVariables() injects default value for ASPNETCORE_URLS variable

### ISSUE THREAD

**Issue by leak** [aspnet/Hosting#1171]
When using AddEnvironmentVariables() during configuration building and not specifying the ASPNETCORE_URLS variable in Visual Studio's launch configuration, it will be populated with a default value of `localhost:5000`.
This effectively overrides the urls configuration in my config.json.

ASP.NET Core 2.0 / win10 x86

**Comment by manigandham** [comment]
The order of the configuration providers matters: https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration

> Configuration sources are read in the order they are specified. In the code above, the environment variables are read last. Any configuration values set through the environment would replace those set in the two previous providers.

Is `AddEnvironmentVariables()` after `AddJsonFile(...)` in your program?

**Comment by leak** [comment]
Yes it is and that is also intentional. I want to be able to override the configuration setting of my json file when I need to.
But this should only happen when i explicitly set the environment variable, for example in the Visual Studio launch configuration.
When I don't set it, I would expect it not to be overridden by default value from unknown source.

**Comment by manigandham** [comment]
Is it set in Windows?

**Comment by leak** [comment]
No it is not.

**Comment by leak** [comment]
By now I am pretty sure Visual Studio is messing with the environment variables:

Nothing configured here, in fact App URL was removed:
![image](https://user-images.githubusercontent.com/530056/30861310-93799732-a2ca-11e7-9b02-3c3fe537e972.png)

And yet the process is already configured with an environment right at the start.
![image](https://user-images.githubusercontent.com/530056/30861247-7057a4e2-a2ca-11e7-9c8d-394a3324d6dc.png)

So this is an issue for the tooling repo?

**Comment by Tratcher** [comment]
Yes, VS does this. @BillHiebert any way to suppress it?

**Comment by BillHiebert** [comment]
You can disable it in the launchSettings.json file. If you set the following property in the launch profile, Visual Studio will assume Kestrel is being configured externally and will not set the ASPNETCORE_URLS environment variable.
"externalUrlConfiguration" : true

However, you should still set the applicationUrl property so that Visual Studio knows how to launch the browser.

**Comment by leak** [comment]
@BillHiebert Thank you, this did the trick for me.
