### ISSUE TITLE
Bootstrapping a non-web console app with WebHostBuilder

### ISSUE THREAD

**Issue by kspearrin** [aspnet/Hosting#1172]
Our existing project infrastructure all revolves around ASP.NET Core applications (API, etc). Recent requirements for our project involve the need for a simple console application to run jobs outside of the web environment (cron jobs calling into the console app).

I want to leverage the existing core library that is setup with our ASP.NET Core applications, however that has several dependencies such including Configuration, Hosting Environment, Dependency Injection, etc. These type of things are neatly bootstrapped in `WebHostBuilder` which calls into `Startup`.

So with this in mind I created the following with our new console application:

```
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore" Version="1.1.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Core\Core.csproj" />
  </ItemGroup>

</Project>
```

```
public class Program
{
    private static IMyCoreService _myCoreService;

    public static void Main(string[] args)
    {
        var host = new WebHostBuilder()
            .UseContentRoot(Directory.GetCurrentDirectory())
            .UseStartup<Startup>()
            .UseServer(new NoopServer())
            .Build();

        // no run...

        _myCoreService = host.Services.GetRequiredService<IMyCoreService>();

        MainAsync(args).Wait();
    }

    private async static Task MainAsync(string[] args)
    {
        // do the jobs...
        // can now use _myCoreService
    }
}
```

```
public class NoopServer : IServer
{
    public IFeatureCollection Features => new FeatureCollection();

    public void Dispose()
    { }

    public Task StartAsync<TContext>(IHttpApplication<TContext> application, CancellationToken cancellationToken)
    {
        return Task.FromResult(0);
    }

    public Task StopAsync(CancellationToken cancellationToken)
    {
        return Task.FromResult(0);
    }
}
```

```
public class Startup
{
    public Startup(IHostingEnvironment env)
    {
        var builder = new ConfigurationBuilder()
            .SetBasePath(env.ContentRootPath)
            .AddJsonFile("settings.json")
            .AddEnvironmentVariables();
        Configuration = builder.Build();
        Environment = env;
    }

    public IConfigurationRoot Configuration { get; private set; }
    public IHostingEnvironment Environment { get; set; }

    public void ConfigureServices(IServiceCollection services)
    {
        // Options
        services.AddOptions();
        
        // Register all my DI stuff...
    }

    public void Configure()
    { }
}
```

This all seems to work as intended. I can now do things in my console application with full access to my core library DI, Configuration, etc.

But it feels kinda dirty... like I'm not suppose to be doing this... this console app is not a web server at all...

Thoughts?

FYI: Real project source can be found here: https://github.com/bitwarden/core/tree/aspnetcore2.0/src/Jobs

**Comment by manigandham** [comment]
Seems fine to me, we do something similar. All apps are technically console apps now with a static `Main` method anyway.

If you want DI only without the webhost then you can just use a `ServiceCollection` container directly:

```
 var serviceProvider = new ServiceCollection()
            .AddSingleton<FooService>()
            .AddTransient<BarService>()
            .BuildServiceProvider();

var foo = serviceProvider.GetService<FooService>();
```

**Comment by davidfowl** [comment]
See https://github.com/aspnet/Hosting/issues/1163. What you have seems like a fine hack though.

**Comment by kspearrin** [comment]
@davidfowl That issue sounds like it's describing my use case perfectly. Glad to see you guys are already on it. Thanks!
