### ISSUE TITLE
TestServer w/ WebHostBuilder doesn't read appsettings.json on ASP.NET Core 2.0, but it worked on 1.1

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/Hosting#1191]
_From @neooleg on August 30, 2017 19:59_

## STR
1. Use .NET 2.0
1. Follow [official manual](https://docs.microsoft.com/en-us/aspnet/core/testing/integration-testing) to create integration tests
1. Use the following code for test server
```
_server = new TestServer(new WebHostBuilder()
    .UseEnvironment("Development")
    .UseContentRoot(projectDir)
    .UseStartup<TestStartup>());
```

h3. AR
- appsettings.json doesn't read and TestStartup doesn't receive them.
- It looks like breaking changes (not found anything documented it) because the same code worked on ASP.NET Core 1.1

h3. ER
appsettings.json should be read and passed into Startup.

_Copied from original issue: aspnet/KestrelHttpServer#2042_

**Comment by Tratcher** [comment]
@neooleg WebHostBuilder and TestServer do not read appsettings.json in any scenarios. CreateDefaultBuilder is the only component that includes appsettins.json by default:
https://github.com/aspnet/MetaPackages/blob/dev/src/Microsoft.AspNetCore/WebHost.cs#L148

**Comment by neooleg** [comment]
@Tratcher I see, thanks!

What is idiomatic way to read appsettings.json in tests except doing it explicit (which is might be good depending on case):
```
_server = new TestServer(new WebHostBuilder()
    .UseEnvironment("Development")
    .UseContentRoot(projectDir)
    .UseConfiguration(new ConfigurationBuilder()
        .SetBasePath(projectDir)
        .AddJsonFile("appsettings.json")
        .Build()
    )
    .UseStartup<TestStartup>());
```

**Comment by Tratcher** [comment]
It needs to be explicit in all apps and tests unless you call CreateDefaultBuilder.

**Comment by Tratcher** [comment]
Note there is a ConfigureAppConfgiuration method that is a little easier than UseConfiguration.

**Comment by neooleg** [comment]
Do you recommend to use CreateDefaultBuilder() in tests as well?

**Comment by Tratcher** [comment]
It depends on what you're testing. If you're trying to mimic a full application then it may make sense.

**Comment by neooleg** [comment]
Thanks a lot, @Tratcher!

P.S. The issue might be closed from my point of view.
