### ISSUE TITLE
DotNetCore.1.0.0-WindowsHosting installation problem: IISExecuteCA

### ISSUE THREAD

**Issue by ferrancg** [aspnet/Hosting#1193]
Install DotNetCore1.0.0-WindowHosting on Windows Server 2016 with IIS10, the installation fails intermittently throwing error "CustomAction IISExecuteCA returned actual error code 1603".

Repo steps:

Uninstall DotNetCore1.0.0-WindowHosting from the server.
Restart server (We have a script will run ".\DotNetCore.1.0.0-WindowsHosting.exe /q /log %logDir%\dotnetcore_install.log" when server is restarted)
Installation failed intermittently

Any idea how to troubleshoot this issue?

**Comment by Tratcher** [comment]
@shirhatti @joeloff

**Comment by joeloff** [comment]
@pan-wang who owns the custom action in ANCM

**Comment by pan-wang** [comment]
@ferrancg  could you  please share the installation log?

**Comment by ferrancg** [comment]
[installlog.zip](https://github.com/aspnet/Hosting/files/1268379/installlog.zip)

**Comment by pan-wang** [comment]
the log did not show any clue about the root cause. We may need collect detailed one. @joeloff do you know how enabled detailed logging for bundle installation

**Comment by joeloff** [comment]
Bundles always enable verbose logging for the MSIs. I see a of entries in the MSI log for the CA.

CAQuietExec:  Unlocked section "system.webServer/handlers" at configuration path "MACHINE/WEBROOT/APPHOST".
MSI (s) (F4:38) [09:27:34:287]: Executing op: CustomActionSchedule(Action=IISBeginTransactionCA,ActionType=3073,Source=BinaryData,Target=IISBeginTransactionCA,)
MSI (s) (F4:30) [09:27:34:303]: Invoking remote custom action. DLL: D:\Windows\Installer\MSI3EE5.tmp, Entrypoint: IISBeginTransactionCA
MSI (s) (F4:38) [09:27:34:318]: Executing op: ActionStart(Name=IISRollbackTransactionCA,,)
MSI (s) (F4:38) [09:27:34:318]: Executing op: CustomActionSchedule(Action=IISRollbackTransactionCA,ActionType=3329,Source=BinaryData,Target=IISRollbackTransactionCA,)
MSI (s) (F4:38) [09:27:34:318]: Executing op: ActionStart(Name=IISCommitTransactionCA,,)
MSI (s) (F4:38) [09:27:34:318]: Executing op: CustomActionSchedule(Action=IISCommitTransactionCA,ActionType=3585,Source=BinaryData,Target=IISCommitTransactionCA,)
MSI (s) (F4:38) [09:27:34:318]: Executing op: ActionStart(Name=IISExecuteCA,,)
MSI (s) (F4:38) [09:27:34:318]: Executing op: CustomActionSchedule(Action=IISExecuteCA,ActionType=3073,Source=BinaryData,Target=IISExecuteCA,CustomActionData=1^1^16^AspNetCoreModule^42^D:\Windows\system32\inetsrv\aspnetcore.dll^0^^0^^1^7^27^system.webServer/aspNetCore^5^Allow^0^^0^^0^^)
MSI (s) (F4:70) [09:27:34:318]: Invoking remote custom action. DLL: D:\Windows\Installer\MSI3F05.tmp, Entrypoint: IISExecuteCA
1: IISCA IISExecuteCA : Begin CA Setup 
1: IISCA IISExecuteCA : CA 'ExecuteInstallModuleCA' completed with return code hr=0x0 
1: IISCA IISExecuteCA : CA 'ExecuteRegisterSectionSchemaCA' completed with return code hr=0x80070020 
1: IISCA IISExecuteCA : CA 'IISExecuteCA' completed with return code hr=0x80070020 
1: IISCA IISExecuteCA : End CA Setup 
CustomAction IISExecuteCA returned actual error code 1603 (note this may not be 100% accurate if translation happened inside sandbox)
MSI (s) (F4:38) [09:27:35:631]: Note: 1: 2265 2:  3: -2147287035 
MSI (s) (F4:38) [09:27:35:631]: User policy value 'DisableRollback' is 0
MSI (s) (F4:38) [09:27:35:631]: Machine policy value 'DisableRollback' is 0
Action ended 9:27:35: InstallFinalize. Return value 3.

**Comment by pan-wang** [comment]
Ok, per the log error,
IISCA IISExecuteCA : CA 'ExecuteRegisterSectionSchemaCA' completed with return code hr=0x80070020
it seems the installer cannot write to %windir%\system32\inetsrv\config\applicationhost.config. This could due to Antivirus software which was scanning the file exclusive due to the dll was added and the file in the middle of updating. Please try install the bundle while disabling the Antivirus software.

**Comment by ferrancg** [comment]
I see, I am not sure this is Antivirus software on our servers, we kinda are using third-party infra, don't have much control on built-in software. Would you add re-try logic in the process to mitigate the issue?

**Comment by joeloff** [comment]
Retry logic is not support in the bundles today at all, except in the case where packages need to be downloaded first, but even then the retries are restricted to download attempts and not installs. Retrying is difficult given all the possible reasons an MSI might fail and especially when a random custom action is executed by the MSI. The bundle has very little insight into that. Adding support would require investing in writing a completely custom engine for the installation bundle.

@pan-wang what might work is adding a retry in the custom action itself - given that it's there the failure is detected first.

Apart from AV software, is it possible some other process could have locked the file or the applicationhost.config supports locking itself? I know with things like machine.config and the root web.config you can lock certain sections to stop the files from being modified. I wasn't sure whether this is something IIS supported as well.

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
