### ISSUE TITLE
Processus never stops on error at startup

### ISSUE THREAD

**Issue by Greooo** [aspnet/Hosting#1194]
Hello,

With the new Core 2.0 SDK, I'm using the extension method "IWebHost.Run" to start the host in a console application. But when an exception is thrown during startup (wrong url by exemple), the processus never stops even with "Ctrl-C" keys combination.

In the method RunAsync of the Microsoft.AspNetCore.Hosting.WebHostExtensions class, the code line "done.Set();" is never called so in the "AttachCtrlcSigtermShutdown" method, thread waits on the following code line "resetEvent.Wait();".

Is it possible to do a try - finally on "host.RunAsync" with "done.Set();" in the finally block or any other solution to not block the thread execution ?

Thanks in advance

**Comment by muratg** [comment]
@Greooo Could you create an app that reproduces this problem and put it on GitHub with instructions to hit this problem?  Ctrl-C technically should work.  What environment/OS are you running this on?

**Comment by NicolasDorier** [comment]
If error at startup `RunAsync` fails on https://github.com/aspnet/Hosting/blob/a63932a492513cdeb4935661145084cad2ae5521/src/Microsoft.AspNetCore.Hosting/WebHostExtensions.cs#L83 so `done.Set()` is never reached, and the application never close.

**Comment by NicolasDorier** [comment]
I managed to repro:

```
dotnet new mvc
```

Then modify `Program.cs`

```
        public static void Main(string[] args)
        {
            IWebHost host = null;
            try
            {
                host = BuildWebHost(args);
                host.Run();
            }
            catch { }
        }
```

Then add a faulty dependency crashing at startup:

```
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.Hosting;

public class BuggyDep : IHostedService
{
    public BuggyDep()
    {
        throw new System.Exception("LOL");
    }

    public Task StartAsync(CancellationToken cancellationToken)
    {
        return Task.CompletedTask;
    }

    public Task StopAsync(CancellationToken cancellationToken)
    {
        return Task.CompletedTask;
    }
}
```

Register it in `Startup.cs`

```
services.AddSingleton<IHostedService, BuggyDep>();
```

Run. now you can see that `dotnet` process is always running.

Workaround:

Do not catch exception of the host in `Program.cs`, let the process burn.

**Comment by muratg** [comment]
Thanks @NicolasDorier for the find!  @Tratcher thoughts?

**Comment by Tratcher** [comment]
Agreed, it looks like that manual reset event could block the ProcessExit event indefinitely.
https://github.com/aspnet/Hosting/blob/a63932a492513cdeb4935661145084cad2ae5521/src/Microsoft.AspNetCore.Hosting/WebHostExtensions.cs#L141-L144

@muratg The repro and change look easy enough. Assign someone to repro it and fix it.

I expect we haven't seen more reports of this because few apps catch and suppress exceptions in Main.

**Comment by muratg** [comment]
@NicolasDorier interested in sending a PR?

**Comment by NicolasDorier** [comment]
@muratg I think fixing is easier than managing to figure out where the hell is sdk 2.1 . :)

**Comment by muratg** [comment]
@NicolasDorier  👍  Got it, and we'll find someone to look into it. Thanks!

**Comment by NicolasDorier** [comment]
@muratg when I find more time I'll learn about this and contributing to .NET Core source code. You guys are doing great job, using .NET Core in all my new projects, some of them are getting traction now, this is a awesome, can't wait 2.1.

**Comment by muratg** [comment]
We'll accept PRs for this :)

**Comment by Rutix** [comment]
@muratg I am up to make a PR for this :). It's a nice up-for-grabs to start with. I am wondering what the best way is to add a test for this.  Any pointers for that?

**Comment by NicolasDorier** [comment]
Should be in the backlog for 2.1 release.

**Comment by Tratcher** [comment]
There are some functional shutdown tests over at https://github.com/aspnet/Hosting/blob/dev/test/Microsoft.AspNetCore.Hosting.FunctionalTests/ShutdownTests.cs. Not sure how well they'll adapt to an intentional crash.

**Comment by tmds** [comment]
@Tratcher will this be fixed too in 2.1?

**Comment by Tratcher** [comment]
We haven't seen nearly enough interest to warrant a 2.1 patch for this.

**Comment by drinkbird** [comment]
I can confirm that this is still an issue on 2.1
