### ISSUE TITLE
Azure Website + Azure Hybrid Connector:The specified CGI application encountered an error and the server terminated the process

### ISSUE THREAD

**Issue by d-chavez** [aspnet/Hosting#1195]
We developed a net core app that accesses SQL Server via WebApi, our requirement is to keep the WebApi on premises, publish the App to Azure and use Azure Hybrid Connector to connect them both, unfortunately, every time we try to get data we receive an error:  "502.3 - Bad Gateway, The specified CGI application encountered an error and the server terminated the process", we know the WebApi/Azure Hybrid Connector combination works because we have another app in azure with the same configuration, but this other app is full .net, not .net core.

We've tested different scenarios (including deploying a .net core 2.0 version) and we still get the same error.

Had anyone faced a similar issue before?

Thanks.

**Comment by Tratcher** [comment]
A 502 error should produce a variety of logs. Check the event logs and the applications logs to see the original error.

**Comment by muratg** [comment]
@d-chavez Any updates on this?

**Comment by muratg** [comment]
We're closing this issue as no response or updates have been provided in a timely manner and we have been unable to reproduce it. If you have more details and are encountering this issue please add a new reply and re-open the issue.
