### ISSUE TITLE
Error 500 with no content while querying data from AWS Sql server

### ISSUE THREAD

**Issue by nkmajeti** [aspnet/Hosting#1199]
I have a .net core 2.0 web api that queries data from AWS RDS (SQL Server). I can see the data being queried from the database, but the API returns Error 500 
{
  "date": "Tue, 05 Sep 2017 22:27:34 GMT",
  "content-length": "0",
  "server": "Kestrel",
  "content-type": null
}
No other details are given.

The same works fine if I connect to similar database in Azure.

**Comment by Tratcher** [comment]
That means there was an exception in your app. What's in the logs?

**Comment by nkmajeti** [comment]
Nothing is logged. 
This is what I found in docs 
_If the server catches an exception before the headers have been sent it sends a 500 Internal Server Error response with no body._
I checked IIS logs and there is nothing there as well.
if it's an exception in the app, it should error same when connected to database in Azure

**Comment by halter73** [comment]
You need to enable the [ASP.NET core logs](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging?tabs=aspnetcore2x#how-to-add-providers). The AddConsole provider is the most popular and should work find if you're capturing the output of the dotnet process.

In these logs you could see something like `fail: Microsoft.AspNetCore.Server.Kestrel[13]
Connection id "XXXXXXXXXXXX": An unhandled exception was thrown by the application. {Exception details}`.

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
