### ISSUE TITLE
How to use Async to the Configure method?

### ISSUE THREAD

**Issue by wangshifeng** [aspnet/Hosting#1200]
I have this simple code, a web api application
`        public async void Configure(IApplicationBuilder app, IHostingEnvironment env)`
 `       {`
      ` await OperationAsync(app);`
     `  app.UseMvc();`
    `    }`
It is success to call async method,but when i open a browser to http://localhost:5000/api/values ,get a 404 http response,Some thing wrong? or bug?

**Comment by Tratcher** [comment]
You don't. Never use async void in ASP.NET (or most other places). There is no async Configure support.

**Comment by wangshifeng** [comment]
@Tratcher  I get it, thx!
