### ISSUE TITLE
TestServer can't access to Views

### ISSUE THREAD

**Issue by deinok** [aspnet/Hosting#1201]
I have two projects, one is the server and the other is the tests.

So if i test that the Uri "/" returns a HTTP 200 using a TestServer, the test servers returns a HTTP 500.
Seems like the TestServer Cant access to the Views folder.

Is this the correct behaviour?

**Comment by Tratcher** [comment]
@javiercn

**Comment by javiercn** [comment]
You need to setup the ContentRoot in your tests to point to your project root instead of the test project. See https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Testing/MvcWebApplicationBuilder.cs#L86 for a way to do it.

**Comment by deinok** [comment]
@javiercn Now the Views are found but they are not rendered. 
Is this process documented anywhere?

# Code:
```csharp
private static IWebHostBuilder CreateTestWebHostBuilder(string[] args = null) => Program.CreateWebHostBuilder(args)
    .UseContentRoot($"{directoryOfAspNetCoreProject.FullName}")
    .UseWebRoot($"{directoryOfAspNetCoreProject.FullName}"wwroot/);
```

# Error:
An error occurred during the compilation of a resource required to process this request. Please review the following specific error details and modify your source code appropriately.


Generated Code

One or more compilation references are missing. Ensure that your project is referencing 'Microsoft.NET.Sdk.Web' and the 'PreserveCompilationContext' property is not set to false.

**Comment by javiercn** [comment]
Ah, you are missing the deps file of your project. You need to copy it to the output folder of your test project. We are improving this story for 2.1 by creating a package that does all this for you. In the mean time, take a look at https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Testing/build/netstandard2.0/Microsoft.AspNetCore.Mvc.Testing.targets

**Comment by deinok** [comment]
@javiercn Great, puting this Target in the test .csproj fixed the problem:
```csharp
<Target Name="CopyAditionalFiles" AfterTargets="Build" Condition="'$(TargetFramework)'!=''">
	<ItemGroup>
		<DepsFilePaths Include="$([System.IO.Path]::ChangeExtension('%(_ResolvedProjectReferencePaths.FullPath)', '.deps.json'))" />
	</ItemGroup>
	<Copy SourceFiles="%(DepsFilePaths.FullPath)" DestinationFolder="$(OutputPath)" Condition="Exists('%(DepsFilePaths.FullPath)')" />
</Target>
```

It would be great to have an explanation of how to fix this in the asp.net core docs ;)

**Comment by Tratcher** [comment]
@javiercn please file a doc bug for this scenario, people keep asking about it.
