### ISSUE TITLE
MVC Controller discovery when using test server

### ISSUE THREAD

**Issue by ItsVeryWindy** [aspnet/Hosting#1202]
https://github.com/aspnet/Hosting/issues/928

Couldn't re-open the issue, but this has become an issue again since migrating to the csproj format and setting preservecompilationcontext no longer fixes the issue.

**Comment by JunTaoLuo** [comment]
Can you provide a repro so I can take a closer look?

**Comment by Tratcher** [comment]
@javiercn

**Comment by javiercn** [comment]
@itsverywindy we know about this. Can you follow the steps in https://github.com/aspnet/Hosting/issues/1201
