### ISSUE TITLE
Issue hosting site in IIS10 and Virtual Directory

### ISSUE THREAD

**Issue by johncollinson2001** [aspnet/Hosting#1206]
Hi,

I'm trying to host my .NET core 2.0 app in IIS 10, as a virtual directory of the default website. 

When browsing to the URL i get a 502.5 - Process Failure error. 

After looking in the event viewer, i see the following error: "Application 'MACHINE/WEBROOT/APPHOST/DEFAULT WEB SITE' with physical root 'C:\inetpub\wwwroot\' failed to start process with commandline ' ', ErrorCode = '0x80070057 : 0.", so dotnet.exe is not being called correctly.

I have set the app up as a website within IIS, which works just fine. It's only when using a virtual directory that it does not work.

Can anyone advise? Is there any known issues around setting up .net core apps as virtual directories?

Thanks,
John

**Comment by Tratcher** [comment]
This issue was moved to aspnet/AspNetCoreModule#156
