### ISSUE TITLE
Figure out how to properly do functional testing

### ISSUE THREAD

**Issue by HaoK** [aspnet/Hosting#121]
Specifically so MVC can remove their fallback provider code: https://github.com/aspnet/Mvc/issues/1612

cc @davidfowl @loudej

**Comment by yishaigalatzer** [comment]
@muratg can you please triage so we can see when/if we can fix the MVC bug?

**Comment by HaoK** [comment]
If this PR goes through, MVC functionals can probably just use the new Hosting.Create overload to add services for the functional tests I think: https://github.com/aspnet/Hosting/pull/146
