### ISSUE TITLE
InjectedStartup_DefaultApplicationNameIsEntryAssembly test broken on linux

### ISSUE THREAD

**Issue by davidfowl** [aspnet/Hosting#1213]
Travis keeps failing with here.

```
InjectedStartup_DefaultApplicationNameIsEntryAssembly in 52.0073982s
Failed   Microsoft.AspNetCore.Hosting.FunctionalTests.WebHostBuilderTests.InjectedStartup_DefaultApplicationNameIsEntryAssembly_CoreClr
Error Message:
 Assert.Equal() Failure
          ↓ (pos 0)
Expected: IStartupInjectionAssemblyName
Actual:   Now listening on: http://localhost:5000
          ↑ (pos 0)
```

@JunTaoLuo my theory is that this commit https://github.com/aspnet/Hosting/commit/b187c1adc4db343ad985e3d45cfb4f77180966e6 broke things. I haven't looked into it much though.

**Comment by JunTaoLuo** [comment]
Most likely, it seems flaky which suggests there's a race in capturing output and we are examining the wrong message. I'll take a look and make the test more robust.
