### ISSUE TITLE
Should IHostLifetime's be composable?

### ISSUE THREAD

**Issue by Tratcher** [aspnet/Hosting#1221]
An open design question from the IHostLifetime design is if there should be a composition model. This could be registering multiple and then having Host resolve and execute all of them, or it could involve some inheritance or other manual composition structure.

Take for example ConsoleLifetime and HostProcessLifetime, they duplicate the ProcessExit event registration. Other environments may also want to compose other host lifetimes on top of existing ones.
https://github.com/aspnet/Hosting/blob/712c992ca827576c05923e6a134ca0bec87af4df/src/Microsoft.Extensions.Hosting/Internal/ConsoleLifetime.cs#L47-L52
https://github.com/aspnet/Hosting/blob/712c992ca827576c05923e6a134ca0bec87af4df/src/Microsoft.Extensions.Hosting/Internal/HostProcessLifetime.cs#L20

@davidfowl @JunTaoLuo

**Comment by JunTaoLuo** [comment]
Or both inheritance and multiple registrations for maximum flexibility?

**Comment by Tratcher** [comment]
*Head Explodes*

**Comment by JunTaoLuo** [comment]
If we ever plan to bring back startup hosting assemblies, then we might want to consider registering multiple so additional IHostLifetime can be added as controlled by the configuration. If not then either should be sufficient.

**Comment by davidfowl** [comment]
The main thing is that it should compose for shutdown reasons.

**Comment by muratg** [comment]
We need a quick discussion on this one.

**Comment by muratg** [comment]
Backloging based on the time issues.

**Comment by Tratcher** [comment]
We've decided not to do this.
