### ISSUE TITLE
Add option to disable hosting startup messages

### ISSUE THREAD

**Issue by JunTaoLuo** [aspnet/Hosting#1225]
Currently there is no way to disable the startup message:
```
Now listening on: http://localhost:5000
Application started. Press Ctrl+C to shut down.
```
We can add an option to disable writing these messages to console output. We will also need to add an option to SelfHostDeployer to stop scraping startup messages to determine the application has started and parse the url the app is listening on.

As a side effect, we can simplify the filtering in a few functional tests. https://github.com/aspnet/Hosting/blob/e53abdb2b8c95d71281f719b5967067191a7cc65/test/Microsoft.AspNetCore.Hosting.FunctionalTests/WebHostBuilderTests.cs#L62-L64 
Also, if it's possible to disable startup messages, can we print a warning for duplicate hosting startup assemblies?

**Comment by Tratcher** [comment]
https://github.com/aspnet/Hosting/blob/e53abdb2b8c95d71281f719b5967067191a7cc65/src/Microsoft.Extensions.Hosting/ConsoleLifetimeOptions.cs#L12
