### ISSUE TITLE
Simplifying ApplicationLifetime.ExecuteHandlers()?

### ISSUE THREAD

**Issue by KPixel** [aspnet/Hosting#1227]
Unless I'm missing something, it seems that the allocation of `List<Exception> exceptions` is unnecessary (that code cannot generate more than one exception).

[The whole method](https://github.com/aspnet/Hosting/blob/dev/src/Microsoft.AspNetCore.Hosting/Internal/ApplicationLifetime.cs#L103-L133) can be simplified as:
```C#
private void ExecuteHandlers(CancellationTokenSource cancel)
{
    // Noop if this is already cancelled
    if (cancel.IsCancellationRequested)
        return;
    // Run the cancellation token callbacks
    cancel.Cancel(false);
}
```

**Comment by jkotalik** [comment]
@KPixel yeah I believe you are right. Feel free to make a pull request if you would like!

**Comment by Tratcher** [comment]
Yes, this is a remnant of some old refactoring by @davidfowl where IHostedServices were embedded in ApplicationLifetime.
