### ISSUE TITLE
Add server feature to detect websocket support on the server

### ISSUE THREAD

**Issue by davidfowl** [aspnet/Hosting#1241]
Similar to what we had in katana, this would be useful for signalr to automatically disable websockets if it wasn't enabled on the IIS Server. 

See https://github.com/aspnet/SignalR/issues/1033.

/cc @Tratcher

**Comment by Tratcher** [comment]
The OS check is easy enough, though pan has said it's hard to tell if the IIS feature is installed. ANCM would also have to follow this information out of proc.
There's also the challenge that websockets is half provided by middleware.

**Comment by jkotalik** [comment]
Why would this be in Hosting rather than IISIntegration?

**Comment by davidfowl** [comment]
We need to look at what system.web did. There’s a server variable that gets set when it it’s enabled.


It’s in hosting because that’s where we currently have server features defined.

**Comment by jkotalik** [comment]
We briefly talked about this yesterday with @pan-wang @anurse and @Tratcher. IIRC ANCM will set an env variable to say whether WebSockets is supported. IISIntegration/Kestrel can then populate something (designed TBD) to signify what protocols are allowed.

**Comment by davidfowl** [comment]
Lets design the feature and decide where it's going to live. Lets also make sure we know how to flow this feature through so the SignalR can read it in the correct place. I think we can just look at IServer.ServerFeatures.

Another issue is that potentially middleware wants to tweak this feature. If you use Kestrel without the websocket middleware then it should say that websocket aren't supported.

**Comment by Tratcher** [comment]
Components involved in the matrix:
- Kestrel - Supports Upgrade
- HttpSys - Supports Upgrade (WebSockets)
- IIS/Express In Proc - Supports WebSockets on Win7+ if the module is installed
- IIS/Express out-of-proc - Supports WebSockets on Win7+ if the module is installed
- NGinx - ?
- Apache - ?
- WebSocket middleware - Supports WebSockets if Upgrade is available
- SignalR - Wants WebSockets
- Hosting - To connect it all together

We also have to consider back-compact for ANCM.

I expect one of the more complex scenarios is the most common:
IIS/Express Win10 With or without module installed -> Kestrel -> Hosting -> WebSockets Middleware -> SignalR

**Comment by davidfowl** [comment]
> We also have to consider back-compact for ANCM.

It's fine telling people to upgrade ANCM if they want SignalR to work properly. We can also tell people to set the feature manually if they're on an older version and they know websocket are supported. 

> IIS/Express Win10 With or without module installed -> Kestrel -> Hosting -> WebSockets Middleware -> SignalR

Yes, it's also common on Antares where the module isn't on by default (last I checked).

> Hosting - To connect it all together

Nothing really happens in hosting, we just filed the bug here because its easy. The feature will likely exist somewhere in server.abstractions.

**Comment by khellang** [comment]
> - NGinx - ?

It supports WebSockets [by establishing a tunnel to the proxied server](http://nginx.org/en/docs/http/websocket.html)

> Since version 1.3.13, nginx implements special mode of operation that allows setting up a tunnel between a client and proxied server if the proxied server returned a response with the code 101 (Switching Protocols), and the client asked for a protocol switch via the “Upgrade” header in a request.

Not sure how you could detect this though...

**Comment by pan-wang** [comment]
Websocket will not work on win7 even IIS websocket module is installed and enabled,  e.g., iisexpress on win7. This is why we detect both OS and module. 
On Antares user needs to enable websocket and pay for it.

**Comment by Tratcher** [comment]
I have a related scenario where middleware needs to know if the app is behind a reverse proxy (ANCM/IIS/NGINX) for the sake of turning on/off redundant functionality.

**Comment by anurse** [comment]
I'll do a little sketch and set up a meeting to design this.

**Comment by Tratcher** [comment]
This will be implemented by the servers directly:
https://github.com/aspnet/IISIntegration/issues/584
https://github.com/aspnet/HttpSysServer/issues/427

**Comment by khellang** [comment]
Or is the assumption that anything else always supports WS? 😊

**Comment by Tratcher** [comment]
WS support is assumed unless something explicitly tells it otherwise. That's our back-compat story as well.

This is one more thing in the list that would be added to a UseNGinxIntegration component.
