### ISSUE TITLE
Preserve build context for IntegrationTesting deployers

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/Hosting#1244]
The dotnet-restore step executed by the IntegrationTesting deployers often fails on CI. The restore context the deployers use does not match the restore context used to build the test project. We need to a way to preserve the MSBuild properties set at build-time.

Ideas:
 - add a target to the IntegrationTesting package that captures build context. The deployers automatically pick this up.
 - generate a .rsp file at build time with relevant properties to be passed into the deployer
 - generate the csproj's at build time
 - generate some other kind of intermediate file that captures build context

Another idea:
 - deployers shouldn't execute restore. They only ever execute build and publish on already restored projects.

cc @ryanbrandenburg - this is why aspnet/Metapackage tests started failing after pinning to specific versions in https://github.com/aspnet/MetaPackages/pull/245

**Comment by natemcmaster** [comment]
Example failure:

> Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet stdout: C:\b\w\33bdfc1cae7b2a38\.r\MetaPackages\test\TestSites\CreateDefaultBuilderOfTApp\CreateDefaultBuilderOfTApp.csproj : error NU1603: Microsoft.AspNetCore depends on Microsoft.AspNetCore.Diagnostics (>= 2.1.0-preview1-27424) but Microsoft.AspNetCore.Diagnostics 2.1.0-preview1-27424 was not found. An approximate best match of Microsoft.AspNetCore.Diagnostics 2.1.0-preview1-27426 was resolved.

It's not actually testing the right packages. It should be trying to use Microsoft.AspNetCore.Diagnostics 2.1.0-preview1-27439.

http://aspnetci/viewLog.html?buildId=350366&tab=buildResultsDiv&buildTypeId=Lite_UniverseTest

**Comment by ryanbrandenburg** [comment]
To clarify "often", this has failed every one of the last 7 Win2012-Universe builds on the CI.

**Comment by muratg** [comment]
Assigning @Tratcher for investigation.

**Comment by natemcmaster** [comment]
Looks like MvcPrecompliation also needs a tweak to react to this. cc @pranavkm 

> error : Assets file 'C:\b\w\33bdfc1cae7b2a38\.r\MvcPrecompilation\testapps\SimpleApp\obj\project.assets.json' doesn't have a target for '.NETCoreApp,Version=v2.0/debian-x64'. Ensure that restore has run and that you have included 'netcoreapp2.0' in the TargetFrameworks for your project. You may also need to include 'debian-x64' in your project's RuntimeIdentifiers. [C:\b\w\33bdfc1cae7b2a38\.r\MvcPrecompilation\testapps\SimpleApp\SimpleApp.csproj]

**Comment by pranavkm** [comment]
Spoke to @ryanbrandenburg about this. I was planning on investigating this at some point today.
