### ISSUE TITLE
Microsoft.AspNetCore.Mvc.Razor.Compilation.CompilationFailedException : One or more compilation failures occurred

### ISSUE THREAD

**Issue by Edward-Zhou** [aspnet/Hosting#1245]
For this error, I have tried multiple solutions which is provided by Github. But, none of them worked. Please help to check whether this issue reopen on new environment like below.
Environment:
VS 2017 Version 15.4.1
Dotnet Version 2.0.2

Reproduce Steps:

1. Create an Asp.Net Core Web Application->.NET Core and Asp.net Core 2.0-> Web Application(Model-View-Controller)
2. Create an xUnit Test Project(.NET Core) 
3. Follow this link [Integration testing in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/testing/integration-testing)
4. Add <PreserveCompilationContext>true</PreserveCompilationContext> to Test.csproj which is pointed at above link.
5. Run test method will return below error.

> Microsoft.AspNetCore.Mvc.Razor.Compilation.CompilationFailedException : One or more compilation failures occurred:
ewiqttdv.z4g(4,62): error CS0012: The type 'Attribute' is defined in an assembly that is not referenced. You must add a reference to assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.

Update: 
After following [this suggestion](https://github.com/aspnet/Hosting/issues/959#issuecomment-286351703) , this error gone, but, it produce below new error.

> Message: System.IO.FileNotFoundException : Could not load file or assembly 'Microsoft.VisualStudio.Web.CodeGeneration, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.

What is the possible way to resolve "Microsoft.AspNetCore.Mvc.Razor.Compilation.CompilationFailedException"?

Any help would be appreciated.

**Comment by muratg** [comment]
@javiercn Any thoughts on this?

**Comment by javiercn** [comment]
There are additional things that you need to do for testing MVC applications:
* Disable shadow copying in your test application.
* Copy the deps file of your application to the test project output folder.
* Set the content root of your webhostbuilder to point to your web application instead of to your test project output folder.

**Comment by Tratcher** [comment]
@javiercn is there a wiki or doc for this? We get enough people asking for it.

**Comment by javiercn** [comment]
@Tratcher We have a package for it, but its for the next release :). I'll see if I get some detailed instructions for this written we can point people to, but it's low priority.

**Comment by javiercn** [comment]
I wrote a complete sample and blog post on how to do this:

The blog post is here:
https://blogs.msdn.microsoft.com/webdev/2017/12/07/testing-asp-net-core-mvc-web-apps-in-memory/

The sample is here:
https://github.com/aspnet/samples/tree/master/samples/aspnetcore/mvc/testing/TestingMVC

It's important to note that you need to run the tests using either Visual Studio or dotnet test. There are some issues that we are investigating regarding running the tests with dotnet xunit at the time.

If you still have problems after this, feel free to reopen the issue.

**Comment by Tratcher** [comment]
@javiercn please file a doc bug to pull in your blog post content.

**Comment by javiercn** [comment]
@Tratcher https://github.com/aspnet/Docs/issues/4943
