### ISSUE TITLE
Integration Testing with two instances of TestServer on different URLs

### ISSUE THREAD

**Issue by latchkostov** [aspnet/Hosting#1254]
I have not been able to find documentation on this, but basically, I need to run two instances of TestServer on different URLs (a token issuer, and some API which uses the token).

I've tried using the following:

```
private readonly TestServer _identityTestServer;
private readonly TestServer _mgmtTestServer;

public AdminClientTests() : base(nameof(AdminClientTests))
{
	_identityTestServer = new TestServer(new WebHostBuilder()
		.UseStartup<USBIdentityServer.Startup>()
		.UseEnvironment("IntegrationTest"));

	_mgmtTestServer = new TestServer(new WebHostBuilder()
		.UseStartup<IdentityServer4.Management.Startup>()
		.UseEnvironment("IntegrationTest"));
}
```

but it seems like both `_identityTestServer.BaseAddress` and `_mgmtTestServer.BaseAddress` are assigned `http://localhost`.

I've also tried using `.UseUrls("http://localhost:12345")` for one of the WebHostBuilder, but that also doesn't seem to have an effect.  Is this possible, and if so, is it documented anywhere?  I have been doing some searching around, but have no been able to find anything related to this.

**Comment by Tratcher** [comment]
Test server does not open any real sockets, so running on different urls is a fictitious concept anyways. You can set BaseAddress to anything you want.

I assume your actual challenge is communicating with those test servers? Again, they don't open any real sockets, the only way to communicate with them is through their CreateClient API which creates an in-memory channel.

**Comment by blgrnboy** [comment]
@Tratcher Yeah, you are right.  I was not aware that you can only communicate via the `CreateClient`.  I was tying to test a library that is creating it's own HttpClient and set the base URL to a provided string (by the test).

It seems like I may try to come up with a different pattern that makes this more testable.  Do you have any ideas?

**Comment by Tratcher** [comment]
Look at this sample in Security:
https://github.com/aspnet/Security/blob/72e1cb1385c982e6dba90c839d1a1455e2813e6c/src/Microsoft.AspNetCore.Authentication/RemoteAuthenticationOptions.cs#L66-L78
It lets you provide the HttpClient or the lower level HttpMessageHandler and it uses those when it needs to make calls. In your case you could provide the client from one test server to your app code in the other instance.

The other think you can do is to start Kestrel or HttpSys twice in process and communicate over localhost. We do that a lot in our functional tests.

**Comment by blgrnboy** [comment]
@Tratcher I tried to do this with HttpClient being a property I can set, and setting is as the reference of `.CreateClient()`, however, still unsuccessful.

It would be great to get this working and documented.  I can't see being the only person that faces this issue.

**Comment by Tratcher** [comment]
Please share the code you tried, inline or as a github repo.

**Comment by blgrnboy** [comment]
It may take me some time.  It's a private project, and posting it on Github entirely will not fly, but I am probably come up with a sample project that replicates the behavior.  I will work on this this weekend then post it up.

**Comment by alesdvorakcz** [comment]
any updates here?

**Comment by ColinM9991** [comment]
Currently looking at the same scenario too, I'm thinking WireMock.NET may resolve this

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
