### ISSUE TITLE
TestServer and OIDC/MSAL

### ISSUE THREAD

**Issue by dmcweeney** [aspnet/Hosting#1271]
Hi,

I've an ASP.Net Core 2 web app/api that is protected using OIDC and MSAL.

For our unit and functional tests, I want to be able to test the routing, model binding, etc 
using the TestServer class. 

Any ideas on the best way to bypass the authentication layer for this kind of testing?

Thanks

Donal

**Comment by Tratcher** [comment]
This issue was moved to aspnet/Security#1548
