### ISSUE TITLE
HTTP Error 502.5 after updating ASP.NET Core from 2.0.0 to 2.0.3

### ISSUE THREAD

**Issue by evgenf** [aspnet/Hosting#1275]
My ASP.NET Core app worked well on production server (windows server 2012 r2, IIS).
Then I updated ASP.NET nuget package from 2.0.0 to 2.0.3. After deploy on production server I got error:

> HTTP Error 502.5 - Process Failure
> Common causes of this issue:
> The application process failed to start
> The application process started but then stopped
> The application process started but failed to listen on the configured port

Event Log entry:

> Application 'MACHINE/WEBROOT/APPHOST/MY_APP' with physical root 'C:\inetpub\wwwroot\CI\MY_APP\' failed to start process with commandline 'dotnet .\MyApp.dll', ErrorCode = '0x80004005 : 8000808c.

After rollback to v2.0.0 app work well again.

**Comment by Tratcher** [comment]
Does the production server have the new runtime installed?

**Comment by evgenf** [comment]
Where can I get new runtime?
On [.NET Downloads page](https://www.microsoft.com/net/download/windows) I see only runtime for v2.0.0

**Comment by Tratcher** [comment]
The downloads page has now been updated. You need the new Windows Server Hosting (.exe).

**Comment by evgenf** [comment]
Thank you! I've installed new Windows Server Hosting (.exe) and updated app works well now.

**Comment by mum6ojum6o** [comment]
Would I need to uninstall previous versions of the .NET Core runtime? Or Could I have .Net Core runtime of multiple versions installed on the server?
