### ISSUE TITLE
Core 2 MVC (WCF to SSRS Execution) project Needs Administrator IIS AppPool to Work?

### ISSUE THREAD

**Issue by cgountanis** [aspnet/Hosting#1277]
Can anyone shed some light on a solution for this? The last thing I feel comfortable doing is giving an IIS application pool identity too much power.

Works fine within IIS Express (Visual Studio), once hosted under IIS you need to give it major user rights to work. I tried giving it elevated appPool virtual user rights on the web folder. I tried playing with the IIS authentication settings, seems to ignore all of that.

I have tied a million different settings and all the old solutions for .NET are not helpful in this case.

I am at a loss on this one and it is very frustrating any help would be great.

```
// Init the basic http binding.
var basicHttpBinding = new BasicHttpBinding()
{
	MaxReceivedMessageSize = int.MaxValue,
	MaxBufferSize = int.MaxValue,
	ReaderQuotas = XmlDictionaryReaderQuotas.Max
};

// Set the binding security mode based on the url scheme.
if (new Uri(model.ReportServerUrl).Scheme.ToUpper() == "HTTPS")
{
	basicHttpBinding.Security.Mode = BasicHttpSecurityMode.Transport;
}
else
{
	basicHttpBinding.Security.Mode = BasicHttpSecurityMode.TransportCredentialOnly;
}

// Binding client security transport settings.
basicHttpBinding.Security.Transport.ClientCredentialType = HttpClientCredentialType.Windows;

// Create the report execution service soap client.
var serviceSoapClient = new ReportExecutionServiceSoapClient(basicHttpBinding, new EndpointAddress($"{model.ReportServerUrl}/ReportExecution2005.asmx"));

// Credentials.
serviceSoapClient.ClientCredentials.Windows.AllowedImpersonationLevel = System.Security.Principal.TokenImpersonationLevel.Impersonation;
serviceSoapClient.ClientCredentials.Windows.ClientCredential = new NetworkCredential(model.Username, model.Password, model.Domain);

// Init the trusted user header.
var trustedUserHeader = new TrustedUserHeader();

// Load report and get response.
var loadReportResponse = serviceSoapClient.LoadReportAsync(trustedUserHeader, model.ReportPath, null).Result;

// Create execution header using load report response information.
var executionHeader = new ExecutionHeader
{
	ExecutionID = loadReportResponse.executionInfo.ExecutionID
};

// Parameters.
var reportParameters = model.Parameters.ToArray();
var setExecutionParametersResponse = serviceSoapClient.SetExecutionParametersAsync(executionHeader, trustedUserHeader, reportParameters, "en-us").Result;

// Render request.
var renderRequest = new RenderRequest(executionHeader, trustedUserHeader, model.ReportFormat, null);

// Render response.
var renderResponse = serviceSoapClient.RenderAsync(renderRequest).Result;
```

**Comment by Tratcher** [comment]
Can you share a repro project as a Github repo?

**Comment by cgountanis** [comment]
At this point in time I do not but I could if it helps. Really it is just a Core2 ClassLibrary with a WFC Connected Service to ReportExecution2005.asmx, from there this single function with a few variables spits out reports as file, byte[], you would not need to go that far to see the issue e.g. LoadReportAsync call is as far as you need to test. The goal was to make this really nice ClassLibrary that takes a few variables, parameters, server url, creds and spit back something you can use as FileResult in MVC. Works great! Just tackling the production hosting issue right now. Send me an email I can zip up the ClassLib project just for you :)

**Comment by muratg** [comment]
@cgountanis do you still have this issue?  Feel free to email me: <my github alias>@microsoft.com. Thanks.

**Comment by cgountanis** [comment]
Yes issue is pending.

https://github.com/dotnet/wcf/issues/2398

https://stackoverflow.com/questions/47416234/core-2-mvc-wcf-to-ssrs-execution-project-needs-administrator-iis-apppool-to-wo

**Comment by cgountanis** [comment]
So what I have done for a work around is just add a locked down (system) Windows User, remove from all groups and run the AppPool/Directory permissions as that system only user. Took a Linux approach and it works fine. I guess it just needed a user other than what the AppPool options provide default. It would be nice of this was solved, would love to run as AppPool default virtual user but not in the cards, better work around the running as a high privileged user at least.
