### ISSUE TITLE
Tag Helpers not being rendered when using Microsoft.AspNetCore.TestHost

### ISSUE THREAD

**Issue by jonasbutt** [aspnet/Hosting#1278]
Microsoft.AspNetCore.TestHost version 2.0.1.

ASP.NET Core Tag Helpers, both custom and built-in, are not being rendered and instead get sent to the client just like they appear in the Razor file. 

This behavior starts once I upgrade all .NET Core NuGet packages to 2.0.0.

Has anyone seen this before?

**Comment by Tratcher** [comment]
@javiercn @NTaylorMullen

**Comment by javiercn** [comment]
@jonasbutt Can you provide a small repro project to help us understand your specific scenario?

**Comment by jonasbutt** [comment]
Yes, hope this helps:

[WebApplication1.zip](https://github.com/aspnet/Hosting/files/1496733/WebApplication1.zip)

**Comment by jonasbutt** [comment]
@javiercn Do you have any update on this one?

**Comment by javiercn** [comment]
Hi, sorry for the delay I was putting together a complete sample and blog post on how to do this.

I looked at your sample and seems you are trying to load the metadata references yourself. The likely problem is that the dependency context of your application is not available in your unit tests project. The post and sample below show the best approach to make your tests run in the same context as your app. This is the solution that we use in the MVC repo for our own end to end tests.

The blog post is here:
https://blogs.msdn.microsoft.com/webdev/2017/12/07/testing-asp-net-core-mvc-web-apps-in-memory/

The sample is here:
https://github.com/aspnet/samples/tree/master/samples/aspnetcore/mvc/testing/TestingMVC

It's important to note that you need to run the tests using either Visual Studio or dotnet test. There are some issues that we are investigating regarding running the tests with dotnet xunit at the time.

If you still have problems after this, feel free to reopen the issue.
