### ISSUE TITLE
Dispose ApplicationServices if it is instantiated by Hosting

### ISSUE THREAD

**Issue by halter73** [aspnet/Hosting#128]
When we call `BuildServiceProvider` to create `IApplicationBuilder.ApplicationServices`, we should be responsible for disposing the `ServiceProvider` appropriately. This ensures that any disposable singletons and any other disposable services resolved from the root scope get disposed once the `ApplicationServices` is no longer in use.

I discussed this issue with @loudej, and we decided that it is wrong to dispose a `ServiceProvider` if the user instantiated it.

**Comment by HaoK** [comment]
This might not be an issue anymore with auto scoping https://github.com/aspnet/Hosting/issues/189

**Comment by muratg** [comment]
Yes, #189 seems to be removing this problem.  Stephen, if this is not correct, please reopen.
