### ISSUE TITLE
Found another duplicated type

### ISSUE THREAD

**Issue by khellang** [aspnet/Hosting#1283]
`Microsoft.Extensions.Hosting.EnvironmentName` and `Microsoft.AspNetCore.Hosting.EnvironmentName`.

Doesn't really matter as long as they don't drift apart, but could use some consolidation. If only they were in the same namespace, they could be type-forwarded :smile:

**Comment by khellang** [comment]
Hmm. `Microsoft.Extensions.Hosting` hasn't shipped yet? In that case, it's still possible to change the namespace of `Microsoft.Extensions.Hosting.EnvironmentName` back to `Microsoft.AspNetCore.Hosting` and forward to it.

**Comment by davidfowl** [comment]
Not sure what you’re suggesting.

**Comment by khellang** [comment]
@davidfowl https://github.com/khellang/Hosting/commit/c87f6eb0e7cd66394cb6fe50b98d34c372449cc9

**Comment by davidfowl** [comment]
The entire reason we do have a duplicate type today is because of the namespace. It’s not an accident

**Comment by khellang** [comment]
Why would you duplicate a type like that just to have it in a different namespace? 🤔

**Comment by davidfowl** [comment]
It says AspNetCore in the name.

**Comment by Matthew-Bonner** [comment]
Can I just ask, as I think the question is relevant, are we moving away from using AspNetCore in namespaces?

**Comment by davidfowl** [comment]
@Matthew-Bonner for generic hosting features that are not specific to ASP.NET Core that would ideally be the case.

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
