### ISSUE TITLE
Symbols and SourceLink

### ISSUE THREAD

**Issue by TicoDePano** [aspnet/Hosting#1284]
When trying to debug using SourceLink referencing Microsoft.AspNetCore.All 2.0.0 ->  Microsoft.AspNetCore.Hosting 2.0.0, it works as expected. But referencing Microsoft.AspNetCore.All 2.0.3 ->  Microsoft.AspNetCore.Hosting 2.0.1, it doesn't work.

Is there anything that could be made to debug directly into source using SourceLink referencing the last version?

**Comment by Tratcher** [comment]
@natemcmaster ?

**Comment by TicoDePano** [comment]
@natemcmaster , Microsoft Symbols Server, and it was working in the previous version, as stated in OP.

**Comment by natemcmaster** [comment]
@TicoDePano we started an internal email thread to get this going. I'll update this thread when we figure it out.

**Comment by muratg** [comment]
Closing this one.
