### ISSUE TITLE
IHttpContextAccessor is unavailable when an application is published

### ISSUE THREAD

**Issue by promanchenko-softheme** [aspnet/Hosting#1288]
Hello,

We've found a possible issue related to IHttpContextAccessor.

**Problem Description:** 
When an application uses Identity it registers IHttpContextAccessor in DI. We found this out in the sources. IHttpContextAccessor is available in DI when we debug the application in Visual Studio. However, when we publish the application and run dotnet.exe my.dll it is unavailable in the DI. This is true irrespectively to the publish configuration (debug/release).
When we attached a debugger to the published code we checked the private members of IServiceProvider (registered services). They are identical for Visual studio mode and publish mode except IHttpContextAccessor.

**Steps to reproduce:**
1. dotnet new mvc
2. inject IServiceProvider in the Startup constructor and save it as a global variable.
3. create a middleware
4. access the IServiceProvider and cal GetService<IHttpContextAccessor> (it is closured into the lambda)
5. In Visual Studio debug the result is not null. In published version the result is null.

**Why we need the HttpContext in a Middleware if we already have the HttpContext:**
We are implementing a multitenant system Using Identity Server + Identity. We determine the tenant by the request subdomain.
We have overridden the UserStore of Identity to take the user tenant into consideration during the login process.
The problem is that a user can get a JWT token using his/her tenant and try to use it for another tenant.
To fix this we have to check the correspondence of the request tenant and token tenant in runtime per each request.
To do so we've overridden the JWT issuer validator. It is a delegate and works as part of Authentication middleware.
That's why we closure the IServiceProvider in it and get the IHttpContextAccessor to get the request URL.

**Point of interest:**
If we inject IHttpContextAccessor into a controller it is available in the published code.

Could someone explain why in Visual Studio it works, but in the published version it doesn't work?

**Comment by campersau** [comment]
See https://github.com/aspnet/Hosting/issues/793#issuecomment-349760662

**Comment by promanchenko-softheme** [comment]
@campersau 
This approach doesn't work. UseIdentity does exactly the same as suggested inside of it.
Moreover, we've tried this and it obviously doesn't work.

**Comment by promanchenko-softheme** [comment]
After adding the UseApplicationInsights into Program.cs  - the issue is fixed.

**Comment by muratg** [comment]
:+1:
