### ISSUE TITLE
Application pool crashing issue

### ISSUE THREAD

**Issue by mshanmugam80** [aspnet/Hosting#1290]
Hi There,

I have deployed aspnet core app in IIS and I am facing app pool crashing issue frequently in production environment.

OS: Windows Server 2012 R2
IIS: Version 8.5
dotnet: Version 2.0.2

I have created separate pool for my app in IIS and configured app pool like below,
.NET CLR Version -> No Managed Code
Managed pipeline mode -> Integrated

Error:
Faulting application name: w3wp.exe, version: 8.5.9600.16384, time stamp: 0x5215df96
Faulting module name: custerr.dll, version: 8.5.9600.18591, time stamp: 0x589b3301
Exception code: 0xc0000005
Fault offset: 0x0000000000004fb2
Faulting process id: 0x2dec
Faulting application start time: 0x01d3700fc6d2379e
Faulting application path: c:\windows\system32\inetsrv\w3wp.exe
Faulting module path: C:\Windows\System32\inetsrv\custerr.dll
Report Id: c67a8f2c-dc07-11e7-81ac-0211e14c40ae
Faulting package full name: 
Faulting package-relative application ID:

Please help me to resolve this issue. My app is already running in production environment.

Thanks in Advance
Shanmugam

**Comment by Tratcher** [comment]
This issue was moved to aspnet/AspNetCoreModule#272
