### ISSUE TITLE
502.5 (0x80070002 : 0) when deploying to Windows Server 2016

### ISSUE THREAD

**Issue by dushkostanoeski** [aspnet/Hosting#1292]
I got a brand new Windows Server 2016 Datacenter Edition and before deploying my web app with Web Deploy, I followed [this](https://docs.microsoft.com/en-us/iis/install/installing-publishing-technologies/installing-and-configuring-web-deploy-on-iis-80-or-later) to set it up and then I followed [this](https://docs.microsoft.com/en-us/iis/install/installing-publishing-technologies/installing-and-configuring-web-deploy-on-iis-80-or-later) to set the environment up. The only difference is that I used Plesk to create the web space and then manually changed the ApplicationPool CLR version to No Managed Code and this has worked on a Windows Server 2012. Also Plesk created all the required identities and permissions so I'm not using the default ApplicationPoolIdentity, but the identity created by Plesk and yes, this identity has all the required permissions at the app destination and at C:\Program Files\dotnet

I am getting the 502.5 - Process Failure error in the browser and 0x80070002 : 0 error in the Application Log (the module Log file is empty). I checked all the instructions for that error here, but nothing changed. Running the app locally on the server using dotnet MyApp.dll works fine. I repaired all the VC++ Redistributable installations, I restarted IIS and even the whole server, but nothing changed.

Am I missing something or not doing something or doing something wrong?

**Comment by dushkostanoeski** [comment]
I reinstalled the OS and here is everything I did:

1. Fresh OS reinstall of `Windows Server 2016 Datacenter Edition`

2. Ran Windows Updates to install all latest updates (this required a reboot)

3. Installed `Recommended `Server Configuration for Web Hosting Providers` which is needed for Web Deploy (I tried a 'only Web Deploy` approach with the previous OS reinstall but that didn't work) and this installed everything except `IISNode for IIIS) and rebooted the system.

4. Installed Node 9.2.1 and rebooted

5. These are the `Microsoft Visual C++ 2015 Redistributable` versions I have installed on the server:

![Microsoft Visual C++ Redistributable](https://user-images.githubusercontent.com/1545030/33803710-74a5d990-dd96-11e7-8a50-865fc405f7f3.PNG)

I tried to install the one mentioned in the [tutorial](https://docs.microsoft.com/en-us/aspnet/core/publishing/iis?tabs=aspnetcore2x) but it said that a newer version is already installed so I didn't do anything else.

6. Installed the `.NET Core Windows Server Hosting bundle` and rebooted the system.

7. Ran Windows Updates  again and rebooted (this wasn't required but just in case)

8. Activated `Plesk Onyx 17.5.3` and added the domain.

9. Changed the .NET CLR Version for that domain to `No Managed Code` in the IIS Manager and added the user created by Plesk to the `IIS Manager Permissions` so I can use that user for deploying from Visual Studio.

10. Deployed the web site.

11. Got the 502.5 Error in browser and `ErrorCode = 0x80070002 : 0` in Event viewer






 Microsoft Visual C++ 2015 Redistributable

**Comment by dushkostanoeski** [comment]
Considering that this is happening on my production server and I am stuck at the moment, will I get any input on this?

**Comment by muratg** [comment]
@pan-wang @shirhatti guys, it looks like the app runs fine without ANCM/IIS.  Any thoughts what may be wrong based on the notes above?  Do we need more information from @dushkostanoeski?

**Comment by shirhatti** [comment]
0x80070002 is file not found. I'm assuming dotnet isn't on your path. We've seen this happen in the past when folks haven't rebooted after installing dotnet, but I'm assuming you've already tried that.
Can you share your SYSTEM Path? I'm assuming it somehow got borked.

Does specifying the full path to dotnet fix your problem in the interim?

```xml
<aspNetCore processPath="C:\Program Files\dotnet\dotnet.exe" arguments="MyApp.dll" />
```

**Comment by dushkostanoeski** [comment]
@shirhatti  I tried specifying the full path and it didn't work... 

The thing is that I gave up on it for about a week (had other stuff to tend to) and when I came there were some updates pending. I installed them, rebooted and it started to work. I'm willing to share any log files or whatever else you need to figure out what was wrong.

**Comment by pan-wang** [comment]
Which identity is used for the application pool?  Does that identity have the privilege to access all resources? Can you try change the apppool identity to local admin to see whether it helps

**Comment by dushkostanoeski** [comment]
The identity generated by Plesk is used, the `IWPD_10(domain_name)` and it works with that.
