### ISSUE TITLE
Add a hosting abstraction to provide a location on disk that components can use to read data from

### ISSUE THREAD

**Issue by javiercn** [aspnet/Hosting#1294]

**Comment by javiercn** [comment]
# IHosting application data

## Motivation
* There are components/libraries in our platform that require of a predefined location on disc to read/store data.
    * DataProtection keys.
    * Default kestrel HTTPS certificates.
    * User secrets.
    * ASP.NET Core buffering. BufferingHelper.cs#L25
* Right now every component chooses their own locations for storing state, which increases the footprint of every
  application on the machine.
* Like our own frameworks, other frameworks may have the need to read or store some state on a well-known location
  on disk, in order to avoid the need to avoid configuring an explicit path on disk.

## Proposed solution
* We can introduce at the hosting level the concept of `IHostingApplicationData`.
* This service defines a location where components in the framework can search for files that they need to work.
    * For example, certificates for HTTPS, keys for data protection, etc.
* This location should be considered GLOBAL for the machine, components requiring more isolation for their data
  MUST further namespace the data by using the application name (for example, caching).
* **The existence of this folder must not be required by any component to work, nor it is the ability to write to
  that folder.**
  * For example, with DataProtection we will just fallback to ephemeral if the location is not available.
* **Compoments on the framework must provide the ability to override this folder if they require a location on disk
  to work.**
  * For example, with the default kestrel HTTPS certificate users can provide the path to the certificate explicitly.

### Options
There are a couple of ways we can go about with this service:

#### Make it something meant for ASP.NET Core components internal comsumption.
* We follow the same pattern HostingEnvironment has for other locations on disk like ContentRoot.
* We use the same set of folders data protection uses to store the keys plus an additional fallback folder APP_DATA.

```csharp
public interface IHostingApplicationData
{
    /// <summary>
    /// Gets or sets the absolute path to the directory that applications use to
    /// store data outside of the content root of the application.
    /// </summary>
    string ApplicationDataPath { get; set; }

    /// <summary>
    /// Gets or sets an <see cref="IFileProvider"/> pointing at <see cref="ApplicationDataPath"/>.
    /// </summary>
    IFileProvider ApplicationDataFileProvider { get; set; }
}
```


#### Make it something all our components and user applications can use to optimistically read/store state.
* We provide a set of abstractions designed to read and write state to this location, with application scoping by default and optionally global scoping.
* We prioritize local/app scoped folders like APP_DATA over other more global/machine scoped folders like %HOME% or %USERPROFILE%
* We might provide different folders instead of a single one for different kinds of data.
    * Global folders use the same conventions as data protection.
    * Local folders prioritize an APP_DATA folder relative to the app and fall-back to
      a global folder with automatic namespacing.
* We might provide three categories of data:
    * Data that is exclusively local and can live in a folder along side your app. (Caching data, etc.)
    * Data that is exclusively global and should be shared across the machine. (Data protection keys)
    * Data that is exclusively local but can't live in a folder along side your app. (User secrets)

```csharp
public interface IHostingApplicationData
{
    string LocalApplicationDataPath { get; set; }
    string GlobalApplicationDataPath { get; set; }

    Stream GetApplicationDataStream(
        string path,
         /* options: read, write, create if not exists, */,
          /* local, global, global-namespaced */);
}

public enum StreamCreationOptions
{
    Read,
    Write,
    CreateIfNotExists
}

public enum DataKind{
    Local,
    Global,
    ApplicationScopedGlobal
}
```

## Details
* By default we try to find the folder to use following the same criteria as data protection, plus an additional fallback location:
    * Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData)/ASP.NET (For windows only).
    * %LOCALAPPDATA%/ASP.NET.
    * %USERPROFILE%/AppData/Local/ASP.NET
    * %HOME%/.aspnet
    * Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData)/ASP.NET
    * AppContext.BaseDirectory/APP_DATA
* The location used can be overriden through configuration.

**Comment by javiercn** [comment]
Replace the kestrel logic to use this:

https://github.com/aspnet/KestrelHttpServer/pull/2246/files/e6bb55101893142f92912c748e66115bc4aacdb4#diff-30cd221b1afd076c151780af8b8d3413R328

**Comment by muratg** [comment]
Closing this one. 

@javiercn please work with @shirhatti and @glennc to define the customer scenario for this if you want to bring it back.
