### ISSUE TITLE
Skip logging in certain routes

### ISSUE THREAD

**Issue by dferretti-fig** [aspnet/Hosting#1297]
I have a health check endpoint that just returns a simple json message indicating the healthy status. The load balancer I use will request that endpoint every 30 seconds, so in my otherwise mostly inactive web app, I have a bunch of logs that look like 
```
Request starting HTTP/1.1 GET http://a.b.c.d/HealthCheck
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
Request finished in 0.2525ms 200
```

I don't want to completely filter out that category as those logs are useful to me for the other endpoints, but it looks like custom log filters only have access to the provider, log level, and category. 

I can imagine one solution that would involve adding my own middleware to write my own logs that are similar to the webhost logs, that would be path aware and could ignore certain routes; and then filter out all webhost logs. I would need to make sure to copy the implementation of the timer and closely match everything else the default logging does (now and in the future). I can also process my logs after they have been generated and not change any code.

Is there any other way I can prevent these logs from being written in the first place just for the health check endpoint?

**Comment by muratg** [comment]
We won't be doing this on Hosting level.  I recommend wrapping the logger to remove things that you don't want.  Alternatively you can use filtering (i.e. filter out Info ones...)

**Comment by dferretti-fig** [comment]
Works for me - thanks!

**Comment by muratg** [comment]
Sounds good, thanks!
