### ISSUE TITLE
Provide way to override service registration in testserver

### ISSUE THREAD

**Issue by arishlabroo** [aspnet/Hosting#1303]
Consider a simple application

```
public class Program
{
    public static void Main(string[] args) => 
        CreateWebHostBuilder(args).Build().Run();

    public static IWebHostBuilder CreateWebHostBuilder(string[] args) =>
        WebHost.CreateDefaultBuilder(args).UseStartup<Startup>();
}

public class Startup
{
    public void ConfigureServices(IServiceCollection services) =>
        services.AddSingleton<IClock>(SystemClock.Instance);
        //Dependency that needs to be overridden.

    public void Configure(IApplicationBuilder app, IHostingEnvironment env) =>
        app.UseMiddleware<ReturnTimeMiddleware>();
}

public class ReturnTimeMiddleware
{
    public ReturnTimeMiddleware(RequestDelegate next) { }

    public Task Invoke(HttpContext context, IClock clock) =>
        context.Response.WriteAsync(clock.GetCurrentInstant().ToDateTimeOffset().ToString());
}
```

For a date/time sensitive application, testing behavior on different dates, I am trying to make the following integration test pass where I need to inject a fake clock(to the middleware here). 

```
[Fact]
public async Task Test1()
{
    var fakeClock = FakeClock.FromUtc(2017, 12, 12);
    var builder = Program.CreateWebHostBuilder(new string[0]);
    builder.ConfigureServices(s => s.AddSingleton<IClock>(fakeClock));

    var r = await (new TestServer(builder)).CreateClient().GetAsync("/");
    var timeString = await r.Content.ReadAsStringAsync();
    //FAILS
    Assert.Equal(fakeClock.GetCurrentInstant().ToDateTimeOffset().ToString(), timeString);
}

```

Looking at some other tickets like https://github.com/aspnet/Hosting/issues/529 its not clear how one can achieve this? If I am understanding correctly `WebHostBuilder.ConfigureServices` should be used only for HostingServices 🤔 and always runs before `Startup.ConfigureServices`. So What I am doing above is clearly wrong and does not work.

Any recommendations How I can achieve this? I can create an empty virtual method `ServiceConfigurationOverrides`, call it at the end of `ConfigureServices` in `Startup` class and then for each of my tests create a new derived startup class and use it like

```
var builder = Program.CreateWebHostBuilder(new string[0]);
builder.UseStartup<DerivedTestStartup>();
```

This works but does not feel right, and I dont want to create a new derived startup class for all my tests.  I just want to override one or two services here and there in each of my test. I also looked at the new `WebApplicationTestFixture<TStartup>` but same issues.

<sup>ps: IClock here is from NodaTime. </sup>
<sup>pps: IClock and Middleware are just for simple demonstration. Actual application has multiple dependencies in different layers.</sup>

**Comment by Tratcher** [comment]
This sounds like a duplicate of https://github.com/aspnet/Hosting/issues/1012 and https://github.com/aspnet/Hosting/pull/1168 which has been done for 2.1.0-preview1.

**Comment by arishlabroo** [comment]
Thanks, `ConfigureTestServices` from https://github.com/aspnet/Hosting/blob/dev/src/Microsoft.AspNetCore.TestHost/WebHostBuilderExtensions.cs is exactly what I needed.

I added 2.1 preview package of `Microsoft.AspNetCore.TestHost` and the below worked. Thank you @Tratcher for the quick response.

```
[Fact]
public async Task Test1()
{
    var fakeClock = FakeClock.FromUtc(2017, 12, 12);
    var builder = Program.CreateWebHostBuilder(new string[0]);
    builder.ConfigureTestServices(s => s.AddSingleton<IClock>(fakeClock));

    var r = await (new TestServer(builder)).CreateClient().GetAsync("/");
    var timeString = await r.Content.ReadAsStringAsync();
    //PASS
    Assert.Equal(fakeClock.GetCurrentInstant().ToDateTimeOffset().ToString(), timeString);
}

```
