### ISSUE TITLE
IHttpContextAccessor not up to date

### ISSUE THREAD

**Issue by guylando** [aspnet/Hosting#1308]
Would be amazing if someone could help me with the following issue:
In Configure method of Startup.cs I get IHttpContextAccessor instance from dependency injection and pass it to a custom logger factory implementation which saves it. Later when loggers are created and logs are written I use the IHttpContextAccessor instance to get the user name from the http context which triggered the log in order to associate it to the log. 
The problem is that the IHttpContextAccessor context always has the user which made the first request to the server when the server was started. It does not hold an up to date http context. Why is that? I thought IHttpContextAccessor is supposed to return the http context of the executing thread.

**Comment by Tratcher** [comment]
Can you share some code? It may be a usage issue.

**Comment by guylando** [comment]
After saving the instance of IHttpContextAccessor in the factory, on logger creation it is passed in its constructor from the factory and saved in an instance and then its used like this for example:
public bool GetCurrentUserInfo(out IPAddress userip, out int userid, out string username)
        {
            userip = null;
            userid = -1;
            username = "";
            if (this.mContextAccessor == null)
            {
                return false;
            }
            else { 
                if (this.mContextAccessor.HttpContext != null)
                {
                    try
                    {
                        // This might throw exception when connection disposed so put it in a try catch block
                        userip = this.mContextAccessor.HttpContext.Connection.RemoteIpAddress;
                    }
                    catch
                    {
                    }
                    string userId = this.mContextAccessor.HttpContext.User.GetUserId(this.mIdentityOptions);
                    if (userId != null)
                    {
                        userid = int.Parse(userId);
                    }
                    username = this.mContextAccessor.HttpContext.User.GetUserName(this.mIdentityOptions);
                    if (username == null)
                    {
                        username = "";
                    }
                }

                return true;
            }
        }

**Comment by Tratcher** [comment]
And the Startup code?

**Comment by guylando** [comment]
```
public class PostgresqlLoggerProvider : ILoggerProvider
    {
        private readonly Func<string, LogLevel, bool> mFilter;
        private readonly IServiceProvider mServiceProvider;
        private readonly IHttpContextAccessor mContextAccessor;
        public PostgresqlLoggerProvider(Func<string, LogLevel, bool> filter, IServiceProvider serviceProvider, IHttpContextAccessor contextAccessor)
        {
            this.mFilter = filter;
            this.mServiceProvider = serviceProvider;
            this.mContextAccessor = contextAccessor;
        }
        public ILogger CreateLogger(string name)
        {
            return new PostgresqlLogger(name, this.mFilter, this.mServiceProvider, this.mContextAccessor);
        }

        public void Dispose()
        {
        }
    }
```

**Comment by Tratcher** [comment]
That's not Startup...

**Comment by guylando** [comment]
The startup is huge and basically the relevant code is:
```
public void ConfigureDevelopment(ILoggerFactory loggerFactory, IHttpContextAccessor contextAccessor)
{
loggerFactory.AddProvider(new PostgresqlLoggerProvider(contextAccessor));
}
```

this is a big private code so if you have a clue I can show specific stuff

**Comment by Tratcher** [comment]
That's probably enough code for now, thanks. The other question is what application event is being logged that shows the wrong user? And is it showing a user from some other request or is it showing an anonymous user?

HttpContext.User is assigned at specific points in the pipeline, it won't be set yet for server or hosting level events.  What kind of Auth are you using? Cookie auth? Windows Auth? Bearer?

**Comment by guylando** [comment]
It shows a user from another request (I am guessing from the first request to the server when the http context was first initialized and never changed after that).
Cookie auth.
I made sure to register .AddAuthentication before registering code which uses the logger.
Application related logs are generated for example from signalr code, or from middleware which is registered after .AddAuthentication is called in startup Configure method.

**Comment by guylando** [comment]
Maybe related: When authenticated user BOB makes a request he gets antiforgery error and the following middleware code is triggered and when user is taken from the http context it reports ALICE and not BOB. I am clueless about whats going on here. 
The middleware:

```
public async Task Invoke(HttpContext context)
{
await this.mNext.Invoke(context);

                if (context.Response.StatusCode == 400 &&
                    context.Request.Headers.ContainsKey("X-Requested-With") &&
                    string.Equals(context.Request.Headers["X-Requested-With"].ToString(), "XMLHttpRequest") &&
                    !context.Response.HasStarted &&
                    !context.Response.ContentLength.HasValue)
                {
this.mLogger.LogError(errorMessage: "ERROR: Middleware user: " + (context.User.Identity.Name ?? "anonymous"));
}
}
```

**Comment by Tratcher** [comment]
Possibly related: https://github.com/aspnet/KestrelHttpServer/issues/1720

**Comment by guylando** [comment]
Some more info which might be relevant: 
- This happens in a multi threaded environment (when multiple users are working on the site).
- We previously had similar weirdness with random csrf errors and it turned out to be related to IIS application pool "Load User Profile" setting which should be set to true. But now its set to true..

**Comment by Tratcher** [comment]
Ok, we're going to have to put together a repro app. If you can condense one from your normal app and share it on github that would help.

**Comment by guylando** [comment]
Created a basic project with custom logger + signalr + antiforgery post request + error catching middleware:
https://github.com/guylando/NetCoreErrorsReproduction

Still need add authentication

**Comment by guylando** [comment]
Update: I added debug message in the beginning of the middleware before it calls Next.Invoke(context); and it reports the wrong user even then.
The authentication cookie sent is of the correct user. So this might be an authentication middleware issue. I opened an issue here: https://github.com/aspnet/Identity/issues/1560

**Comment by khellang** [comment]
@guylando Auth middleware lives in [aspnet/Security](github.com/aspnet/Security) 😄

**Comment by guylando** [comment]
OK I feel the problem is not related to the http context accessor so I moved the issue here: https://github.com/aspnet/Security/issues/1602
