### ISSUE TITLE
Stop the magic method names pattern

### ISSUE THREAD

**Issue by Eilon** [aspnet/Hosting#1311]
_From @oliverjanik on January 18, 2018 2:5_

This is the official way how you set up WebHost:
```csharp
            WebHost.CreateDefaultBuilder(args)
                .UseStartup<Startup>()
                .Build();
```

This then looks up the Startup class, magically instantiates it and looks for methods with magic names like `ConfigureServices` or `Configure`. Now I have solution analysis complaining these methods are not used anywhere. 

To mitigate this issue the template generates a comment for these methods:
![image](https://user-images.githubusercontent.com/2280140/35077146-b98c6ed4-fc4f-11e7-96b6-49b3351631cf.png)

That just adds salt to the wound. This is a bad pattern.  Anders invented interfaces for a reason. I know this pattern has been around for ages (old ASP.NET, EF and many many other MS libraries) but that does not make it acceptable.

Gentlemen, let's end this atrocity!

To be constructive, here's a suggestion:
```csharp
.UseStartup(c => new Startup(c))
```

_Copied from original issue: aspnet/Home#2795_

**Comment by Eilon** [comment]
_From @oliverjanik on January 18, 2018 3:51_

Another case in point is 
```
app.UseMiddleware<MyMiddleware>()
```

Magic constructor, magic method names 👎 and instead of compile-time type errors we get Runtime erros if the constructor does not conform.

**Comment by Eilon** [comment]
Unfortunately interfaces can't work for `UseStartup` or `UseMiddleware` because there is no specific requirement about the number or types of the parameters. For example, the `ConfigureServices` method has many different allowed signatures, so we can't restrict it to only one.

The lambda syntax you propose could probably work. I'm not sure if that's come up before as an idea.

**Comment by Eilon** [comment]
@Tratcher which repo would this bug go to? Hosting?

**Comment by Eilon** [comment]
_From @davidfowl on January 18, 2018 6:59_

> @Tratcher which repo would this bug go to? Hosting?

Yes Hosting.

> Magic constructor, magic method names 👎 and instead of compile-time type errors we get Runtime erros if the constructor does not conform.

There are actually interfaces for both of the things you suggest. There's an IMiddleware and an IMiddlewareFactory, and there's also an IStartup. We've received similar feedback in the past so we did introduce these interfaces. 

It does mean you lose the ability to use environment specific Configure and ConfigureServices via method names, you also lose the ability to get dependencies injected via method arguments but maybe that's ok in your scenario.

> To be constructive, here's a suggestion:
> ```C#
> .UseStartup(c => new Startup(c))
> ```

What is c in this case?

**Comment by Eilon** [comment]
_From @Tratcher on January 18, 2018 6:59_

We actually do have IStartup and IMiddleware, but nobody has ever shown much interest in them. Want to give them a try?

This can go in Hosting.

**Comment by oliverjanik** [comment]
@Eilon Which overload of .UseStartup does take IStartup? Can't find one.

Isn't that a half measure? Why would I use it if the thing is created and called via reflection anyway?

**Comment by oliverjanik** [comment]
Looking through the code I found this gem:
https://github.com/aspnet/Hosting/blob/dev/src/Microsoft.AspNetCore.Hosting/Internal/StartupLoader.cs

Talk about over-engineering.  Why do you feel the need to introduce yet another convention for something straight-forward as configuration/setup? More conventions add to higher cognitive overload for developers. I can't just rely on IntelliSense to tell me what is available and possible I have to look at documentation for this convention each time I use it.

Why not just give the environment name and let them return whatever they want from statically verifiable method?

In the end, all of this non-sense breaks solution wide analysis, reports unused dead-code, creates run-time errors instead of compile time errors and overall encourages bad practices.

**Comment by davidfowl** [comment]
Thank for the feedback but we’re not going to make any breaking changes in this area. If you’d like, use the interfaces that are available to you (IStartup and IMiddleware). It should give you all the things you’re missing with the caveats stared above.

If those interfaces don’t help you accomplish you goals then feel free to file more specific issues with that feedback.

**Comment by oliverjanik** [comment]
Spare me the political BS. Which part of my post do you disagree with? Am I incorrect in my conclusions?

I understand you can't make a breaking change. You delivered over-engineered solution and you'll have to support it forever. The sad thing is this what Microsoft does over and over again. Generation after generation of bloat. Unique opportunity blown again.

Those interfaces are half useless. Is there a way to do Startup and Middleware without reflection? Can I get a way to setup Startup and Middleware that does not use reflection and does not throw runtime errors? 

I'd be happy if that covered the most common 80% of use cases, and keep your fancy reflection and conventions who enjoy reflection, javascript and other forms of torture.

**Comment by khellang** [comment]
> Is there a way to do Startup and Middleware without reflection?

Implementing `IStartup` or deriving from `StartupBase` _is_ the way to go without using reflection. When you call `UseStartup` with a type implementing the interface, it uses those methods directly.

I'm curious why you think using reflection for this is so bad? Are you seeing performance problems? It's a one-off discovery that happens on startup.

> You delivered over-engineered solution and you'll have to support it forever. 

This isn't your problem, though? The current setup is very convenient for a lot of users. If you don't agree with some solutions, the system is pretty pluggable, so it should be fairly straight-forward to swap the bits you disagree with, or bypass them altogether.

**Comment by oliverjanik** [comment]
Another one:

https://docs.microsoft.com/en-us/aspnet/core/mvc/razor-pages/?tabs=visual-studio

Notice `OnGet` is not an override, even though you're deriving from PageModel.

I'm very dissapointed with these design decisions. ASPNetCore needs to be a stellar example of good engineering principles. This is someone discovered reflection and everything looks like a nail.

**Comment by davidfowl** [comment]
@oliverjanik when you design a framework that needs to invoke different method signatures based on various input, this is usually what it looks like. This shouldn't be a surprise as the application author writes a method signature with input arguments they want to bind and the framework has to find the method and invoke it appropriately. 

Using an interface here would be extremely prohibitive and would actually make the coding experience worse than it is today. If you've been around many .NET frameworks that are "dispatched into with variable arguments" this is usually what they look like.

There are also several advantages to support different types of methods without interfaces like being able to change behavior based on various types of input binding and return types (we actually take advantage of this in a variety of places).

Regardless, this issue isn't actionable and the feedback has been heard so I'm closing this out.

**Comment by oliverjanik** [comment]
Yeah, same argument. You traded static analysis for a bit more perceived flexibility. 

It bothers me on a deep level to see even JS ecosystem trending towards better static analysis (Typescript and Flow), which is a must in any larger project, and here we have one of the most important .net libs pushing in the other direction. 

This issue is very much actionable, but you have already made up your mind and think you did a good job. So there is no point discussing this further, I suppose.

**Comment by khellang** [comment]
> You traded static analysis for a bit more perceived flexibility.

Just because you can define methods with arbitrary arguments, without overriding something, it doesn't mean you've traded static analysis.

The types are still there, you can do as much static analysis on them as you want, just like you can on any other methods you define in your application. If anything, I'd argue that having a fixed signature for you to override would be even worse for static analysis.

I wonder why you think the current behavior is "trading static analysis"? Do you have a proposed signature for people to override (that doesn't do this)?

**Comment by oliverjanik** [comment]
Here's an example:

![image](https://user-images.githubusercontent.com/2280140/35498418-48d5b840-0522-11e8-87a9-bb4487bde9c2.png)

Shouldn't this kind of error be easily preventable during compilation? Instead that method is marked as unreachable code by Resharper and I get runtime exceptions.

I will be using StartupBase, thank you for the suggestion. I'm just not sure why this style (reflection, run-time exceptions) is encouraged.

**Comment by Korporal** [comment]
I agree with the other critics here that this design is bad and should at the very least by discouraged and a slicker alternative introduced. I don't know how something like this gets through a code review either!

**Comment by khellang** [comment]
Just implement `IStartup` or derive from `StartupBase` 😄
