### ISSUE TITLE
Update fwlink in startup error page

### ISSUE THREAD

**Issue by Tratcher** [aspnet/Hosting#1316]
This fwlink is on the Hosting startup error page with the text “Need Help?”
http://go.microsoft.com/fwlink/?LinkId=517394 
https://github.com/aspnet/Hosting/blob/b6da89f54cff11474f17486cdc55c2f21f2bbd6b/src/Microsoft.AspNetCore.Hosting/Startup/ExceptionPage/Views/ErrorPage.cshtml#L154

It forwards to https://www.asp.net/ rather than to any debugging instructions. It should at least forward to https://docs.microsoft.com/en-us/aspnet/core/index, if not a more specific debugging page. That said, I can’t find any docs for debugging startup errors.

**Comment by muratg** [comment]
@danroth27 bringing back to your attention. Please triage.

**Comment by Tratcher** [comment]
Here's one new doc that would be good to link to: https://github.com/aspnet/Docs/pull/5380/files.

**Comment by muratg** [comment]
@danroth27

**Comment by DamianEdwards** [comment]
Done
