### ISSUE TITLE
ASP.NET CORE MVC Compiler Exception - View Models and HtmlHelpers in separate project

### ISSUE THREAD

**Issue by joetherod** [aspnet/Hosting#1319]
Running latest version of VS 2017, have Docker for Windows installed on Windows 10 with host set to linux
Running application via VS in debug all works fine, when running in Release mode I get compiler exceptions of the views, cant find namespace or reference. My razors views are retried from database and are compiled at runtime. Why is this issue happening in Release mode and not in Debug. Tried adding references in RazorViewOptions and still not working. Looked at this post and didnt see a resolution.

https://github.com/aspnet/Razor/issues/715#issuecomment-198456302

Please help.

**Comment by joetherod** [comment]
The issue is related to my views in the database and during compilation the ViewImports isnt used to add to the namespaces. It works fine in debug mode, but not in Release mode via docker with linux as host. 
Is there a way to indicate to the razor view engine options to use the applications _ViewImports file that is in the project when it does a runtime compilation of razor view that is retrieved from the database??

**Comment by muratg** [comment]
This issue was moved to aspnet/Razor#2030
