### ISSUE TITLE
Design server capabilities (E.g. can SignalR advertise WebSockets?)

### ISSUE THREAD

**Issue by Tratcher** [aspnet/Hosting#1323]
@anurse I didn't see an existing bug for this.

Katana had a feature to for the server to report what capabilities it supported, like websockets. 
https://github.com/aspnet/AspNetKatana/blob/9f6e09af6bf203744feb5347121fe25f6eec06d8/src/Microsoft.Owin.Host.HttpListener/OwinServerFactory.cs#L56-L57

SignalR would use this information when advertising protocols to the client. 

In Core we have the same collection on IApplicationBuilder but we haven't populated it with anything.
https://github.com/aspnet/HttpAbstractions/blob/6cd313fcfaa81448fff2b65e74c9aa765dbdcff8/src/Microsoft.AspNetCore.Http.Abstractions/IApplicationBuilder.cs#L21-L24

We need to work out how this interacts with SignalR, Kestrel, HttpSys, WebSockets middleware, ANCM, NGinx, etc..

Tangent: What if we used a service instead? Katana never had those.

**Comment by muratg** [comment]
Dup of https://github.com/aspnet/Hosting/issues/1241
