### ISSUE TITLE
host.RunAsService() not found

### ISSUE THREAD

**Issue by johnsrude** [aspnet/Hosting#1338]
I am setting up a webserver for internal use using ASP.Net Core 2.x so I want to run it as a service.

I am following the instructions  [Host an ASP.NET Core app in a Windows Service](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/windows-service?tabs=aspnetcore2x):

```
public static void Main(string[] args)
{
    var pathToExe = Process.GetCurrentProcess().MainModule.FileName;
    var pathToContentRoot = Path.GetDirectoryName(pathToExe);

    var host = WebHost.CreateDefaultBuilder(args)
        .UseContentRoot(pathToContentRoot)
        .UseStartup<Startup>()
        .UseApplicationInsights()
        .Build();

    host.RunAsService();  <------- NOT FOUND
}
```

The problem is that RunAsService is undefined.   I have with the same code been able to run host.Run() though.

Here is the project file:

```
<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>netcoreapp2.0</TargetFramework>
    <StartupObject></StartupObject>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.All" Version="2.0.5" />
    <PackageReference Include="Microsoft.AspNetCore.Hosting.WindowsServices" Version="2.0.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="2.0.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="2.0.1" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="2.0.2" />
    <PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="2.0.1" />
    <PackageReference Include="Pomelo.EntityFrameworkCore.MySql.Design" Version="1.1.2" />
  </ItemGroup>
  <ItemGroup>
    <DotNetCliToolReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Tools" Version="2.0.2" />
  </ItemGroup>
</Project>
```

**Comment by Tratcher** [comment]
Do you have a Net Core app or a Net4x app? RunAsService is only available for Net4x.

**Comment by johnsrude** [comment]
It's Net Core.  Do I have to go through the whole reverse proxy thing to get this to work, then?

**Comment by Tratcher** [comment]
@johnsrude reverse proxies aren't involved here, the components needed for windows service support haven't been ported to .NET Core yet. You can use ASP.NET Core in a console application targeting .NET Framework 4.x to get windows service support.

You could also try 2.1.0-preview1, .NET Core support has been added there. https://github.com/aspnet/Hosting/pull/1189

**Comment by Drawaes** [comment]
Or you can use the excellent package by @dasmulli that provides windows services in .net core ;)

**Comment by DerGroncki** [comment]
Change the target framework to `<TargetFramework>net461</TargetFramework>` in the csproj-file of your application.

You need to install the NuGet package Microsoft.AspNetCore.Hosting.WindowsServices.

Add the following using statement to program.cs: `using Microsoft.AspNetCore.Hosting.WindowsServices;`

After this the methode "RunAsService()" will be available:

![image](https://user-images.githubusercontent.com/2815398/37254644-cf723282-2540-11e8-9457-35cbf12e307a.png)

**Comment by muratg** [comment]
@johnsrude If you'd like to use this on .NET Core, you'll have to move to 2.1.0-preview2. 

We decided not to bring this back to 2.0.x (https://github.com/aspnet/Hosting/issues/1229)
