### ISSUE TITLE
How to deploy Kestrel ASP.NET Core 2.0 on internal webserver

### ISSUE THREAD

**Issue by johnsrude** [aspnet/Hosting#1339]
I am trying to deploy a Kestrel web application on an internal webserver running Windows Server 2012.

Using the directions in  [Hosting in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/hosting?tabs=aspnetcore2x) I get the following code in Program.cs:
```
public class Program
{
    public static void Main(string[] args)
    {
        BuildWebHost(args).Run();
    }

    public static IWebHost BuildWebHost(string[] args) =>
   WebHost.CreateDefaultBuilder(args)
       .UseStartup<Startup>()
       // .UseKestrel(options =>{options.Listen(IPAddress.Loopback, 11111);})
       .Build();
}
```
This runs fine in Visual Studio 2017 CE using the debugging Kestrel on my development machine.

But when I publish it to my internal server, it times out, even if I uncomment the .UseKestrel() line.

If I simply specify the remote server in the URL of my browser, I get the IIS default splash page.

What do I need to do to get this running?

**Comment by Tratcher** [comment]
Did you follow these instructions?
https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/?tabs=aspnetcore2x
https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/troubleshoot

**Comment by johnsrude** [comment]
@Tratcher  I'm trying to avoid using IIS.  I should be able to access Kestrel itself, according to the docs.

**Comment by Tratcher** [comment]
Ah. If you're getting the IIS default splash page then you need to shut down IIS or change the port Kestrel is listening on.

**Comment by johnsrude** [comment]
@Tratcher I tried changing the port  by checking for unused ports with netstat and then using

```
   public static IWebHost BuildWebHost(string[] args) =>
   WebHost.CreateDefaultBuilder(args)
       .UseStartup<Startup>()
       .UseKestrel(options =>{options.Listen(IPAddress.Loopback, 11111);})
       .Build();
```
but no joy.

**Comment by Tratcher** [comment]
Are you trying to test it locally on that machine or remotely from your dev machine?

**Comment by johnsrude** [comment]
@Tratcher remotely from my dev machine

**Comment by Tratcher** [comment]
You can't use Loopback then, you need to use IPv6Any and make sure you have opened your firewall ports.

**Comment by Tratcher** [comment]
Get it working locally on that machine and then worry about making it work remotely.

**Comment by johnsrude** [comment]
@Tratcher How do I execute Kestrel on the remote server?  When I look at the published directory I don't see any executables.

**Comment by Tratcher** [comment]
`dotnet.exe myapp.dll`

**Comment by johnsrude** [comment]
Thanks.  That was enough information for me to get it to work.
