### ISSUE TITLE
Log messages messed up when logging in StartAsync

### ISSUE THREAD

**Issue by glennc** [aspnet/Hosting#1340]
If I write `_logger.LogInformation` as the only operation of the `StartAsync` method in an `IHostedService` then the output looks like this:

![image](https://user-images.githubusercontent.com/234688/36872130-112c3c80-1d59-11e8-8640-de1d56d8bda6.png)

The `Console.WriteLine` output is inserted into the logging message.

**Comment by glennc** [comment]
```csharp
   public class Program
    {
        public static async Task Main(string[] args)
        {
            await new HostBuilder()
                    .ConfigureLogging(loggerFactory =>
                    {
                        loggerFactory.SetMinimumLevel(LogLevel.Information);
                        loggerFactory.AddConsole();
                    })
                    .ConfigureServices(services => services.AddSingleton<IHostedService, MyHostedService>())
                    .RunConsoleAsync();
        }
    }

    public class MyHostedService : IHostedService
    {
        private ILogger<MyHostedService> _logger;

        public MyHostedService(ILogger<MyHostedService> logger, IHostingEnvironment env)
        {
            _logger = logger;
        }

        public Task StartAsync(CancellationToken cancellationToken)
        {
            _logger.LogInformation("Starting hosted service.");
            return Task.CompletedTask;
        }

        public Task StopAsync(CancellationToken cancellationToken)
        {
            _logger.LogInformation("Stopping hosted service.");
            return Task.CompletedTask;
        }
    }
```

**Comment by Tratcher** [comment]
Maybe it's finally time to kill the console writelines and move everything to logging....

**Comment by glennc** [comment]
I wrote a post saying no. But then thought that maybe you're right. I'll go do that on my fork and see if I am happy with the way it looks :).

**Comment by glennc** [comment]
Refreshing my memory about Console today. Locking on `Console.Out` will synchronize. But not for colors. So you the banner log goes green in this case but no text mangling. If you don't delay the startup banner, write inside the register callback, then it happens to be fine but not as correct.

If we put it through logging it looks like this:

![image](https://user-images.githubusercontent.com/234688/37318695-260d1510-2629-11e8-9842-b2b9b3a65395.png)

Which is probably fine. But it would change the way things work, you wouldn't see it in production with our default template for example. Since it would be part of the Microsoft filter on Logging. I assume that's correct anyway, I didn't actually try this...

**Comment by PureKrome** [comment]
Hi 👋 Any further info on this, please?

Just started playing with logging and noticed this exact thing and came here to log an issue but found this one, first (phew! :)  )

Compared to other issues, this is probably tiny ... but hopefully it might get some quick resolution and fixed?

**Comment by totht91** [comment]
This is a tiny but painful bug for us. We would like to log the application startup events so logger intergration would be nice.

**Comment by glennc** [comment]
For now I think the only real option is to use `SuppressStatusMessages` pn the WebHost options to stop the text from being logged and mangling content.

**Comment by totht91** [comment]
Aren't there any chance to user `ILogget` instead of `Console.WriteLine`?

**Comment by glennc** [comment]
Sure, there is a chance we will change it to that. My comment was meant to talk about the options you have right now.

**Comment by davidfowl** [comment]
Fixing this with #1584
