### ISSUE TITLE
DataProtection - PersistKeysToFileSystem in Docker hosted in Linux

### ISSUE THREAD

**Issue by joetherod** [aspnet/Hosting#1343]
Trying to AddDataProtection for MVC Core app.
services.AddDataProtection()
                .PersistKeysToFileSystem(new DirectoryInfo("etc/keys/"))
                .SetApplicationName("AppName")

The Directory is a configured volume mount in the linux host.
If I dont use the volume mount, it works.
Volume mount is needed as per described in MS Docs since the app is hosted in many Docker containers.
Please advise.

Works locally. But when configured to a Docker container hosted in linux, I get the following exception on startup:

{"Timestamp":"2018-03-08T20:45:37.4873753+00:00","Level":"Error","MessageTemplate":"An error occurred while reading the key ring.","Exception":"System.IO.IOException: Unknown error 524\n   at System.IO.UnixFileSystem.MoveFile(String sourceFullPath, String destFullPath)\n   at System.IO.File.Move(String sourceFileName, String destFileName)\n   at Microsoft.AspNetCore.DataProtection.Repositories.FileSystemXmlRepository.StoreElementCore(XElement element, String filename)\n   at Microsoft.AspNetCore.DataProtection.Repositories.FileSystemXmlRepository.StoreElement(XElement element, String friendlyName)\n   at Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager.Microsoft.AspNetCore.DataProtection.KeyManagement.Internal.IInternalXmlKeyManager.CreateNewKey(Guid keyId, DateTimeOffset creationDate, DateTimeOffset activationDate, DateTimeOffset expirationDate)\n   at Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager.CreateNewKey(DateTimeOffset activationDate, DateTimeOffset expirationDate)\n   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingProvider.CreateCacheableKeyRingCore(DateTimeOffset now, IKey keyJustAdded)\n   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingProvider.GetCurrentKeyRingCore(DateTime utcNow)","Properties":{"EventId":{"Id":48},"SourceContext":"Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingProvider","RequestId":"0HLC55SODK05P:00000001","RequestPath":"/_health","CorrelationId":null,"ConnectionId":"0HLC55SODK05P"}}

**Comment by Tratcher** [comment]
@natemcmaster

**Comment by natemcmaster** [comment]
This appears to be an issue with your Docker host, not with ASP.NET Core. System.IO.File.Move is failing to write into the mounted directory. Can you verify this with a minimal repro like this?
```c#
public static void Main(string[] args)
{
    var tempFile = Path.Combine(Path.GetTempPath(), "test.txt");
    File.WriteAllText(tempFile, "Hello");
    File.Move(tempFile, "etc/keys/test.txt");
}
```

**Comment by joetherod** [comment]
Write and move works, but still getting exception.

An error occurred while reading the key ring.","Exception":"System.IO.IOException: Unknown error 524\n   at System.IO.UnixFileSystem.MoveFile(String sourceFullPath, String destFullPath)\n   at System.IO.File.Move(String sourceFileName, String destFileName)\n   at Microsoft.AspNetCore.DataProtection.Repositories.FileSystemXmlRepository.StoreElementCore(XElement element, String filename)\n   at Microsoft.AspNetCore.DataProtection.Repositories.FileSystemXmlRepository.StoreElement(XElement element, String friendlyName)\n   at Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager.Microsoft.AspNetCore.DataProtection.KeyManagement.Internal.IInternalXmlKeyManager.CreateNewKey(Guid keyId, DateTimeOffset creationDate, DateTimeOffset activationDate, DateTimeOffset expirationDate)\n   at Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager.CreateNewKey(DateTimeOffset activationDate, DateTimeOffset expirationDate)\n   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingProvider.CreateCacheableKeyRingCore(DateTimeOffset now, IKey keyJustAdded)\n   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingProvider.GetCurrentKeyRingCore(DateTime utcNow)","Properties":{"EventId":{"Id":48},"SourceContext":"Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingProvider","RequestId":"0HLC597NS53I0:00000001","RequestPath":"/_health","CorrelationId":null,"ConnectionId":"0HLC597NS53I0"}}

An unhandled exception was thrown by the application.","Exception":"System.Security.Cryptography.CryptographicException: An error occurred while trying to encrypt the provided data. Refer to the inner exception for more information. ---> System.IO.IOException: Unknown error 524\n   at System.IO.UnixFileSystem.MoveFile(String sourceFullPath, String destFullPath)\n   at System.IO.File.Move(String sourceFileName, String destFileName)\n   at Microsoft.AspNetCore.DataProtection.Repositories.FileSystemXmlRepository.StoreElementCore(XElement element, String filename)\n   at Microsoft.AspNetCore.DataProtection.Repositories.FileSystemXmlRepository.StoreElement(XElement element, String friendlyName)\n   at Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager.Microsoft.AspNetCore.DataProtection.KeyManagement.Internal.IInternalXmlKeyManager.CreateNewKey(Guid keyId, DateTimeOffset creationDate, DateTimeOffset activationDate, DateTimeOffset expirationDate)\n   at Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager.CreateNewKey(DateTimeOffset activationDate, DateTimeOffset expirationDate)\n   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingProvider.CreateCacheableKeyRingCore(DateTimeOffset now, IKey keyJustAdded)\n   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingProvider.GetCurrentKeyRingCore(DateTime utcNow)\n   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Protect(Byte[] plaintext)\n   --- End of inner exception stack trace ---\n   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Protect(Byte[] plaintext)\n   at Microsoft.AspNetCore.Session.CookieProtection.Protect(IDataProtector protector, String data)\n   at Microsoft.AspNetCore.Session.SessionMiddleware.<Invoke>d__9.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.<Invoke>d__3.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.<Invoke>d__3.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.<ProcessRequestsAsync>d__185`1.MoveNext()","Properties":{"ConnectionId":"0HLC597NS53I0","TraceIdentifier":"0HLC597NS53I0:00000001","EventId":{"Id":13,"Name":"ApplicationError"},"SourceContext":"Microsoft.AspNetCore.Server.Kestrel","RequestId":"0HLC597NS53I0:00000001","RequestPath":"/_health","CorrelationId":null}}

**Comment by natemcmaster** [comment]
Can you provide more log info? There should be an INFO log item just before this File.Move

https://github.com/aspnet/DataProtection/blob/8a42c24f46d728b4728e6b20febd0a11c1111df2/src/Microsoft.AspNetCore.DataProtection/Repositories/FileSystemXmlRepository.cs#L232-L233

**Comment by joetherod** [comment]
services.AddDataProtection()
                .PersistKeysToFileSystem(new DirectoryInfo("etc/talentbrew/keys"))
                .SetApplicationName("XXX")
                .SetDefaultKeyLifetime(TimeSpan.FromDays(365));

Level":"Information","MessageTemplate":"Writing data to file '{FileName}'.","Properties":{"FileName":"/app/etc/talentbrew/keys/key-fb6f8187-5606-445b-9591-3c268c59ff84.xml","EventId":{"Id":39},"SourceContext":"Microsoft.AspNetCore.DataProtection.Repositories.FileSystemXmlRepository","RequestId":"0HLC5BJ5EVUU9:00000001","RequestPath":"/_health","CorrelationId":null,"ConnectionId":"0HLC5BJ5EVUU9"}

"Level":"Error","MessageTemplate":"Connection id \"{ConnectionId}\", Request id \"{TraceIdentifier}\": An unhandled exception was thrown by the application.","Exception":"System.Security.Cryptography.CryptographicException: An error occurred while trying to encrypt the provided data. Refer to the inner exception for more information. ---> System.IO.IOException: Unknown error 524\n   at System.IO.UnixFileSystem.MoveFile(String sourceFullPath, String destFullPath)\n   at System.IO.File.Move(String sourceFileName, String destFileName)\n   at Microsoft.AspNetCore.DataProtection.Repositories.FileSystemXmlRepository.StoreElementCore(XElement element, String filename)\n   at Microsoft.AspNetCore.DataProtection.Repositories.FileSystemXmlRepository.StoreElement(XElement element, String friendlyName)\n   at Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager.Microsoft.AspNetCore.DataProtection.KeyManagement.Internal.IInternalXmlKeyManager.CreateNewKey(Guid keyId, DateTimeOffset creationDate, DateTimeOffset activationDate, DateTimeOffset expirationDate)\n   at Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager.CreateNewKey(DateTimeOffset activationDate, DateTimeOffset expirationDate)\n   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingProvider.CreateCacheableKeyRingCore(DateTimeOffset now, IKey keyJustAdded)\n   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingProvider.GetCurrentKeyRingCore(DateTime utcNow)\n   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Protect(Byte[] plaintext)\n   --- End of inner exception stack trace ---\n   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Protect(Byte[] plaintext)\n   at Microsoft.AspNetCore.Session.CookieProtection.Protect(IDataProtector protector, String data)\n   at Microsoft.AspNetCore.Session.SessionMiddleware.<Invoke>d__9.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.<Invoke>d__3.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.<Invoke>d__3.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.<ProcessRequestsAsync>d__185`1.MoveNext()","Properties":{"ConnectionId":"0HLC5BJ5EVUU9","TraceIdentifier":"0HLC5BJ5EVUU9:00000001","EventId":{"Id":13,"Name":"ApplicationError"},"SourceContext":"Microsoft.AspNetCore.Server.Kestrel","RequestId":"0HLC5BJ5EVUU9:00000001","RequestPath":"/_health","CorrelationId":null}}

"Level":"Information","MessageTemplate":"Creating key {KeyId:B} with creation date {CreationDate:u}, activation date {ActivationDate:u}, and expiration date {ExpirationDate:u}.","Properties":{"KeyId":"fb6f8187-5606-445b-9591-3c268c59ff84","CreationDate":"2018-03-09T01:33:27.3851082+00:00","ActivationDate":"2018-03-09T01:33:27.3843013+00:00","ExpirationDate":"2019-03-09T01:33:27.3843013+00:00","EventId":{"Id":58},"SourceContext":"Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager","RequestId":"0HLC5BJ5EVUU9:00000001","RequestPath":"/_health","CorrelationId":null,"ConnectionId":"0HLC5BJ5EVUU9"},"Renderings":{"KeyId":[{"Format":"B","Rendering":"{fb6f8187-5606-445b-9591-3c268c59ff84}"}],"CreationDate":[{"Format":"u","Rendering":"2018-03-09 01:33:27Z"}],"ActivationDate":[{"Format":"u","Rendering":"2018-03-09 01:33:27Z"}],"ExpirationDate":[{"Format":"u","Rendering":"2019-03-09 01:33:27Z"}]}}

Level":"Error","MessageTemplate":"An error occurred while reading the key ring.","Exception":"System.IO.IOException: Unknown error 524\n   at System.IO.UnixFileSystem.MoveFile(String sourceFullPath, String destFullPath)\n   at System.IO.File.Move(String sourceFileName, String destFileName)\n   at Microsoft.AspNetCore.DataProtection.Repositories.FileSystemXmlRepository.StoreElementCore(XElement element, String filename)\n   at Microsoft.AspNetCore.DataProtection.Repositories.FileSystemXmlRepository.StoreElement(XElement element, String friendlyName)\n   at Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager.Microsoft.AspNetCore.DataProtection.KeyManagement.Internal.IInternalXmlKeyManager.CreateNewKey(Guid keyId, DateTimeOffset creationDate, DateTimeOffset activationDate, DateTimeOffset expirationDate)\n   at Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager.CreateNewKey(DateTimeOffset activationDate, DateTimeOffset expirationDate)\n   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingProvider.CreateCacheableKeyRingCore(DateTimeOffset now, IKey keyJustAdded)\n   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingProvider.GetCurrentKeyRingCore(DateTime utcNow)","Properties":{"EventId":{"Id":48},"SourceContext":"Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingProvider","RequestId":"0HLC5BJ5EVUU9:00000001","RequestPath":"/_health","CorrelationId":null,"ConnectionId":"0HLC5BJ5EVUU9"}}

**Comment by natemcmaster** [comment]
Issue moved to [aspnet/Home #2941](https://github.com/aspnet/Home/issues/2941) via [**ZenHub**](https://www.zenhub.com/)
