### ISSUE TITLE
Multiple Sites in IIS 8.5 with mixed frameworks, running on port 80

### ISSUE THREAD

**Issue by Serjster** [aspnet/Hosting#1344]
Hello,

I also asked this question here: https://serverfault.com/q/900811/161144

I have read many, many things trying to solve this problem and I feel hopeless at this point... please help! I have a Win 2012 server running on my VM in Azure. For over a year, I've had 2 DotNet Core 1.X sites running, as well as 2 PHP sites running, quite nicely as separate Websites in IIS all bound to port 80, with a Host for each of them, like app.mydomain.com and api.mydomain.com. Recently, I've updated my site to DotNet Core 2. I installed the version 2 Windows Hosting package and now my Core 2.0 Site starts fine, but neither the 1.0 or the PHP sites are able to start with a message:

The process cannot access the file because it is being used by another process.

I've trying doing all of the NET... commands to see which process is running on port 80 (Of course I have Process ID: 4) which I believe I tracked down to be World Wide Web Publishing Service. Of course, I can't just stop that service because IIS needs that service to be running in order to start itself. So I'm stuck it seems and am feeling very frustrated right now, hopefully someone can help.

**Comment by Tratcher** [comment]
Please list your current IIS bindings for each site. 

Also, what does your Program.Main look like for your Core2 site?

**Comment by Serjster** [comment]
Hey Tratcher, thanks for the reply:

`Program.Main`:

```
       public static void Main(string[] args)
        {
            var host = new WebHostBuilder()
                .UseKestrel()
                .UseContentRoot(Directory.GetCurrentDirectory())
                .UseIISIntegration()
                .UseStartup<Startup>()
                .Build();
        }
```

See image for bindings:
![tb](https://user-images.githubusercontent.com/3606218/37241261-a772e886-2413-11e8-899a-7a1677dbe17a.png)

**Comment by Tratcher** [comment]
There's nothing here that would indicate a .NET Core specific problem, these are all generic IIS binding configurations. @shirhatti any suggestions?

**Comment by Serjster** [comment]
So... on a hunch, I removed my SSL binding and that allowed me to run those apps! That's progress, but what if I need SSL?

**Comment by Tratcher** [comment]
Sounds like an SNI issue. @shirhatti are there any special steps for configuring SNI?

**Comment by shirhatti** [comment]
@Serjster I don't follow where you're seeing this message "The process cannot access the file because it is being used by another process." Is that in the eventlog? If so, can you share the provider name and event id as well.

Also, can you share the output of running `Get-WebBinding` in a powershell prompt? As a sanity check I want to ensure your `sslFlags` are correctly set.

**Comment by Serjster** [comment]
I am seeing this message as soon as hit `Start` for the site:
![iis](https://user-images.githubusercontent.com/3606218/37313573-7aee5904-2615-11e8-9240-5d0263fc184c.png)

`Get-WebBinding`:
![image](https://user-images.githubusercontent.com/3606218/37313644-c0163e34-2615-11e8-86e4-7e79ae30ad86.png)

**Comment by Serjster** [comment]
SSL Site Binding:
![image](https://user-images.githubusercontent.com/3606218/37313723-21cd320e-2616-11e8-9192-0a8829584a8c.png)

I also noticed that my certificate is expired. Would that cause this problem?

**Comment by Serjster** [comment]
nm, made a new unexpired Cert and it is still giving me that error.

**Comment by shirhatti** [comment]
I have a hypothesis that SSL is just a red herring here. It is simply the fact that something else is already bound to port 443. Try creating an HTTPS binding with a different port number.
See https://support.microsoft.com/en-us/help/973094/error-0x80070020-when-you-try-to-start-a-web-site-in-iis-7-0

**Comment by Serjster** [comment]
Yep, that did work with `port 444` using that link, using this command `netstat -aon | find ":443"` I saw that my VPN software was also running on that port. Thanks for your help. Now I need to figure out how to get VPN working on a diffrnet port... and also strange, how did it work before I made the upgrades?

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
