### ISSUE TITLE
Add HostBuilderContext on IHostBuilder

### ISSUE THREAD

**Issue by glennc** [aspnet/Hosting#1345]
If we expect extension methods like this to exist:

```csharp
        public static IWebHostBuilder UseRabbitMq<T>(this IWebHostBuilder builder,
                                                     Action<RabbitMQOptions> options)
        {
            builder.ConfigureServices(services =>
            {
                services.Configure(options);
                services.AddSingleton<IHostedService, RabbitMQHostedService<T>>();
            });
            return builder;
        }
```

Then it would presumably also be nice to be able to do something like this:

```csharp
public static IWebHostBuilder UseRabbitMq<T>(this IWebHostBuilder builder, Action<HostBuilderContext, RabbitMQOptions> options)
```

Where values can be pulled from Configuration directly as they are for first class methods on the builder. But if you wanted to actually implement this then we would need to add `HostBuilderContext` to `IHostBuilder`.

Alternatively, what would the idiomatic way be to create and configure a `HostedService` without this?

@davidfowl @Tratcher

**Comment by muratg** [comment]
@Tratcher will investigate if this is possible currently.

**Comment by Tratcher** [comment]
The other ConfigureServices overload already exposes the builder context. This is available both for IWebHostBuilder and IHostBuilder.
`builder.ConfigureServices((builderContext, services) =>`

**Comment by muratg** [comment]
@glennc what's the status?

**Comment by muratg** [comment]
@glennc Is the other ovlead workable? Good to close this one?
