### ISSUE TITLE
HostLifetime in its current form doesn't work for WindowsServices

### ISSUE THREAD

**Issue by glennc** [aspnet/Hosting#1347]
Creating a HostLifetime to work with ServiceBase doesn't currently work.

We need to re-evaluate what we want to do here before preview2. This was one of the major reasons we did HostLifetime. If it isn't going to work we need to change it.

@davidfowl @Tratcher @muratg

**Comment by muratg** [comment]
Do we know why already (and just need to design a solution), or do we need to investigate further?

**Comment by glennc** [comment]
The Run method of ServiceBase blocks and our current surface area doesn't really let you handle that in a 100% correct way. You can kind of get it to work but it's not really the way you want it to be.

**Comment by glennc** [comment]
I can put together some code with comments that shows the problems.

**Comment by Rinsen** [comment]
Do you have any sample on that "kind of get it to work" @glennc ? I tried to get the sample to work but failed...

**Comment by Tratcher** [comment]
@Rinsen putting a Task.Run around the Run call here is the main workaround. https://github.com/aspnet/Hosting/blob/10a56f198169bc75bd07efbfb7a8d5a04630aa0a/samples/GenericHostSample/ServiceBaseLifetime.cs#L36

**Comment by muratg** [comment]
Any design work left on this one?  Also, what's the cost?

**Comment by Tratcher** [comment]
The PR is waiting for @davidfowl's review. We'll see if he accepts the modified design.

**Comment by Rinsen** [comment]
Awesome! :) 

Thanks @Tratcher and I am looking forward to this feature in the 2.1 release! So very good to have the full stack with loggers and all in a Windows Service for background tasks 👍
