### ISSUE TITLE
Restart .NetCore 2.0 app

### ISSUE THREAD

**Issue by Eilon** [aspnet/Hosting#1353]
_From @jasieg on March 1, 2018 7:45_

I'm using IApplicationLifetime to stop my application, however it doesn't contain method for restart. How can it be achieved? I played a bit with CancellationToken, but on linux all it does is stop application.

_Copied from original issue: dotnet/core#1316_

**Comment by Eilon** [comment]
_From @embryologist on March 1, 2018 10:15_

Does this help?
https://stackoverflow.com/questions/36121999/how-to-restart-asp-net-core-app-programmatically

**Comment by Eilon** [comment]
_From @jasieg on March 1, 2018 10:38_

That's what I meant by playing with CancellationToken. It works on Windows, but not on Linux.

**Comment by Eilon** [comment]
_From @Petermarcu on March 15, 2018 4:26_

@Eilon @muratg @DamianEdwards

**Comment by muratg** [comment]
@jasieg Just to clarify, in the example you shared, IIS does the restart in Windows case, it's not an ASP.NET Core feature. So this is more of a feature request. 

Could you describe your scenario?  Perhaps it can be achieved in some other way.

**Comment by Tratcher** [comment]
Restart is a function of your application launcher (e.g. IIS), not a function of ASP.NET Core.

[dotnet watch run](https://docs.microsoft.com/en-us/aspnet/core/tutorials/dotnet-watch) does something like this for development environments.
Here are some similar suggestions for Apache and systemd https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/linux-apache
Here's a general example for nginx and supervisor http://jakeydocs.readthedocs.io/en/latest/publishing/linuxproduction.html#monitoring-our-web-application

**Comment by karthicksundararajan** [comment]
Initially I've played arround with CancellationToken, as @Eilon mentioned it works on Windows and not on Linux. Therefore, I was looking on a proper solution to restart the asp.net core app. Finally, I found a way to restart using C#7.1 feature [async Main](https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-7-1#async-main) method and `await webHost.RunAsync()` inside a while loop. Loop can be exited on receiving CancelKeyPress (Ctrl+C). Could this be a solution?

`
public class Program
    {
        public static async Task Main(string[] args)
        {
            bool isCancelKeyPressed = false;

            Console.CancelKeyPress += (sender, eventArgs) =>
            {
                isCancelKeyPressed = true;
                // Don't terminate the process immediately, wait for the Main thread to exit gracefully.
                eventArgs.Cancel = true;
            };

            while (true)
            {
                Console.WriteLine("Application is starting");
                await ApplicationManager.Instance.Start(args);
                Console.WriteLine("Application has been terminated");
                if (isCancelKeyPressed)
                    break;
            }
        }

        public static IWebHostBuilder CreateWebHostBuilder(string[] args) =>
            WebHost.CreateDefaultBuilder(args)
                .UseStartup<Startup>();
    }
`

Complete source code https://github.com/deviserplatform/deviserplatform/blob/master/src/Deviser.WI/Program.cs

**Comment by jshin47** [comment]
@Tratcher , what do you think of the in-process restart solution that @karthicksundararajan proposes using `async Main` ? I know it works - would it break the assumptions of `IApplicationLifetime` ?

**Comment by Tratcher** [comment]
There's nothing wrong with running a web app in a loop (but you should dispose it though), IApplicationLifetime is not related to process lifetime. The one place you have to be careful is the WebHost.RunAsync methods that do tie the webhost to [CTL+C, ProcessExit](https://github.com/aspnet/Hosting/blob/f9d145887773e0c650e66165e0c61886153bcc0b/src/Microsoft.AspNetCore.Hosting/WebHostExtensions.cs#L155-L156), etc..

Stay clear of the Run methods entirely in this model. Call StartAsync, listen for IApplicationLifetime.Stopping, and wire up your own key listeners.

**Comment by Tratcher** [comment]
Note the in process loop does not give you any real fault tolerance, nor does it let you redeploy any part of the app.

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
