### ISSUE TITLE
host.Run(cancellationToken) 

### ISSUE THREAD

**Issue by radloori** [aspnet/Hosting#1354]
I have bee using host.Run(cancellationToken) in ASP.Net Core 1.1 and it was working fine.

But, this does not work in ASP.Net Core 2.0. 

Error:
`'IWebHost' does not contain a definition for 'Run' and the best extension method overload 'RunExtensions.Run(IApplicationBuilder, RequestDelegate)' requires a receiver of type 'IApplicationBuilder'`

**Comment by Tratcher** [comment]
You want these:
https://github.com/aspnet/Hosting/blob/a63932a492513cdeb4935661145084cad2ae5521/src/Microsoft.AspNetCore.Hosting/WebHostExtensions.cs#L57-L74
