### ISSUE TITLE
Flaky tests: Port collision issues. 

### ISSUE THREAD

**Issue by muratg** [aspnet/Hosting#1358]
_From @jkotalik on March 17, 2018 1:50_

Https and NTLM tests still use static ports, which causes arbitrary tests to fail: https://github.com/aspnet/IISIntegration/blob/dev/test/IISIntegration.FunctionalTests/OutOfProcess/HttpsTest.cs#L31

_Copied from original issue: aspnet/IISIntegration#691_

**Comment by HaoK** [comment]
Should we try to check if a port is in use, and try another random port in this range if its taken?

**Comment by Tratcher** [comment]
That would be a good start. We already have GetNextPort() for doing this, but we'd have to be able to give it a bounded range.

**Comment by HaoK** [comment]
Is there something specific I need to have installed to build in IISIntegration?

I installed VS, turned on IIS, added the Development with IIS design time in VS...

But i still get this when I run build.cmd:

```
C:\Users\haok\.dotnet\buildtools\korebuild\2.2.0-preview1-17060\modules\KoreBuild.Tasks\module.targets(141,5): error : Could not find an installation of Visual Studio that satisifies the specified requirements in C:\Github\IISIntegration/korebuild.json. See https://docs.microsoft.com/en-us/visualstudio/install/workload-component-id-vs-community for more details on any missing components. [C:\Users\haok\.dotnet\buildtools\korebuild\2.2.0-preview1-17060\KoreBuild.proj]
```

**Comment by Tratcher** [comment]
@jkotalik

**Comment by HaoK** [comment]
@Tratcher so a new helper that does something like this (which I found off SO)?   Basically find a port, then use that for the port instead of 44394 always in `ApplicationBaseUriHint = "https://localhost:44394/"`

```
public static int GetOpenPort(int startPort = 2555)
{
    int portStartIndex = startPort;
    int count = 99;
    IPGlobalProperties properties = IPGlobalProperties.GetIPGlobalProperties();
    IPEndPoint[] tcpEndPoints = properties.GetActiveTcpListeners();

    List<int> usedPorts = tcpEndPoints.Select(p => p.Port).ToList<int>();
    int unusedPort = 0;

    unusedPort = Enumerable.Range(portStartIndex, 99).Where(port => !usedPorts.Contains(port)).FirstOrDefault();
    return unusedPort;
}
```

**Comment by Tratcher** [comment]
Something like that, though you need an upper and lower boundary.

**Comment by HaoK** [comment]
GetNextPort does a bind against 0 though, I don't think that will give us the range checking at all right?

.Can we just scan the range and bind...will bind fail if the port is in use?

**Comment by HaoK** [comment]
Fixed in https://github.com/aspnet/IISIntegration/pull/874
