### ISSUE TITLE
Override ASPNETCORE_ environment variable settings

### ISSUE THREAD

**Issue by tugberkugurlu** [aspnet/Hosting#1372]
I am trying to override `ASPNETCORE_` environment variable settings. The below is what I am trying now:

```
        public static void Run(string[] args)
        {
            BuildWebHost(args).Run();
        }

        private static IWebHost BuildWebHost(string[] args)
        {
            return WebHost.CreateDefaultBuilder(args)
                .ConfigureAppConfiguration(builder => builder
                    .AddEnvironmentVariables("FOO_ASPNETCORE_")
                    .AddCommandLine(args))
                .UseStartup<Startup>()
                .UseHttpSys(options =>
                {
                    options.Authentication.Schemes = AuthenticationSchemes.NTLM | AuthenticationSchemes.Negotiate;
                    options.Authentication.AllowAnonymous = true;
                })
                .Build();
        }
```

Even with this, if `ASPNETCORE_URLS` environment variable is set, it's being used by the hosting environment. 

What is the way to override the `ASPNETCORE_` settings? Being able to prefix this would also be OK for my purposes.

**Comment by tugberkugurlu** [comment]
I believe doing this is the aggressive bit which overrides any settings apart from directly calling `UseUrls`.

https://github.com/aspnet/Hosting/blob/1f5379e38d201d329e28b50ecd080e999d274678/src/Microsoft.AspNetCore.Hosting/WebHostBuilder.cs#L59

Am I on the right track here?

**Comment by Tratcher** [comment]
The line you referenced is in the constructor, before any possible calls to UseUrls.

**Comment by Tratcher** [comment]
It's this line that's giving you grief:
https://github.com/aspnet/Hosting/blob/1f5379e38d201d329e28b50ecd080e999d274678/src/Microsoft.AspNetCore.Hosting/WebHostBuilder.cs#L46

**Comment by Tratcher** [comment]
To clarify, what do you want to override ASPNETCORE_ environment variables with?

**Comment by Tratcher** [comment]
Any config you add that defines the URLS config key (including UseUrls) would override the ASPNETCORE_URLS environment variable. The only other way to suppress this is to configure URLs directly in HttpSys's options.

**Comment by Tratcher** [comment]
Oh, I see what's wrong, ConfigureAppConfiguration is too late, you need to configure the host, not the app. Let me find that bug...

**Comment by Tratcher** [comment]
https://github.com/aspnet/MetaPackages/issues/247#issuecomment-350033881

**Comment by tugberkugurlu** [comment]
I will see if UseConfiguration does the trick but I tried that and it didn’t work as far as I remember. Will try again.

**Comment by tugberkugurlu** [comment]
Nice one, the below one definitely works 🎉 

```
private static IWebHost BuildWebHost(string[] args)
{
    var hostConfig = new ConfigurationBuilder()
        .AddEnvironmentVariables("FOO_ASPNETCORE_")
        .AddCommandLine(args)
        .Build();

    return WebHost.CreateDefaultBuilder(args)
        .UseConfiguration(hostConfig)
        .UseStartup<Startup>()
        .UseHttpSys(options =>
        {
            options.Authentication.Schemes = AuthenticationSchemes.NTLM | AuthenticationSchemes.Negotiate;
            options.Authentication.AllowAnonymous = true;
        })
        .Build();
}
```

Thanks @Tratcher!
