### ISSUE TITLE
Thinner RequestServicesMiddleware (#1360) removes ability to sub out request services

### ISSUE THREAD

**Issue by tillig** [aspnet/Hosting#1377]
This change [to RequestServicesMiddleware](https://github.com/aspnet/Hosting/commit/b3625b8173b19935e22b4fe5ac0ea64edd934bd4#diff-682be05953da51fb7d5c7ed8130f8a5b) removes a check to see if the `IServiceProvidersFeature` is null and only put it in if it's required.

Unfortunately, the RequestServicesMiddleware _also_ takes the `IServiceScopeFactory` in during its constructor rather than during `Invoke`, which, for multitenant support, is too early - you can't identify a tenant that early in the pipeline since you don't have a context, which means you can't provide info to the service scope factory on which tenant needs a scope.

As a concrete example, [the Autofac ASP.NET Core multitenant integration](https://github.com/autofac/Autofac.AspNetCore.Multitenant) intentionally inserts itself in front of the RequestServicesMiddleware so it can put its own request services in place first, assuming the RequestServicesMiddleware will later effectively become a no-op.

This is a pretty painful breaking change to 2.1 - would you be open to a PR to put the null check back in RequestServicesMiddlware? Alternatively, is there a way to remove the default RequestServicesMiddleware altogether?

**Comment by Tratcher** [comment]
@davidfowl
