### ISSUE TITLE
Create middleware to handle x- override/forwarded header values

### ISSUE THREAD

**Issue by Tratcher** [aspnet/Hosting#138]
When the client can't create quite the request they want, or when an intermediary needs to modify it, then they can tunnel the extra data in an X- header.

Create one or more middleware that understands common override headers and applies the requested overrides to the request.

Some common items to override:
Host: X-Forwarded-Host
Method: X-Http-Method-Override
Scheme: X-Forwarded-Proto

**Comment by danroth27** [comment]
This is being done in the [BasicMiddleware](https://github.com/aspnet/basicmiddleware) repo.
