### ISSUE TITLE
Calls to IWebHostBuilder.Build() are failing when configured with a startup assembly passed in as string

### ISSUE THREAD

**Issue by fiksen99** [aspnet/Hosting#1382]
### Title
Calls to IWebHostBuilder.Build() are failing when configured with a startup assembly passed in as string

### Functional impact
Calling .Build() on a Builder configured with an .exe assembly via it's string Assembly name fails at dependency injection time. With the default ASP.NET Core + .NET Framework project, the following is thrown:
`System.InvalidOperationException: 'Unable to resolve service for type 'Microsoft.Extensions.Configuration.IConfiguration' while attempting to activate 'WebAppWithAfterBuildTarget.Startup'.'`

### Minimal repro steps
1. Create a simple library project named 'MsBuildTask' targeting net462. 
2. Add a reference to `Microsoft.Build.[Framework/Utilities.v4.0]` assemblies, and a reference to the `Microsoft.AspNetCore + .Http.Abstractions` nugets.

3. Create a class like so: 
```
    public class RunStartup : Microsoft.Build.Utilities.Task
    {
        public string AssemblyToLoad { get; set; }

        public override bool Execute()
        {
            var startupAssembly = Assembly.LoadFrom(Path.Combine(Directory.GetCurrentDirectory(), AssemblyToLoad));
            var builder = WebHost.CreateDefaultBuilder();
            builder.UseStartup(startupAssembly.FullName);
            var host = builder.Build();

            // ... do more stuff
            return true;
        }
    }
```

4. Build the MsBuildTask project, copy a path to the dll output (used below).

5. Create an ASP.NET Core 2.0 + .Net Framework 462 project in visual studio.

6. In the webapp csproj file, add
```
  <UsingTask AssemblyFile="..\MsBuildTask\bin\Debug\net462\MsBuildTask.dll" TaskName="RunStartup" />
  <Target Name="RunStartup" AfterTargets="AfterBuild">
    <RunStartup AssemblyToLoad="$(OutputPath)$(AssemblyName).exe" />
  </Target>
```

7. Build the webapp. (for debugging purposes, in MsBuildTask>Properties>Debug, you can set Launch as executable, Executable as the path to msbuild, and Application arguments as the path to the webapp, then just hit F5 on the MsBuildTask).

### Expected result
The build task would complete successfully, we could do more interesting stuff with the host.

### Actual result
Observe that during the AfterBuild targets section runs the `MsBuildTask.RunStartup.Execute` method.

This fails at the `.Build()` stage as `IConfiguration` has not been registered.

### Further technical details
I've tried copying over the Startup to this project (whilst adding the AspNetCore.Mvc nuget as necessary) and running `.UseStartup<Startup>()` as in a normal ASP.NET Core app and this succeeds. It is when referencing the assembly by name that I hit this error where the dependencies don't seem to be registered.

**Comment by fiksen99** [comment]
Thaks for the feedback @davidfowl . Unfortunately I'm struggling a bit even after sitting down with colleagues. Loading the assembly via 

`var loadedAssembly = Assembly.Load(AssemblyName.GetAssemblyName(Path.Combine(Directory.GetCurrentDirectory(), AssemblyToLoad)));`

results in the same issue. I've tried converting the output type of the assembly we're using to be dll (previously it was exe) and load that assembly, however I've had no luck.

I've also looked into running code alongside the loaded assembly in a new app domain and unfortunately didn't get anywhere. It also looks like it's not possible to run two processes (my MSBuild Task + the loaded assembly) in the same app domain. 

As such, I'm a bit stumped as to what to try from here. I've also tried using reflection via appDomains with domain.CreateInstanceFromAndUnwrap, however I can't see how to hook in the dependency injection required for the constructor here. A couple of references I looked at [here](https://stackoverflow.com/questions/6816032/c-sharp-reflection-appdomain-execute-same-assembly-from-different-folders) and [here](https://stackoverflow.com/questions/3588648/usage-of-appdomain-createinstancefromandunwrap).

Any further pointers you could provide would be really helpful please!

**Comment by muratg** [comment]
Hi. It looks like this is a question about how to use ASP.NET Core. While we do our best to look through all the issues filed here, to get a faster response we suggest posting your questions to [StackOverflow](https://www.stackoverflow.com) using the 'asp.net-core' tag.
