### ISSUE TITLE
IIS deployment not working with Windows Authentication

### ISSUE THREAD

**Issue by vanandrao** [aspnet/Hosting#1389]
Steps we followed.
1. We created a sample project from asp.net core template using windows authentication 
2. Tested It with IISExpress works fine Gives me the Name of the Windows user on the right side of the UI (works properly).
3. added `services.AddAuthentication(IISDefaults.AuthenticationScheme);` as mentioned on the [documentation](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/windowsauth?view=aspnetcore-2.1&tabs=aspnetcore2x) 
3. Published to IIS with windows authentication enabled on IIS. 
4. It does not give me the user name. 

Also, I have done the proper installation of aspnetcore hosting module and it works fine for other .net core application without windows authentication. 
Let me know If I am missing any action?

**Comment by Tratcher** [comment]
Is anonymous login disabled in IIS?

**Comment by vanandrao** [comment]
@Tratcher  Yes, It is disabled on IIS

**Comment by vanandrao** [comment]
Yes, I found out the issue was related to web.config. You need to set forwardWindowsAuthToken=true in the aspNetCore tag under system.webserver.
