### ISSUE TITLE
No addresses in IServerAddressesFeature

### ISSUE THREAD

**Issue by tomstreet** [aspnet/Hosting#1390]
Could this be related to https://github.com/aspnet/Announcements/issues/224?

I'm binding to port 0 as [described in the docs](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel?view=aspnetcore-2.1&tabs=aspnetcore2x) and trying to use the `IServerAddressesFeature` to find out what port was actually used - but the addresses array is empty.

VS: 15.6.6
dotnet --version: 2.1.104
Microsoft.AspNetCore.Server.Kestrel: 2.1.0-preview2-final

**Comment by Tratcher** [comment]
When are you checking? IServerAddressesFeature won't be populated until after Startup.

**Comment by tomstreet** [comment]
Ah, yeh... checking in Configure in Startup.cs

**Comment by Tratcher** [comment]
You'll have to delay that. Here's a middleware that checks it on first request:
https://github.com/aspnet/BasicMiddleware/blob/354cb18d6304b24063d460e0a41c6c1d51ea4000/src/Microsoft.AspNetCore.HttpsPolicy/HttpsRedirectionMiddleware.cs#L139

**Comment by Tratcher** [comment]
IHostedService's are started after the server, but IServerAddressesFeature isn't a service in DI so I'm not sure how you'd acquire it.

**Comment by Tratcher** [comment]
You're going to have to do some experimenting here. IServerAddressesFeature can't be registered as a service because it's not available until after services are built. You'd have to register some proxy service with a IServerAddressesFeature property that you could assign later.

**Comment by Drawaes** [comment]
We had a similar problem. Now we just generate the port ourselves from the emphemeral pool and assign it to asp.net as we can't get it from aspnet when we want it.

First request is too late, as no one can find your service if you don't advertise your address.

**Comment by tomstreet** [comment]
Yeh exactly... generating our own port is not ideal as you can't guarantee the port is available, but better than nothing.

**Comment by Tratcher** [comment]
The other place we extract these addresses is in Program.Main after StartAsync. https://github.com/aspnet/Hosting/blob/a63932a492513cdeb4935661145084cad2ae5521/src/Microsoft.AspNetCore.Hosting/WebHostExtensions.cs#L104
Is that something you can do?

**Comment by tomstreet** [comment]
Ok it looks like creating a proxy object with a property to hold the IServerAddressesFeature and injecting it into an IHostedService works.

**Comment by tomstreet** [comment]
... for now :)

**Comment by Drawaes** [comment]
If you want to pre allocate 60% of the time this works every time.

https://github.com/Drawaes/CondenserDotNet/blob/master/src/CondenserDotNet.Client/ServiceManagerConfig.cs#L22

**Comment by Tratcher** [comment]
@Drawaes we were doing that for our functional tests but it was very flaky on OSX, it would often return duplicate ports.

**Comment by Drawaes** [comment]
Cool that the other method works might have to take a look and put it in my lib as well.

**Comment by tomstreet** [comment]
Also with the finding the port yourself, it could in theory be taken by something else in the small space between finding it and binding to it.

**Comment by Drawaes** [comment]
1. Don't use osx so don't care ;) and certainly don't use osx in prod.
2. Unlikely that another app will get it if you look at how the ports are allocated it won't reallocate you port unless you used the entire rest of the emphemeral ports in the time between closing and opening. (On windows) and an entire bucket on Linux which is theorically possible but I doubt it will happen ever (and certainly not enough to be a problem).

That said I like the proxy object idea and will investigate it for my consul lib.

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
