### ISSUE TITLE
Running in local Visual Studio 2017 ASP NET Core 2.0 HTTP Error 502.5 - Process Failure

### ISSUE THREAD

**Issue by aerosunilkumar** [aspnet/Hosting#1392]
HTTP Error 502.5 - Process Failure

Common causes of this issue:
The application process failed to start
The application process started but then stopped
The application process started but failed to listen on the configured port

Troubleshooting steps:
Check the system event log for error messages
Enable logging the application process' stdout messages
Attach a debugger to the application process and inspect

For more information visit: https://go.microsoft.com/fwlink/?LinkID=808681

**Comment by ClanLeader** [comment]
Hi Sunil,

This is common error on .net core. Maybe you can refer to this post http://dotnet4europeanhosting.hostforlife.eu/post/European-ASPNET-Core-Hosting-HostForLIFEeu-How-to-Fix-Error-5025-Process-Failure-in-ASPNET-Core.aspx

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
