### ISSUE TITLE
Provide a way to retrieve registered background services and start, stop them from controllers

### ISSUE THREAD

**Issue by cilerler** [aspnet/Hosting#1393]
Due to `.Singleton()` behavior `BackgroundService` gets run at startup.  However in some cases, stopping those services and then start again could be beneficial.

It would be really nice if you may provide a method that retrieves all registered BackgroundServices and allow us to start/stop those from controllers.

**Comment by benaadams** [comment]
Register them as `IHostedService` and then you can DI `IEnumerable<IHostedService>`?

`IHostedService` has `StopAsync` and `StartAsync` methods?

**Comment by cilerler** [comment]
My bad, thanks.
