### ISSUE TITLE
Long running IStartupFilter time-outs windows service during startup

### ISSUE THREAD

**Issue by davidkaya** [aspnet/Hosting#1396]
Hello,

I have an application built on top of 2.1.0-preview which uses `RunAsService` so I can launch it as a service on Windows. 

I have a middleware, which needs some data from remote server. I retrieve this data in an`IStartupFilter`. If I encounter a situation, where the remote server is not running (or there is large response time) I keep retrying data retrieval. However if this process takes more than 30 seconds (which is afaik default windows server startup timeout), Windows kills the service. This is because of the fact, that the `Configure()` method from `IStartupFilter` is called during `WebHostBuilder.Build()` which blocks the application. 

I can also imagine having a large application which would take more than 30 seconds to process all `IStartupFilter`s and this would make it unusable as a Windows service. 

Are `IStartupFilter`s meant for this purpose or is there some mechanic that I am missing?

Thanks

**Comment by Tratcher** [comment]
IStartupFilter is meant to add components to the request pipeline, not to pre-load data.

The only suitable mechanic for operations that take longer than your startup timeout is to offload them to lazy background tasks. This takes a little more work because you can't rely on them being completed before requests start arriving.

**Comment by davidkaya** [comment]
I picked `IStartupFilter` based on @davidfowl 's comment https://github.com/aspnet/Hosting/issues/1085#issuecomment-305720242. I will have to come up with other solution. Thanks anyways

**Comment by davidfowl** [comment]
@Tratcher the IStartupFilter is specifically for this sorta logic (running code at startup). You're just hitting an issue with windows services.

**Comment by davidkaya** [comment]
However doesn't this make https://github.com/aspnet/Hosting/blob/62cd07d0a6c32a828fb636fffe40b44ad13b5d73/src/Microsoft.AspNetCore.Hosting.WindowsServices/WebHostWindowsServiceExtensions.cs#L36 
really hard (if possible) to use with `IStartupFilter`s with code which does not execute in less than 30 seconds? A workaround would be inheriting from `ServiceBase` and wrapping `WebHost` building and execution in `Task.Run(...)` so the building part does not block the service. However I think that is a little bit hacky workaround.

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
