### ISSUE TITLE
Don't stop the server on *any* key press

### ISSUE THREAD

**Issue by victorhurdugaci** [aspnet/Hosting#140]
There are environments in which the ReadLine is instantly executed and the server stops immediately. Wait for a particular combination of keys instead.

**Comment by glennc** [comment]
related to https://github.com/aspnet/Hosting/issues/59?

**Comment by victorhurdugaci** [comment]
Yes, could be related. Can we get this fixed ASAP? It is blocking automation...

**Comment by Praburaj** [comment]
`Console.ReadKey` is not available on coreclr yet. We need a way to capture the key strokes.

**Comment by victorhurdugaci** [comment]
`PInvoke`? :)

**Comment by Praburaj** [comment]
Related : https://github.com/dotnet/corefx/issues/311

**Comment by victorhurdugaci** [comment]
Also related https://github.com/aspnet/Hosting/pull/129

**Comment by Praburaj** [comment]
Related coreclr work done. We can do this now.

**Comment by Tratcher** [comment]
https://github.com/aspnet/Hosting/pull/255
