### ISSUE TITLE
Don't populate IHostEnvironment from IConfiguration (configure app configuration)

### ISSUE THREAD

**Issue by maelgrove** [aspnet/Hosting#1413]
The current implementation of `IHostBuilder` in **Microsoft.Extensions.Hosting** (possibly also the webhost, haven't checked) populates the contents of the `IHostEnvironment` using the `IConfiguration` created within the builder. While this is kinda neat for changing the environment name of the application via e.g. the command line configuration provider, there is no control over which values actually can be configured that way, which means as soon as I enable such a thing, a client could also e.g. change the application name, the content root etc. which can lead to confusing and undesired effects.

## Proposal

1. Populate the `IHostEnvironment` from the `Properties` of the `HostBuilder` / `HostBuilderContext`.
2. Change the `IDictionary<string, object>` contract of the properties to `IDictionary<string, Func<object>>`, allowing to lazily fetch the values to set using a callback.
3. Create an extension method for the `HostBuilder` similiar to `.UseSetting()`, which then fetches one individual key to set within the settings from the `IConfiguration` of the `HostBuilderContext`.

That would allow developers to individually control what values of the environment could be set via configuration. In a second step, we could even get rid of `IHostEnvironment` and completely rely on the `Properties` for host configuration, as this is way more flexible. Also, the dependency on `Microsoft.Extensions.Configuration` could be optional too.

I am aware that this is a breaking change though.

**Comment by Tratcher** [comment]
It's too late for a breaking change like this. We're already finalizing the release.

**Comment by muratg** [comment]
@davidfowl thoughts for a 3.0 change?

**Comment by davidfowl** [comment]
No, I'm also not sure it's worth it. This is the first I've heard anyone complain about the behavior.
