### ISSUE TITLE
Cannot create HttpClient in MsTest from TestServer for net472.

### ISSUE THREAD

**Issue by msmolka** [aspnet/Hosting#1414]
I've recently updated solution to net472, however I cannot resolve HttpClient for such version.
My project file looks:
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net472</TargetFrameworks>
    <Platforms>x64;x86</Platforms>
    <GenerateBindingRedirectsOutputType>true</GenerateBindingRedirectsOutputType>
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.TestHost" Version="2.1.0-rc1-final" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.7.0" />
    <PackageReference Include="MSTest.TestAdapter" Version="1.3.0-beta2" />
    <PackageReference Include="MSTest.TestFramework" Version="1.3.0-beta2" />
    <PackageReference Include="System.Net.Http" Version="4.3.3" />
  </ItemGroup>

</Project>
```
following code is not compiling:
```c#
using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace UnitTestProject1
{
    using Microsoft.AspNetCore.Hosting;
    using Microsoft.AspNetCore.TestHost;

    [TestClass]
    public class UnitTest1
    {
        [TestMethod]
        public void TestMethod1()
        {
            var testServer = new TestServer(new WebHostBuilder());
            var client = testServer.CreateClient();
        }
    }
}

```

See attached sample project. Changing to net 462 make it working. 471 works as well.
[UnitTestProject1.zip](https://github.com/aspnet/Hosting/files/1987497/UnitTestProject1.zip)

**Comment by Tratcher** [comment]
What's the actual error message?

**Comment by msmolka** [comment]
It cannot resolve `HttpClient`. System.Net.Http is not referenced, even by manual adding nuget. It only happen in 472

**Comment by mgwalm** [comment]
I have exactly the same problem. After updating to net472 my net472 project is broken. it wont compile. I get the following error message:
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0246	The type or namespace name 'HttpClient' could not be found (are you missing a using directive or an assembly reference?)	WCF.Client(net472)	E:\MSIV2012\Framework\NETStandard\src\WCF.Client\WebClientExtensions.cs	295	Active

This was compiling correctly with net471.

**Comment by mgwalm** [comment]
I solved it by removing the nuget package (System.Net.Http) from the472 references ONLY and adding a direct reference to the assembly (>C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7.2\System.Net.Http.dll).

However this is only a band aid.

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
