### ISSUE TITLE
Improve debugging of startup errors

### ISSUE THREAD

**Issue by justinhelgerson** [aspnet/Hosting#1415]
Is there a better way to debug & log errors that occur during application startup in ASP.NET Core while being hosted in IIS?

Here's a real example I ran into yesterday:

 1. Deployed application (hosted in IIS) and visited application
 2. IIS presented a 502.5 error (as [documented](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/troubleshoot?view=aspnetcore-2.1#app-startup-errors))
 3. No application logs existed (I'm using Serilog, but that should be irrelevant)
 4. Then I checked the Event Viewer and saw two entries:

> Application 'MACHINE/WEBROOT/APPHOST/WEB-EVENTS' with physical root 'C:\inetpub\wwwroot\app-name\' failed to start process with commandline 'dotnet .\app.name.dll', ErrorCode = '0x80004005 : e0434352.

Followed by:

> Fault bucket 1264276480542710354, type 5 Event Name: CLR20r3 Response:
> Not available Cab Id: 0
> 
> Problem signature: P1: C:\Program Files\dotnet\dotnet.exe P2:
> 2.0.25816.2 P3: 59e535ea P4: Hangfire.Core P5: 1.6.19.0 P6: 5ac7be18 P7: 1ad P8: 8 P9: System.InvalidOperationException P10: 
> 
> Attached files:
> 
> These files may be available here:
> C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_C__Program
> Files_1493957f28ecec6bc3d1c6db498b565126f34b31_c6ec74f4_1a9638ca
> 
> Analysis symbol:  Rechecking for solution: 0 Report Id:
> 722e40de-a1cf-42c7-82a2-ab438802d3e9 Report Status: 0 Hashed bucket:
> 16ac364bb5761eefe18b9cc2b8a11a52

 5. I then looked at the file referenced in the Event Viewer log:

> Version=1
> EventType=CLR20r3
> EventTime=131702870315523918
> ReportType=2
> Consent=1
> UploadTime=131702870317398916
> ReportIdentifier=4e88d9bf-5303-11e8-a945-00155d036875
> IntegratorReportIdentifier=722e40de-a1cf-42c7-82a2-ab438802d3e9
> NsAppName=dotnet.exe
> AppSessionGuid=00002790-0000-000d-9648-610910e7d301
> TargetAppId=W:00068c7b9da0d43f7b4cf190c4ef8922362800000904!000066253830621631b71015dbe0c6583f0b107c041d!dotnet.exe
> TargetAppVer=2017//10//16:22:42:50!2c0f1!dotnet.exe
> BootId=4294967295
> Response.BucketId=16ac364bb5761eefe18b9cc2b8a11a52
> Response.BucketTable=5
> Response.LegacyBucketId=1264276480542710354
> Response.type=4
> Sig[0].Name=Problem Signature 01
> Sig[0].Value=C:\Program Files\dotnet\dotnet.exe
> Sig[1].Name=Problem Signature 02
> Sig[1].Value=2.0.25816.2
> Sig[2].Name=Problem Signature 03
> Sig[2].Value=59e535ea
> Sig[3].Name=Problem Signature 04
> Sig[3].Value=Hangfire.Core
> Sig[4].Name=Problem Signature 05
> Sig[4].Value=1.6.19.0
> Sig[5].Name=Problem Signature 06
> Sig[5].Value=5ac7be18
> Sig[6].Name=Problem Signature 07
> Sig[6].Value=1ad
> Sig[7].Name=Problem Signature 08
> Sig[7].Value=8
> Sig[8].Name=Problem Signature 09
> Sig[8].Value=System.InvalidOperationException
> DynamicSig[1].Name=OS Version
> DynamicSig[1].Value=10.0.14393.2.0.0.400.8
> DynamicSig[2].Name=Locale ID
> DynamicSig[2].Value=1033
> DynamicSig[22].Name=Additional Information 1
> DynamicSig[22].Value=ae63
> DynamicSig[23].Name=Additional Information 2
> DynamicSig[23].Value=ae6383b887caccf7e904c13656d03c19
> DynamicSig[24].Name=Additional Information 3
> DynamicSig[24].Value=2b0a
> DynamicSig[25].Name=Additional Information 4
> DynamicSig[25].Value=2b0ad4e65f091a43064f52a505407218
> UI[2]=C:\Program Files\dotnet\dotnet.exe
> LoadedModule[0]=C:\Program Files\dotnet\dotnet.exe
> LoadedModule[1]=C:\Windows\SYSTEM32\ntdll.dll
> LoadedModule[2]=C:\Windows\System32\KERNEL32.DLL
> LoadedModule[3]=C:\Windows\System32\KERNELBASE.dll
> LoadedModule[4]=C:\Windows\System32\ucrtbase.dll
> LoadedModule[5]=C:\Program Files\dotnet\host\fxr\2.0.3\hostfxr.dll
> LoadedModule[6]=C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.0.3\hostpolicy.dll
> LoadedModule[7]=C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.0.3\coreclr.dll
> LoadedModule[8]=C:\Windows\System32\ADVAPI32.dll
> LoadedModule[9]=C:\Windows\System32\msvcrt.dll
> LoadedModule[10]=C:\Windows\System32\sechost.dll
> LoadedModule[11]=C:\Windows\System32\RPCRT4.dll
> LoadedModule[12]=C:\Windows\System32\ole32.dll
> LoadedModule[13]=C:\Windows\System32\combase.dll
> LoadedModule[14]=C:\Windows\System32\bcryptPrimitives.dll
> LoadedModule[15]=C:\Windows\System32\GDI32.dll
> LoadedModule[16]=C:\Windows\System32\gdi32full.dll
> LoadedModule[17]=C:\Windows\System32\USER32.dll
> LoadedModule[18]=C:\Windows\System32\win32u.dll
> LoadedModule[19]=C:\Windows\System32\OLEAUT32.dll
> LoadedModule[20]=C:\Windows\System32\msvcp_win.dll
> LoadedModule[21]=C:\Windows\System32\SHLWAPI.dll
> LoadedModule[22]=C:\Windows\SYSTEM32\VERSION.dll
> LoadedModule[23]=C:\Windows\SYSTEM32\bcrypt.dll
> LoadedModule[24]=C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.0.3\System.Private.CoreLib.dll
> LoadedModule[25]=C:\Windows\System32\kernel.appcore.dll
> LoadedModule[26]=C:\inetpub\wwwroot\app.name\app.name.dll
> LoadedModule[27]=C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.0.3\System.Runtime.dll
> LoadedModule[28]=C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.0.3\clrjit.dll
> LoadedModule[29]=C:\inetpub\wwwroot\app.name\Microsoft.AspNetCore.Hosting.Abstractions.dll
> LoadedModule[30]=C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.0.3\netstandard.dll
> LoadedModule[31]=C:\inetpub\wwwroot\app.name\Microsoft.Extensions.DependencyInjection.Abstractions.dll
> LoadedModule[32]=C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.0.3\System.ComponentModel.dll
> LoadedModule[33]=C:\inetpub\wwwroot\app.name\app.name.Data.dll
> LoadedModule[34]=C:\inetpub\wwwroot\app.name\Microsoft.EntityFrameworkCore.dll
> LoadedModule[35]=C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.0.3\System.Linq.Expressions.dll
> LoadedModule[36]=C:\inetpub\wwwroot\app.name\app.name.Job.dll
> LoadedModule[37]=C:\inetpub\wwwroot\app.name\Hangfire.Core.dll
> LoadedModule[38]=C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.0.3\System.Threading.Tasks.dll
> LoadedModule[39]=C:\inetpub\wwwroot\app.name\Microsoft.AspNetCore.Hosting.dll
> LoadedModule[40]=C:\inetpub\wwwroot\app.name\Serilog.dll
> LoadedModule[41]=C:\inetpub\wwwroot\app.name\Microsoft.AspNetCore.dll
> LoadedModule[42]=C:\inetpub\wwwroot\app.name\Serilog.AspNetCore.dll
> LoadedModule[43]=C:\inetpub\wwwroot\app.name\Microsoft.Extensions.Configuration.Abstractions.dll
> LoadedModule[44]=C:\inetpub\wwwroot\app.name\Microsoft.AspNetCore.Server.Kestrel.dll
> LoadedModule[45]=C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.0.3\System.IO.FileSystem.dll
> LoadedModule[46]=C:\inetpub\wwwroot\app.name\Microsoft.Extensions.Logging.dll
> LoadedModule[47]=C:\inetpub\wwwroot\app.name\Microsoft.AspNetCore.Server.IISIntegration.dll
> LoadedModule[48]=C:\inetpub\wwwroot\app.name\Microsoft.Extensions.DependencyInjection.dll
> LoadedModule[49]=C:\inetpub\wwwroot\app.name\Microsoft.Extensions.FileProviders.Abstractions.dll
> LoadedModule[50]=C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.0.3\System.Collections.dll
> LoadedModule[51]=C:\inetpub\wwwroot\app.name\Microsoft.Extensions.Configuration.dll
> LoadedModule[52]=C:\inetpub\wwwroot\app.name\Microsoft.Extensions.Configuration.EnvironmentVariables.dll
> LoadedModule[53]=C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.0.3\System.Runtime.Extensions.dll
> LoadedModule[54]=C:\inetpub\wwwroot\app.name\Microsoft.Extensions.Primitives.dll
> LoadedModule[55]=C:\Windows\System32\CRYPTSP.dll
> LoadedModule[56]=C:\Windows\system32\rsaenh.dll
> LoadedModule[57]=C:\Windows\SYSTEM32\CRYPTBASE.dll
> LoadedModule[58]=C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.0.3\System.Linq.dll
> LoadedModule[59]=C:\inetpub\wwwroot\app.name\Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.dll
> LoadedModule[60]=C:\inetpub\wwwroot\app.name\Microsoft.AspNetCore.Http.Features.dll
> LoadedModule[61]=C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.0.3\System.Console.dll
> LoadedModule[62]=C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.0.3\System.Diagnostics.DiagnosticSource.dll
> LoadedModule[63]=C:\inetpub\wwwroot\app.name\Microsoft.AspNetCore.Http.Abstractions.dll
> LoadedModule[64]=C:\inetpub\wwwroot\app.name\Microsoft.Extensions.Configuration.FileExtensions.dll
> LoadedModule[65]=C:\inetpub\wwwroot\app.name\Microsoft.AspNetCore.Http.dll
> LoadedModule[66]=C:\inetpub\wwwroot\app.name\Microsoft.Extensions.Options.dll
> LoadedModule[67]=C:\inetpub\wwwroot\app.name\Microsoft.Extensions.ObjectPool.dll
> LoadedModule[68]=C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.0.3\System.Resources.ResourceManager.dll
> LoadedModule[69]=C:\inetpub\wwwroot\app.name\Microsoft.Extensions.FileProviders.Physical.dll
> LoadedModule[70]=C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.0.3\System.IO.FileSystem.Watcher.dll
> LoadedModule[71]=C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.0.3\System.ComponentModel.Primitives.dll
> LoadedModule[72]=C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.0.3\System.Collections.Concurrent.dll
> LoadedModule[73]=C:\inetpub\wwwroot\app.name\Microsoft.Extensions.FileSystemGlobbing.dll
> LoadedModule[74]=C:\inetpub\wwwroot\app.name\Microsoft.Extensions.Configuration.Json.dll
> LoadedModule[75]=C:\inetpub\wwwroot\app.name\Microsoft.Extensions.Configuration.CommandLine.dll
> LoadedModule[76]=C:\inetpub\wwwroot\app.name\Microsoft.Extensions.Configuration.UserSecrets.dll
> LoadedModule[77]=C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.0.3\System.Threading.dll
> LoadedModule[78]=C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.0.3\System.Diagnostics.Tracing.dll
> LoadedModule[79]=C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.0.3\System.Threading.Overlapped.dll
> LoadedModule[80]=C:\inetpub\wwwroot\app.name\Newtonsoft.Json.dll
> LoadedModule[81]=C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.0.3\System.Dynamic.Runtime.dll
> LoadedModule[82]=C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.0.3\System.ObjectModel.dll
> LoadedModule[83]=C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.0.3\System.IO.dll
> LoadedModule[84]=C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.0.3\System.Globalization.dll
> LoadedModule[85]=C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.0.3\System.Runtime.Numerics.dll
> LoadedModule[86]=C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.0.3\System.Private.Uri.dll
> LoadedModule[87]=C:\inetpub\wwwroot\app.name\Microsoft.Extensions.Logging.Abstractions.dll
> LoadedModule[88]=C:\inetpub\wwwroot\app.name\Microsoft.AspNetCore.Server.Kestrel.Transport.Abstractions.dll
> LoadedModule[89]=C:\inetpub\wwwroot\app.name\Microsoft.AspNetCore.Server.Kestrel.Core.dll
> LoadedModule[90]=C:\inetpub\wwwroot\app.name\Microsoft.AspNetCore.Hosting.Server.Abstractions.dll
> LoadedModule[91]=C:\inetpub\wwwroot\app.name\Microsoft.Extensions.Logging.Configuration.dll
> LoadedModule[92]=C:\inetpub\wwwroot\app.name\Microsoft.Extensions.Logging.Console.dll
> LoadedModule[93]=C:\inetpub\wwwroot\app.name\Microsoft.Extensions.Logging.Debug.dll
> LoadedModule[94]=C:\inetpub\wwwroot\app.name\Microsoft.Extensions.Options.ConfigurationExtensions.dll
> LoadedModule[95]=C:\inetpub\wwwroot\app.name\Microsoft.AspNetCore.HttpOverrides.dll
> LoadedModule[96]=C:\inetpub\wwwroot\app.name\Microsoft.AspNetCore.Authentication.Core.dll
> LoadedModule[97]=C:\inetpub\wwwroot\app.name\Microsoft.AspNetCore.Authentication.Abstractions.dll
> LoadedModule[98]=C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.0.3\System.Security.Claims.dll
> LoadedModule[99]=C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.0.3\System.Runtime.InteropServices.RuntimeInformation.dll
> LoadedModule[100]=C:\Windows\System32\clbcatq.dll
> LoadedModule[101]=C:\inetpub\wwwroot\app.name\Serilog.Settings.Configuration.dll
> LoadedModule[102]=C:\inetpub\wwwroot\app.name\Microsoft.Extensions.DependencyModel.dll
> LoadedModule[103]=C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.0.3\System.Reflection.dll
> LoadedModule[104]=C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.0.3\System.AppContext.dll
> LoadedModule[105]=C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.0.3\System.IO.FileSystem.Primitives.dll
> LoadedModule[106]=C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.0.3\System.Reflection.Emit.ILGeneration.dll
> LoadedModule[107]=C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.0.3\System.Reflection.Primitives.dll
> LoadedModule[108]=C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.0.3\System.Reflection.Emit.Lightweight.dll
> LoadedModule[109]=C:\inetpub\wwwroot\app.name\Serilog.Extensions.Logging.dll
> LoadedModule[110]=C:\inetpub\wwwroot\app.name\Serilog.Sinks.File.dll
> LoadedModule[111]=C:\inetpub\wwwroot\app.name\Serilog.Sinks.RollingFile.dll
> LoadedModule[112]=C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.0.3\System.Reflection.Extensions.dll
> LoadedModule[113]=C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.0.3\System.Text.Encoding.dll
> LoadedModule[114]=C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.0.3\System.Text.RegularExpressions.dll
> LoadedModule[115]=C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.0.3\System.Collections.NonGeneric.dll
> LoadedModule[116]=C:\inetpub\wwwroot\app.name\Microsoft.AspNetCore.Mvc.dll
> LoadedModule[117]=C:\inetpub\wwwroot\app.name\Microsoft.AspNetCore.Mvc.Core.dll
> LoadedModule[118]=C:\inetpub\wwwroot\app.name\Microsoft.AspNetCore.NodeServices.dll
> LoadedModule[119]=C:\inetpub\wwwroot\app.name\Microsoft.AspNetCore.Authorization.dll
> LoadedModule[120]=C:\inetpub\wwwroot\app.name\app.name.Common.dll
> LoadedModule[121]=C:\inetpub\wwwroot\app.name\Hangfire.AspNetCore.dll
> LoadedModule[122]=C:\inetpub\wwwroot\app.name\Microsoft.AspNetCore.Authentication.dll
> LoadedModule[123]=C:\inetpub\wwwroot\app.name\Microsoft.AspNetCore.Authentication.Cookies.dll
> LoadedModule[124]=C:\inetpub\wwwroot\app.name\Microsoft.AspNetCore.Mvc.Razor.dll
> LoadedModule[125]=C:\inetpub\wwwroot\app.name\Microsoft.AspNetCore.Mvc.ApiExplorer.dll
> LoadedModule[126]=C:\inetpub\wwwroot\app.name\Microsoft.AspNetCore.Mvc.ViewFeatures.dll
> LoadedModule[127]=C:\inetpub\wwwroot\app.name\Microsoft.AspNetCore.Razor.Runtime.dll
> LoadedModule[128]=C:\inetpub\wwwroot\app.name\Microsoft.AspNetCore.Mvc.RazorPages.dll
> LoadedModule[129]=C:\inetpub\wwwroot\app.name\Microsoft.AspNetCore.Mvc.TagHelpers.dll
> LoadedModule[130]=C:\inetpub\wwwroot\app.name\Microsoft.AspNetCore.Mvc.DataAnnotations.dll
> LoadedModule[131]=C:\inetpub\wwwroot\app.name\Microsoft.AspNetCore.Mvc.Formatters.Json.dll
> LoadedModule[132]=C:\inetpub\wwwroot\app.name\Microsoft.AspNetCore.Mvc.Cors.dll
> LoadedModule[133]=C:\inetpub\wwwroot\app.name\Microsoft.AspNetCore.Mvc.Abstractions.dll
> LoadedModule[134]=C:\inetpub\wwwroot\app.name\Microsoft.AspNetCore.Routing.dll
> LoadedModule[135]=C:\inetpub\wwwroot\app.name\Microsoft.VisualStudio.Web.CodeGeneration.dll
> LoadedModule[136]=C:\inetpub\wwwroot\app.name\Microsoft.VisualStudio.Web.CodeGeneration.Core.dll
> LoadedModule[137]=C:\inetpub\wwwroot\app.name\dotnet-aspnet-codegenerator-design.dll
> LoadedModule[138]=C:\inetpub\wwwroot\app.name\Microsoft.VisualStudio.Web.CodeGeneration.EntityFrameworkCore.dll
> LoadedModule[139]=C:\inetpub\wwwroot\app.name\Microsoft.VisualStudio.Web.CodeGeneration.Templating.dll
> LoadedModule[140]=C:\inetpub\wwwroot\app.name\Microsoft.VisualStudio.Web.CodeGenerators.Mvc.dll
> LoadedModule[141]=C:\inetpub\wwwroot\app.name\app.name.Model.dll
> LoadedModule[142]=C:\inetpub\wwwroot\app.name\System.Text.Encodings.Web.dll
> LoadedModule[143]=C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.0.3\System.Buffers.dll
> LoadedModule[144]=C:\inetpub\wwwroot\app.name\Microsoft.AspNetCore.Routing.Abstractions.dll
> LoadedModule[145]=C:\inetpub\wwwroot\app.name\Microsoft.AspNetCore.Authorization.Policy.dll
> LoadedModule[146]=C:\inetpub\wwwroot\app.name\Microsoft.AspNetCore.DataProtection.dll
> LoadedModule[147]=C:\inetpub\wwwroot\app.name\Microsoft.AspNetCore.Antiforgery.dll
> LoadedModule[148]=C:\inetpub\wwwroot\app.name\Microsoft.Extensions.WebEncoders.dll
> LoadedModule[149]=C:\inetpub\wwwroot\app.name\Microsoft.AspNetCore.Cryptography.Internal.dll
> LoadedModule[150]=C:\inetpub\wwwroot\app.name\Microsoft.AspNetCore.DataProtection.Abstractions.dll
> LoadedModule[151]=C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.0.3\System.Runtime.InteropServices.dll
> LoadedModule[152]=C:\inetpub\wwwroot\app.name\Microsoft.CodeAnalysis.dll
> LoadedModule[153]=C:\inetpub\wwwroot\app.name\Microsoft.AspNetCore.Razor.Language.dll
> LoadedModule[154]=C:\inetpub\wwwroot\app.name\Microsoft.AspNetCore.Mvc.Razor.Extensions.dll
> LoadedModule[155]=C:\inetpub\wwwroot\app.name\Microsoft.CodeAnalysis.Razor.dll
> LoadedModule[156]=C:\inetpub\wwwroot\app.name\Microsoft.Extensions.Caching.Abstractions.dll
> LoadedModule[157]=C:\inetpub\wwwroot\app.name\Microsoft.Extensions.Caching.Memory.dll
> LoadedModule[158]=C:\inetpub\wwwroot\app.name\Microsoft.AspNetCore.Cors.dll
> LoadedModule[159]=C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.0.3\System.Net.Primitives.dll
> LoadedModule[160]=C:\inetpub\wwwroot\app.name\Microsoft.Net.Http.Headers.dll
> LoadedModule[161]=C:\inetpub\wwwroot\app.name\System.Runtime.CompilerServices.Unsafe.dll
> LoadedModule[162]=C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.0.3\System.Threading.ThreadPool.dll
> LoadedModule[163]=C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.0.3\Microsoft.Win32.Registry.dll
> LoadedModule[164]=C:\Windows\System32\shell32.dll
> LoadedModule[165]=C:\Windows\System32\cfgmgr32.dll
> LoadedModule[166]=C:\Windows\System32\windows.storage.dll
> LoadedModule[167]=C:\Windows\System32\powrprof.dll
> LoadedModule[168]=C:\Windows\System32\shcore.dll
> LoadedModule[169]=C:\Windows\System32\profapi.dll
> LoadedModule[170]=C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.0.3\System.Security.Principal.Windows.dll
> LoadedModule[171]=C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.0.3\System.Security.Principal.dll
> LoadedModule[172]=C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.0.3\System.Xml.XDocument.dll
> LoadedModule[173]=C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.0.3\System.Private.Xml.Linq.dll
> LoadedModule[174]=C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.0.3\System.Private.Xml.dll
> LoadedModule[175]=C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.0.3\System.Text.Encoding.Extensions.dll
> LoadedModule[176]=C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.0.3\System.Security.Cryptography.Algorithms.dll
> LoadedModule[177]=C:\Windows\System32\crypt32.dll
> LoadedModule[178]=C:\Windows\System32\MSASN1.dll
> LoadedModule[179]=C:\Windows\SYSTEM32\DPAPI.DLL
> LoadedModule[180]=C:\inetpub\wwwroot\app.name\Microsoft.AspNetCore.Rewrite.dll
> LoadedModule[181]=C:\inetpub\wwwroot\app.name\Microsoft.AspNetCore.Diagnostics.dll
> LoadedModule[182]=C:\inetpub\wwwroot\app.name\Microsoft.Extensions.Configuration.Binder.dll
> LoadedModule[183]=C:\inetpub\wwwroot\app.name\Microsoft.AspNetCore.StaticFiles.dll
> LoadedModule[184]=C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.0.3\System.ComponentModel.TypeConverter.dll
> LoadedModule[185]=C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.0.3\System.Collections.Specialized.dll
> LoadedModule[186]=C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.0.3\System.Drawing.Primitives.dll
> LoadedModule[187]=C:\inetpub\wwwroot\app.name\Microsoft.Extensions.Localization.Abstractions.dll
> LoadedModule[188]=C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.0.3\System.Runtime.Serialization.Primitives.dll
> LoadedModule[189]=C:\inetpub\wwwroot\app.name\Microsoft.AspNetCore.JsonPatch.dll
> LoadedModule[190]=C:\inetpub\wwwroot\app.name\Microsoft.Extensions.FileProviders.Composite.dll
> LoadedModule[191]=C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.0.3\System.Collections.Immutable.dll
> LoadedModule[192]=C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.0.3\System.Security.Cryptography.Primitives.dll
> LoadedModule[193]=C:\Windows\System32\mscoree.dll
> LoadedModule[194]=C:\Windows\Microsoft.NET\Framework64\v4.0.30319\mscoreei.dll
> LoadedModule[195]=C:\Windows\SYSTEM32\sxs.dll
> LoadedModule[196]=C:\Windows\Microsoft.NET\Framework64\v4.0.30319\diasymreader.dll
> LoadedModule[197]=C:\Windows\SYSTEM32\MSVCR120_CLR0400.dll
> LoadedModule[198]=C:\inetpub\wwwroot\app.name\Hangfire.SqlServer.dll
> LoadedModule[199]=C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.0.3\System.Data.Common.dll
> LoadedModule[200]=C:\inetpub\wwwroot\app.name\runtimes\win\lib\netstandard2.0\System.Data.SqlClient.dll
> LoadedModule[201]=C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.0.3\System.Transactions.Local.dll
> LoadedModule[202]=C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.0.3\System.Threading.Timer.dll
> LoadedModule[203]=C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.0.3\System.Threading.Thread.dll
> LoadedModule[204]=C:\inetpub\wwwroot\app.name\runtimes\win-x64\native\sni.dll
> LoadedModule[205]=C:\Windows\System32\WS2_32.dll
> LoadedModule[206]=C:\inetpub\wwwroot\app.name\runtimes\win\lib\netcoreapp2.0\System.Text.Encoding.CodePages.dll
> LoadedModule[207]=C:\Windows\system32\secur32.dll
> LoadedModule[208]=C:\Windows\SYSTEM32\SSPICLI.DLL
> LoadedModule[209]=C:\Windows\system32\schannel.DLL
> LoadedModule[210]=C:\Windows\system32\kerberos.DLL
> LoadedModule[211]=C:\Windows\system32\msv1_0.DLL
> LoadedModule[212]=C:\Windows\SYSTEM32\NtlmShared.dll
> LoadedModule[213]=C:\Windows\SYSTEM32\cryptdll.dll
> LoadedModule[214]=C:\Windows\system32\ntdsapi.dll
> LoadedModule[215]=C:\Windows\SYSTEM32\DSPARSE.DLL
> LoadedModule[216]=C:\Windows\system32\netapi32.dll
> LoadedModule[217]=C:\Windows\SYSTEM32\LOGONCLI.DLL
> LoadedModule[218]=C:\Windows\SYSTEM32\NETUTILS.DLL
> LoadedModule[219]=C:\Windows\system32\mswsock.dll
> LoadedModule[220]=C:\Windows\SYSTEM32\DNSAPI.dll
> LoadedModule[221]=C:\Windows\System32\NSI.dll
> LoadedModule[222]=C:\Windows\SYSTEM32\IPHLPAPI.DLL
> LoadedModule[223]=C:\Windows\System32\rasadhlp.dll
> LoadedModule[224]=C:\Windows\System32\fwpuclnt.dll
> LoadedModule[225]=C:\Windows\SYSTEM32\mskeyprotect.dll
> LoadedModule[226]=C:\Windows\SYSTEM32\ncrypt.dll
> LoadedModule[227]=C:\Windows\SYSTEM32\NTASN1.dll
> LoadedModule[228]=C:\Windows\system32\ncryptsslp.dll
> LoadedModule[229]=C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.0.3\Microsoft.Win32.Primitives.dll
> LoadedModule[230]=C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.0.3\System.Diagnostics.StackTrace.dll
> LoadedModule[231]=C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.0.3\System.Reflection.Metadata.dll
> LoadedModule[232]=C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.0.3\System.IO.MemoryMappedFiles.dll
> LoadedModule[233]=C:\inetpub\wwwroot\app.name\Microsoft.EntityFrameworkCore.SqlServer.dll
> LoadedModule[234]=C:\inetpub\wwwroot\app.name\Microsoft.EntityFrameworkCore.Relational.dll
> LoadedModule[235]=C:\inetpub\wwwroot\app.name\Remotion.Linq.dll
> LoadedModule[236]=C:\inetpub\wwwroot\app.name\System.Interactive.Async.dll
> LoadedModule[237]=C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.0.3\System.Linq.Queryable.dll
> LoadedModule[238]=C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.0.3\System.ComponentModel.Annotations.dll
> LoadedModule[239]=C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.0.3\System.Diagnostics.Debug.dll
> LoadedModule[240]=C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.0.3\System.Xml.ReaderWriter.dll
> State[0].Key=Transport.DoneStage1
> State[0].Value=1
> FriendlyEventName=Stopped working
> ConsentKey=CLR20r3
> AppName=dotnet
> AppPath=C:\Program Files\dotnet\dotnet.exe
> NsPartner=windows
> NsGroup=windows8
> ApplicationIdentity=8FBBA37C0A283E6C4680B2E83767C33E
> MetadataHash=-2111484060

After all of this, what was the issue?  It was a SQL Server permissions error, caused by this line in `ConfigureServices`:

`services.AddHangfire(x => x.UseSqlServerStorage(Configuration.GetConnectionString("Hangfire")));`

So I'm left wondering, what can I do to make debugging errors like this easier in the future?  From all of the error logs I had, none of them provided information about what the real error was.  Instead of my app being down for 15 minutes, it could have been down for 15 seconds.  Is there a way I can show the actual exception caused in startup?

Windows Server 2016
IIS 10
ASP.NET Core 2.0

**Comment by Tratcher** [comment]
Anything on stdout? https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/troubleshoot?view=aspnetcore-2.1#aspnet-core-module-stdout-log

**Comment by justinhelgerson** [comment]
Good point.  I don't typically have stdout logging enabled, but I enabled it & reproduced the scenario and the log message was exactly what I was looking for.

Is it recommended to leave stdout disabled in production?  Is there much of an impact to always having it enabled?

**Comment by Tratcher** [comment]
Yes, leave it disabled unless debugging something. It can consume a lot of disk space.

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
