### ISSUE TITLE
Consider adding "UseDefaultServiceProvider()" to HostingHostBuilderExtensions

### ISSUE THREAD

**Issue by cwe1ss** [aspnet/Hosting#1418]
`WebHostBuilderExtensions.cs` has `UseDefaultServiceProvider()` methods ([code](https://github.com/aspnet/Hosting/blob/38f691c09e3aae4f34be139c39ae1fb264803fd0/src/Microsoft.AspNetCore.Hosting/WebHostBuilderExtensions.cs#L90)) but the new `HostingHostBuilderExtensions` does not. 

Would be nice to have that as well as it makes configuring the behavior of `ValidateScopes` easier (like in [WebHost](https://github.com/aspnet/MetaPackages/blob/7fea7ab5fd4ffbb97c1b659101b3eea37d224129/src/Microsoft.AspNetCore/WebHost.cs#L209)).

**Comment by davidfowl** [comment]
Yes please!
