### ISSUE TITLE
IHostingBuilder design 

### ISSUE THREAD

**Issue by SinxHe** [aspnet/Hosting#1419]
First of all. I am sorry about my poor english. Please do not mind.

Hi, I am reading the source code of hosting, and i design a similarity ETL framework follow the hosting design. I found the source code of IWebHostingBuilder contains method like `ConfigureAppConfiguration`, `ConfigureServices`, I have some doubts about why just simplify the interface use method `Configure(Action<IServiceCollection>)` to configure the services and thread IConfigurationBuilder as one of the service. we can just use `Configure` to do the same thing as `ConfigureAppConfiguration` and `ConfigureServices` done, and the concept is more simple. And for simplifing usage, we can just make a IWebHostingBuilderExtensions static method to extension the interface.

Here is some of my code in abstraction project.

```csharp
public interface IHostBuilder
{
    IHost Build();

    IHostBuilder Configure(Action<IServiceCollection> configureServices);
}
```

Here is some of my code in implement project.

```csharp
public static class IHostBuilderExtensions
{
    public static IHostBuilder AddDefaultServices(this IHostBuilder builder)
    {
		// TODO
		return builder;
    }

    public static IHostBuilder Configure(this IHostBuilder builder, Action<IConfigurationBuilder> action)
    {
	    builder.Configure(sc =>
	    {
		    var cb = sc.BuildServiceProvider().GetRequiredService<IConfigurationBuilder>();
		    action(cb);
	    });
		return builder;
    }

    public static IHostBuilder Configure(
	    this IHostBuilder builder, 
	    Action<IConfigurationBuilder, IServiceCollection> action)
    {
	    builder.Configure(sc =>
	    {
			var cb = sc.BuildServiceProvider().GetRequiredService<IConfigurationBuilder>();
			action(cb, sc);
	    });
		return builder;
    }

	public static IHostBuilder Configure(
		this IHostBuilder builder,
		Action<IConfiguration, IConfigurationBuilder, IServiceCollection> action)
	{
		builder.Configure(sc =>
		{
			var cb = sc.BuildServiceProvider().GetRequiredService<IConfigurationBuilder>();
			var conf = cb.Build();
			action(conf, cb, sc);
		});
		return builder;
    }
}
```

Thank you for showing me the way.

**Comment by davidfowl** [comment]
Calling BuildServiceProvider creates a new service provider so you can't use really use the IServiceCollection to pass state around unless you pass a service that is instance based. Each call to BuildServiceProvider creates a new universe of types that are unrelated.

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
