### ISSUE TITLE
IISExpress exe logs in Output window still contains Helios in the name

### ISSUE THREAD

**Issue by balachir** [aspnet/Hosting#143]
REPRO STEPS
1. New ASP.NET 5 StarterWeb app
2. F5  
3. Stop F5 and view Output window
 
ACTUAL
IIS Express logs in Output window still show "Helios" in the name
 
...
'iisexpress.exe' (CLR v4.0.30319: **Helios**-fd478731-da06-457e-98c7-bd10c8b3a29a): Loaded 'C:\Users\balach\.kre\packages\KRE-CLR-x86.1.0.0-rc1-10892\bin\klr.net45.managed.dll'. Cannot find or open the PDB file.
'iisexpress.exe' (CLR v4.0.30319: **Helios**-fd478731-da06-457e-98c7-bd10c8b3a29a): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Core\v4.0_4.0.0.0__b77a5c561934e089\System.Core.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'iisexpress.exe' (CLR v4.0.30319: **Helios**-fd478731-da06-457e-98c7-bd10c8b3a29a): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'iisexpress.exe' (CLR v4.0.30319: Helios-fd478731-da06-457e-98c7-bd10c8b3a29a): Loaded 'C:\Users\balach\.kre\packages\KRE-CLR-x86.1.0.0-rc1-10892\bin\klr.host.dll'. Cannot find or open the PDB file.
'iisexpress.exe' (CLR v4.0.30319: Helios-fd478731-da06-457e-98c7-bd10c8b3a29a): Loaded 'Microsoft.Framework.Runtime.Infrastructure.CallContextServiceLocator'. Module was built without symbols.
'iisexpress.exe' (CLR v4.0.30319: Helios-fd478731-da06-457e-98c7-bd10c8b3a29a): Loaded 'Microsoft.Framework.Runtime.Infrastructure.IServiceProviderLocator'. Module was built without symbols.
'iisexpress.exe' (CLR v4.0.30319: Helios-fd478731-da06-457e-98c7-bd10c8b3a29a): Loaded 'Microsoft.Framework.Runtime.AssemblyNeutralAttribute'. Module was built without symbols.
'iisexpress.exe' (CLR v4.0.30319: Helios-fd478731-da06-457e-98c7-bd10c8b3a29a): Loaded 'Microsoft.Framework.Runtime.IAssemblyLoadContext'. Module was built without symbols.
'iisexpress.exe' (CLR v4.0.30319: Helios-fd478731-da06-457e-98c7-bd10c8b3a29a): Loaded 'Microsoft.Framework.Runtime.IAssemblyLoadContextAccessor'. Module was built without symbols.
'iisexpress.exe' (CLR v4.0.30319: Helios-fd478731-da06-457e-98c7-bd10c8b3a29a): Loaded 'Microsoft.Framework.Runtime.IAssemblyLoader'. Module was built without symbols.
'iisexpress.exe' (CLR v4.0.30319: Helios-fd478731-da06-457e-98c7-bd10c8b3a29a): Loaded 'Microsoft.Framework.Runtime.IAssemblyLoaderContainer'. Module was built without symbols.
'iisexpress.exe' (CLR v4.0.30319: Helios-fd478731-da06-457e-98c7-bd10c8b3a29a): Loaded 'Microsoft.Framework.Runtime.IApplicationEnvironment'. Module was built without symbols.

**Comment by Tratcher** [comment]
This issue was moved to aspnet/Helios#85
