### ISSUE TITLE
ASPNETCORE_ENVIRONMENT seems to be ignored using Generic Host

### ISSUE THREAD

**Issue by chrisckc** [aspnet/Hosting#1440]
Using the ASP.NET Background Tasks Sample (Generic Host)
[https://github.com/aspnet/Docs/tree/master/aspnetcore/fundamentals/host/hosted-services/samples/2.x/BackgroundTasksSample-GenericHost](https://github.com/aspnet/Docs/tree/master/aspnetcore/fundamentals/host/hosted-services/samples/2.x/BackgroundTasksSample-GenericHost)
I am unable to set the Environment to "Development", it remains set to "Production" despite the ASPNETCORE_ENVIRONMENT env variable being set to Development.

I updated the vscode launch.json as instructed in the readme, i also added the ASPNETCORE_ENVIRONMENT env var to it as follows:

```
"console": "integratedTerminal",
            "env": {
                "ASPNETCORE_ENVIRONMENT": "Development"
            },
```
When running in debug in vscode on Mac and also when using `ASPNETCORE_ENVIRONMENT=Development dotnet run`
or when using `export ASPNETCORE_ENVIRONMENT=Development`, then dotnet run, the output still reports the Hosting Environment to be Production

> Application started. Press Ctrl+C to shut down.
> Hosting environment: Production

I am using the latest 2.1 RC1 framework and have not changed anything in the csproj file, just performed a restore and build.

I also added the following to the top of Program.cs to check:

```
Console.WriteLine("Running Main() ...");
string environment = Environment.GetEnvironmentVariable("ASPNETCORE_ENVIRONMENT");
Console.WriteLine("ASPNETCORE_ENVIRONMENT: {0}", environment);

var host = new HostBuilder()
........
```
Which outputs:
> Running Main() ...
> ASPNETCORE_ENVIRONMENT: Development

despite the Hosting Environment still showing Production.

The only other possibly related issue i could find was this: [https://github.com/aspnet/Hosting/issues/1366](https://github.com/aspnet/Hosting/issues/1366)

I actually first noticed the issue on a Generic Host app i built myself and then when looking for a sample to make sure i had not missed anything important. I also tried this on Windows using Visual Studio 2017 and updating the launchSettings.json to include the env var. I haven't yet tried this using v2.0

As a workaround to fix this added a line fo code to update hostContext.HostingEnvironment.EnvironmentName

```
.ConfigureAppConfiguration((hostContext, config) =>
                {
                    hostContext.HostingEnvironment.EnvironmentName = environment;
                    config.AddEnvironmentVariables();
                     ........
```

**Comment by Tratcher** [comment]
HostBuilder has no default config providers, including environment variables.
https://github.com/aspnet/Hosting/blob/23e3ab6555acf68715672f930b01b9a6a8b8134b/src/Microsoft.Extensions.Hosting/HostBuilder.cs#L102-L127
Call ConfigureHostConfiguration to add config providers:
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/generic-host?view=aspnetcore-2.1#host-configuration
configHost.AddEnvironmentVariables("DOTNET_");

@guardrex

**Comment by guardrex** [comment]
I'll open a doc issue to address this soon.

**Comment by chrisckc** [comment]
Found another sample here:
[https://github.com/aspnet/Docs/tree/master/aspnetcore/fundamentals/host/generic-host/samples/2.x/GenericHostSample](https://github.com/aspnet/Docs/tree/master/aspnetcore/fundamentals/host/generic-host/samples/2.x/GenericHostSample)

this has the section:
```
.ConfigureHostConfiguration(configHost =>
                {
                    configHost.AddEnvironmentVariables();
                    configHost.AddJsonFile("hostsettings.json", optional: true);
                    configHost.AddCommandLine(args);
                })
```
but still does not work, also tried editing it to AddEnvironmentVariables("DOTNET_"); and AddEnvironmentVariables("ASPNETCORE_"); 

Currently both samples are broken as they suggest it should work due to the inclusion of:
`config.AddJsonFile($"appsettings.{hostContext.HostingEnvironment.EnvironmentName}.json", optional: true);`

but it is not possible to use appsettings.Development.json

**Comment by guardrex** [comment]
I'll see if I can repro what you're seeing @chrisckc. I don't recall whether or not I specifically tested setting an env var, but I probably didn't test that scenario. I'll get back to you in perhaps an hour or two.

**Comment by Tratcher** [comment]
Were you running that GenericHostSample as-is? Or copying pieces into your own project?

**Comment by chrisckc** [comment]
Running it as is, just edited console entry inside the vscode generated
launch.json as instructed in the readme

**Comment by guardrex** [comment]
I'm able to repro the env var behavior here with the sample. @Tratcher, anything else you'd like me to try?

### *hostsettings.json*

```json
{
  "environment": "Development"
}
```

Works ... **BUT ... there's a 🐞 in the sample**. It needs ...

```csharp
configHost.SetBasePath(System.IO.Directory.GetCurrentDirectory());
```
... to work. I'll patch that right now.

### VSC env var

```json
{
    "name": ".NET Core Launch (console)",
    "type": "coreclr",
    "request": "launch",
    "preLaunchTask": "build",
    "program": "${workspaceRoot}/bin/Debug/netcoreapp2.1/GenericHostSample.dll",
    "args": [],
    "cwd": "${workspaceRoot}",
    "stopAtEntry": false,
    "console": "externalTerminal",
    "env": {
        "ASPNETCORE_ENVIRONMENT": "Development"
    }
},
```

Doesn't work.

### System env var

Doesn't work. However, I didn't do a restart. I don't think it's required in this case, as the console window should take it's snapshot of env vars when VSC opens the console window ... is that right @Tratcher?

### Command line

```console
dotnet run --environment Development
```

**Works!**

### UseEnvironment

```csharp
.UseEnvironment("Development")
```

**Works!**

**Comment by Tratcher** [comment]
Does this work?
```
    "env": {
        "ENVIRONMENT": "Development"
    }
```

You're not specifying a prefix on AddEnvironmentVariables and there is no default.

**Comment by guardrex** [comment]
Ah ... I see. Stand-by ... I'll check that.

**Comment by guardrex** [comment]
Yep ... that got it. When I get this patch in, the *hostsettings.json* file will work. I'm putting the same call to set the base path down on the `configApp` prior to setting up the *appsettings* files.

**Comment by Tratcher** [comment]
If you set the host contentroot then you shouldn't have to do anything for appsettings.

**Comment by guardrex** [comment]
@Tratcher Which is simpler/best ...

* Tell the reader that `AddEnvironmentVariables` doesn't specify the prefix, so they should use un-prefixed env vars when setting them for the debugger in an IDE.
* Change the sample so that `AddEnvironmentVariables` does specify the prefix. We then instruct to use the prefix when setting the env var.

**Comment by Tratcher** [comment]
Specify a prefix in the sample, that's more discoverable.

**Comment by guardrex** [comment]
> remove the environment variable from the docs.

If we go the other way and make the change across the docs to specify the prefix every time ...

```csharp
.AddEnvironmentVariables(prefix: "ASPNETCORE_")
```

... then we'd get out of this mess, right? :smile:

**Comment by Tratcher** [comment]
You'd still want to all out that env vars aren't added by default, and if you add them then you get to choose the prefix. I'd almost want to change all of the docs to use an alternate prefix to make it more obvious. "YOURPREFIX_"...

**Comment by guardrex** [comment]
Ok, I'll open a docs issue so that we can do that work.

For now on this one patch PR to the Generic Host, let's set this one up with the `ASPNETCORE_` prefix on `AddEnvironmentVariables`. Let's just patch it for now until we figure out the final, permanent fix for all topics+samps.

Besides, I'm neck-deep in 2.1 updates. After the 2.1 updates are complete, I'll have more time.

**Comment by chrisckc** [comment]
Great work in getting this progressed so quickly!

I spotted the merge into master so pulled the repo again to test it, i also updated to the release version of the 2.1.300 SDK which i believe was released yesterday.

Using the GenericHost Sample as is:

> dotnet run 

Works, Hosting Environment is set to Development using the hostsettings.json file
I then removed   "environment": "Development" from hostsettings.json, this caused Hosting Environment to be set to Production which i believe is the default. 

With "environment": "Development" still removed from hostsettings.json, i tried this:

> ASPNETCORE_ENVIRONMENT=Development dotnet run
Works, Hosting Environment is set to Development

I then added ASPNETCORE_ENVIRONMENT to launch.json:

```
            "console": "integratedTerminal",
            "env": {
                "ASPNETCORE_ENVIRONMENT": "Development"
            }
```
Works running vscode debug, Hosting Environment is set to Development.

**Other observations:**

I then added "environment": "Development" back into hostsettings.json and discovered that as expected, in the sample, this overrides any other configuration method.

For example if i do this:

> ASPNETCORE_ENVIRONMENT=Staging dotnet run
Hosting Environment is still set to Development
Same if i try using Staging inside the launch.json file.

I then edited the Program.cs in the sample so that the call to AddEnvironmentVariables comes after AddJsonFile:
```
                .ConfigureHostConfiguration(configHost =>
                {
                    configHost.SetBasePath(Directory.GetCurrentDirectory());
                    configHost.AddJsonFile("hostsettings.json", optional: true);
                    configHost.AddEnvironmentVariables(prefix: "ASPNETCORE_");
                    configHost.AddCommandLine(args);
                })
```
This fixes that issue, i can now override the hostsettings.json file using env vars, is this behaviour intended for the sample? Would it not be better to have it like the above so that env vars always override configuration files which is what i have seen in most of the MVC examples?

Also i believe that the Web Host CreateDefaultBuilder method uses the following order:

appsettings.json
appsettings.{Environment}.json
User secrets when in Development mode
Environment variables
Commandline args

This is an inconsistency which i can't see any reason for?

Maybe Generic Host should have an equivalent CreateDefaultBuilder method which behaves the same way?

**Comment by chrisckc** [comment]
Sounds good, ConfigureAppConfiguration should also be the edited to be same order as ConfigureHostConfiguration.

**Comment by guardrex** [comment]
@chrisckc Already done. :+1:

**Comment by chrisckc** [comment]
Great, found some another samples here that i had open in one of my many web browser tabs...
[https://github.com/aspnet/Hosting/tree/release/2.1/samples](https://github.com/aspnet/Hosting/tree/release/2.1/samples)

Looks like they will have the same issue.

**Comment by guardrex** [comment]
I'll catch those on https://github.com/aspnet/Docs/issues/6760. I'm neck-deep in 2.1 sample updates. I'll get on that PR first thing when these samps are under control.

**Comment by mattspicer1** [comment]
I'm running the sample at Docs\aspnetcore\fundamentals\host\hosted-services\samples\2.x\BackgroundTasksSample-GenericHost and I'm seeing this issue.  I've just pulled the latest and I'm running straight from VS2017.  I'm attempting to set the environment variables through the debug settings in the Project Properties/Debug/Environment variables box.

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
