### ISSUE TITLE
Consuming a Local Build

### ISSUE THREAD

**Issue by seth-capistron** [aspnet/Hosting#1442]
I've made some code changes in my local repo that build and pass tests. Next, I was hoping to take my local build and consume it within an existing ASP.NET Core web project that I have. Is this possible? Are there instructions for doing so? The closest I was able to find were these [instructions](https://github.com/aspnet/Home#daily-builds) for consuming daily builds, but was hoping to try my changes end-to-end based off my local build.

**Comment by Tratcher** [comment]
My current cross-repo flow:
In any AspNetCore repo:
build.cmd /p:buildnumber=T111

In my dependent project:
Add D:\github\AspNet\Hosting\artifacts\build as a nuget source and as a symbols source.
Update project dependencies to the new build number.

Expect nuget warnings/errors about mismatched dependencies...

**Comment by seth-capistron** [comment]
Thanks for the pointer - this worked out perfect.

A few other things I stumbled through (jotting them down in case it helps someone in the future)...

1. I needed to install the 2.2.0 version of the AspNetCore runtime. I found that [here](https://github.com/aspnet/Universe#aspnet-core-shared-framework).
2. Also needed the 2.2.0 version of the NETCore App runtime. I found that [here](https://github.com/dotnet/core-setup#daily-builds).

My .csproj ended up looking like this. Note that 2.2.0-perview1-26529-01 is the version of the runtime I downloaded in step 2 above. And 2.2.0-preview1-34351 is from step 1 above. And 2.2.0-preview1-T115 is from my local Hosting git repo build.

```
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.2</TargetFramework>
    <RuntimeFrameworkVersion>2.2.0-preview1-26529-01</RuntimeFrameworkVersion>
    <NETCoreAppMaximumVersion>2.2</NETCoreAppMaximumVersion>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="wwwroot\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.App" Version="2.2.0-preview1-34351" />
    <PackageReference Include="Microsoft.AspNetCore.Hosting" Version="2.2.0-preview1-T115" />
    <PackageReference Include="Microsoft.AspNetCore.Hosting.Abstractions" Version="2.2.0-preview1-T115" />
    <PackageReference Include="Microsoft.AspNetCore.Hosting.Server.Abstractions" Version="2.2.0-preview1-T115" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="2.2.0-preview1-T115" />
  </ItemGroup>

</Project>
```

And my Nuget.Config looked like this...
```
<configuration>
  <packageSources>
    <add key="local aspnet hosting" value="D:\Repos_2\github\Hosting\artifacts\build" /> <!-- Change this to your own output path -->
    <add key="dotnet-core" value="https://dotnet.myget.org/F/dotnet-core/api/v3/index.json" />
    <add key="aspnetcore-dev" value="https://dotnet.myget.org/F/aspnetcore-dev/api/v3/index.json" />
  </packageSources>
</configuration>
```
