### ISSUE TITLE
Failure to resolve System.Net.Http

### ISSUE THREAD

**Issue by phatcher** [aspnet/Hosting#1443]
I have a WebApi project targeting .NET 4.7.2 using Microsoft.AspNet.WebApi 5.2.6.

It has a reference to System.Net.Http
```
    <Reference Include="System.Net.Http">
      <HintPath>..\..\..\..\..\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7.2\System.Net.Http.dll</HintPath>
    </Reference>
```
and there is a redirect in the web.config
```
    <dependentAssembly>
        <assemblyIdentity name="System.Net.Http" publicKeyToken="B03F5F7F11D50A3A" culture="neutral"/>
        <bindingRedirect oldVersion="0.0.0.0-4.2.0.0" newVersion="4.2.0.0"/>
    </dependentAssembly>
```
However, on compiling it fails to resolve the System.Net.Http assembly (it is there) and says that HttpRequestMessage is undefined and I should add a reference to System.Net.Http 4.0

Any ideas how I can make this work?

**Comment by Tratcher** [comment]
This issue was moved to aspnet/AspNetWebStack#167
