### ISSUE TITLE
Improve hosting APIs for startup self host scenarios

### ISSUE THREAD

**Issue by davidfowl** [aspnet/Hosting#145]
While updating omnisharp to beta2 I ended up doing this https://github.com/OmniSharp/omnisharp-roslyn/blob/beta2/src/OmniSharp/Startup.cs#L38, because we made it close to impossible to add services if you're the host. I suggest we make it so that the caller of HostingServices.Create can provider types that will be imported by the calling application.

/cc @HaoK @lodejard @Tratcher

**Comment by HaoK** [comment]
Yeah I agree I felt the same way when writing unit tests as well.
