### ISSUE TITLE
implement Environment.IsDocker

### ISSUE THREAD

**Issue by cilerler** [aspnet/Hosting#1454]
According to https://github.com/dotnet/announcements/issues/71 new docker images adds `DOTNET_RUNNING_IN_CONTAINER=true` into the environment variables.  

Based on that please implement `Environment.IsDocker`

```
bool IsDocker => bool.TryParse(Environment.GetEnvironmentVariable("DOTNET_RUNNING_IN_CONTAINER"), out bool isDocker) && isDocker;
```

**Comment by Tratcher** [comment]
This issue was moved to dotnet/corefx#30246
