### ISSUE TITLE
GenericHostSample does not start when run as service

### ISSUE THREAD

**Issue by waxingsatirical** [aspnet/Hosting#1456]
If you install GenericHostSample.exe as a service and attempt to start it, the start attempt times out. Startup object ProgramHelloWorld, TargetFramework net461.

sc create GenericHostSampleService binPath= "path to exe"
sc start GenericHostSampleService

Bit confused about the implementaion of BackGroundService. It returns a task which is representative of the long-running process in AsyncStart, whereas ServiceB returns a completed task in AsyncStart???

**Comment by Tratcher** [comment]
Which Program.Main are you using? The default one is for consoles.

**Comment by Tratcher** [comment]
Is this what you're looking at?
https://github.com/aspnet/Hosting/blob/712c992ca827576c05923e6a134ca0bec87af4df/src/Microsoft.Extensions.Hosting.Abstractions/BackgroundService.cs#L35

**Comment by waxingsatirical** [comment]
My mistake, I was using ProgramHelloWorld. AsyncStart logic also fine.
