### ISSUE TITLE
Support for user defined correlation consumption

### ISSUE THREAD

**Issue by seth-capistron** [aspnet/Hosting#1462]
## Motivation
Currently, the Request-Id header is read and used to populate the Activity.Current instance. There is a need for services to support other forms of correlation, namely Correlation Vector and the MS-CV header. The motivation is to allow developers an intuitive hook where they can control the incoming correlation that is tracked by their ASP.NET Core application.

## Proposed API
```cs
namespace Microsoft.AspNetCore.Hosting.Internal
{
    public class HostingApplication
    {
        /// <summary>
        /// Developers only need to call this method once for the lifetime of their application.
        /// HostingApplication will execute these callbacks as part of the incoming request
        /// code. They will be called after an Activity has been created but before it has been
        /// started. This will give the callback an opportunity to read any incoming headers and
        /// act on any Activity Extensions.
        /// </summary>
        public static void RegisterCorrelationConsumer(
            Action<HttpContext, HostingApplication.Context> correlationConsumer)
        { ... }
    }
}
```
## Usage
```cs
// This code assumes changes to Activity based on https://github.com/dotnet/corefx/issues/30369
HostingApplication.RegisterCorrelationConsumer(
    (HttpContext httpContext, HostingApplication.Context context) =>
    {
        var currentExtension = context.Activity?.GetActivityExtension<CorrelationVectorExtension>();

        if (currentExtension != null &&
            httpContext.Request.Headers.ContainsKey(CorrelationVectorPropagationDelegates.HeaderName))
        {
            currentExtension.SetExternalCorrelationVectorParent(
                httpContext.Request.Headers[CorrelationVectorPropagationDelegates.HeaderName][0]);
        }
    });
```
CC: @SergeyKanzhelev, @vancem, @jacpull, @lmolkova, @glennc, @davidfowl, @aaronrm

**Comment by davidfowl** [comment]
The goal seems fine but we don't design APIs like this (public static methods). It would likely be a service you can register in the DI container.

**Comment by SergeyKanzhelev** [comment]
@seth-capistron what's the drawback of listening for `Microsoft.AspNetCore.Hosting.HttpRequestIn.Start` event and update Activity from inside the callback. Similar to how we do back compat in Application Insights [today](https://github.com/Microsoft/ApplicationInsights-aspnetcore/blob/217e5d415a4b0c4dfd00164d842f55aa4321e5e6/src/Microsoft.ApplicationInsights.AspNetCore/DiagnosticListeners/Implementation/HostingDiagnosticListener.cs#L81-L88)


Similar comment to https://github.com/dotnet/corefx/issues/30369#issuecomment-397449301. Sorry if I missing something, but it would be great to list the issues with this approach.

**Comment by seth-capistron** [comment]
Going to close this since we are going to leverage the Diagnostic Source activity instead.

**Comment by jacpull** [comment]
What is the likelihood of this Event and its associated semantics being modified in future versions? And will it be considered a breaking change?

**Comment by SergeyKanzhelev** [comment]
@jacpull it is a breaking change. So any change of it will only happen with the major version revision.
