### ISSUE TITLE
Should there be a TestServer for Generic Host?

### ISSUE THREAD

**Issue by seesharper** [aspnet/Hosting#1464]
Just briefly looking into using a generic host for hosting background services.
The `TestServer` we have today takes an `IWebHostBuilder`. 

I'm just wondering if there should be a `TestServer` that takes an `IHostBuilder` so that we can spin up a in memory server for generic hosts as well?

**Comment by Tratcher** [comment]
And serve what? GenericHost doesn't support HTTP yet.

**Comment by davidfowl** [comment]
Closing this in place of https://github.com/aspnet/Hosting/issues/1583
