### ISSUE TITLE
2.1.1 HTTP error 502.5 in Chrome 

### ISSUE THREAD

**Issue by dotNetAthlete** [aspnet/Hosting#1469]
I have just followed the instructions in VS 2017 to update installed NuGet dependencies for AspNetCore from 2.1.0-preview1 final to 2.1.1.
Now I can't even debug into the start file

**Comment by Tratcher** [comment]
Release 2.1.1 is still being deployed, please use 2.1.0 instead.

**Comment by muratg** [comment]
@dotNetAthlete if you're still having issues, please file another issue.
