### ISSUE TITLE
RunAsync not returning when supplied CancellationToken cancelled

### ISSUE THREAD

**Issue by kierenj** [aspnet/Hosting#1474]
I'm on package version 2.0.0 / .NET SDK 2.1.201, and the following does not complete when `stop` is cancelled:

```
await _host.RunAsync(stop);
```

However, if I change to this, it works fine, exiting immediately / gracefully when it is cancelled:

```
stop.Register(() => _host.StopAsync(TimeSpan.FromSeconds(30)));
await _host.RunAsync(stop);
```

(Edit: well, it *seems* to stop nicely - `RunAsync`'s task finished. But I do see a thread in the debugger sitting at `Microsoft.AspNetCore.Hosting.Internal.HostedServiceExecutor.StopAsync` afterwards)
(Edit 2: oops, sorry, no, the addition of the StopAsync call works *intermittently*.)

From the intellisense it seemed that calling `StopAsync` wouldn't be necessary?
If this is unexpected, what's the best thing I can do to assist in diagnosing?

**Comment by Tratcher** [comment]
Does it behave any different with 2.1?

**Comment by davidfowl** [comment]
@kierenj Can you provide a repro?

**Comment by kierenj** [comment]
I'll try to put one together this week, as well as try with 2.1 to see if that changes anything

**Comment by kierenj** [comment]
I tried a minimal repro from scratch on 2.0 and couldn't repro the issue.
The issue shows itself using our library which provides a basis for API apps, so it's a little difficult to unpick.

After triggering the cancellation token, looking at the threads window, things of note:

- 4x LibuvThread at `Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.dll!Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.Networking.LibuvFunctions.run`
- Plenty of threads in `Pipelines.Sockets.Unofficial.dll!Pipelines.Sockets.Unofficial.DedicatedThreadPoolPipeScheduler.RunWorkLoop` (likely from the new StackExchange.Redis)
- This one looks interesting (it doesn't move from here):

![image](https://user-images.githubusercontent.com/82343/45346087-1b2b0880-b5a0-11e8-816d-21d145c54956.png)

- One or two threads like this:

![image](https://user-images.githubusercontent.com/82343/45346131-3e55b800-b5a0-11e8-933c-a3f378930a0e.png)

Then I tried package version `2.1.1`, this thread seems to be of the most interest:

![image](https://user-images.githubusercontent.com/82343/45346699-d56f3f80-b5a1-11e8-95b1-95a79a022056.png)

(Hovering over the top line here shows `IsCancellationRequested=true`)

There's still some threads in a `WaitUntilCountOrTimeout` with `BlockingCollection`/`ConsoleLoggerProcessor` mentioned... but they're in `TryTake` so seems normal.

What else can I do to help diagnose?

**Comment by kierenj** [comment]
No, not in 2.0 or 2.1

**Comment by davidfowl** [comment]
Cab you provide a repro?

**Comment by davidfowl** [comment]
I'd close until further notice
