### ISSUE TITLE
SuppressStatusMessages() is not available on HostBuilder

### ISSUE THREAD

**Issue by matteocontrini** [aspnet/Hosting#1478]
With the WebHostBuilder we can call [SuppressStatusMessages](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.hosting.hostingabstractionswebhostbuilderextensions.suppressstatusmessages?view=aspnetcore-2.1#Microsoft_AspNetCore_Hosting_HostingAbstractionsWebHostBuilderExtensions_SuppressStatusMessages_Microsoft_AspNetCore_Hosting_IWebHostBuilder_System_Boolean_) to disable logging of status messages on the console when the application is started ([these ones](https://github.com/aspnet/Hosting/blob/4e1ba2a6c75fdc2866791b63bb22ee34efe74441/src/Microsoft.Extensions.Hosting/Internal/ConsoleLifetime.cs#L35)). With the HostBuilder, the method is not available.

In my case the requirement is to disable the status messages because when using an `ILogger` instance the output might get "interleaved", like in the following image (note that the "info" word is on the wrong line), but that's another (unrelated?) issue.

![image](https://user-images.githubusercontent.com/2164763/42136456-246ca858-7d5c-11e8-8e55-92b7d9887143.png)

**Comment by Tratcher** [comment]
This is managed differently for HostBuilder. See https://github.com/aspnet/Hosting/blob/f9d145887773e0c650e66165e0c61886153bcc0b/src/Microsoft.Extensions.Hosting/Internal/ConsoleLifetime.cs#L33

**Comment by matteocontrini** [comment]
Thanks, but I'm seeing a similar option in the WebHost as well

https://github.com/aspnet/Hosting/blob/a3300a6a605dd66d79fabc297e8d8abdb8b8edf6/src/Microsoft.AspNetCore.Hosting/WebHostExtensions.cs#L109

The difference is that with the WebHostBuilder [there's a method](https://github.com/aspnet/Hosting/blob/a63932a492513cdeb4935661145084cad2ae5521/src/Microsoft.AspNetCore.Hosting.Abstractions/HostingAbstractionsWebHostBuilderExtensions.cs#L168) for changing that property.

I'm probably missing something, but how am I supposed to set that `SuppressStatusMessages` option so that the `ConsoleLifetime` picks it up?

**Comment by Tratcher** [comment]
See the sample in https://github.com/aspnet/Hosting/issues/1346
