### ISSUE TITLE
Hosting should pick up 'app' environment var in IIS Express as well

### ISSUE THREAD

**Issue by rustd** [aspnet/Hosting#148]
Today, the following scenario only works on SelfHost.
Hosting does let you select the assembly to search. This can be set via the ’app’ environment variable. If they set this globally on their production machines then web applications will only try to load via the specified assembly. However, this can be overridden by specifying the same parameter on the command line. Once they’ve loaded their Startup class then they would be able to do their own initialization and use some self-defined convention to locate the normal application Startup and invoke it.
Please reference these links:
https://github.com/aspnet/Hosting/blob/dev/src/Microsoft.AspNet.Hosting/Program.cs#L49
https://github.com/aspnet/Hosting/blob/dev/src/Microsoft.AspNet.Hosting/HostingEngine.cs#L106

**Comment by Tratcher** [comment]
See https://github.com/aspnet/Helios/blob/7c2934b261e618cd5fa20e1a107bd0ed47eb7acf/src/Microsoft.AspNet.Loader.IIS/DotnetHttpApplication.cs#L94

**Comment by davidfowl** [comment]
@rustd What's the scenario?

**Comment by glennc** [comment]
Moving to backlog until I understand the scenario that requires overwriting  the app name.

**Comment by Tratcher** [comment]
Obsolete?

**Comment by glennc** [comment]
Closing given how long it's been. @rustd can reopen if he still wants something to happen with this.
