### ISSUE TITLE
Provide a better experience when using TestServer

### ISSUE THREAD

**Issue by PinpointTownes** [aspnet/Hosting#149]
That would be marvelous if we could simply give `TestServer` a startup generic type and if it could automagically call `Configure` and `ConfigureServices`. That would even be double great if it could set the environment name to "Testing" and invoke `ConfigureTestingServices`.

/cc @Tratcher

**Comment by PureKrome** [comment]
@PinpointTownes could you post some sample code, to explain your idea, pwease? #curious

**Comment by Tratcher** [comment]
Katana had this. 
http://katanaproject.codeplex.com/SourceControl/latest#src/Microsoft.Owin.Testing/TestServer.cs
`TestServer.Create<MyStartupType>()`

**Comment by HaoK** [comment]
Will take a look at this as part of revisiting hosting, considering at the least something like

`TestServer.Create(Action<IApplicationBuilder> configureApp, Action<IServiceCollection configureServices)'

So calls to UseServices will no longer be required

**Comment by davidfowl** [comment]
Having the type overload would be ideal as well. So the overloads would look like:

- `TestServer.Create(Action<IApplicationBuilder> configureApp)`
- `TestServer.Create<TStartup>()`
- `TestServer.Create(Action<IApplicationBuilder> configureApp, Action<IServiceCollection configureServices)`

**Comment by HaoK** [comment]
Fixed in https://github.com/aspnet/Hosting/pull/205

**Comment by PinpointTownes** [comment]
@HaoK fantastic! Does it also support `ConfigureTestingServices`? (or at least, can we specify a custom environment name?)

**Comment by HaoK** [comment]
Not yet, but I still need to look at how to expose everything in hosting to test server, there are too many permutations to simply add overloads for everything in TestServer.Create as it stands today

**Comment by HaoK** [comment]
merged 77e2dc263f11655312d4c73bb8e22d7b6254d485
