### ISSUE TITLE
Flaky test: ShutdownTestRun

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/Hosting#1503]
This test [fails](http://aspnetci/viewLog.html?buildId=514188&buildTypeId=XPlat_Linux_UbuntuUniverseCoreCLR) occasionally with the following error:
```
System.Exception : dotnet publish exited with exit code : 1
   at Microsoft.AspNetCore.Server.IntegrationTesting.ApplicationDeployer.DotnetPublish(String publishRoot) in /_/src/Microsoft.AspNetCore.Server.IntegrationTesting/Deployers/ApplicationDeployer.cs:line 150
   at Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer.DeployAsync() in /_/src/Microsoft.AspNetCore.Server.IntegrationTesting/Deployers/SelfHostDeployer.cs:line 55
   at Microsoft.AspNetCore.Hosting.FunctionalTests.ShutdownTests.ExecuteShutdownTest(String testName, String shutdownMechanic) in /_/test/Microsoft.AspNetCore.Hosting.FunctionalTests/ShutdownTests.cs:line 70
   at Microsoft.AspNetCore.Hosting.FunctionalTests.ShutdownTests.ShutdownTestRun() in /_/test/Microsoft.AspNetCore.Hosting.FunctionalTests/ShutdownTests.cs:line 33
--- End of stack trace from previous location where exception was thrown ---
------- Stdout: -------
| [0.025s] TestLifetime Information: Starting test ShutdownTestRun at 2018-07-25T01:54:30
| [0.001s] TestLifetime Information: Starting test ExecuteShutdownTest at 2018-07-25T01:54:31
| [0.014s] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: Deploying [Variation] :: ServerType=Kestrel, Runtime=CoreClr, Arch=x64, BaseUrlHint=, Publish=True
| [0.023s] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: SET ASPNETCORE_ENVIRONMENT=Shutdown
| [0.023s] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: Executing command dotnet publish  --output "/mnt/temp/buildTmp/2fddb6a2-127f-4395-b479-db25173f3890" --framework netcoreapp2.2 --configuration Release --no-restore -p:VerifyMatchingImplicitPackageVersion=false 
| [0.471s] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet-publish stdout: Microsoft (R) Build Engine version 15.7.179.6572 for .NET Core
| [0.472s] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet-publish stdout: Copyright (C) Microsoft Corporation. All rights reserved.
| [2.208s] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet-publish stdout: /mnt/work/33bdfc1cae7b2a38/packages/internal.aspnetcore.sdk/3.0.0-alpha1-10013/build/GenerateAssemblyInfo.targets(25,5): error MSB4062: The "Microsoft.AspNetCore.BuildTools.Sdk_GetAssemblyFileVersion" task could not be loaded from the assembly /mnt/work/33bdfc1cae7b2a38/packages/internal.aspnetcore.sdk/3.0.0-alpha1-10013/build/../tools/netcoreapp2.1/Internal.AspNetCore.Sdk.dll. Assembly with same name is already loaded Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask. [/mnt/work/33bdfc1cae7b2a38/modules/Hosting/src/Microsoft.Extensions.Hosting.Abstractions/Microsoft.Extensions.Hosting.Abstractions.csproj]
| [2.226s] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet-publish stdout: /mnt/work/33bdfc1cae7b2a38/packages/internal.aspnetcore.sdk/3.0.0-alpha1-10013/build/GenerateAssemblyInfo.targets(25,5): error MSB4062: The "Microsoft.AspNetCore.BuildTools.Sdk_GetAssemblyFileVersion" task could not be loaded from the assembly /mnt/work/33bdfc1cae7b2a38/packages/internal.aspnetcore.sdk/3.0.0-alpha1-10013/build/../tools/netcoreapp2.1/Internal.AspNetCore.Sdk.dll. Assembly with same name is already loaded Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask. [/mnt/work/33bdfc1cae7b2a38/modules/Hosting/src/Microsoft.AspNetCore.Hosting.Server.Abstractions/Microsoft.AspNetCore.Hosting.Server.Abstractions.csproj]
| [2.308s] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Error: dotnet publish exited with exit code : 1
| [2.312s] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Warning: Host process already exited or never started successfully.
| [2.316s] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Warning: Failed to delete directory : Could not find a part of the path '/mnt/temp/buildTmp/2fddb6a2-127f-4395-b479-db25173f3890'.
| [2.416s] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Warning: Failed to delete directory : Could not find a part of the path '/mnt/temp/buildTmp/2fddb6a2-127f-4395-b479-db25173f3890'.
| [2.517s] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Warning: Failed to delete directory : Could not find a part of the path '/mnt/temp/buildTmp/2fddb6a2-127f-4395-b479-db25173f3890'.
| [2.619s] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: [Time]: Total time taken for this test variation '2.6044817' seconds
| [2.621s] TestLifetime Information: Finished test ExecuteShutdownTest in 2.6206626s
| [2.712s] TestLifetime Information: Finished test ShutdownTestRun in 2.7011415s
```

**Comment by ryanbrandenburg** [comment]
ShutdownTestRun [failed again](http://aspnetci/viewLog.html?buildId=514299&buildTypeId=XPlat_Linux_UbuntuUniverseCoreCLR).

**Comment by ryanbrandenburg** [comment]
ShutdownTestRun [failed again](http://aspnetci/viewLog.html?buildId=514791&buildTypeId=XPlat_Linux_UbuntuUniverseCoreCLR).

**Comment by ryanbrandenburg** [comment]
ShutdownTestRun [failed again](http://aspnetci/viewLog.html?buildId=514893&buildTypeId=XPlat_Linux_UbuntuUniverseCoreCLR).

**Comment by ryanbrandenburg** [comment]
ShutdownTestRun [failed again](http://aspnetci/viewLog.html?buildId=514938&buildTypeId=XPlat_Linux_UbuntuUniverseCoreCLR).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
ShutdownTestRun [failed again](http://aspnetci/viewLog.html?buildId=515667&buildTypeId=XPlat_Linux_UbuntuUniverseCoreCLR).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
ShutdownTestRun [failed again](http://aspnetci/viewLog.html?buildId=515729&buildTypeId=XPlat_Linux_UbuntuUniverseCoreCLR).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
ShutdownTestRun [failed again](http://aspnetci/viewLog.html?buildId=515846&buildTypeId=XPlat_Linux_UbuntuUniverseCoreCLR).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
ShutdownTestRun [failed again](http://aspnetci/viewLog.html?buildId=516066&buildTypeId=XPlat_Linux_UbuntuUniverseCoreCLR).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
ShutdownTestRun [failed again](http://aspnetci/viewLog.html?buildId=516723&buildTypeId=XPlat_Linux_UbuntuUniverseCoreCLR).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
ShutdownTestRun [failed again](http://aspnetci/viewLog.html?buildId=516866&buildTypeId=XPlat_Linux_UbuntuUniverseCoreCLR).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
ShutdownTestRun [failed again](http://aspnetci/viewLog.html?buildId=517245&buildTypeId=XPlat_Linux_UbuntuUniverseCoreCLR).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
ShutdownTestRun [failed again](http://aspnetci/viewLog.html?buildId=517579&buildTypeId=Releases_22xPublic_UbuntuUniverse).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
ShutdownTestRun [failed again](http://aspnetci/viewLog.html?buildId=517677&buildTypeId=XPlat_Linux_UbuntuUniverseCoreCLR).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
ShutdownTestRun [failed again](http://aspnetci/viewLog.html?buildId=517920&buildTypeId=Releases_22xPublic_UbuntuUniverse).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
ShutdownTestRun [failed again](http://aspnetci/viewLog.html?buildId=517995&buildTypeId=XPlat_Linux_UbuntuUniverseCoreCLR).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
ShutdownTestRun [failed again](http://aspnetci/viewLog.html?buildId=518078&buildTypeId=XPlat_Linux_UbuntuUniverseCoreCLR).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
ShutdownTestRun [failed again](http://aspnetci/viewLog.html?buildId=518000&buildTypeId=Releases_22xPublic_UbuntuUniverse).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
ShutdownTestRun [failed again](http://aspnetci/viewLog.html?buildId=519154&buildTypeId=XPlat_Linux_UbuntuUniverseCoreCLR).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
ShutdownTestRun [failed again](http://aspnetci/viewLog.html?buildId=519259&buildTypeId=Releases_22xPublic_UbuntuUniverse).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
ShutdownTestRun [failed again](http://aspnetci/viewLog.html?buildId=519473&buildTypeId=Releases_22xPublic_UbuntuUniverse).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
ShutdownTestRun [failed again](http://aspnetci/viewLog.html?buildId=519354&buildTypeId=XPlat_Linux_UbuntuUniverseCoreCLR).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
ShutdownTestRun [failed again](http://aspnetci/viewLog.html?buildId=519655&buildTypeId=Releases_22xPublic_UbuntuUniverse).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by Eilon** [comment]
@Tratcher - can you please take a look at this failing/flaky test?

**Comment by ryanbrandenburg** [comment]
ShutdownTestRun [failed with about the same error](http://aspnetci/viewLog.html?buildId=519178&buildTypeId=Releases_22xPublic_UbuntuUniverse).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
ShutdownTestRun [failed with about the same error](http://aspnetci/viewLog.html?buildId=520907&buildTypeId=Releases_22xPublic_UbuntuUniverse).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
ShutdownTestRun [failed with about the same error](http://aspnetci/viewLog.html?buildId=522190&buildTypeId=Releases_22xPublic_UbuntuUniverse).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
ShutdownTestRun [failed with about the same error](http://aspnetci/viewLog.html?buildId=523227&buildTypeId=Releases_22xPublic_UbuntuUniverse).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by Tratcher** [comment]
@natemcmaster does this error make sense to you?
```
[2.399s] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet-publish stdout: /mnt/work/33bdfc1cae7b2a38/packages/internal.aspnetcore.sdk/3.0.0-alpha1-20180731.2/build/GenerateAssemblyInfo.targets(25,5): error MSB4062: The "Microsoft.AspNetCore.BuildTools.Sdk_GetAssemblyFileVersion" task could not be loaded from the assembly /mnt/work/33bdfc1cae7b2a38/packages/internal.aspnetcore.sdk/3.0.0-alpha1-20180731.2/build/../tools/netcoreapp2.1/Internal.AspNetCore.Sdk.dll. Assembly with same name is already loaded Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask. [/mnt/work/33bdfc1cae7b2a38/modules/Hosting/src/Microsoft.AspNetCore.Hosting.Server.Abstractions/Microsoft.AspNetCore.Hosting.Server.Abstractions.csproj]
[2.518s] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet-publish stdout: /mnt/work/33bdfc1cae7b2a38/packages/internal.aspnetcore.sdk/3.0.0-alpha1-20180731.2/build/GenerateAssemblyInfo.targets(25,5): error MSB4062: The "Microsoft.AspNetCore.BuildTools.Sdk_GetAssemblyFileVersion" task could not be loaded from the assembly /mnt/work/33bdfc1cae7b2a38/packages/internal.aspnetcore.sdk/3.0.0-alpha1-20180731.2/build/../tools/netcoreapp2.1/Internal.AspNetCore.Sdk.dll. Assembly with same name is already loaded Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask. [/mnt/work/33bdfc1cae7b2a38/modules/Hosting/src/Microsoft.Extensions.Hosting.Abstractions/Microsoft.Extensions.Hosting.Abstractions.csproj]
```

**Comment by natemcmaster** [comment]
It happens when you run `dotnet publish` without `--no-restore` in the context of a Universe build. In general, it's better to use `--no-restore` if you can. It prevents `dotnet-publish` from re-restoring the .csproj and changing its dependencies.

**Comment by ryanbrandenburg** [comment]
ShutdownTestRun [failed with about the same error](http://aspnetci/viewLog.html?buildId=523974&buildTypeId=Releases_22xPublic_UbuntuUniverse).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
ShutdownTestRun [failed with about the same error](http://aspnetci/viewLog.html?buildId=524045&buildTypeId=Releases_22xPublic_UbuntuUniverse).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by Tratcher** [comment]
--no-restore is being used here.

There's definitely a build tools issue here. The tests pass on Mondays and continue to pass until Universe updates it's BuildTools dependency.

First failure 27 Jul 18 16:32: http://aspnetci/viewLog.html?buildId=517560&tab=buildResultsDiv&buildTypeId=Releases_22xPublic_UbuntuUniverse
This may have been the very first build of BuildTools produced by VSTS. Is it possible there was a regression in BuildTools when transitioned to VSTS?

**Comment by ryanbrandenburg** [comment]
ShutdownTestRun [failed with about the same error](http://aspnetci/viewLog.html?buildId=525152&buildTypeId=XPlat_Linux_UbuntuUniverseCoreCLR).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
ShutdownTestRun [failed with about the same error](http://aspnetci/viewLog.html?buildId=525813&buildTypeId=Releases_22xPublic_UbuntuUniverse).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
ShutdownTestRun [failed with about the same error](http://aspnetci/viewLog.html?buildId=527001&buildTypeId=Releases_22xPublic_UbuntuUniverse).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
ShutdownTestRun [failed with about the same error](http://aspnetci/viewLog.html?buildId=527413&buildTypeId=XPlat_Linux_UbuntuUniverseCoreCLR) on master.

This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by natemcmaster** [comment]
Should be resolved by this update to build tools https://github.com/aspnet/BuildTools/pull/734
