### ISSUE TITLE
IApplicationLifetime ApplicationStopping does not trigger if ConfigureServices method exists

### ISSUE THREAD

**Issue by davidfowl** [aspnet/Hosting#151]
I spent a good few hours trying to track this down on mono and it seems like it happens on windows as well. 

```C#
using System;
using Microsoft.AspNet.Http;
using Microsoft.AspNet.Builder;
using Microsoft.AspNet.Hosting;
using Microsoft.Framework.DependencyInjection;

public class Startup
{
    public void ConfigureServices(IServiceCollection services)
    {

    }

    public void Configure(IApplicationBuilder app, IApplicationLifetime lifetime)
    {
        lifetime.ApplicationStopping.Register(OnStuff);
    }

    public void OnStuff()
    {
        Console.WriteLine("Goodbye!");
    }
}
````

The above code will not print out goodbye.

**Comment by Praburaj** [comment]
Related: https://github.com/aspnet/WebListener/issues/71

**Comment by davidfowl** [comment]
Is it? It happens when use kestrel. Seems like a bug in hosting

**Comment by Tragetaschen** [comment]
On Mono, Kestrel throws an Exception during its `Dispose` (aspnet/KestrelHttpServer#49). This means the cleanup code in `HostingEngine.Start`'s `Disposable` does not invoke [`applicationLifetime.SignalStopped()`](https://github.com/aspnet/Hosting/blob/dev/src/Microsoft.AspNet.Hosting/HostingEngine.cs#L51)

**Comment by davidfowl** [comment]
I'm not sure that's even related, when you remove ConfigureServices, the text `"Goodbye!"` gets printed

**Comment by davidfowl** [comment]
Here's my workaround:

```
using System;
using Microsoft.AspNet.Builder;
using Microsoft.AspNet.Hosting;
using Microsoft.Framework.DependencyInjection;

namespace WebApplication52
{
    public class Startup
    {
        public void ConfigureServices(IServiceCollection services, IApplicationLifetime lifetime)
        {
            services.AddInstance(lifetime);
        }

        public void Configure(IApplicationBuilder app, IApplicationLifetime lifetime)
        {
            lifetime.ApplicationStopping.Register(OnStuff);
        }

        public void OnStuff()
        {
            Console.WriteLine("Goodbye!");
        }
    }
}

```

**Comment by Praburaj** [comment]
okay. Actually these are all problems related to app shutdown .

**Comment by davidfowl** [comment]
This is specifically related to the fact that something is going bonkers when services are applied. I don't think this has to do with app shutdown per se as everything is functioning. It feels like its triggering the event on some bogus ApplicationLifetime service, rather than the one I'm using. Which is why the above code seems to work.

**Comment by Praburaj** [comment]
Looks like the case. I can see a difference in the `ApplicationStopping` cancellation token that I receive in `ConfigureServices` vs `Configure`. If `ConfigureServices` is present then hosting additionally does a `services.BuildServiceProvider()`. I'm investigating this more.

**Comment by Praburaj** [comment]
Fixed https://github.com/aspnet/Hosting/commit/718d923c7dd1d1039fba3a5d987793226de117b7
