### ISSUE TITLE
Init.d issues startup

### ISSUE THREAD

**Issue by deinok** [aspnet/Hosting#1512]
Hi, I'm having a strange issue with the startup of the the webhost.

First of all, the device is a Linux x86, and the engine to run the AspNetCore app is mono 5.12

Everything goes perfect when I run `mono myApp.exe` the server is started and is lisening okey.
But it needs to be runned at the startup, so a I create a file in /etc/init.d/myApp.init.sh
```bash
#!/bin/bash

start() {
	mono myApp.exe
}

#stop() {
#}

#reload() {
#}

#status() {
#}

case "$1" in
	start)
		start
		;;
	stop)
#		stop 
		;;
	restart)
#		stop
		start
		;;
	reload)
#		reload
		;;
	status)
#		status
		;;
	*)
		echo $"Usage: $0 {start|stop|restart|reload|status}" 
esac
```
Then I run the following -> `update-rc.d myApp.init.sh default 99`, and I restart the devices.

And here comes the issue:
At the startup of the device, mono starts working, trying to execute the .exe
If for example I write simple code not related to AspNetCore it works well.
But when It try to run the `WebHost` it stucks. Seems like mono starts using about 95% of CPU (Device is 400Mhz) but the interesting thing is that it never ends.
Seems like some kind of issue with runlevels.

Aditional Notes:
Device is an IOT2000 with mono-5.12
The init daemon is not systemd

**Comment by deinok** [comment]
Any idea @Tratcher

**Comment by Tratcher** [comment]
No. Any way to attach a debugger or capture a dump?

**Comment by deinok** [comment]
I can try to debug it by command line an try to detect the point where it enters to the infinite loop.
But it will be hard, cause this just happen at init time.

**Comment by deinok** [comment]
[correct_execution_debug.log](https://github.com/aspnet/Hosting/files/2261645/correct_execution_debug.log)
[incorrect_execution_debug.log](https://github.com/aspnet/Hosting/files/2261646/incorrect_execution_debug.log)

I have executed the following command:
`mono --trace=Microsoft.AspNetCore.Hosting /myApp.exe`
With:
mono ->5.12.0.226
net471 
Microsof.AspNetCore.Hosting -> 2.1.1
publish -> debug

The line 109 of correct_execution_debug.log is never done when executed at init time.

**Comment by deinok** [comment]
More hard tracing indicates that the problem is in `Microsoft.Extensions.Configuration.ConfigurationBuilder:Build`
The method is ENTER but never LEAVE

**Comment by Tratcher** [comment]
Possibly related: https://github.com/aspnet/Hosting/issues/1287
Mono has known issues with the file change watcher which configuration would also use. If you set your config files to not reload on change does it help?

**Comment by deinok** [comment]
Probably yes, i found that the issue happenz when using the default webhost, when build method is called.
This generates a lot of file watchdogs.
I will try to close more the circle of where it happenz and the reason it happen

**Comment by deinok** [comment]
Seems like the error is caused due`.UseContentRoot()` and triggered in `.Build()`

The default implementation `CreateDefaultBuilder()` seems to call `.UseContentRoot(Directory.GetCurrentDirectory())` and at init time `Directory.GetCurrentDirectory()` is `/` while `AppContext.BaseDirectory` returns the correct path where the assembly live.
Changing to `.UseContentRoot(AppContext.BaseDirectory)` works well.

@Tratcher Is there any diference in `Directory.GetCurrentDirectory()` vs `AppContext.BaseDirectory`?

**Comment by Tratcher** [comment]
The calling application decides what the current directory is, it's not uncommon to need to override it. BaseDirectory isn't always what you want either, in many tooling scenarios it points to bin/debug/etc...

**Comment by deinok** [comment]
So, this is not a bug?

**Comment by Tratcher** [comment]
There may still be a bug around excess CPU usage, but the current directory itself does not look like a bug. I wonder if it's trying to create a file watcher for the entire drive, that would be expensive.

**Comment by deinok** [comment]
Yes, it is trying to create the watch for `/`.
When using BaseDirectory works well
