### ISSUE TITLE
Cannot spin up WebHostBuilderFactory<Startup> if Startup.cs is in a class Library

### ISSUE THREAD

**Issue by caseylobrien** [aspnet/Hosting#1517]
# Context: 
Spin up an in memory server following [this guide](https://docs.microsoft.com/en-us/aspnet/core/test/integration-tests?view=aspnetcore-2.1) for integration tests. The structure of the solution is not typical, the program.cs references a Startup.cs that is in a class library

### Error: 
`System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=Microsoft.AspNetCore.Mvc.Testing
  StackTrace:
   at Microsoft.AspNetCore.Mvc.Testing.WebApplicationFactory.CreateWebHostBuilder()
   at Microsoft.AspNetCore.Mvc.Testing.WebApplicationFactory.EnsureServer()
   at Microsoft.AspNetCore.Mvc.Testing.WebApplicationFactory.CreateDefaultClient(DelegatingHandler[] handlers)
   at Microsoft.AspNetCore.Mvc.Testing.WebApplicationFactory.CreateClient(WebApplicationFactoryClientOptions options)
   `

### Debugging:
Loaded the pdb for MS libraries and stepped into the code and determined that `typeof(TEntryPoint).Assembly.EntryPoint` evaluates to null in `WebApplicationFactory.CreateWebHostBuilder` and throws `NullArgumentException` rather than the intended `InvalidOperationException`

### Expectations
If a Startup class in a dll is not allowed as described at
 `System.Reflection.Assembly.EntryPoint` 's return tag "An object that represents the entry point of this assembly. If no entry point is found (for example, the assembly is a DLL), null is returned." 
then I would expect an `InvalidOperationException` thrown stating as much rather than a `NullReferenceException`

### Work around:
Inside the Integration Test's project, add a Startup class that inherits from the class library's Startup file

**Comment by Tratcher** [comment]
@javiercn

**Comment by javiercn** [comment]
@caseylobrien thanks for contacting us.

WebApplicationFactory<TEntryPoint> requires a class in the entry point assembly of your app. We use Startup as in the most common case it's on your entry point assembly.

Given that you've moved your startup class to a class library, you need to change the class passed as an argument to use Program. (Or whatever class your main method is in).

Closing this as there's no more action to be taken here for now. Feel free to reopen this issue if this doesn't solve your problem.

**Comment by caseylobrien** [comment]
Requiring a non-static class from an entry point of the Assembly makes perfect sense. I was suggesting that a better Exception than a generic `NullReferenceExcpetion` be thrown instead.

**Comment by caseylobrien** [comment]
If you agree that this would be useful, I would not mind taking a stab at a PR for this.

**Comment by javiercn** [comment]
@caseylobrien We'll be ok to take a PR for that. Could you file an issue in the MVC repo? (where the code lives) And we can follow up there?

**Comment by caseylobrien** [comment]
Sure can. Thanks!
