### ISSUE TITLE
Visual Studio compilation : System namespace not found

### ISSUE THREAD

**Issue by dtkujawski** [aspnet/Hosting#152]
This is probably a beginner question for how to work with the ASPNET repo here:
I am able to fork and clone the repo and successfully run the "Build" command (everything download and compiles fine from the command line).

However, when I load the solution in Visual Studio and try to compile, I get lots of errors because VS doesn't seem to resolve the "System" namespace.
		CS0246	The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?)

Is there any wiki or other document on how to get started working with these source files?  I've checked the KSPROJ and dependencies and all seems normal to me.  I think the source is cloned ok, since I am able to run BUILD form the command line.

Any help would be appreciated.

UPDATE: If I create a new project (vNEXT Class Library) in the same Hosting Solution, it finds the System namespace correctly and compiles fine in Visual Studio.  So, it appears to be dependency related.  If I start removing the dependencies in the project.json file - I can get it VS to see "system".  So, I'm wondering if maybe some of the dependencies are compiled with different version of system somehow causing VS to get confused?

**Comment by davidfowl** [comment]
Unfortunately this won't work with beta2. You'll have to use something like omnisharp or wait until a new version of visual studio comes out. There were some breaking changes around folder names and ctp5 won't function properly

**Comment by dtkujawski** [comment]
Thank you!  I was making myself crazy by trying weird things to see if I could get it working.
