### ISSUE TITLE
Run Generic Host can not read config when start as windows service

### ISSUE THREAD

**Issue by huyjack178** [aspnet/Hosting#1521]
![image](https://user-images.githubusercontent.com/11793001/44143273-5724b8de-a0ad-11e8-87b4-eafaf9db172b.png)
This is my code in Program.cs to read appsettings.json.
But I got error when install and run as windows service. Can anyone help me?
```
Exception Info: System.IO.FileNotFoundException: 
The configuration file 'appsettings.json' was not found and is not optional. 
The physical path is 'C:\WINDOWS\system32\appsettings.json'.
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load(Boolean reload)

```

**Comment by Tratcher** [comment]
See https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/windows-service?view=aspnetcore-2.1#get-started for setting content root in a service.

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
