### ISSUE TITLE
`TestServer` seems to use `HTTPS_PORT` env var instead of `ASPNETCORE_HTTPS_PORT`

### ISSUE THREAD

**Issue by dougbu** [aspnet/Hosting#1523]
Using a fairly-generic 2.1 web site with `app.UseHttpsRedirection();` in its `Startup.Configure(...)` method, the following code does _not_ prevent the `Failed to determine the https port for redirect.` warning from the middleware:
``` c#
Environment.SetEnvironmentVariable("ASPNETCORE_HTTPS_PORT", "443");

using (var server = new TestServer(builder))
{
    var httpClient = server.CreateClient();
    // send a request to HTTP port e.g. client's default base address
}
```

When starting the same site using `dotnet run`, the `ASPNETCORE_HTTPS_PORT` environment variable has the expected impact -- no warning and the client is redirected to the named port.

The following code is necessary to clean up the warning when using `TestServer`:
``` c#
Environment.SetEnvironmentVariable("HTTPS_PORT", "443");

using (var server = new TestServer(builder))
{
    var httpClient = server.CreateClient();
    // send a request to HTTP port e.g. client's default base address
}
```

The above inconsistency feels like a bug in `TestServer` per @jkotalik

**Comment by Tratcher** [comment]
Setting up config sources for IWebHostBuilder isn't a responsibility of TestServer, WebHostBuilder does that. "ASPNETCORE_" should be enabled by default, but from your example you may have set the variable too late, after creating the builder.
