### ISSUE TITLE
`TestServer` does not honour `launchSettings.json`

### ISSUE THREAD

**Issue by dougbu** [aspnet/Hosting#1525]
Ideally neither of the workarounds described in #1523 and #1524 should be necessary to avoid warnings / successfully redirect when fetching using HTTP with `TestServer`. The net outcome would be to make `IServerAddressesFeature.Addresses` more closely align with the values included when running the same site for realz.

One option would be for `TestServer` to honour `launchSettings.json`. Obviously, this is specific to the case where the `TestServer` application starts in the web site's project directory and the site app has not been published.

To be clear, this issue is not a high priority from my POV. Just an annoyance I hit that seemed worth reporting.

----

I suspect other ways to configure ports / schemes / URIs / et cetera are mostly honoured in `TestServer` already, modulo #1523 and #1524. But, that may be worth confirming.

**Comment by Tratcher** [comment]
TestServer is a code-first component for testing middleware, not full applications. launchSettings.json support seems more appropriate for https://github.com/aspnet/Mvc/blob/a7301120b1971d6d047c63db5e6911aa134f99a2/src/Microsoft.AspNetCore.Mvc.Testing/WebApplicationFactory.cs.

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
