### ISSUE TITLE
Wrong configuration injected into Startup

### ISSUE THREAD

**Issue by BalassaMarton** [aspnet/Hosting#1528]
Try this setup:

```cs
    public class Program
    {
        public static void Main(string[] args)
        {
            CreateWebHostBuilder(args).Build().Run();
        }

        public static IConfiguration BuildConfiguration()
        {
            return new ConfigurationBuilder()
                .SetBasePath(Directory.GetCurrentDirectory())
                .AddJsonFile("appsettings.json")
                .AddJsonFile("othersettings.json")
                .Build();
        }

        public static IWebHostBuilder CreateWebHostBuilder(string[] args)
        {
            return WebHost.CreateDefaultBuilder(args)
                .UseConfiguration(BuildConfiguration())
                .UseStartup<Startup>();
        }
    }

    public class Startup
    {
        public Startup(IConfiguration configuration)
        {
            Configuration = configuration;
        }

        public IConfiguration Configuration { get; }

        // ...  
    }
```

The configuration object injected into `Startup` will not have any values or providers from the one passed to `UseConfiguration`, e.g. nothing from `othersettings.json`. The configuration is otherwise correctly injected into controllers and pages.

**Comment by BalassaMarton** [comment]
Workaround is to use `ConfigureAppConfiguration` instead of `UseConfiguration`.

**Comment by khellang** [comment]
It's not really a "workaround". Everything works as designed, as confusing as it is. The `ConfigureAppConfiguration` exist for a reason 😉 See https://github.com/aspnet/Hosting/issues/1148#issuecomment-318524939

**Comment by BalassaMarton** [comment]
After a few hours of trial and error, I can finally repro the problem. It's not that the wrong instance is injected. When using `WebHost.CreateDefaultBuilder`, `appsettings.json` is loaded _after_ anything that was passed to `UseConfiguration`, overwriting existing values. The problem goes away when either calling `ConfigureAppConfiguration` or building the host manually with a new `WebHostBuilder`.
I'm not sure if this qualifies as a bug, it's more like a documentation problem. The previously quoted sections fail to mention that the default builder itself calls `ConfigureAppConfiguration`, which ultimately overwrites anything passed in `UseConfiguration`.
To try it out, clone this repo and fiddle with the switches in `Program.cs`
https://github.com/BalassaMarton/AspnetHosting1528Repro

**Comment by lonix1** [comment]
@BalassaMarton This is certainly a mess!

In my case I need to start logging before the webhost, to ensure if something goes wrong during startup, it gets logged! So I setup 1) configuration, 2) logging (serilog) and 3) webhost.

So obviously I pass the config into `UseConfiguration()` and it doesn't work properly. But if I use `ConfigureAppConfiguration()` it does work, but trashes the existing config, so my webhost and logging are using different config!

What approach are you now using?

**Comment by lonix1** [comment]
I posted a [separate issue](https://github.com/aspnet/Hosting/issues/1532) for that.

@BalassaMarton I tried your code and get the same results.

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
