### ISSUE TITLE
Question: RunAsService for non web-apps

### ISSUE THREAD

**Issue by johnkors** [aspnet/Hosting#1529]
Hi,

What would be the equivalent of `host.RunAsService()` for regular .NET Core (non-web, no ASP.NET Core/Kestrel)-apps..? 

Do you have minimal sample of a host that does this? All samples I've seen are centered around hosting _ASP.NET Core_ as a Windows Service, but I only want a `IHostedService` to run background tasks - no Kestrel or WebHosts needed.

**Comment by khellang** [comment]
See https://github.com/aspnet/Hosting/blob/master/samples/GenericHostSample/ServiceBaseControlled.cs

**Comment by johnkors** [comment]
Thanks!

**Comment by johnkors** [comment]
So to get this part running, I'd need to implement the [the ServiceBaseLiftetime as in the sample](https://github.com/aspnet/Hosting/blob/master/samples/GenericHostSample/ServiceBaseLifetime.cs#L24) ? Any reason for it not being part of a NuGet somewhere instead of the samples..?

**Comment by davidfowl** [comment]
Because we haven't gotten to that part yet 😄

**Comment by johnkors** [comment]
Hah. Fair enough. 😸
