### ISSUE TITLE
ApplicationLifetime.Signal* rename

### ISSUE THREAD

**Issue by muratg** [aspnet/Hosting#154]
Some ideas from the API review:
- Notify
- Trigger

**Comment by Praburaj** [comment]
@muratg Is the suggestion here to rename `ApplicationStopping` to `NotifyStopping` and `ApplicationStopped` to `NotifyStopped`?

**Comment by muratg** [comment]
@Praburaj "Signal" to "Notify" I believe.  /cc: @glennc

**Comment by Praburaj** [comment]
I see. Changing it to `SignalStopping` and `SignalStopped` then.
