### ISSUE TITLE
Create an infrastructure/guidance for using WebHost with generic host and a single container

### ISSUE THREAD

**Issue by pakrym** [aspnet/Hosting#1541]
@Tratcher  @davidfowl 

We need to start pointing people to the right way of doing web host inside the generic host without having 3 containers.

**Comment by davidfowl** [comment]
This is the plan for 3.0. It's why generic host doesn't have a Startup class or a second and third container.

**Comment by pakrym** [comment]
We need to adapt https://github.com/aspnet/MetaPackages/blob/master/src/Microsoft.AspNetCore/WebHost.cs to work nicely in the generic host.

**Comment by Tratcher** [comment]
Current guidance: don't. We'll get this sorted out in 3.0.

**Comment by davidfowl** [comment]
Right, it's not a 2.2 work item. There isn't enough time to do anything good.

**Comment by davidfowl** [comment]
Closing in favor of #1544
