### ISSUE TITLE
Allow us to communicate with the TestServer over the network

### ISSUE THREAD

**Issue by drauch** [aspnet/Hosting#1549]
We would love to run our browser-based Selenium web tests against an instance of `TestServer` (as described here: https://docs.microsoft.com/en-us/aspnet/core/test/integration-tests?view=aspnetcore-2.1). Unfortunately, TestServer does not open an in-process HTTP server, instead it directly communicates with the application. It'd be great if there'd be a second `TestServer` which actually hosts an HTTP server (e.g., in-process Kestrel).

**Comment by Tratcher** [comment]
Why not just use kestrel?

**Comment by Tratcher** [comment]
Kestrel is fine for in process functional testing. TestServer is for more targeted unit testing.

**Comment by drauch** [comment]
Fair enough, then we keep going with our in process Kestrel strategy.
