### ISSUE TITLE
reading from appsettings in Program.cs using getsetting

### ISSUE THREAD

**Issue by imxavi** [aspnet/Hosting#1556]
Hi,
I have this:
```
        public static void Main(string[] args)
        {
            _config = LoadConfiguration(args);
            CreateWebHostBuilder(args).Build().Run();
        }
		
		public static IWebHostBuilder CreateWebHostBuilder(string[] args)
        {
            var hostBuilder = WebHost.CreateDefaultBuilder(args).UseConfiguration(_config);

            var settingName = "SHUTDOWNTIMEOUTSECONDS";
            var settingStrShutdownTimeout = hostBuilder.GetSetting(settingName);
			
            hostBuilder
			//....
                .UseStartup<StartUp>();

            return hostBuilder;
        }
 
         static IConfiguration LoadConfiguration(string[] args)
        {
            var builder = new ConfigurationBuilder()
            .SetBasePath(Directory.GetCurrentDirectory())
            .AddJsonFile("appsettings.json", optional: true, reloadOnChange: true);
            .AddEnvironmentVariables();
            if (args != null)
            {
                builder.AddCommandLine(args);
            }
            return builder.Build();
        }
```
I was expecting 2 things:
a) get SHUTDOWNTIMEOUTSECONDS from appsettings, but it gets null
b) if SHUTDOWNTIMEOUTSECONDS is in appsettings.json with 30 and launchSettings.json (env var) with 50, I was expecting 50 due to  Loadconfiguration order. i.e, env var overrides previous value set. but I am getting always what is in appsettings.
Is I use new WebHostBuilder()instead of WebHost.CreateDefaultBuilder is the same behavior.
Some light on what I am doing wrong please.
Thanks

**Comment by Tratcher** [comment]
Can you show appsettings.json and the related environment variables?

**Comment by imxavi** [comment]
Hi, sorry let me explain better.
I did 2 scenarios:
A) 
using just CreateDefaultBuilder without UseConfiguration
var hostBuilder = WebHost.CreateDefaultBuilder(args);

var settingName = "SHUTDOWNTIMEOUTSECONDS";
var settingStrShutdownTimeout = hostBuilder.GetSetting(settingName);

- launchSettings.json:
	SHUTDOWNTIMEOUTSECONDS not added to env vars
- appsettings.json:
{
  "SHUTDOWNTIMEOUTSECONDS": 50
}
like this settingStrShutdownTimeout is null.
Could it be that CreateDefaultBuilder only have the info from appsettings after 
IWebHostBuilder is Build()?

B) add  UseConfiguration with the code above in the initial question.
    files are with:
	
	- launchSettings.json:
	      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development",
        "ASPNETCORE_SHUTDOWNTIMEOUTSECONDS" : "50"
      }
	- appsettings.json:
	"SHUTDOWNTIMEOUTSECONDS": 30

	I was expecting to get 50 because in LoadConfiguration we do AddEnvironmentVariables() after AddJsonFile("appsettings.json"...)

Thanks in advance.

**Comment by Tratcher** [comment]
AddEnvironmentVariables isn't working because you need to specify the prefix in order for the matching to work correctly: `AddEnvironmentVariables("ASPNETCORE_")`.

hostBuilder.GetSettings reads only from the host config, where appsettings isn't loaded later until the app's config is build. That's why UseConfiguration works, it loads the config immediately into the host config.

**Comment by imxavi** [comment]
Hi, understood.
Thank You.
