### ISSUE TITLE
HostingContext.Servername: misleading name

### ISSUE THREAD

**Issue by muratg** [aspnet/Hosting#156]
Can be confused with the server name (as in URL)

**Comment by Praburaj** [comment]
Was there a suggestion on name during the discussion? 

A typical value for this looks like `Microsoft.AspNet.Server.WebListener` which is the package containing the server's factory type. Should we rename this to `ServerFactoryAssembly`?

This may also demand a change in the command parameter name from `--server` => `--serverfactory.assembly`

```
"web": "Microsoft.AspNet.Hosting --server Microsoft.AspNet.Server.WebListener --server.urls http://localhost:5002"
```

```
"web": "Microsoft.AspNet.Hosting --serverfactory.assembly Microsoft.AspNet.Server.WebListener --server.urls http://localhost:5002"
```

thoughts?
