### ISSUE TITLE
Question on Generic Host logging setup

### ISSUE THREAD

**Issue by guardrex** [aspnet/Hosting#1563]
@Tratcher In the Generic Host sample app, we have both `AddLogging` in service config and `AddConsole`+`AddDebug` in `ConfigureLogging`. I noticed that the call to `AddLogging` isn't required, and I speculated that perhaps `AddConsole` and `AddDebug` call `AddLogging` on their own.

We don't remark at all on `AddLogging`; and for `ConfigureLogging` all we say is ...

> `ConfigureLogging` adds a delegate for configuring the provided `ILoggingBuilder`. `ConfigureLogging` may be called multiple times with additive results.

Do we need to make any changes or call anything out in the topic/sample regarding logging activation?

```csharp
.ConfigureServices((hostContext, services) =>
{
    services.AddLogging();
    ...
})
.ConfigureLogging((hostContext, configLogging) =>
{
    configLogging.AddConsole();
    configLogging.AddDebug();
})
```

**Comment by Tratcher** [comment]
ConfigureLogging [embeds](https://github.com/aspnet/Hosting/blob/f9d145887773e0c650e66165e0c61886153bcc0b/src/Microsoft.Extensions.Hosting/HostingHostBuilderExtensions.cs#L61) AddLogging.

**Comment by guardrex** [comment]
Ok, thanks.

How do you want to handle it in the topic+sample? We can add a remark to the `ConfigureLogging` section of the topic, but that doesn't address the sample app including the call to `AddLogging` when it isn't necessary.

**Comment by Tratcher** [comment]
If anything it's there as an example for ConfigureServices. Have anything else that could go there? 

It would be worth mentioning somewhere what the default services are.

**Comment by guardrex** [comment]
Yes, we have the hosted services there because the sample for the topic is the hosted services sample. The full method is ...

```csharp
.ConfigureServices((hostContext, services) =>
{
    services.AddLogging();
    services.AddHostedService<LifetimeEventsHostedService>();
    services.AddHostedService<TimedHostedService>();
})
```

> It would be worth mentioning somewhere what the default services are.

Very good. :+1:

I've opened https://github.com/aspnet/Docs/issues/8893 to address these.
