### ISSUE TITLE
Include URL in request finished log message

### ISSUE THREAD

**Issue by HassanHashemi** [aspnet/Hosting#1575]
Having the URL of the request finished message would be some thing nice to have when parsing log message:

https://github.com/aspnet/Hosting/blob/f9d145887773e0c650e66165e0c61886153bcc0b/src/Microsoft.AspNetCore.Hosting/Internal/HostingRequestFinishedLog.cs#L53

![image](https://user-images.githubusercontent.com/6805984/47552550-d04c2280-d8b9-11e8-82d5-8c534cc6edec.png)

**Comment by Tratcher** [comment]
We've tried to avoid this kind of duplication. For anything but the most trivial cases you need to use tooling to correlate all the logs for a request, which will give you the request started log that has this information already.

**Comment by HassanHashemi** [comment]
@Tratcher Fair enough.
