### ISSUE TITLE
HostBuilder and headed UWP app on IoT core

### ISSUE THREAD

**Issue by tymtam2** [aspnet/Hosting#1578]
What is the correct way to run IHost in a headed UWP App on IoT Core to avoid issues with running code on the UI thread?

I have to have something working quickly so for now I went for Thread.Start.

```
internal sealed partial class App : Windows.UI.Xaml.Application
{
    (...)
    protected override void OnLaunched(LaunchActivatedEventArgs e)
    {
        (...)
        new System.Threading.Thread(() =>
        {
            System.Threading.Thread.CurrentThread.IsBackground = true;
            MyRun();
        }).Start();
    }

    public void MyRun()
    {
        (...) 
        Host = ConfigureHost().Build();
        Host.Run();
    }

    private IHostBuilder ConfigureHost()
    {
        return new HostBuilder()
            .ConfigureHostConfiguration...
            .ConfigureAppConfiguration...
    }
}
```

Is this a correct way? Is there a better way?

**Comment by davidfowl** [comment]
Are you just trying to avoid blocking on the UI thread until the host shuts down? You can start Start on the host instead of Run, then you can call Dispose in the dispose of the Windows.UI.Xaml.Application (or close, not sure which one exists).

**Comment by muratg** [comment]
Hi. We're closing this issue as no response or updates have been provided in a timely manner and we have been unable to reproduce it. If you have more details and are encountering this issue please add a new reply and re-open the issue.

**Comment by tymtam2** [comment]
We've stayed with 

```new System.Threading.Thread(() =>
        {
            System.Threading.Thread.CurrentThread.IsBackground = true;
            MyRun();
        }).Start();
```
solution, but moved from `OnLaunched` since `OnLaunched` is called multiple times.

**Comment by davidfowl** [comment]
But why?
