### ISSUE TITLE
can't stop in Task manager

### ISSUE THREAD

**Issue by gwhzh21** [aspnet/Hosting#1581]
Asp.net standalone mode,my app is 'webshopserverv3.exe' , remote windows desktop, can't close, prompts, can't abort the process, refuse access.

![qq 20181112164938](https://user-images.githubusercontent.com/17920677/48336320-f8e66180-e69a-11e8-9276-e83df38a21e5.png)

**Comment by gwhzh21** [comment]
windows server2008 r2

**Comment by Tratcher** [comment]
Are you using Kestrel or HttpSys?

**Comment by gwhzh21** [comment]
using Kersrel.

**Comment by Tratcher** [comment]
Can you capture a dump and look at the thread stacks?

**Comment by gwhzh21** [comment]
forget, next time.thanks.
