### ISSUE TITLE
launchBrowser blocks Visual Studio UI thread

### ISSUE THREAD

**Issue by dotnetchris** [aspnet/Hosting#1599]
launchBrowser seems to block the Visual Studio UI thread. When the browser window is being triggered Visual Studio becomes unresponsive until the window is finished opening.

**Comment by Tratcher** [comment]
Please give that feedback through the feedback tool in VS.

@BillHiebert

**Comment by dotnetchris** [comment]
Submitted https://developercommunity.visualstudio.com/content/problem/386547/launchbrowser-blocks-visual-studio-ui-thread.html
