### ISSUE TITLE
Rename IHttpContextAccessor.Value to IHttpContextAccessor.HttpContext

### ISSUE THREAD

**Issue by muratg** [aspnet/Hosting#160]

**Comment by HaoK** [comment]
@davidfowl filed https://github.com/aspnet/Options/issues/31 to change Options.Options -> Value, HttpContextAccessor seems to be going the other direction, do we have final consensus for naming these properties (Value or Type name)?

cc @divega @yishaigalatzer

**Comment by yishaigalatzer** [comment]
I'm game for whatever of the two as long as its consistent

**Comment by Praburaj** [comment]
@davidfowl ?

**Comment by davidfowl** [comment]
I dunno the 2 things need to be consistent. Look at the usage patterns:

```
private FooOptions _options;
public Foo(IOptions<FooOptions> options)
{
  _options = options.Options;
}
```

VS

```
private IHttpContextAccessor _accessor;
public Foo(IHttpContextAccessor accessor)
{
    _accessor = accessor;
}
```

**Comment by HaoK** [comment]
But IOptions true name was/is IOptionsAccessor, so it feels like they really should have the same naming pattern
