### ISSUE TITLE
Microsoft.AspNetCore.Hosting.WindowsServices RunAsServiceAsync

### ISSUE THREAD

**Issue by bugproof** [aspnet/Hosting#1600]
I'm using [C# 7.1 `async Task Main(string[] args)`](https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-7-1#async-main). I wanted to convert my project into a Windows Service following this: https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/windows-service?view=aspnetcore-2.1

In my `Program.Main` I'm using `await webHost.RunAsync();`. I was hoping to have something like `await webHost.RunAsServiceAsync()`. What should I do?

**Comment by Tratcher** [comment]
ServiceBase Run isn't async, there's nothing to do here.
https://github.com/aspnet/Hosting/blob/f9d145887773e0c650e66165e0c61886153bcc0b/src/Microsoft.AspNetCore.Hosting.WindowsServices/WebHostWindowsServiceExtensions.cs#L38-L39
