### ISSUE TITLE
Move IServerInformation and IServerFactory into a package that server authors can use

### ISSUE THREAD

**Issue by davidfowl** [aspnet/Hosting#172]
Today IServerInformation exists in Microsoft.AspNet.Http and IServerFactory exists in Hosting. We need to have a simple package that server authors like Nowin can use to implement the ASP.NET 5 server abstraction.

**Comment by davidfowl** [comment]
## Proposal

**Microsoft.AspNet.Hosting.Interfaces** - Interfaces made available to applications that use the ASP.NET hosting model.

- IHttpContextAccessor.cs
- IHostingEnvironment.cs

**Microsoft.AspNet.Hosting.Server.Interfaces** - The WebServer contract.

- IServerFactory.cs

Depends on
- Microsoft.Framework.ConfigurationModel.Interfaces
- Microsoft.AspNet.FeatureModel
- Microsoft.AspNet.Http

Some interfaces stay inside of the hosting package itself since they are pretty much implementation details.

- IApplicationLifetime.cs
- IConfigureHostingEnvironment.cs
- IHostingEngine.cs
- IStartupLoader.cs
- IServerLoader.cs
- IApplicationBuilderFactory.cs
- IHttpContextFactory.cs

Thoughts? /cc @lodejard @glennc @Eilon @muratg

**Comment by muratg** [comment]
Sounds fine to me.  How about IServerInformation?

**Comment by muratg** [comment]
@davidfowl assuming you wanted this in RC, assigning this to Prabu.

**Comment by davidfowl** [comment]
Renamed Hosting.Server interfaces to M.A.Server.Interfaces

**Comment by HaoK** [comment]
Since we already have a .Server subnamespace, maybe it would be clearer if we had a Engine namespace for the engine and the four interfaces that are only used by the HostingEngine?  i.e. 

M.A.Hosting.Engine:
- HostingEngine
- IHostingEngine
- IApplicationBuilderFactory
- IHttpContextFactory
- IStartupFilter
- IServerLoader

**Comment by davidfowl** [comment]
I would move things out of the Engine namespace that can be overridden by the application

**Comment by HaoK** [comment]
So maybe collapse everything into root Microsoft.AspNet.Hosting except for

IHostingEngine and IStartupLoader which live in Microsoft.AspNet.Hosting.Engine, and the ones you've already called out?

**Comment by davidfowl** [comment]
Yep

**Comment by HaoK** [comment]
Do we want to do this with the current rework PR or leave this for another PR?  Lou's taking a final look at the PR tomorrow, I can run this proposal by him and then move things around before pushing

**Comment by davidfowl** [comment]
It can be another PR, I mostly want to get consensus on the layering and name of those packages.
