### ISSUE TITLE
Revisit and improve/simplify Manifest/Import logic

### ISSUE THREAD

**Issue by HaoK** [aspnet/Hosting#180]
So far this has been a bit of a bug farm, need to revisit to see if we can improve the manifest/import logic

Issues so far:
- Easy to forget to add new services (Logger<>, IApplicationLifetime)
- Generic services don't work via delegate (so Logger<> doesn't actually chain)

cc @lodejard @davidfowl

**Comment by davidfowl** [comment]
Adding more problems:
- Flowing more services requires combining manifests

**Comment by davidfowl** [comment]
This is a huge wart we need to talk about.

/cc @glennc @muratg

**Comment by muratg** [comment]
@davidfowl adding this to the agenda of "tactical items" discussion.

**Comment by HaoK** [comment]
Summary of proposed changes:

- Introduce interface which can modify the app during hosting
```
public interface IStartupFilter
  void Configure(IApplicationBuilder app, Action<IApplicationBuilder> next)
```

- Call ConfigureServices early and resolve all hosting services other than IStartupLoader/IHostingEngine (which are not replaceable any longer, ini config swapping is CUT)

- Add new helper class
````
public class StartupMethods {
  Func<IServiceCollection, IServiceProvider> ConfigureServices { get; set; }
  Action<IpplicationBuilder> Configure { get; set; }
}
```

- Rename IServiceManifest to something obtuse (IRuntimeExportedSerivices??), stop using manifest hosting now that we will have auto request scope, and directly populate app DI container with the old hosting services (IHttpContextAccessor, IApplicationLifetime, IHostingEnvironment, etc.)

- Kill UseServices/UseRequestServices/RequestContainer

**Comment by HaoK** [comment]
Depends on https://github.com/aspnet/Hosting/issues/189
