### ISSUE TITLE
Need overload to CreateClient that takes a CookieContainer

### ISSUE THREAD

**Issue by ajaybhargavb** [aspnet/Hosting#191]
When using session(Eg. TempData in MVC) in TestHost the session cookie is not automatically forwarded to the next request. To overcome this we have to manually do 

``` C#
request.Headers.Add("Cookie", response.Headers.GetValues("Set-Cookie"));
```

Its easier if we can pass the `CookieContainer` or `ClientHandler` when creating the client.

cc @Praburaj

**Comment by davidfowl** [comment]
Why not just let you specify a message handler?

**Comment by ajaybhargavb** [comment]
Sure, that could also work.

**Comment by muratg** [comment]
@ajaybhargavb Closing this one as it seems you can use a workaround.  Reopen/file another one if you need something from Hosting layer.

**Comment by kichalla** [comment]
Came across the following post today: 
http://stackoverflow.com/questions/32750457/access-cookies-inside-unit-test-in-aspnet-testhost-testserver-context-on-asp-net

We do like `var setCookieArray = response.Headers.GetValues("Set-Cookie").ToArray();` in some places but not sure if this is the best approach...also using CookieContainer standalone where I can parse the incoming response's cookies seems to be not possible..

**Comment by Tratcher** [comment]
See https://github.com/aspnet/Mvc/blob/538cd9c19121f8d3171cbfddd5d842cbb756df3e/test/Microsoft.AspNet.Mvc.FunctionalTests/TempDataTest.cs#L201-L202

**Comment by deinok** [comment]
So, is there any way to configure the HttpClient generated by testServer.CreateClient() ?

**Comment by Tratcher** [comment]
@deinok what are you trying to configure? Test server [creates](https://github.com/aspnet/Hosting/blob/dev/src/Microsoft.AspNetCore.TestHost/TestServer.cs#L42-L51) a [ClientHandler](https://github.com/aspnet/Hosting/blob/dev/src/Microsoft.AspNetCore.TestHost/ClientHandler.cs) which doesn't have any configuration to speak of.

**Comment by deinok** [comment]
@Tratcher I want to setup the CookieStore for the HttpClient. I need it to make tests on my WebApp

**Comment by Tratcher** [comment]
ClientHandler doesn't manage cookies at all. You can set them directly on the requests.
https://github.com/aspnet/Security/blob/22d2fe99c6fd9806b36025399a217a3a8b4e50f4/test/Microsoft.Owin.Security.Interop.Test/CookieInteropTests.cs#L76-L79

**Comment by deinok** [comment]
@Tratcher So why don't we are able to set a CookieStore or let configure the handlers. This way we can avoid all this boilerplate. Correct me if im wrong with this approach

**Comment by Tratcher** [comment]
TestServer is built as unit test infrastructure designed for maximum control over each action. It does not have any automatic behavior across actions (e.g. redirects, cookies, auth, etc.). We could add more built in functionality here to reduce the boiler plate code, but it would be disabled by default. E.g.:
* `TestServer.EnableAutomaticRedirects { get; set; } = false;`
* `TestServer.EnableCookieManagement { get; set; } = false;`

**Comment by deinok** [comment]
@Tratcher Yes, this would be perfect. Thanks you. If help is needed, I can give help

**Comment by deinok** [comment]
@Tratcher Any update on this?

**Comment by Tratcher** [comment]
No, it hasn't even been triaged or assigned yet. It won't be any time soon.

**Comment by unjello** [comment]
@Tratcher Will you accept the changes if I make a PR? Or is there other reason beside it being of low priority that makes it lay unassigned? :)

**Comment by Tratcher** [comment]
Yes we would consider a PR. I recommend you summarize your approach before sending a PR though.

**Comment by Tratcher** [comment]
Here's an interesting variant on this idea:
https://github.com/aspnet/Hosting/issues/312#issuecomment-278665288

**Comment by Matthew-Bonner** [comment]
It shouldn't be up to Brock to provide this functionality, he might have broad shoulders but the weight of this shouldn't be on his shoulders. Has this been triaged yet as it is now 2018?

**Comment by davidfowl** [comment]
@Matthew-Bonner because there is a viable workaround and we're working on various other things that are higher priority than this. If you have an API proposal and you'd like to contribute, it would be great for you to send a pull request to add this functionality.

**Comment by Matthew-Bonner** [comment]
Thanks for responding so quick @davidfowl, if I was to take something similar to what Brock has provided does it stand a chance of being accepted or are there any concerns with Brock's implementation. I should add that I've not tested it yet and will probably pull it apart and give it a good test anyway, just after some early feedback.

**Comment by Eilon** [comment]
The new testing stuff that @javiercn is working on I believe has exactly this functionality via a message handler. @javiercn can you share some pointers/thoughts?

**Comment by javiercn** [comment]
These scenarios will be supported as part of the testing improvements we are doing for MVC. You'll have a way to get a client that does Cookies and handles redirects automatically for you. See the original announcement (a bit outdated)
https://github.com/aspnet/Announcements/issues/275

We will be updating it later this year to include further improvements which we've managed to squeeze into our next release. (Among those improvements, cookies and redirect handling).

**Comment by Eilon** [comment]
Yes

**Comment by muratg** [comment]
Closing. (Again, after 2 years and 9 days. :smiley_cat: )
