### ISSUE TITLE
Add extension method MapPath to HostingEnvironment

### ISSUE THREAD

**Issue by Praburaj** [aspnet/Hosting#195]
Add extension method: `MapPath`

Moving a part of https://github.com/aspnet/Hosting/issues/157 into a separate item.

**Comment by tyson-benson** [comment]
Hi @Praburaj Can I ask what kind of timeframe we've got for this extension? I got stuck on this when attempting to port an existing project to ASP.NET 5

**Comment by davidfowl** [comment]
It's literally an extension method that does Path.Combine :smile:

**Comment by tyson-benson** [comment]
That gave me a good chuckle, i figured it would be more complicated. Would it go something like this?
```
public static string MapPath(this IHostingEnvironment env, string relativePath)
{
    return System.IO.Path.Combine(env.WebRoot, relativePath);
}
```

**Comment by Praburaj** [comment]
@tyson-benson @davidfowl I sent out a PR. I'll add some tests before checkin.
