### ISSUE TITLE
Consider making IHostingEnvironment.EnvironmentName read only

### ISSUE THREAD

**Issue by HaoK** [aspnet/Hosting#198]
We added the set for IConfigureHostingEnvironment, now that that is nuked with the hosting changes, we could make it { get } only again.  But MvcTagHelpers has a test that is using the set today

cc @davidfowl

**Comment by HaoK** [comment]
@lodejard says all of these MUST be get/set...

**Comment by davidfowl** [comment]
Crazy

**Comment by HaoK** [comment]
Yeah, I added "do not make these read only" comments to IHostingEnvironment in my PR since he doesn't want people to keep changing these during API reviews :)
