### ISSUE TITLE
Remove CallContextServiceLocator where possible

### ISSUE THREAD

**Issue by davidfowl** [aspnet/Hosting#199]
It makes assumptions about the hosting environment, and statics are bad.

**Comment by HaoK** [comment]
https://github.com/aspnet/EntityFramework/issues/2024

**Comment by HaoK** [comment]
Looks like all product references have been removed except for Test related code, and the associated EF migration tool issue:

Hosting also has two but they live in test helper code:

Hosting\src\Microsoft.AspNet.Server.Testing\Deployers\IISExpressDeployer.cs:134:            
```
var libraryManager = (ILibraryManager)CallContextServiceLocator.Locator.ServiceProvider.GetService(typeof(ILibraryManager));
```
Hosting\src\Microsoft.AspNet.TestHost\TestServer.cs:81:                
```
services ?? CallContextServiceLocator.Locator.ServiceProvider,
```

All the rest of the CallContext usage is only in tests, so looks like we are good for now...
