### ISSUE TITLE
HttpConfiguration MessageHandlers Moved

### ISSUE THREAD

**Issue by jskulavik** [aspnet/Hosting#209]
In the consolidation of MVC and WebApi the HttpConfiguration object was moved *somewhere*.  Can we document where it went, and also provide guidance as to where to add MessageHandlers to the pipeline as was done pre-ASPNET 5 via ```HttpConfiguration.MessageHandlers.Add()```?

**Comment by danroth27** [comment]
@jskulavik The Web API model was changed pretty substantially as part of merging MVC and Web API together. Configuration is now handled through `MvcOptions` using the new ASP.NET 5 options model (see https://github.com/aspnet/Mvc/blob/dev/test/WebSites/FormatterWebSite/Startup.cs for an example). Also message handlers are not used at all - instead you write ASP.NET 5 middleware.

If you prefer to work with something closer to the ASP.NET Web API model we did build a Web API compat on top of MVC 6 that you can try out (see https://github.com/aspnet/Mvc/tree/dev/test/WebSites/WebApiCompatShimWebSite). 

You can find our current docs at http://asp.net/vnext. The docs are pretty light right now, but you can expect more content to become available as we get closer to releasing.

**Comment by jskulavik** [comment]
Thanks @danroth27!  Are you guys planning on documenting and providing examples for writing middleware?  If you point me in the direction of the ASP.NET 5 middleware components, I'll fork and publish what I write.

**Comment by danroth27** [comment]
@jskulavik I think the best middleware samples we have right now are in the sketchy but useful Entropy repo. Check out https://github.com/aspnet/Entropy/blob/dev/samples/Builder.Middleware.Web/Startup.cs.
