### ISSUE TITLE
Simplify ServerLoader logic

### ISSUE THREAD

**Issue by HaoK** [aspnet/Hosting#214]
Per @lodejard the logic should be simplified to:
- serverFactoryIdentifier should be treated only as the assembly name and directly used via Assembly.Load, the assembly will be scanned for a IServerFactory (no more split of name, and no more support for the serverFactoryIdentifier being a type)

**Comment by davidfowl** [comment]
Nice

**Comment by Tratcher** [comment]
@HaoK Did this get done? If not please move it to beta6.

**Comment by HaoK** [comment]
Not yet I will take a look today/next week

**Comment by HaoK** [comment]
bf6e293bfedcb921215f8c4273839912be205719
