### ISSUE TITLE
Provide .NET 4.5 framework support

### ISSUE THREAD

**Issue by tugberkugurlu** [aspnet/Hosting#215]
Is it possible to provide builds of hosting libraries for .NET 4.5? I tried to see if it was as simple as adding .NET 4.5 but even the Microsoft.AspNet.Hosting.Interfaces project is failing to build.

If it matters, I am actually trying to in-memory host an MVC project through `TestServer` in a good old console application.

**Comment by davidfowl** [comment]
Why not use an ASP.NET 5 console app?

**Comment by tugberkugurlu** [comment]
For a bit weird reason. I want to in-memory host the MVC project just render and get out the html from it and use it in a pure .NET application.

Also, in my other case, I want to be able to host the app as a Windows Service.

**Comment by davidfowl** [comment]
@tugberkugurlu see https://github.com/aspnet/Hosting/issues/291#issuecomment-150558413

**Comment by tugberkugurlu** [comment]
This is great, thx!
