### ISSUE TITLE
Deploying a simple MVC app to IIS (32 bit app) fails

### ISSUE THREAD

**Issue by kirthik** [aspnet/Hosting#220]
Create an app using `ASP.NET 5 Preview Empty` template
Add MVC service in 'startup.cs'
Add `HomeController.cs` and `Index.cshtml`
Add some text in `Index.cshtml`
Create a package using `dnu publish`. Include `x86` version of runtime in the packages
Create a site in IIS and point it to the above package. Set `Enable 32-bit Applications` to `true`
Run the app. Expected to work but shows `NullReferenceException`
Same app works fine its packed with `x64` runtime and `Enable 32-bit application` is left with default value(`false`)
Runtime version I am using : `1.0.0-beta4-11431`

![image](https://cloud.githubusercontent.com/assets/1267650/6930294/b6e326c0-d7b6-11e4-9fa1-f036a3fd8508.png)
![image](https://cloud.githubusercontent.com/assets/1267650/6930302/c8dac522-d7b6-11e4-8eb3-e4d011d9413c.png)

**Comment by Praburaj** [comment]
This is due to an issue with Dataprotection stack. This was fixed with : https://github.com/aspnet/DataProtection/commit/56cfbdde82b3ed3034799c64f0259b3e755477e6
