### ISSUE TITLE
Microsoft.AspNet.Server.WebListener HTTP 400 from remote client

### ISSUE THREAD

**Issue by jskulavik** [aspnet/Hosting#230]
When starting an app using a command to invoke **Microsoft.AspNet.Server.WebListener** on a port of your choice (5102 in my case) the app starts as expected and can be invoked with http://localhost:5102/[attribute-route].  However, attempting to access the app from a remote machine (e.g. not localhost, but http://[DNSorIP]:5102/[attribute-route]) the response is consistently HTTP 400.  It *seems* like http.sys is not handling requests.

**Environment**
* Server: Any Windows OS, all firewalls turned off
* Client:  curl, any browser, any http client to http://[DNSorIP]:5102/[attribute-route]
* App: One controller using attribute routing

**project.json**

```JSON
"dependencies": {
        "Microsoft.AspNet.Server.IIS": "1.0.0-beta3",
        "Microsoft.AspNet.Mvc": "6.0.0-beta3",
        "Microsoft.AspNet.StaticFiles": "1.0.0-beta3",
        "Microsoft.AspNet.Server.WebListener": "1.0.0-beta3",
        "Microsoft.Net.Http": "2.2.29"
    },
    "frameworks": {
        "aspnet50": { }
    },
    "commands": {
        "winhost": "Microsoft.AspNet.Hosting --server Microsoft.AspNet.Server.WebListener --server.urls http://localhost:5102",
        "kestrel": "Microsoft.AspNet.Hosting --server Kestrel --server.urls http://localhost:5104"
    }
```

**Comment by davidfowl** [comment]
You can't use "localhost" as the url if you want [dnsorip] to bind. You need to use + or *.

```
        "winhost": "Microsoft.AspNet.Hosting --server Microsoft.AspNet.Server.WebListener --server.urls http://+:5102",

```

This article might help http://www.codeproject.com/Articles/437733/Demystify-http-sys-with-HttpSysManager

/cc @Tratcher
