### ISSUE TITLE
No wwwroot after clone causes VS error

### ISSUE THREAD

**Issue by danroth27** [aspnet/Hosting#233]
From @bartmax (see aspnet/mvc#2352):

Since wwwroot is not added to source control, when someone clone a project and tries to run it an error of webroot pointing to a folder which doesn't exist.

More info here: http://stackoverflow.com/questions/29437784/mvc-6-api-error-webroot-points-to-a-file-that-does-not-exist.

I think kpm restore should create this folder if it does not exist

**Comment by davidfowl** [comment]
> I think kpm restore should create this folder if it does not exist

No way, we should just not explode if the folder doesn't exist.

**Comment by Bartmax** [comment]
why not create it? npm tasks will fail on CI servers, or am I missing something?

**Comment by davidfowl** [comment]
Mixing distinct layers. The package manager shouldn't be assuming anything about the wwwroot on restore. The publish step can certainly do it since thats all about producing deployable bits, but the sdk command shouldn't really be looking at the wwwroot and making decisions.

**Comment by Bartmax** [comment]
Copy :+1:

**Comment by Tratcher** [comment]
This issue manifests in several different ways.
A) In VS you get an error trying to run with IIS Express: `The 'webroot' property value 'wwwroot' in the project.json file points to a folder which doesn't exist.`. In this case I think VS could try to create the directory.
B) `dnx . web` throws a `System.IO.DirectoryNotFoundException`. See #278. Hosting could create the directory in this case.
C) Publish?
D) Others?

**Comment by Tratcher** [comment]
A tooling bug has been filed for Scenario A. Scenario B is fixed by #293. I think we can call this done unless you find other scenarios.
