### ISSUE TITLE
Inconsistent usage of delegate types

### ISSUE THREAD

**Issue by davidfowl** [aspnet/Hosting#234]
Some examples:

- https://github.com/aspnet/Hosting/blob/dev/src/Microsoft.AspNet.Hosting/Startup/StartupMethods.cs#L10
- https://github.com/aspnet/HttpAbstractions/blob/dev/src/Microsoft.AspNet.Http/RequestDelegate.cs
- https://github.com/aspnet/Hosting/blob/dev/src/Microsoft.AspNet.Hosting.Server.Interfaces/IServerFactory.cs#L15
- https://github.com/aspnet/HttpAbstractions/blob/dev/src/Microsoft.AspNet.Http/IApplicationBuilder.cs#L17

Our public interfaces should be consistent (or have a good reason not to be).

**Comment by HaoK** [comment]
So I take it this means we want to add delegates for everything?

```
public delegate Task ServerDelegate(IFeatureCollection features);
public delegate void ApplicationDelegate(IApplicationBuilder app);
public delegate RequestDelegate MiddlewareDelegate(RequestDelegate next);
```

**Comment by lodejard** [comment]
Not sure if this is worth the effort. The `RequestDelegate` type was only declared because it appears as a middleware constructor parameter in end-user code. I don't think any of the func or action these delegates represent appear in end-user code, so no reason to give them a named delegate type.

**Comment by HaoK** [comment]
Only RequestDelegate remains doesn't sound like there's any interest in creating more delegates, closing this issue
