### ISSUE TITLE
Need ability to host on custom servers in Microsoft.AspNet.Server.Testing package

### ISSUE THREAD

**Issue by Praburaj** [aspnet/Hosting#241]
Right now only these options are possible.  https://github.com/aspnet/Hosting/blob/dev/src/Microsoft.AspNet.Server.Testing/Common/ServerType.cs#L8

@Tratcher

**Comment by Tratcher** [comment]
See https://github.com/aspnet/Hosting/blob/dev/src/Microsoft.AspNet.Server.Testing/Deployers/ApplicationDeployerFactory.cs#L37

We need to change that from an enum and static switch statement to a dictionary lookup where you can register alternates by name.

**Comment by davidfowl** [comment]
@Tratcher  Yes please
