### ISSUE TITLE
Need ability to run a specific command while using deployers in Microsoft.AspNet.Server.Testing package

### ISSUE THREAD

**Issue by Praburaj** [aspnet/Hosting#242]
Currently only web and kestrel are possible. 

@Tratcher

**Comment by Tratcher** [comment]
See https://github.com/aspnet/Hosting/blob/dev/src/Microsoft.AspNet.Server.Testing/Deployers/SelfHostDeployer.cs#L50
And
https://github.com/aspnet/Hosting/blob/dev/src/Microsoft.AspNet.Server.Testing/Deployers/MonoDeployer.cs#L71
