### ISSUE TITLE
The parameters of the configure services delegate are not injected

### ISSUE THREAD

**Issue by Tragetaschen** [aspnet/Hosting#252]
All parameters [but `IServiceCollection`](https://github.com/aspnet/Hosting/blob/dev/src/Microsoft.AspNet.Hosting/Startup/ConfigureServicesDelegate.cs#L33) are `null`

**Comment by davidfowl** [comment]
That's by design. We don't want to resolve anything from the service collection until it is built.

**Comment by Tragetaschen** [comment]
But constructor arguments for `Startup` are injected already (which is my workaround now).

If this is the case, then there should be a better error message.

**Comment by davidfowl** [comment]
+1 on the error message. This just hit me in omnisharp.

**Comment by HaoK** [comment]
Yeah seems like we can just always throw if the ConfigureServices isn't returning void or IServiceProvider, and its taking anything other than a single IServiceCollection parameter or no parameters...

**Comment by Tragetaschen** [comment]
I'm not so convinced that only taking `IServiceCollection` as a parameter is the right thing, though. When I'm implementing `Configure` I can get dependencies like `IHostingEnvironment` or `ILoggerFactory` (see the default templates in VS), but that's not possible for `ConfigureServices`. This seems odd.

**Comment by davidfowl** [comment]
@Tragetaschen ConfigureServices is setting up your dependencies. It's the last ditch effort to provide any more dependencies before the container is built. Configure runs after the container has been built and has access to everything.

**Comment by Tragetaschen** [comment]
I'm well aware, but try to look at how a startup class works: I can get dependencies in the constructor (that's the first opportunity) and I can get dependencies in `Configure` (that's the last opportunity), but I cannot get any in `Configure*Services`. That's why I think it's odd.

**Comment by HaoK** [comment]
We actually removed this functionally as a simplification/cleanup to avoid passing the host service provider to the startup loader in the last hosting iteration I think. 

A workaround would be to just grab the dependencies in the startup ctor and store them for later use in configure services. A further subtlety is that the startup dependencies are actually from a different (hosting) container than the configure dependencies (application) container.

**Comment by HaoK** [comment]
5b851c49a337e49001ed2351253ab0f52b696040
