### ISSUE TITLE
Startup.Configure does not require IApplicationBuilder

### ISSUE THREAD

**Issue by Tratcher** [aspnet/Hosting#257]
https://github.com/aspnet/Hosting/blob/dev/src/Microsoft.AspNet.Hosting/Startup/ConfigureDelegate.cs#L36
The parameter order for Configure is flexible, allowing IApplicationBuilder to be mixed with DI dependencies.  However the code does not verify that IApplicationBuilder was used at least once.

This works:
```
    public void Configure()
    {
    }
```

Recommendation: Throw if IApplicationBuilder does not match at least one parameter.

**Comment by Matthew-Bonner** [comment]
Is there a compelling reason to force the use of IApplicationBuilder?

**Comment by Tratcher** [comment]
Well, you can't set up a web-app without it, so....

**Comment by Matthew-Bonner** [comment]
I wouldn't consider that a compelling reason as it causes more problems than it solves, especially in terms of unit testing.

**Comment by Tratcher** [comment]
What are you going to do without it?

**Comment by Matthew-Bonner** [comment]
Unit test?

**Comment by Tratcher** [comment]
Any examples? I can't picture a case where Startup.Configure would even be involved in unit tests. Functional/integration tests maybe, but then I would still expect you to be using IApplicationBuilder to set up the request pipeline.  Configure serves no other purpose.

**Comment by HaoK** [comment]
So one scenario that this currently allows is an empty request pipeline, and using hosting to just run ConfigureServices to setup ApplicationServices correctly.  I think that is a worthwhile scenario to use hosting in this manner (EF's Migration tool currently does this for example, it only wants to ConfigureServices and create the appropriate DbContext).

**Comment by Tratcher** [comment]
Sounds like you need to make Hosting's services more directly accessible...

**Comment by HaoK** [comment]
Well we had a few iterations like that, and the reason we went away from that is to get away from exposing the manifest/import multiple container nightmare to the world... So now if you want to build a real IServiceProvider, you always call something like this:

```
new WebHostBuilder(runtimeServices, config)
    .UseServices(services => { })
    .Build().ApplicationServices
```

vs the old error prone manually mucking around with service collections:

**Comment by HaoK** [comment]
But my main point was, the usage above doesn't require use of IApplicationBuilder or any request pipeline...

**Comment by Tratcher** [comment]
We don't need to add anything until we find users actually encountering this issue.
