### ISSUE TITLE
Should DataDirectory be set to App_Data?

### ISSUE THREAD

**Issue by bricelam** [aspnet/Hosting#262]
This affects where connection strings like `"Data Source=|DataDirectory|\MyDatabase.sdf"` look for files. Without it, paths will be relative to `AppDomain.CurrentDomain.BaseDirectory` which, per aspnet/dnx#1253, is set to the runtime directory.

**Comment by muratg** [comment]
https://github.com/aspnet/dnx/issues/1507

**Comment by davidfowl** [comment]
This should be set in hosting

**Comment by davidfowl** [comment]
Murat that's another bug

**Comment by bricelam** [comment]
Note, on Desktop .NET, this was done by setting an application domain property:
```C#
domain.SetData("DataDirectory", Path.Combine(appRoot, "App_Data"));
```
I'm not sure what SQL Client will do on .NET Core.

**Comment by davidfowl** [comment]
We need to investigate (that was gonna be my next question). Does that entire concept still exist on CoreCLR?

**Comment by bricelam** [comment]
It looks like they've just removed the feature on .NET Core:

    System.ArgumentException: Invalid value for key 'attachdbfilename'.
       at System.Data.SqlClient.SqlConnectionString..ctor(String connectionString)
       at System.Data.SqlClient.SqlConnectionFactory.CreateConnectionOptions(String connectionString, DbConnectionOptions previous)
       at System.Data.ProviderBase.DbConnectionFactory.GetConnectionPoolGroup(DbConnectionPoolKey key, DbConnectionPoolGroupOptions poolOptions, DbConnectionOptions& userConnectionOptions)
       at System.Data.SqlClient.SqlConnection.ConnectionString_Set(DbConnectionPoolKey key)
       at System.Data.SqlClient.SqlConnection.set_ConnectionString(String value)
       at System.Data.SqlClient.SqlConnection..ctor(String connectionString)

**Comment by davidfowl** [comment]
@bricelam I'm going to close this out.

**Comment by Shazwazza** [comment]
Is there an equivalent of what used to be IApplicationEnvironment.GetData("DataDirectory") from RC1 in the RC2 release? Sorry to ask here but have searched around everywhere and can't come up with much

**Comment by bluemmc** [comment]
@Shazwazza Have the same question - did you find out what happened to IApplicationEnvironment.GetData ?

**Comment by davidfowl** [comment]
Are you using .NET Framework or .NET Core?

**Comment by Shazwazza** [comment]
@bluemmc nope didn't end up getting anywhere with that - but haven't looked at this for quite a while.

My application is using .Net Core targeting netcoreapp1.0 and .Net 4.5.2

**Comment by bluemmc** [comment]
@davidfowl  Thanks for looking at this. I am using .NET framework (dot net core MVC but targeting net452 framework). Currently I am considering creating my own IMyApEnv and injecting it in my classes to pass the data around that I used  IApplicationEnvironment.GetData/SetData for in RC1.

P.S. Migrating a non-trivial RC1 app to RTM is a huge task. I am quite surprised by the huge amount of breaking api changes (considering I was using a release candidate). Many of which completely undocumented. In this case google yields NO available information.

**Comment by davidfowl** [comment]
Yes RC1 to RC2 was a pretty massive change. We tried our best to document all of the changes but some slipped through the cracks. 

Regarding this issue, "DataDirectory" isn't a thing on .NET Core and we don't set one for .NET Framework. As for GetData/SetData, there's replacements in .NET Core (AppContext.GetData) and on .NET Framework you can use AppDomain.SetData/GetData
