### ISSUE TITLE
Hosting:Application environment variable issue

### ISSUE THREAD

**Issue by sujitdmello** [aspnet/Hosting#265]
Really like the facility of providing a global Startup component for all apps via the Hosting:Application environment variable. This allows enterprise customers to put common Configure and ConfigureServices logic into one place and enforce it for every app. The one problem is that if you have this configured, the apps don’t get their own Configure or ConfigureServices methods called, so if apps want to add their own services (e.g. Repository), they can’t do that. 
 
I’ve worked around the problem by loading the application’s assembly from the global startup component and invoking Startup.ConfigureServices within the application code … sort of like daisy-chaining the call to the applications ConfigureServices. But I am hitting a problem with DI. Although the application ConfigureServices method calls services.AddSingleton<IRep, RepositoryImpl(), it does not resolve the type within the controller constructor as expected. I get the exception ‘Unable to resolve service for type IRep’. It used to work in Beta3 but this same logic is not working now (in Beta5). Was wondering if this is a design change or did I mess something? 
 
If I remove the Hosting:Application setting everything works as expected within the application itself.

**Comment by HaoK** [comment]
ConfigureServices now runs earlier, as the first thing the hosting engine does when it starts up.  In Beta 3, this would run much later.  Are there any dependencies in your RepositoryImpl ctor that might be missing when run this early?

**Comment by Tratcher** [comment]
How are you doing your chaining?
Hosting -> Global Startup -> Global Configure Services -> App Specific Configure Services
Hosting -> Global Startup -> Global Configure -> App Specific Configure
Or
Hosting -> Global Startup -> Global Configure Services
Hosting -> Global Startup -> Global Configure -> App Specific Configure Services, App Specific Configure

The second example won't work, you'd need to do it like the first example.

**Comment by sujitdmello** [comment]
I think it's Hosting -> Global Startup -> Global Configure Services -> App Specific Configure Services

Everything works (all the other services are working fine). It's just the Repository which it is not finding. And I dumped all service descriptors to verify that it was in the list after it was added by the application code. It's a simple in-memory repository that uses a Dictionary so hopefully no dependencies there.

**Comment by sujitdmello** [comment]
This may be a problem with the way I am loading the application assembly and executing the *ConfigureServices* method. If I directly add a reference from the global configuration component to the application component and call *ConfigureServices* that way - it works fine. Unfortunately this is not a viable solution because the global component is meant to work with any application. However if I use reflection to load and execute *ConfigureServices*, the method is called with the correct parameters but the dependency injection for the application repository does not work. This worked in Beta3 so trying to figure out how to make it working now in Beta5.

Thanks

**Comment by sujitdmello** [comment]
So the problem was on my end - I was using some convoluted Assembly loading technique to load and run the *ConfigureServices* and *Configure* methods in the application code which was causing the problem. Turns out there is a much easier way to do this now in Beta5. Here is a snippet from my Global Configuration component (activated by setting the *Hosting:Application=GlobalConfigurationComponentAssemblyName* environment variable).

```
public class Startup
    {
        string appName;
        string envName;
        IHostingEnvironment host;
        IServiceProvider serviceProvider;
        public Startup(IApplicationEnvironment env, IHostingEnvironment hostEnv, IServiceProvider sp)
        {
            appName = env.ApplicationName;
            envName = hostEnv.EnvironmentName;
            serviceProvider = sp;
            host = hostEnv;
        }

        public void ConfigureServices(IServiceCollection services)
        {
            Console.WriteLine("GlobalStartup.ConfigureServices");
            services.AddMvc();
            List<string> diagnosticMessages = new List<string>();
            StartupLoader sl = new StartupLoader(serviceProvider, host);
            Type t = sl.FindStartupType(appName, diagnosticMessages);
            StartupMethods startupMethods = sl.LoadMethods(t, diagnosticMessages);            
            if (startupMethods.ConfigureServicesDelegate != null)
            {
                startupMethods.ConfigureServicesDelegate.Invoke(services);
            }
            diagnosticMessages.ForEach(msg => Console.WriteLine(msg));
            Console.WriteLine("Application startup called.");
        }        
        public void Configure(IApplicationBuilder app)
        {
            Console.WriteLine("GlobalStartup.Configure");
        }
    }
