### ISSUE TITLE
Change Microsoft.AspNet.Hosting.ini to Microsoft.AspNet.Hosting.json

### ISSUE THREAD

**Issue by Matthew-Bonner** [aspnet/Hosting#269]
This might already be planned but I'm raising it here as there are many references to Microsoft.AspNet.Hosting.ini in examples on websites giving an insight into ASP.NET 5, which is likely to cause confusion if the file is changed from an ini to a json file, so if we are going to use json files it would be better if we switched sooner rather than later.

**Comment by Matthew-Bonner** [comment]
Pull request: #270

**Comment by Michael-DST** [comment]
It does cause confusion and does not reflect well on the project structure or overall design.  A provider model to load the configuration would be ideal.  This would/should default to .json, but would enable .xml/.ini/.xaml/.yaml/.etc if desired.  Related issue: https://github.com/aspnet/Tooling/issues/140

**Comment by Michael-DST** [comment]
Horray... very cool.  Some sanity restored. :)  Are there plans to make this more consistent with the rest of ASP.NET's configuration model and allow providers to dictate the configuration format?

**Comment by Tratcher** [comment]
Not at the moment. You can open a separate issue.

**Comment by Michael-DST** [comment]
Cool.  Done.  Thank you!

**Comment by davidfowl** [comment]
That would require a plugin model for config format since hosting won't depend on every format possible

**Comment by davidfowl** [comment]
I think if you wanted that you'd be better off constructing the host in your own program main

**Comment by Michael-DST** [comment]
Exactly.  The plugin model is already in use elsewhere and can be used here as well.  It obviously already has two different formats that users favor, so why not open it up to all formats if it's the same amount of work to do?

**Comment by Michael-DST** [comment]
There is also the issue of providing proper guidance here in case someone else gets a crazy idea somewhere down the line to also use .ini or (god forbid) .xml :)
