### ISSUE TITLE
Security: if (env.IsEnvironment("Development")) is true on Azure

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Hosting#272]
Using VS2015 RC.
Create a new MVC 6 app and deploy to Azure. The debugger shows that the following code in the Configure method in startup.cs returns true on Azure

```c#
 if (env.IsEnvironment("Development"))
            {
                app.UseBrowserLink();
                app.UseErrorPage(ErrorPageOptions.ShowAll);
            }
```

So on Azure you could leak information through the call stack and detailed errors. I used KUDU to verify ("Development") is not an environment variable.

**Comment by Eilon** [comment]
The env var is called `ASPNET_ENV` or something, and its *value* is the environment name. Not that this necessarily explains what you're seeing...

**Comment by davidfowl** [comment]
It does, we don't default to Production yet...

**Comment by Eilon** [comment]
Oh... we want to change the default in Antares or something? I vaguely recall discussing this like 12 months ago...

**Comment by davidfowl** [comment]
Ahh yes I dont think we ever did that.

**Comment by blowdart** [comment]
Yes. You all promised that release would be the default a year ago. Changing the default in Antares isn't enough. Change the default *everywhere* as was agreed.

**Comment by Eilon** [comment]
So default is Release (or Production or whatever) and VS sets its F5/Run setting to Development? That sounds familiar too.

**Comment by blowdart** [comment]
That was what we agreed to, but still isn't implemented.

**Comment by Eilon** [comment]
@blowdart can you log a bug in Tooling-Internal for VS and another bug in DNX for the runtime?

**Comment by Eilon** [comment]
Or sorry, no bug in DNX. Just Hosting. Which is this bug. So just one bug :smile:

**Comment by Eilon** [comment]
One *new* bug, that is :smile:

**Comment by blowdart** [comment]
Yes, it's been in DNX for a while - https://github.com/aspnet/dnx/issues/777

**Comment by Eilon** [comment]
I think this is a Hosting-specific thing though, isn't it? Maybe back then it was DNX-wide but I'm not sure that's the case anymore... is it?

**Comment by glennc** [comment]
We had not done this yet because we were waiting on tooling to set the variable to development, so that we didn't change everyone to prod on their dev machine overnight. Not sure if that work has been done or not yet.

**Comment by blowdart** [comment]
There was no issue logged with tooling, so there doesn't appear to have been any tracking of this. There is now an issue.

**Comment by glennc** [comment]
Ok, tracked this down a bit more. VS sets it to dev when running IISExpress.

**Comment by muratg** [comment]
This is hosting specific.  Assigning to @Tratcher
