### ISSUE TITLE
Hosting should take in hosting file name as an argument

### ISSUE THREAD

**Issue by rustd** [aspnet/Hosting#276]
This would allow us to do the following.
```C#
    "web": "Microsoft.AspNet.Hosting --config hosting.ini",
```
The code that needs to be changed is https://github.com/aspnet/Hosting/blob/5b851c49a337e49001ed2351253ab0f52b696040/src/Microsoft.AspNet.Hosting/Program.cs

As a stretch it would be awesome if the hosting could read a json file so we could have hosting.json

**Comment by rustd** [comment]
@muratg @Eilon This is for Beta5 from the templates review

**Comment by muratg** [comment]
https://github.com/aspnet/Hosting/issues/277

**Comment by davidfowl** [comment]
@lodejard

**Comment by muratg** [comment]
@rustd Template change for the web command should be unblocked now.
