### ISSUE TITLE
Decouple service discovery from Hosting

### ISSUE THREAD

**Issue by bricelam** [aspnet/Hosting#286]
As mentioned in aspnet/EntityFramework#2136 and aspnet/EntityFramework#2020, we should try to decouple the discovery of services using `Startup.ConfigureServices()` from the rest of Hosting. Maybe it should be part of DependencyInjection.

Service discovery is used by the EF Migrations tooling to get the IServiceProvider to pass into the DbContext at design-time. Clearly, this doesn't require setting up the request pipeline or any of the other things handled by Hosting.

@HaoK did make a good point...

> I'm not sure we can, since Startup potentially can take things like IHostingEnvironment in its ctor which only come from hosting.

...but to me, that feels like we have too much coupling between the components involved in startup.

**Comment by Tratcher** [comment]
One of Hosting's primary jobs is to find Startup and execute it. I don't think you can meaningfully decouple that. The EF Migrations service discovery you're referring to is Asp.Net specific, correct? Startup is the Asp.Net entry point (via Hosting) so the current setup seems appropriate. DI is not Asp.Net specific so I don't think you could move this there.

That said, if there were a way to have Hosting execute just ConfigureServices and not Configure that may help, but I know this has been tried and rejected several times already.

**Comment by HaoK** [comment]
> That said, if there were a way to have Hosting execute just ConfigureServices and not Configure that may help, but I know this has been tried and rejected several times already.

This actually possible already. Simply access ApplicationServices off of the hosting engine without calling start(). That will trigger only configure services without invoking configure.

**Comment by bricelam** [comment]
Should ConfigureServices be moved outside of Startup?

Another options is to create a non-ASP.NET (but DNX) specific entry point to configure services at design-time. To keep things DRY users could make their Startup.ConfigureServices call into this entry point...

**Comment by Tratcher** [comment]
The only DNX app entry point is Program.Main.  It sounds like you're recommending Program.ConifigureServices. Though as Hao pointed out, DNX doesn't have access to Hosting's services needed for an Asp.Net application.

**Comment by muratg** [comment]
Interesting https://twitter.com/RickStrahl/status/604197208674574336 

cc @davidfowl

**Comment by bricelam** [comment]
We could also go back to the EF6 approach of `IDbContextFactory` where the user is responsible for writing code to bridge the gaps between runtime and design-time.

**Comment by Tratcher** [comment]
And/or provide the bridge for Asp.Net as a separate package.

**Comment by divega** [comment]
Yes, it would help to just move the ability to find and execute `Startup.ConfigureServices()` to some kind of utility package that can be used by both Hosting and design time tooling such as the EF commands, so that the EF commands don't need to depend on the whole Hosting. It doesn't need to move to DNX. 

That said, I do see as something good to have the ability to create DNX applications that are not ASP.NET applications and use similar patterns to `Startup.ConfigureServices()` to initialize the DI container.

**Comment by Tratcher** [comment]
Or split EF.Commands so that only the Asp.Net specific commands depend on Hosting.
