### ISSUE TITLE
Simplify RequestContainerMiddleware

### ISSUE THREAD

**Issue by davidfowl** [aspnet/Hosting#288]
I think we should inline some of RequestServicesContainer.EnsureRequestServices

**Comment by muratg** [comment]
@Tratcher

**Comment by HaoK** [comment]
Yep I don't think we actually need it anymore, we used to call it directly via auth/routing middlewares.  I think we can just nuke it and put all the code back inside of RequestContainerMiddleware's Invoke

**Comment by HaoK** [comment]
ee8baab1ed725cbce97e8daccd5ee7dbacad51b5
