### ISSUE TITLE
Hosting:Application environment variable does not work when hosted in IIS

### ISSUE THREAD

**Issue by sujitdmello** [aspnet/Hosting#289]
Tried *setx Hosting:Application CustomStartup*, then *iisreset* but it does not invoke the custom startup class. Running from command-line with *dnx . web* works as expected.

How do we configure apps in IIS to use the custom Startup assembly?

**Comment by muratg** [comment]
@Tratcher

**Comment by Tratcher** [comment]
Is this related to https://github.com/aspnet/Home/issues/645? Or does it not even work with a project.json reference?

**Comment by sujitdmello** [comment]
It does not work even with the project.json reference. Running the published web.cmd helper file works but not when run via AspNetLoader as an IIS app. The app works fine, it just does not attempt to load the global startup assembly.

**Comment by muratg** [comment]
@sujitdmello What does your project.json look like?  Are you using Beta 4 or dev bits (Beta 5)?

**Comment by sujitdmello** [comment]
Using dev bits. Below is the published *project.json* file. 

```
{
  "webroot": "../../../../../wwwroot",
  "version": "1.0.0-*",
  "dependencies": {
    "ContactsApi": "1.0.0",
    "GlobalStartup" : "1.0.0"
  },
  "commands": {
    "web": "Microsoft.AspNet.Hosting --server Microsoft.AspNet.Server.WebListener --server.urls http://localhost:5000"
  },
  "frameworks": {
    "dnx451": {},
    "dnxcore50": {}
  },
  "exclude": [
    "wwwroot",
    "node_modules",
    "bower_components"
  ],
  "publishExclude": [
    "node_modules",
    "bower_components",
    "**.xproj",
    "**.user",
    "**.vspscc"
  ],
  "entryPoint": "ContactsApi",
  "loadable": false
}
```

**Comment by Tratcher** [comment]
It works for me if I add `/M'. IIS runs as a different user, so the extra flag is needed to set the environment variable system wide.

**Comment by sujitdmello** [comment]
Nice catch - I forgot about the /M switch :(

Thank you @Tratcher
