### ISSUE TITLE
Streamline server specific entry points

### ISSUE THREAD

**Issue by Tratcher** [aspnet/Hosting#298]
Kestrel and WebListener have their own Program.Main that wraps Hosting's. This allows the commands to be simplified, but requires each server to add its own `--server` parameter. See https://github.com/aspnet/KestrelHttpServer/blob/dev/src/Kestrel/Program.cs#L15-L20

Proposal: Add a code path in Hosting's Program class that allows servers to directly provide a reference to their server factory that will be passed into `WebHostBuilder.UseServer(IServerFactory factory)`

Note we want to avoid just duplicating the logic from Hosting's Main method in the other servers, as that becomes difficult to maintain. It's already hard enough to maintain IIS's parallel startup code.

**Comment by davidfowl** [comment]
Do we still need this? I think we should remove the server specific entry points in RC2.

**Comment by Tratcher** [comment]
If the server entrypoints go away then you don't need this exact item, but you need almost the same thing for WebApplication.Run to specify the server.

**Comment by JunTaoLuo** [comment]
As part of https://github.com/aspnet/Hosting/issues/525, the only entry point will now be in Startup.Main.
