### ISSUE TITLE
Ensure static ServiceProvider remains current

### ISSUE THREAD

**Issue by bricelam** [aspnet/Hosting#30]
@loudej wanted to ensure that the static accessor `CallContextServiceLocator.Locator.ServiceProvider` added in aspnet/KRuntime@3a19be54c9be8d8ba3f0fa3ba5976c6cd1ae5971 remained up-to-date with the application's latest IServiceProvider.

**Comment by muratg** [comment]
:watch:

**Comment by muratg** [comment]
@davidfowl RC1 or backlog backlog?

**Comment by davidfowl** [comment]
RC1

**Comment by muratg** [comment]
@davidfowl #402 is not checked in yet so why close this?

**Comment by bricelam** [comment]
Wasn't this issue about keeping `CallContextServiceLocator` up-to-scope? #402 look like adding parallel API...

**Comment by davidfowl** [comment]
@bricelam Yea, but we're deleting CallContextServiceLocator
