### ISSUE TITLE
BUG: WebHostBuilder.UseEnvironment being overwritten on WebHostBuilder.Build

### ISSUE THREAD

**Issue by giggio** [aspnet/Hosting#302]
If you set the environment using `WebHostBuilder.UseEnvironment` and later call `WebHostBuilder.Build` it will initialize using `HostingEnvironmentExtensions`:
https://github.com/aspnet/Hosting/blob/1.0.0-beta5/src/Microsoft.AspNet.Hosting/WebHostBuilder.cs#L101
This will overwrite the setting applied with `UseEnvironment`, making this method useless.
Either remove the method, or rewrite the way it is working so that on `Build` the environment passed in by the user is used.

**Comment by davidfowl** [comment]
@giggio Care to submit a pull request?

/cc @HaoK

**Comment by giggio** [comment]
@davidfowl sure. I will change it in a way that the Build method works.
