### ISSUE TITLE
Can not use browsers to browse TestServer

### ISSUE THREAD

**Issue by JiajieBao** [aspnet/Hosting#312]
I use the following code to start a TestServer and keep it running:
TestServer server = TestServer.Create(app => app.UseFileServer());
Thread.Sleep(20000);
Then I enter "http://localhost/index.html".
The browser shows "can not connect to server".
server.BaseAddress.Port is 80.
How to fix it?

**Comment by Tratcher** [comment]
This is by design. TestServer is for unit testing components in memory, it does not open any real network connections. HttpRequestMessages (HttpClient) are converted directly to HttpContext objects   (Asp.Net) without being sent over a socket.

Here is a usage example:
https://github.com/aspnet/BasicMiddleware/blob/dev/test/Microsoft.AspNet.HttpOverrides.Tests/OverrideHeaderMiddlewareTest.cs#L21

If you would like to test using the browser then you need to use a real server like WebListener, Kestrel, or IIS instead.

**Comment by JiajieBao** [comment]
I want to build unit tests to test a JavaScript library.
First I start a local server, then use Selenium to do web browser automation, then do some assertion.
I want all these code within an xUnit testcase.
My question is: Can I start a "real" server within an [Fact]? And how?

**Comment by glennc** [comment]
@Tratcher Will get you an example, AFAIK it is possible to do what you want.

**Comment by Tratcher** [comment]
You can do that with WebListener or Kestrel. Try this:
```C#
using System;
using System.Collections.Generic;
using System.Net;
using System.Net.Http;
using System.Threading.Tasks;
using Microsoft.AspNet.Builder;
using Microsoft.AspNet.Hosting;
using Microsoft.AspNet.Http;
using Microsoft.Dnx.Runtime.Infrastructure;
using Microsoft.Framework.Configuration;
using Xunit;

namespace ClassLibrary1
{
    public class TestClass
    {
        [Fact]
        public async Task MyTest()
        {
            string address = "http://localhost:8080";
            using (CreateServer(address, app =>
            {
                app.Run(ctx =>
                {
                    return ctx.Response.WriteAsync("Hello World");
                });
            }))
            {
                var response = await SendRequestAsync(address);
                Assert.Equal(HttpStatusCode.OK, response.StatusCode);
                Assert.Equal("Hello World", await response.Content.ReadAsStringAsync());
            }
        }

        public async Task<HttpResponseMessage> SendRequestAsync(string uri)
        {
            using (HttpClient client = new HttpClient())
            {
                return await client.GetAsync(uri);
            }
        }

        public IDisposable CreateServer(string address, Action<IApplicationBuilder> app)
        {
            var builder = new ConfigurationBuilder();
            builder.AddInMemoryCollection(new[]
            {
                new KeyValuePair<string, string>("server.urls", address)
            });
            var config = builder.Build();

            var hostBuilder = new WebHostBuilder(CallContextServiceLocator.Locator.ServiceProvider, config);
            hostBuilder.UseStartup(app);
            hostBuilder.UseServer("Microsoft.AspNet.Server.WebListener");
            return hostBuilder.Build().Start();
        }
    }
}
```
And project.json:
```
{
  "version": "1.0.0-*",
  "commands": {
    "test": "xunit.runner.aspnet"
  },

  "dependencies": {
    "Microsoft.AspNet.Server.WebListener": "1.0.0-*",
    "xunit.runner.aspnet": "2.0.0-aspnet-*",
    "System.Net.Http": "4.0.0"
  },

  "frameworks": {
    "dnx451": { },
    "dnxcore50": { }
  }
}
```

**Comment by JiajieBao** [comment]
Thanks. I tried this code and got a Runtime Error at CreateServer.
After debugging, I find that CallContextServiceLocator.Locator is null.
Could you help me to fix that?

**Comment by Tratcher** [comment]
Hmm, which version of DNX are you running it on? It worked fine on beta6.

**Comment by davidfowl** [comment]
@JiajieBao are you on mono?

**Comment by JiajieBao** [comment]
Fixed. Looks like I used some incompatible references. Thanks.

**Comment by hekaiduo** [comment]
Hello, I've read [the Sep 10th webdev blog](http://blogs.msdn.com/b/webdev/archive/2015/09/10/asp-net-community-standup-september-8-2015.aspx). It says,

> Kestrel and DNX are the only server and host processes that will be shipped.
> WebListener will not be shipped.

and

> **Question**: What if I wanted to host kestrel in my own process?
> There is no self-host model.  Dnx is a hosted model, where you pass in the application that you want dnx to host.  This is similar to node where you execute node and pass in the application that you want node to run.

So here is my question: since WebListener will not be 'shipped', and kestrel doesn't have a self-host model, how do we achieve an *real* test server demonstrated by @Tratcher above? Thanks.

**Comment by davidfowl** [comment]
Change this line:

```
hostBuilder.UseServer("Microsoft.AspNet.Server.Kestrel");
```

**Comment by hekaiduo** [comment]
@davidfowl 

Thanks. What happens when changing to `hostBuilder.UseServer("Microsoft.AspNet.Server.Kestrel");`? Will it spin up a new process for kestrel? If yes,when will the external process will be shut down?

**Comment by Tratcher** [comment]
No, it starts kestrel in process just like WebListener. Try it.

**Comment by hekaiduo** [comment]
That is what I want :) 

But what does the blog mean by `There is no self-host model` for kestrel? A bit confused, as the code here seems to be *a self-hosted model*.

**Comment by davidfowl** [comment]
The blog might be wrong :smile: I'll check the wording.

**Comment by BennieCopeland** [comment]
It has been a year since this answer. Is there any new information on how someone can do browser testing with tools like Selenium? This is what I currently have, and it works, but I don't know how correct it is or if there is a better way.
```csharp
public abstract class SeleniumTests : nspec
{
    private IWebHost host;
    protected IWebDriver driver;

    void before_each()
    {
        host = new WebHostBuilder()
                        .UseKestrel()
                        .UseContentRoot(GetContentRoot())
                        .UseStartup<Startup>()
                        .Build();

        host.Start();

        var ieService = InternetExplorerDriverService.CreateDefaultService();
        ieService.SuppressInitialDiagnosticInformation = true;

        driver = new InternetExplorerDriver(ieService);
    }

    void after_each()
    {
        driver.Dispose();
        host.Dispose();
    }

    private static string GetContentRoot()
    {
        var solutionRoot = new DirectoryInfo(PlatformServices.Default.Application.ApplicationBasePath) // netcoreapp1.1 folder
            .Parent // Debug or Release folder
            .Parent // bin folder
            .Parent // TSC.Services.Authentication.AcceptanceTests folder
            .Parent // test folder
            .Parent.FullName; // root folder

        Console.WriteLine(PlatformServices.Default.Application.ApplicationBasePath);

        return Path.GetFullPath(Path.Combine(solutionRoot, @"src\TSC.Services.Authentication.Api"));
    }
}
```

**Comment by brockallen** [comment]
FWIW we have created a simple browser-like user agent to use when testing with the TestServer: https://brockallen.com/2016/01/01/browsr-helper-for-integration-testing-in-asp-net-5/, and here's the current version in use: https://github.com/IdentityServer/IdentityServer4/blob/dev/test/IdentityServer.IntegrationTests/Common/BrowserClient.cs

**Comment by BennieCopeland** [comment]
@brockallen Thank you for the links. Its actually IdentityServer4 that I am currently testing against. That looks like it will be helpful for API calls, but does it allow for actual browser viewing of the HTML? I'm using Selenium for functional/user acceptance testing to show the UI is connected up.

**Comment by brockallen** [comment]
Correct -- there's not real "viewing" or the HTML. It's mostly just to make requests that act like a browser in terms of cookie container and following redirects.
