### ISSUE TITLE
TestServer HttpClient send does not return after first write

### ISSUE THREAD

**Issue by tmds** [aspnet/Hosting#313]
I have a test which has some code like this:

    var response = await client.PostAsync(...

On the server side, I am trying to stream some content so when I have some data I do a write and a flush:

    await _context.Response.Body.WriteAsync(buffer.Array, buffer.Offset, buffer.Count, cancellationToken);
    await _context.Response.Body.FlushAsync(cancellationToken);

My expectation is that the PostAsync would continue after the first Flush, but that is not the case.

Note that when I use perform the same request using a 'real' server, I see some buffering occurs at first and then content goes out chunked.

Is this use-case supported by the TestServer?

**Comment by Tratcher** [comment]
This is a behavior of HttpClient, it's unrelated to TestServer. Most of the methods on HttpClient fully buffer the response body before returning. You would see this even when connecting to a real server. You need to use this overload https://msdn.microsoft.com/en-us/library/hh193601(v=vs.118).aspx with the HttpCompletionOption.ResponseHeadersRead option to disable response buffering. This one also works https://msdn.microsoft.com/en-us/library/Hh551739(v=VS.118).aspx, but only for GET requests.

Note TestServer starts sending the response to the client on the first Write, it has no initial buffer so Flush is not required.

**Comment by tmds** [comment]
Thanks!
