### ISSUE TITLE
Support WebSocket tests using TestServer

### ISSUE THREAD

**Issue by tmds** [aspnet/Hosting#315]
Request to be able to test WebSockets using the TestServer.

WebSocket testing could start by calling a new method TestServer.CreateWebSocketClient(). This method returns a WebSocketClient. This is similar to the normal http request testing: TestServer.CreateClient method which returns an HttpClient.

**Comment by Tratcher** [comment]
It sounds doable, and kindof fun actually. I don't think it's a very high priority though, so I can't say how soon it would happen.

**Comment by davidfowl** [comment]
Sounds like it would make a good contribution

**Comment by tmds** [comment]
@Tratcher, @davidfowl, if you want, you can assign the issue to me.

**Comment by davidfowl** [comment]
@tmds issues can't be assinged to non core contributors

**Comment by tmds** [comment]
@davidfowl I guess you mean the tool doesn't allow it.
I want to check whether it is worth spending my time, that is: you guys won't work on it in the short term and it is 'up for grabs'.

**Comment by davidfowl** [comment]
We don't have any plans to do it in the short term so feel free to do it
