### ISSUE TITLE
DI: Unity-Backed Service Provider Breaks Controller Routing

### ISSUE THREAD

**Issue by emilyclairelewis42** [aspnet/Hosting#317]
I have written a bare bones Web API solution against 6.0.0-beta6 and dnx451 using my own Unity container as the service provider. I arrived at this approach using reference code [here](https://github.com/aspnet/DependencyInjection)
and [here](http://dzimchuk.net/post/bring-your-own-di-container-to-aspnet-5-unity). 

With Unity installed MVC6 no longer seems able to route requests to the controller (I am simply hitting F5 to debug and running IIS express). In fact, MVC6 never even makes an attempt to instantiate the controller nor does it even go after the scope factory (as witnessed by setting a breakpoint in the service provider's "GetService" method). All requests simply yield the message "HTTP Error 404.0 - Not Found". 

Code is as follows:

## IServiceScopeFactory
```c#
class ServiceScopeFactory : IServiceScopeFactory
{
    IUnityContainer _container = null;

    public ServiceScopeFactory(IUnityContainer container)
    {
        _container = container;
    }

    IServiceScope IServiceScopeFactory.CreateScope()
    {
        IServiceScope serviceScope = _container.Resolve<IServiceScope>();
        return serviceScope;
    }
}
```

## IServiceScope
```c#
class ServiceScope : IServiceScope
{
    IUnityContainer _container = null;
    IServiceProvider _serviceProvider = null;

    public ServiceScope(IUnityContainer container)
    {
        _container = container.CreateChildContainer();
        _serviceProvider = _container.Resolve<IServiceProvider>();
    }

    IServiceProvider IServiceScope.ServiceProvider
    {
        get
        {
            return _serviceProvider;
        }
    }

    void IDisposable.Dispose()
    {
        _container.Dispose();
    }
}
```
## IServiceProvider
```c#
class ServiceProvider : IServiceProvider
{
    IUnityContainer _container = null;

    public ServiceProvider(IUnityContainer container)
    {
        _container = container;
    }

    object IServiceProvider.GetService(Type serviceType)
    {
        object instance = _container.Resolve(serviceType);
        return instance;
    }
}
```

## Startup
```c#
public class Startup
{
    IUnityContainer _container = new UnityContainer();

    public IServiceProvider ConfigureServices(IServiceCollection services)
    {
        services.AddMvc();

        _container.RegisterType<IServiceScopeFactory, ServiceScopeFactory>();
        _container.RegisterType<IServiceScope, ServiceScope>();
        _container.RegisterType<IServiceProvider, ServiceProvider>();

        _container.RegisterType
        (
            typeof(IEnumerable<>),
            new InjectionFactory
            (
                (container, enumerableType, name) =>
                {
                    Type type = enumerableType.GetGenericArguments().Single();

                    object[] allInstances = container.ResolveAll(type).Concat
                    (
                        (_container.IsRegistered(type) || (type.IsGenericType && _container.IsRegistered(type.GetGenericTypeDefinition())))
                        ?
                        new object[] { container.Resolve(type) }
                        :
                        new object[] { }
                    ).ToArray();

                    return
                            typeof(Enumerable).
                            GetMethod("OfType", BindingFlags.Static | BindingFlags.Public).
                            MakeGenericMethod(new Type[] { type }).
                            Invoke(null, new object[] { allInstances });
                }
            )
        );

        Func<ServiceDescriptor, LifetimeManager> FetchLifetime = (serviceDescriptor) =>
        {
            switch (serviceDescriptor.Lifetime)
            {
                case ServiceLifetime.Scoped:
                    return new HierarchicalLifetimeManager();
                case ServiceLifetime.Singleton:
                    return new ContainerControlledLifetimeManager();
                case ServiceLifetime.Transient:
                    return new TransientLifetimeManager();
                default:
                    throw new NotImplementedException(string.Format("Unsupported lifetime manager type '{0}'", serviceDescriptor.Lifetime));
            }
        };

        foreach (ServiceDescriptor serviceDescriptor in services)
        {
            LifetimeManager lifetimeManager = FetchLifetime(serviceDescriptor);

            if (serviceDescriptor.ImplementationType != null)
            {
                _container.RegisterType(serviceDescriptor.ServiceType, serviceDescriptor.ImplementationType, lifetimeManager);
            }

            else if (serviceDescriptor.ImplementationFactory != null)
            {
                _container.RegisterType
                (
                    serviceDescriptor.ServiceType,
                    lifetimeManager,
                    new InjectionFactory
                    (
                        container =>
                        {
                            IServiceProvider serviceProvider = container.Resolve<IServiceProvider>();
                            object instance = serviceDescriptor.ImplementationFactory(serviceProvider);
                            return instance;
                        }
                    )
                );
            }

            else if (serviceDescriptor.ImplementationInstance != null)
            {
                _container.RegisterInstance(serviceDescriptor.ServiceType, serviceDescriptor.ImplementationInstance, lifetimeManager);
            }

            else
            {
                throw new InvalidOperationException("Unsupported registration type");
            }

        }

        return _container.Resolve<IServiceProvider>();
    }

    public void Configure(IApplicationBuilder app)
    {
        app.UseMvc();
    }
}
```

## Controller
```c#
[Route("api/[controller]")]
public class ValuesController : Controller
{
    // GET: api/values
    [HttpGet]
    public IEnumerable<string> Get()
    {
        return new string[] { "value1", "value2" };
    }
}
```

As I mentioned previously, MVC6 never even makes an attempt to instantiate the scope factory when it receives the HTTP GET request using this code. Curiously, I discovered that changing "ConfigureServices" to return null:

```c#
...
public void ConfigureServices(IServiceCollection services)
...
```
...and installing the service provider late in the "Configure" method:

```c#
public void Configure(IApplicationBuilder app)
{
    app.UseMvc();

    app.ApplicationServices = _container.Resolve<IServiceProvider>();
}
```
...seems to alter this behavior, where at least each incoming HTTP GET request *does* hit the scope factory, fetch a scope, and then hit the service provider's "GetService" method. The exact series of resolution events when an HTTP GET request is received is:

- Resolve IServiceScopeFactory
- Resolve MVCMarkerService
- Resolve IActionSelector
- Resolve IServiceScopeFactory
- Resolve MVCMarkerService
- Resolve IActionSelector
- Return 404

I can upload a sample solution or the IIS express trace logs if it would help. Thanks.

**Comment by emilyclairelewis42** [comment]
This error was happening because I was not properly registering collections of types. For example, there are multiple registrations for IStartupFilter. The following startup resolved that issue:

## Startup
```c#
public class Startup
{
    IUnityContainer _container = new UnityContainer();

    public IServiceProvider ConfigureServices(IServiceCollection services)
    {
        services.AddMvc();

        HashSet<Type> aggregateTypes = new HashSet<Type>
            (
                services.
                GroupBy
                (
                    serviceDescriptor => serviceDescriptor.ServiceType,
                    serviceDescriptor => serviceDescriptor
                ).
                Where(typeGrouping => typeGrouping.Count() > 1).
                Select(type => type.Key)
            );

        MethodInfo miRegisterInstanceOpen =
            typeof(UnityContainerExtensions).
            GetMethods(BindingFlags.Static | BindingFlags.Public).
            Single(mi => (mi.Name == "RegisterInstance") && mi.IsGenericMethod && (mi.GetParameters().Length == 4));

        _container.RegisterType<IServiceScopeFactory, ServiceScopeFactory>();
        _container.RegisterType<IServiceScope, ServiceScope>();
        _container.RegisterType<IServiceProvider, ServiceProvider>();

        _container.RegisterType
        (
            typeof(IEnumerable<>),
            new InjectionFactory
            (
                (container, enumerableType, name) =>
                {
                    Type type = enumerableType.GetGenericArguments().Single();

                    object[] allInstances = container.ResolveAll(type).Concat
                    (
                        (_container.IsRegistered(type) || (type.IsGenericType && _container.IsRegistered(type.GetGenericTypeDefinition())))
                        ?
                        new object[] { container.Resolve(type) }
                        :
                        new object[] { }
                    ).ToArray();

                    return
                            typeof(Enumerable).
                            GetMethod("OfType", BindingFlags.Static | BindingFlags.Public).
                            MakeGenericMethod(new Type[] { type }).
                            Invoke(null, new object[] { allInstances });
                }
            )
        );

        Func<ServiceDescriptor, LifetimeManager> FetchLifetime = (serviceDescriptor) =>
        {
            switch (serviceDescriptor.Lifetime)
            {
                case ServiceLifetime.Scoped:
                    return new HierarchicalLifetimeManager();
                case ServiceLifetime.Singleton:
                    return new ContainerControlledLifetimeManager();
                case ServiceLifetime.Transient:
                    return new TransientLifetimeManager();
                default:
                    throw new NotImplementedException(string.Format("Unsupported lifetime manager type '{0}'", serviceDescriptor.Lifetime));
            }
        };

        // Configure all registrations into Unity
        foreach (ServiceDescriptor serviceDescriptor in services)
        {
            LifetimeManager lifetimeManager = FetchLifetime(serviceDescriptor);
            bool isAggregateType = aggregateTypes.Contains(serviceDescriptor.ServiceType);

            // Register From-->To types
            if (serviceDescriptor.ImplementationType != null)
            {
                if (isAggregateType)
                {
                    _container.RegisterType(serviceDescriptor.ServiceType, serviceDescriptor.ImplementationType, serviceDescriptor.ImplementationType.AssemblyQualifiedName, lifetimeManager);
                }
                else
                {
                    _container.RegisterType(serviceDescriptor.ServiceType, serviceDescriptor.ImplementationType, lifetimeManager);
                }
            }

            // Register types that have a factory
            else if (serviceDescriptor.ImplementationFactory != null)
            {
                if (isAggregateType)
                {
                    _container.RegisterType
                    (
                        serviceDescriptor.ServiceType,
                        serviceDescriptor.ImplementationType.AssemblyQualifiedName,
                        lifetimeManager,
                        new InjectionFactory
                        (
                            container =>
                            {
                                IServiceProvider serviceProvider = container.Resolve<IServiceProvider>();
                                object instance = serviceDescriptor.ImplementationFactory(serviceProvider);
                                return instance;
                            }
                        )
                    );
                }
                else
                {
                    _container.RegisterType
                    (
                        serviceDescriptor.ServiceType,
                        lifetimeManager,
                        new InjectionFactory
                        (
                            container =>
                            {
                                IServiceProvider serviceProvider = container.Resolve<IServiceProvider>();
                                object instance = serviceDescriptor.ImplementationFactory(serviceProvider);
                                return instance;
                            }
                        )
                    );
                }
            }
            // Register singletons
            else if (serviceDescriptor.ImplementationInstance != null)
            {
                if (isAggregateType)
                {
                    miRegisterInstanceOpen.
                        MakeGenericMethod(new Type[] { serviceDescriptor.ServiceType }).
                        Invoke(null, new object[] { _container, serviceDescriptor.ImplementationType.AssemblyQualifiedName, serviceDescriptor.ImplementationInstance, lifetimeManager });
                }
                else
                {
                    _container.RegisterInstance(serviceDescriptor.ServiceType, serviceDescriptor.ImplementationInstance, lifetimeManager);
                }
            }
            else
            {
                throw new InvalidOperationException("Unsupported registration type");
            }

        }

        return _container.Resolve<IServiceProvider>();
    }
```

This led to a new error though, MVC6 throwing the exception:

System.NullReferenceException
Object reference not set to an instance of an object.
at Microsoft.AspNet.Mvc.UrlHelper..ctor(IScopedInstance<ActionContext> contextAccessor, IActionSelector actionSelector) 
.lambda_method(Closure , IBuilderContext ) 

Full stack trace:

at Microsoft.Practices.Unity.UnityContainer.DoBuildUp(Type t, Object existing, String name, IEnumerable<ResolverOverride> resolverOverrides) 
at Microsoft.Practices.Unity.UnityContainer.DoBuildUp(Type t, String name, IEnumerable<ResolverOverride> resolverOverrides) 
at Microsoft.Practices.Unity.UnityContainer.Resolve(Type t, String name, ResolverOverride[] resolverOverrides) 
at Microsoft.Practices.Unity.UnityContainerExtensions.Resolve(IUnityContainer container, Type t, ResolverOverride[] overrides) 
at junk.ServiceProvider.System.IServiceProvider.GetService(Type serviceType) in C:\Temp\junk\src\junk\Startup.cs:line 74 
at Microsoft.Framework.DependencyInjection.ServiceProviderExtensions.GetRequiredService(IServiceProvider provider, Type serviceType) 
at Microsoft.AspNet.Mvc.ModelBinding.ServicesModelBinder.BindModelCoreAsync(ModelBindingContext bindingContext) 
at Microsoft.AspNet.Mvc.ModelBinding.BindingSourceModelBinder.<BindModelAsync>d__5.MoveNext() 
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) 
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) 
at System.Runtime.CompilerServices.TaskAwaiter<TResult>.GetResult() 
at Microsoft.AspNet.Mvc.ModelBinding.CompositeModelBinder.<TryBind>d__5.MoveNext() 
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) 
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) 
at System.Runtime.CompilerServices.TaskAwaiter<TResult>.GetResult() 
at Microsoft.AspNet.Mvc.ModelBinding.CompositeModelBinder.<BindModelAsync>d__4.MoveNext() 
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) 
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) 
at System.Runtime.CompilerServices.TaskAwaiter<TResult>.GetResult() 
at Microsoft.AspNet.Mvc.DefaultControllerActionArgumentBinder.<BindModelAsync>d__5.MoveNext() 
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) 
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) 
at System.Runtime.CompilerServices.TaskAwaiter<TResult>.GetResult() 
at Microsoft.AspNet.Mvc.DefaultControllerActionArgumentBinder.<PopulateArgumentsAsync>d__8.MoveNext() 
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) 
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) 
at System.Runtime.CompilerServices.TaskAwaiter.GetResult() 
at Microsoft.AspNet.Mvc.DefaultControllerActionArgumentBinder.<BindActionArgumentsAsync>d__4.MoveNext() 
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) 
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) 
at System.Runtime.CompilerServices.TaskAwaiter<TResult>.GetResult() 
at Microsoft.AspNet.Mvc.Core.FilterActionInvoker.<InvokeAllActionFiltersAsync>d__48.MoveNext() 
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) 
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) 
at System.Runtime.CompilerServices.TaskAwaiter.GetResult() 
at Microsoft.AspNet.Mvc.Core.FilterActionInvoker.<InvokeExceptionFilterAsync>d__47.MoveNext() 
--- exception rethrown --- 
at Microsoft.AspNet.Mvc.Core.FilterActionInvoker.<InvokeAsync>d__40.MoveNext() 
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) 
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) 
at System.Runtime.CompilerServices.TaskAwaiter.GetResult() 
at Microsoft.AspNet.Mvc.MvcRouteHandler.<InvokeActionAsync>d__4.MoveNext() 
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) 
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) 
at System.Runtime.CompilerServices.TaskAwaiter.GetResult() 
at Microsoft.AspNet.Mvc.MvcRouteHandler.<RouteAsync>d__3.MoveNext() 
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) 
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) 
at System.Runtime.CompilerServices.TaskAwaiter.GetResult() 
at Microsoft.AspNet.Mvc.Routing.InnerAttributeRoute.<RouteAsync>d__10.MoveNext() 
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) 
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) 
at System.Runtime.CompilerServices.TaskAwaiter.GetResult() 
at Microsoft.AspNet.Routing.RouteCollection.<RouteAsync>d__9.MoveNext() 
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) 
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) 
at System.Runtime.CompilerServices.TaskAwaiter.GetResult() 
at Microsoft.AspNet.Builder.RouterMiddleware.<Invoke>d__4.MoveNext() 
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) 
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) 
at System.Runtime.CompilerServices.TaskAwaiter.GetResult() 
at Microsoft.AspNet.Hosting.Internal.RequestServicesContainerMiddleware.<Invoke>d__3.MoveNext() 
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) 
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) 
at System.Runtime.CompilerServices.TaskAwaiter.GetResult() 
at Microsoft.AspNet.Hosting.Internal.HostingEngine.<>c__DisplayClass29_0.<<Start>b__0>d.MoveNext() 
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) 
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) 
at System.Runtime.CompilerServices.TaskAwaiter.GetResult() 
at Microsoft.AspNet.Loader.IIS.RuntimeHttpApplication.<ProcessRequestAsyncImpl>d__10.MoveNext() 
--- exception rethrown --- 
at Microsoft.AspNet.Loader.IIS.RuntimeHttpApplication.<ProcessRequestAsyncImpl>d__10.MoveNext() 
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) 
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) 
at System.Runtime.CompilerServices.TaskAwaiter.GetResult() 
at Microsoft.AspNet.Loader.IIS.HttpApplicationBase.<InvokeProcessRequestAsyncImpl>d__9.MoveNext()

**Comment by glennc** [comment]
@rynowak Can you take a quick look at this?

**Comment by emilyclairelewis42** [comment]
Further testing today reveals that this exception only happens exactly one time at startup, at least on our development boxes. All subsequent calls to the controller work fine. This seems to suggest that IScopedInstance< T > (specifically IScopedInstance<ActionContext> for this use case), which **is** being registered as a Scoped (a.k.a. Hierarchical in Unity lingo) lifetime, is not being managed properly at startup? 

Though this is totally invalid for a production scenario, I tried changing the registration of IScopedInstance< T > to be a singleton (a.k.a. container controlled in Unity lingo) and then the controller is called the very first time.

**Comment by rynowak** [comment]
@emilyclairelewis42 - `IScopedInstance<>` really needs to be scoped (per-request). If it's a singleton then all kinds of things will be accessed concurrently that need per-request state.

**Comment by emilyclairelewis42** [comment]
I agree ;o)  I wasn't especially clear in the previous comment. I meant to point out that when MVC6 throws the exception:

>System.NullReferenceException
 Object reference not set to an instance of an object.
 at Microsoft.AspNet.Mvc.**UrlHelper**..ctor(IScopedInstance contextAccessor, IActionSelector actionSelector) 
 .lambda_method(Closure , IBuilderContext )
UrlHelper

... this only happens one time at startup on the first call to my controller. All subsequent calls work.

Looking at the source code for UrlHelper indicates that it dependency injects IScopedInstance< ActionContext >. Since it's throwing a null reference exception the Value property of  IScopedInstance< ActionContext > must be null, which I have confirmed in the debugger.

This seems to suggest that someone in the chain, on startup at least, doesn't seem to be filling in IScopedInstance< ActionContext > correctly or at the right time. I was speculating that a way to prove this would be temporarily to change IScopedInstance<> lifetime to singleton, though I did not intend to present this as a fix.

As to why IScopedInstance< ActionContext >.Value is null on startup, I can't begin to speculate, other that the Unity implementation I have attempted is causing the bug. For what it's worth I instrumented up some logging and here's the instantiation sequence at startup:

>ILoggerFactory (root container)
>IApplicationBuilderFactory (root container)
>IEnumerable< IStartupFilter > (root container)
>IEnumerable< IStartupFilter > (root container)
>MvcMarkerService (root container)
>IActionDescriptorsCollectionProvider (root container)
>IInlineConstraintResolver (root container)
>IEnumerable< IConfigureOptions< RouteOptions > > (root container)
>ILoggerFactory (root container)
>ILoggerFactory (root container)
>IHostingEnvironment (root container)
>ILoggerFactory (root container)
>IServiceProvider (root container)
>ILogger< HostingEngine > (root container)
>IHttpContextFactory (root container)
>IHttpContextAccessor (root container)
>IServiceScopeFactory (root container)
>Scope Created
>IEnumerable< IActionDescriptorProvider > (root container)
>IEnumerable< IActionDescriptorProvider > (root container)
>IEnumerable< IApplicationModelProvider > (root container)
>IEnumerable< IConfigureOptions< AuthorizationOptions > > (root container)
>IEnumerable< IConfigureOptions< MvcOptions > > (root container)
>IEnumerable< IConfigureOptions< MvcJsonOptions > > (root container)
>MvcMarkerService (child container)
>ILoggerFactory (child container)
>INotifier (child container)
>IActionSelector (child container)
>IEnumerable< IActionConstraintProvider > (child container)
>IScopedInstance< ActionContext > (child container)
>IActionInvokerFactory (child container)
>IEnumerable< IActionInvokerProvider > (child container)
>IEnumerable< IControllerPropertyActivator > (child container)
>IOptions< MvcOptions > (child container)
>IEnumerable< IFilterProvider > (child container)
>IOptions< MvcOptions > (child container)
>IModelMetadataProvider (child container)
>IMyService (child container)
>IScopedInstance< ActionBindingContext > (child container)
>IModelMetadataProvider (child container)
>IUrlHelper (child container)
>Exception thrown: 'System.NullReferenceException' in Microsoft.AspNet.Mvc.Core.dll
>Exception thrown: 'System.NullReferenceException' in Microsoft.Practices.Unity.dll
>Exception thrown: 'Microsoft.Practices.Unity.ResolutionFailedException' in Microsoft.Practices.Unity.dll
>Scope Disposed
>Exception thrown: 'Microsoft.Practices.Unity.ResolutionFailedException' in mscorlib.dll
>Exception thrown: 'Microsoft.Practices.Unity.ResolutionFailedException' in Microsoft.AspNet.Loader.IIS.dll
>Exception thrown: 'Microsoft.Practices.Unity.ResolutionFailedException' in mscorlib.dll
>IServiceScopeFactory (root container)
>Scope Created
>Scope Disposed

This clearly shows IScopedInstance< ActionContext > is instantiated before IUrlHelper.

Every subsequent GET works:

> IServiceScopeFactory (root container)
> Scope Created
> MvcMarkerService (child container)
> IActionSelector (child container)
> IScopedInstance< ActionContext > (child container)
> IActionInvokerFactory (child container)
> IEnumerable< IActionInvokerProvider > (child container)
> IEnumerable< IFilterProvider > (child container)
> IMyService (child container)
> IScopedInstance< ActionBindingContext > (child container)
> IModelMetadataProvider (child container)
> IUrlHelper (child container)
> IObjectModelValidator (child container)
> ITempDataDictionary (child container)
> ILogger< ObjectResult > (child container)
> IScopedInstance< ActionBindingContext > (child container)
> ILogger< ObjectResult > (child container)
> IOptions< MvcOptions > (child container)
> Scope Disposed

**Comment by muratg** [comment]
@rynowak Is there any investigation left here?

**Comment by muratg** [comment]
Closing as `IScopedInstance` is removed.

**Comment by Hem** [comment]
This bug is back? 

I keep running into the following message using both Unity Core-CLR or Microsoft.Practices.Unity;
[Web.zip](https://github.com/aspnet/Hosting/files/435236/Web.zip)

-----------------------

An exception of type 'System.InvalidOperationException' occurred in Microsoft.Extensions.DependencyInjection.Abstractions.dll but was not handled in user code

Additional information: No service for type 'Microsoft.AspNetCore.Mvc.Internal.MvcRouteHandler' has been registered.

**Comment by muratg** [comment]
@hem can you put the repro code in a GitHub repo and file another bug with the details?  Thanks.
