### ISSUE TITLE
Can't run on IISExpress (ASP.NET application initialization failed)

### ISSUE THREAD

**Issue by evorine** [aspnet/Hosting#319]
When I'm using dnx version `1.0.0-beta7-12302`, IIS Express can't startup my application.
I receive an undetailed error page says:
> HTTP Error 500.0 - Internal Server Error
> ASP.NET application initialization failed.

By the way I can run my application with `web` command without any problem.

When I'm using the version `1.0.0-beta7-12290` IIS Express can start my application but this time I get:
> TypeLoadException: Could not load type 'Microsoft.Dnx.Compilation.ILibraryExporter' from assembly 'Microsoft.Dnx.Compilation.Abstractions...

I looked everywhere but didn't find any log files about IIS Express. So I don't know what is going on here.

**PS:** Tried x64 dnx and also forced VS to launch 64bit version IIS Express but nothing changed.

---

**To reproduce this:**

* I created an empty web project
* Targeted `1.0.0-beta7-12302`

project.json dependencies:
````
"dependencies": {
    "Microsoft.AspNet.Server.IIS": "1.0.0-beta7-*",
    "Microsoft.AspNet.Server.WebListener": "1.0.0-beta7-*"
}
````
These beta7-* versions currently are: `1.0.0-beta7-12119` and `1.0.0-beta7-12499`.

startup.cs:
````
public class Startup
{
    public void ConfigureServices(IServiceCollection services)
    {
    }

    public void Configure(IApplicationBuilder app)
    {
        app.Run(async (context) =>
        {
            await context.Response.WriteAsync("Hello World!");
        });
    }
}
````

**Comment by Tratcher** [comment]
Yes, there's a known break currently being resolved. We recommend using beta6 for the time being.

**Comment by glennc** [comment]
@Tratcher Can you close this when we have fixed the break? If there is another bug tracking that work you can link it and close this now.

**Comment by Tratcher** [comment]
This has been resolved in the latest beta7 dnx and packages.
