### ISSUE TITLE
ASP.NET 5 on IIS

### ISSUE THREAD

**Issue by PrimeObjects** [aspnet/Hosting#321]
I created a ASP.NET web app. Configure it to IIS. I got the following error. Any idea?

Couldn't determine an appropriate version of runtime to run. See http://go.microsoft.com/fwlink/?LinkId=517742 for more information.

Thanks lot!
Gary

**Comment by Eilon** [comment]
@PrimeObjects can you share a little bit more info about what you've done? Which versions of ASP.NET/DNX are you using? Which version of Windows and IIS? Can you upload the project to GitHub for us to take a look?

**Comment by PrimeObjects** [comment]
Windows 8 (Ver 6.2 Build 9200)
IIS Version 8.5.9600.16384

![po iis v7](https://cloud.githubusercontent.com/assets/3459952/9156419/33b39a52-3e8e-11e5-8f45-3e7a8097e3c9.JPG)

Please download my code from http://downloads.primeobjects.com.s3.amazonaws.com/PrimeObjects.Platform.Web.zip

Thanks lot
Gary

**Comment by glennc** [comment]
@moozzyk Can you investigate what is going on here?

**Comment by PrimeObjects** [comment]
Thank you guys for the help.

I searched online, I'm not the only one who has issue to easily (even successfully) run ASP.NET on IIS. I did not find any good blog or article to layout a How-to steps.

I don't mind to help write one after you help me figure out what's wrong here.

Thanks
Gary

**Comment by Tratcher** [comment]
@PrimeObjects have you started with the publish docs? http://docs.asp.net/en/latest/publishing/iis.html

**Comment by moozzyk** [comment]
This happens if there is no web.config file indicating the runtime and the runtime could not be determined based on the %PATH%. As @Tratcher mentioned one of the reasons might be that the application was not published or was not published with the --runtime switch. This issue looks very similar to #452

**Comment by PrimeObjects** [comment]
Could you give me a link to #452? or what should I put in web.config

**Comment by moozzyk** [comment]
Trying again https://github.com/aspnet/Home/issues/452

**Comment by moozzyk** [comment]
@PrimeObjects  - were you able to resolve this issue?

**Comment by PrimeObjects** [comment]
No. I did publish to local and use wwwroot in the IIS I got the following error
Unable to find the runtime directory 'C:\PrimeObjects\V7.0\artifacts\bin\PrimeObjects.Platform.Web\Release\www\wwwroot\..\approot\runtimes\dnx-clr-win-x64.1.0.0-beta6'.
Possible causes:
1. The runtime was not packaged with the application.
2. The packaged runtime architecture is different from the application pool architecture.

I also try to publish Azure, the VS2015 taking forever to publish (I eventually have to kill the VS2015 process).

**Comment by moozzyk** [comment]
This 'wwwroot..\' does not look right...

**Comment by PrimeObjects** [comment]
This is the folder I put in IIS
C:\PrimeObjects\V7.0\artifacts\bin\PrimeObjects.Platform.Web\Release\www\wwwroot

**Comment by kichalla** [comment]
Since you are using  `64-bit` clr and the error mentions this `The packaged runtime architecture is different from the application pool architecture.`, can you verify again by setting the `Enable 32-bit applications` flag to `false`(if it was `true` earlier) on the application pool that your app is using.

(Based on the help text of `Enable 32-bit applications` it says that `Processes in WOW64 mode are 32-bit processes that load only 32-bit applications`)

**Comment by PrimeObjects** [comment]
It is Enable 32-bit applications= false.

**Comment by PrimeObjects** [comment]
My project.json
{
    "webroot": "wwwroot",
    "version": "7.0.0-*",

    "dependencies": {
        "Microsoft.ApplicationInsights.AspNet": "1.0.0-beta6",
        "Microsoft.AspNet.Mvc": "6.0.0-beta6",
        "Microsoft.AspNet.Mvc.TagHelpers": "6.0.0-beta6",
        "Microsoft.AspNet.Server.IIS": "1.0.0-beta6",
        "Microsoft.AspNet.Server.WebListener": "1.0.0-beta6",
        "Microsoft.AspNet.StaticFiles": "1.0.0-beta6",

        "Microsoft.Framework.Configuration.Json": "1.0.0-beta6",
        "Microsoft.Framework.Configuration.Xml": "1.0.0-beta6",
        "Microsoft.Framework.Configuration.EnvironmentVariables": "1.0.0-beta6",
        "Microsoft.Framework.Logging.Console": "1.0.0-beta6",

        "Microsoft.AspNet.Diagnostics": "1.0.0-beta6",
        "Microsoft.AspNet.Diagnostics.Entity": "7.0.0-beta6",

      
        "Microsoft.AspNet.Session": "1.0.0-beta6",

        "Microsoft.Framework.Caching.SqlServer": "1.0.0-beta6",
        "Microsoft.Framework.Caching.Abstractions": "1.0.0-beta6",
        "Microsoft.Framework.Caching.Redis": "1.0.0-beta6",

        "Microsoft.AspNet.Antiforgery": "1.0.0-beta6",

        "Microsoft.AspNet.Authentication.Cookies": "1.0.0-beta6",
        "Microsoft.AspNet.Authentication.Facebook": "1.0.0-beta6",
        "Microsoft.AspNet.Authentication.Google": "1.0.0-beta6",
        "Microsoft.AspNet.Authentication.MicrosoftAccount": "1.0.0-beta6",
        "Microsoft.AspNet.Authentication.OpenIdConnect": "1.0.0-beta6",
        "Microsoft.AspNet.Authentication.Twitter": "1.0.0-beta6",

        "Microsoft.AspNet.Identity.EntityFramework": "3.0.0-beta6",

        "Microsoft.AspNet.Tooling.Razor": "1.0.0-beta6",

        "System.Runtime": "4.0.20",


        "PrimeObjects.Platform.KnowledgeSearch": "7.0.0-beta",
        "Microsoft.AspNet.WebApi.MessageHandlers.Compression": "1.3.0"
    },

    "commands": {
        "web": "Microsoft.AspNet.Hosting --config hosting.ini"
    },

    "frameworks": {
        "dnx46": {
            "dependencies": {
                "Microsoft.Web.RedisSessionStateProvider": "1.6.4"
            }
        }
    },

    "exclude": [
        "wwwroot",
        "node_modules",
        "bower_components"
    ],
    "publishExclude": [
        "node_modules",
        "bower_components",
        "**.xproj",
        "**.user",
        "**.vspscc"
    ]
}

**Comment by PrimeObjects** [comment]
my web.config

<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <system.web>
    <compilation debug="true" targetFramework="4.6" />
    <httpRuntime targetFramework="4.6" />
  </system.web>
  <system.webServer>
    <handlers>
      <remove name="ExtensionlessUrlHandler-Integrated-4.0" />
      <remove name="OPTIONSVerbHandler" />
      <remove name="TRACEVerbHandler" />
      <add name="ExtensionlessUrlHandler-Integrated-4.0" path="*." verb="*" type="System.Web.Handlers.TransferRequestHandler" preCondition="integratedMode,runtimeVersionv4.0" />
    </handlers>
  </system.webServer>
</configuration>

**Comment by PrimeObjects** [comment]
By the way I saw a launchSettings.json, does this file did something bad?

{
  "profiles": {
    "IIS Express": {
      "commandName" : "IISExpress",
      "launchBrowser": true,
      "launchUrl": "home/index.html",
      "environmentVariables" : {
        "ASPNET_ENV": "Development"
      }
    }
  }
}

**Comment by kichalla** [comment]
what runtime folder do you have under your published application's `approot\runtimes`? do you have a 64-bit clr in it?

**Comment by PrimeObjects** [comment]
C:\PrimeObjects\V7.0\artifacts\bin\PrimeObjects.Platform.Web\Release\www\approot\runtimes\dnx-clr-win-x86.1.0.0-beta6

**Comment by kichalla** [comment]
Ok..so that is the issue...you need to deploy the 64-bit version of clr since your application pool is a 64-bit process...

**Comment by PrimeObjects** [comment]
Works. Thank you for the help!

**Comment by amera7md** [comment]
i have the same issue here but I have dnx-clr-win-x86.1.0.0-beta7 version , should I install 64 version of dnx or I can as it ?
