### ISSUE TITLE
Dispose hosting engine services once the application is shutting down

### ISSUE THREAD

**Issue by kichalla** [aspnet/Hosting#322]
Scenario: LoggerFactory needs to be disposed once the application shutdown so that dispose can be called on all the registered logger providers. This is so that these logger providers can flush any data that they might be holding.

@Tratcher @HaoK 
The proposal is to create  a DI scope for hosting engine services which get disposed once the hosting engine is being disposed.

**Comment by HaoK** [comment]
Is there anything other than the logger that is going to be disposed as part of this scope cleanup?  If not is it really worth creating a scope to dispose one service?

**Comment by davidfowl** [comment]
+1 to @HaoK's comment. Why would we create a scope just to dispose the ILoggerFactory.

**Comment by dougbu** [comment]
@Tratcher and I suspect aspnet/Mvc#3066 is related. Could fix that one in other ways but could also piggy-back on a solution here.
