### ISSUE TITLE
Move IHttpContextAccessor to Http.Abstractions

### ISSUE THREAD

**Issue by Tratcher** [aspnet/Hosting#324]
Identity depends on Hosting.Abstractions only for IHttpContextAccessor. Since this is only HttpContext related consider moving it to Http.Abstractions instead.

**Comment by HaoK** [comment]
For further context, identity only needs this to get ahold of the Request.Aborted CancellationToken to use by default...

**Comment by davidfowl** [comment]
Hmmmm is Microsoft.AspNet.Hosting.Abstractions too heavy? Or do we think it fits Http.Abstractions better?

**Comment by Tratcher** [comment]
I think Http.Abstractions is a better fit because the interface only deals with HttpContext.

**Comment by davidfowl** [comment]
What about the implementation? Does that move to Http?

**Comment by Tratcher** [comment]
It could, though I don't think the implementation is used outside of hosting service registration.

**Comment by davidfowl** [comment]
Should we just do this for beta7? Best to do these sorts of moves as early as possible. /cc @Eilon @muratg @glennc @DamianEdwards

**Comment by Eilon** [comment]
If you have time in betea7 among other work, please go ahead.

**Comment by davidfowl** [comment]
@Tratcher or @HaoK can one of you do this?

**Comment by HaoK** [comment]
I can probably take a look at this tomorrow since the big options change is blocked on MVC and identity ripple out anyways...  I don't that's going to make it into beta 7 so I can get this in

**Comment by davidfowl** [comment]
I'm guessing that not many repos will break as a result

**Comment by HaoK** [comment]
ad6e4b838a5daad0b9a36870e5d0e3f586e9ca06
