### ISSUE TITLE
Allow .json (and other) Configuration in Addition to .ini

### ISSUE THREAD

**Issue by Michael-DST** [aspnet/Hosting#326]
It would be nice to see configurations for hosting to be provided in other formats besides .ini.  As someone who is looking at a generated codebase for the first time, it is confusing to see both .json and .ini files used within a project (this is in addition to the .xml format that is used in the.xproj file, but that is another topic altogether :stuck_out_tongue:).

Additionally, .ini is a MSFT/Windows format, and this seems to fly in the face of the new direction of cross-platform/openness that the ASP.NET team (and other MSFT groups) are taking.

Ideally, .json would be used as the default file format.  .ini should be a supported format along with .xml and even .xaml (another MSFT-based format that I personally prefer).

It would be great to see a consistent (and industry standard -- whatever that is) file format used across all components in the ASP.NET5 system.

I personally would love to help out with this if at all possible.

This is also a related issue: https://github.com/aspnet/Tooling/issues/140  Ideally/ultimately I believe a Visual Studio Extension is required to display/define/edit  files in Visual Studio in a manner/format that makes the most sense and is of the preference of the developer/team.

**Comment by henkmollema** [comment]
There is also an issue and PR for JSON support: #269 / #270

**Comment by Michael-DST** [comment]
Ahhh!!  I am fail.  Thank you for that, @henkmollema!
