### ISSUE TITLE
set_HttpContext – LogicalSetData possibly expensive, needs investigation

### ISSUE THREAD

**Issue by DamianEdwards** [aspnet/Hosting#330]
![logicalsetdata](https://cloud.githubusercontent.com/assets/249088/9283153/5e1c5d00-4286-11e5-8241-7a9472d91f04.jpg)

**Comment by rynowak** [comment]
It's worth doing looking at the comparison with `AsyncLocal` here - which we can get by if-defing for coreclr/.net46

**Comment by davidfowl** [comment]
+1

**Comment by benaadams** [comment]
```AsyncLocal``` is also bad see #356

**Comment by benaadams** [comment]
Config opt-out would be nice; the ```AsyncLocal``` wouldn't necessarily be needed for webapi based servers where everything needed should be available through the invoke+httpcontext in the call chain parameters.

**Comment by rynowak** [comment]
MVC has the option to go back to not-using async local. We have some APIs that depend on on this today but they could use a scoped service instead - which was what we were doing before.

**Comment by benaadams** [comment]
Now on coreclr [```AsyncLocal``` cost has been reduced](https://github.com/dotnet/coreclr/issues/1591); on x64 it clocks in at a ```Dictionary``` (212 bytes) and ```ExecutionContext``` (32 bytes) so you'd need to go under that. 

However it will stay high on .net451 as is a different mechanism and [doesn't look like it will be reduced the same way on.net46](https://github.com/dotnet/coreclr/pull/1631).

The current coreclr x64 byte costs for 4k requests:

![set local bottom](http://aoa.blob.core.windows.net/aspnet/set-local-bottom.png)

**Comment by benaadams** [comment]
Would still want opt out, on by default because people would shoot themselves in foot; and able to switch off because if you aren't using it, doing nothing generally is faster than doing something

**Comment by Eilon** [comment]
We're doing something else in the interim. See https://github.com/aspnet/Hosting/issues/404 and the linked bugs.

**Comment by muratg** [comment]
Also see #405.  Closing this one.
