### ISSUE TITLE
Is there a way to parameterize and pass an instance of Startup rather than just the type?

### ISSUE THREAD

**Issue by Tratcher** [aspnet/Hosting#333]
_From @humblelistener on August 14, 2015 5:8_

The intention is to avoid creating a separate TestStartUp class rather - rather inject an instance of Configuration

Sample start up below,

```
public class Startup
{
  public IConfiguration Configuration {get; set;}

  public void Startup()
  {
    Configuration = new ConfigurationBuilder()
              .AddEnvironmentVariables()
              .Build();
   }

  public void ConfigureServices(IServiceCollection services)
  {
     //uses Configuration object to set up everything
  }
}
```

In the above implementation, if only 

`` TestServer.CreateBuilder().UseStartup(instanceOfStartup)  ``
is permitted

I can do this,

```
Startup instanceOfStartup= new Startup();
instanceOfStartup.Configuration = myOwnconfigurationWithKeysRequiredForTest;
//create a test server with 
TestServer.CreateBuilder().UseStartup(instanceOfStartup) 
```

Advantage: I dont have to maintain multiple startup class.

Does it make sense?

_Copied from original issue: aspnet/Home#831_

**Comment by Tratcher** [comment]
How about the `UseStartup(Action<IApplicationBuilder>)` overload? So your sample above becomes: `TestServer.CreateBuilder().UseStartup(instanceOfStartup.Configure)`

**Comment by humblelistener** [comment]
These overloads are limited - It wont work because

1. Configure method can be using just IApplicationBuilder or taking ILoggerFactory and so on as parameters

2. If I then have a configure services method - it complicates further because the overload takes a different signature of configureservices compared to expected one defined for configure

Instead of trying to draw two parallels - using StartUp class and StartUpMethods and having supported UseStartUp extension method, IMHO - it will be simple and easy to just start supporting taking an instance of StartUp thats got environment specific configuration state in it.

**Comment by humblelistener** [comment]
and this is what I have to do to keep it working - right now

```
var startup = new Startup();

//update configuration
startup.Configuration["XYZ_ENV_VAR"] = testEnvValue;

var Action<IApplicationBuilder> configureMethod = (app) => {
  app.UseMvc();
};

var configureServicesStartupMethodInfo = typeof(Startup).GetMethod("ConfigureServices");

var configureServicesMethod = new ConfigureServicesBuilder(configureServicesStartupMethodInfo).Build(startup);

using (var testServer = new TestServer(TestServer.CreateBuilder().UseStartup(configureMethod, configureServicesMethod)))
{
  ...
}
```

Doesn't feel good! any suggestions?

**Comment by HaoK** [comment]
Just to clarify the scenario you are trying to accomplish, you mostly want a way to configure a test to run with specific configuration (i.e. just tweak the configuration per test?)

**Comment by humblelistener** [comment]
that is right, I would prefer to keep the same startup while injecting a different configuration compared to having two startup files or having conditions in the start up file.

**Comment by JunTaoLuo** [comment]
You can now configure a `WebApplicationBuilder` to use a `Startup` class and create a `TestServer` from it in #525.

**Comment by muratg** [comment]
Moving this to Backlog as we will be in RC2 ask mode very soon.  If you feel strongly about this issue, please ping me.

**Comment by davidfowl** [comment]
Fixed with 8f5f8d28d00468725d9fd8dd95123f43d22f2c3c which is post RC2. You can add an `IStartup` class to the DI container and that will get resolved for app startup.

**Comment by davidfowl** [comment]
PS: it would look like this:

```
Startup instanceOfStartup= new Startup();
instanceOfStartup.Configuration = myOwnconfigurationWithKeysRequiredForTest;
//create a test server with 
var builder = new WebHostBuilder()
                      .ConfigureServices(services =>
                       {
                            services.AddSingleton<IStartup>(instanceOfStartup);
                       });
var server = new TestServer(builder);
```

**Comment by ohadschn** [comment]
And here's a nice blog post about the new `IStartup` interface: https://www.strathweb.com/2017/06/resolving-asp-net-core-startup-class-from-the-di-container/.
