### ISSUE TITLE
EventNotification support for Hosting

### ISSUE THREAD

**Issue by avanderhoorn** [aspnet/Hosting#334]
We want to add support for events via Microsoft.Framework.Notification to various components in Hosting that can be consumed in process by diagnostic tools.

To start with we want to include data/events with known tooling experiences built around them. This isn't a complete list, but includes things we can start on.

### Pipeline
 - Begin/End Request - HttpContext
 - Unhandled Exception - HttpContext, Exception

// @rynowak @Tratcher

**Comment by Tratcher** [comment]
This seems redundant, you can already put a data gathering middleware at the start of the pipeline (possibly via IStartupFilter) to get this kind of information.

**Comment by avanderhoorn** [comment]
Same argument could be made for the logging that is [there](https://github.com/aspnet/Hosting/blob/dev/src/Microsoft.AspNet.Hosting/Internal/HostingEngine.cs#L76-L80) at the moment. Leveraging Event Notifications means we can tap in in a much more consistent way and when you have multiple instrumentation providers all playing in the same sandpit, its not like you are going to end up with a bunch of profiling middleware cluttering your pipeline. Lastly, Event Notifications is going into the BLC and being leveraged by various parts of the platform (ADO, network, IO, Azure SDKs, etc), it seems weird that you can't access a notification for Begin/End Request.

**Comment by Eilon** [comment]
Derp, forgot about this bug. This is now a dup of https://github.com/aspnet/Hosting/issues/354, which is out for PR.

**Comment by avanderhoorn** [comment]
Sounds good!
