### ISSUE TITLE
Best practice to restart an application

### ISSUE THREAD

**Issue by csunali** [aspnet/Hosting#339]
I am wondering what could be the best implementation supporting the following case:

Some middlewares need to be configured within the Startup methods. These middlewares need to use configuration coming from Json configuration files.

If the configurations are already in place, that is fine but in some scenarios - for instance during installation of a web application - we might need to ask the user for some information. E.g.: database connection string, security middleware issuer and audience, etc.

Imagine an API controller that gets this request and serializes the new Json configuration into *.json files. The rest of the application is still not aware of any of these new values.

I tried implementing a shutdown procedure using IApplicationShutdown and it seems to work in a development environment. However, I am wondering if that would be the case in production. The shutdown process might be delayed if "something" is in use or any such unexpected behavior might occur.

My question in short is; how could I make sure that a web application is shutdown (to be restarted asap) immediately so that the startup methods get invoked once again?

**Comment by Tratcher** [comment]
IApplicationShutdown.RequestShutdown should work, except that it will wait for active requests to finish. Note that if you're running in IIS the app instance will stop accepting new requests, IIS will spin up a new instance as soon as the next request arrives (and re-run Startup), and this new instance does not affect the old instance that is in the process of shutting down.

**Comment by csunali** [comment]
Thank you @Tratcher. That provides the explanation I needed.

I have successfully implemented an API controller that has three actions:

`RequestShutdown`, `MonitorShutdownRequest` and `AcknowledgeShutdown`.

Everything seems to work.

Thank you.
