### ISSUE TITLE
Consider resolving IServiceScopeFactory once instead of per request in AutoRequestServicesStartupFilter

### ISSUE THREAD

**Issue by davidfowl** [aspnet/Hosting#347]
Seems like we don't need to resolve it per request.

/cc @pranavkm @HaoK @halter73 @rynowak

**Comment by halter73** [comment]
IServiceScopeFactory no longer takes an IServiceProvider as an argument, so using a single IServiceScopeFactory instance in the RequestServicesContainerMiddleware might lead to some subtle issues.

Basically, if httpContext.ApplicationServices is replaced by a middleware/filter earlier in the request pipeline, the IServiceScopeFactory won't create a scope nested from the replaced service provider.

I'm not sure if the httpContext.ApplicationServices would ever be replaced in practice, but I wanted to point out the *potential* functional impact.

**Comment by HaoK** [comment]
So it sounds like this change would be introducing a subtle bug then?

**Comment by halter73** [comment]
@HaoK That's what I'm afraid of. We might be able to fix the perf issue without changing functionality by changing the IServiceScopeFactory to take IServiceProvider as an argument to CreateScope.

**Comment by davidfowl** [comment]
@halter73 That's why I added you to this bug :smile: . We should discuss this change and how it affects 3rd parties like autofac.

**Comment by halter73** [comment]
@davidfowl Yeah. I want to retract my last comment. Making IServiceProvider an argument to CreateScope won't work for 3rd party containers.

**Comment by muratg** [comment]
Looks like it's not going to work... is this good to close?

**Comment by davidfowl** [comment]
Yes
