### ISSUE TITLE
[HttpPlatformHandler]: Allow retrieving the PID of the process via a DEBUG verb

### ISSUE THREAD

**Issue by davidfowl** [aspnet/Hosting#348]
When we launch a webserver behind httpplatformhandler in VS, VS needs to be able to get the pid so that it can attach the debugger. There are 2 scenarios:

- Launching IIS Express
- Launching in IIS

The way this works today is that vs sends a request with a DEBUG verb that gets the pid. We might need to support this when running  in a particular mode.

We need to flesh this out

**Comment by Tratcher** [comment]
Hosting will automatically handle a request that the application never sees? Hmm. This should only be enabled in Development mode.

**Comment by davidfowl** [comment]
Yes

**Comment by Tratcher** [comment]
What if this was inverted? Have a option that would make Hosting take some action to inform interested parties that the server was ready. E.g. make an HTTP request to a given url, write to an event log or a named pipe, etc..

**Comment by davidfowl** [comment]
We can closes this. The Http platform handler will  allow passing the port to forward to. This means VScan launch the web server with the required port

**Comment by Tratcher** [comment]
Nevermind, we still need to do this.

**Comment by davidfowl** [comment]
Should we put this in the middleware?

**Comment by Tratcher** [comment]
By all means.

**Comment by davidfowl** [comment]
The only problem is rhat debugging won't work in vs without it which is a bit insane 😞

**Comment by Tratcher** [comment]
Well, start in the middleware and push it down later if it turns out terrible.

**Comment by Tratcher** [comment]
On a related note, how can they debug startup errors? The FailSafeLoader will help, but then then Hosting will have to implement the DEBUG logic.

How about server or hosting config issues? I think the debugger would have to attach very early to debug these.

**Comment by Tratcher** [comment]
This needs to be fixed a different way: https://github.com/aspnet/dnx/issues/2810
