### ISSUE TITLE
[HttpPlatformHandler]: Forward common headers from reverse proxy

### ISSUE THREAD

**Issue by davidfowl** [aspnet/Hosting#349]
This bug is to track the work that needs to happen so that items forwarded from httpplatformhandler show up in the user's application.

There are several parts to this:

- Windows Auth (coming soon)
- Client certs (not yet available)
- Https scheme

We could do some of it in middleware (like WindowsAuth) but that would mean it wouldn't work out of the box. It could also be in the template by default so that we don't couple to the HttpPlatformHandler in any of our core components.

**Comment by Tratcher** [comment]
Also of interest are the remote ip & port and the reverse proxy public IP & port. I'd recommend doing it all in middleware.

Eventually we'll need the TLS token binding.

**Comment by davidfowl** [comment]
I think scheme is the only one we'd want to support by default.

**Comment by Tratcher** [comment]
HttpPlatformHandler needs to forward them all, it's up to the app how many forwarders they check.

**Comment by davidfowl** [comment]
Well let the user experience drive that. This is our new ootb experience for IIS and it can't be degraded in obvious ways. We'll discuss it in the design meeting

**Comment by Tratcher** [comment]
A few other interop questions:
100-continue support
http/2 termination (should just work, it happens in http.sys)
client disconnects

**Comment by davidfowl** [comment]
We decided to make this a separate middleware `UseHttpPlatformHandler()`.

**Comment by rubenprins** [comment]
What about nested applications/child paths? Is that still something that will be supported out of the box? Or will we need to configure the application's base path (a.k.a. `~/`) manually?

**Comment by davidfowl** [comment]
Won't be supported out of the box. I haven't tried it myself with the platform handler.

**Comment by Tratcher** [comment]
@Eilon @muratg Let's create a new repo for this: `IIS` or `IISIntegration`. I think it will just replace Helios in the build hierarchy.

**Comment by Tratcher** [comment]
@davidfowl  repo name?

**Comment by davidfowl** [comment]
@Tratcher move this bug over

**Comment by Tratcher** [comment]
This issue was moved to aspnet/IISIntegration#2
