### ISSUE TITLE
Print out the environment on the command line when launching hosting

### ISSUE THREAD

**Issue by davidfowl** [aspnet/Hosting#351]
So the relevant information when booting up is:

- Port
- Environment

http://www.tugberkugurlu.com/archive/setting-ihostingenvironment-isdevelopment-as-true-in-an-asp-net-5-application

**Comment by Tratcher** [comment]
RE: https://github.com/aspnet/Hosting/issues/328

**Comment by muratg** [comment]
@Tratcher straightforward enough for Beta 8?

**Comment by Tratcher** [comment]
Should be. I can do it in my current WriteLine PR.

**Comment by davidfowl** [comment]
@tugberkugurlu merry christmas

**Comment by tugberkugurlu** [comment]
@davidfowl nice one! :fireworks:
