### ISSUE TITLE
Allow ContextAccessor.HttpContext be config opt-out

### ISSUE THREAD

**Issue by benaadams** [aspnet/Hosting#356]
Allow ContextAccessor.HttpContext be config opt-out-able (i.e. on by default)

For example a purely WebApi based site or one with no auth might not have need for a .Current equivalent as HttpContext  is passed in to each stage.

---
*Was* **High alloc setting ContextAccessor.HttpContext**
At https://github.com/aspnet/Hosting/blob/dev/src/Microsoft.AspNet.Hosting/Internal/HostingEngine.cs#L94 the ```contextAccessor``` is defined at the server instance level but its ```HttpContext``` property is set per request in the callback closure:

````csharp
// --- defined here ----
var contextAccessor = _applicationServices.GetRequiredService<IHttpContextAccessor>();
var server = ServerFactory.Start(_serverInstance,
    async features =>
    {
        var httpContext = contextFactory.CreateHttpContext(features);
        httpContext.ApplicationServices = _applicationServices;
        var requestIdentifier = GetRequestIdentifier(httpContext);

        using (logger.BeginScope("Request Id: {RequestId}", requestIdentifier))
        {
            // --- context set here ---
            contextAccessor.HttpContext = httpContext;
            await application(httpContext);
        }
    });
````

This will mean every request is changing it and if more than one request is happening in parallel only one of them will have the right value?

Not sure what it's used for though.

**Comment by tmds** [comment]
The IHttpContextAccessor can be used do retrieve the HttpContext via Dependency Injection.
The implementation handles the per 'context' part, see [HttpContextAccessor](https://github.com/aspnet/HttpAbstractions/blob/8487e42a6874eef8e0cd85b4c9f44eb6f9ec330e/src/Microsoft.AspNet.Http/HttpContextAccessor.cs)

I don't know what the benefit is of instantiating this globally vs per request.

**Comment by Tratcher** [comment]
HttpContextAccessor uses thread local storage, so parallel execution should not be a problem.

**Comment by tmds** [comment]
@Tratcher is there a benefit compared to per request instantiation?

**Comment by benaadams** [comment]
Hmm, looking at the code, won't TLS kill the fast path for every async/await on 451 as it will no longer be a default execution context?

I assume AsyncLocal in core50 is more well behaved; so should be ok.

**Comment by Tratcher** [comment]
It's designed to replace the static HttpContext.Current by letting you inject the service at startup into components that don't get HttpContext passed to them directly.

**Comment by tmds** [comment]
@Tratcher ok, thanks

**Comment by benaadams** [comment]
Hmm, it allocates 680k for per 2000 requests in coreclr

![hc-0](http://aoa.blob.core.windows.net/aspnet/hc-0.png)

**Comment by benaadams** [comment]
Raised issue in coreclr for this: https://github.com/dotnet/coreclr/issues/1591

**Comment by tmds** [comment]
@benaadams Perhaps you can check using a benchmark (https://github.com/aspnet/benchmarks) what the penalty is for this allocation?

**Comment by benaadams** [comment]
@tmds this is the benchmark though not using Kestrel; however everything other than the ```await``` line is the regular aspnet stack and the plaintext benchmark

**Comment by tmds** [comment]
@benaadams You could check how many requests per seconds can be handled when providing the contextAccessor vs not providing it. It would be a way to to assess the performance impact of this allocation at the webserver level.

**Comment by benaadams** [comment]
Could setting the ContextAccessor.HttpContext be an opt-out-able (i.e. on by default); for example a purely WebApi based site or one with no auth might not have need for a ```.Current``` equivalent

**Comment by muratg** [comment]
Please see #405.  Closing this one.
