### ISSUE TITLE
Rename IApplication

### ISSUE THREAD

**Issue by Tratcher** [aspnet/Hosting#357]
This new type's name is slightly too generic. How about IWebApplication?

**Comment by davidfowl** [comment]
Does it need to be an interface? We should just make it a Poco.

Throwing out some names:

- `HostedApplication`
- `WebApplication`

**Comment by Tratcher** [comment]
It's returned from IHostingEngine.Start(), so an interface seems appropriate.

**Comment by davidfowl** [comment]
I disagree. It's a poco with 2 properties, there's no behavior. Nothing to be gained from making it an interface.

**Comment by Tratcher** [comment]
It also handles the shutdown via IDisposable.

**Comment by HaoK** [comment]
HostingApplication to match HostingEngine?

**Comment by HaoK** [comment]
Name also could relate to Start, like: RunningApplication

**Comment by muratg** [comment]
We need to decide on the name, and if it's going to be a POCO or an Interface.

**Comment by JunTaoLuo** [comment]
@Tratcher @davidfowl After #395 we will have 3  classes with similar names: `WebApplication`, `Application` and `HostingApplication`. This could be confusing as they have nothing to do with each other. 

Also, is there a final decision on POCO vs Interface? Whatever we decide, `HostingEngine` and `Application` should be the same to remain consistent with the other.

**Comment by JunTaoLuo** [comment]
@Tratcher @davidfowl Need to decide between POCO and Interface.

**Comment by JunTaoLuo** [comment]
Will be addressed in #525
