### ISSUE TITLE
[HttpPlatformHandler]: Support HTTP_PLATFORM_PORT env variable as an address

### ISSUE THREAD

**Issue by davidfowl** [aspnet/Hosting#358]
The HttpPlatformHandler passes the port via the env variable `HTTP_PLATFORM_PORT`.

**Comment by davidfowl** [comment]
We should also support port

/cc @Tratcher

**Comment by Tratcher** [comment]
Have Hosting read HTTP_PLATFORM_PORT and add it to IServerAddressesFeature.Addresses?

**Comment by davidfowl** [comment]
Yep

**Comment by Tratcher** [comment]
Actually, we can do it in the new UseHttpPlatformHandler extension.

**Comment by davidfowl** [comment]
We decided to put this in hosting

**Comment by Tratcher** [comment]
Move the default address from Kestrel to hosting and make it http://localhost:5000/. Make HTTP_PLATFORM_PORT into http://localhost:port/
