### ISSUE TITLE
Environment Detection Feature

### ISSUE THREAD

**Issue by louislewis2** [aspnet/Hosting#366]
The environment detection features are extremely useful. I am specifically referring too:
IsDevelopment(), IsProduction() and IsEnvironment().

My question however is based on my current development where I thought I might make use of this feature, however it is only available off of IHostingEnvironment. Which I find puzzling. Would it not make sense to provide these extension methods off the IApplicationEnvironment type, which is available in both web and console applications for example? I am also sure that like me, other developers might want environment detection regardless of how they are running / hosting.

We and I am sure other fellow developers are writing modules / class libraries that run in both a web and console environment, where console is overloaded meaning windows service etc.. 

I think environment detection might be more "reusable" where it an extension method off the IApplicationEnvironment type.

As a workaround I can create a HostingEnvironment instance and register it in the service collection so that the type and extension method is available throughout the code base, but this feels incorrect.

**Comment by muratg** [comment]
Interesting suggestion. Due to the (current) nature of the layering in the stack, IApplicationEnvironment is a DNX level concept (Console apps and class libraries) while IHostingEnvironment (mainly Web apps and APIs) is a Hosting level one.  I suppose people can write Windows Services on DNX and may want different behavior based on the environment but I wonder if it's worth complication the situation for all other DNX apps.

**Comment by louislewis2** [comment]
Interesting that you should mention running an application as a Windows Service on DNX, as this is something we are testing out. However more than that, as we are writing / porting existing applications onto the new stack, we internally would like to make sure that some of our components can run in any environment and thus far we have had great success at this. We then wanted to be able to leverage upon the environment detection feature and stumbled into what led me to ask this question.

I understand that IHotsingEnvironment is particularly aimed at web apps as you noted, but IApplicationEnvironment is a "common" across more than just web apps. I therefore suggested that an application can be in development or staging regardless of the application type or host type.

As I understand it, the methods in question are all extension methods, could it not be possible to implement them against IApplicationEnvironment?

**Comment by davidfowl** [comment]
We have no plans to push environments that low in the stack. If anything it would be another package that provides that experience similar to hosting for ASP.NET apps

**Comment by louislewis2** [comment]
I would accept that as a resolution any day.

**Comment by muratg** [comment]
Closing, as we won't be doing this.
