### ISSUE TITLE
[Perf] High Allocator LoggingScope when no loggers

### ISSUE THREAD

**Issue by benaadams** [aspnet/Hosting#367]
Using works with null references, so this is simpler than outlined below; added change to logging to improve efficiency.

---
Creating a scope is expensive (at benchmarking speeds) and the techempower benchmarks specify in [general requirements](https://www.techempower.com/benchmarks/#section=code) item 2:

> All test implementations **must disable all disk logging**. For many reasons, we expect all tests will run without writing logs to disk. Most importantly, the volume of requests is sufficiently high to fill up disks even with only a single line written to disk per request. Please disable all forms of disk logging. We recommend but do not require disabling console logging as well.

For fair comparison, only create the logging scope if logging is enabled:

Add ```LogLevel``` of ```None = 7```? 

Change the following from:

```csharp
var logger = _applicationServices.GetRequiredService<ILogger<HostingEngine>>();
...
var server = ServerFactory.Start(_serverInstance,
    async features =>
    {
        try
        {
            using (logger.BeginScope("Request Id: {RequestId}", requestIdentifier))
            {
                contextAccessor.HttpContext = httpContext;
                await application(httpContext);
            }
        }
        catch (Exception ex)
        {
            if (telemetrySource.IsEnabled("Microsoft.AspNet.Hosting.UnhandledException"))
            {
                telemetrySource.WriteTelemetry("Microsoft.AspNet.Hosting.UnhandledException", new { httpContext = httpContext, exception = ex });
            }

            throw;
        }
```

To something similar to:

```csharp
var logger = _applicationServices.GetRequiredService<ILogger<HostingEngine>>();
...
var isLogging = logger.IsEnabled(LogLevel.Critical); // ? not sure about how not logging is checked
var server = ServerFactory.Start(_serverInstance,
    async features =>
    {
        ILogger loggerScope;
        try
        {
            if (isLogging) 
            {
                loggerScope = logger.BeginScope("Request Id: {RequestId}", requestIdentifier);
            }

            contextAccessor.HttpContext = httpContext;
            await application(httpContext);
        }
        catch (Exception ex)
        {
            if (telemetrySource.IsEnabled("Microsoft.AspNet.Hosting.UnhandledException"))
            {
                telemetrySource.WriteTelemetry("Microsoft.AspNet.Hosting.UnhandledException", new { httpContext = httpContext, exception = ex });
            }

            throw;
        }
        finally
        {
            if (loggerScope != null) loggerScope.Dispose();
        }
```

Ensure having no local logging scope doesn't cause issues.

**Comment by benaadams** [comment]
For reference 437 kBytes for 4k requests; or 672 Mbytes/s for 6M rps; or 40 GBytes/min for the GC to clean up.

![logging scope](http://aoa.blob.core.windows.net/aspnet/logger-beginscope-bytes.png)

**Comment by benaadams** [comment]
Would be resolved by https://github.com/aspnet/Logging/pull/254 and changing:

```using (logger.BeginScope("Request Id: {RequestId}", requestIdentifier))```

to

```using (logger.BeginScope($"Request Id: {requestIdentifier.ToString()}"))```

**Comment by benaadams** [comment]
Taking it a little further and changing
```using (logger.BeginScope("Request Id: {RequestId}", requestIdentifier))```
to
```using (logger.IsEnabled(LogLevel.Critical) ? logger.BeginScope("Request Id: {RequestId}", requestIdentifier) : null)```
with this change reduces it to zero allocs
![post-allocs](http://aoa.blob.core.windows.net/aspnet/logging-post-allocs-test.png)
And zero bytes
![post-bytes](http://aoa.blob.core.windows.net/aspnet/logging-post-bytes-test.png)

**Comment by benaadams** [comment]
@davidfowl please reopen; commit [Reduce logging overhead in hosting]( https://github.com/aspnet/Hosting/commit/f37375f43cd9e49ebcd61b62130d3455c8d41944) has brought this back but with even higher byte allocation.

For 2003 requests 

Drill down on Issue #288
Measurements post PR #287

Allocations (Same as previous)

![hc-new](http://aoa.blob.core.windows.net/aspnet/hc-new-alloc.png)

Bytes (256kB per 4k -> 352kB per 4k; up 96kB)

![hc-new](http://aoa.blob.core.windows.net/aspnet/hc-new.png)

**Comment by lodejard** [comment]
Too many cross-references, history, and screen shots! :) I can't tell how much of this is from before the current changes, or what the recommendation is.

Can we discuss this in a more direct way?

**Comment by davidfowl** [comment]
@benaadams @lodejard this still relevant? If so reopen

**Comment by benaadams** [comment]
Still features (just under highlighted line)

![After-QueueUserWorkItemCallback](http://aoa.blob.core.windows.net/aspnet/quwi.png)

Don't know how urgent it is

**Comment by benaadams** [comment]
Also other than `string` and `QUWICDC` is the only thing on that list that can't be pooled (am guessing RequestServicesFeature can be optionally removed)

**Comment by davidfowl** [comment]
@benaadams what are those strings?

**Comment by benaadams** [comment]
Header, host, path values - is what I did the StringCache for back in the day https://github.com/aspnet/KestrelHttpServer/pull/411#issue-118097489
