### ISSUE TITLE
Add/Update logging in hosting

### ISSUE THREAD

**Issue by rynowak** [aspnet/Hosting#374]
From offline logging discussion:

Add Verbose logging where it can be useful for debugging
- Time box to 2 dev-days maximum (across all of k-core)
- Use EventIds at each logging statement
- Update any existing logging to include an EventId

Relevant logging points we want to include for sure:

```
    Hosting:
        -Request - Information
        -Response - Information
        -Startup - Information
        -Shutdown - Information
```

**Comment by muratg** [comment]
cc @Tratcher (also see the StaticFiles one)
