### ISSUE TITLE
[Testing] Provide dynamic port allocation for the server tests

### ISSUE THREAD

**Issue by Tratcher** [aspnet/Hosting#378]
Right now the tests in IISIntegration and ServerTests use hard-coded port numbers. Generate these dynamically instead.

Note that the IIS Express HTTPS tests require a specific port range that is pre-configured with a test certificate.

**Comment by Tratcher** [comment]
Punting. This hasn't caused us any issues yet, it's just a long term maintenance item.

**Comment by ryanbrandenburg** [comment]
As a datapoint, @anurse and I believe this caused a build failure today, so it is still happening.

**Comment by anurse** [comment]
Actually I don't think this bug is the right place for this. I'll find the right one or create a new one. This bug was actually resolved, we now allocate ports dynamically, just buggily :)
