### ISSUE TITLE
HostingEngine.Start shouldn't get request ID unless it begins a scope

### ISSUE THREAD

**Issue by AspNetSmurfLab** [aspnet/Hosting#392]
Generating request ID is expensive so `HostingEngine.Start` shouldn't be grabbing the request ID from the feature collection unless it's actually going to call `BeginScope`.

Effectively we need to merge line 99 into line 110.

by @DamianEdwards

**Comment by benaadams** [comment]
Had a go at this previously https://github.com/aspnet/Hosting/commit/ed1fd4a2e8143b0213b2630ab6834fe207fbd213 but it made some tests upset; would need to move some of the code out and into the feature, with the lazy eval

**Comment by DamianEdwards** [comment]
Yeah we have a changed planned in Logging to make the entire `BeginScope` call free until somebody actually tries to log so this will likely get changed as part of that.

**Comment by benaadams** [comment]
Pushing the RequestIdentifierFeature up the chain into the HttpContext gets you some of the way there: https://github.com/benaadams/HttpAbstractions/commit/e3b8f1a8ce0cff0059ecc9a63e12baf6b6a6db69

**Comment by benaadams** [comment]
Should be resolved by  #394 but needs the upstream commit; may need test fixes.

**Comment by muratg** [comment]
Just talked to @lodejard.  Moving is issues to RC2.

**Comment by pakrym** [comment]
Was solved by @loudej in https://github.com/aspnet/Hosting/commit/f37375f43cd9e49ebcd61b62130d3455c8d41944
