### ISSUE TITLE
Update WebHostBuilder.BuildHostingServices to flow IRuntimeServices

### ISSUE THREAD

**Issue by PinpointTownes** [aspnet/Hosting#393]
Currently, `BuildHostingServices` does not re-inject `IRuntimeServices` in the services container it uses for the hosting block: https://github.com/aspnet/Hosting/blob/dev/src/Microsoft.AspNet.Hosting/WebHostBuilder.cs#L81-L89

To work around this limitation, we have to use `CallContextServiceLocator` to resolve `IRuntimeServices`: https://github.com/aspnet-contrib/AspNet.Hosting.Extensions/blob/dev/src/AspNet.Hosting.Extensions/HostingExtensions.cs#L218-L224

/cc @MartinJohns @Tratcher

**Comment by davidfowl** [comment]
We actually plan to deprecate and remove CallContextServiceLocator. There'll be a nicer way to do this.

**Comment by davidfowl** [comment]
@PinpointTownes The plan is to expose an extension method AddPlatformServices that you can call.

**Comment by muratg** [comment]
@davidfowl Are we doing an extension method or expose it via a static? (Or both?) 

https://github.com/aspnet/Hosting/issues/402

**Comment by davidfowl** [comment]
Extension method only.

**Comment by pakrym** [comment]
@davidfowl reopen if this is something we will actually do
