### ISSUE TITLE
Revisit IServerFactory.Start

### ISSUE THREAD

**Issue by davidfowl** [aspnet/Hosting#395]
Does it really need to pass back in the IFeatureCollection returned in Initialize?

```
IDisposable Start(IFeatureCollection serverFeatures, Func<IFeatureCollection, Task> application);
```

Why not just:

```
IDisposable Start(Func<IFeatureCollection, Task> application);
```

The current design does allow you to pass in different instances but I'm not sure if that's a goal since we don't use it that way currently.

**Comment by Tratcher** [comment]
Well as a factory it can be used more than once (not that we actually do this at the moment). Maybe a factory isn't the pattern you want here? Removing that param makes it a statefull single use class. At that point you would just make the factory itself disposable rather than returning anything from start.

**Comment by davidfowl** [comment]
Thats what I'm wondering. I know the pattern allows for that but I'm not sure we use it or plan to use it anywhere that way. I know this stuff came from katana but I'd like to understand if we ever plan to use it in that way in the current stack.

/cc @loudej @lodejard

**Comment by davidfowl** [comment]
```C#
public interface IServerFactory : IDisposable
{
    IFeatureCollection Initialize(IConfiguration configuration);
    void Start(Func<IFeatureCollection, Task> application);
}
```

I'm not sure. I guess it does feel a bit off that some of those things are inferred (e.g. the fact that the returned IFeatureCollection should be used later by Start?)

**Comment by Tratcher** [comment]
How about:
```c#
public interface IServer : IDisposable
{
    IFeatureCollection Features { get; }
    void Initialize(IConfiguration configuration);
    void Start(Func<IFeatureCollection, Task> application);
}
```

Note initialize only exists in this model because we don't have a good way of getting the IConfiguration into the DI constructor.

**Comment by davidfowl** [comment]
What about:

```C#
public interface IServerFactory
{
    IServer CreateServer(IConfiguration configuration);
}
```

```c#
public interface IServer : IDisposable
{
    IFeatureCollection Features { get; }
    void Start(Func<IFeatureCollection, Task> application);
}
```

**Comment by Tratcher** [comment]
*shrug* we can try it. I don't think it solves any issues, it's just API cleanup.

**Comment by davidfowl** [comment]
This whole issue is about API cleanup. I was demoing the interface recently and decided to file this issue because I thought the stateless nature of the server factory was a little weird.

**Comment by Eilon** [comment]
After discussion with @lodejard @davidfowl , slight change:

```C#
public interface IServerFactory
{
    IServer CreateServer(IConfiguration configuration);
}
```

```c#
public interface IServer : IDisposable
{
    IFeatureCollection Features { get; }
    void Start(RequestDelegate requestDelegate);
}
```

**Comment by Tratcher** [comment]
RequestDelegate takes an HttpContext, not an IFeatureCollection. Hosting creates the HttpContext, not  the server.

**Comment by Eilon** [comment]
I think @davidfowl or @lodejard requested that change from IFeatureCollection to HttpContext, but I didn't quite get why.

**Comment by davidfowl** [comment]
We're unifying the signatures. Everything is HttpContext now and the feature collection becomes and implementation detail of the HttpContextFactory. The layers have been mushed.

**Comment by HaoK** [comment]
This looks pretty similar to all of the builders we have

Maybe?
```
public interface IServerBuilder
{
    IServer Build(IConfiguration configuration);
}
```

**Comment by davidfowl** [comment]
Except there's nothing to hang off of it.

**Comment by HaoK** [comment]
So the distinction is that Builder means a fancy Factory that has knobs/settings that you can adjust before calling build?

**Comment by davidfowl** [comment]
Yah. We aren't actually building/configuring anything just making a sever instance

**Comment by JunTaoLuo** [comment]
merged to dev

**Comment by JunTaoLuo** [comment]
The new proposal is as follows:

```
namespace Microsoft.AspNet.Server.Abstractions
{
    public interface IHttpApplication<THttpContext>
    {
        THttpContext CreateHttpContext(IFeatureCollection contextFeatures);
        Task InvokeAsync(THttpContext httpContext);
        void DisposeHttpContext(THttpContext httpContext);
    }

    public interface IServerFactory
    {
        IServer CreateServer(IConfiguration configuration);
    }

    public interface IServer : IDisposable
    {
        void Start<THttpContext>(IHttpApplication<THttpContext> app);
    }
}

public class HostingApplication : IHttpApplication<HttpContext>
{
    HttpContext CreateHttpContext(IFeatureCollection contextFeatures) { ... }
    Task InvokeAsync(HttpContext httpContext) { ... }
    void DisposeHttpContext(HttpContext httpContext) { ... }
}
```

cc @davidfowl @lodejard @Tratcher @troydai @rynowak

**Comment by davidfowl** [comment]
Updated the spec

**Comment by JunTaoLuo** [comment]
Updated the spec

**Comment by JunTaoLuo** [comment]
While looking to adapt the Kestrel server to the new spec, I found that the generic typing is causing us to make many function calls/callbacks to become generic, see https://github.com/aspnet/KestrelHttpServer/commit/3077b96eb3a90f1503b7ae4309912fe899c6f179. Maybe we should just use object instead? 

cc @halter73 @Tratcher @davidfowl @loudej @rynowak

**Comment by halter73** [comment]
:+1: for using object over trying to flow the generic parameter.

**Comment by JunTaoLuo** [comment]
Moar updates to the design! Instead of using object, we'll use generics but modify Kestrel's design a bit to make the generic propagation less viral.
