### ISSUE TITLE
Regression: 500 returned for all requests when running under Nowin

### ISSUE THREAD

**Issue by borgdylan** [aspnet/Hosting#397]
After updating all my packages to the latest ones in the aspnetvnext feed (myget), I am getting a 500 return code for each request. My middleware seems to not be running any more either. I can only see the headers added by Nowin itself.

**Comment by borgdylan** [comment]
The issue is kind of fixed by wrapping the OwinFeatureCollection inside a FeatureCollection. However the app will hang under heavy traffic.

**Comment by Tratcher** [comment]
Dupe: https://github.com/aspnet/HttpAbstractions/issues/431
