### ISSUE TITLE
ConfigureServices can take at most a single IServiceCollection parameter.

### ISSUE THREAD

**Issue by VZhuck** [aspnet/Hosting#398]
As  I understand from issue 2790 I should use kestrel server to run my dnx allpication,
However I get following issue: 
"
Application startup exception: System.InvalidOperationException: ConfigureServices can take at most a single IServiceCollection parameter.
   at Microsoft.AspNet.Hosting.Startup.ConfigureServicesBuilder..ctor(MethodInfo configureServices)
   at Microsoft.AspNet.Hosting.Startup.StartupLoader.FindConfigureServicesDelegate(Type startupType, String environmentName)
   at Microsoft.AspNet.Hosting.Startup.StartupLoader.LoadMethods(Type startupType, IList`1 diagnosticMessages)
   at Microsoft.AspNet.Hosting.Internal.HostingEngine.EnsureStartup()
   at Microsoft.AspNet.Hosting.Internal.HostingEngine.EnsureApplicationServices()
   at Microsoft.AspNet.Hosting.Internal.HostingEngine.BuildApplication()
Hosting environment: Production
Now listening on: http://localhost:5004
Application started. Press Ctrl+C to shut down.
"

My Project.jason is following: 
{
  "webroot": "wwwroot",
   "userSecretsId": "aspnet5-TestWebApp-222b480d-3e1f-4032-bd97-816c4ce5c2f2",
  "src" :  "src",
  "version": "1.0.0-*",

  "dependencies": {
    "Microsoft.AspNet.Server.Kestrel": "1.0.0-*",
    "Microsoft.AspNet.Server.IIS": "1.0.0-beta8-*",
    "Microsoft.AspNet.Server.WebListener": "1.0.0-rc1-*",

    "Microsoft.AspNet.Mvc": "6.0.0-rc1-*",
    "Microsoft.AspNet.Mvc.TagHelpers": "6.0.0-rc1-*",

    "Microsoft.AspNet.Diagnostics": "1.0.0-rc1-*",
    "Microsoft.AspNet.Diagnostics.Entity": "7.0.0-rc1-*",

    "Microsoft.AspNet.StaticFiles": "1.0.0-rc1-*",

    "Microsoft.Framework.Configuration.Abstractions": "1.0.0-rc1-*",
    "Microsoft.Framework.Configuration.Json": "1.0.0-rc1-*",
    "Microsoft.Framework.Configuration.UserSecrets": "1.0.0-rc1-*",
    "Microsoft.Framework.Logging": "1.0.0-rc1-*",
    "Microsoft.Framework.Logging.Console": "1.0.0-rc1-*",
    "Microsoft.VisualStudio.Web.BrowserLink.Loader": "14.0.0-rc1-*"
  },

  "commands": {
    "web": "Microsoft.AspNet.Hosting --config hosting.ini",
    "kestrel": "Microsoft.AspNet.Hosting --server Microsoft.AspNet.Server.Kestrel --server.urls http://localhost:5004"
  
  },...

Startup.cs:
public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
            

            // Configure the HTTP request pipeline.
            app.UseStaticFiles();
            app.UseMvc();
        }

Do you have any up to date sample dnx application to follow your changes by example.

**Comment by davidfowl** [comment]
That error is pretty specific can you show your entire Startup.cs file?

**Comment by VZhuck** [comment]
Here is complete setup file:
 public class Startup
    {
        // For more information on how to configure your application, visit http://go.microsoft.com/fwlink/?LinkID=398940
        public void ConfigureServices(IServiceCollection services)
        {
            
        }

        public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
            

            // Configure the HTTP request pipeline.
            app.UseStaticFiles();
            app.UseMvc();
        }
    }

**Comment by VZhuck** [comment]
I have updated configuration and issue has been fixed.
xproj configuration example can be found here: https://github.com/aspnet/Home/blob/dev/samples/latest/HelloWeb/
