### ISSUE TITLE
Expose access to current service provider via a static

### ISSUE THREAD

**Issue by davidfowl** [aspnet/Hosting#402]
For those cases where it's hard to get to context. It won't be something we advertise but it'll be available for those people that love statics :smile:. https://github.com/aspnet/Hosting/issues/30

**Comment by davidfowl** [comment]
Related to https://github.com/aspnet/dnx/issues/2927

**Comment by henkmollema** [comment]
Is there some kind of design for this?

**Comment by davidfowl** [comment]
It's going to be something awful, just like the CallContextServiceLocator.

**Comment by henkmollema** [comment]
Haha, sounds great! :ok_hand:

**Comment by davidfowl** [comment]
Or we may punt this and say you need to provide us with your own static. Hmmmm

**Comment by henkmollema** [comment]
Can we use `services.BuildServiceProvider` for this?

**Comment by muratg** [comment]
@davidfowl  Punting.  Bring it back if necessary.

**Comment by davidfowl** [comment]
Moving this one away from @pakrym until details are figured out.

**Comment by muratg** [comment]
:+1: adding `needs design` label

**Comment by muratg** [comment]
@davidfowl Do you want this in V1?  If so, it needs to happen in RC2

**Comment by davidfowl** [comment]
Yea, we're not going to do this

**Comment by javiercn** [comment]
Things like https://github.com/aspnet/mvc/issues/4014 require this to access IApplicationEnvironment without having to change the public API of AddMvc and similar.

In general, any framework that needs to do any sort of discovery requires these services (Like discover controllers, discover views, etc).

@davidfowl @rynowak
