### ISSUE TITLE
Add IHttpContextFactory.DisposeHttpContext(...) and call it from the end of the request

### ISSUE THREAD

**Issue by Eilon** [aspnet/Hosting#404]
Discussed with @lodejard and @davidfowl :

Change `IHttpContextFactory` to have two methods:

```c#
    public interface IHttpContextFactory
    {
        HttpContext Create(IFeatureCollection featureCollection); // just renamed
        void Dispose(HttpContext httpContext); // add this
    }
```

Need to call the new `Dispose` method from the end of the request from within the *server*, which is where the context was created.

**Comment by Tratcher** [comment]
This affects the layering of multiple APIs and packages:
- IHttpContextFactory should move from the Hosting package to Hosting.Server.Abstractions if we're maintaining the ability to author servers without a direct dependency on Hosting.
- This and #395 negate any separation between Http.Abstractions and Http.Features, both are now required in all server and middleware scenarios so we might as well merge them.

**Comment by davidfowl** [comment]
Yah that's what I said :)

**Comment by davidfowl** [comment]
@Tratcher as part of this we should probably move IHttpContextFactory into HttpAbstractions (maybe with HttpContext in abstractions.)

**Comment by Tratcher** [comment]
I think Hosting.Server.Abstractions is more appropriate, it's a service only used in association with servers.

**Comment by benaadams** [comment]
Devil's advocate ```IDisposable``` ```HttpContext``` that calls ```IHttpContextFactory.Dispose(this)```? 

**Pro** 
```csharp
using (var httpContext =  httpContextFactory.Create(featureCollection))
{
  ...
}
```
rather than 
```csharp
var httpContext = httpContextFactory.Create(featureCollection);
try 
{
 ...
} 
finally 
{
   httpContextFactory.Dispose(httpContext);
}
```
**Con**
Puts a dependency and reference in to ```HttpContext``` so may not be good

```csharp
HttpContext(IHttpContextFactory factory, IFeatureCollection featureCollection)
{
   _factory = factory;
   _featureCollection = featureCollection;
}

Dispose()
{
   _factory.Dispose(this);
}
```
Also may mean people might think they can do multi-dispose which would be bad if the factory was doing pooling.

**Comment by Tratcher** [comment]
@benaadams Yeah, I don't recommend it as there's only one place in the stack where it's good/safe to dispose. You don't want other people thinking they can dispose it.

**Comment by benaadams** [comment]
@Tratcher good enough reason for me :+1: As you say might end up with people trying to dispose it all over the place; just thought I'd bring it up

**Comment by JunTaoLuo** [comment]
Implemented in https://github.com/aspnet/HttpAbstractions/pull/452
