### ISSUE TITLE
Assign IHttpContextAccessor in the default implementation of IHttpContextFactory

### ISSUE THREAD

**Issue by davidfowl** [aspnet/Hosting#405]
As part of https://github.com/aspnet/Hosting/issues/404, we should be setting the IHttpContextAccessor in CreateHttpContext

**Comment by benaadams** [comment]
Is ```CreateHttpContext``` per request or per connection? Per connection is fine; but per request setting an ```AsyncLocal``` incurs a ```new Dictionary``` cost per set.

**Comment by davidfowl** [comment]
It's per request. Nothing is changing there. We're just moving things around so that application code can remove it if required.

**Comment by benaadams** [comment]
Ah, kk

**Comment by JunTaoLuo** [comment]
merged to dev
