### ISSUE TITLE
Membership - IHttpContextAccessor missing - beta7

### ISSUE THREAD

**Issue by Fosol** [aspnet/Hosting#407]
Where did you put IHttpContextAccessor?
I can't figure out the NuGet package that is required for this to work.

**Comment by kowsheek** [comment]
It seems to be under `Microsoft.AspNet.Http.IHttpContextAccessor` and `Microsoft.AspNet.Http.Internal.HttpContextAccessor` as a concrete implementation.

**Comment by Fosol** [comment]
Thanks!
