### ISSUE TITLE
How to run/debug a website using HttpPlatformModule with IIS Express ?

### ISSUE THREAD

**Issue by IsaacSee** [aspnet/Hosting#408]
Now that HttpPlatformModule replace Helios for IIS Hosting, what is the new way to run/debug a website localy using IIS Express, keeping the file watch functionnality ?

If it is not possible or not yet ready, is there a way to run dnx-watch as a project command to be able to run a website with wathing directly from visual studio ?

**Comment by davidfowl** [comment]
> Now that HttpPlatformModule replace Helios for IIS Hosting, what is the new way to run/debug a website localy using IIS Express, keeping the file watch functionnality ?

Wait for beta8. It's pretty much unworkable without the new tooling within VS.

> If it is not possible or not yet ready, is there a way to run dnx-watch as a project command to be able to run a website with wathing directly from visual studio ?

You probably could but it would be *very* rough (no browser launching etc). 

I recommend waiting for beta8, we're *very*, *very* close to shipping it.

**Comment by IsaacSee** [comment]
Ok, thanks for this clarification and great news for the very, very close shipping.
When you refer to beta8 I am not sure what you are talking about (dnx, vs tools) ?
Right now we are based the "unstable" rc1 runtime & aspnet packages, the good news is that everything seems to work when publishing and running on IIS (non express).

**Comment by davidfowl** [comment]
> Ok, thanks for this clarification and great news for the very, very close shipping. When you refer to beta8 I am not sure what you are talking about (dnx, vs tools)

These changes to the platform handler ripple throughout the entire stack. The biggest wrinkle is that the tooling needs to be updated to do all of the right http platform handler things (the changes are very impactful). Everything can be made to work, but the steps without the new tooling bits are extremely manual and we aren't going to document them. VS automates it all.

We also need to release a new http platform handler module with the enhancements we made (windows auth support and other things).

> Right now we are based the "unstable" rc1 runtime & aspnet packages, the good news is that everything seems to work when publishing and running on IIS (non express).

Great! There are some missing things if you don't have the new platform handler as mentioned above.

**Comment by IsaacSee** [comment]
All right ! Thanks. We will stick with the "cmd" dev mode waiting for the new tooling and hope the HttpPlatformHandler "missing" things we have not yet discovered are not a big deal for your stack.

**Comment by davidfowl** [comment]
> HttpPlatformHandler "missing" things we have not yet discovered are not a big deal for your stack.

If it didn't matter at all we wouldn't have changed the platform handler or added a middleware that does specific things. 

Anyways here's the list of things https://github.com/aspnet/Hosting/issues/364#issuecomment-144321477
