### ISSUE TITLE
Move webroot out of project.json

### ISSUE THREAD

**Issue by davidfowl** [aspnet/Hosting#411]
We should have a default convention based `wwwroot` in a known location relative to the app base. As an override, it can also be specified as a config option.

**Comment by muratg** [comment]
@Tratcher Let's get this done before other RC1 items, and remove project.json parsing from Hosting layer.

@BillHiebert FYI. This will have tooling impact that will need to go in RC1.  Do you have a tracking bug on your side.

**Comment by BillHiebert** [comment]
Do now,  TFS# Bug 156338 

@sayedihashimi

**Comment by muratg** [comment]
Note: project.json schema will need to change.

**Comment by muratg** [comment]
@Tratcher Could you file the DNX bug for the publish, test etc change (RC1) as well?

**Comment by Tratcher** [comment]
@muratg https://github.com/aspnet/dnx/issues/3035

**Comment by Tratcher** [comment]
@BillHiebert does tooling read the webroot from project.json for anything?

**Comment by davidfowl** [comment]
@Tratcher please post an announcement

**Comment by Tratcher** [comment]
@davidfowl waiting on the details of aspnet/dnx#3035
