### ISSUE TITLE
beta8: DNX_PATH being set wrong, when building in Appveyor vs. VS2015

### ISSUE THREAD

**Issue by kirk-marple** [aspnet/Hosting#412]
I've updated my Azure API app to beta 8 today, and have this line now in my web.config.

        <httpPlatform processPath="%DNX_PATH%" arguments="%DNX_ARGS%" stdoutLogEnabled="false" startupTimeLimit="3600"/>

When running the publish to Azure locally, the web.config ends up with this line below:
(C:\Users\Administrator\AppData\Local\Temp\2 \PublishTemp\Api.Onboarding83\wwwroot\web.config)

    <httpPlatform processPath="%home%\site\approot\web.cmd" arguments="" stdoutLogEnabled="false" stdoutLogFile="\\?\%home%\LogFiles\stdout.log" startupTimeLimit="3600"></httpPlatform>

But when running dnu publish from within a deployment script on Appveyor build server, the web.config ends up with this line:

    <httpPlatform processPath="..\approot\web.cmd" arguments="" stdoutLogEnabled="false" stdoutLogFile="..\logs\stdout.log" startupTimeLimit="3600"></httpPlatform>

This causes the Azure API App to fail to load with a weird "The specified CGI application encountered an error and the server terminated the process." error.

What part of the publish process in VS sets DNX_PATH and DNX_ARGS?  Is there something I can emulate via my Appveyor build script?

Thanks,
Kirk

**Comment by davidfowl** [comment]
That's actually correct. The latest version of the http platform handler needs to be installed on appveyor for relative paths to work. Can you file an issue to have them install it?

**Comment by kirk-marple** [comment]
Great, thanks for the quick reply.  I'll check with them and see how to achieve that.

**Comment by TwoToneBytes** [comment]
We are encountering this issue as well. No matter we set `processPath` to it gets overwritten to that relative path which doesn't work. We have the latest version of HttpPlatformHandler on the server installed.

**Comment by davidfowl** [comment]
The relative path definite works with 1.2. Make sure you actually have the latest version of the http platform handler.

**Comment by TwoToneBytes** [comment]
Where is that available? From the main download location I only see v1.0: http://www.iis.net/downloads/microsoft/httpplatformhandler

**Comment by GuardRex** [comment]
x86 version: http://go.microsoft.com/fwlink/?LinkId=690722
x64 version: http://go.microsoft.com/fwlink/?LinkId=690721

**Comment by muratg** [comment]
@kirk-marple @TwoToneBytes does the new http platform handler resolve this issue?

**Comment by TwoToneBytes** [comment]
Yes it has fixed it for me, thanks!
Is there anyway to update the official IIS.net downloads page to reflect this new version? The current one points to:
x86 http://go.microsoft.com/fwlink/?LinkID=524117
x64 http://go.microsoft.com/fwlink/?LinkID=524118

I'm assuming other people are encountering the same issues we are.

**Comment by muratg** [comment]
Yeah, we should update the downloads page. I'll reach out to folks who maintain the site to update the links. Thanks!

**Comment by kirk-marple** [comment]
Waiting for Appveyor to update their build server images by next week, and
I'll let you know.

**Comment by sulhome** [comment]
@davidfowl  there is no version 1.2, it is only 1.0. Where do we get version 1.2 from?

**Comment by apwestgarth** [comment]
The IIS.Net download entry for the HttpPlatformHandler v1.2 has been staged and is awaiting publication along with an update to the HttpPlatformHandler Configuration Reference.

The update to the Web Platform Installer Feed is now live so you can install HttpPlatformHandler v1.2 using the WebPI now.  I'll add a further comment as soon as I receive notification that the IIS.Net changes have gone live.

**Comment by GuardRex** [comment]
@apwestgarth Might not be relevant, but it's here, too: http://www.microsoft.com/en-us/download/details.aspx?id=47338

**Comment by muratg** [comment]
Closing this one. @kirk-marple let us know if you have problems after the AppVeyor update.
