### ISSUE TITLE
Error launching the application - Error while unloading appdomain. (Exception from HRESULT: 0x80131015)

### ISSUE THREAD

**Issue by matteomigliore** [aspnet/Hosting#415]
My project.json:
```json
"dependencies": {
	"EntityFramework.Commands": "7.0.0-rc1-15945",
	"EntityFramework.MicrosoftSqlServer": "7.0.0-rc1-15945",
	"EntityFramework.MicrosoftSqlServer.Design": "7.0.0-rc1-15945",
	"Microsoft.AspNet.Mvc":  "6.0.0-rc1-16028",
	"Microsoft.AspNet.Server.IIS": "1.0.0-beta8-15609",
	"Microsoft.AspNet.Server.Kestrel": "1.0.0-rc1-15767",
	"Microsoft.AspNet.Server.WebListener": "1.0.0-rc1-15727",
	"Microsoft.AspNet.StaticFiles": "1.0.0-rc1-15718",
	"Swashbuckle": "6.0.0-beta7",
	"System.Data.SqlClient": "4.0.0-beta-23409"
}
```

I obtain the error:
<pre>
Error while unloading appdomain. (Exception from HRESULT: 0x80131015)
</pre>

And when I refresh:
<pre>
Error when starting application. Status code `-2146233079`.
</pre>

**Comment by Tratcher** [comment]
Microsoft.AspNet.Server.IIS is obsolete. See https://github.com/aspnet/Hosting/issues/364

**Comment by matteomigliore** [comment]
I used "Microsoft.AspNet.IISPlatformHandler":  "1.0.0-rc1-15657", now the error is:
<pre>
Unexpected application failure. Status code '-2146233079'.
</pre>
