### ISSUE TITLE
beta8 published app doesn't run on IIS 7.5

### ISSUE THREAD

**Issue by PeterJakubik** [aspnet/Hosting#416]
I cannot run published beta8 app in IIS 7.5

I have installed beta8 and created new project (Empty web app)
and it works well with IIS Express from visual studio.

I have installed platform handler 1.2 ( and i see httpPlatformHandler in IIS Modules)
Then i published the app and add IIS Application pointing to wwwroot.

web.config looks like this
```
<configuration>
  <system.webServer>
    <handlers>
      <add name="httpplatformhandler" path="*" verb="*" modules="httpPlatformHandler" resourceType="Unspecified" />
    </handlers>
    <httpPlatform processPath="..\approot\web.cmd" arguments="" stdoutLogEnabled="false" stdoutLogFile="..\logs\stdout.log" startupTimeLimit="3600"></httpPlatform>
  </system.webServer>
</configuration>
```
When i enable stdoutLog i get log entry:
"Hosting environment: Production
Now listening on: http://localhost:32299
Application started. Press Ctrl+C to shut down.
"

The browser returns 404. 
I tried setting AppPool .NET Framework to 4, or no managed code, still getting 404

**Comment by Tratcher** [comment]
Are you using virtual apps/directories in IIS? If so see https://github.com/aspnet/Hosting/issues/364#issuecomment-148755010

**Comment by PeterJakubik** [comment]
I added App into Default website

**Comment by PeterJakubik** [comment]
OK, got it.
I renamed Configure(... in Startup.cs to Configure1(...

And my code looks now
```
public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
        {
            app.Map("/testBeta8", (app1) => this.Configure1(app1, env, loggerFactory));
        }

        // Configure is called after ConfigureServices is called.
        public void Configure1(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
        {
```

now it works
Thanks  @Tratcher

**Comment by Tratcher** [comment]
We're working on it, not sure what the solution will be yet. https://github.com/aspnet/IISIntegration/issues/14

**Comment by Fosol** [comment]
I don't understand the workaround.

Are you saying we need to configure the sub-application within the parent application.  Essentially copying the Configure method of the sub-application into the parent?
