### ISSUE TITLE
HttpPlatformHandler requirement is a serious issue

### ISSUE THREAD

**Issue by xatabhk** [aspnet/Hosting#417]
Publishing to a hosted site did not work, unlike beta 7 or earlier. The previous working site now is broken.
You guys have to find a native way to host asp.net 5 on an IIS server user has no control of.

If HttpPlatformHandler requirement does not get dropped, fewer and fewer people will use ASP.NET. I think I may have to stop using asp.net.

I don't want to see HttpPlatformHandler requirement will be the final thing moves user away from ASP.NET to other technologies like PHP.

**Comment by muratg** [comment]
@xatabhk there's already an issue for discussing this change.  Please post your comment/continue the discussion in https://github.com/aspnet/Hosting/issues/364.  Closing this one.

**Comment by xatabhk** [comment]
Not the same issue. My post is to suggest get rid of HttpPlatformHandler requirement.

**Comment by muratg** [comment]
@xatabhk That's the discussion thread for IIS hosting changes. The main announcement post (linked from that thread) contains the reasons for this requirement.
