### ISSUE TITLE
Get more hosters to install the HttpPlatformHandler

### ISSUE THREAD

**Issue by xatabhk** [aspnet/Hosting#418]
How can you install HttpPlatformHandler on a hosted site?
So get rid of HttpPlatformHandler requirement, or people stop use asp.net at all.

**Comment by muratg** [comment]
@xatabhk Again, please use the discussion thread https://github.com/aspnet/Hosting/issues/364 for this issue. We are not planning to bring the older IIS hosting model back, for the reasons called out in https://github.com/aspnet/Announcements/issues/69 post.

**Comment by muratg** [comment]
(https://github.com/aspnet/Hosting/issues/417)

**Comment by davidfowl** [comment]
@xatabhk What @muratg said, we're not going to drop that requirement to run in IIS.  What hosting are you running on?

**Comment by xatabhk** [comment]
GearHost  I don’t think other ASP providers will let user install anything on their shared IIS servers.
Asp.net 5 does not work on hosted sites and I never have liked asp.net prior to V5, I don’t know if I should go to PHP right now.

**Comment by davidfowl** [comment]
We can have a chat with them.

**Comment by xatabhk** [comment]
It sounds great. Their contact information can be found at https://www.gearhost.com/company/contact.

**Comment by davidfowl** [comment]
@xatabhk I'll request you change the bug title to - "Get more hosters to install the HttpPlatformHandler!"

**Comment by xatabhk** [comment]
Understandable. But I would wait till asp.net 5 works on my site to prove this is a good doable idea than getting rid of HttpPlatformHandler requirement totally.

**Comment by davidfowl** [comment]
But we're not getting rid of the HttpPlatformHandler requirement to run in IIS. I understand the frustration though, hopefully we can get hosters to install it so that you can test it out.

**Comment by muratg** [comment]
We are closing this issue because no further action is planned for this issue. If you still have any issues or questions, please log a new issue with any additional details that you have.
