### ISSUE TITLE
Issue after upgrading to beta8

### ISSUE THREAD

**Issue by ankitvijay** [aspnet/Hosting#424]
Hi All,
I'm facing rather strange issue after upgrading my project to beta 8 from beta 7. On running my web app (by pressing F5 or Ctrl + F5), I get following screen.
![image](https://cloud.githubusercontent.com/assets/5988564/10609349/dfda5932-7760-11e5-9b22-44cc78d2b694.png)
Visual Studio tries to configure the Windows Phone for debugging. My application is web application and does not target Windows Phone. I have made the relevant changes to the project for beta 8 and upgraded the Visual Studio tooling to Beta 8. Additionally, new project workflow works fine. My system configuration is: Windows Server 2012 R2, x64.

**Comment by Tratcher** [comment]
@BillHiebert?

**Comment by BillHiebert** [comment]
It sounds like you have one of the windows phone emulators set as your default browser.  Drop down the start button (green button on the toolbar). Which web browser is selected?

![startmenu](https://cloud.githubusercontent.com/assets/1553785/10613163/e7cebb0e-7708-11e5-905c-2d49e5a6602c.png)

**Comment by ankitvijay** [comment]
My apologies. It was indeed the case. Though I don't know how it got changed :(. Closing the issue.
