### ISSUE TITLE
Why doesn't ConfigureServices support dependency injection?

### ISSUE THREAD

**Issue by shawnwildermuth** [aspnet/Hosting#429]
I have a use case where I want to know what environment we're in to register services. For example

    public void ConfigureServices(IServiceCollection services, IHostingEnvironment env)
    {
      services.AddMvc();

      if (env.IsDevelopment())
      {
        services.AddScoped<IMailService, DebugMailService>();
      }
      else
      {
        services.AddScoped<IMailService, MailService>();
      }
    }

This doesn't work and I think it should. We could get it in the constructor and keep it around but that feels forced.

**Comment by Tratcher** [comment]
@hoak?

**Comment by GuardRex** [comment]
:+1: I had to hack it ...
```
string machineName = Environment.GetEnvironmentVariable("COMPUTERNAME");
if (machineName.StartsWith("<server_prefix>", StringComparison.OrdinalIgnoreCase))
{
// My server: Do this!
} else {
// My dev box: Do that!
}
```
... it be cool if I didn't have to do it this way.

**Comment by shawnwildermuth** [comment]
This feels safer (getting hosting environment and saving it in the constructor):

    private IHostingEnvironment _env;
    public IConfigurationRoot Configuration { get; set; }

    public Startup(IHostingEnvironment env, IApplicationEnvironment appEnv)
    {
      _env = env;

      var builder = new ConfigurationBuilder()
              .SetBasePath(appEnv.ApplicationBasePath)
              .AddJsonFile("config.json")
              .AddJsonFile($"config.{env.EnvironmentName}.json", optional: true);

      builder.AddEnvironmentVariables();
      Configuration = builder.Build();

    }

    // This method gets called by the runtime.
    public void ConfigureServices(IServiceCollection services)
    {
      // ...

      if (_env.IsDevelopment())
      {
        // dev stuff
        services.AddTransient<IEmailSender, MockAuthMessageSender>();
        services.AddTransient<ISmsSender, MockAuthMessageSender>();
      }
      else
      {
        // production stuff
        services.AddTransient<IEmailSender, AuthMessageSender>();
        services.AddTransient<ISmsSender, AuthMessageSender>();
      }
    }

**Comment by Tragetaschen** [comment]
I asked that question some time ago: #252

**Comment by muratg** [comment]
This is by design.

**Comment by shaunluttin** [comment]
Given that this is by design, what is the recommended way to set the entity framework data source type during startup? This, for instance, does not work, because we are inside `ConfigureServices`.

```
services.AddDbContext<AlgaeDbContext>(options => 
    { 
        if(env.IsDevelopment())
        {
            options.UseInMemoryDatabase(); 
        }
        else
        {
            options.UseSqlite("Database=Algae");
        }
    });
```

**Comment by davidfowl** [comment]
Inject it into the `Startup` class

**Comment by shaunluttin** [comment]
@davidfowl And then save it in a `private IHostingEnvironment _env` field in the Startup class? That seems kind of ugly too, because we're also injecting into into `Configure`. I suppose we could just inject everything into the `Startup` class ctor and then not inject anywhere else.

**Comment by davidfowl** [comment]
There are different sets of services injected into Configure and the Startup ctor. 
- Startup gets services provided by the Hosting environment
- Configure gets services provided by both the hosting environment and the application

**Comment by shaunluttin** [comment]
@davidfowl That makes sense. The duplication inside `Configure` does confuse things. If I were god :) then I would separate that.

**Comment by davidfowl** [comment]
> Why not inject only application stuff into Configure?

Because there's a single application container when everything is built up.
