### ISSUE TITLE
Asp.Net 5 MVC 6 Startup Assembly Decoupling in Beta8

### ISSUE THREAD

**Issue by sshassan** [aspnet/Hosting#433]
I am experiencing a hosting related issue since I upgraded to beta8 and started using the new hosting model. I am trying to get my head around it but so far couldn't find a solution. Instead of explaining the issue again, I asked this question on StackOverlow earlier, and suggestion I got was that I ask this question here. Can someone please shed some light on this?

Following is the question link: http://stackoverflow.com/questions/33240413/asp-net-5-mvc-6-startup-cs-assembly-decoupling-in-beta8

**Comment by davidfowl** [comment]
You can't load things that aren't referenced. You'll need to write a custom assembly loader for that.

**Comment by sshassan** [comment]
How was it working in Beta7? I didn't have to reference the Bootstrapper project. As I mentioned in my question, I only provided the location in global.json

{
  "projects": [ "Source/Projects", "Source/Bootstrapper" ],
	"sdk": {
		"architecture": "x64",
		"runtime": "clr",
		"version": "1.0.0-beta8"
	}
}

In wwwroot I had the Microsoft.AspNet.Hosting.ini file with the following lines

[Hosting]
Application=Bootstrapper

And it was working without any issues. Should it not work in a similar manner?

**Comment by sshassan** [comment]
Just want to highlight that in Beta7 it also works using "dnx command" for both Microsoft.AspNet.Server.WebListener and Microsoft.AspNet.Server.Kestrel.

```json
    "commands": {
    		"kestrel": "Microsoft.AspNet.Hosting --server Microsoft.AspNet.Server.Kestrel --server.urls http://localhost:5004 --config wwwroot/Microsoft.AspNet.Hosting.ini",
    		"web": "Microsoft.AspNet.Hosting --server Microsoft.AspNet.Server.WebListener --server.urls http://localhost:5004 --config wwwroot/Microsoft.AspNet.Hosting.ini"
    	}
```
However, the dnx command (using Microsoft.AspNet.Hosting.json file) fails for both servers in Beta8. If someone is wondering that it's something to do with IIS Helios component in Beta7, it's not the case. I am baffled as why the assembly lookup stopped working in Beta8

**Comment by davidfowl** [comment]
Was a bug that it worked before. You must reference things for it to be loadable.

**Comment by sshassan** [comment]
Here is the stack trace that I get when I try to run in Beta8 using IISExpress. Looks like it's trying to find the assembly in the dnx bin folder.

System.IO.FileNotFoundException: Could not load file or assembly 'Bootstrapper' or one of its dependencies. The system cannot find the file specified. File name: 'Bootstrapper' at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks) at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks) at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks) at System.Reflection.Assembly.Load(AssemblyName assemblyRef) at Microsoft.AspNet.Hosting.Startup.StartupLoader.FindStartupType(String startupAssemblyName, IList`1 diagnosticMessages) at Microsoft.AspNet.Hosting.Internal.HostingEngine.EnsureStartup() at Microsoft.AspNet.Hosting.Internal.HostingEngine.EnsureApplicationServices() at Microsoft.AspNet.Hosting.Internal.HostingEngine.BuildApplication()

=== Pre-bind state information === LOG: DisplayName = Bootstrapper (Partial) WRN: Partial binding information was supplied for an assembly: WRN: Assembly Name: Bootstrapper | Domain ID: 1 WRN: A partial bind occurs when only part of the assembly display name is provided. WRN: This might result in the binder loading an incorrect assembly. WRN: It is recommended to provide a fully specified textual identity for the assembly, WRN: that consists of the simple name, version, culture, and public key token. WRN: See whitepaper http://go.microsoft.com/fwlink/?LinkId=109270 for more information and common solutions to this issue. LOG: Appbase = file:///C:/Users/sshassan/.dnx/runtimes/dnx-clr-win-x86.1.0.0-beta8/bin/ LOG: Initial PrivatePath = NULL Calling assembly : (Unknown). === LOG: This bind starts in default load context. LOG: No application configuration file found. LOG: Using host configuration file: LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework\v4.0.30319\config\machine.config. LOG: Policy not being applied to reference at this time (private, custom, partial, or location-based assembly bind). LOG: Attempting download of new URL file:///C:/Users/sshassan/.dnx/runtimes/dnx-clr-win-x86.1.0.0-beta8/bin/Bootstrapper.DLL. LOG: Attempting download of new URL file:///C:/Users/sshassan/.dnx/runtimes/dnx-clr-win-x86.1.0.0-beta8/bin/Bootstrapper/Bootstrapper.DLL. LOG: Attempting download of new URL file:///C:/Users/sshassan/.dnx/runtimes/dnx-clr-win-x86.1.0.0-beta8/bin/Bootstrapper.EXE. LOG: Attempting download of new URL file:///C:/Users/sshassan/.dnx/runtimes/dnx-clr-win-x86.1.0.0-beta8/bin/Bootstrapper/Bootstrapper.EXE.

Perhaps, if I run dnu publish and host it under IIS it will work, but that means that I would have to publish it every time I make the change. However, I still wouldn't have to reference it in the MVC project.

**Comment by muratg** [comment]
This was not supposed to work before, so it's by design now.
