### ISSUE TITLE
Resolve logging when the request completes

### ISSUE THREAD

**Issue by rynowak** [aspnet/Hosting#443]
See this PR feedback: https://github.com/aspnet/Hosting/pull/403#discussion_r42696834

There's some things we can't log accurately right now from hosting (after request). Need to continue the discussion about how to improve the accuracy of this logging.

**Comment by Tratcher** [comment]
Offline recommendation was to move the logging into the servers. WebListener already has these kinds of logs.

**Comment by Tratcher** [comment]
https://github.com/aspnet/WebListener/blob/dev/src/Microsoft.Net.Http.Server/RequestProcessing/Request.cs#L156

**Comment by JunTaoLuo** [comment]
This will be resolved in https://github.com/aspnet/Hosting/issues/395 with the new design and reactions that that design in all affected servers.
