### ISSUE TITLE
Rename Microsoft.AspNet.Hosting.json

### ISSUE THREAD

**Issue by PinpointTownes** [aspnet/Hosting#452]
![image](https://cloud.githubusercontent.com/assets/6998306/10776573/f9272f16-7d12-11e5-9ae1-dc2ed43cbaaa.png)

Personally, I vote for `hosting.json` :+1:

**Comment by PureKrome** [comment]
@PinpointTownes @davidfowl 

- `hosting.json`

[](http://media.giphy.com/media/S8LWP0CotPAQw/giphy.gif)

**Comment by MJomaa** [comment]
Much better imo

**Comment by Bartmax** [comment]
:+1:  `hosting.json`

**Comment by henkmollema** [comment]
`hosting.json` :+1: 
Seems consistent with `project.json`, `config.json`, `packages.json`, etc.

**Comment by mikehaas763** [comment]
:+1:

**Comment by Tratcher** [comment]
@BrennanConroy
