### ISSUE TITLE
Add a new line in console when a request ends

### ISSUE THREAD

**Issue by rustd** [aspnet/Hosting#458]
In the templates review we were looking at the output of the console logger. When you make 2 requests there is no line break or spacing between the requests. The ask is to add a new line when the request ends.

**Comment by Tratcher** [comment]
Line breaks aren't a good system to distinguish between requests. Hosting doesn't control the format of the log output, and logging doesn't know when a request ends (except when a scope ends?). Also, this breaks down as soon as you have any concurrency.

**Comment by davidfowl** [comment]
So close?

**Comment by Tratcher** [comment]
Maybe the console logger needs to log scopes in a visually distinctive way? Right now ignores them.
