### ISSUE TITLE
Publish to Azure - Not working

### ISSUE THREAD

**Issue by Fosol** [aspnet/Hosting#467]
I've attempted to publish my web application to Azure but I always get the following error, "**The specified CGI application encountered an error and the server terminated the process.**"
# global.json
```
{
  "projects": [ "src", "test" ],
  "sdk": {
    "version": "1.0.0-beta8",
    "runtime": "clr",
    "architecture": "x64"
  }
}
```
# project.json
```
{
    "webroot": "wwwroot",
    "version": "1.0.0-*",
    "dependencies": {
      "Microsoft.Extensions.NotNullAttribute.Sources": {
        "version": "1.0.0-*",
        "type": "build"
      },
      "Microsoft.AspNet.Diagnostics": "1.0.0-beta8",
      "Microsoft.AspNet.Server.Kestrel": "1.0.0-beta8",
      "Microsoft.AspNet.IISPlatformHandler": "1.0.0-beta8",
      "Microsoft.AspNet.Hosting": "1.0.0-beta8",
      "Microsoft.AspNet.Html.Abstractions": "1.0.0-beta8",
      "Microsoft.AspNet.Identity": "3.0.0-beta8",
      "Microsoft.AspNet.Mvc": "6.0.0-beta8",
      "Microsoft.AspNet.Mvc.Core": "6.0.0-beta8",
      "Microsoft.AspNet.Mvc.TagHelpers": "6.0.0-beta8",
      "Microsoft.AspNet.Razor": "4.0.0-beta8",
      "Microsoft.AspNet.StaticFiles": "1.0.0-beta8",
      "Microsoft.AspNet.Tooling.Razor": "1.0.0-beta8",
      "Microsoft.AspNet.Mvc.ApiExplorer": "6.0.0-beta8",
      "Microsoft.Framework.Configuration": "1.0.0-beta8",
      "Microsoft.Framework.Configuration.EnvironmentVariables": "1.0.0-beta8",
      "Microsoft.Framework.Configuration.Json": "1.0.0-beta8",
      "SP7.DAL": "1.0.0-*",
      "SP7.DAL.Models": "1.0.0-*",
      "SP7.MVC.Core": "1.0.0-*"
    },
    "commands": {
      "web": "Microsoft.AspNet.Server.Kestrel"
    },
    "frameworks": {
        "dnx451": { }
    },
    "publishExclude": [
        "node_modules",
        "bower_components",
        "**.xproj",
        "**.user",
        "**.vspscc"
    ],
    "exclude": [
        "wwwroot",
        "node_modules",
        "bower_components"
    ]
}
```

**Comment by Fosol** [comment]
Looks like you have a bug in Azure/VS2015/Publish or some combination of them.

I found a solution/workaround here - http://www.brandonmartinez.com/2015/10/28/resolve-an-asp-net-dnx-httpplatformhandler-cgi-application-exception-on-azure/

Essentially you have to publish the project locally, manually edit the web.config file and then FTP to AZURE.

**Comment by kichalla** [comment]
Which version of VS tooling are you using? Beta8?

**Comment by Fosol** [comment]
I'm pretty certain Beta8.  How can I confirm?

**Comment by kichalla** [comment]
For example, when you go to Help | About Microsoft visual studio 

![image](https://cloud.githubusercontent.com/assets/6559784/10975839/ac5acdbe-839d-11e5-94bc-769a9b4135f5.png)

**Comment by Fosol** [comment]
I'm actually using version 14.0.61012.0

**Comment by kichalla** [comment]
Hmm...let me give it a try and will let you know

**Comment by davidfowl** [comment]
@Fosol are you using csproj files?

**Comment by Fosol** [comment]
No I'm using the standard templates for creating a VNext project.  So there are xproj files.

**Comment by kichalla** [comment]
I now installed the tooling version as yours and tried a VS template based project and published via VS and I am unable to repro the issue you are seeing.

**Comment by kichalla** [comment]
Also could you share how your web.config looks like...for example, following is the VS template generated one:

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <system.webServer>
    <handlers>
      <add name="httpPlatformHandler" path="*" verb="*" modules="httpPlatformHandler" resourceType="Unspecified"/>
    </handlers>
    <httpPlatform processPath="%DNX_PATH%" arguments="%DNX_ARGS%" stdoutLogEnabled="false" startupTimeLimit="3600"/>
  </system.webServer>
</configuration>
```

**Comment by Fosol** [comment]
He's the web.config after the publish.

<configuration>
  <system.webServer>
    <handlers>
      <add name="httpplatformhandler" path="*" verb="*" modules="httpPlatformHandler" resourceType="Unspecified" />
    </handlers>
    <httpPlatform processPath="..\approot\web.cmd" arguments="" stdoutLogEnabled="true" stdoutLogFile="..\logs\stdout.log" forwardWindowsAuthToken="false" startupTimeLimit="3600"></httpPlatform>
  </system.webServer>
</configuration>

**Comment by Fosol** [comment]
I suspect it's a template issue.  Can you point me in the right direction to test this theory?

**Comment by GuardRex** [comment]
@Fosol I list the known Azure publishing issues on Github at the top of the Application section at https://github.com/aspnet/Hosting/issues/364#issuecomment-148567294. If I missed one, let me know, as I'd like to keep that updated for the time being.

**Comment by Fosol** [comment]
Looks like the bug I've ran into is in your list already.

> @mkelley82 at #364 (comment) (remove the  forwardWindowsAuthToken  attribute).

**Comment by GuardRex** [comment]
@Fosol Ok ... cool. Thanks for confirming that.
