### ISSUE TITLE
Regression: Not detecting HTTP_PLATFORM_PORT in IIS/Express

### ISSUE THREAD

**Issue by Tratcher** [aspnet/Hosting#470]
Regressed by https://github.com/aspnet/Hosting/issues/453
The configuration is now filtering out environment variables that do not begin with "ASPNET_". `.AddEnvironmentVariables(prefix: EnvironmentVariablesPrefix)`.

Either re-work the config to pick up other environment variables, or read HTTP_PLATFORM_PORT directly from the Environment (not recommended as this makes testing more difficult). 
@davidfowl

**Comment by davidfowl** [comment]
Did we add a test?

**Comment by pakrym** [comment]
@davidfowl nope, it's environment variable and we cannot test them
