### ISSUE TITLE
How to specify port number in hosting.

### ISSUE THREAD

**Issue by Bartmax** [aspnet/Hosting#473]
I think it would be good if you can include how port number is defined in configuration or as a sample.

https://github.com/aspnet/Announcements/issues/108

**Comment by Tratcher** [comment]
Configuring the port is server specific but WebListener and Kestrel use most of the same logic. `server.urls` is the key. The value is a semi-colon separated list of url prefixes, or ints if you only want to specify the port for `http://localhost:{port}`. E.g.:
`http://localhost:8080/`, or `8080`, or `http://*:8080/;https://*:9090/`.
