### ISSUE TITLE
502.3 - Bad Gateway when debugging with IIS Express

### ISSUE THREAD

**Issue by rhegner** [aspnet/Hosting#475]
I created a new WebApp with ASP.NET 5 Beta 8. I started with the template, then got rid of EntityFramework, and am now in the process of making it work with my custom data store.

When I try to debug it out of Visual Studio 2015 (IIS Express, Internet Explorer), the WebApp starts fine but when I go to the Login page I get the following error:

502.3 - Bad Gateway
Module: httpPlatformHandler
Notification: ExecuteRequestHandler
Handler: httpPlatformHandler
Error Code: 0x80072f78

I saw that other people have similar problems. But they either encounter this problem when publishing the WebApp to some other machine (I have the problem on my development machine), or with projects they created with Beta 7 or earlier (I created the project using Beta 8).

So... I don't really know where to start....

I did install HttpPlatformHandler 1.2 but it didn't help.

**Comment by muratg** [comment]
Have you seen this while you were bashing HttpPlatformHandler @pakrym?

**Comment by pakrym** [comment]
@muratg looks like an exception somewhere in appbuilder.Run, need a repro to tell exactly

**Comment by muratg** [comment]
@rhegner could you share a simplified repro?

**Comment by rhegner** [comment]
Yes I'm pretty sure there are some internal exceptions happening. I started to implement my own IUserStore and so far all interface methods throw a NotImplementedException. So - yes, obviously my code isn't running correctly yet. But shouldn't I just see the exception and the call stack in the browser instead of the "Bad Gateway"?

I'll simplifiy my solution and upload it later today.

**Comment by muratg** [comment]
Thanks, that would be helpful for us to debug in case there's something we need to fix on our side.

**Comment by rhegner** [comment]
Ok you can find a very simple solution here:
https://drive.google.com/file/d/0B89qp_QRBuXQTTZ0RFk1b2YxUGM/view?usp=sharing

You can reproduce the problem by debugging the solution (IIS Express) and then click on "Log in".

**Comment by rhegner** [comment]
One thing i noticed: Visual Studio seems to be unhappy with the "httpPlatform" section in the wwwroot/web.config file (see screenshot).
![screenshot](https://cloud.githubusercontent.com/assets/2563997/11113298/04aed554-891c-11e5-96bb-9a1909aabd94.png)

**Comment by pakrym** [comment]
@rhegner, Enable catching all thrown exceptions by checking "Common Language Runtime Exceptions" in "Debug->Windows->Exception Settings" window. ![](http://i.imgur.com/u6iniPp.png)

In your case it throws here:
```
>	FESplaWebApp!FESplaWebApp.Models.FESplaWebAppUserStore.FindByIdAsync(string userId, System.Threading.CancellationToken cancellationToken) Line 29	C#
 	[External Code]	
 	FESplaWebApp!FESplaWebApp.Controllers.ManageController.GetCurrentUserAsync() Line 347	C#
 	FESplaWebApp!FESplaWebApp.Controllers.ManageController.Index(FESplaWebApp.Controllers.ManageController.ManageMessageId? message) Line 49	C#
 	[External Code]	
```

**Comment by rhegner** [comment]
Ok thanks Pavel. This helps me to continue coding :)

But still, I'd expect such an exception to bubble up and then be displayed in the browser (just like with ASP.NET vOld). So there's still a bug or misconfiguration somewhere, right?

**Comment by pakrym** [comment]
It does exactly like you say on my machine but I have RC1 tooling, try waiting until RC1 and upgrade project and tooling, ping me if it won't solve your problem.

**Comment by Tratcher** [comment]
If the exception happens before the response has started then it can be handled gracefully. However, if the exception happens after the response has started then all Kestrel can do is terminate the connection, and HttpPlatformHandler reports this as a 502.

**Comment by muratg** [comment]
Thanks folks, and closing this one. @rhegner please let us know if you hit other issues after your investigation.

**Comment by GuardRex** [comment]
@rhegner btw - VS not recognizing `<httpPlatform>`: That's just a file schema issue and will be updated soon. https://github.com/aspnet/Tooling/issues/222
