### ISSUE TITLE
[HttpPlatformHandler] termination of child process causes termination of parent process

### ISSUE THREAD

**Issue by tuespetre** [aspnet/Hosting#477]
Specific example: running the dnx-watch command. When you save changes to a file, dnx-watch terminates its child dnx process and starts a new one, but by the time dnx-watch has recorded that to stdout (which does show in the logs) the HttpPlatformHandler terminates the dnx-watch process and starts a new one.

**Comment by muratg** [comment]
@Tratcher Where's the best place to log this?

**Comment by Tratcher** [comment]
This issue was moved to aspnet/IISIntegration#34
