### ISSUE TITLE
Logged elapsed time is wrong

### ISSUE THREAD

**Issue by sebastienros** [aspnet/Hosting#478]
This is what I get when I log the time for a request, and then Hosting is also logging the same time:

```
verb: Orchard.Hosting.OrchardContainerMiddleware[0]
      Request took 42ms
info: Microsoft.AspNet.Hosting.Internal.HostingEngine[2]
      Request finished in 0.0047ms 200 text/html; charset=utf-8
```

Something in how this TimeSpan is constructed must be wrong.

**Comment by JunTaoLuo** [comment]
@sebastienros I took a look at our logging and I don't see an obvious error. Do you have a project available for me to repro this and take a look at why there is a discrepancy between the logged times?

**Comment by sebastienros** [comment]
The issue comes from the fact that the tick counts are base on `Environment.TickCount` but displayed using ` Timespan` instance. The tick counts don't represent the same thing for both, with a difference of about 10000. The solution is to use `DateTime.Now.Ticks` instead on `Environment.Ticks` as you can't assume that the system timer will always return milliseconds (which seems to be the case on my system).

Here is some code showing the difference:
```c#
using System;
					
public class Program
{
	public static void Main()
	{
		var startEnvironmentTicks = Environment.TickCount;
		var startDateTimeTicks = DateTime.Now.Ticks;
		
		System.Threading.Thread.Sleep(50);

		Console.WriteLine("Environment: {0}", Environment.TickCount - startEnvironmentTicks);
		Console.WriteLine("DateTime: {0}", DateTime.Now.Ticks - startDateTimeTicks);
	}
}
```

Which results in:
```
Environment: 79
DateTime: 781292
```

It's also mentioned in this help page under the remarks section: https://msdn.microsoft.com/en-us/library/system.environment.tickcount(v=vs.110).aspx

**Comment by JunTaoLuo** [comment]
We will need to find a substitute for timing requests. `DateTime.Now` is too slow since it's a system call.

**Comment by sebastienros** [comment]
This gist shows the perf differences between different techniques:
https://gist.github.com/sebastienros/40981268e057eb9235f3

For 1 million calls

`Environment.TickCount`: 15ms
`DateTime.UtcNow.Ticks`: 41ms
`DateTime.Now.Ticks`: 135ms

Not sure the way I profiled is right but I assume it should help deciding.

**Comment by tmds** [comment]
The constructor used here: accepts 100-ns ticks:
https://github.com/aspnet/Hosting/blob/f3384d97cb7bba9b9f2d33268bad78e54714395a/src/Microsoft.AspNet.Hosting/Internal/HostingLoggerExtensions.cs#L35
While the value from Environment.TickCount are millisecond ticks.

**Comment by JunTaoLuo** [comment]
Completed in #485, Thanks @tmds!
