### ISSUE TITLE
In RC2 remove the fallback of webroot to the approot

### ISSUE THREAD

**Issue by blowdart** [aspnet/Hosting#480]
#450 defines that you fall back to webroot for porting concerns. 

This has security implications and shouldn't be automatic. If people want that behaviour, they can set it. 

The default should be

If hosting.json exists and defines "webroot", use it.
Else if the "wwwroot" directory exists, use it as the webroot.
Else STOP

**Comment by PureKrome** [comment]
For @blowdart with :heart: 

... 
Else STOP (and display message in default browser (which pops open..) ) 
![](https://31.media.tumblr.com/23c48740b9aa235a53aa1a228f53273b/tumblr_inline_n4hamtONMB1solpjm.gif)

**Comment by davidfowl** [comment]
That's fine by me 😀

**Comment by davidfowl** [comment]
We need to look at what things will start to fail. Mvc file results, static file server. Where should it throw?

**Comment by Tratcher** [comment]
Here: https://github.com/aspnet/Hosting/blob/660f1cad10b7c3e08e9267b7f5967fbcdbd6c18f/src/Microsoft.AspNet.Hosting/HostingEnvironmentExtensions.cs#L31
This just broke ServiceFabric.

**Comment by muratg** [comment]
FYI @glennc

**Comment by bradwilson** [comment]
An API-only project would have no need for wwwroot, and I wouldn't want you to start randomly serving my source files.

**Comment by Eilon** [comment]
@dougbu @rynowak FYI because we were talking about this the other day. This definitely needs to change.

**Comment by dougbu** [comment]
@Eilon yeah, I demoed the issue to a certain @blowdart. Who bet against this issue existing?

**Comment by Eilon** [comment]
Probably @rynowak bet on it. Certainly not me :smile:

**Comment by davidfowl** [comment]
@random files won't get served unless you added the static file middleware or wrote code to do it

**Comment by blowdart** [comment]
@davidfowl Yes, but we're trying to be secure by default. And all the templates add static file middleware. And this behaviour is specifically to support people using the static file middleware to help port old code. So, saying "This won't activate unless you add the static file middleware" isn't really a good justification :D

**Comment by Tratcher** [comment]
This also needs to be updated in dnu publish.
