### ISSUE TITLE
Consider renaming WebApplication class

### ISSUE THREAD

**Issue by muratg** [aspnet/Hosting#482]
Default yeoman template for "Web Application" creates the project with the name WebApplication. This creates a conflict.  

We have a bug on YO templates to change this default on the templates themselves. But it makes sense to have the change made in Hosting as well (to a less common name.)

**Comment by muratg** [comment]
https://github.com/OmniSharp/generator-aspnet/issues/488

**Comment by peterblazejewicz** [comment]
@muratg 
We could use FCQN in generator:
```
public static void Main(string[] args) => Microsoft.AspNet.Hosting.WebApplication.Run<Startup>(args);
```
Will this be OK? (at least for rc1)

**Comment by muratg** [comment]
@peterblazejewicz Yes, that works.

**Comment by peterblazejewicz** [comment]
@muratg Thanks a lot!

**Comment by muratg** [comment]
This is good to close as YO template was already updated.
