### ISSUE TITLE
Flow hosting configuration through to application

### ISSUE THREAD

**Issue by DamianEdwards** [aspnet/Hosting#488]
There's currently no way to get access to the configuration constructed and used by the hosting layer, from the application. This is useful in cases where the application wants to get access to values that have already been parsed into an `IConfiguration` by the hosting layer, e.g. command line arguments.

I propose we add a new property to `IHostingEnvironment`: `IConifguration Configuration { get; }`

This would be set by `WebHostBuilder` when it's initializing the `IHostingEnvironment` instance (e.g. somewhere around [here](https://github.com/aspnet/Hosting/blob/dev/src/Microsoft.AspNet.Hosting/WebHostBuilder.cs#L130)).

That way, an application can simply accept `IHostingEnvironment` in its constructor to get access to the hosting's configuration.

Example usage:
``` C#
public class Startup
{
    public static void Main(string[] args) => WebApplication.Run<Startup>(args);

    public Startup(IHostingEnvironment hosting)
    {

        var builder = new ConfigurationBuilder()
            .AddJsonFile("appsettings.json")
            .AddEnvironmentVariables()
            .AddConfiguration(hosting.Configuration);

        Configuration = builder.Build();

        Configuration.Bind(Options);
    }

    public IConfigurationRoot Configuration { get; set; }

    public StartupOptions Options { get; } = new StartupOptions();

    public class StartupOptions
    {
        public bool EnableThing { get; set; }
    }
        ...
```

Required change to configuration to support this aspnet/Configuration#339

**Comment by Tratcher** [comment]
Someone asked for this a few months ago specifically for the command line parameters. It was eventually closed for some reason. @Eilon had some interest in that discussion.

**Comment by DamianEdwards** [comment]
To be clear, you could do this right now (if you don't launch via commands) like the following, but I think something more formal like this is nicer.

``` C#
public class Startup
{
    private static string[] _args;
    public static void Main(string[] args) => WebApplication.Run<Startup>(_args = args);

    public Startup(IHostingEnvironment env)
    {

        var builder = new ConfigurationBuilder()
            .AddJsonFile("appsettings.json")
            .AddEnvironmentVariables()
            .AddCommandLine(_args);

        Configuration = builder.Build();

        Configuration.Bind(Options);
    }

    public IConfigurationRoot Configuration { get; set; }

    public StartupOptions Options { get; } = new StartupOptions();

    public class StartupOptions
    {
        public bool EnableThing { get; set; }
    }
```

**Comment by Tratcher** [comment]
Note even the commands work if you change your command to `"web": "MyWebApp"`

**Comment by Tratcher** [comment]
But you have to include `--server=Microsoft.AspNet.Server.Kestrel`

**Comment by davidfowl** [comment]
This is a cleaner way to flow that data. It works irregardless of how you host your application. Unlike the previous request to only flow command line arguments, this flows all of the configuration.

**Comment by Eilon** [comment]
@Tratcher yeah I can't find the issue you're referring to. I did find this semi-related issue: https://github.com/aspnet/Hosting/pull/399

**Comment by penderi** [comment]
Why was this removed ? Accessing the config twice in my pipeline makes no sense
