### ISSUE TITLE
How do we fall through IIS when using IISPlatformHandler? 

### ISSUE THREAD

**Issue by dealdiane** [aspnet/Hosting#491]
Now that ASPNET 5 runs on kestrel only how do we fall through IIS? There used to be an `app.RunIISPipeline()` but I couldn't find this anywhere anymore.

I hope this was not forgotten. https://github.com/aspnet/Hosting/issues/323

**Comment by davidfowl** [comment]
You don't fall through IIS anymore. It's a reverse proxy

**Comment by dealdiane** [comment]
How do we take advantage of IIS's feature like static compression and etc? They don't seem to work (at least static files no longer work without adding `app.UseStaticFiles`?

**Comment by Tratcher** [comment]
This issue was moved to aspnet/IISIntegration#40
