### ISSUE TITLE
TestHost.Create() has incompatible overloads

### ISSUE THREAD

**Issue by joaroyen** [aspnet/Hosting#497]
rc1 added a set of "Func<IServiceCollection, IServiceProvider> configureServices" overloads to TestHost.Create() that is not compatible with the existing "Action<IServiceCollection> configureServices" overloads:
```c#
public static TestServer Create(Action<IApplicationBuilder> configureApp, Action<IServiceCollection> configureServices)
public static TestServer Create(Action<IApplicationBuilder> configureApp, Func<IServiceCollection, IServiceProvider> configureServices)
```
After upgrading to rc1 I get this error from the compiler:
Error	CS0407	'void Startup.ConfigureServices(IServiceCollection)' has the wrong return type	MediaStreams.Test.

I've currently implemented a workaround by changing signature from void to System.IServiceProvider and returning services.BuildServiceProvider() at the end of the method.

**Comment by muratg** [comment]
Ugh.  Perhaps we should rename the second overload?

@davidfowl

**Comment by Radek44** [comment]
Quick workaround for now is to cast explicitely: 
```
var startup = new Startup(hostingEnvironment, applicationEnvironment);
            var server = TestServer.Create(startup.Configure, (Action<IServiceCollection>)startup.ConfigureServices);
```
