### ISSUE TITLE
ConfigureServices IServiceCollection exception message is confusing.

### ISSUE THREAD

**Issue by JesperTreetop** [aspnet/Hosting#502]
The code calling `ConfigureServices` generates the following exception message:

> ConfigureServices can take at most a single IServiceCollection parameter.

When I got this, I read this as "`ConfigureServices` can take various parameters, but just one of the type `IServiceCollection`, so you're trying to use two or more `IServiceCollection` parameters"! I had to go find the code where the exception was thrown to realize that it meant that it can't take any other parameters, which was my problem (trying to have `IHostingEnvironment` injected to set up services differently based on environment; I solved that by having the constructor, which can take it, squirrel away the `IHostingEnvironment` instance).

How about:

> ConfigureServices can not take any parameters besides at most one IServiceCollection parameter.

..?

**Comment by davidfowl** [comment]
> besides at most one IServiceCollection parameter

Is confusing as well. I'm all for changing it to be clearer though.

/cc @Eilon

**Comment by Eilon** [comment]
I'll come up with something.

**Comment by Radek44** [comment]
Linking to #497

**Comment by davidfowl** [comment]
@Eilon last chance 😄

**Comment by JunTaoLuo** [comment]
`"ConfigureServices must be parameterless or take only one IServiceCollection parameter."`?

**Comment by Eilon** [comment]
Slight modification @JunTaoLuo 's text:

`The ConfigureServices method must either be parameterless or take only one parameter of type IServiceCollection.`

**Comment by Eilon** [comment]
Unassigning from me. @muratg can find a new owner to implement this complex feature 😄

**Comment by JesperTreetop** [comment]
Thanks for listening and caring about things like this. I know it would have been very easy to swat it away and say "nah, you just weren't thinking". I think the message you settled on was great and better than my proposal.

**Comment by Eilon** [comment]
@JesperTreetop of course, and thanks for bringing it to our attention!
