### ISSUE TITLE
WebHostBuilder.Build returns a type that's in the Internal namespace

### ISSUE THREAD

**Issue by DamianEdwards** [aspnet/Hosting#504]
When manually bootstrapping an app using `WebHostBuilder`, the call to `Build` returns `IHostingEngine` which is in the `Internal` namespace. This is far from ideal, as apps that wish to emulate the behavior of `WebApplication.Run` while also adding their own behavior (e.g. interactive console) have to take dependencies on unsupported (Internal) types.

Example at https://github.com/aspnet/benchmarks/blob/master/src/Benchmarks/Program.cs#L18

**Comment by Radek44** [comment]
Linking with #497

**Comment by JunTaoLuo** [comment]
Will be addressed in #525
