### ISSUE TITLE
env.IsDevelopment() returns False always in latest RC2

### ISSUE THREAD

**Issue by xatabhk** [aspnet/Hosting#506]
In the following general startup code, no matter what value is specified for ‘Hosting:Environment’, env.IsDevelopment() always retusns false, that is ‘Hosting:Environment’=‘Production’ all the time.

public Startup(IHostingEnvironment env)
{
    If(env.IsDevelopment())
    {
        //Unreachable code
    }
    Else
    {
        //...
    }
}

In RC2 not so long ago (for an example, RC2 16177), no this issue exists.

**Comment by davidfowl** [comment]
See https://github.com/aspnet/Announcements/issues/108
