### ISSUE TITLE
When starting up Kestrel throws EADDRNOTAVAIL error

### ISSUE THREAD

**Issue by janpieterz** [aspnet/Hosting#520]
When starting up the ASP.NET app in IIS, Kestrel throws the following exception:

```
Microsoft.AspNet.Server.Kestrel.Networking.UvException: Error -4090 EADDRNOTAVAIL address not available
   at Microsoft.AspNet.Server.Kestrel.Networking.Libuv.Check(Int32 statusCode)
   at Microsoft.AspNet.Server.Kestrel.Networking.UvTcpHandle.Bind(ServerAddress address)
   at Microsoft.AspNet.Server.Kestrel.Http.TcpListener.CreateListenSocket()
   at Microsoft.AspNet.Server.Kestrel.Http.Listener.<>c__DisplayClass5_0.<StartAsync>b__0(Object _)
```

I first thought it might have something to do with having two ASP.NET apps, both listening to port 80 in IIS (different subdomain bindings though). This proved wrong when booting up a fresh VM in Azure, routing subdomain to that one and getting the same error, indicating it might be something else. The only thing I can currently think of that is significantly different from the two ASP.NET apps is that one runs on dnx-clr-win-x64.1.0.0-rc1-update1 (the failing one) and the other one still on dnx-clr-win-x64.1.0.0-rc1-final (the working one).

For reference, a StackOverflow I started before trying it on a fresh VM:
http://stackoverflow.com/questions/34228559/how-do-i-get-httpplatformhandler-and-kestrel-to-play-nicely-with-multiple-websit

**Comment by janpieterz** [comment]
Update: I confirmed that going back to dnx-clr-win-x64.1.0.0-rc1-final fixed the issue for me, so it must be some kind of bug introduced in update-1.

**Comment by GuardRex** [comment]
@janpieterz There's no known reason for apps on with different subdomains on port 80 to have any problem. What is your `web` command in `project.json`?

**Comment by janpieterz** [comment]
My apologies about the earlier 'fix'. This only fixed it on my own PC running in IIS, not on the server.

@GuardRex I think you're onto something. I added a server.urls there to allow remote listening while in development, but my File Publish has not removed this so it probably tries to attach itself to an IP it can't reach.

I saw your massive explanation post, also detailing your publish changes. Do you know of any way to have a local server.urls that is different than the deployed one?

**Comment by janpieterz** [comment]
@GuardRex Just confirmed it working when I removed my server.urls specific for local usage. Would still appreciate your insight in how to have development urls there while allowing these to be different when deployed.

If you'd like to submit your insights as an answer on StackOverflow I'll accept it as an answer, plus I'll close this issue. Thanks a lot!

**Comment by GuardRex** [comment]
@janpieterz I think so ..... sort of ... you can specify the command to run through modifications to the `web.config` file. Something like this (maybe ... just spitballing here) ...
```c#
<httpPlatform 
    processPath="%DNX_PATH%" 
    arguments="--project F:\MyApp\approot\packages\MyApp\1.0.0\root web" 
    stdoutLogEnabled="true" 
    stdoutLogFile="..\logs\httpplatform" 
    startupTimeLimit="3600"></httpPlatform>
```
... where you see "web" there ... you could put a different command from `project.json`, say "web2" ... a command that on the server would have a different `server.urls` specified. Then, the only issue would be how to substitute the `web.config` file with the "server version" on the server and the "local version" of `web.config` still has "web" command with `server.urls` for the local environment. It should only come down at that point to getting a local `web.config` and a server `web.config`.

We would need @Tratcher to come in here with his vast knowledge and tell us if this is the right way to go.

**Comment by GuardRex** [comment]
Actually, it might be even simpler than that with the command. This might work ...
```xml
```xml
<httpPlatform 
    processPath="%DNX_PATH%" 
    arguments="--project .. web" 
    stdoutLogEnabled="true" 
    stdoutLogFile="..\logs\httpplatform" 
    startupTimeLimit="3600"></httpPlatform>
```
```

**Comment by GuardRex** [comment]
@janpieterz I just filed an issue related to this for doc coverage that deals with configuration of the `httpPlatform` element in scenarios just like this: https://github.com/aspnet/Docs/issues/786. Please do ping back if this turns out to be a good approach.

**Comment by janpieterz** [comment]
That  would certainly work for me, although I'd more expect the core of my issue (the binding to a non-existing IP, no way to 'overwrite' whatever is in project.json when publishing (should this be a publish setting?)) to be solved differently.

**Comment by GuardRex** [comment]
@janpieterz Not so far as I know ... I mean when you say override or overwrite what's in `project.json`, you'd have to do something like this with PowerShell ... https://github.com/GuardRex/net5-autoupdate-version ... but its **horrible** and might not even work.

I have a gut feeling that having two commands in `project.json` and then triggering one command locally and triggering the other command on the server probably fits the design best. It only comes down to triggering one command or the other with a local `web.config` and a server `web.config`. I'm trying to think what I've seen about that scenario of having a different `web.config` on the server, but I don't remember it coming up.

The only reason that IIS Basic Settings path to the application is pointed to `wwwroot` is to read the `web.config` file AFAIK. I wonder if you would simply point the app in IIS to read from a folder where there is a server `web.config` file sitting there that isn't published with the app ... that `web.config` is the one with this other command that has the `server.urls` that the server should be using. That file would sit in a stable location outside of your deployment.

Really though ... when things get this wild, you need @Tratcher to jump in and give us a hand.
