### ISSUE TITLE
Application goes cold on IIS even with StartMode = AlwaysRunning

### ISSUE THREAD

**Issue by mikes-gh** [aspnet/Hosting#522]
IIS 7.5 2008 r2 Latest Platform Handler rc1-update1

This is a bit of a woolly description sorry.
It appears to me that my asp.net 5 app goes cold (or at least semi cold) even when StartMode = AlwaysRunning
Second request of resource is always very quick.
Does DNX or maybe Kestrel  stand down some resources outside of IIS control.

MVC 5 app always seems to be ready to go.

**Comment by GuardRex** [comment]
@mikes-gh Did you set the AppPool's `Advanced Settings > Idle Time-out (minutes)` to 0 (zero)?

**Comment by GuardRex** [comment]
@mikes-gh You can try setting the `Advance Settings > Start Mode` to `AlwaysRunning`, too.

**Comment by mikes-gh** [comment]
@GuardRex 
>you can try setting the Advanced Settings > Start Mode to AlwaysRunning
Please read original message (and title)..  The point is it is already set. .  Also AFAIK idle time out does not apply with StartMode =- Always running..

It works fine on MVC 5 app.  It appears with Kestrel some resources are unloaded after a period of inactivity although as far as I can tell not all.  ie first page hit is not as slow as a full cold start but is still slower than subsequent page hits.

**Comment by GuardRex** [comment]
@mikes-gh Sorry ... was doing like four things at once ... and probably screwing up three of them!

There are posts out there with comments that `Idle Time-out` still had to be set to 0 (zero) (e.g., http://stackoverflow.com/a/28171672/5012375 ), but MS says https://msdn.microsoft.com/en-us/library/ee677260(v=azure.10).aspx ...

> If the auto-start feature is enabled for a service, IIS ignores the Idle Timeout setting on the application pool and on the application that uses the application pool. The worker process associated with the application pool remains in memory even after the application pool is idle for longer than the Idle Timeout value.

When I do what you're trying to do, I always set them both ... on the "it couldn't hurt" principle.

AFAIK noone has asked in the issues about response delays due to Kestrel disposing of resources, but I look forward to hearing the answer from the team.

**Comment by muratg** [comment]
@Tratcher @halter73 Any thoughts on this one?

@mikes-gh Did you get a chance to test with a newer OS?  I remember hearing some issues with 2008 R2 but not sure if they're related to Kestrel unloading resources rather quickly.

**Comment by mikes-gh** [comment]
@muratg Sorry I only have 2008 r2 IIS 7.5 but I have the latest Platform handler.
Happy to dig into this if someone can give me some hints as to where to start.as first hit (first impressions) are important.

**Comment by Tratcher** [comment]
It wouldn't be dnx or kestrel voluntarily shutting down, it would be HttpPlatformHandler or IIS killing the process. @pakrym want to play with it?

**Comment by muratg** [comment]
Assigning to @pakrym for investigation.

**Comment by mikes-gh** [comment]
In the Application Event Log I have regular occurrences of this

Faulting application name: w3wp.exe, version: 7.5.7601.17514, time stamp: 0x4ce7afa2
Faulting module name: ntdll.dll, version: 6.1.7601.18933, time stamp: 0x55a6a196
Exception code: 0xc000070a
Fault offset: 0x000000000006298a
Faulting process id: 0x380
Faulting application start time: 0x01d1377a20bc09b6
Faulting application path: c:\windows\system32\inetsrv\w3wp.exe
Faulting module path: C:\Windows\SYSTEM32\ntdll.dll
Report Id: d9e22b37-a377-11e5-9084-00155d016705

Which probably explains what I'm seeing.  The thing is I am using form authentication so not sure how ntdll.dll is getting involved.

Thanks

Mike

**Comment by mikes-gh** [comment]
OK looks like platform handler is recycling the process every 20 mins

```
The description for Event ID 1001 from source HttpPlatformHandler cannot be found. Either the component that raises this event is not installed on your local computer or the installation is corrupted. You can install or repair the component on the local computer.

If the event originated on another computer, the display information had to be saved with the event.

The following information was included with the event: 

Process '1956' started successfully and is listening on port '14856'.
```
Its as if it is trying to honour timeout and always running at the same time.
So it looks like HTTP Platform handler is using the idle timeout of 20 mins when always running is set.
When the idle timeout is reached it seems to start a new process as if it was recycling app pool.
However Apppool recycling  is set to 1740 mins (29 hours).

I will set idle timeout to 0 and see what happens

**Comment by GuardRex** [comment]
@mikes-gh The first one is a known issue and perhaps unrelated to the second one (the w3wp.exe crash). https://github.com/aspnet/IISIntegration/issues/32#issuecomment-156497256

**Comment by mikes-gh** [comment]
@GuardRex 

The facts as I see them

The idle timeout should not be used when Always Running is true.

Setting the idletimeout to 0 resolves the issue of the apppool recycling every 20 mins.

This seems like a bug (potentially been there before Platform handler existed).

It seems that setting AlwaysRunning = true without setting the idletimeout to 0 results in the app recycling every idle timeout.  This is not desired.
We have Apppool recylcling (default 1740 mins) for that.

Desired behaviour would be

Setting AlwaysRunning=true should ignore ideltimeout

They are mutually exclusive

**Comment by GuardRex** [comment]
@mikes-gh 

> The idle timeout should not be used when Always Running is true.

I agree ... but I would say "shouldn't need to be used" given what MS has published.

> Setting the idletimeout to 0 resolves the issue of the apppool recycling every 20 mins.

I agree.

> It seems that setting AlwaysRunning = true without setting the idletimeout to 0 results in the app recycling every idle timeout.

Yeah. I agree. That matches what others have reported ... it's broken somehow.

... and here's a tidbit ... I made sure the Idle Time-out was 0 (zero) ... and the apps are still throwing that "Event ID 1001" entry ... so ... it feels like it's request-based. It's not an AppPool doing something kind of a thing as far as I can guess from the behavior. It's more of a module-thing. They're getting back to it in January. I'm sure they'll sort this out in short order. The w3wp.exe crashing bit ... I'd sort of like to see that. I might just spin up a 2008 VM just for kicks to see that (if I have time).

**Comment by mikes-gh** [comment]
The w3wp crash occurs a few seconds before the "platform handler event 1001" log when it restarts the process.  Presumably due to an unclean shutdown.

Doesn't happen all the time though so probably some sort of load or timing thing at that point of shutting down..

If anyone directly involved with IIS needs any more info I am happy to help.

**Comment by GuardRex** [comment]
@mikes-gh Just curious:
```
Visual C++ Redistributable for Visual Studio 2012 Update 4
```
... is installed on your server?

**Comment by mikes-gh** [comment]
I have

VC++ 2010 10.0.40219 listed in control panel

**Comment by GuardRex** [comment]
@mikes-gh They put this in the instructions ...

> On Windows 7 and Windows Server 2008 R2 you will also need to install the Visual C++ Redistributable for Visual Studio 2012 Update 4.

https://www.microsoft.com/en-us/download/confirmation.aspx?id=30679

... maybe worth a shot?

**Comment by mikes-gh** [comment]
Ok I missed that.  I just llooked at the platform handler download and couldn't see any read me or instructions.  Where are they?

**Comment by GuardRex** [comment]
I think that shows up under the docs.asp.net in the install for Windows doc
in the getting started section.

Just a shot in the dark on it stopping that proc crash ... maybe that
explains it. If so, well have to add a note to the iis doc.

**Comment by mikes-gh** [comment]
Can't find it in the docs either can you post link.

**Comment by GuardRex** [comment]
@mikes-gh Sorry. I was out of the office and trying to type on that tiny cell phone screen.

Here is it is: https://docs.asp.net/en/latest/getting-started/installing-on-windows.html

In the *Install ASP.NET 5 with Visual Studio* section; however, it looks like this is for development purposes only (i.e., even the name "Visual C++ Redistributable for Visual Studio 2012 Update 4" implies that). It probably won't work ... buy maybe worth a shot just for kicks.

**Comment by mikes-gh** [comment]
Ok. I can try that but if   It would be nice to have a diffinitive answer on whether that's a tooling dependency or not.  If it's I runtime dependency then the platform installer should also install it.

**Comment by GuardRex** [comment]
@mikes-gh I'm just kind'a curious what version of of the VC++ it puts on there ... does it come in above VC++ 2010 10.0.40219 that you're seeing. Additionally, does that then have something to do with the module such that the proc stops crashing. This is all highly unlikely, of course. Even it does jack up the VC++, it prob won't help.

I'd run it myself, but I would need to spin up a 2008R2 VM, and I'm trying to get an app pushed further to completion. If you don't want to try it, let me know, and I'll do it tonight to see what's what ... (1) to repro what you're seeing with the crash on 2008R2, (2) to see what installing this would do.

**Comment by mikes-gh** [comment]
Hi it's on a production box so I guess I'm always looking to justify any software install.  Hope that doesn't look like I am not listening to advice.

**Comment by GuardRex** [comment]
@mikes-gh No, no, I understand completely. I'm *exactly* the same way on that. I even wrote that PowerShell publish script so I could try not to have to stick with WebDeploy and muck up my machines with WebDeploy dependencies.

I'm going to play with it tonight ... I'll report back ---

**Comment by GuardRex** [comment]
@mikes-gh I spun up an Azure 2008R2 VM ... configured ... tested with a middleware test app ... I can't reproduce process crashing behavior. The "The description for Event ID 1001" thing is there, but that's a well-known harmless issue.

I'd recommend spinning up an Azure VM and testing your app(s) (one at a time if there are several). If the process crash goes away on the Azure VM, it would narrow it down to something hokey with the module, IIS, or OS on your current server.

[The the VC++ thing is just a slightly misleading/confusing line in the setup steps. I opened https://github.com/aspnet/Docs/issues/816 to see if they want to add a note there.]

**Comment by mikes-gh** [comment]
My app has been running fine for a while now.  The idle timeout being used with always running for the app pool is a bug but I guess that belongs somewhere else.  If someone @Tratcher ? could let the IIS team know.
The crashing I can't repro with consistency for now and I am on the rc2 train so Kestrel is still changing.
Closing to avoid noise.

**Comment by jurijzilcov** [comment]
For those who is on ASP.NET Core it is easy to see that the dotnet.exe process auto-terminates - use TcpView (from sysinternals suite).
Same way, you will see that accessing IIS web site after the time-out will start up a new process of the dotnet.exe.
