### ISSUE TITLE
Main method not called

### ISSUE THREAD

**Issue by christiannagel** [aspnet/Hosting#524]
With the RC1 change, a Main method was added. The compiler complains fine if emitEntryPoint is set to true, and the method is missing. However, I could not find a way to have the Main method invoked. I can have an empty implementation, and the Web application is still running fine. 
I tried this with Kestrel and IISExpress.

Version "1.0.0-rc1-update1" from global.json.

Thanks,
Christian

**Comment by brockallen** [comment]
It's there for something coming in RC2.

**Comment by christiannagel** [comment]
Thanks Brock!

**Comment by Tratcher** [comment]
It would be called if you changed the command in your project.json from "Microsoft.AspNet.Server.Kestrel" to "MyWebApplication" (or whatever you named your project). Note you'll need to specify Microsoft.AspNet.Server.Kestrel as your server via command line or config file. Most people are still using the program main in Hosting or Kestrel.

**Comment by christiannagel** [comment]
Yes, now it's working, thanks! Will this behavior be changed with RTM?

**Comment by Tratcher** [comment]
In RC2 the commands are going away and we'll just call your Main method.
