### ISSUE TITLE
WEC2013

### ISSUE THREAD

**Issue by GerhardKreuzer** [aspnet/Hosting#526]
Hi,

is there any chance to run a Web Application (html5, MVC 6, SignalR, Bootstrap) on a WEC2013 system?
No I want compete to a server farm, I just want to add an UI to my measurement system running on a SoC (System on a chip)

Thanks a lot for helping.

With best trgards

Gerhard

**Comment by muratg** [comment]
We are closing this issue because no further action is planned for this issue. If you still have any issues or questions, please log a new issue with any additional details that you have.
