### ISSUE TITLE
HostingEnvironmentExtensions.MapPath should use IFileProvider

### ISSUE THREAD

**Issue by lodejard** [aspnet/Hosting#527]
The extension method should not use the base physical path and path.combine, it defeats the purpose of having an IFileProvider on the hosting environment interface at all.

Instead it should call GetFileInfo and return fileInfo.PhysicalPath if not null or empty.

**Comment by davidfowl** [comment]
Yap! I also think we should rename MapPath since it's a little misleading https://github.com/aspnet/Hosting/issues/222

**Comment by muratg** [comment]
@Tratcher We can load balance this.

**Comment by Tratcher** [comment]
Here: https://github.com/aspnet/Hosting/blob/f600604140e048df7671fa6e196791492ecacbe1/src/Microsoft.AspNet.Hosting.Abstractions/HostingEnvironmentExtensions.cs#L104-L105

Something like this?
`return hostingEnvironment.WebRootFileProvider.GetFileInfo(virtualPath).PhysicalPath;`

Who are the actual consumers for this API? Is the input expected to be something like `httpContext.Request.Path`?

**Comment by muratg** [comment]
Moving this to Backlog as we will be in RC2 ask mode very soon.  If you feel strongly about this issue, please ping me.

**Comment by lodejard** [comment]
Backlog is fine. It's also behavior rather than public API, so a bit less milestone-critical in that way

**Comment by davidfowl** [comment]
We killed this extension method
