### ISSUE TITLE
Remove IHostingEnvironment.Configuration property

### ISSUE THREAD

**Issue by lodejard** [aspnet/Hosting#528]
The fact that the hosting engine uses iconfiguration to grab some options at startup is its own business. It doesn't even need to be closed over after the builder/application start has completed.

There's nothing an application would correctly do while poking around or grabbing settings from the hosting engine's configuration sources.

**Comment by Tratcher** [comment]
https://github.com/aspnet/Hosting/issues/488
Command line args was one example.

**Comment by davidfowl** [comment]
It's a really nice way to flow arbitrary config from the hosting API to the app

**Comment by lodejard** [comment]
Nope. It's a really bad way to make people think it's a good idea to use `Hosting.json` and hostingEnvironment.Configuration as the new "System.Configuration" singleton. `Hosting.json` is only to configure hosting, it's not the aspnet5 version of appSettings.

@Tratcher command line args are better handled with `.AddCommandLine(Environment.GetCommandLineArgs())` because the application will almost certainly have a different set of cli-friendly switch aliases for their configuration settings.

This property absolutely must be removed. It's an actively incorrect thing to use.

**Comment by Tratcher** [comment]
`Environment.GetCommandLineArgs()` isn't available on CoreCLR, correct?

**Comment by lodejard** [comment]
Seemed to be, in the dnxcore tfm at least, which I think is the same as coreclr for that Type

Sent from mobile device
________________________________

**Comment by davidfowl** [comment]
> Nope. It's a really bad way to make people think it's a good idea to use Hosting.json and hostingEnvironment.Configuration as the new "System.Configuration" singleton. Hosting.json is only to configure hosting, it's not the aspnet5 version of appSettings.

I disagree. If you look at WebApplicationBuilder without `hosting.json`, it's an API that can be used to set arbitrary settings that need to flow to the application.  

> @Tratcher command line args are better handled with .AddCommandLine(Environment.GetCommandLineArgs()) because the application will almost certainly have a different set of cli-friendly switch aliases for their configuration settings.

That doesn't even work because the first arg is the application name, so it's really `.AddCommandLine(Environment.GetCommandLineArgs().Skip(1).ToArray())`

> This property absolutely must be removed. It's an actively incorrect thing to use.

I don't see why.

/cc @DamianEdwards

**Comment by lodejard** [comment]
I totally get the motivation, but there are a dozen ways to pass references from-code-to-code that don't involve an IConfiguration on IHostingEnvironment.

It's confusing to have templates which show a configuration loaded in startup constructor, and have a configuration passed on hosting environment which is ignored.

Unless the template has also been changed to move the configuration loading outside of the startup class? In which case hosting shouldn't be connected to a hosting.json be default.

The connection-by-default was only necessary for the case when no user code ran before startup was loaded.

**Comment by lodejard** [comment]
Lets talk when you're back in the states :)

**Comment by davidfowl** [comment]
Sure but API freeze is coming up soon. So we should remove it and have examples on how to do it if we're going to do it

**Comment by lodejard** [comment]
Recommendation:

```cs
  interface IHostingEnvironment 
  {
    <doc>Contains the command-line arguments which pass through to the application.
    Arguments and switches which were consumed by runtime and hosting are not present 
    in this list.</doc>
    string[] ApplicationArguments;
  }
```

**Comment by muratg** [comment]
Moving this to Backlog as we will be in RC2 ask mode very soon.  If you feel strongly about this issue, please ping me.

**Comment by muratg** [comment]
@lodejard @davidfowl Louis brought this back, do we have anything else to discuss about this?

Once we have a closed design, @JunTaoLuo can take this.

**Comment by muratg** [comment]
@lodejard @Eilon mentioned that you can take this one.

**Comment by lodejard** [comment]
Sure - assuming we're all signed off on the change
