### ISSUE TITLE
Rename "exclude" to "compileExclude" in "project.json" so its intent becomes crystal clear.

### ISSUE THREAD

**Issue by rustd** [aspnet/Hosting#538]
Porting this issue from ASP.NET UserVoice site https://aspnet.uservoice.com/forums/41199-general-asp-net/suggestions/9013414-rename-exclude-to-compileexclude-in-project-j#/duplicates

Please triage as appropriate.

Rename "exclude" to "compileExclude" in "project.json" so its intent becomes crystal clear.

For instance, "publishExclude" in "project.json" is crystal clear.

**Comment by muratg** [comment]
@davidfowl What do you think?

**Comment by muratg** [comment]
dotnet CLI + templates?

**Comment by davidfowl** [comment]
2 things:
1. No, exclude is actually more than just compileExclude (and has been that way since like beta5). We could add compileExclude but renaming it wouldn't make any sense.
2. This is in the wrong repository.
