### ISSUE TITLE
Reverse forwarders requirement for WS 2016 TP4 Nano Server?

### ISSUE THREAD

**Issue by GuardRex** [aspnet/Hosting#539]
@Tratcher @moozzyk 

RE: http://stackoverflow.com/questions/33467943/running-asp-net-5-on-nano-server-throws-unable-to-load-dll-kernel32

Reverse forwarders were required for hosting Kestrel on Nano as of November 17, when that SO question was answered. WS 2016 TP4 was released (according to the release notes) a few days after that on the 19th. Just checking: Are reverse forwarders required with TP4? If so, is this requirement going to persist into RTM for Nano?

**Comment by muratg** [comment]
@moozzyk Could you have a look?

**Comment by GuardRex** [comment]
@moozzyk I opened a cross-post to IIS and WS about my hunch that there will be a special version of the `HttpPlatformHandler` for IIS 10/Nano or perhaps bits I didn't install for v1.2 on Nano Server (e.g., registry keys, etc.). If there's any info on this, I'd love to get a .NET 5 test app running on Nano and notes/steps over to @Rick-Anderson on it. https://github.com/aspnet/Docs/issues/194 If there is nothing on this and no chance of getting it to work right now, I'll close and re-open later.

http://forums.iis.net/t/1229557.aspx?Is+there+a+new+version+of+the+HttpPlatformHandler+for+IIS+10+Nano+Server

https://social.technet.microsoft.com/Forums/windowsserver/en-US/09ad731f-ef8a-43d0-afc8-0fe6229ac741/is-there-a-new-version-of-the-httpplatformhandler-for-iis-10-for-nano-server?forum=NanoServer

**Comment by moozzyk** [comment]
@GuardRex - HttpPlatformHandler is one thing that needs reverse forwarders but Kestrel (or to be more accurate libuv.dll) is the other. A PR to libuv would be required to fix this. I think there were ~20 calls to Win API that needed to be replaced to be able to compile libuv.dll against onecore.lib

**Comment by GuardRex** [comment]
@moozzyk Ah! That explains it ... why the module runs in a docker container on Nano but not on Nano itself.

Let me ask another one: I can't tell from what's been put online thus far if either (or both) the Nano cats and the IIS cats (not to mention the .NET 5 cats) would prefer all .NET 5 apps run with the container model ... OR ... is it just that the container model is being discussed openly (forums, docs, Channel 9) because it's the only thing available right now for .NET 5/HttpPlatformHandler/IIS/Nano.

My personal opinion is that a lot of folks are **not** going to want containers (count me in that group ... I personally don't want containers) ... a lot will ... but a lot won't. Both stories will probably need to be told eventually. What's your opinion on the "NO containers please" scenario, and do you think MS generally is going to be pushing the container scenario hard?

Whatever the case with containers, I'm going to make a first run at notes/steps for docs based on the container approach, since that's all we have right now that works (besides WebListener or triggering `web.cmd` directly, both of which probably aren't a good basis for the best practices scenario in docs).

**Comment by GuardRex** [comment]
@moozzyk Very interesting ... David So just said it **will** work in a non-container scenario. He sent me steps that he plans to publish to iis.net soon. I'm going to try to replicate what he did here and see if I can get some Nano Server love. I'll leave this open just a little longer while I see how things go.

**Comment by GuardRex** [comment]
@moozzyk He says he thinks this has to do with OneCore compliance and that Reverse Forwarders will be required for the time-being. He implies that with changes to libuv that Reverse Forwarders will not be required at some point in the future.

**May the Server Gods smile on me!** I'm going to hit this hard in the morning. :punch: :punch: :punch:

**Comment by GuardRex** [comment]
@moozzyk GOT IT! It's working now ... with the Reverse Forwarders package. I'm good! :smile: Thanks for your help.

**Comment by moozzyk** [comment]
@GuardRex - glad you got it working! 
FYI - I haven't tried containers with nano - I typically just published my app and xcopied to the server but I think there will be people who will want to use containers.

**Comment by GuardRex** [comment]
@moozzyk I agree. I was going to pitch to @Rick-Anderson and @danroth27 the idea that a second doc be the "containers version" for Nano. On the hand, it could be just a section (albeit a bit of a long section) in the one doc that they slated. I'll ref your comment over there now.

**Comment by GuardRex** [comment]
@moozzyk I need to go back and watch this again ...

https://channel9.msdn.com/Series/Nano-Server-Team/Demo-Nano-Server-in-a-Container-running-IIS-ASPNET5

... but I think the deltas are large enough that it would be kind'a rough trying to shoehorn that into the non-container doc. You might want to open an issue. One thing for sure, I'll add this video reference in its own section to the doc I wrote and explain (briefly) the detlas to the process (if I can).
