### ISSUE TITLE
Deployment to IIS 8 does not work properly！

### ISSUE THREAD

**Issue by lataing** [aspnet/Hosting#540]
I use Visual Studio 2015 to create ASP.NET 5, is operating normally.
But deploy to native IIS, visit for a long time to load, and then displays a blank.

I press https://docs.asp.net/en/latest/publishing/iis.html said.
HTTP Platform Handler installed and properly configured IIS.

**Comment by GuardRex** [comment]
@lataing I have an issue comment that might have some info to help you: https://github.com/aspnet/Hosting/issues/364#issuecomment-148567294

What is your runtime? If you are on RC2 bits, you'll need to take into account the new Hosting changes:

https://github.com/aspnet/Hosting/issues/530
https://github.com/aspnet/IISIntegration/tree/dev/samples/IISSample

**Comment by lataing** [comment]
global.json content:
{
  "projects": [ "src", "test" ],
  "sdk": {
    "version": "1.0.0-rc1-update1"
  }
}

**Comment by GuardRex** [comment]
@lataing ... and your packages are all `-rc1-final`?

**Comment by lataing** [comment]
I was using ASP.NET5 to create the VS2015, and I did not make any changes.
Operation steps:

1.Server2012 Windows

2.Install IIS

3.install 64 HTTP Platform Handler bit

4.set  system.webServer/handlers  to Unlock Section

5.IIS Manager In create a new web site and set the physical path to wwwroot.

6.The application pool to No Managed Code Set

**Comment by GuardRex** [comment]
@lataing What are the dependencies in your `project.json` file?

... also ... set `stdoutLogEnabled="true"` in `web.config` and see if you're getting something in the log when you make a request to the app.

**Comment by lataing** [comment]
I re create a simple ASP.NET5, do the normal operation of the VS2015. Using Web.cmd can also be normal operation. But IIS is always in loading state, as the network is slow, has been circling.

I uploaded my source code, you can help me to see it?


[HelloASP5.zip](https://github.com/aspnet/Hosting/files/73013/HelloASP5.zip)

**Comment by lataing** [comment]
I set the stdoutLogEnabled= "true", but did not produce any diary.

**Comment by GuardRex** [comment]
Are you moving the published output from here ...
```
..\..\artifacts\bin\HelloASP5\Release\PublishOutput
```
... to the server?

**Comment by lataing** [comment]
I uploaded the copy from the..\..\artifacts\bin\HelloASP5\Release\PublishOutput, and put it into the C:\inetpub\wwwroot\HelloASP5.

Set physical path to C:\inetpub\wwwroot\HelloASP5\wwwroot.

**Comment by lataing** [comment]
I did not change the release path, I just copied from PublishOutput a to C, used to deploy IIS

**Comment by GuardRex** [comment]
Oh, no ... that's not what I meant ...

You just put the `wwwroot`, `approot`, and `logs` folders into a folder on the server, then point the physical path in IIS to the `wwwroot` folder. Since I can't see your folder structure from here, I just wanted to make sure you had the folders in the right spot on the server.

I'm going to publish your project here to one of my VM's to see what it's doing. brb

**Comment by lataing** [comment]
Yes, that's right.

The physical path I set up in IIS is my HelloASP5..

Thank you very much for helping me with this problem. This problem has troubled me for a long time, I even the most basic deployment can not be successful.

**Comment by GuardRex** [comment]
There is something funky with this project sample ... I can't even get it to compile as you sent it. I think this project sample is broken the way it is.

Try one of the official samples at https://github.com/aspnet/Home/tree/dev/samples/1.0.0-rc1-update1

Also, I noticed that in your publish profile you didn't check the box for compiling into a NuGet package. Check that box when you publish to the filesystem. Then, move the published folders and files to your IIS server and point to `wwwroot` from there.

![capture](https://cloud.githubusercontent.com/assets/1622880/12015841/64c93214-acf7-11e5-8d90-a53fe1635d7e.PNG)

**Comment by lataing** [comment]
Sorry, I sent the above is already released, used to deploy the code.

[HelloASP5 Source.zip](https://github.com/aspnet/Hosting/files/73050/HelloASP5.Source.zip)
I have uploaded a copy of all the source code.Help me to see if it can be properly compiled?
Thank you.

**Comment by GuardRex** [comment]
Looks ok. 

When you publish, check the box for `Compile source files into NuGet packages` to get the fully published project. Then, try that on the server. It should work.

**Comment by lataing** [comment]
I just tested, according to the way you provided, check the two, and uploaded to my Server Windows 2012 test, is still the same situation.
[PublishOutput.zip](https://github.com/aspnet/Hosting/files/73063/PublishOutput.zip)

**Comment by GuardRex** [comment]
Yes, the published output looks good.

Check the version of the HttpPlatformHandler: Go to `Control Panel > Programs > Programs and Features` and confirm it says "v1.2" in the name.

Also, check the bindings of your IIS website ... did you bind to a domain? ... or to just *:80 (the default website)?

**Comment by lataing** [comment]
Help me take a look at the screenshot below
![5](https://cloud.githubusercontent.com/assets/3190530/12016607/3143b9f0-ad88-11e5-88d3-70e96000eadb.png)
![4](https://cloud.githubusercontent.com/assets/3190530/12016609/36c180ce-ad88-11e5-8250-66be37caa820.png)
![1](https://cloud.githubusercontent.com/assets/3190530/12016613/410a9052-ad88-11e5-8b90-9df6700c4db2.png)
![2](https://cloud.githubusercontent.com/assets/3190530/12016614/445107be-ad88-11e5-8fc1-77faaaac0013.png)
![3](https://cloud.githubusercontent.com/assets/3190530/12016617/48766c94-ad88-11e5-867f-b94f2c563921.png)

**Comment by GuardRex** [comment]
For unlocking the `webServer.handlers` section of `web.config`, that's the wrong spot. Click on the name of the server `WIN-59ND1RB4ADN` ... then, double-click on `Configuration Editor` ... then, on the right under `Section` click to `Unlock Section`.

**Comment by lataing** [comment]
Is that right?
![8](https://cloud.githubusercontent.com/assets/3190530/12016734/a7d5ea7e-ad89-11e5-9797-e3462570de51.png)



I feel ASP.NET5 no problem, it should be the problem of IIS. Because I run directly through the Web.cmd normal.

**Comment by GuardRex** [comment]
Good. How about router and firewall ... port 80 open on both?

**Comment by lataing** [comment]
I see. It's really successful.
![9](https://cloud.githubusercontent.com/assets/3190530/12016752/eb190320-ad89-11e5-97ef-78f85cbcaff8.png)

I'm close to the firewall.
![10](https://cloud.githubusercontent.com/assets/3190530/12016789/584992de-ad8a-11e5-904b-eacaeef5709a.png)

I was enabled on a website, and I was doing a local visit to my website.
http://localhost

**Comment by lataing** [comment]
I set to 5005, the same can not run
![11](https://cloud.githubusercontent.com/assets/3190530/12016847/e5532adc-ad8a-11e5-8e92-bcf5367a7c4f.png)

**Comment by GuardRex** [comment]
Hummmmmm..... You should have been able to browse the site on the server at http://localhost when you had it at port 80.

Before you setup this app and the `Default Web Site` was sitting on port 80, was IIS able to serve the default website?

**Comment by GuardRex** [comment]
Check your Event Viewer Application log for anything. Also check your `C:\inetpub\logs\LogFiles` logs and see if these requests are even making it to IIS.

**Comment by GuardRex** [comment]
You should see something like this in IIS logs when it processes a request for the default web site ...
```
2015-12-06 22:19:26 100.76.158.83 GET / - 80 - XX.XXX.XXX.XX Mozilla/5.0+(Windows+NT+10.0;+WOW64)+AppleWebKit/537.36+(KHTML,+like+Gecko)+Chrome/46.0.2490.86+Safari/537.36 - 200 0 0 14196
```

**Comment by GuardRex** [comment]
I'm loading your `PublishOutput` on one of my Azure VM's to see if it will run here.

**Comment by GuardRex** [comment]
Oh ... something else just occurred to me. This is a 32-bit app ... did you set the AppPool to enable for 32-bit apps?

![capture](https://cloud.githubusercontent.com/assets/1622880/12017206/cbbaf668-ad08-11e5-8b36-cb4b604f4e22.PNG)

**Comment by GuardRex** [comment]
Your app **does** run on my Azure VM. It's gotta be something in your IIS settings.

**Comment by GuardRex** [comment]
:beers: all around on that one! I'm headed to slumberland ... @davidfowl or @Tratcher or one of the other cats will jump in to help with this one. Hang in there ... I'm pull'in for ya!

"Just remember what ol' Jack Burton does when the Earth quakes, and the poison arrows fall from the sky, and the pillars of heaven shake. Yeah, Jack Burton just looks that big ol' storm right square in the eye and he says, 'Give me your best shot, pal. I can take it.'" - Jack Burton (Kurt Russell) [Big Trouble in Little China](http://www.imdb.com/title/tt0090728/?ref_=nm_flmg_act_33), 1986 

![jack](https://cloud.githubusercontent.com/assets/1622880/12017416/f7e854a4-ad0a-11e5-8be5-f4e5f6386625.jpg)

**Comment by lataing** [comment]
Still unable to run successfully.I use the virtual machine installed Server Windows 2012 and windows 10, using IIS8 and IIS10. but are the same results.

Set Enable 32-Bit applications  to ture is not running.

**Comment by GuardRex** [comment]
@lataing Did you find out if your IIS could serve a normal (not .NET 5) website ... just return a basic `index.htm`, `iisstart.htm`, or some other static file from the `Default Web Site`? Did you see anything in the W3SVC logs for requests? Is there anything interesting in the Event Viewer?

**Comment by muratg** [comment]
@Tratcher Could you investigate?

**Comment by lataing** [comment]
Yes, normal. I do add IIS to test the default site, I can access the normal.

**Comment by GuardRex** [comment]
@lataing Perhaps the `HttpPlatformHandler` install is bad ... try uninstalling it in Programs and Features and re-installing it. The 64-bit version is here: http://go.microsoft.com/fwlink/?LinkID=690721

**Comment by lataing** [comment]
Yes, I downloaded it.
![20](https://cloud.githubusercontent.com/assets/3190530/12028256/5855711e-ae0f-11e5-8f35-c72085317393.png)
![21](https://cloud.githubusercontent.com/assets/3190530/12028259/5c66c884-ae0f-11e5-90c4-132b81c9cc99.png)

**Comment by GuardRex** [comment]
If you re-install the module and the .NET 5 app is still not responding, then I would think this is a deeper problem with your IIS ... a corrupt metabase or something??? @Tratcher, I've worked through all of the known issues with @lataing, and I know the app works (I ran it on one of my Azure WS 2012 VM's). I can only point to general IIS troubleshooting at this point.

**Comment by lataing** [comment]
Thank you very much for your patience to help me solve the problem.

I think it is also a question of IIS, because I use Web.cmd to run the site is normal.

I'm trying to reinstall my system to test it again.

**Comment by GuardRex** [comment]
np ... sorry it's still giving you trouble. If there is anything else I can do, give me a yell.

**Comment by lataing** [comment]
I don't know why, I reinstall the system, using Windows 10
First install .NET Framework 3.5 before installing IIS, the website can run normally.
![1111](https://cloud.githubusercontent.com/assets/3190530/12032222/d13088d0-ae50-11e5-99ef-8550bf9a94a1.png)
But Server Windows 2012 still does not work.

**Comment by markusvt** [comment]
I had a similar problem and found out the following: I had to name the publish-folder on the server "wwwroot". If it has another Name, like the Project Name, the Webserver will create an empty folder called "wwwroot" and that "blank site never loading" thing occurs. 
So if I deploy into a "wwwroot" folder, the "approot" folder is generated during deploy and everythings works fine. 
Is it maybe possible to remove that "wwwroot" restriction, so that you can name the folder whatever you like?

**Comment by KyleGobel** [comment]
Just FYI I had a similar problem with the very long "loading" problem.

Mine was I copied over the files from a network location (Amazon S3) and forgot to unblock them.

![image](https://cloud.githubusercontent.com/assets/4460054/12898663/e83d4f68-ce7b-11e5-9e91-c4eed18952e4.png)
