### ISSUE TITLE
Option to not handle exceptions thrown during bootstrapping (Startup.cs)

### ISSUE THREAD

**Issue by kcraft** [aspnet/Hosting#551]
I am running my .NET app inside of a containerized environment where I don't have control over the order that my app's dependencies start up (databases and such). I intentionally want my container to fail to start if my app cannot connect to its dependencies during startup. The container runtime will take care of retrying until it works. However, ASP.NET seems to absorb any exceptions that are thrown during startup and reports that it started up successfully anyway. From looking at the code, it seems that "captureStartupErrors" is hardcoded to "true". I would like an option to disable this behavior.

**Comment by Tratcher** [comment]
@JunTaoLuo changed this in RC2, it's now a configuration option. It's currently disabled by default but we plan to turn it back on. https://github.com/aspnet/Hosting/issues/552

**Comment by kcraft** [comment]
Ah, great. Thank you! I'll go ahead and close this, then.
