### ISSUE TITLE
Possibility to host WCF service on ASP.NET 5

### ISSUE THREAD

**Issue by Centurys** [aspnet/Hosting#558]
Hi,

we have legacy system that uses WCF SOAP services, and we thinking about migrating projects to new ASP.NET 5 project system, because it's way better :)
We want to use ASP.NET 5 project system (xproj) and develop rest API, but we also want to have side by side in same project legacy WCF service for backward compatibility. Yes for this project we will use only full .NET 4.6 runtime. We know that it could be done with 2 different project and host on two different virtual apps on IIS.

Is there a easy way to achieve that WCF service and ASP.NET 5 web API would run on one web app (source code sample would by amazing)?

**Comment by aL3891** [comment]
Hello :)

There is no build in way of hosting wcf services in asp.net 5 and i don't think there are any immediate plans to make one either, at least not one that supports all the stuff wcf supports, like diffrent transports and things like that. (and i'm pretty sure that will never happen)

The asp.net 5 architecture is very (very) extensible though, so someone could write some asp.net 5 middleware that exposed a soap service. A general soap middleware might be a bit more work though..

**Comment by muratg** [comment]
@aL3891 is spot on :)
