### ISSUE TITLE
Consider changing WebApplication* to WebHost*

### ISSUE THREAD

**Issue by davidfowl** [aspnet/Hosting#567]
We have `IWebApplicationBuilder`, `WebApplicationBuilder`, `IWebApplication`, and `IApplicationBuilder`.

`IApplicationBuilder` looks related to `IWebApplicationBuilder` but they are not. 

Today:

```C#
var app = new WebApplicationBuilder()
                        .UseServer("Microsoft.AspNet.Server.Kestrel")
                        .UseUrls("http://localhost:5001")
                        .UseStartup<Startup>()
                        .Build();

app.Run();
```

Potentially changed to:

```C#
var host = new WebHostBuilder()
                        .UseServer("Microsoft.AspNet.Server.Kestrel")
                        .UseUrls("http://localhost:5001")
                        .UseStartup<Startup>()
                        .Build();

host.Run();
```

`IWebHostBuilder` builds the `IWebHost`

/cc @lodejard @Tratcher @JunTaoLuo @DamianEdwards  Thoughts? I'm not 100% on the naming though and I also don't think this matters that much but think about it a little :smile: 

This *is* the hosting repository and we are *hosting* ASP.NET so it sorta makes sense.

**Comment by Tratcher** [comment]
I do agree there's ambiguity between IWebApplicationBuilder and IApplicationBuilder.

**Comment by davidfowl** [comment]
Shall we go with host instead of application then?

**Comment by Tratcher** [comment]
You're with @DamianEdwards right? Did he have anything to say on the subject?

I think it's fine, but I don't envy @JunTaoLuo having to touch all the repos again.

**Comment by davidfowl** [comment]
Yes, we spoke about this today and concluded that it looks like WebApplication was wrong.

**Comment by mikes-gh** [comment]
Would that mean also changing WebApplicationConfiguration to WebHostConfiguration?

**Comment by davidfowl** [comment]
@mikes-gh yes re: `WebHostConfiguration`

**Comment by mikes-gh** [comment]
@davidfowl 
```
WebHostBuilder
WebHostConfiguration
```
vs
```
WebHostingBuilder
WebHostingConfiguration
```
The later seems slightly more abstracted to me

**Comment by davidfowl** [comment]
I dunno what you mean by more abstracted. I prefer:

I prefer a `WebHostBuilder` that builds a  `WebHost` using `WebHostConfiguration`

**Comment by mikes-gh** [comment]
WebHost is fine.

**Comment by davidfowl** [comment]
PS: @JunTaoLuo I'm sorry dude, that's alot of repos to update :disappointed:

**Comment by mikes-gh** [comment]
WebHostConfiguration would read hosting.json seems a mismatch
WebHostingConfiguration would seem a more logically. match..

**Comment by davidfowl** [comment]
But we're going to call it `WebHostConfiguration` so it matches the other names. We're splitting hairs and naming is hard but that's what we're calling it.

**Comment by aL3891** [comment]
Maybe hosting.json could be host.json? (or webhost.json)

**Comment by henkmollema** [comment]
`hosting.json` configures the hosting API. Webhost is just a part of that. It's not like we're renaming the repo to Webhost.

**Comment by JunTaoLuo** [comment]
Marking as done since rename has been merged to dev and all repos have been updated. Will post announcement after monitoring test pass and close issue.

**Comment by GuardRex** [comment]
@JunTaoLuo Suggestion: Due to the slight lag in MyGet, you might want to say it will be for (if I have this correct, of course) ...

> Microsoft.AspNet.Hosting rc2-16219 and later. Microsoft.AspNet.IISIntegration rc2-16132 and later

... according to @Tratcher https://github.com/aspnet/IISIntegration/issues/52#issuecomment-171444840

**Comment by mikes-gh** [comment]
@JunTaoLuo 
Looks like aspnet/Security is failing after this

**Comment by davidfowl** [comment]
What is failing?

**Comment by mikes-gh** [comment]
Microsoft.AspNet.Authentication.Test 

I noticed because I have a pull request for FacebookMiddleware

```
[00:05:14] Compiling 
[00:05:14] Microsoft.AspNet.Authentication.Test
[00:05:14]  for 
[00:05:14] DNX,Version=v4.5.1
[00:05:14] 
[00:05:17] [1m[31mC:\projects\security\test\Microsoft.AspNet.Authentication.Test\test\Microsoft.AspNet.Authentication.Test\Twitter\TwitterMiddlewareTests.cs(155,31): error CS0246: The type or namespace name 'WebHostBuilder' could not be found (are you missing a usi
[00:05:17] ng directive or an assembly reference?)
[00:05:17] 
[00:05:17] 
[00:05:17] Compilation failed.
```

**Comment by JunTaoLuo** [comment]
@mikes-gh I think your packages may be out of date and updating to the newest packages should fix the problem. @GuardRex I don't know how feasible listing all the versions is since many packages were affected. I will look into it but at least the renames will impact Microsoft.AspNet.Hosting rc2-16237 or later for sure.

**Comment by JunTaoLuo** [comment]
Seems like test pass will be broken for other reasons. Since I did not see any test failures relating to this change, I'm closing the issue for now.

**Comment by davidfowl** [comment]
:clap:
