### ISSUE TITLE
IsLocal returns false when hosted through the TestServer

### ISSUE THREAD

**Issue by Tratcher** [aspnet/Hosting#570]
_From @fermaem on January 13, 2016 12:47_

The following test fails when ran against rc2. 

Is this considered as a bug? Wouldn't that be the case, could you please help me working around it (maybe through some additional test configuration setup)?

```csharp
using System;
using System.Net;
using System.Net.Http;
using Microsoft.AspNet.Hosting;
using Microsoft.AspNet.TestHost;
using Newtonsoft.Json;
using Microsoft.AspNet.Builder;
using Microsoft.AspNet.Http;
using Xunit;

namespace ClassLibrary1
{
    public class Class
    {
        public class Model
        {
            public string RemoteIPAddress;
            public int RemotePort;
            public string LocalIPAddress;
            public int LocalPort;
            public bool IsLocal;
        }

        [Fact]
        public async void tada()
        {
            var builder = new WebApplicationBuilder()
            .Configure(app =>
            {
                app.Run(async context =>
                {
                    var connection = context.Connection;
                    await context.Response.WriteAsync(JsonConvert.SerializeObject(new Model
                    {
                        RemoteIPAddress = connection.RemoteIpAddress?.ToString(),
                        RemotePort = connection.RemotePort,
                        LocalIPAddress = connection.LocalIpAddress?.ToString(),
                        LocalPort = connection.LocalPort,
                        IsLocal = connection.IsLocal
                    }));
                });
            }); ;

            using (var server = new TestServer(builder))
            using (var client = server.CreateClient())
            {
                var request = new HttpRequestMessage(HttpMethod.Get, new Uri("http://localhost/Huh"));
                request.Headers.Host = request.RequestUri.Host;
                var response = await client.SendAsync(request);
                Assert.Equal(HttpStatusCode.OK, response.StatusCode);
                var body = await response.Content.ReadAsStringAsync();

                var obj = JsonConvert.DeserializeObject<Model>(body);

                Console.WriteLine(body);
                Assert.True(obj.IsLocal);
            }
        }
    }
}
```

Below what the server returns

```json
{
  "RemoteIPAddress":null,
  "RemotePort":0,
  "LocalIPAddress":null,
  "LocalPort":0,"
  IsLocal":false
}
```

/cc @troydai (because of #284)

_Copied from original issue: aspnet/KestrelHttpServer#576_

**Comment by Tratcher** [comment]
_From @troydai on January 13, 2016 19:12_

Thanks for reporting the issue. Can I know the implementation of the `TestServer`? It doesn't seem to be https://github.com/aspnet/KestrelHttpServer/blob/dev/test/Microsoft.AspNet.Server.KestrelTests/TestServer.cs

**Comment by Tratcher** [comment]
This one? https://github.com/aspnet/Hosting/blob/dev/src/Microsoft.AspNet.TestHost/TestServer.cs

**Comment by Tratcher** [comment]
This us unrelated to Kestrel. I really want to remove the IsLocal property, it's misleading.

**Comment by Tratcher** [comment]
_From @fermaem on January 13, 2016 20:5_

Thanks for the feedback.

>Can I know the implementation of the TestServer?

@troydai @Tratcher Indeed this is `Microsoft.AspNet.TestHost.TestServer`

>I really want to remove the IsLocal property, it's misleading.

@Tratcher Any chance you could elaborate further on this?

**Comment by Tratcher** [comment]
_From @troydai on January 13, 2016 22:21_

@fermaem this is not an actual Kestrel issue, since the `TestServer` you're using doesn't use `Kestrel` instead it initialize the default http components like `HttpConnectionFeature` (https://github.com/aspnet/HttpAbstractions/blob/dev/src/Microsoft.AspNet.Http/Features/HttpConnectionFeature.cs). Of which the property value of `IsLocal` is never set, so by default it is `False`. 

For `TestServer` the assumption is that the server code is aware of the situation that `IsLocal` property doesn't provide the most accurate information.

**Comment by Tratcher** [comment]
TestServer Could populate the ips and IsLocal, but with what? Loopbacks?

**Comment by troydai** [comment]
@fermaem Since we know what cause this issue, I'd like to understand the impact before we come up any solution. In your usage of `TestServer`, is the `IsLocal` property so important that it impact your scenario? In the meantime, we don't populate neither address and ports either.

**Comment by fermaem** [comment]
>In your usage of TestServer, is the IsLocal property so important that it impact your scenario?

@troydai Thanks for asking. 

The initial requirements were:
 - The server refuses to serve request over http (and eventually performs http->https redirections for GET requests)
 - It's ok to allow the server to serve requests over http when
  - being ran on a developer's computer
  - the CI server runs integration tests

We relied on `IsLocal` to solve this.

**Comment by Tratcher** [comment]
Ah, we have a different recommendation for those scenarios: Environments. https://github.com/aspnet/Templates/blob/dev/src/BaseTemplates/StarterWeb/Startup.cs#L40-L47.

**Comment by fermaem** [comment]
@Tratcher Makes sense. Considering the requirements, `IsLocal` wasn't the best approach. I've switched to your much more thoughtful proposal.

Sorry for the noise and thanks a lot for the amazing support :heart:

**Comment by troydai** [comment]
@fermaem appreciate the feedback, too.
