### ISSUE TITLE
How to remove the "X-Powered-By" header?

### ISSUE THREAD

**Issue by fermaem** [aspnet/Hosting#571]
We're running a 1.0.0-rc2-16357 mvc application in an Azure web app.

This application is deployed through a _slightly_ patched version of the kudu generated `deploy.cmd` script.
`
What would be the recommended way to remove the "X-Powered-By" header?

**Comment by Eilon** [comment]
Exactly which header is that? The IIS one? ASP.NET?

**Comment by nulltoken** [comment]
the ASP.NET one

**Comment by fermaem** [comment]
The `ASP.NET` one.

In order to get rid of it, I've added to the generated web.config the following.

```xml
<httpProtocol>
  <customHeaders>
    <remove name="X-Powered-By" />
  </customHeaders>
</httpProtocol>
```

Is that the way to go?

**Comment by GuardRex** [comment]
@fermaem Delete it in IIS at the server level ... Click on the server on the left, go to HTTP Response Headers. You can get rid of it there.

![capture](https://cloud.githubusercontent.com/assets/1622880/12396928/ed33e4b4-bdbe-11e5-99e7-0da12dbd33ac.PNG)

**Comment by GuardRex** [comment]
@fermaem Was there one at the ASP.NET level?

**Comment by GuardRex** [comment]
@fermaem The only one I'm getting is from IIS, in which case you prob know to kill it there ...

![capture](https://cloud.githubusercontent.com/assets/1622880/12397070/aa92f310-bdbf-11e5-8f45-0cb096928500.PNG)

**Comment by fermaem** [comment]
@GuardRex Thanks for your answer. 

I'm targeting Azure Web Apps, so I need an approach that doesn't require a direct access to the underlying platform. :wink: 

The web.config thing did the thing. However, I don't know if this is currently the recommended way of doing this in a DNX context. Neither do I know what are the long term plans regarding the underlying hosting provider in Azure web apps (IOW, will this "hack" still work three months from now or will DNX Azure Web Apps be running on top of something different than IIS?).

**Comment by GuardRex** [comment]
@fermaem Ah, I see. It's not only the recommended way for your situation ... but the only way. The `Server` header is one of the ones that can be killed with middleware https://github.com/aspnet/IISIntegration/issues/36 ...
```c#
app.Use((context, next) =>
{
    context.Response.Headers.Remove("Server");
    return next();
});
```
... but the IIS one can't be removed that way. More interesting info on this: It's on the backlog to (probably) not have this `Server` header automatically added or have it switched off in config. See: https://github.com/aspnet/Hosting/issues/327

**Comment by muratg** [comment]
@danroth27 This would require documentation

**Comment by timadamson** [comment]
Is there some way to remove the "X-Powered-By" header in Kestrel?

**Comment by Tratcher** [comment]
@timadamson No, it's added by IIS, you have to remove it via web.config as shown above https://github.com/aspnet/Hosting/issues/571#issuecomment-172480573

You may try just replacing it though.

**Comment by martincostello** [comment]
@timadamson I've done this by removing it before the HTTP response headers in a piece of [custom middleware](https://github.com/martincostello/api/blob/master/src/API/Middleware/CustomHttpHeadersMiddleware.cs#L80). It works for Kestrel and IIS locally, but I haven't gotten it to work in IIS in Azure.

**Comment by martincostello** [comment]
I had this working in RC2, but the behaviour seems to have regressed in RTM.

**Comment by AshkanSecure** [comment]
in insert code but not hidden server and X-Powered-By in header.why?

**Comment by ashishyadav400** [comment]
If you're running website on php add the following in **php.ini** file.
`expose_php = off`
The above line will hide X-Powered-By.

**Comment by RohitPrre** [comment]
i have observed that some of the data/files revealed internal IP address. so want to hide Or Remove Real IP on project . it is in ASP.net

**Comment by TehWardy** [comment]
none of this works for me using .Net Core 2.1

**Comment by martincostello** [comment]
@TehWardy Are you hosting behind IIS or some other reverse proxy?

**Comment by TehWardy** [comment]
I'm just testing this locally at the moment through VS / IIS Express.

I threw this in a new web.config file and I get an exception on load ...
```
  <httpProtocol>
    <customHeaders>
      <add name="X-Frame-Options" value="DENY" />
      <remove name="Server" />
      <remove name="X-Powered-By" />
    </customHeaders>
  </httpProtocol>
```

... i threw this in as the first line in the method ...

```
public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
            app.Use((context, next) =>
            {
                context.Response.OnStarting(() =>
                {
                    context.Response.Headers.Add("X-Frame-Options", "DENY");
                    context.Response.Headers.Remove("Server");
                    context.Response.Headers.Remove("X-Powered-By");
                    context.Response.Headers.Remove("X-SourceFiles");
                    return Task.CompletedTask;
                });

                return next();
            });
          .....

```
... changed nothing ... seems to be executing it but not honouring it.

**Comment by TehWardy** [comment]
Here's the exception i get ...

![image](https://user-images.githubusercontent.com/6891030/43327479-72876256-91b3-11e8-993a-9fc6d8daec0a.png)

**Comment by martincostello** [comment]
Some ASP.NET Core features set `X-Frame-Options` themselves, it's possible an exception is being thrown because you're trying to set it again (I've had this issue [in the past](https://github.com/martincostello/alexa-london-travel-site/blob/76982398b9014096d91617ffd2d35677e78ef6d5/src/LondonTravel.Site/Middleware/CustomHttpHeadersMiddleware.cs#L96-L97)).

To disable the `Server` header from Kestrel, you need to set `AddServerHeader` to `false`: https://github.com/martincostello/website/blob/664bb882cb3577eacc90dd5731fbab5613ee6123/src/Website/Program.cs#L41

I set things up in Web.config, middleware and in Program.cs for my ASP.NET Core 2.1 sites and neither header is emitted.

**Comment by Tratcher** [comment]
X-Powered-By can only be removed in the web.config because it's added directly by IIS, not by ASP.NET.

**Comment by guardrex** [comment]
... or manually (permanently) at the server level in IIS Manager ...

<img width="492" alt="capture" src="https://user-images.githubusercontent.com/1622880/43328982-f36ed1e4-9184-11e8-87dc-1f1953220152.PNG">

**Comment by TehWardy** [comment]
@martincostello if i change the entire web.config file to this ...

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <system.webServer>
    <handlers>
      <remove name="aspNetCore"/>
      <add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModule" resourceType="Unspecified"/>
    </handlers>
    <aspNetCore processPath="%LAUNCHER_PATH%" arguments="%LAUNCHER_ARGS%" stdoutLogEnabled="false" stdoutLogFile=".\logs\stdout" />
  </system.webServer>
  <httpProtocol>
    <customHeaders>
      <remove name="X-Powered-By" />
    </customHeaders>
  </httpProtocol>
</configuration>
```

... i still get the above exception ... removing the httpProtocol tag and its contents removes the exception.

**Comment by guardrex** [comment]
@TehWardy Try making `httpProtocol` a child of `system.webServer` ...

```xml
<configuration>
   <system.webServer>
      ...
      <httpProtocol>
         <customHeaders>
            <remove name="X-Powered-By" />
         </customHeaders>
      </httpProtocol>
   </system.webServer>
</configuration>
```

**Comment by TehWardy** [comment]
@Tratcher ... so is IIS telling us the underlying framework ?
The value is set to "ASP.NET" so I figured it was asp.net adding it and it was something that could be configured in the asp.net pipeline.

**Comment by TehWardy** [comment]
@guardrex  ah nice catch ... the exception is gone ... and so is the header :)
@martincostello also your fix for removing the Server header is working too.

Thx guys !!

**Comment by guardrex** [comment]
@TehWardy It's provided in `C:\Windows\System32\inetsrv\Config\applicationHost.config` with an IIS install OOB. If you search in the file, you'll see it set ....

```xml
<httpProtocol>
    <customHeaders>
        <clear />
        <add name="X-Powered-By" value="ASP.NET" />
    </customHeaders>
    <redirectHeaders>
        <clear />
    </redirectHeaders>
</httpProtocol>
```

After you delete it in IIS Manager, it's no longer added here. When you remove it in *web.config*, the *applicationHost.config* element is overridden.

**Comment by Tratcher** [comment]
X-Powered-By is an artifact of having ASP.NET 4.x installed, it's unrelated to ASP.NET Core.
