### ISSUE TITLE
Add environment variable to set the application's appbase

### ISSUE THREAD

**Issue by danroth27** [aspnet/Hosting#572]
@anurse @BillHiebert @Tratcher 

This is needed so that VS can set from where the application should find the web root, views, etc.

**Comment by davidfowl** [comment]
Works already APPLICATIONBASE

**Comment by Tratcher** [comment]
You mean ASPNET_APPLICATIONBASE

**Comment by Tratcher** [comment]
https://github.com/aspnet/Hosting/blob/dev/src/Microsoft.AspNet.Hosting.Abstractions/WebApplicationDefaults.cs#L15-L18

**Comment by anurse** [comment]
> Works already APPLICATIONBASE

Jeez, no need to SHOUT :stuck_out_tongue_closed_eyes:

**Comment by davidfowl** [comment]
Yes that `ASPNET_APPLICATIONBASE` OMG!!!
