### ISSUE TITLE
Unable to host in Azure App Service

### ISSUE THREAD

**Issue by joshcomley** [aspnet/Hosting#576]
When I publish to Azure using the latest RC2 I receive the following error message to the browser after an extremely long load time:

    The specified CGI application encountered an error and the server terminated the process.

The app sometimes runs after the initial error message, but extremely slowly.

Any RC2 app I make has the same effect, however here is a stripped down example app to demo the problem:
https://www.dropbox.com/s/hpkrj6c74eaytjz/TinyProject.zip?dl=1

I have ensured I am publishing with the exact correct clr version. I have ensure my web.config is perfect. I have gone through absolutely everything I can think of, the only thing remaining is the possibility that the latest HttpPlatformHandler is not installed on Azure App Services.

All my logs just show successful Kestrel launches.

Does anybody have any suggestions?

Is it possible to try to install the latest HttpPlatformHandler on Kestrel, per chance?

**Comment by joshcomley** [comment]
I solved this by not using the Free or Shared App Service plan in Azure:
http://stackoverflow.com/questions/34833877/error-and-problems-after-publishing-asp-net-5-vnext-rc2-to-azure/34843117#34843117

I don't know why Free or Shared wouldn't work.

**Comment by GuardRex** [comment]
@joshcomley There was a report re: running out of space on the free tier https://github.com/aspnet/dnx/issues/3192

**Comment by joshcomley** [comment]
@GuardRex thanks, that's useful to know!

However I don't think it was that; I was trying to publish an effectively empty project that did nothing other than say "Hello World", and in RC1 it worked, immediately after converting to RC2 it didn't unless I used the non-free/shared option.

You can see the project here:
https://www.dropbox.com/s/hpkrj6c74eaytjz/TinyProject.zip?dl=1

**Comment by GuardRex** [comment]
@joshcomley I don't see ...
```
"Microsoft.AspNet.IISPlatformHandler":  "1.0.0-rc2-*",
```
and
```
.UseIISPlatformHandler();
```

**Comment by davidfowl** [comment]
And https://github.com/aspnet/Announcements/issues/139

**Comment by GuardRex** [comment]
I still have `WebApplicationBuilder`, too ... I'm behind the Announcement on the Hosting changes.

**Comment by muratg** [comment]
@glennc is looking into making free tiers work properly.

**Comment by muratg** [comment]
@glennc Assigning to you to track

**Comment by LeandroPT** [comment]
Any feedback?

**Comment by glennc** [comment]
This particular error means you got some sort of server error, could be several issues. There are a couple of updates to Azure that need to happen for RC2, and they should be rolling out soon-ish. Once they are done this should be resolved. It is possible to get it to work today if you know how, but the e2e experience for everyone still needs some work.

**Comment by davunderscorei** [comment]
@glennc Hi, any updates on the RC2ifying of Azure? If not, is it possible to instil the knowledge of "if you know how"?

**Comment by LeandroPT** [comment]
Hey,

I have it working perfectly with VSO builds and WebApp@Azure

If you need https, you need to check aspnet/IISIntegration#140

**Comment by glennc** [comment]
As of right now you can deploy a standalone RC2 application to Azure with the latest verisons of all the packages. So the "if you know how" right now is to make your app standalone instead of portable. You will be able to deploy portable apps once we ship the next release.

**Comment by muratg** [comment]
If you still have issues, please file another bug.
