### ISSUE TITLE
Settings always override UseConfiguration, no matter what order they were specified in

### ISSUE THREAD

**Issue by davidfowl** [aspnet/Hosting#582]
```c#

var host = new WebHostBuilder()
                .UseApplicationBasePath(Directory.GetCurrentDirectory())
                .UseDefaultConfiguration(args)
                .UseIISPlatformHandlerUrl()
                .UseStartup<Startup>()
                .Build();

host.Run();
```

In the above example, the application base will *always* be set to the current directory.

Because we still have 2 sources of truth, an `IConfiguration` and a settings dictionary and the settings are always applied after https://github.com/aspnet/Hosting/blob/dev/src/Microsoft.AspNet.Hosting/WebHostBuilder.cs#L193-L196 . Ideally things would be order sensitive so that it works the way you'd expect but that would mean need to either expand the `IConfiguration` inline or only use an `IConfiguration` (somehow).

/cc @divega @JunTaoLuo @Tratcher

**Comment by divega** [comment]
I am not sure I understand the problem correctly, but what if `WebHostBuilder` *had* a `ConfigurationBuilder` member? I.e. we move the creation of the `ConfigurationBuilder` to the constructor of the WebHostBuilder and then each UseXyz methods that need to introduce configuration settings can add their own configuration providers to the `ConfiguraitonBuilder` in the order in which they are called.

**Comment by davidfowl** [comment]
@divega Don't like that because the UseXyz() introduce a single setting into the existing configuration. I also explored exposing the configuration builder but ordering is still a problem. It's even worse because you can't get ahead of any other provider set before you. That's why I think it's really just a settings API (key value pairs).

**Comment by Tratcher** [comment]
I don't expect it to cause too much confusion, especially if our samples specify the config first.

**Comment by davidfowl** [comment]
We need the ordering to work in general. Here's what our template will look like https://github.com/davidfowl/dotnetcli-aspnetcore/blob/master/HelloWeb/Program.cs. The ordering is intentional:

Set defaults in code, override with configuration, overwrite with iis platform handler if specified. This allows us to set the application base in VS as an override to the current directory.

**Comment by Tratcher** [comment]
Wait, you want to set the server in code and then override it from config? That's even more confusing. Code should always have the highest precedence. Environment vars, config files, command line, code.

/cc: @DamianEdwards

**Comment by DamianEdwards** [comment]
I agree with @davidfowl, the order is what matters, not where it came from. In the end, it's all code-based config, as you have to have the lines that load from the other places (inc. the defaults).

**Comment by muratg** [comment]
@JunTaoLuo @DamianEdwards approved this for RC2 ask mode.

cc @Eilon

**Comment by JunTaoLuo** [comment]
merged to dev
