### ISSUE TITLE
webroot setting by default using environment variable

### ISSUE THREAD

**Issue by mrajranjan** [aspnet/Hosting#585]
webroot setting in project.json is not there anymore in asp.net core 1.0 rc1. In the release blog, it is mentioned that it has been moved to another file called hosting.json. Even the new file doesn't exist anywhere in the project. The strange thing is that rc1 is making use of environment setting for webroot value. What's the best way to override the default webroot setting?

**Comment by JunTaoLuo** [comment]
The recommended way to do this is to add a `hosting.json`:
```
{
    “webroot”: "pathToWebroot"
}
```
Note that the default webroot is wwwroot so unless you are using a different path, it's not necessary to specify it in `hosting.json`

**Comment by mrajranjan** [comment]
I created hosting.json with the webroot setting and saved the file in the folder where project.json exists. No change in the outcome. 

But if I add webroot setting as an environment variable in lauchSettings.json using the project properties, it works. Basically, it is overriding the existing environment setting.

Cause of the problem is that I have an environment variable with the key "webroot" which points to another folder and when I run the DNX project it grabs all the static files based on the environment setting.

**Comment by Tratcher** [comment]
@JunTaoLuo @davidfowl remind me again why environment variables override local config? https://github.com/aspnet/Hosting/blob/dev/src/Microsoft.AspNetCore.Hosting/WebHostConfiguration.cs#L28 The locality of that seems backwards.

**Comment by davidfowl** [comment]
@Tratcher so that you can set hosting settings on your environment (like AZURE) and have that override the local configuration. Same idea as the application config.

**Comment by Tratcher** [comment]
Which causes issues like this bug where you're impacted by machine-wide settings have have nothing to do with you and it's hard to override them.

**Comment by davidfowl** [comment]
> Cause of the problem is that I have an environment variable with the key "webroot" which points to another folder and when I run the DNX project it grabs all the static files based on the environment setting.

Why did you set it in the first place? What were you trying to achieve?

**Comment by mrajranjan** [comment]
We have apache server running on the machine(s) on a different port and it's using environment webroot setting to host its static files. We cannot change that. 
Why we can't override the setting using hosting.json?
It certiainly works when the setting is inserted in lauchSettings.json. But that's when run from Visual Studio.

**Comment by Tratcher** [comment]
Note in RC2 this shouldn't be a problem because Hosting requires the ASPNET_ prefix for all of its environment variables.
