### ISSUE TITLE
 runs several projects on the same port

### ISSUE THREAD

**Issue by john182** [aspnet/Hosting#587]
Good morning I'm having trouble putting N projects in the same port , in the case would be a new application

**Comment by benaadams** [comment]
Use reverse proxy e.g. IIS/ngnix to listen on the port and then route to the aspnet projects 
https://github.com/aspnet/Announcements/issues/139

**Comment by Tratcher** [comment]
Kestrel cannot share ports. WebListener and IIS can.

**Comment by muratg** [comment]
Yes, unfortunately Kestrel doesn't support this.
