### ISSUE TITLE
Have consistent way to terminate server across platforms

### ISSUE THREAD

**Issue by ahmetalpbalkan** [aspnet/Hosting#59]
I was trying to run ASP.NET web servers inside Docker containers using “k web” command, I realized that Microsoft.AspNet.Hosting waits for console input to terminate web server. (see this line https://github.com/aspnet/Hosting/blob/dev/src/Microsoft.AspNet.Hosting/Program.cs#L90 )
 
This is preventing the process inside Docker container to terminate when no stdin is attached. (workaround: if I run the container with `-i`, it works fine since it attaches a stdin).
 
I suggest removing this behavior, it doesn’t make sense to terminate upon stdin input, users always have Ctrl+C option to terminate and by convention, server applications are designed to be daemons and should not be interacting with STDIN.

**Comment by directhex** [comment]
@chriseldredge your daemon works in Docker, though it requires the "ps" command be installed, which it may not be (e.g. it isn't in the Microsoft ASP.NET vNext Docker image - RUN apt-get install procps)

**Comment by davidfowl** [comment]
This is finally done https://github.com/aspnet/Hosting/commit/e19289f7ac8a960ae84b04020331bbed9f035a7a. We now rely on `ctrl + c` across the board (SIGINT on mono and likely on coreclr xplat).
