### ISSUE TITLE
After integrating to IIS the webapp starts at random port (11771) at localhost

### ISSUE THREAD

**Issue by rsheptolut** [aspnet/Hosting#590]
I want to have an app that resides at http://localhost/apppath, but kestrel always starts listening at http://localhost:[some random port]. It gives off static files if I create "apppath" at wwwroot and access it like http://localhost/apppath/test.txt. How do I instruct my kestrel listener to ignore the "apppath" part for all requests?

**Comment by Tratcher** [comment]
If you're getting blank 404 pages when using IIS sub apps then it's probably this issue: https://github.com/aspnet/IISIntegration/issues/14

**Comment by rsheptolut** [comment]
@Tratcher, yep! Thank you, got it working with a workaround (until RC2 will be released with a fix). Sorry for not digging through the issues very good, I've really tried :)
