### ISSUE TITLE
Multiple Startup Files

### ISSUE THREAD

**Issue by endeffects** [aspnet/Hosting#593]
Hi,

is there any chance that we get support for multiple Startup files in the future to have a plugin enviroment? So each library would be able to configurate itself, especially for dependency injection.

**Comment by Tratcher** [comment]
No, we don't plan on having an automatic wire-up system built in. Too many things require user-configuration, and working out the pipeline ordering is prohibitive.  Folks that really want to go this route can build a more constrained framework on top of the existing system.

**Comment by endeffects** [comment]
Thanks for your response. I had a look into your Builder Classes, but they are not designed to inherit and reuse them. Which makes it quite hard to build something on top without duplicating alot of code.

**Comment by davidfowl** [comment]
Then send a pull request with the appropriate modifications you would need. As long as they are reasonable and align with what we're doing, we'd take them.

**Comment by Tratcher** [comment]
Out of curiosity, which classes specifically?

**Comment by endeffects** [comment]
I have forked the project and refactored the WebHostBuilder to give you an idea about my intentions.
Please have a look and let me know your thoughts. 

https://github.com/endeffects/Hosting/blob/dev/src/Microsoft.AspNetCore.Hosting/WebHostBuilder.cs

**Comment by Tratcher** [comment]
How does that get you closer to your goal of detecting multiple startup classes? Startup detection doesn't happen in WebHostBuilder, most of it is in the resulting WebHost.

**Comment by endeffects** [comment]
Well, I just picked up the first class that is involved here, i know that there are some more left. But i don't need to spent more effort here if such a refactoring won't be acceptable for you. That's why i'd like to know if this changes would have a chance for a pull request.

At the moment most of the business objects in the hosting project are sealed by it's design. There is no chance to inerhit them because all members are private and alot of the business logic has be splitted (separation of concernes). Don't get me wrong, i like the concept and work you have spent here, but the reusability is limited.

Usually i just would build my own component. But this is such a central unit where so many upcoming fixes and features are involved, that this is not an option for me.

**Comment by Tratcher** [comment]
It's hard to evaluate how useful this is without an idea of how it enables the end-to-end scenario. So far it looks like extensibility for extensibility sake. e.g. you need a very good reason to expose private fields as protected, I'd be surprised if your scenario actually required it for any or all of those fields.

**Comment by endeffects** [comment]
You are right, exposing the private fields is probably not a good option nor required - and yes, for my scenario not all changes may be needed. But i think i'm not the only one who will need access to core logic of these classes, so from my point of view i would keep the splitting of the business and so of the protected methodes.

**Comment by muratg** [comment]
As @davidfowl we would probably be able to accept a good PR that aligns with our direction.  Please make sure to discuss with @Tratcher and @davidfowl your approach before coding in case the approach is not something we would be going with.  Putting this in the backlog for now.

**Comment by davidfowl** [comment]
@endeffects any updates or can we close this.
