### ISSUE TITLE
Hosting logging needs to use structured logging instead of format strings

### ISSUE THREAD

**Issue by Eilon** [aspnet/Hosting#597]
E.g. here: https://github.com/aspnet/Hosting/blob/3ea44c6f75c4e74b10942033dae982f0490cb65a/src/Microsoft.AspNetCore.Hosting/Internal/HostingLoggerExtensions.cs#L269

It's using a formatted string, which means that structured logging doesn't get to see what's in there. It also means that the formatting is being done in the current locale of the thread, which is unlikely to achieve the desired effect.

The logging calls need to instead use structured logging.

**Comment by Tratcher** [comment]
The structured part is here:
https://github.com/aspnet/Hosting/blob/3ea44c6f75c4e74b10942033dae982f0490cb65a/src/Microsoft.AspNetCore.Hosting/Internal/HostingLoggerExtensions.cs#L241-L257
ToString is just the fallback.

**Comment by Eilon** [comment]
Hmm according to the linked bug https://github.com/aspnet/Mvc/issues/3986 the data is formatted via the ToString in the log entry - that still looks wrong. Good to know that the structured data is available, though.

**Comment by Tratcher** [comment]
Some of the loggers don't consume the structured data, they just call ToString. @BrennanConroy?

**Comment by BrennanConroy** [comment]
Its up to the logger to decide if it wants to use structured data and currently none of our loggers use structured logging anymore.

**Comment by Eilon** [comment]
Perhaps not, but the formatting to a string needs to be done with InvariantCulture in anything that we ship. Is that in Logging maybe?

**Comment by Tratcher** [comment]
The formatting is happening inline in ToString.

**Comment by Eilon** [comment]
Ah then I think that should change, no? Just need to pass in the right culture (InvariantCulture).

**Comment by Tratcher** [comment]
Well, it means you can't use the `$"{myVar}"` syntax anymore.

**Comment by Eilon** [comment]
Hardly the end of the world :smile:
