### ISSUE TITLE
RC2 on Azure - web app works for a while, then later I get "CGI application encountered an error"

### ISSUE THREAD

**Issue by nathanielcook** [aspnet/Hosting#602]
The web app works, but at some point Azure decides to sleep this app (I guess because it is on the free tier), so the next time I access it I get:
```
The specified CGI application encountered an error and the server terminated the process
```
I keep getting that message until I restart the app using the Azure portal. After the restart it starts working again. Any ideas? The stdout log doesn't have any clues as far as I can tell.

I am using the coreclr runtime, x64 architecture, 1.0.0-rc2-16357
I can provide my project.lock.json if that helps.

**Comment by GuardRex** [comment]
@nathanielcook See https://github.com/aspnet/Hosting/issues/576

**Comment by nathanielcook** [comment]
Thanks for pointing me in the right direction. Was a bit painful to update to the latest build on aspnetcidev (had to switch to *Core packages, and update the runtime again, setting DNX_UNSTABLE_FEED variable to aspnetcidev feed), but doing that and calling UseIISPlatformHandlerUrl as suggested in aspnet/Announcements#139 seems to have helped. I have still seen the cgi error message appear, but it definitely seems better than it was. Now I'm on runtime 1.0.0-rc2-16453. 

Closing this issue.
