### ISSUE TITLE
[Question] - IFileProvider, IFileInfo.PhysicalPath and Request Path

### ISSUE THREAD

**Issue by dazinator** [aspnet/Hosting#610]
Hi People :)
I have a question about how to get the "Request Path" for a file `IFileInfo`.

The scenario is that I have a `CompositeFileProvider` that contains a bunch of physical file providers, that point to various "webroot" directories from which I allow files to be served.

The structure looks like this:

```
wwwroot <-- my main web root (PhysicalFileProvider)
approot / packages / moduleA / wwwroot / ModuleA <-- module A web root (PhysicalFileProvider)
approot / packages / moduleB / wwwroot / ModuleB <-- module B web root (PhysicalFileProvider)
```

I am passing this Composite FileProvider to the `StaticFiles` Middleware, so that it can serve up:

```
~/main.js <-- some js file directly in the main wwwroot.
~/ModuleA/main.js <-- some js file in ModuleA's wwwroot/ModuleA folder.
~/ModuleB/main.js <-- some js file in ModuleB's wwwroot/ModuleB folder.
```

This is working nicely, but now I am puzzled. Given some `IFileInfo` from an `IFileProvider` i'd like to get back the appropriate Request Path.

So for example, if I grab some file:

```
 IFileProvider compositeFileProvider = GetFileProvider();
 var directoryContents = compositeFileProvider.GetDirectoryContents(folder);
 IFileInfo someFile = directoryContents.First();
```

The full physical path of that file could be: `C:\Website\approot\packages\ModuleA\wwwroot\ModuleA\main.js`

Of for example it could be:
`C:\Website\wwwroot\main.js`

How do I get the "Request Path" for that file?

So for `C:\Website\approot\packages\ModuleA\wwwroot\ModuleA\main.js` I want to get `/ModuleA/main.js`

and for `C:\Website\wwwroot\main.js` I want to get `main.js`

i.e  Is there some mechanism already provided by the framework for this kind of thing? I am hoping I don't have to write a whole bunch of reflection (as I am working at the `IFileProvider` level of abstraction) to get the particular file's `PhysicalFileProvider`, handling Composite file providers and all sorts, and then attempting to access the "PhysicalFileProvider.Root" to use that to try and do the mapping?

**Comment by Tratcher** [comment]
No, there is no reverse lookup mechanic.

**Comment by Tratcher** [comment]
This issue was moved to aspnet/FileSystem#166
