### ISSUE TITLE
Treat logger.ApplicationError as Critical

### ISSUE THREAD

**Issue by cwe1ss** [aspnet/Hosting#612]
https://github.com/aspnet/Hosting/blob/e62ceb852827d386b492abc9cc6801b1a8c70263/src/Microsoft.AspNetCore.Hosting/Internal/HostingLoggerExtensions.cs#L52

Wouldn't it be better to treat startup exceptions as LogLevel `Critical`? 

```csharp
/// <summary>
/// Logs that describe an unrecoverable application or system crash, 
/// or a catastrophic failure that requires immediate attention.
/// </summary>
Critical = 5,
```

If you have a web application that doesn't start up, it's as bad as it can get in my opinion. Using Critical would make it easier to raise alerts etc.

**Comment by muratg** [comment]
This makes sense to me. @Tratcher let me know what you think.

**Comment by Tratcher** [comment]
Sounds good.
