### ISSUE TITLE
WebHostBuilder should have an option to set the IApplicationEnvironment.ApplicationName

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Hosting#613]
We could default this to the `StartupAssemblyName` \ `WebHostOptions.Application`. In addition, it would be useful to be able to set these properties independently of each other.

**Comment by pranavkm** [comment]
More background: In Mvc, we treat the `IApplicationEnvironment.ApplicationName` as the entry assembly. This is required to make controller discovery work when the actual entry point is the test runner but the test wants Mvc to treat the test assembly as the entry point. It'd be nice to take advantage of the `IApplicationEnvironment` that the builder creates rather than creating and injecting a mock one in the test,

**Comment by muratg** [comment]
Looks like a good change.  Assigning to @JunTaoLuo

**Comment by JunTaoLuo** [comment]
Merged to dev
