### ISSUE TITLE
A serializer is not forcing deferred evaluation/execution in a controller method

### ISSUE THREAD

**Issue by cottsak** [aspnet/Hosting#614]
Not sure if this belongs here or in the [Mvc repo](https://github.com/aspnet/Mvc).

I have an `IActionResult` controller method returning a `IEnumerable<T>` via the `Ok()` helper method. The last method on my LINQ chain is a `.Take()` which, if I was calling this from elsewhere I could expect potential deferred evaluation potential. However, since this method is a controller method and then dispatched as serialised JSON over the wire, I'm expecting the equivalent of `.ToList()` to force the evaluation of the result.

When in my [`TestServer`](https://github.com/aspnet/Hosting/blob/dev/src/Microsoft.AspNetCore.TestHost/TestServer.cs) test, I call `CreateClient().GetAsync()` I am finding tests fail as the wrong number of items are being returned. When I add the Take to the end of my controller method like `.Take().ToList()` the problem goes away and my test passes. This is suggesting to me that the deferred evaluation is not happening when I use `TestServer`. 

Is this a problem with `TestServer`, the pipeline (`HttpResponseMessage`, etc) or something else?

**Comment by muratg** [comment]
@Tratcher Is this a `TestServer` issue?

**Comment by Tratcher** [comment]
I don't see how TestServer would cause this. The evaluation of the `IEnumerable<T>` takes place within MVC. TestServer only ever sees the response body bytes.

I recommend uploading a repro project and tests to a github repo.

**Comment by muratg** [comment]
@cottsak Could you provide a simple repro/tests for this issue?

**Comment by muratg** [comment]
@cottsak Let us know if you still have issues. Please make sure to add a simple repro.
