### ISSUE TITLE
Question: Memory consumption of dnx.exe

### ISSUE THREAD

**Issue by VaclavElias** [aspnet/Hosting#623]
Moved from https://github.com/aspnet/dnx/issues/3371

Please, let us know if this is still relevant as there are coming some new changes or/and bring the light to this question :)

Thanks.

**Comment by muratg** [comment]
We should do more investigation on this in 1.0.0

**Comment by VaclavElias** [comment]
I will also update this once I have got my hands on RC2 :)

**Comment by cwe1ss** [comment]
when I moved from dnx based hosting to exe-based hosting with dotnet cli, the memory footprint of my apps dropped from ~ 250 MB to ~ 30-40 MB. so that's actually quite an improvement :)
