### ISSUE TITLE
HTTP Error 502.3 - Bad Gateway- The specified CGI application encountered an error and the server terminated the process.

### ISSUE THREAD

**Issue by PRebba** [aspnet/Hosting#624]
I am getting this error only on PUT after upgrading dnx to 1.0.0 rc1 update. In eventvwr, I can see the below logged as Application Error:
Faulting application name: dnx.exe, version: 1.0.0.11123, time stamp: 0x5653996f
Faulting module name: MSVCR80.dll, version: 8.0.50727.9193, time stamp: 0x56048aec
Exception code: 0xc000000d
Fault offset: 0x000000000001da44
Faulting process id: 0x1958
Faulting application start time: 0x01d173a169bd9f64
Faulting application path: ..\approot\runtimes\dnx-clr-win-x64.1.0.0-rc1-update1\bin\dnx.exe
Faulting module path: C:\WINDOWS\WinSxS\amd64_microsoft.vc80.crt_1fc8b3b9a1e18e3b_8.0.50727.9193_none_88e4514b2faac6c7\MSVCR80.dll
Report Id: 97c4f341-6aee-4165-a317-ebd49827598b
Faulting package full name: 
Faulting package-relative application ID:

I can see HttpPlatformHandler installed and rc1 update as well. The appPool is running with my credentials. DNX is also running.
I have seen the stdoutLogFile where the below is logged.
"Hosting environment: Production
Now listening on: http://localhost:5000
Now listening on: http://localhost:26959
Application started. Press Ctrl+C to shut down."

Had anyone faced this issue earlier?

**Comment by moozzyk** [comment]
MSVCR80.dll? dnx should not use it at all. Are you using any 3rd party dependencies/libraries (possibly native) that are loading MSVCR80.dll? What OS is this? Do you have .NET Framework 4.5.1 installed? If you run the application directly (i.e. without http platform handler) does it crash as well? Can you `set DNX_TRACE=1` and show the output?

**Comment by PRebba** [comment]
My OS is Windows 10. Framework 4.5.1 is installed.

**Comment by moozzyk** [comment]
Can you show your project.json file? Also, can you provide a minimal repro?

**Comment by muratg** [comment]
No repro... closing for now. @PRebba If you still have an issue, please either re-open or file another one and provide a minimal repro.
