### ISSUE TITLE
Test deployers cause console popup windows

### ISSUE THREAD

**Issue by Tratcher** [aspnet/Hosting#631]
The test deployers are written to avoid opening any new windows, but something has regressed recently where `dotnet run` and `dotnet publish` cause new very short lived console windows. This is annoying because the new windows grab focus and interrupt typing on the machine.

See https://github.com/aspnet/Hosting/blob/a04dae1b1487ba4cd00753b86d2b6d153b46d503/src/Microsoft.AspNetCore.Server.Testing/Deployers/SelfHostDeployer.cs#L83

**Comment by muratg** [comment]
@JunTaoLuo could you investigate? The actual issue could be in the CLI...

**Comment by JunTaoLuo** [comment]
The pop ups are generated by the processes we create to kill the deployed apps https://github.com/aspnet/Hosting/blob/dev/src/Microsoft.AspNetCore.Server.Testing/Deployers/ApplicationDeployer.cs#L127-L133. I'll also probably update the code to correctly recursively kill the process tree as is done in dotnet-watch

cc @victorhurdugaci

**Comment by muratg** [comment]
Makes sense. Recursively killing the processes sounds like it would work.

**Comment by victorhurdugaci** [comment]
Can you please move the kill process tree code in common and reference it from here and from dotnet-watch



On Tue, Mar 15, 2016 at 6:25 PM -0700, "Murat Girgin" <notifications@github.com<mailto:notifications@github.com>> wrote:


Makes sense. Recursively killing the processes sounds like it would work.

-

**Comment by muratg** [comment]
:+1: Less duplication

**Comment by JunTaoLuo** [comment]
will be addressed by https://github.com/aspnet/Common/issues/100
