### ISSUE TITLE
Add ContentRootPath to IHostingEnvironment

### ISSUE THREAD

**Issue by davidfowl** [aspnet/Hosting#633]
See discussion at https://github.com/aspnet/PlatformAbstractions/issues/26. We're going to leave out `IApplicationEnvironment` as it's intended as a pure BCL abstraction API and instead we're going to add the `ContentRootPath` property (and maybe file provider) to `IHostingEnvironment`.

/cc @DamianEdwards @lodejard @JunTaoLuo

**Comment by davidfowl** [comment]
```C#
public interface IHostingEnvironment
{
    ... 

    string ContentRootPath { get; set; }
    IFileProvider ContentRootFileProvider { get; set; }

    string WebRootPath { get; set; }
    IFileProvider WebRootFileProvider { get; set; }
    ...
}
```

**Comment by halter73** [comment]
When I saw `ContentRoot`, I assumed that it was the `wwwroot` directory.

It seems that isn't the case, but instead `ContentRoot` is really what I'd expect to be `ApplicationRoot` and `WebRoot` is where I put my static content. I don't have a big problem with `WebRoot`, but `ContentRoot` is misleading.

**Comment by JunTaoLuo** [comment]
We had this conversation last week. I believe @DamianEdwards mentioned that elsewhere they were using something like `contentBase` as application base and we should follow the precedence.

**Comment by DamianEdwards** [comment]
The prior art I was referring to was the msbuild "build action" concept where "Content" meant it's not input to the compiler, but may get copied to the output, depending on the value of the "Copy to output dir" setting. That, and there isn't really another good name for it :sad: but I'm all ears on suggestions.

**Comment by JunTaoLuo** [comment]
We made the following changes in our updates in `IHostingEnvironment`:

- Added `ApplicationName`. This replaces `IApplicationEnvironment.ApplicationName` but otherwise contain the same information.
- Added `ContentRootPath`. This replaces `IApplicationEnvironment.ApplicationBasePath` but otherwise contain the same information.
- Removed Configuration
- Removed MapPath

**Comment by robbaman** [comment]
The announcement also mentions the removal of the ```MapPath(string virtualPath)``` method. Is there still a way to do what MapPath used to do?

**Comment by davidfowl** [comment]
I added a code snippet to the announcement to show the MapPath replacement.

**Comment by pranavkm** [comment]
Could we create a separate discussion work item for this?

**Comment by JunTaoLuo** [comment]
I'll move it
