### ISSUE TITLE
File database relative path connection string issue

### ISSUE THREAD

**Issue by divega** [aspnet/Hosting#639]
_From @andrew-vandenbrink on February 19, 2016 11:2_

Not sure if this can be solved but an issue anyway
This is the configuration
![image](https://cloud.githubusercontent.com/assets/12871379/13173635/087de5fe-d6ff-11e5-869e-06d3ed47be96.png)

When developing with local machine its expect the databases to reside in the same level of source code
![image](https://cloud.githubusercontent.com/assets/12871379/13173667/38257ede-d6ff-11e5-88c8-68966cb6fc20.png)

When you deploy it, it expect the databases to be resided at
![image](https://cloud.githubusercontent.com/assets/12871379/13173696/5f60aaa0-d6ff-11e5-9bc2-73f895d255dd.png)

where it "ideally" it should expect the databases to reside at **approot/src/{project_name}/**

Of course I know there is workaround to put additional production appsettings.json and use different path.

_Copied from original issue: aspnet/Identity#751_

**Comment by divega** [comment]
@Eilon any insights on this feedback and what the "ideal" location for a database file would be at development time and on deployment? 

FWIW, our SQLite provider simply uses `AppContext.BaseDirectory` (or equivalent) to resolve file name locations in the connection string.

**Comment by divega** [comment]
_From @Eilon on February 27, 2016 18:59_

I have no strong opinion on this, as long as it's not in `wwwroot` :smile:

**Comment by divega** [comment]
_From @MaximRouiller on February 29, 2016 13:47_

`App_Data`? :stuck_out_tongue_winking_eye:

**Comment by divega** [comment]
_From @blowdart on March 2, 2016 22:5_

This really isn't an identity issue, it's more a configuration one. @Eilon where should this bug end up?

**Comment by divega** [comment]
It a question/suggestion about what should the base path be at development and deployment so I don't think @blowdart means "configuration" in the [aspnet/Configuration](http://github.com/aspnet/Configuration) sense. 
Maybe [aspnet/Hosting](http://github.com/aspnet/Hosting)?

**Comment by davidfowl** [comment]
I'm not sure this belongs anywhere. It's about guidance, there's no code change here

**Comment by andrew-vandenbrink** [comment]
@davidfowl Not true, if the code use this
```
IApplicationEnvironment app;
app.ApplicationBasePath;
```

It will ensure the root path of application will be at 

![image](https://cloud.githubusercontent.com/assets/12871379/13737113/0acdf49c-e9bb-11e5-8bf3-723c7a6fa69a.png)

**Comment by muratg** [comment]
We are closing this issue because no further action is planned for this issue. If you still have any issues or questions, please log a new issue with any additional details that you have.
