### ISSUE TITLE
ApplicationBasePath set to temporary folder

### ISSUE THREAD

**Issue by JunTaoLuo** [aspnet/Hosting#641]
Using `Assembly.Location` to set the application base path does not work for tests launched with xunit console runner. 

It seems that the location of the test assembly is set to somewhere in the temporary folder such as `AppData\Local\Temp\7e915e1e-22f9-4172-8ade-491b924bf79c\7e915e1e-22f9-4172-8ade-491b924bf79c\assembly\dl3\815768c5\09292b41_dd7bd101\Microsoft.AspNetCore.Hosting.Tests.dll`. We expected the path instead to be `\test\Microsoft.AspNetCore.Hosting.Tests\bin\Debug\net451\win7-x64\Microsoft.AspNetCore.Hosting.Tests.DLL`. 

This currently breaks tests that contains content files (such as StaticFiles).

cc @davidfowl

**Comment by JunTaoLuo** [comment]
`Path.Get(new Uri(Assembly.CodeBase).LocalPath)` seems to do the trick.

**Comment by davidfowl** [comment]
Ohhhh shadow copying hmmmm maybe we should hair stick to the original application base path
