### ISSUE TITLE
HTTP Error 502.3 – Bad Gateway on long runnig task.

### ISSUE THREAD

**Issue by ildmth** [aspnet/Hosting#645]
1. I have platformhandler 1.2 installed.
2. I am not using ARR.
3. Actually my app works. 

But:
When running long running operation (more than 120 sec), i am getting error:

**HTTP Error 502.3 - Bad Gateway
The specified CGI application encountered an error and the server terminated the process.**

In empty project:
```
[Route("api/[controller]")]
public class ValuesController : Controller
{
        [HttpGet]
        public async Task<IEnumerable<string>> Get()
        {
	      await Task.Delay(130000);
            return new string[] { "value1", "value2" };
        }
}
```

```
"dependencies": {
		"Microsoft.AspNet.Diagnostics": "1.0.0-rc1-final",
		"Microsoft.AspNet.IISPlatformHandler": "1.0.0-rc1-final",
		"Microsoft.AspNet.Mvc": "6.0.0-rc1-final",
		"Microsoft.AspNet.Server.WebListener": "1.0.0-rc1-final",
		"Microsoft.AspNet.StaticFiles": "1.0.0-rc1-final",
		"Microsoft.Extensions.Configuration.FileProviderExtensions": "1.0.0-rc1-final",
		"Microsoft.Extensions.Configuration.Json": "1.0.0-rc1-final",
		"Microsoft.Extensions.Logging": "1.0.0-rc1-final",
		"Microsoft.Extensions.Logging.Console": "1.0.0-rc1-final",
		"Microsoft.Extensions.Logging.Debug": "1.0.0-rc1-final",
	},

  "commands": {
    "web": "Microsoft.AspNet.Server.WebListener"
  }
```

EventViewer:

The description for Event ID 1000 from source HttpPlatformHandler cannot be found. Either the component that raises this event is not installed on your local computer or the installation is corrupted. You can install or repair the component on the local computer.

If the event originated on another computer, the display information had to be saved with the event.

The following information was included with the event: 

Process '5956' failed to start. Port = 28429, Error Code = '-2147023265'.

**Comment by Tratcher** [comment]
Do not use WebListener with IIS, use Kestrel instead. https://github.com/aspnet/IISIntegration/issues/8
