### ISSUE TITLE
Hosting problems on azure

### ISSUE THREAD

**Issue by vsotov** [aspnet/Hosting#650]
I've deployed project to Azure App Service, everything went ok, except after some random amount of time kestrel seems to loose requests. 

In logs I see something like
info: Microsoft.AspNet.Hosting.Internal.HostingEngine[1]
      Request starting HTTP/1.1 GET http://renta-api.azurewebsites.net/projects  

without any continuation. Than after some time everything is working ok.
Maybe this is an issue with HttpPlatformHandler.

Here is its configuration 
`<handlers>
      <add name="httpplatformhandler" path="*" verb="*" modules="httpPlatformHandler" resourceType="Unspecified"/>
    </handlers>
    <httpPlatform processPath="%home%\site\approot\web.cmd" arguments="" stdoutLogEnabled="false" stdoutLogFile="\\?\%home%\LogFiles\stdout.log"
   `

PS I use standard right-click deploy project method.

**Comment by Tratcher** [comment]
This issue was moved to aspnet/KestrelHttpServer#698
