### ISSUE TITLE
Discussion for WebHostBuilder extension renames

### ISSUE THREAD

**Issue by JunTaoLuo** [aspnet/Hosting#674]
Discussion for https://github.com/aspnet/Announcements/issues/163.

Changes were made in #660

**Comment by Tratcher** [comment]
> UseDefaultConfiguration() will also no longer configure the WebHost to capture startup errors by default.

However, UseIIS will call `CaptureStartupErrors(true)` if it detects you're running behind IIS/Express.

**Comment by muratg** [comment]
We are closing this issue because no further action is planned for this issue. If you still have any issues or questions, please log a new issue with any additional details that you have.
