### ISSUE TITLE
Move some WebHostBuilderExtensions to Hosting.Abstractions

### ISSUE THREAD

**Issue by Tratcher** [aspnet/Hosting#675]
IISIntegration was able to depend just on Hosting.Abstractions until it called CaptureStartupErrors.

Move extensions that may be used by extensions from other packages and not just app code. E.g:
- UseConfiguration
- CaptureStartupErrors
- UseEnvironment
- UseUrls
- Start

Don't move:
- UseStartup
- UseDefaultHostingConfiguration
- UseServer? - What if I wanted a UseKestrel extension?
- UseContentRoot
- UseWebRoot

https://github.com/aspnet/Hosting/blob/dev/src/Microsoft.AspNetCore.Hosting/WebHostBuilderExtensions.cs

@JunTaoLuo @davidfowl

**Comment by davidfowl** [comment]
Why not move everything that can be moved?

**Comment by Tratcher** [comment]
Doesn't matter, as long as it doesn't require too much implementation code or any dependencies.

**Comment by diryboy** [comment]
I'm confused. Why webroot is not the configuration that comes with StaticFiles? It looks to me that only the StaticFile module is interested in setting the dir where it would find files to serve.

**Comment by davidfowl** [comment]
StaticFiles and MVC use the webroot folder by default for serving files. It's in hosting because it flows via the `IHostingEnvironment` service.

**Comment by diryboy** [comment]
Thanks, @davidfowl, when does MVC need webroot folder to serve files? I'm under the impression this should be done by StaticFiles.

**Comment by davidfowl** [comment]
https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Core/VirtualFileResult.cs#L148

**Comment by diryboy** [comment]
Oh I see. It's in the core. Thank you very much!
