### ISSUE TITLE
base path for hosting.json

### ISSUE THREAD

**Issue by rmja** [aspnet/Hosting#694]
The base path for finding the hosting.json file is not configurable in https://github.com/aspnet/Hosting/blob/dev/src/Microsoft.AspNetCore.Hosting/Internal/WebHostConfiguration.cs, so my question is: What is the recommended way to setting the base path for finding the hosting.json file to e.g. `Directory.GetCurrentDirectory()`?

**Comment by davidfowl** [comment]
What exactly are you trying to do?

**Comment by rmja** [comment]
@davidfowl I was trying to work may way throug putting the hosting configuration in the hosting.json file.   Specifically the `server.urls` configuration parameter. The different sample projects seems to not use it anymore, so I was going through the source, and found that the hosting.json file was not loaded because its location was expected to be in the `bin\Debug\netcoreapp1.0` directory instead of the content root path where the appsettings.json file is located.

Maybe my struggle to find a sample hosting.json file indicates that it is obsolete, or?

**Comment by davidfowl** [comment]
@rmja It's no obsolete but we've mostly moved to putting settings in code since there's a Program.Main now. If you want to get your hosting.json to load, you need to set the content property to have it in `project.json`. That will make sure it gets copied to the output folder:

```
{
    "content": [
        "hosting.json"
    ]
}
```

**Comment by rmja** [comment]
@davidfowl ... and that was exactly what I was missing. Thanks!
