### ISSUE TITLE
Hosting:Environment value does not persist for web profile when switching between IIS Express and web profiles. Value is reset to 'Development'

### ISSUE THREAD

**Issue by kimbaudi** [aspnet/Hosting#697]
In Visual Studios 2015, I set the Hosting:Environment value to 'Staging' or 'Production' for the web profile using the Debug tab of my web application project's Properties menu or from the launchSettings.json file. Whenever I switch running my application to IIS Server, checking the Environment Variables value for the web profile shows 'Development'. Shouldn't the value I set for Hosting:Environment persist? It does for IIS Express, but not for web. 

I also saw the Note in the docs (https://docs.asp.net/en/latest/fundamentals/environments.html) that states: 
"Changes made to project profiles or to launchSettings.json directly may not take effect until the web server used is restarted (in particular, kestrel must be restarted before it will detect changes made to its environment)."

So I rebuilt my solution and ran my application using web to host. But still, changing hosting to IIS Express resets the Hosting:Environment value to 'Development' for the web profile

**Comment by Tratcher** [comment]
Duplicate of https://github.com/aspnet/Tooling/issues/354 ?

**Comment by kimbaudi** [comment]
Closing
