### ISSUE TITLE
Add ASPNETCORE_* environment variables by default to hosting configuration

### ISSUE THREAD

**Issue by davidfowl** [aspnet/Hosting#700]
Today you have to call `UseDefaultConfiguration` to turn on the ASPNETCORE_ environment variables. This means that `ASPNETCORE_` settings aren't applied unless the application code is setup to do so. While this seems like a pure choice, it makes it hard to diagnose why things aren't working. An example of this is the IISIntegration middleware. If you don't call UseDefaultConfiguration then it won't bind to IIS. 

Instead, we should just setup the the env vars by default.

/cc @DamianEdwards @Tratcher

**Comment by Tratcher** [comment]
How do you turn it off?

**Comment by LeandroPT** [comment]
Hello all... 

This should be reflected in all examples with upper cases :), specially hosting in IIS...

I have been banging my head with this.. Thanks for the post :+1:

**Comment by muratg** [comment]
@JunTaoLuo We think this is required for #727. 

cc @Tratcher
