### ISSUE TITLE
Accessing IHostingEnvironment from console app

### ISSUE THREAD

**Issue by hauteur** [aspnet/Hosting#704]
It is quite possible that I'm missing something obvious, but I have not been able to find a way to get the IHostingEnvironment implementation in a console app (no DI).  I can get Environment and Runtime using PlatformServices, but I don't see a way to get at the hosting environment.  Am I missing it?

**Comment by muratg** [comment]
@hauteur This is by design. Not sure why you would like IHostingEnvironment in a "console" application.  What's your specific scenario?

**Comment by hauteur** [comment]
Thanks for the response.

I have a console app set up to run as a Windows service.  I was thinking of adding the ability to leave it as a console app (don't call run) if it is development.  In ASP.NET, you have if (env.IsDevelopment)...  

I couldn't get if Debug  to work either.  It seemed to, but it didn't actually hit.

**Comment by Tratcher** [comment]
IHostingEnvironment is an Asp.Net concept. It does not apply to misc console applications.

We just read the value from configuration or default to Production, it would be easy for you to do the same.

**Comment by hauteur** [comment]
That's actually the way I have it right now - I've got a configuration value that says whether or not to run it as a service.  That seems messy to me - it can be easy to forget it when you deploy.  I'm working on pulling all of the logic out of it and into a library.  I'll have two shell apps that use the libraries.

I don't know, though.  It seems like being able to tell whether or not you are in debug mode would be pretty handy.

**Comment by Tratcher** [comment]
We just set "Development" mode via an environment variable before launch.

**Comment by GuardRex** [comment]
@hauteur I do little of that myself. I look at the machine name. My servers are all consistently named in production and staging. From the machine name, I can load alternative configs. If there are no machine name matches, I default to a dev environment config. As you say, I never screw up this way! :smile:

**Comment by ranouf** [comment]
Hi,

I added AddApplicationInsightsTelemetry to my IServiceCollection but it need IHostingEnvironment to be able to Instanciate using the dependency Injection, this the error I Have:
DependencyResolutionException: None of the constructors found with 'Autofac.Core.Activators.Reflection.DefaultConstructorFinder' on type 'Microsoft.ApplicationInsights.AspNetCore.TelemetryInitializers.AspNetCoreEnvironmentTelemetryInitializer' can be invoked with the available services and parameters:
Cannot resolve parameter 'Microsoft.AspNetCore.Hosting.IHostingEnvironment environment' of constructor 'Void .ctor(Microsoft.AspNetCore.Hosting.IHostingEnvironment)'.

Is there a way to bypass this pb?

**Comment by davidfowl** [comment]
Add your own
