### ISSUE TITLE
Include the content root path as part of exception message

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Hosting#707]
UseContentRoot throws an `ArgumentException` when the directory does not exist. We should modify the error message to include the actual path. 

https://github.com/aspnet/Hosting/blob/b7bdc9c40494f8e0f0eac22db91b8d5c58811ee2/src/Microsoft.AspNetCore.Hosting/Internal/HostingEnvironmentExtensions.cs#L28 line to change.

**Comment by Eilon** [comment]
@ryanbrandenburg mark as done?
