### ISSUE TITLE
Http Error 502.3 Bad gateway. There was a connection error while trying to route the request.

### ISSUE THREAD

**Issue by ibrmohammed** [aspnet/Hosting#710]
Web application is running on RC2  1.0.0-rc2-20222.HtppPlatformHandler 1.2 is installed.
I used dotnet publish to publish the WebApp.
Publish created different folder structure (as opposed to Visual studio publish structure of approot, wwwroot, logs)
1. Refs
2. wwwroot
3. Lot of dlls and a exe with a webapp name.

Hosted a webapp on iis with the above contents and physical path set to wwwroot.I got a 502.3 error.

My Web.config: process path in httpplatform set to %DNX_PATH%
![image](https://cloud.githubusercontent.com/assets/5870046/14588679/7a78f16a-04ec-11e6-8758-50c292291b10.png)

Event viewer gives an error and a warning
Error: Process '0' failed to start. Port = 3038, Error Code = '-2147024894'.
![image](https://cloud.githubusercontent.com/assets/5870046/14588700/e804ad32-04ec-11e6-8d18-ecf90c1a6ba5.png)
Warning:Could not create stdoutLogFile \\?\C:\inetpub\wwwroot\logs\stdout_10712_2016417165928.log, ErrorCode = -2147024893.
![image](https://cloud.githubusercontent.com/assets/5870046/14588712/40db1cf2-04ed-11e6-8883-1404e11dae41.png)

Is there a problem with command prompt publish  or my web.config?

**Comment by GuardRex** [comment]
@ibrmohammed  A lot is changing in Hosting and with IIS. Catch up on the latest changes with the RC2 Annoucements: https://github.com/aspnet/Announcements/issues?q=is%3Aopen+is%3Aissue+milestone%3A1.0.0-rc2

You hit on a few here when you tried to deploy: DNX is going away in favor of `dotnet cli`, the published output is changing, the `web.config` file is changing, and the `HttpPlatformHandler` is being replaced by the `AspNetCoreModule` ... just to name a few!

RC2 is probably getting close to release, and there will be a migration document to help you convert an RC1-final app into an RC2-final app along with updated docs on hosting when RC2 is released.

**Comment by ibrmohammed** [comment]
@GuardRex  I saw the following link.https://github.com/aspnet/Announcements/issues/164.Before RC2 gets released, can we start using coremodule with RC2 nighly builds.and from where can i get this package related to coremodule "Microsoft.AspNetCore.Server.IISIntegration"

**Comment by GuardRex** [comment]
@ibrmohammed Yes, the new module works great. It hasn't been rolled out to Azure Apps yet, you can use it on an Azure VM. Regarding the package, take a look at the cli samples, which are setup to run a RC2-nightly shared framework app on IIS: https://github.com/aspnet/cli-samples ... they have the correct NuGet feeds in the `NuGet.config` file to pull down the package when you restore any of the apps in the sample.

**Comment by muratg** [comment]
Closing this one. @ibrmohammed if you still have problems with AspNetCoreModule, please file another one. Thanks.
