### ISSUE TITLE
Could not find this package "Microsoft.AspNetCore.Server.IISIntegration" in nugget feed

### ISSUE THREAD

**Issue by ibrmohammed** [aspnet/Hosting#711]
Web App uses RC2. According to this link https://github.com/aspnet/Announcements/issues/164
we might need to use core module instead of HttpPlatformHandler.

from where can i get the following package "Microsoft.AspNetCore.Server.IISIntegration".

**Comment by davidfowl** [comment]
You can look at the feeds on cli-samples https://github.com/aspnet/cli-samples/blob/master/NuGet.Config

**Comment by ibrmohammed** [comment]
installed asp.net core x64 module.
added the following dependency "Microsoft.AspNetCore.Server.IISIntegration": "1.0.0-rc2-*"
modified my startup.cs
![image](https://cloud.githubusercontent.com/assets/5870046/14662862/15fddc44-06d8-11e6-8261-6f9fd792ac49.png)

modified the web.config
![image](https://cloud.githubusercontent.com/assets/5870046/14662890/4422910a-06d8-11e6-9c5b-608f1add3232.png)

publish folder using dotnet publish
![image](https://cloud.githubusercontent.com/assets/5870046/14662934/b6437970-06d8-11e6-9288-a9bcee84c376.png)


copied the contents of publish folder in a c:/inetpub/wwwroot/IdpWebApp
![image](https://cloud.githubusercontent.com/assets/5870046/14662964/0cd81214-06d9-11e6-9597-5d55692819ca.png)

createa a webapplication and pointed to wwwroot of publish folder
![image](https://cloud.githubusercontent.com/assets/5870046/14662994/604b5654-06d9-11e6-9ab5-c3535106cfb5.png)


Browsing the site gave me 500 internal server error
![image](https://cloud.githubusercontent.com/assets/5870046/14663041/c6031dce-06d9-11e6-88cd-d77e524be08b.png)

checked event  viewer.It shows Asp.net core module started successfully.
![image](https://cloud.githubusercontent.com/assets/5870046/14663069/08f38cfe-06da-11e6-9f32-6ae212424150.png)

What's missing here.

**Comment by Tratcher** [comment]
You're pretty close actually, that's the Asp.Net startup error page. It means there was an exception starting your app, probably from the Startup class. If you set ASPNETCORE_ENVIRONMENT to Development you should get the details. The easiest place to set this is in the Web.Config, aspNetCore has an environment variables sub-section.

**Comment by ibrmohammed** [comment]
my hosting environment is 
![image](https://cloud.githubusercontent.com/assets/5870046/14663274/caeb6500-06dc-11e6-8d14-59d3d90e08fe.png)

**Comment by GuardRex** [comment]
@ibrmohammed You're not following the cli-samples project. Check out https://github.com/aspnet/cli-samples/tree/master/HelloMvc ... unless you were specifically trying to setup a standalone application; the cli-samples follow the shared framework model.

**Comment by ibrmohammed** [comment]
the framework in my project is 
  "frameworks": {
    "net451": { }
  },

**Comment by GuardRex** [comment]
That's fine, but were you trying to setup a standalone (self-contained) application or a shared framework application? Since your output shows an executable, it looks like you are trying to create a standalone project. If you didn't know about the difference between the two application types, you can read more here: https://github.com/blackdwarf/core-docs/blob/clidocs/docs/core-concepts/app-types.md

The cli-samples are all shared framework projects. If you want to see one that's a standalone project, I have a test project of mine in my repo at: https://github.com/GuardRex/standalone ... the standalone project would be restored the same way, `dotnet restore` but published with the RID: `dotnet publish --configuration Release --runtime win81-x64`.

**Comment by ibrmohammed** [comment]
i think its a shared framework because of the dependencies

![image](https://cloud.githubusercontent.com/assets/5870046/14664420/5bda70d2-06e8-11e6-8b4d-bb287d8dbbae.png)

**Comment by GuardRex** [comment]
You need to depend on ..
```
"Microsoft.NETCore.App": {
  "type": "platform",
  "version": "1.0.0-*"
}
```
... for it to be a shared framework app. It's the `"type": "platform"` part that makes it shared.

**Comment by ibrmohammed** [comment]
So you mean to say its a standalone application.And what does win 81-x64 suggests?

**Comment by ibrmohammed** [comment]
the command that i used to publish the application was this
dotnet publish "src\Aps.Idp.Web" -c "Release"  -f "net451" -o "artifacts\bin\Aps.Idp.Web\Release\PublishOutput"

**Comment by GuardRex** [comment]
That's the runtime id (RID). `win81-x64` is appropriate for Windows 8.1+/Windows Server 2012/R2+.

Add the `runtimes` section to `project.json` with the `win81-x64` RID, and add `-r win81-x64` to your publish command. You should get proper ouput.

There may be a few other issues here to address though:
- `web.config` has the correct paths for the `.exe` and log file
- the `"Microsoft.NETCore.DotNetHostPolicy": "1.0.1-*"` package dep
- `web.config` is in the content root (the application base path)
- `web.config` added to the `content` section of `project.json`
- `NuGet.config` is pointed to the `aspnetcirelease` feed and `api.nuget.org` feed.

There are a lot of little things to check. Compare your app to my standalone for the general layout.

**Comment by ibrmohammed** [comment]
Is that the publish folder for standalone app
https://github.com/ibrmohammed/standalone

**Comment by GuardRex** [comment]
No, it will publish deep within the `bin` folder ... you'll see a `publish` folder in there. That will contain the bits you need to deploy. See the full layout here: https://github.com/dotnet/cli/issues/937#issuecomment-186737388

**Comment by ibrmohammed** [comment]
Ah !! My bad.Its the project.
can you give me the publish folder for the standalone app.so that i can get a better understanding.

**Comment by GuardRex** [comment]
Just publish that one ... run `dotnet restore` on it, then do a ...
```
dotnet publish --configuration Release --runtime win81-x64
```
 ... It will create the full outputs for you, and you'll see the `publish` folder in there. The contents of that folder is what you deploy to the server.

![capture](https://cloud.githubusercontent.com/assets/1622880/14664877/613f6e3c-0694-11e6-9ecb-6e1a617d20e0.PNG)

**Comment by ibrmohammed** [comment]
@GuardRex 

From the points mentioned above. I did not get your 3rd point.what change should i have to do for point 3?

1.web.config has the correct paths for the .exe and log file
2.the "Microsoft.NETCore.DotNetHostPolicy": "1.0.1-*" package dep
3.web.config is in the content root (the application base path)
4.web.config added to the content section of project.json
5.NuGet.config is pointed to the aspnetcirelease feed and api.nuget.org feed.

**Comment by GuardRex** [comment]
web.config will exist at the application base path along with the rest of
the project's files.

You can also have no web.config in the project and use the publish-iis tool
to generate one for you as the cli samples show and is discussed here:
https://github.com/aspnet/IISIntegration/issues/105#issuecomment-212519337

**Comment by ibrmohammed** [comment]
@GuardRex  for the standalone app, the feed used is aspnetcirelease feed.Is this using "dnx-clr-win-x86.1.0.0-rc2-20221"

the feed i am using is https://www.myget.org/F/aspnetcidev/
My application is using "dnx-clr-win-x86.1.0.0-rc2-20222". 
framework net451
Included runtimes as win81-x64 in project.json and tried dotnet restore. But the restore failed.
then tried dnu restore.Again the restore failed.
Now removed run times section from project.json and tried dnu restore.it was successfull.
But dotnet publish gave a  publish folder with  win7-x64.Upon hosting on IIS gives "Http 403.14"

**Comment by GuardRex** [comment]
@ibrmohammed No, DNX is dead. `dotnet cli` totally takes over. You should be using this: https://github.com/dotnet/cli/tree/rel/1.0.0

**Comment by ibrmohammed** [comment]
May i know if this  dnx clr version or cli version.

![image](https://cloud.githubusercontent.com/assets/5870046/14699773/1f44d560-07b8-11e6-8eb2-1a71758e5051.png)

**Comment by GuardRex** [comment]
@ibrmohammed ... no ... none of that matters. `dotnet cli` is a totally different runtime, build, and tooling system. All of that is :skull: dead :skull:. The only value to it at all is for use with Visual Studio to get Intellisence. Visual Studio will get a tooling update when RC2 releases in a few weeks. You can leave those runtimes there for now, but when RC2 releases, you'll be able to delete all of the DNX stuff (including those runtimes) from your machine. If you want to work with `dotnet cli`, you'll be using the commands shown in the `dotnet cli` repo and the docs there.

You would probably be better off with VS Code. Install the ["Insiders Edition,"](https://code.visualstudio.com/Download#insiders) and use that until the updated Visual Studio comes out in a few weeks. To make your life with it a little easier, you can try out my [Status Bar Tasks extension](https://marketplace.visualstudio.com/items?itemName=GuardRex.status-bar-tasks).

**Comment by ibrmohammed** [comment]
getting the following error while trying to publish using dotnet publish

![image](https://cloud.githubusercontent.com/assets/5870046/14732032/2468065e-0874-11e6-884b-dd79ef182e76.png)

**Comment by ibrmohammed** [comment]
"frameworks": {
    "net451": { }
  }

**Comment by davidfowl** [comment]
@ibrmohammed File a bug on github.com/dotnet/cli

**Comment by ibrmohammed** [comment]
<b>modified my project.json</b>
{
  "userSecretsId": "aspnet5-Idp-149e9283-fb72-416b-bf12-4bc1df27d486",
  "version": "1.0.0-*",
  "description": "Aps.Idp.Web Project",
  "authors": [ "IPPCS" ],
  "commands": {
    "web": "Aps.Idp.Web",
    "ef": "EntityFrameworkCore.Commands"
  },
  "content": [
    "wwwroot",
    "web.config"
  ],
  "compilationOptions": {
    "emitEntryPoint": true,
    "preserveCompilationContext": true
  },
  "exclude": [
    "wwwroot",
    "node_modules"
  ],
  "frameworks": {
    "net451": { },
    "netcoreapp1.0": {
      
    }
  },
  "dependencies": {
    "Aps.Idp": "1.0.0-*",
    "Aps.Idp.Repository": "1.0.0-*",
    "Aps.Idp.Repository.EF": "1.0.0-*",
    "Microsoft.AspNetCore.Authentication.JwtBearer": "1.0.0-rc2-*",
    "Microsoft.AspNetCore.Server.IISIntegration": "1.0.0-*",
    "Microsoft.AspNetCore.Server.Kestrel": "1.0.0-rc2-*",
    "Microsoft.Extensions.Logging.Console": "1.0.0-rc2-*",
    "Microsoft.Extensions.Logging.Debug": "1.0.0-rc2-*",
    "Microsoft.Extensions.Options.ConfigurationExtensions": "1.0.0-rc2-*",
    "Microsoft.AspNetCore.Diagnostics": "1.0.0-rc2-*",
    "Microsoft.NETCore.DotNetHostPolicy": "1.0.1-*"
  },
  "runtimes": {
    "win81-x64": { }
  },
  "publishExclude": [
    "**.user",
    "**.vspscc"
  ],
  "scripts": {
    "prepublish": [ "npm install", "bower install", "gulp clean", "gulp min" ]
  }
}


<b>got the following errors when i ran a dotnet restore</b>

log  : Restore failed in 6061ms.

Errors in C:\Users\ibrmohammed\Source\Workspaces\SbmAps\Idp\src\Aps.Idp.Web\proj
ect.json
    Package Ix-Async 1.2.5 is not compatible with netcoreapp1.0 (.NETCoreApp,Ver
sion=v1.0). Package Ix-Async 1.2.5 supports:
      - net40 (.NETFramework,Version=v4.0)
      - net45 (.NETFramework,Version=v4.5)
      - portable-net45+win8+wp8 (.NETPortable,Version=v0.0,Profile=Profile78)
    Package Remotion.Linq 2.0.2 is not compatible with netcoreapp1.0 (.NETCoreAp
p,Version=v1.0). Package Remotion.Linq 2.0.2 supports:
      - net35 (.NETFramework,Version=v3.5)
      - net40 (.NETFramework,Version=v4.0)
      - net45 (.NETFramework,Version=v4.5)
      - portable-net45+win8+wp8+wpa81 (.NETPortable,Version=v0.0,Profile=Profile
259)
    Package Newtonsoft.Json 8.0.3 is not compatible with netcoreapp1.0 (.NETCore
App,Version=v1.0). Package Newtonsoft.Json 8.0.3 supports:
      - net20 (.NETFramework,Version=v2.0)
      - net35 (.NETFramework,Version=v3.5)
      - net40 (.NETFramework,Version=v4.0)
      - net45 (.NETFramework,Version=v4.5)
      - portable-dnxcore50+net45+win8+wp8+wpa81 (.NETPortable,Version=v0.0,Profi
le=net45+wp80+win8+wpa81+dnxcore50)
      - portable-net40+sl5+win8+wp8+wpa81 (.NETPortable,Version=v0.0,Profile=Pro
file328)
    One or more packages are incompatible with .NETCoreApp,Version=v1.0.
    Package Ix-Async 1.2.5 is not compatible with netcoreapp1.0 (.NETCoreApp,Ver
sion=v1.0) / win81-x64. Package Ix-Async 1.2.5 supports:
      - net40 (.NETFramework,Version=v4.0)
      - net45 (.NETFramework,Version=v4.5)
      - portable-net45+win8+wp8 (.NETPortable,Version=v0.0,Profile=Profile78)
    Package Remotion.Linq 2.0.2 is not compatible with netcoreapp1.0 (.NETCoreAp
p,Version=v1.0) / win81-x64. Package Remotion.Linq 2.0.2 supports:
      - net35 (.NETFramework,Version=v3.5)
      - net40 (.NETFramework,Version=v4.0)
      - net45 (.NETFramework,Version=v4.5)
      - portable-net45+win8+wp8+wpa81 (.NETPortable,Version=v0.0,Profile=Profile
259)
    Package Newtonsoft.Json 8.0.3 is not compatible with netcoreapp1.0 (.NETCore
App,Version=v1.0) / win81-x64. Package Newtonsoft.Json 8.0.3 supports:
      - net20 (.NETFramework,Version=v2.0)
      - net35 (.NETFramework,Version=v3.5)
      - net40 (.NETFramework,Version=v4.0)
      - net45 (.NETFramework,Version=v4.5)
      - portable-dnxcore50+net45+win8+wp8+wpa81 (.NETPortable,Version=v0.0,Profi
le=net45+wp80+win8+wpa81+dnxcore50)
      - portable-net40+sl5+win8+wp8+wpa81 (.NETPortable,Version=v0.0,Profile=Pro
file328)
    System.Security.Principal.Windows 4.0.0-rc2-24018 provides a compile-time re
ference assembly for System.Security.Principal.Windows on .NETCoreApp,Version=v1
.0, but there is no run-time assembly compatible with win81-x64.
    System.Collections 4.0.11-rc2-24018 provides a compile-time reference assemb
ly for System.Collections on .NETCoreApp,Version=v1.0, but there is no run-time
assembly compatible with win81-x64.
    System.Diagnostics.Debug 4.0.11-rc2-24018 provides a compile-time reference
assembly for System.Diagnostics.Debug on .NETCoreApp,Version=v1.0, but there is
no run-time assembly compatible with win81-x64.
    System.Globalization 4.0.11-rc2-24018 provides a compile-time reference asse
mbly for System.Globalization on .NETCoreApp,Version=v1.0, but there is no run-t
ime assembly compatible with win81-x64.
    System.IO 4.1.0-rc2-24018 provides a compile-time reference assembly for Sys
tem.IO on .NETCoreApp,Version=v1.0, but there is no run-time assembly compatible
 with win81-x64.
    System.Net.Primitives 4.0.11-rc2-24018 provides a compile-time reference ass
embly for System.Net.Primitives on .NETCoreApp,Version=v1.0, but there is no run
-time assembly compatible with win81-x64.
    System.Runtime.Extensions 4.1.0-rc2-24018 provides a compile-time reference
assembly for System.Runtime.Extensions on .NETCoreApp,Version=v1.0, but there is
 no run-time assembly compatible with win81-x64.
    System.Runtime.InteropServices 4.1.0-rc2-24018 provides a compile-time refer
ence assembly for System.Runtime.InteropServices on .NETCoreApp,Version=v1.0, bu
t there is no run-time assembly compatible with win81-x64.
    System.Text.Encoding 4.0.11-rc2-24018 provides a compile-time reference asse
mbly for System.Text.Encoding on .NETCoreApp,Version=v1.0, but there is no run-t
ime assembly compatible with win81-x64.
    System.Threading.Tasks 4.0.11-rc2-24018 provides a compile-time reference as
sembly for System.Threading.Tasks on .NETCoreApp,Version=v1.0, but there is no r
un-time assembly compatible with win81-x64.
    System.Threading.Timer 4.0.1-rc2-24018 provides a compile-time reference ass
embly for System.Threading.Timer on .NETCoreApp,Version=v1.0, but there is no ru
n-time assembly compatible with win81-x64.
    System.Console 4.0.0-rc2-24018 provides a compile-time reference assembly fo
r System.Console on .NETCoreApp,Version=v1.0, but there is no run-time assembly
compatible with win81-x64.
    System.Reflection.Extensions 4.0.1-rc2-24018 provides a compile-time referen
ce assembly for System.Reflection.Extensions on .NETCoreApp,Version=v1.0, but th
ere is no run-time assembly compatible with win81-x64.
    System.Data.SqlClient 4.1.0-rc2-24018 provides a compile-time reference asse
mbly for System.Data.SqlClient on .NETCoreApp,Version=v1.0, but there is no run-
time assembly compatible with win81-x64.
    System.Reflection 4.1.0-rc2-24018 provides a compile-time reference assembly
 for System.Reflection on .NETCoreApp,Version=v1.0, but there is no run-time ass
embly compatible with win81-x64.
    System.Resources.ResourceManager 4.0.1-rc2-24018 provides a compile-time ref
erence assembly for System.Resources.ResourceManager on .NETCoreApp,Version=v1.0
, but there is no run-time assembly compatible with win81-x64.
    System.Runtime 4.1.0-rc2-24018 provides a compile-time reference assembly fo
r System.Runtime on .NETCoreApp,Version=v1.0, but there is no run-time assembly
compatible with win81-x64.
    System.Runtime.Handles 4.0.1-rc2-24018 provides a compile-time reference ass
embly for System.Runtime.Handles on .NETCoreApp,Version=v1.0, but there is no ru
n-time assembly compatible with win81-x64.
    System.IO.FileSystem 4.0.1-rc2-24018 provides a compile-time reference assem
bly for System.IO.FileSystem on .NETCoreApp,Version=v1.0, but there is no run-ti
me assembly compatible with win81-x64.
    System.Reflection.Primitives 4.0.1-rc2-24018 provides a compile-time referen
ce assembly for System.Reflection.Primitives on .NETCoreApp,Version=v1.0, but th
ere is no run-time assembly compatible with win81-x64.
    System.Diagnostics.Tracing 4.1.0-rc2-24018 provides a compile-time reference
 assembly for System.Diagnostics.Tracing on .NETCoreApp,Version=v1.0, but there
is no run-time assembly compatible with win81-x64.
    System.Security.Cryptography.Algorithms 4.1.0-rc2-24018 provides a compile-t
ime reference assembly for System.Security.Cryptography.Algorithms on .NETCoreAp
p,Version=v1.0, but there is no run-time assembly compatible with win81-x64.
    System.Text.Encoding.Extensions 4.0.11-rc2-24018 provides a compile-time ref
erence assembly for System.Text.Encoding.Extensions on .NETCoreApp,Version=v1.0,
 but there is no run-time assembly compatible with win81-x64.
    System.Runtime.InteropServices.RuntimeInformation 4.0.0-rc2-24018 provides a
 compile-time reference assembly for System.Runtime.InteropServices.RuntimeInfor
mation on .NETCoreApp,Version=v1.0, but there is no run-time assembly compatible
 with win81-x64.
    System.Security.Cryptography.X509Certificates 4.1.0-rc2-24018 provides a com
pile-time reference assembly for System.Security.Cryptography.X509Certificates o
n .NETCoreApp,Version=v1.0, but there is no run-time assembly compatible with wi
n81-x64.
    System.Security.Cryptography.Encoding 4.0.0-rc2-24018 provides a compile-tim
e reference assembly for System.Security.Cryptography.Encoding on .NETCoreApp,Ve
rsion=v1.0, but there is no run-time assembly compatible with win81-x64.
    Microsoft.Win32.Registry 4.0.0-rc2-24018 provides a compile-time reference a
ssembly for Microsoft.Win32.Registry on .NETCoreApp,Version=v1.0, but there is n
o run-time assembly compatible with win81-x64.
    System.IO.FileSystem.Watcher 4.0.0-rc2-24018 provides a compile-time referen
ce assembly for System.IO.FileSystem.Watcher on .NETCoreApp,Version=v1.0, but th
ere is no run-time assembly compatible with win81-x64.
    System.AppContext 4.1.0-rc2-24018 provides a compile-time reference assembly
 for System.AppContext on .NETCoreApp,Version=v1.0, but there is no run-time ass
embly compatible with win81-x64.
    System.Globalization.Extensions 4.0.1-rc2-24018 provides a compile-time refe
rence assembly for System.Globalization.Extensions on .NETCoreApp,Version=v1.0,
but there is no run-time assembly compatible with win81-x64.
    System.Security.Cryptography.Cng 4.1.0-rc2-24018 provides a compile-time ref
erence assembly for System.Security.Cryptography.Cng on .NETCoreApp,Version=v1.0
, but there is no run-time assembly compatible with win81-x64.
    System.Security.Cryptography.Csp 4.0.0-rc2-24018 provides a compile-time ref
erence assembly for System.Security.Cryptography.Csp on .NETCoreApp,Version=v1.0
, but there is no run-time assembly compatible with win81-x64.
    System.Diagnostics.Tools 4.0.1-rc2-24018 provides a compile-time reference a
ssembly for System.Diagnostics.Tools on .NETCoreApp,Version=v1.0, but there is n
o run-time assembly compatible with win81-x64.
    One or more packages are incompatible with .NETCoreApp,Version=v1.0 (win81-x
64).

NuGet Config files used:
    C:\Users\ibrmohammed\Source\Workspaces\SbmAps\Idp\NuGet.Config
    C:\Users\ibrmohammed\AppData\Roaming\NuGet\NuGet.Config

Feeds used:
    https://www.myget.org/F/aspnet-contrib/api/v2
    https://www.myget.org/F/aspnetvnext/api/v2
    http://www.myget.org/F/azureadwebstacknightly/
    https://api.nuget.org/v3/index.json
    https://www.myget.org/F/xunit/api/v3/index.json
    https://www.myget.org/F/aspnetcirelease/api/v3/index.json

**Comment by ibrmohammed** [comment]
@davidfowl any thing more that I have to check.to get this resloved
