### ISSUE TITLE
hosting site using dotnet publish gave 500 Internal server error.

### ISSUE THREAD

**Issue by ibrmohammed** [aspnet/Hosting#717]
installed asp.net core x64 module.
added the following dependency "Microsoft.AspNetCore.Server.IISIntegration": "1.0.0-rc2-*"
modified my startup.cs
![image](https://cloud.githubusercontent.com/assets/5870046/14663123/b37d8e2c-06da-11e6-8bd9-df7dd6a00a02.png)

modified the web.config
![image](https://cloud.githubusercontent.com/assets/5870046/14663132/c02fe2fa-06da-11e6-968b-6df8c7e509f4.png)

publish folder using dotnet publish
![image](https://cloud.githubusercontent.com/assets/5870046/14663204/b0c6e8f8-06db-11e6-82a7-ced40552bffe.png)

copied the contents of publish folder in a c:/inetpub/wwwroot/IdpWebApp
![image](https://cloud.githubusercontent.com/assets/5870046/14663142/eebca8ec-06da-11e6-81f0-f21acdfd6a66.png)

created a webapplication and pointed to wwwroot of publish folder
![image](https://cloud.githubusercontent.com/assets/5870046/14663155/12e8fbbc-06db-11e6-9594-311abd91ca55.png)

Browsing the site gave me 500 internal server error
![image](https://cloud.githubusercontent.com/assets/5870046/14663163/2a893624-06db-11e6-91a7-c24826643746.png)

checked event viewer.It shows Asp.net core module started successfully.
![image](https://cloud.githubusercontent.com/assets/5870046/14663168/3a0500a6-06db-11e6-8f26-7d695459ebbe.png)

What's missing here.

**Comment by Tratcher** [comment]
You're pretty close actually, that's the Asp.Net startup error page. It means there was an exception starting your app, probably from the Startup class. If you set ASPNETCORE_ENVIRONMENT to Development you should get the details. The easiest place to set this is in the Web.Config, aspNetCore has an environment variables sub-section.

Also, UseIIS() was renamed to UseIISIntegration().

**Comment by ibrmohammed** [comment]
let's continue on this thread.

![image](https://cloud.githubusercontent.com/assets/5870046/14663314/44ae8f66-06dd-11e6-8eb8-1d81e89ea856.png)

my the reference that i added for IIsInteegration was v1.0.0-rc2-20466
![image](https://cloud.githubusercontent.com/assets/5870046/14663355/c40b1a72-06dd-11e6-8783-1a1bbf5bb58a.png)

**Comment by ibrmohammed** [comment]
can you ping the sample code of environment variables sub section

**Comment by muratg** [comment]
@ibrmohammed Set `ASPNETCORE_ENVIRONMENT` environment variable to Development, not `Hosting:Environment`.

**Comment by muratg** [comment]
@ibrmohammed Do you still have this issue?

**Comment by ibrmohammed** [comment]
yes I am still facing the issue.
did some changes to the main method.
## main method
             var builder = new ConfigurationBuilder()
		    .AddJsonFile("appsettings.json")
                    .AddEnvironmentVariables()
                    .AddCommandLine(args)
                    .Build();

                var application = new WebHostBuilder()
                  //.UseDefaultHostingConfiguration()                  
                  //.UseIISPlatformHandlerUrl()
                  .UseConfiguration(builder)
                  .UseIISIntegration()
                  .UseServer("Microsoft.AspNetCore.Server.Kestrel")
                  .UseStartup<Startup>()
                  .Build();

## project.json changes
"content": [
    "wwwroot",
    "appsettings.json",
    "web.config"
  ],

  "frameworks": {
    "net451": { }
  },

## Dependencies
"Microsoft.NETCore.DotNetHostPolicy": "1.0.1-*",
    "Microsoft.Extensions.Configuration.CommandLine": "1.0.0-rc2-*",
    "Microsoft.Extensions.Configuration.EnvironmentVariables": "1.0.0-rc2-*",
    "Microsoft.Extensions.Configuration.Json": "1.0.0-rc2-*"

## scripts
"scripts": {
    "prepublish": [ "npm install", "bower install", "gulp clean", "gulp min" ],
    "postpublish": "dotnet publish-iis --publish-folder %publish:OutputPath% --framework %publish:FullTargetFramework%"
  }

## Actual behavior
did a dotnet restore and a dotnet run

## my queries
1.the publish-IIS tool. where does this publish the project.Is dot net run command enough to  publish  the project or should I again do with dotnet publish command.

2. the target framework I am using is net451.When should we use netcoreapp 1.0.Are DOTNET CLI commands dependent on netcoreapp1.0

3. As I was not clear about publish-IIS tool I executed the following command
    dotnet publish --configuration Release --runtime win81-x64.This created a folder with net451 and a sub folder win81-x64.
   ## Folders
 publish
wwwroot
  ## Publish folder contents
refs
wwwroot
Myproject.dll and other dlls
web.config

## web.config
 Web.config

    <handlers>
      <add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModule" resourceType="Unspecified" />      
    </handlers>
    <aspNetCore processPath="%LAUNCHER_PATH%" arguments="%LAUNCHER_ARGS%" stdoutLogEnabled="false" stdoutLogFile=".\logs\stdout" forwardWindowsAuthToken="false" />    
  



## IIS hosting
copied all the contents of publish folder and pointed the websites physical path to wwwroot folder

## iis hosting issues
![502 3](https://cloud.githubusercontent.com/assets/5870046/15010939/a8e531b2-120c-11e6-9af5-bbbc6628919c.png)

## event viewer
![eventvwr](https://cloud.githubusercontent.com/assets/5870046/15011111/9c71748a-120d-11e6-99ec-573aa30bc8d1.png)

**Comment by moozzyk** [comment]
Show your web.config after publishing - if the web.config you showed is what you got after publishing this is the problem. It was not updated correctly - you still have `processPath="%LAUNCHER_PATH%" arguments="%LAUNCHER_ARGS%"`. 
Also show your project.json - the tools section. Are you sure you are using the new publish-iis tool as per: https://github.com/aspnet/Announcements/issues/169 and https://github.com/aspnet/Announcements/issues/172?
Finally, when you publish publish-iis will print some output - can you show it as well?

**Comment by ibrmohammed** [comment]
The web.config I have shared is after doing "dotnet publish". Yes I am using the tools section below.
## Tools
 "tools": {
    "Microsoft.AspNetCore.Server.IISIntegration.Tools": {
      "version": "1.0.0-*",
      "imports": "portable-net45+wp80+win8+wpa81+dnxcore50"
    }
  }

## Scripts
"scripts": {
    "prepublish": [ "npm install", "bower install", "gulp clean", "gulp min" ],
    "postpublish": "dotnet publish-iis --publish-folder %publish:OutputPath% --framework %publish:FullTargetFramework%"
  }


## Project structure
The project was started earlier using asp.net 5. Then we moved the application to core.
Currently my web.config is located inside wwwroot folder.How important is this?
I have checked some core samples and web.config is located at the web project level.

## queries
How does publish-iis tool gets triggered.Is it after I run the following command
dotnet publish --configuration Release --runtime win81-x64

**Comment by moozzyk** [comment]
It does not look to me that publish-iis ran at all. Can you share your application and show exact steps to repro this?

**Comment by ibrmohammed** [comment]
Please find the application here https://github.com/ibrmohammed/IDPNew
web project is located in src --> aps.idp.web

## repro steps
dotnet restore on the solution folder
traverse to path src --> aps.idp.web --> dotnet run
dotnet publish --configuration Release --runtime win81-x64

**Comment by moozzyk** [comment]
@ibrmohammed - I got 404 when I try the link you provided.

**Comment by moozzyk** [comment]
I was able to repro this. For now publish with `-r win7-x64`

**Comment by moozzyk** [comment]
The issues is in the `dotnet publish`. I filed this: https://github.com/dotnet/cli/issues/2956. Closing as external.

**Comment by uflex99** [comment]
This error also occurs when attempting a database connection from the startup (eg for seeding) and it fails on the deployment server due to insufficent previleges at the database server.
