### ISSUE TITLE
Cannot set self-hosting url using command line argument and hosting.json

### ISSUE THREAD

**Issue by xatabhk** [aspnet/Hosting#724]
"dotnet run -serverurl http://xyz:5000" or 
"siteapp.exe -serverurl http://xyz:5000" does not work. Neither does ""server.urls": "http://xyz:5000/"" in hosting.json. Only "UseUrls("http://xyz:5000")" in code works.

**Comment by Tratcher** [comment]
Share your Program.Main and and your hosting.json file. The command line should be `server.urls` not `serverurl`.

**Comment by xatabhk** [comment]
@Tratcher  server.urls does not work for me.
![host_url_error](https://cloud.githubusercontent.com/assets/6814395/14765725/651180c4-0a20-11e6-8d8b-db4bbe10e597.png)

Program.Main and hosting.json:
		public static void Main(string[] args)
		{
			var application = new WebHostBuilder()
				.UseDefaultHostingConfiguration(args)
				.CaptureStartupErrors(true)
				.UseKestrel()
				//.UseUrls("http://.:5000")	
				.UseIISIntegration()
				.UseStartup<Startup>()
				.Build();  

				application.Run();
		}//public static void Main(string[] args)

{
    "server": "Microsoft.AspNetCore.Server.Kestrel",
    "server.urls": "http://wdwin10:5001/"
}

**Comment by cwe1ss** [comment]
I think you need two dashes - so it should be `--server.urls`

**Comment by xatabhk** [comment]
@cwe1ss Same result.
![host_url_error_2](https://cloud.githubusercontent.com/assets/6814395/14765785/1a00323e-0a24-11e6-9a6f-260a0cb87878.png)

**Comment by cwe1ss** [comment]
I missed that you use dotnet cli.

Try `dotnet run -- --server.urls http://...`

See [docs](https://github.com/dotnet/cli/blob/rel/1.0.0/src/dotnet/commands/dotnet-run/README.md) for more details.

**Comment by xatabhk** [comment]
@cwe1ss Not this one either. But I got the command line figured out. Here is:
dotnet run /server.urls http://.:8000
Aslo hosting.json is now working after the app rebuilt.
