### ISSUE TITLE
RC2 Templates Review follow-up: Remove UseDefaultHostingConfiguration

### ISSUE THREAD

**Issue by rustd** [aspnet/Hosting#727]
From the templates review, it was brought up that the following line of code (https://github.com/aspnet/Templates/blob/dev/src/BaseTemplates/StarterWeb/Program.cs#L18) should be removed from the templates. Please make the corresponding FX changes.
```c#
               // ToDo: Open a bug
                .UseDefaultHostingConfiguration(args)
```
@muratg FYI

**Comment by muratg** [comment]
@JunTaoLuo This is from the templates review today. Please have a look, and send a mail to @Eilon and @DamianEdwards for approval.

cc @Tratcher

**Comment by muratg** [comment]
https://github.com/aspnet/Hosting/issues/700

**Comment by khellang** [comment]
@muratg During the template review, did you discuss IStartup/StartupBase/ConventionBasedStartup? :smile:

**Comment by davidfowl** [comment]
We didn't but I don't see us using that interface in the templates.

**Comment by khellang** [comment]
So that means ConventionBasedStartup implicitly, like today?

**Comment by DamianEdwards** [comment]
It did come up as I thought we were making that change (to use `IStartup`). For now it appears we're staying with the convention based approach in the templates by default.

**Comment by khellang** [comment]
Alright. As long as I can opt-out (of the conventions), I'm all good :smile:

**Comment by JunTaoLuo** [comment]
Need to track the updates of our samples.
