### ISSUE TITLE
Self host deployers not testing on full CLR if test app is not published before deployment

### ISSUE THREAD

**Issue by JunTaoLuo** [aspnet/Hosting#728]
Currently if the app is not published before deployment the command executed by the self host deployer looks like `dotnet run -p "C:\gh\Localization\samples\LocalizationSample" -- --server.urls http://localhost:5081/  --server Microsoft.AspNetCore.Server.Kestrel`. This is missing the framework specification `--framework net451/netcoreapp1.0` and will always run the coreclr version by default. As a result, some of our full CLR functional tests currently are tested with CoreCLR instead. We should update the deployer so we don't have this hole in our test coverage.

**Comment by Eilon** [comment]
@muratg do we want to do this for RC2? If we're missing important test coverage we should add this ASAP.

**Comment by muratg** [comment]
Yes, we should do this now. @JunTaoLuo I assume the change is not that hard (although if tests fail, fixing those may take some time.)
