### ISSUE TITLE
Remove UseServer overloads

### ISSUE THREAD

**Issue by davidfowl** [aspnet/Hosting#731]
We're moving away from generic hosting understanding how to wire up servers to servers adding themselves to the DI container via first class extension methods. This also avoids issues where the default extension methods setup things by default (like a default set of options) so that it's possible to configure server settings in the application.

**Comment by muratg** [comment]
This would be a breaking change, right? So in RC2? Could you start a thread for approval?

cc @Eilon @DamianEdwards

**Comment by Eilon** [comment]
What exactly do we want to remove/change? And are these APIs already frequently used?

**Comment by muratg** [comment]
Let's revisit after RC2.

**Comment by Tratcher** [comment]
Fowler's latest ask: Remove the extension, the config value, and the server factory that read the server value. Require servers be registered via DI in Main.
