### ISSUE TITLE
Not way to get assembly physical path

### ISSUE THREAD

**Issue by xyting** [aspnet/Hosting#741]
I need to read XML documentation at run-time, but I cannot find a way to get the physical path of my assembly.xml file

```C#
public static string XmlDoc(this MemberInfo member) {
            var assemblyName = member.Module.Assembly.GetName();
            // How can I get the assembly's physical path?
            var assemblyPhysicalPath = "?"
            var path = Path.Combine(assemblyPhysicalPath, assemblyName.Name + ".xml");

            return XmlDoc(member, path);
 }
```

**Comment by GuardRex** [comment]
@xyting I was just playing with a reflection approach for this via `GetTypeInfo()`, as I'm eventually going to need what you're doing to work here, too. If you can `GetTypeInfo()` on that `member.Module`, then it might just work.
```c#
Path.Combine(Path.GetDirectoryName(typeof(object).GetTypeInfo().Assembly.Location), assemblyName.Name + ".xml")
```

**Comment by davidfowl** [comment]
Also has nothing to do with ASP.NET. APIs questions like these belong on github.com/dotnet/corefx

**Comment by xyting** [comment]
@GuardRex If using the types of GAC, the location is correct, but I run the same code in ASP.NET core RC1, the typeof(myObject).GetTypeInfo().Assembly.Location, the Location is "".

I run my web app in VS using project.json web command

  "commands": {
    "web": "Microsoft.AspNet.Server.Kestrel --ASPNET_ENV Development"
  },

**Comment by GuardRex** [comment]
@xyting Open this issue over at https://github.com/dotnet/corefx/issues ... idk on the actual answer either other than what I was hacking around with, but they will know over there what to do.

**Comment by davidfowl** [comment]
It's empty string because of dynamic compilation. If you publish with `--no-source` in RC1, you'll have something on disk.

**Comment by xyting** [comment]
@davidfowl Makes sense. Thanks for the answer!

**Comment by shaunluttin** [comment]
@GuardRex Could you please add a link to the issue that you opened. I couldn't find it though I searched. https://github.com/dotnet/corefx/issues?utf8=%E2%9C%93&q=is%3Aissue%20author%3Aguardrex

**Comment by shaunluttin** [comment]
This is working: 

```
var location = System.Reflection.Assembly.GetEntryAssembly().Location;
var directory = System.IO.Path.GetDirectoryName(location);
System.Console.WriteLine(directory);
```

**Comment by GuardRex** [comment]
@shaunluttin Oh, I didn't open one. I was just saying to @xyting that he should open one on it.

I get the assembly this way ...
```c#
Assembly.GetEntryAssembly().GetName().Name
```
for logging purposes.

`publish iis` tooling does it this way to get the file ...
```c#
var projectContext = GetProjectContext(applicationBasePath, _framework);
var appName = projectContext.ProjectFile.GetCompilerOptions(
    projectContext.TargetFramework, _configuration).OutputName;
// For a portable app, this will return `myapp.dll` in appName.
// For a self-contained app, this will return `myapp.exe` in appName.
```
and
```
private static ProjectContext GetProjectContext(string applicationBasePath, string framework)
{
    var project = ProjectReader.GetProject(Path.Combine(applicationBasePath, "project.json"));

    return new ProjectContextBuilder()
        .WithProject(project)
        .WithTargetFramework(framework)
        .Build();
}
```
