### ISSUE TITLE
Option to remove AutoRequestServicesStartupFilter

### ISSUE THREAD

**Issue by benaadams** [aspnet/Hosting#742]
If you don't need `RequestServices` how can you remove `AutoRequestServicesStartupFilter` from startup?

I've tried a few things but its very tenacious. 

`RequestServicesContainerMiddleware.Invoke` for a small function is quite chunky:

![request-services-movenext](http://aoa.blob.core.windows.net/aspnet/request-services-movenext-1.png)

**Comment by khellang** [comment]
Can't you just yank out the `AutoRequestServicesStartupFilter` service descriptor somewhere?

**Comment by davidfowl** [comment]
You can:

```
services.Remove(services.FirstOrDefault(s => s.ServiceType == typeof(IStartupFilter)));
```

You can't really use much middleware without it though 😄

**Comment by benaadams** [comment]
> You can't really use much middleware without it though

Have some very single minded servers :laughing:

**Comment by benaadams** [comment]
Works! Thank you :)
