### ISSUE TITLE
Hosting the Mvc.Server project on IIS with net451 not working

### ISSUE THREAD

**Issue by ibrmohammed** [aspnet/Hosting#744]
## project
https://github.com/openiddict/openiddict-core
This project has sample MVC.Server which i am trying to host on IIS

## Actual Behaviour
when i publish with netcoreapp1.0 as a target framework and host on IIS it works fine.
But when i publish with net451 as a target framework and  host on IIS it doesn't.

For More info about this
https://github.com/openiddict/openiddict-core/issues/105

**Comment by Tratcher** [comment]
@moozzyk @halter73 Libuv loading issue

**Comment by moozzyk** [comment]
I saw it over the weekend. I will look into it. I don't think this is libuv related per se. Rather a weird combination of bitness/OS/dependencies.

**Comment by moozzyk** [comment]
This is an issue in dotnet publish: https://github.com/dotnet/cli/issues/2956
