### ISSUE TITLE
Question: Can we use net451 with aspnetcore applications?

### ISSUE THREAD

**Issue by Challagolla** [aspnet/Hosting#745]
Hi Team,
Can someone please educate me on which version to use with the web applications built using latest asp.net RC2 packages ? as per the asp.net core [documentation](http://dotnet.github.io/docs/core-concepts/app-types.html), i understood that we need to use netcoreapp1.0 framework. But, i have found several applications building on github are using net451 framework. what is the difference between these two frameworks? is there any article/link which can explain the different frameworks that can be used with the latest aspnet core web applications. if we use the net451 framework, does the hosting work correctly?

Thanks In Advance.

**Comment by muratg** [comment]
@Challagolla Yes, you should be able to use net451 with asp.net core apps if you want to target full CLR (instead of CoreCLR). However, I suggest using net452 at least (as .NET Framework 4.5.1 is not officially supported by Microsoft anymore).

**Comment by Challagolla** [comment]
@muratg thanks for the informaton. please share if there any documentation location where we can find the current supported versions of the .net frameworks.

**Comment by davidfowl** [comment]
@Challagolla are you using visual studio? You can just download the latest bits and create a new project

**Comment by muratg** [comment]
We are closing this issue because no further action is planned for this issue. If you still have any issues or questions, please log a new issue with any additional details that you have.
