### ISSUE TITLE
The default port 5000 conflicts with commplex-main/UPnP

### ISSUE THREAD

**Issue by moozzyk** [aspnet/Hosting#746]
As a result when you start an app with default settings it fails on Mac with `(Error -48 EADDRINUSE address already in use)`

**Comment by khellang** [comment]
Would it be crazy to move to `http://localhost:0` (dynamic port) as a default?

**Comment by GuardRex** [comment]
They list 1900, 5350, 5351, and 5353 ... https://support.apple.com/en-us/HT202944

**Comment by moozzyk** [comment]
@GuardRex - I think you are right - it's used by commplex-main.

**Comment by Matthew-Bonner** [comment]
Not only that, 5000 seems a very strange port to listen on, most would have gone with port 8080.

**Comment by Tratcher** [comment]
Yes, we avoided 8080 as it was more likely to have a conflict.
