### ISSUE TITLE
How to debug a web application which is running on DotNet CLI

### ISSUE THREAD

**Issue by ibrmohammed** [aspnet/Hosting#747]
apologies in advance.I do not know where to put up this query of mine. pls let me know.
I have an aplication which uses net451 and i have run dotnet CLI commands to restore it.
On dotnet run I have the application running on localhost:5000

How can we debug this application.the problem that i have here is when i open my code in VS2015,
it asks me to install dnx packages.

**Comment by aL3891** [comment]
VS2015 doesn't support the new cli yet, although we'll see preview tooling fairly soon, check out https://blogs.msdn.microsoft.com/dotnet/2016/05/06/net-core-rc2-improvements-schedule-and-roadmap/

**Comment by Challagolla** [comment]
Does this mean, we do not have any way to debug the applications that are using DotNet CLI ?

**Comment by GuardRex** [comment]
@Challagolla You can use VS Code to debug apps. Since they've been saying "mid-May" for an RC2 release (with updated VS tooling), I don't think you have long to wait. There is a Community Standup today, and it's likely we'll get a progress report on where they're at: https://live.asp.net/

**Comment by moozzyk** [comment]
You can start your application and attach the debugger to the process.

**Comment by DreamingDevs** [comment]
@moozzyk Can you share some tutorials or links around debugging RC2 app with DOTNET RUN command process.

**Comment by moozzyk** [comment]
Here is the tutorial :) 
1. Start your app with `dotnet -v run` - `-v` will tell you the process id so that you don't have to guess if you have multiple `dotnet` processes running
2. From Visual Studio - Ctrl + Alt + P (Debug -> Attach to Process), select the `dotnet` process you started and Attach. For simplicity make sure that you have automatic code type
3. Open source code, set breakpoints, perform an action that uses the code path where you set the breakpoint and it should be hit (if symbols were loaded correctly)

If you need to debug something that runs immediately after you run `dotnet run` (e.g. `Main`)  the hack of the day is to use `Console.ReadLine()` to stop execution of the app until you attach to the process and set the breakpoint. Once you are done press enter to resume execution.

**Comment by DreamingDevs** [comment]
Thanks @moozzyk, I know VS CTRL + ALT + P, but I was side tracked by VS Code. Now I was able to debug the code.

**Comment by MartinDawson** [comment]
@moozzyk `-v` doesn't show the process id anymore it seems.

Also I attach it to dotnet.exe and it doesn't hit the breakpoint, they never turn from white to red.

**Comment by moozzyk** [comment]
@MartinDawson - either you are not attaching to the right dotnet.exe (easy to pick a wrong one if there is more than one running), the assembly was not loaded yet or the debugger cannot find the symbols. Ctrl+Alt+U to display modules and if you cannot find your modules it either 1) or 2). Send a request to make sure that code is loaded. If you see your dlls in the module list it's 3). Right click and tell it to load the symbols. It will open a dialog which you will use to select the folder with the symbols. The symbols have to match.

**Comment by MartinDawson** [comment]
@moozzyk Figured it out. Dotnet.exe was the wrong process, it was comming up as my applications name. Thanks.

**Comment by junkangli** [comment]
How do you identify the process id of `dotnet.exe` now in sdk 2.0?

**Comment by MartinDawson** [comment]
@junkangli in program.cs just `console.writeline(Process.GetCurrentProcess().Id)`

**Comment by moozzyk** [comment]
@junkangli @MartinDawson - trick of the day. 99% of times the dotnet.exe you want to attach to is the first dotnet.exe on the Ctrl+Alt+P list. (My understanding is that it is the most recently started).

**Comment by travrob1** [comment]
What if you are trying to debug a simple app that runs, executes the code, and terminates.
I am still learning and I am using simple apps to do so.
My program ends way before i have time to attach to the process.
