### ISSUE TITLE
Question: Is IFormFile SaveAsAsync function not available in AspNetCore Http ?

### ISSUE THREAD

**Issue by zenixgrace** [aspnet/Hosting#750]
Hi Team,

is IFormFile in Microsoft.AspNetCore.Http namespace doesn't have SaveAsAsync function?
it available when use Microsoft.AspNet.Http namespace

**Comment by Tratcher** [comment]
It was simplified to `CopyToAysnc(Stream)`
https://github.com/aspnet/HttpAbstractions/blob/dev/src/Microsoft.AspNetCore.Http.Features/IFormFile.cs#L61

**Comment by zenixgrace** [comment]
@Tratcher  thanks for the information. I found old source and use the extension
