### ISSUE TITLE
Script working with localhost url and not with servername

### ISSUE THREAD

**Issue by lenzodb** [aspnet/Hosting#751]
I have an application interacting with servers to stop-start service.
I have put a waiting screen to block the windows.
all is working like I want on visual studio and also on the server when  I access the site from the server opening it with the url http://localhost:8020/ I can see my waiting screen but when I try to reach the site with the server name from my computer of from the server itself the wainting screen is not displaying.
so url http://ap6472:8020/ form my pc of form the server where the site is hosted the waiting screen is not ok.
this is the aspx code I have in my masterpage
```html
        <style>
          .subinsblogSpec
        {
            
            background: black url(http://ap6472:8020/loader.gif) 50% 50% no-repeat ;
            background-color :  White ;
            background-position-x : 50% ;
            background-position-y : 50% ;
            position :absolute;
            right:0px;
            left:0px;
            top:0px;
            bottom:0px;
            opacity:0.8;
        }

    </style>
    <script>
       subinsblogla = 0;
       setInterval(function () {
           if (document.readyState != 'complete') {
               document.documentElement.style.overflow = "hidden";
               var subinsblog = document.createElement("div");
               subinsblog.id = "subinsblogldiv";
               var polu = 99 * 99 * 99999999 * 999999999;
               
               subinsblog.style.zIndex = polu;
               subinsblog.classList.add("subinsblogSpec");

               if (subinsblogla == 0) {
                   document.documentElement.appendChild(subinsblog);
                   subinsblogla = 1;
               }
           } else if (document.getElementById('subinsblogldiv') != null) {
               document.getElementById('subinsblogldiv').style.display = "none";
               document.documentElement.style.overflow = "auto";
           }
       }, 1000);
</script>
```
site is running on windows 2012 iis 8.5

**Comment by GuardRex** [comment]
@lenzodb There could be several reasons leading to this behavior. Did you run down the Troubleshooting section at https://docs.asp.net/en/latest/publishing/iis.html#common-errors? Also note that devs online at Slack can help you sort through a config issue like this (get into the chat via this link: http://tattoocoder.com/aspnet-slack-sign-up/ ).

**Comment by muratg** [comment]
@lenzodb Could you share your web.config?  Since it's working on localhost, it feels like this is a problem with your IIS configuration.

@Tratcher any ideas?

**Comment by moozzyk** [comment]
Can it be that the registered url is http://*localhost*/ and therefore all requests the refer to the machine with a name or ip are rejected?

**Comment by GuardRex** [comment]
Not if the binding is correct and the `.UseIISIntegration()` is below the `.UseUrls()`, right?

**Comment by GuardRex** [comment]
I noticed that if you move the host off of `localhost` that adding an entry to the `HOSTS` file at `c:\windows\system32\drivers\etc\hosts` will permit the site to be browsed.
```txt
127.0.0.1 myhost
```
![binding](https://cloud.githubusercontent.com/assets/1622880/15371665/3c879fae-1d02-11e6-8c21-c97cf2665d7e.png)


![capture](https://cloud.githubusercontent.com/assets/1622880/15371653/2ae35c98-1d02-11e6-8567-f5f6b4b6dd32.PNG)

**Comment by buraktamturk** [comment]
Does Kestrel binds ipv6 localhost (::1)? If it does not, this could happen when localhost resolved as ipv6 (::1) instead of ipv4's 127.0.0.1.

**Comment by buraktamturk** [comment]
Missed a point in my previous post. Kestrel or whatever the server is (IIS etc.) has to be bind on 0.0.0.0 or any external/internal ip, where connection made to, in order to make it accessible over network.

**Comment by lenzodb** [comment]
HI thanks for your advise
I will check the likes shared by luke...
As requested by muratg  I share my web.config 
<?xml version="1.0" encoding="UTF-8"?>
<configuration>
	<configSections>
		<sectionGroup name="applicationSettings" type="System.Configuration.ApplicationSettingsGroup, System, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089">
			<section name="NewServicesManagement.Properties.Settings" type="System.Configuration.ClientSettingsSection, System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" requirePermission="false" />
			<section name="NewServiceManagement.Properties.Settings" type="System.Configuration.ClientSettingsSection, System, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" requirePermission="false" />
			<section name="WebApplication9.Properties.Settings" type="System.Configuration.ClientSettingsSection, System, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" requirePermission="false" />
		</sectionGroup>
	</configSections>
	<appSettings />
	<connectionStrings>
    
      <add name="Strconn" connectionString="Data Source=CA-SQL-SHA\SHAA;Initial Catalog=DbWmc;User ID=UserWMC;Password=************** providerName="System.Data.SqlClient" />
	</connectionStrings>
	<system.web>
		
		<compilation debug="true" targetFramework="4.0">
		</compilation>
		
            <authentication mode="Windows" />
            <identity impersonate="false" />

		
		<pages controlRenderingCompatibilityVersion="4.0" clientIDMode="AutoID" /></system.web>
	
	<applicationSettings>
		<NewServicesManagement.Properties.Settings>
   <setting name="NewServicesManagement_wsslib_library" serializeAs="String">
    <value>http://wsslib/library.asmx</value>
   </setting>
   <setting name="NewServicesManagement_bc_win_oai_ComputerManagement_GetTemporaryLocalAdminMembership_1_0_Service" serializeAs="String">
    <value>http://oai.win.bc/BMS_Service/servicerouter.v1.svc/IServiceRouter</value>
   </setting>
  </NewServicesManagement.Properties.Settings>
	</applicationSettings>
 <system.serviceModel>
  <bindings />
  <client />
 </system.serviceModel>
    <system.webServer>
        <defaultDocument>
            <files>
                <add value="index.aspx" />
            </files>
        </defaultDocument>

    </system.webServer>
</configuration>

**Comment by lenzodb** [comment]
What I have tested also is form the server to reach my page with http://127.0.01:8020/ and the script doesn't work and same issue with the IP of the sever so it works strangely only with the url localhost...

**Comment by lenzodb** [comment]
I found the solution on the net 
it's a problem of compatibility it seems
I have added the following lines and now it's working
 <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

**Comment by muratg** [comment]
@lenzodb Good to hear! Let us know is you have other issues.
