### ISSUE TITLE
Using a config file with Microsoft service

### ISSUE THREAD

**Issue by evkw** [aspnet/Hosting#752]
Hey,

Ive created a service and got it all humming along nicely.I use a config.json to do some configuration stuff in the app and if this file is not in c:/windows/system32 (where the service starts) it throws a IO.FileNotFoundException.

Is there an easy way to tell the service to look for the file in the published output path?

```
    public class Program
    {
        public static void Main(string[] args)
        {
            var host = new WebHostBuilder()
                .UseKestrel()
                .UseContentRoot(Directory.GetCurrentDirectory())
                .UseIISIntegration()
                .UseStartup<Startup>()
                .Build();

            if (Debugger.IsAttached)
            {
                host.Run();
            }
            else
            {
                host.RunAsService();
            }
        }
    }
```
```
public Startup(IHostingEnvironment env)
        {
            // Set up configuration sources.
            var configBuilder = new ConfigurationBuilder()
                .SetBasePath(env.ContentRootPath)
                .AddJsonFile(Path.Combine(env.ContentRootPath, "config.json"));

            Configuration = configBuilder.Build();
        }
```

**Comment by davidfowl** [comment]
Change the call to `UseContentRoot` to be more somewhere more appropriate (you might want to try removing that call from `Program.Main`

**Comment by evkw** [comment]
Removing it still has the same issue. My first thought was to use the ContentRootPath on IHostingEnvironment, but im not sure how to access that from the static main.

I'll keep pressing buttons, something will work eventually

**Comment by davidfowl** [comment]
You always want to use the ContentRootPath on `IHostingEnvironment`. You need to figure out what to set it to. What did you remove? The call to `UseContentRoot` or the call to `SetBasePath`?

**Comment by evkw** [comment]
I take it back, you were right about removing the the call in program.main.

dotnet publish either didnt replace the binaries.. or i did it to the wrong file.

In the end my main and startup look like this

```
 public static void Main(string[] args)
        {
            var host = new WebHostBuilder()
                .UseKestrel()
                .UseIISIntegration()
                .UseStartup<Startup>()
                .Build();

            if (Debugger.IsAttached)
            {
                host.Run();
            }
            else
            {
                host.RunAsService();
            }
        }

```
```
 public Startup(IHostingEnvironment env)
        {
            // Set up configuration sources.
            var configBuilder = new ConfigurationBuilder()
                .SetBasePath(env.ContentRootPath)
                .AddJsonFile("config.json");

            Configuration = configBuilder.Build();
        }
```

Thank you for your help :)
