### ISSUE TITLE
Returning IServiceProvider from WebHostBuilder.ConfigureServices

### ISSUE THREAD

**Issue by myefforts** [aspnet/Hosting#754]
Is there any way to return an IServiceProvider instance via ConfigureServices on WebHostBuilder? I'm trying to replicate the functionality that used to be available in RC1 on Microsoft.AspNetCore.TestHost.TestServer.Create() but with the API change in RC2 does not seem to be.

**Comment by davidfowl** [comment]
Nope, it's not possible without a `Startup` class. There's separation between the hosting services and the application container.

**Comment by myefforts** [comment]
Thanks for response
