### ISSUE TITLE
Add a second environment variable for Urls

### ISSUE THREAD

**Issue by glennc** [aspnet/Hosting#755]
Add `ASPNETCORE_URLS` in addition to `server.urls`.

**Comment by JunTaoLuo** [comment]
Curious why we want to add another environment variable that does the same thing? Is it because environment variables containing dots are hard to set in certain environments? If that's the case, maybe we should consider renaming the environment variable instead simply adding another one?

**Comment by davidfowl** [comment]
> Curious why we want to add another environment variable that does the same thing? Is it because environment variables containing dots are hard to set in certain environments? 

> If that's the case, maybe we should consider renaming the environment variable instead simply adding another one?

We don't want to break anybody so we're going to add a new one and deprecate the old one. Eventually we can remove it.
