### ISSUE TITLE
Double request on first run

### ISSUE THREAD

**Issue by hikalkan** [aspnet/Hosting#762]
Maybe related to https://github.com/aspnet/Hosting/issues/603, but I did not used HTTPS. Just created a new project from standard template and added a breakpoint to Home/Index. When I press F5 to debug application, Index action is called twice on first run (from different threads). Then I browse other pages including home, it only calls once per page. I suspect there is a bug here.

**Comment by GuardRex** [comment]
Duplicate of https://github.com/aspnet/Tooling/issues/261 with WIP in https://github.com/aspnet/IISIntegration/issues/102

**Comment by hikalkan** [comment]
Thank you, I could not find them.
