### ISSUE TITLE
Use single-thread SynchronizationContext

### ISSUE THREAD

**Issue by tmds** [aspnet/Hosting#765]
Is there a way to setup the pipeline so execution is done on a SynchronizationContext?

I want to make a webapp with shared state and avoid multithreading issues by having a single-threaded SynchronizationContext.

**Comment by davidfowl** [comment]
Then you need to write your own webserver. Kestrel doesn't support this.

**Comment by tmds** [comment]
@davidfowl does this need support from the webserver? is it not possible to setup it up in the handler pipeline?

**Comment by davidfowl** [comment]
@tmds Kestrel is not a single threaded webserver so it depends on what you care about. What do you care about? Using a single thread for handling the request? The request itself runs on a random threadpool thread. Are you trying to control what happens when user code awaits? If you only care about the request pipeline then you could setup a sync context as a piece of middleware or as an `IStartupFilter`.

> I want to make a webapp with shared state and avoid multithreading issues by having a single-threaded SynchronizationContext.

Can you elaborate? Maybe with an example?

**Comment by tmds** [comment]
I'd like all requests on the pipeline to be handled by a single thread, similar to what happens in a nodejs app.

Suppose there is some code down the pipeline which deals with shared state, it should be safe to run without any locks:

```
s_staticCounter++;
await Task.Yield();
s_staticCounter++;
```

If I want to do it as Middleware, would it be something like this?

```
var tcs = new TaskCompletionSource<Task>();
s_synchronizationContext.Post(
	try
	{
		var result = next(context);
		tcs.SetResult(result);
	}
	catch (Exception e)
	{
		tcs.SetException(e);
	}
)
return await tcs.Task;
```

**Comment by davidfowl** [comment]
> I'd like all requests on the pipeline to be handled by a single thread, similar to what happens in a nodejs app.

That's impossible. The WebServer is multi threaded...

**Comment by tmds** [comment]
I'd like to implement some request handlers with shared state and make those thread safe by executing them on a single thread.

Does this make sense?

So:
* the webserver may accept requests on multiple threads
* and I want to use a piece of middleware which has the effect that 'next' handlers starts running on a single thread and awaits return to the single thread (unless ConfigureAwait(false))

Is this possible?

**Comment by davidfowl** [comment]
Yes, you can wrap the middleware pipeline execution by setting a sync context for the duration of the execution and removing it afterwards. You can also add an `IStartupFilter` if you don't want to make user code register a middleware at the right place.

**Comment by davidfowl** [comment]
But it just seems like a bad idea. Do you want deadlocks? Cuz that's how you end up dead locking 😄

**Comment by davidfowl** [comment]
```C#
app.Use(async (_, next) =>
{
    var current = SynchronizationContext.Current;

    try
    {
        SynchronizationContext.SetSynchronizationContext(SingleThreadedSyncContext);

        // Yield's execution to the sync context
        await Task.Yield();

        // Call user code
        await next();
    }
    finally
    {
        SynchronizationContext.SetSynchronizationContext(current);
    }
});
```

You're effectively turning the request processing pipeline into a giant queue of callbacks. Is that really want you want?

**Comment by tmds** [comment]
When I wrote the issue, I know it would be considered blasphemy ;)

It's a real easy way to deal with shared state. It's a tradeoff between performance and dealing with concurrency.

Libraries used in the pipeline should ConfigureAwait(false) when possible so their stuff gets done on other threads.

I don't plan to do this in any production apps.

Thanks for the code!
