### ISSUE TITLE
How to get access to the HostingEnvironment and the applicationEnvironment inside the WebHostBuilder?

### ISSUE THREAD

**Issue by paulvanbladel** [aspnet/Hosting#766]
The WebHostBuilder has 2 specific extension methods : Configure and ConfigureServices.

These methods are also part of the **Startup class**, but in the context of the Startup class, you can **inject** multiple other services (like applicationEnvironment and HostingEnvironment)
So, basically the setup of a webhost can be done via the WebHostBuilder without the Startup class, but what's the way to go to get access to the **HostingEnvironment and the applicationEnvironment** inside the Configure and ConfigureService Actions used in the aforementioned webhostbuilder extension methods?
Thanks.

**Comment by davidfowl** [comment]
What specifically are you trying to do?

**Comment by paulvanbladel** [comment]
I Want to use the UseUrls extension method  inside WebHostBuilder inside static void main.
As parameter for UseUrls I want to give something I read from the Configuration, So, I need to to do the ConfigurationBuilder stuff in static main rather than startup class.
That makes that the added value of startup class is reduced and I should better do the ConfigureServices and Configure directly in the WebHostBuilder.
In Startup class HostingEnvironment and applicationEnvironment are available, but NOT in static main, as far as I can see.

**Comment by Tratcher** [comment]
How about using `IWebHostBuilder.UseConfiguration and GetSetting` to access the config data?

**Comment by Tratcher** [comment]
Wait, why do you need HostingEnvironment to set up ConfigurationBuilder? You're just trying to set the config base path right? We use Directory.GetCurrentDirectory() to set that in Main.
https://github.com/aspnet/Security/blob/dev/samples/SocialSample/Program.cs#L21.

**Comment by GuardRex** [comment]
@paulvanbladel I do something similar to what you're doing with my "NUTJOB" startup pattern. My configuration is simply above the `WebHostBuilder` bits.

https://gist.github.com/GuardRex/f40f1b1414e175a6514f#file-nutjob-webhostbuilder-pattern-cs-L37

You'll see there where you could take the configuration first ... then have your `WebHostBuilder` below have a `.UseUrls()` on it to use config values. You'll be adding in the ability to read a file for your config ... all I do there is get env vars. Whatever you get in that config, you'll be able to use below in `WebHostBuilder` ... `ConfigureServices` and `Configure`.

**Comment by stefanoric** [comment]
+1 

The startup method has `IHostingEnvironment` injected and therefore you can do things like:

```
.AddJsonFile($"appsettings.{env.EnvironmentName}.json", optional: true)
```

What is the equivalent of doing the same from within the main method?

As the OP, I am also trying to assign the URL from a dynamic environment variable (will be passed in by the the host of the container, so it is not known at build time). But I don't seem to be able to find an elegant solution which keeps the advantages of the startup class.

**Comment by davidfowl** [comment]
Chicken and egg problem, you can't get to it. See https://github.com/aspnet/Hosting/issues/955 which attempts to solve this problem.
