### ISSUE TITLE
Discussion: Remove UseServer overloads

### ISSUE THREAD

**Issue by davidfowl** [aspnet/Hosting#767]
As part of https://github.com/aspnet/Hosting/issues/731 we removed support for passing the server as an assembly name. Servers will provide extension methods that add types directly to the DI container for configuring a specific Server e.g. 

``` C#
public class Program
{
    public static void Main(string[] args)
    {
        var host = new WebHostBuilder()
            .UseKestrel()
            .UseStartup<Startup>()
            .Build();

        host.Run();
    }
}
```

In the above example `UseKestrel()` replaces `UseServer("Microsoft.AspNetCore.Server.Kestrel")`. It's also less error prone.

**Comment by muratg** [comment]
We are closing this issue because no further action is planned for this issue. If you still have any issues or questions, please log a new issue with any additional details that you have.
