### ISSUE TITLE
Is there a nice way to propagate CommandLine configurations from Program.Main to Startup.ctor?

### ISSUE THREAD

**Issue by am11** [aspnet/Hosting#768]
In `Program.cs`, I have:

```cs
public static void Main(string[] args)
{
    // configuration building step 1: get hosting configurations
    var hostingConfig = new ConfigurationBuilder()
                       .AddCommandLine(
                           args,
                           new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
                           {
                               ["--port"] = "port",         ["-p"] = "port",
                               ["--urlhost"] = "host",      ["-u"] = "url",
                               ["--configfile"] = "file",   ["-c"] = "file",
                          })
                      .Build();

    // TODO: validate and set defaults for hosting configurations using
    //       our custom hostSettings.json.

    var host = new WebHostBuilder()
                    .UseKestrel()
                    .UseUrls($"{hostingConfig["host"]}:{hostingConfig["port"]}")
                    .UseConfiguration(hostingConfig)
                    .UseContentRoot(Directory.GetCurrentDirectory())
                    .UseIISIntegration()
                    .UseStartup<Startup>()
                    .Build();

    host.Run();
}
```

In `Startup` class' ctor, I want to access `configfile`:

```cs
public Startup(IHostingEnvironment env)
{
    // configuration building step 2: get web application configuration.
    var builder = new ConfigurationBuilder()
                 .SetBasePath(env.ContentRootPath)
                 .AddJsonFile("need to access configfile here?");

    Configuration = builder.Build();
}
```

One approach is to build all configurations in `Program.cs`.

The other approach is to add an `internal static ConfigFile { get; private set; }` prop in `Program.cs` and use `Program.ConfigFile` in `Startup.cs`.

Questions:

1. Is there a better (third) way to approach this problem, such as; making DI activator to inject `IConfigurationRoot` in another Startup ctor: `Startup(IHostingEnvironment, IConfigurationRoot)`?

2. Are those `Dictionary<string,string>` configurations set in `Program.Main` accessible at all anywhere else in Startup class or (injectable in other parts of the) application in general?

**Comment by davidfowl** [comment]
> Is there a better (third) way to approach this problem, such as; making DI activator to inject IConfigurationRoot in another Startup ctor: Startup(IHostingEnvironment, IConfigurationRoot)?

The benchkmarks program does something similar https://github.com/aspnet/benchmarks/blob/dev/src/Benchmarks/Program.cs. Also `UseConfiguration` on `WebHostBuilder` doesn't flow to the application.

> Are those Dictionary<string,string> configurations set in Program.Main accessible at all anywhere else in Startup class or (injectable in other parts of the) application in general?

That's your job. You need to inject them if you want access to them.

**Comment by am11** [comment]
Many thanks for pointing me to Benchmark repo @davidfowl! 🎉 
I replaced `.UseConfiguration(hostingConfig)` to `.ConfigureServices(services => services.AddSingleton(hostingConfig))` and activator injected `IConfiguration` to the ctor: `public Startup(IHostingEnvironment env, IConfiguration hostingConfig)`.

**Comment by davidfowl** [comment]
@am11 I would avoid sticking the `IConfiguration` directly in the DI container just because you may end up passing the wrong one to other components. Better to inject something very specific.

**Comment by leak** [comment]
@am11 
How did you deal with with EntityFramework, if you are even using it. I'm facing a similar problem but well since the entry point for EF CLI commands is Startup.cs, it does not know how to inject IConfiguation in the Startup ctor.

**Comment by am11** [comment]
@leak, we are not using EntityFramework but a custom storage management for Azure NoSQL storages.
