### ISSUE TITLE
Catch selfhost Startup errors and show them in the browser

### ISSUE THREAD

**Issue by Tratcher** [aspnet/Hosting#77]
When anything goes wrong with Helios' startup code path it will catch those errors, finish starting the server, and send an error page in response to any HTTP requests.

When anything goes wrong with the Self-Host startup code path it will throw an exception and crash the process. If you're lucky the exception will be printed on the console, but even this requires setting the ASPNET_ENV to Development.  This is even harder to debug in AppFabric or Azure Worker roles.

Proposal: Move/duplicate some of Helios' startup logic into the Hosting package. When errors occur locating the startup class/method or executing it, catch those and generate a default error page application instead.

There are only a small class of errors that would prevent the server from actually starting and serving such an error page (address conflicts, compiler errors, etc.), so we should be able to provide the error page for a range of common errors.

**Comment by davidfowl** [comment]
I like this suggestion

**Comment by muratg** [comment]
@Tratcher feel free to move this to RC1.

**Comment by davidfowl** [comment]
This cannot be moved to RC1
