### ISSUE TITLE
Windows authentication 

### ISSUE THREAD

**Issue by zigzag95** [aspnet/Hosting#775]
how to use NTLM Windows authentication when running from powershell using dotnet run or watch?
Ps this works when running from VS after checking Windows authentication

**Comment by davidfowl** [comment]
NTLM authentication only works with WebListener when self hosted or with IIS + Kestrel. You can't run `dotnet run` with IIS to get Windows Authentication, you need to use a different web server to do that. Kestrel does not support windows authentication on its own.

**Comment by zigzag95** [comment]
Thank you for the clear answer
