### ISSUE TITLE
Question: Memory consumption in RC2

### ISSUE THREAD

**Issue by VaclavElias** [aspnet/Hosting#781]
Hi,

This is a follow up from this https://github.com/aspnet/Hosting/issues/623#event-666241811

I have moved one website from RC1 to RC2 (net46). The website is using EF6, MySql.

I am running parallel both versions RC1 and RC2 so I could see memory consumption on my server.

**The result:**
RC1 - dnx.exe - **77MB**
RC2 - JyotiYoga.exe - **106MB**

Do you have the same results with your website?

![image](https://cloud.githubusercontent.com/assets/4528464/15775920/9359c90c-297c-11e6-9e33-54bf23f21016.png)

Also, I am going to move other around 20 websites to RC2 and I am still worried with what I mentioned here https://github.com/aspnet/dnx/issues/3371

20 websites \* 106MB = 2120MB of memory. 

Isn't ASP.NET Core hosting in IIS memory hungry? Again, the concern is hosting on **Microsoft Azure VM** where you cannot simply expand only memory and I would need to move actually my hosting to a different server provider for a better deal.

By the way on that IIS Worker Process w3wp.exe I am running 15 small ASP.NET MVC 5 websites.

I don't know too much about hosting but I am a bit worried.

15 ASP.NET MVC websites with 173-300MB memory consumption vs. 1 ASP.NET Core website with 106MB memory consumption.

Community, what is your experience?

**Comment by Tratcher** [comment]
The raw numbers don't mean much without a memory profile breakdown.

**Comment by davidfowl** [comment]
@VaclavElias Are you comparing the same application?

**Comment by VaclavElias** [comment]
@davidfowl Yes. It is the same application. I will have more applications to compare as I need to migrate around 20 RC1 to RC2 so will update this post :)

**Comment by davidfowl** [comment]
If you could provide us with both applications that would be great
/cc @SajayAntony

**Comment by VaclavElias** [comment]
Sure, how can I send them privately?

**Comment by muratg** [comment]
@VaclavElias Is RC1/RC2 the only difference between the apps?  Or per your first post, did you added EF to the mix?

**Comment by VaclavElias** [comment]
@muratg Yes, the only difference is RC1/RC2. 

I have updated my original post and moved the EF6, MySq words. That was just to let you know what I am using but placed it incorrently.

**Comment by SajayAntony** [comment]
@VaclavElias Would you be able to upload it somewhere and send the info to sajaya at microsoft.com.

**Comment by VaclavElias** [comment]
Will do in next 24 hours!

**Comment by mnltejaswini** [comment]
> By the way on that IIS Worker Process w3wp.exe I am running 15 small ASP.NET MVC 5 websites.
> 
> I don't know too much about hosting but I am a bit worried.
> 
> 15 ASP.NET MVC websites with 173-300MB memory consumption
@VaclavElias  Was 173-300MB  the memory of 15 JyotiYoga MVC 5 sites ?

**Comment by davidfowl** [comment]
We've made some changes that should improve this in later versions https://github.com/aspnet/DependencyInjection/pull/429.

**Comment by VaclavElias** [comment]
That sounds very good, can we expect it in 1.0.1 or later? Are the changes related only to the .net core or also some non recommended practices in the code I provided @mnltejaswini ? Thanks!

**Comment by davidfowl** [comment]
> That sounds very good, can we expect it in 1.0.1 or later?

It's not coming in a 1.0.1, but later in 1.1 of the DependencyInjection component.

> Are the changes related only to the .net core or also some non recommended practices in the code I provided @mnltejaswini ?

The change affects both .NET Core and .NET Framework but the memory reduction is mostly in .NET Framework.

**Comment by VaclavElias** [comment]
Hello again,

Regarding this subject, how can I measure or find out (what tools to use) why one website after launch on the production server has got around 170MBs and later it goes to 340MBs. It is ASP.NET Core 1.0.0 running on net461. 

Thanks :)

**Comment by VaclavElias** [comment]
I am moving my 20 ASP.NET Core websites from 1.0.1 to 1.1.

At the moment it seems that the Memory Consumption is much better, or the best so far. I will update you with my findings, especially once I moved the initial project mentioned in the beginning.

**Comment by VaclavElias** [comment]
It seems that upgrade to 1.1, and change from net461 to netcoreapp1.1 brought a welcome change

The result:
RC1 - dnx.exe - 77MB
RC2 - JyotiYoga.exe - 106MB
1.1.0 - dotnet.xe - 68MB

![image](https://cloud.githubusercontent.com/assets/4528464/20836213/3c828b74-b896-11e6-9b07-77d316aa0bc6.png)

I am closing this issue.

**Comment by ArashMotamedi** [comment]
@VaclavElias Just a quick follow-up on your latest observations on your environment, how are things going? I too was surprised to see that a stock project template (Asp.net Core 1.1 on .Net 4.6.1, Web App with Individual User Accounts) spikes to 200 ~ 300 MB of memory on startup and takes a good 15 seconds to serve up the first request. Since you were migrating your apps, are you satisfied with how things are going? Have you had to adjust/beef up your Azure hosting environment in any way?

**Comment by VaclavElias** [comment]
Hi @ArashMotamedi, I am half way through migration of all my websites to netcoreapp1.1. At the moment I would be only using ASP.NET Core 1.1 with netcoreapp1.1 and not with net461 as this seems to reduce the amount of memory. I don't mind a slow start up, I think you can improve this from version 1.1 by compiling your Views (you need to add extra bits to project.json..).

I am satisfied at the moment as some websites dropped from 200 ~ 300 MB to 80 ~ 100 MB and I hadn't have to adjust my Azure VMs.

Still, I will be moving away from Azure VM in couple of months as Azure VM doesn't allow you to increase only memory while the other providers allow this by increment 500MB.

https://feedback.azure.com/forums/216843-virtual-machines/suggestions/6012262-granular-cpu-and-memory-proivisioning

**Comment by VaclavElias** [comment]
This seems going to continue, I have moved to Visual Studio 2017 Community and moved a few projects to new msbuild. All using `<TargetFramework>netcoreapp1.1</TargetFramework>`

A few changes I can see on my server:

1) I cannot generate anymore **.exe**, the website becomes as **dll** and so the application in TaskManager says dotnet.exe and I cannot recognise which website is which.

2) The memory consumption almost doubled - what you see as dotnet.exe used to be in between 80-120MB. JyotiYoga wasn't migrated yet to msbuild.

![image](https://cloud.githubusercontent.com/assets/4528464/23825491/9a29b5c4-0682-11e7-8f1b-f147b5386a59.png)

 If I changed all to net461 I can generate exe but I haven't tested memory consumption yet.

Anyone else is observing the same?

**Comment by davidfowl** [comment]
> I cannot generate anymore .exe, the website becomes as dll and so the application in TaskManager says dotnet.exe and I cannot recognise which website is which.

If you were running on .NET Core before instead of .NET Framework, the only way to get an exe was to go standalone. What did your `project.json` look like before and did you auto migrate your project in VS2017, or did you do it yourself manually. Showing the before and after would help identify the differences.

> The memory consumption almost doubled - what you see as dotnet.exe used to be in between 80-120MB. JyotiYoga wasn't migrated yet to msbuild.

Migrating to msbuild won't change your runtime behavior unless the migration steps changed the runtime settings along the way. If you can, please re-run the migration step and save before and after so we can take a look.

You might want to take a look at turning off server GC  (which is on by default for web projects) if you're concerned about site density on a server. The default settings aren't tuned for that.

**Comment by VaclavElias** [comment]
Thanks @davidfowl for a quick reply.

**Before - project.json** - This was generating .exe with a small memory footprint, I guess it was standalone.

![image](https://cloud.githubusercontent.com/assets/4528464/23831767/8e5c277a-071f-11e7-8ff4-fea92381fc5b.png)

**After auto migrate** - changed to dll with a bigger memory footprint, and I had to install on the server Windows Server Hosting runtime.

![image](https://cloud.githubusercontent.com/assets/4528464/23831810/4a924e42-0720-11e7-977d-7cabdc1b74bf.png).

I am going to play with server GC as well.

**Comment by davidfowl** [comment]
> After auto migrate - changed to dll with a bigger memory footprint, and I had to install on the server Windows Server Hosting runtime.

Looks like the runtime identifiers were preserved. When you publish, what outputs were you looking at? It also looks like you didn't have server GC on before, it's not on by default in the web SDK. You can turn it off by setting the `<ServerGarbageCollection>` property to false in your csproj.

You should also look at your previous deployment's `{app}.runtimeconfig.json` to see if server GC was indeed off.

**Comment by VaclavElias** [comment]
The previous deployment had in {app}.runtimeconfig.json just this:
```
{
  "runtimeOptions": {}
}
```
I will try to use `<ServerGarbageCollection>` but for now I changed my target framework to net461 and was able to generate .exe. Also, by this change the memory consumption lowered by almost **100MB** for both websites as you can see on the image now and before so the consumption is now as previously.

![image](https://cloud.githubusercontent.com/assets/4528464/23835258/0de24fc4-075c-11e7-9770-f08e9f1d03c3.png)

and this is with this settings in {app}.runtimeconfig.json

```
{
  "runtimeOptions": {
    "configProperties": {
      "System.GC.Server": true
    }
  }
}
```
..This memory consumption is quite important as it might double the cost of VM or Azure App Service if you are forced to upgrade your hardware as there is no option just to add 1-2GB extra memory.

For now now my problem was resolved by switching to net461. Thanks @davidfowl for your suggestions I will update my findings here.

**Comment by davidfowl** [comment]
I would think for better density you'd want to try the following:
- Remove RuntimeIdentifiers, you don't want to deploy the Core CLR with every application. Install the shared framework on your server (assuming you don't already have it installed)
- Turn server GC off (by default it uses as much memory as it can). The app performance might suffer as a result (it's all trade offs) /cc @Maoni0

**Comment by VaclavElias** [comment]
Yes, I installed the shared framework previously. What do you mean by Remove RuntimeIdentifiers? This is my current csproj.
![image](https://cloud.githubusercontent.com/assets/4528464/23835548/24c618b0-0761-11e7-8313-cb4e3bc1e413.png)

I turned server GC off and the memory lowered to 54MB and 72MB that is even less memory, I will keep an eye on the performance.

**Comment by davidfowl** [comment]
Why are you specifying win10-x64 in your project file?

**Comment by VaclavElias** [comment]
Honestly, I don't know. I remember something wasn't working previously in VS 2015 so I put it there and it was working.. Anyway, I will remove it as it seems ok now. 

..I checked the server today and my websites are well with the same low memory consumption 54MB and 72MB.
