### ISSUE TITLE
Add ASPNETCORE_DETAILEDERRORS back to default configuration

### ISSUE THREAD

**Issue by davidfowl** [aspnet/Hosting#784]
We should be reading this value by default.

/cc @Tratcher

**Comment by Tratcher** [comment]
At what point do we just read all environment variables by default?

**Comment by davidfowl** [comment]
We *could* read the ones we have settings for. Everything else is kinda pointless.

**Comment by Tratcher** [comment]
Seed config with `.AddEnvironmentVariables(prefix: "ASPNETCORE_")` rather than adding them all piecemeal.

**Comment by davidfowl** [comment]
Yep! Sounds good to me. That was the original bug I filed.
