### ISSUE TITLE
Output to console that the application is shutting down gracefully

### ISSUE THREAD

**Issue by mrahhal** [aspnet/Hosting#794]
Until recently whenever I wanted to stop my app I felt that `ctrl+c` felt really slow without a reason, I didn't know that it was canceling the shutdown to wait for the main thread to exit gracefully.

So perhaps output a message after [this line of code](https://github.com/aspnet/Hosting/blob/dev/src/Microsoft.AspNetCore.Hosting/WebHostExtensions.cs#L23) to say that "Application is shutting down." so that it doesn't feel like nothing is going on?

**Comment by davidfowl** [comment]
How long did it take?

**Comment by mrahhal** [comment]
Takes a while sometimes, most of the times not so much. The problem is that people won't know what's going on and will just force it to exit. This might or might not be problematic, I use `IApplicationLifetime` to clean stuff up for example so this got me to think.

**Comment by davidfowl** [comment]
> This might or might not be problematic, I use IApplicationLifetime to clean stuff up for example so this got me to think.

That makes sense. It really won't help in the general case (since this only helps when looking at the console directly) but I don't see a problem doing this.

**Comment by mrahhal** [comment]
Yeah, that's my reasoning also. I'll do a PR.

**Comment by davidfowl** [comment]
We'll likely not take this for 1.0.0 since we're pretty much locking down. Also consider this bug that we do plan to fix https://github.com/aspnet/Hosting/issues/770 (which is about sprinkling Console messages that need to be turned off sometimes).

**Comment by mrahhal** [comment]
Oh makes sense, then feel free to close this if you want.

**Comment by mrahhal** [comment]
@davidfowl I did a PR anyway. Feel free to do whatever is appropriate.

**Comment by davidfowl** [comment]
Thanks!

**Comment by muratg** [comment]
@Tratcher Could you take a look? Seems simple enough to take in 1.0.0 for me.

**Comment by Tratcher** [comment]
It looks fine, but it can wait, it's only a cosmetic issue.
