### ISSUE TITLE
Option to customize ASPNETCORE_ENVIRONMENT to something else.

### ISSUE THREAD

**Issue by govin** [aspnet/Hosting#797]
Is there an option to customize ASPNETCORE_ENVIRONMENT to something else? We already have an environment variable on our servers that denotes a particular environment and hence would like to leverage that instead of setting another variable such as ASPNETCORE_ENVIRONMENT

**Comment by tmds** [comment]
Related:
I think this variable is even picked up even without explicitly stating in code you want to include environment variables. This doesn't seem to be consistent with other configuration.

I don't know how to set the environment in case it is not set when the server starts.

**Comment by Matthew-Bonner** [comment]
Have you seen the **EnvironmentName** property in the **IHostingEnvironment** interface (**Hosting/src/Microsoft.AspNetCore.Hosting.Abstractions/IHostingEnvironment.cs**)?

**Comment by davidfowl** [comment]
@govin You can call the API `UseEnvironment` on `WebHostBuilder` and set it to whatever you want.

**Comment by Tratcher** [comment]
FYI: Reading APSNETCORE_ environment variables by default is intentional: https://github.com/aspnet/Hosting/pull/790

**Comment by muratg** [comment]
We are closing this issue because no further action is planned for this issue. If you still have any issues or questions, please log a new issue with any additional details that you have.
