### ISSUE TITLE
log reports DataProtection-Keys using non-existent directory - causes VS to hang

### ISSUE THREAD

**Issue by esargent** [aspnet/Hosting#798]
I ran into this after I ran into the issue https://github.com/aspnet/Hosting/issues/791
The stack exchange article mentions deleting old DataProtection-Keys directories which is what I did - and it got me past the issue in 791.

But then I ran into an issue where Visual Studio hung on the "Debug is Starting" window. So I left VS and went directly to powershell, which let me see this line:

**User profile is available. Using 'C:\Users\esargent\AppData\Local\ASP.NET\DataProtection-Keys' as key repository and Windows DPAPI to encrypt keys at rest.**

However the directory didn't exist, so I recreated it and that fixed the problem.

I admit this is self-inflicted, but I am reporting it as an issue because the log output claims it found and is using that directory, even though the directory doesn't exist. And, apparently, that causes Visual Studio to hang.

![nodataprotection directory](https://cloud.githubusercontent.com/assets/14894721/15979293/0b6d4d38-2f18-11e6-8185-241fb31da146.png)
 Screenshot shows Windows Explorer and powershell output side-by-side.

**Comment by Tratcher** [comment]
This issue was moved to aspnet/DataProtection#161
