### ISSUE TITLE
[Question] How to run application during development in IIS?

### ISSUE THREAD

**Issue by epignosisx** [aspnet/Hosting#800]
I'm trying to run an ASP.NET Core app using IIS during development instead of IIS Express, but so far I've had no luck. I have found online how to set up IIS but that requires a publishing step which is far from ideal during active development.

**Comment by Tratcher** [comment]
IIS is not currently supported for development. Some folks have hacked it together, but I can't recommend it for most users.

**Comment by epignosisx** [comment]
Thanks for the reply @Tratcher. Is this planned for VS Tooling RTM? To give you some context: Our website is composed of multiple apps. We have a main IIS Site and multiple Web Apps under it. I'm working on a new web app written in ASP.NET Core and I need to have this app hosted in IIS to have the same hostname. I would think this is a common enough scenario to have first class support.

As for those folks that have made it work, do they have something I can look at? This is what I have come up with, but I'm looking for something simpler:
1- Do an initial publish
2- Point IIS to that location
3- Run "npm install cpx"
4- Create a watch.js file with the following content:

```js
var cpx = require("cpx");

cpx.watch("bin/Debug/netcoreapp1.0/*.*", "bin/Debug/PublishOutput");
cpx.watch("Views/*.*", "bin/Debug/PublishOutput/Views");
cpx.watch("appsettings*.json", "bin/Debug/PublishOutput");
//any other folders that need to be watched
```

5- Keep it running it during development: 
```batch
node watch.js
```

**Comment by Tratcher** [comment]
This is covered over here: https://github.com/aspnet/Tooling/issues/410#issuecomment-198172052

**Comment by GuardRex** [comment]
@tuespetre Given that tooling might not get to it for a while, is this still something that you'll be working on for RTM? https://github.com/tuespetre/dnx-watch-iis
