### ISSUE TITLE
Allow us to set credentials against the HttpClient created by TestServer.CreateClient()

### ISSUE THREAD

**Issue by robalexclark** [aspnet/Hosting#803]
In order to do integration testing against a solution with Windows Authentication enabled I need to be able to specify that the CredentialCache.DefaultNetworkCredentials are used when an HttpClient is created.  Normally I can create an HttpClient to work with Windows Authentication as follows:

```
HttpClientHandler handler = new HttpClientHandler();
handler.Credentials = CredentialCache.DefaultNetworkCredentials;
HttpClient client = new HttpClient();
```

There is no option available to set the credentials on the HttpClient created by TestServer (and no way to set them after the HttpClient is instantiated).

Please consider allowing credentials to be passed to TestServer through some mechanism so that systems with Windows Authentication can be integration tested.

**Comment by Tratcher** [comment]
This doesn't make much sense as there's nothing on the server side to process the credentials. TestServer is not designed for deep integration testing, but for limited middleware testing.  We have a different infrastructure for integration tests. See how we test Windows Auth scenarios over here: https://github.com/aspnet/ServerTests/blob/dev/test/ServerComparison.FunctionalTests/NtlmAuthenticationTest.cs

**Comment by muratg** [comment]
We are closing this issue because no further action is planned for this issue. If you still have any issues or questions, please log a new issue with any additional details that you have.
