### ISSUE TITLE
Routing bug - Default actions are mapped to another controller

### ISSUE THREAD

**Issue by xatabhk** [aspnet/Hosting#804]
Step to reproduce:
Add the following action to any MVC controller (e.g. TodoItemsController) as follows:
```
		[HttpGet("{id}")]
		public IActionResult Get(string id)
		{
			return new JsonResult("xyz");
		}//public IActionResult Get(string id)

```
Here is the generated mapping:
```
	    app.UseMvc(routes =>
            {
                routes.MapRoute(
                    name: "default",
                    template: "{controller=Home}/{action=Index}/{id?}");
            });

```
Actual result:
The default action of any controller gets mapped to “/TodoItems/Get”, and client receives "xyz".
For an examples:
	"/Home"	 =>    "/TodoItems/Get"
![default_map_bug_wrongcontroller](https://cloud.githubusercontent.com/assets/6814395/16360304/88e4c33c-3b8d-11e6-9db8-9d4d6184ef4c.png)

The only way to invoked “/Home” is using “/Home/Index”.

**Comment by dougbu** [comment]
If client receives a `404`, what leads you to conclude `/` is mapped to `/TodoItems/Get`? Suggest you provide a repro project and more information about the debugging you've done so far.

**Comment by xatabhk** [comment]
From the log output. When error code is not 404, the client receives content from wrong controller (Get).
Just add the following action to any MVC controller to reproduce the bug:
```
		[HttpGet("{id}")]
		public IActionResult Get(string id)
		{
			return new JsonResult("xyz");
		}//public IActionResult Get(string id)
```
![default_map_bug_wrongcontroller](https://cloud.githubusercontent.com/assets/6814395/16360302/6a2a92d2-3b8d-11e6-8dbf-9c60f69b4d11.png)

Remove the above action, all back to normal.

**Comment by dougbu** [comment]
Sorry, I missed the template in `[HttpGet("{id}")]`. That's an attribute route which will match every HTTP GET of the form `http://localhost:5001/xyz`. Suggest using attribute routes in your `HomeController` as well and adjusting their `Order` as you wish. Or change that template to something specific e.g. `"/api/{id}"`.

**Comment by xatabhk** [comment]
@dougbu Yes, the cause is  [HttpGet("{id}")]. But the issue is that request gets routed to wrong controller (TodoItemsController). No attribute routes in HomeController. Even if HomeController or another controller uses attribute routes, default action should not be mapped to another controller (TodoItemsController).

**Comment by dougbu** [comment]
It seems you would like the template `"{id}"` to be relative to `/TodoItems` instead of `/`. If that's correct, add `[Route("/TodoItems")]` on the `TodoItemsController` class.

Put another way, your conventional and attribute route templates currently overlap. You need to make some changes to separate them.

**Comment by xatabhk** [comment]
@dougbu You are right. Close it.
