### ISSUE TITLE
Can't publish site with RC2

### ISSUE THREAD

**Issue by csmith93** [aspnet/Hosting#805]
I had the site working previously, but started getting:

    Unhandled Exception: System.TypeLoadException: Method 'get_Services' in type 'Microsoft.AspNetCore.Hosting.Internal.WebHost' from assembly 'Microsoft.AspNetCore.Hosting, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' does not have an implementation.
        at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
        at TimeCardReminder.Program.Main(String[] args)

I'm not sure how to check what's going wrong, but the event viewer on the server shows:

`Failed to start process with commandline 'dotnet .\Website.dll', Error Code = '0x80004005'.`

and:

    Faulting application name: dotnet.exe, version: 0.0.0.0, time stamp: 0x573411d9
    Faulting module name: KERNELBASE.dll, version: 6.1.7601.18229, time stamp: 0x51fb1677
    Exception code: 0xe0434352
    Fault offset: 0x000000000000940d
    Faulting process id: 0x2c44
    Faulting application start time: 0x01d1d217548387e4
    Faulting application path: C:\Program Files\dotnet\dotnet.exe
    Faulting module path: C:\Windows\system32\KERNELBASE.dll
    Report Id: 927ea046-3e0a-11e6-b5ac-0050569d00fd

Any ideas?

**Comment by csmith93** [comment]
[Nevermind](https://docs.asp.net/en/1.0.0-rc2/publishing/iis.html#missing-net-framework-version).

**Comment by muratg** [comment]
Your project.json? 

Also, I'd recommend moving to RTM bits, they were released just a couple days ago.

**Comment by csmith93** [comment]
@muratg

Plan to move to RTM next, but just pushing out some recent changes to my project

project.json:

  {
    "dependencies": {
      "Domain": "1.0.0-*",
      "Common": "1.0.0-*",
      "MailKit": "1.3.0-rc1-1",
      "Microsoft.AspNetCore.Diagnostics": "1.0.0-rc2-final",
      "Microsoft.AspNetCore.Mvc": "1.0.0-rc2-final",
      "Microsoft.AspNetCore.Razor.Tools": {
        "version": "1.0.0-preview1-final",
        "type": "build"
      },
      "Microsoft.AspNetCore.Server.IISIntegration": "1.0.0-rc2-final",
      "Microsoft.AspNetCore.Server.Kestrel": "1.0.0-rc2-final",
      "Microsoft.AspNetCore.StaticFiles": "1.0.0-rc2-final",
      "Microsoft.Extensions.Configuration.EnvironmentVariables": "1.0.0-rc2-final",
      "Microsoft.Extensions.Configuration.Json": "1.0.0-rc2-final",
      "Microsoft.Extensions.Logging": "1.0.0-rc2-final",
      "Microsoft.Extensions.Logging.Console": "1.0.0-rc2-final",
      "Microsoft.Extensions.Logging.Debug": "1.0.0-rc2-final",
      "Microsoft.Extensions.Options.ConfigurationExtensions": "1.0.0-rc2-final",
      "Microsoft.VisualStudio.Web.BrowserLink.Loader": "14.0.0-rc2-final",
      "Microsoft.EntityFrameworkCore.Tools": "1.0.0-preview1-final",
      "Microsoft.EntityFrameworkCore.SqlServer": "1.0.0-rc2-final",
      "Microsoft.EntityFrameworkCore.SqlServer.Design": "1.0.0-rc2-final",
      "Microsoft.ApplicationInsights.AspNetCore": "1.0.0-rc2-final"
    },

    "tools": {
      "Microsoft.EntityFrameworkCore.Tools": {
        "version": "1.0.0-preview1-final",
        "imports": [ "dnxcore50", "portable-net45+win8" ]
      },
      "Microsoft.AspNetCore.Razor.Tools": {
        "version": "1.0.0-preview1-final",
        "imports": "dnxcore50"
      },
      "Microsoft.AspNetCore.Server.IISIntegration.Tools": {
        "version": "1.0.0-preview1-final",
        "imports": "dnxcore50"
      }
    },
    "frameworks": {
      "netcoreapp1.0": {
        "dependencies": {
          "Microsoft.NETCore.App": {
            "version": "1.0.0-rc2-3002702",
            "type": "platform"
          }
        },
        "imports": [ "dnxcore50", "portable-net45+win8" ]
      }
    },
    "buildOptions": {
      "emitEntryPoint": true,
      "preserveCompilationContext": true
    },
    "runtimeOptions": {
      "gcServer": true
    },
    "publishOptions": {
      "include": [
        "wwwroot",
        "Views",
        "appsettings.json",
        "web.config"
      ]
    },
    "scripts": {
      "prepublish": [ "npm install", "bower install", "gulp clean", "gulp min" ],
      "postpublish": [ "dotnet publish-iis --publish-folder %publish:OutputPath% --framework %publish:FullTargetFramework%" ]
    }
  }

**Comment by muratg** [comment]
How about project.json's for `Common` and `Domain` projects?  I suspect something is bringing in incompatible packages transitively.

**Comment by csmith93** [comment]
Common and Domain are identical and look like:

    {
      "version": "1.0.0-*",
      "dependencies": {
        "NETStandard.Library": "1.5.0-rc2-24027"
      },
      "frameworks": {
        "netstandard1.5": {
          "imports": "dnxcore50"
        }
      }
    }

**Comment by cesarbs** [comment]
@csmith93 What CLI version are you using?

**Comment by csmith93** [comment]
1.0.0-preview1-002702

**Comment by cesarbs** [comment]
Have you tried clearing your NuGet caches and rebuilding?

**Comment by csmith93** [comment]
No luck. Going to try and just switch to RTM.

**Comment by cesarbs** [comment]
@csmith93 Any luck with RTM?

**Comment by csmith93** [comment]
Sorry... yess. Switching to RTM fixed the issue.
