### ISSUE TITLE
Suppress logging for specific requests (e.g. health checks)

### ISSUE THREAD

**Issue by sunsided** [aspnet/Hosting#807]
We're using ASP.NET Core with Kestrel dockerized in Google Container Engine. The load balancer performs regular health checks (to a customizable route) which, depending on the configuration, can make the logs somewhat to extremely unreadable. That is, we end up with up to hundreds of log lines per second using the standard console logger (possible machines x replication factor x each line a log entry) - without any useful information.

Currently, each requests generates at least some lines similar to

```
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://localhost:12345/foo/bar/
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 1962.8502ms 200 application/json; charset=utf-8
```

While I was able to suppress all other messages by writing a custom middleware, I would like to also suppress these log lines if and only if the request comes from a specific IP subnet and/or has known HTTP headers set.

For requests different from health checks, I do want to see log output though (e.g. from `Microsoft.AspNetCore.Mvc.Internal`, etc.).

**Comment by muratg** [comment]
This issue was moved to aspnet/Logging#459
