### ISSUE TITLE
Loading all assemblies on startup, not on first request? (Warmup)

### ISSUE THREAD

**Issue by leak** [aspnet/Hosting#809]
Is there a clean way to handle all the assembly loading that is usually done at the first request right at the start of the application?

I know there is an extension for IIS (http://blogs.iis.net/thomad/now-available-the-iis-7-5-application-warm-up-module) which does exactly that.

How would one do that with Kestrel? Is there something better than http-getting the own website?

**Comment by GuardRex** [comment]
Just for reference for the IIS case, that will be addressed: https://github.com/aspnet/IISIntegration/issues/161 This is the first issue asking for a warmup for Kestrel IIRC.

**Comment by davidfowl** [comment]
Sending a request doesn't load all assemblies (unless you wrote code to do that in your application).

**Comment by leak** [comment]
Well it does load the assemblies that are required for serving the initial request, thus "warming up" the application.
Also, yes, I am looking for this in a Kestrel context, not IIS.

**Comment by davidfowl** [comment]
You need another thing to ping your app. Kestrel is part of your process.

**Comment by schmitch** [comment]
well actually isn't this something that a production app should always do? load all assemblies? I mean it's a little bit akward to "ping" an application. In Java the first request is also a little bit slower, but not that slow, actually.

**Comment by davidfowl** [comment]
> well actually isn't this something that a production app should always do?

No, why would you force load all of your assemblies? That could destroy your startup time. Assemblies always load lazily.

**Comment by schmitch** [comment]
eh I don't care for startup time I care for fast web requests. I mean startup time doesn't matter, but if your user loads some sites slower it does matter.

**Comment by davidfowl** [comment]
Then you can load your assemblies by calling into them or by force loading everything.

**Comment by schmitch** [comment]
I'm not sure what you mean by force loading? do you mean something like:

> http://stackoverflow.com/questions/37895278/how-to-load-assemblies-located-in-a-folder-in-net-core-console-app

Sorry but that looks more like a hack to me.
Also calling into them is not suitable. I mean I have a pretty "dumb" application which does not call into any database (yet). And the first request takes like 2s-3s, thats extremly slow. while instant startup looks good on paper it's akward if there is a 2s penalty for the first request.
I know that there might be cases where this is good, but for many users I doubt it isn't. at least provide a way to warmup the whole vm while trading startup time, maybe via `dotnet --warmup my_application.dll`, I like a lot yet about .net core  (and I'm a java/scala guy as you can see in my github account), but this is not really to my liking that I **need** to at least make a single request via `curl http://localhost:5000` to my app before I can use it.

**Comment by davidfowl** [comment]
I don't know what to tell you, there's no code that will be baked into the framework that will force load all assemblies by default. If you desperately want this, you can write some logic to force load all assemblies in the application (which won't really do much BTW) and "warm" up your application by calling relevant parts of the code.

**Comment by muratg** [comment]
We are closing this issue because no further action is planned for this issue. If you still have any issues or questions, please log a new issue with any additional details that you have.

**Comment by nzain** [comment]
The warmup / first request problem becomes critical, when running on small devices. I'm developing a REST service for an embedded arm device (Cortex-A7) and the first request (that simply returns an integer) takes more than 7 seconds (!). Subsequent requests finish in ~1 millisecond (!).

I will fire up a thread to GET some of my own resource, since _seven seconds_ is far above typical timeout / user acceptance.

**Comment by secretorange** [comment]
I also think this is a useful and common request. For example, we would prefer to bring in our servers behind a load balancer after they're "warm". 

If a server registers and is suddenly hit by 1000s of requests it can cause problems if it's not ready to go.

**Comment by Matthew-Bonner** [comment]
Are you aware of the IApplicationLifetime interface? You could just use the ApplicationStarted event to warm up the cache. Is that any good for you?

**Comment by secretorange** [comment]
In my example, the app has already started (i.e. services registered and configured etc). I use AWS, so the health ping will initially load the app. But, I find that the first request to an endpoint takes considerably longer and sometimes can cause problems under heavy load.

**Comment by nzain** [comment]
IApplicationLifetime.ApplicationStarted may eventually provide the correct point in time to do the warmup (thanks for the hint), but nothing more. We have to create a `HttpClient` and `GET http://localhost:xxxx/something` to actually trigger the warmup.

Is noone of the ASP/Kestrel team curious about "why first request takes 7000 times longer than subsequent requests"? If we better understand what is going on, we could eventually optimize. I understand that the pure service startup time is relevant for server machines spawning a lot of ASP webservices, but for sure the "service is available time" is relevant, too.

**Comment by leak** [comment]
Even if you ping a single API, you are still just loading the assemblies required for that particular API. If you are hitting one of your other APIs for the first time and they require other assemblies, you still get additionally delay for that request. Granted you are not paying the loading cost for the aspnet pipeline again, but still.

I wish there was way more control for developers on this subject.

**Comment by nzain** [comment]
Are we sure that "assembly loading" is the performance bottleneck? MEF service creation could be involved, too?

Fact is, that calling any endpoints (that requests any of my own services or none at all) will take long and any subsequent call to any other endpoint (requiring any services) is fast as hell. However, this doesn't shed any light on how many ASP dlls are loaded and how many services are created for the ASP pipeline.

**Comment by kgrosvenor** [comment]
I notice this same Issue. Couldn't we do something in start up to scan project and load assemblies, seems like a pretty wide spread issue. I am also experiencing this. Surley the build itself should do this anyway?
