### ISSUE TITLE
Buffering Request Body Stream

### ISSUE THREAD

**Issue by BadriL** [aspnet/Hosting#814]
First of all, I do not know where I should be asking his question. If this is not the right project, please let me know. I have a middleware like this that writes the request body out.
```
app.Use(next => async context =>
{
    var request = context.Request;
    var buffer = new MemoryStream();
    await request.Body.CopyToAsync(buffer);
    request.Body = buffer;
    string body = System.Text.Encoding.UTF8.GetString(buffer.ToArray());
    buffer.Position = 0;

    await next.Invoke(context);
});
```

This works correctly for the first request. For the subsequent request, `request.Body` continues to be a `MemoryStream` and the request body of the second message is not being copied into buffer, since `request.body` is not the network stream.

If I change the code like this, it works.
```
app.Use(next => async context =>
{
    var request = context.Request;
    var buffer = new MemoryStream();
    var originalStream = request.Body;
    await request.Body.CopyToAsync(buffer);
    request.Body = buffer;
    string body = System.Text.Encoding.UTF8.GetString(buffer.ToArray());
    buffer.Position = 0;

    await next.Invoke(context);

    request.Body = originalStream;
});
```

But why do I need to restore the request body stream so that it works correctly for the next request? It seems very weird, at least to me.

**Comment by Tratcher** [comment]
This is a bug in kestrel: https://github.com/aspnet/KestrelHttpServer/issues/940
