### ISSUE TITLE
Consider adding a RequestHandler property in TestServer to represent RequestDelegate

### ISSUE THREAD

**Issue by jijiechen** [aspnet/Hosting#816]
TestServer is great for most scenarios, but sometimes people really want to reference an HttpContext instance to confirm it is correctly processed.

Right now, we can only create a client object and invoke TestServer in a "integration" way. Could you add some property to TestServer class to add ability to invoke the RequestDelegate directly?
With such reference, we can check state of HttpContext, can assert exceptions which correctly handled, etc.
We can easily to implement another IServer to make things happen but if you make it a builtin feature, it would be very nice.

Refer to issue https://github.com/aspnet/HttpAbstractions/issues/669

**Comment by Tratcher** [comment]
Yes, sometimes HttpClient is too abstracted and I'd like to directly build and send an HttpContext and check the results. This would be nice for customizing server side structures like the IFeature interfaces.

**Comment by MCGPPeters** [comment]
Working on a port a the [OWINHttpMessageHandler](https://github.com/damianh/OwinHttpMessageHandler) Damian Hickey created. Maybe it can help : [AspNetCoreHttpMessageHandler](https://github.com/MCGPPeters/AspNetCoreHttpMessageHandler) ....

**Comment by Tratcher** [comment]
Bumping out of backlog for re-triage. We get lots of requests for higher fidelity control over the request. People want to set things like a Windows Auth user, the client certificate, remote IP, etc..
See:
https://github.com/aspnet/Hosting/issues/1135
https://github.com/aspnet/Hosting/issues/924#issuecomment-334813951

**Comment by jkotalik** [comment]
@Tratcher I think it is best to expose the feature collection for modification before we send the request. It may be hard to expose everything in the TestServer as a property.

**Comment by Tratcher** [comment]
@jkotalik this wouldn't be for modification, this would be for full construction. You wouldn't use HttpClient as an intermediary with this approach.

**Comment by jkotalik** [comment]
Gotcha. Just so we are on the same page, we would have a new code path that accepts an IFeatureCollection or HttpContext and allows you to effectively call "SendAsync" on the context. Then when you receive the response, we can expose the modified HttpContext and or the RequestDelegate.

**Comment by fletchsod-developer** [comment]
Any idea what version will this be available in NuGet?

**Comment by davidfowl** [comment]
When we ship the next version of asp.net Core. You can use the myget feed if you want to use bleeding edge stuff. We don’t ship individual packages.
