### ISSUE TITLE
Passing on IConfiguration to Startup (in order to read environment correctly) ?

### ISSUE THREAD

**Issue by ghost** [aspnet/Hosting#820]
I would like to be able to specify the correct runtime environment (test/production etc) from either a command line OR environment variable OR appsettings.json while still allowing for environment specific additional json files.

To do so I can do the following in program.cs which is a bit complex. However, once configuration is setup with UseConfiguration in Program.cs there is no way I can pass this configuration the Startup.cs class which only takes a IHostingEnvironment parameter and will not accept a IConfiguration parameter. Instead I have to replicate configuation in Startup but this time I do not have access to the command line "args" so I can't make it work. I could use a global variable to temporarily save the  configuration but that would interfere with other usages like testing.... What to do ? 

```
       // First setup a partial configuration so we can retrieve environment:
        IConfigurationRoot config = new ConfigurationBuilder()
            .AddCommandLine(args)
            .AddEnvironmentVariables()
            .SetBasePath(Directory.GetCurrentDirectory())
            .AddJsonFile("appsettings.json", optional: false)
            .Build();
        string env = config["ASPNETCORE_ENVIRONMENT"];

        // Next, setup a full configuration using the environment we just found out:
        config = new ConfigurationBuilder()
            .AddCommandLine(args)
            .AddEnvironmentVariables()
            .AddJsonFile("appsettings.json", optional: false)
            .AddJsonFile($"appsettings.{env}.json", optional: false)
            .Build();

        // Create and run hosting
        IWebHost host = new WebHostBuilder()
            .UseKestrel()
            .UseConfiguration(config) // How to access this config in Startup.cs ????
            .UseContentRoot(Directory.GetCurrentDirectory())
            .UseIISIntegration()
            .UseStartup<Startup>()
            .Build();

        host.Run();
```

**Comment by muratg** [comment]
@davidfowl Thoughts on this one?

**Comment by davidfowl** [comment]
There's several ways to do this but here's a question, are you trying to unify hosting configuration and application configuration in the same file? Don't think of the UseConfiguration call as something you can access, it's purely for the hosting environment (servers, etc). You should try to configure as much as you can via Startup.

As for flowing command line args, here's a pattern we use in our benchmarks repository:

A service is added to the service collection that flows the command line arguments:

https://github.com/aspnet/benchmarks/blob/dev/src/Benchmarks/Program.cs#L42-L46

That'll make it accessible in the `Startup` ctor.

**Comment by bluemmc** [comment]
Thank you very much for your help. I am trying to support very flexible configuration that works both when hosted in IIS and when running locally from command line etc. 
The sample you point to is very interesting and I think it might solve my issue. I would be great if this trick could be documented. I was not aware - and I think few are - that ConfigureServices on WebHostBuilder can be used to setup stuff to be injected into the Startup constructor. Very handy trick if I understand it correctly! Nice!!

**Comment by GuardRex** [comment]
I've enjoyed the pattern you mention since it became available: https://gist.github.com/GuardRex/f40f1b1414e175a6514f

It's only mentioned in the last Note at https://docs.asp.net/en/latest/fundamentals/hosting.html?highlight=configureservices#setting-up-a-host

I opened an issue at  to discuss expanding the coverage a bit on it: https://github.com/aspnet/Docs/issues/1756

**Comment by tmds** [comment]
+1
Most examples show reading the configuration the Startup constructor but this makes it hard to pass in a configuration via code.

**Comment by GuardRex** [comment]
@tmds They ultimately said "Most people should use a Startup class."

... and *not* the "NUTJOB" pattern :smile: ... that's only for nuts like me.

https://github.com/aspnet/Docs/issues/1756#issuecomment-238954404

**Comment by tmds** [comment]
@GuardRex There are valid use cases for this. Mine is: using the Startup class in tests. Dependency injection approach is working.

**Comment by GuardRex** [comment]
Seems reasonable, but I'm just a community :cat2: ... @Rick-Anderson, @danroth27, and @davidfowl are my "bosses" so-to-speak. I trust their judgement.

There is the little blurb in the Hosting doc as things stand. It's a bit difficult to tease out in the midst of everything else going on, but at least it's there:

> When setting up a host, you can provide Configure and ConfigureServices methods, instead of or in addition to specifying a Startup class

https://docs.asp.net/en/latest/fundamentals/hosting.html#setting-up-a-host

**Comment by muratg** [comment]
We are closing this issue because no further action is planned for this issue. If you still have any issues or questions, please log a new issue with any additional details that you have.
