### ISSUE TITLE
Consider renaming Microsoft.AspNetCore.Server.Testing

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Hosting#824]
We produced versions of this package with 1.0.0-rc2-* versions and went back in time to 0.1.0 \ 0.2.0. It would be nicer to use a different name instead here.

**Comment by Tratcher** [comment]
Suggestions? The current name is pretty accurate.

**Comment by pranavkm** [comment]
`Microsoft.AspNetCore.ServerTesting`?

**Comment by brockallen** [comment]
IntegrationTesting?

**Comment by muratg** [comment]
This is package is not on nuget.org, right? So is it a matter of myget cleanup?

I think move to dotnet.myget.org would hopefully fix this problem (and of course we'll tell folks to clear their caches)

cc @Eilon

**Comment by pranavkm** [comment]
We use the old package in RC2. So clearing it might be problematic.

**Comment by Eilon** [comment]
Yeah we kind of don't want to delete the old existing package. I'm fine with `ServerTesting`. We can always just rename it again later 😄

**Comment by Tratcher** [comment]
Boycotting this change until we finally get project renaming tools.
