### ISSUE TITLE
UseStartup is flawed for custom constructors

### ISSUE THREAD

**Issue by jchannon** [aspnet/Hosting#825]
When using `WebhostBuilder` and using the `UseStartup<Startup>` approach you cannot have a Startup class with 2 constructors

For example
```
        public Startup(IHostingEnvironment env)
            : this(env, null)
        {

        }

        public Startup(IHostingEnvironment env, MyBlah blah)
        {
        }
```

To use this pattern you can get your Startup class to implement `IStartup`

`IStartup` determines that the method is `public void Configure(IApplicationBuilder app)`, so now if I want to add `ILoggerFactory` to that method it won't compile as it doesn't adhere to the interface. So now I'm in a catch 22.

**Comment by davidfowl** [comment]
What is `MyBlah`?

**Comment by jchannon** [comment]
I think I can solve this by using:

```
                new WebHostBuilder()
                .ConfigureServices(services => {
                    services.AddSingleton(new MyBlah());
                })
                .UseStartup<Startup>()
```

I can then access MyBlah in Startup constructor and set my app up
