### ISSUE TITLE
Proposal: Support IServiceProviderFactory

### ISSUE THREAD

**Issue by davidfowl** [aspnet/Hosting#829]
Based on https://github.com/aspnet/DependencyInjection/issues/442

The `WebHostBuilder` API would take advantage of this by using it as a way to override the default `IServiceProvider` implementation without returning it directly from the application's `Startup` class. The wire up could look like this:

```C#
public static void Main(string[] args)
{
    var host = new WebHostBuilder()
        .UseKestrel()
        .UseAutofac() // Replace the built-in IServiceProviderFactory with an autofac impl
        .UseContentRoot(Directory.GetCurrentDirectory())
        .UseStartup<Startup>()
        .Build();

    host.Run();
}
```

One downside to this is that you don't get direct access to the container APIs in the `Startup` class (which is part of the benefit besides being able to swap out the default impl).

In the above example, `UseAutofac` would wire up the `IServiceProviderFactory`. We could also extend the `ConventionBasedStartup` to allow authoring a `ConfigureContainer` method that takes the concrete ContainerBuilder directly:

```C#
public class Startup
{
    public void ConfigureServices(IServiceCollection services)
    {
         services.AddMvc();
    }

    public void ConfigureContainer(ContainerBuilder builder)
    {
        builder.RegisterInstance(new TaskRepository())
           .As<ITaskRepository>();
    }

    public void Configure(IApplicationBuilder app)
    {
        app.UseMvc();
    }
}
```

**Comment by GuardRex** [comment]
> you don't get direct access to the container APIs in the Startup class

Will there be any consequences for those who despise the vile and dreaded `Startup` class? :smile:
```c#
public static void Main(string[] args)
{
    var host = new WebHostBuilder()
        .UseKestrel()
        .UseContentRoot(Directory.GetCurrentDirectory())
        .ConfigureServices(services =>
        {
            ...
        })
        .Configure((app) =>
        {
            ...
        })
        .Build();

    host.Run();
}
```

**Comment by davidfowl** [comment]
You can't replace the `IServiceProvider` today if you configure everything with the `WebHostBuilder` today. See https://github.com/aspnet/Hosting/issues/550

**Comment by GuardRex** [comment]
Fair enough ... just checking. Since I don't, it won't affect me. :smile:

**Comment by Tratcher** [comment]
How does it work if UseKestrel is already adding and accessing services?

**Comment by davidfowl** [comment]
@Tratcher what specifically are you asking about? Passing the `IServiceProvider` directly or the new `IServiceProviderFactory` proposal?

**Comment by Tratcher** [comment]
In the new IServiceProviderFactory.

**Comment by davidfowl** [comment]
Works fine. Just like it does today. UseKestrel wires up an `IConfigureOptions<KestrelOptions>` that captures the `IServicerProvider` provided by the application.
