### ISSUE TITLE
Fix startup exception page to handle flattened exceptions

### ISSUE THREAD

**Issue by kichalla** [aspnet/Hosting#831]
@Eilon looks like one more place we need to do the fixes :-(

Current behavior: https://jsfiddle.net/2s6g0xsx/ (notice that we do not display the code for other exceptions and also the `show exception details` link does not toggle as we have seen in developer exception page)

**Comment by Eilon** [comment]
Oops. Clearly we need more tests for these. Can you come up with a good way to do meaningful tests for these pages? But without launching a real browser... anything we can do here?
