### ISSUE TITLE
Does ASP.NET Core not support IIS Applications anymore

### ISSUE THREAD

**Issue by devtriad** [aspnet/Hosting#835]
I have production Web Applications in ASP.NET 5 RC1 hosting it in IIS using the HTTPPlatform Handler. It was simple enough.

However this new IIS in ASP.NET Core publishing is so complicated and log files don't make sense. One would expect if your project can run in Visual Studio that publishing would be easy but not so.

If I follow the instructions 
https://docs.asp.net/en/latest/publishing/iis.html
I get blank pages for my deployed app and the log files don't assist me in telling me why.

Is it possibly to publish ASP.NET Core apps which targetsnet452 to an IIS application  in an IIS Website like one could with ASP.NET 5 RC1  and the HttpPlatformHandler?

I could not find anything that helped while googling.
I have posted [more  detail  on stackoverflow  ](http://stackoverflow.com/questions/38955514/how-to-deploy-an-asp-net-core-targetting-net452-project-as-an-iis-application-of)

**Comment by Tratcher** [comment]
A) Can you share a repro app so we can review your setup. 
B) Use the F12 tool in your browser to see what the actual response was for your "blank page". It is likely a 500 or a 404.
C) What does your IIS configuration look like? Are you deploying to the root site or a child Application (e.g. /SubApplication)?

**Comment by devtriad** [comment]
A)Sure will try setup a basic one for you
B) Using http://localhost/myside Using the port it decides and displays in my logs http://localhost:15250/myside i get Connection Refused
c) I am deploying an app that targets net452 (non core app) to a child/sub application.

**Comment by devtriad** [comment]
Here is the repo that describes the behavior

https://github.com/devtriad/Test4

Create a application in your default website called Test4. Make sure the logging is enabled and see the behavior match how I described

**Comment by Tratcher** [comment]
Remove `app.Map("/Test4", (app1) => this.Configure1(app1, env, loggerFactory));`, that workaround is not required in RC2 or 1.0 RTM.

**Comment by devtriad** [comment]
thanks
