### ISSUE TITLE
IIS Debugguing

### ISSUE THREAD

**Issue by Serjster** [aspnet/Hosting#838]
I'm not sure if this is the best place to post this, but is there a timeline for debugging straight from IIS... not using IIS Express. We have multi-project solutions (Web, API, etc.) that all need to be running at the same time. The current work around is to attach each project or load multiple instances of VS with the same solution... neither is ideal. It would be very helpful if we could run all of our apps in IIS and just debug whichever we are working in at the moment... like the good old days... is this anywhere on the near horizon? If not, how can I help make it a higher priority?

**Comment by davidfowl** [comment]
You should move this to aspnet/Tooling.

**Comment by Serjster** [comment]
Done: https://github.com/aspnet/Tooling/issues/734

Thanks.
