### ISSUE TITLE
Passing configuration section into WebHostBuilder.UseConfiguration uses full keys

### ISSUE THREAD

**Issue by kierenj** [aspnet/Hosting#839]
I have a large JSON config file and want to have a config section within it containing ASP.NET keys (`urls`, `detailedErrors`, etc).

However, when I use `myConfiguration.GetSection("webApi")` to get the section and pass it to `.UseConfiguration()`, the settings are not picked up.

Looking at the source, I see that the extension method simply calls `.AsEnumerable()` on the `IConfiguration` then adds settings by `.Key` and `.Value`.  This seems a good approach... but for sections/subsections, the `.Key` includes the hierarchy.  For example:

``` json
{
  "webApi": {
    "urls": "http://*:1234/"
  }
}
```

(`.UseConfiguration()` doesn't configure the key as `urls`, but as `webApi.urls`)

This is unexpected to me: it means that passing a section returned from `.GetSection()` simply /filters/ the configuration keys by that section, rather than configuring /using/ that section, rendering my approach not possible.

I'm not sure if this is something others would expect to work, but to me, `.GetSection()` returns a section, and since the object can be passed to `.UseConfiguration()`, the impression given is that it should, I think.

Not sure if this is a bug/feature request for /Hosting, /Configuration, or somewhere else?  Thanks!

**Comment by Tratcher** [comment]
It looks like there's another overload of AsEnumerable that takes a parameter (makePathsRelative) that does this. https://github.com/aspnet/Configuration/blob/c202d3148130cacadb6133425e14ac134bf9cb68/src/Microsoft.Extensions.Configuration.Abstractions/ConfigurationExtensions.cs#L37

Either
A) AsEnumerable() should default to makePathsRelative or
B) Hosting should set makePathsRelative

**Comment by muratg** [comment]
We can' t change the existing API before 2.0.  The only realistic fix for 1.x would be a new API. We'd consider taking a PR.

**Comment by AndSDev** [comment]
May be
C) `UseConfigurationSection(...)` - [Gist](https://gist.github.com/AndSDev/03b2ed680ded355724bef4f7e02df491).

**Comment by joelharkes** [comment]
I think webhost builder should be able to use an IAppsettings for its settings instead just like any other IOptions is defined. It would create more unity, and would be able to be defined in the StartUp class instead (where we normally place our AppSettings initialization code). 

Now i can overwrite my appsettings with environment variables, in my application,
but i can't use appsettings to set the ServerUrl, but i can only overwrite it with environment variables or commandline args.
It would be nice to unify this and create more synergy.

**Comment by mcm-ham** [comment]
@Tratcher I think the only change needed is this:

https://github.com/aspnet/Hosting/blob/873a0e7/src/Microsoft.AspNetCore.Hosting.Abstractions/HostingAbstractionsWebHostBuilderExtensions.cs#L24

```cs
    foreach (var setting in configuration.AsEnumerable())
```
To
```cs
    foreach (var setting in configuration.GetChildren())
```

This is not changing the API so should be fine?

**Comment by WernerMairl** [comment]
2.0 is on the finish line... what about this issue ?

if not solved - it should be documented on a more visible place, because probably more people uses sections inside the json file and is wondering why this does not works!

(my usecase: one json file with sections for "appsettings", "hosting" etc....)

If it results in a breaking change then please offer a new api where i can at leat opt in/out!

**Comment by Tratcher** [comment]
Indeed, please open a doc bug here: https://github.com/aspnet/docs

**Comment by Tratcher** [comment]
We should still fix this one as it carries over to the generic web host. We were primarily waiting for 3.0 to do so.

**Comment by davidfowl** [comment]
Isn't this a breaking change? What does it break?

**Comment by Tratcher** [comment]
Yes it's breaking, that's why we waited until 3.0.

When working with a subsection all the keys are truncated so it's expected that padding those to another config would behave the same. We've had several bugs about this. Look at the 1/3 page [Note](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/web-host?view=aspnetcore-2.1#override-configuration) in the docs.

**Comment by Tratcher** [comment]
Note this is likely the same change as https://github.com/aspnet/Hosting/issues/1430
