### ISSUE TITLE
Unity Backed Service Provider breaks MVC 6 Application

### ISSUE THREAD

**Issue by Hem** [aspnet/Hosting#842]
I have written two web applications with Unity Service Provider

1. Using .net core web application using Unity.CoreClr + Unity.Mvc6 (beta 3)
2. Using .net core web application using Unity (4.0.1)

Both instances I'm unable to get the application running. 

The error seems to be very similar to DI: Unity-Backed Service Provider Breaks Controller Routing #317

You can find the source code on
 https://github.com/Hem/DotNetCoreWithUnity

Thanks
-Hem

**Comment by muratg** [comment]
This issue was moved to aspnet/DependencyInjection#449
