### ISSUE TITLE
[Discussion] Running app under web server sub directory reverse proxy

### ISSUE THREAD

**Issue by eByte23** [aspnet/Hosting#849]
Currently when trying to run a .netcoreapp under a webserver subdirectory with reverse proxy. It doesn't work by default.
For example. http://example.com/app1
the app gets passed url of /app1*

The fix for this is to use app.PathBase however this must be set in code or you have to write your own infrastructure around the setting.

However when running an app in IIS on the same domain http://example.com/app1
it passes environment var ASPNETCORE_APPL_PATH=/app1

When using IISIntegration, could we not have one for other reverse proxy hosts that does this and if its not define well then just use / as PathBase like normal.

Note: this is not just nginx, I would think it is any web server that can use reverse proxy 
See for history.
https://github.com/aspnet/HttpAbstractions/issues/702
https://github.com/aspnet/HttpAbstractions/pull/703

Relevant and possible duplicate
https://github.com/aspnet/Hosting/issues/815

**Comment by muratg** [comment]
Let's keep the discussion here: #815. Closing this one as dup.
