### ISSUE TITLE
Do we need to expose invoking ConfigureServices?

### ISSUE THREAD

**Issue by HaoK** [aspnet/Hosting#85]
Currently ConfigureServices is invoked as part of StartupManager's LoadStartup.

Would splitting it out and exposing just the ConfigureServices method be useful for Migrations/DesignTime?

**Comment by glennc** [comment]
@bricelam @divega Is this still an issue?

**Comment by bricelam** [comment]
Yes, we need an easy way for tools to call Startup.ConfigureServices the same way Hosting would. [Our workaround](https://github.com/aspnet/EntityFramework/blob/dev/src/EntityFramework.Commands/ContextTool.cs#L32-L54) is pretty ugly and incomplete.

**Comment by HaoK** [comment]
I have some cycles to take a look at this if this is something we want to do

**Comment by glennc** [comment]
We just talked about the same thing in the hosting API review. Talk to @lodejard. I can fill you in one the basic plan if you can't pin him down.

**Comment by HaoK** [comment]
Current thinking is to try to remove UseServices with ConfigureServices as the only supported way to well...configure services

**Comment by HaoK** [comment]
needs moar sugah still

**Comment by HaoK** [comment]
Currently EF's tool is doing this:

+                var context = new HostingContext
+                {
+                    ServerFactory = new ServerFactory(),
+                };
+                var instance = new HostingEngine().Start(context);
+                return context.ApplicationServices.GetService(type) as DbContext;

**Comment by HaoK** [comment]
Will be addresed by https://github.com/aspnet/Hosting/issues/204
