### ISSUE TITLE
How to get the server name?

### ISSUE THREAD

**Issue by abcplex** [aspnet/Hosting#851]
I need to know at run-time whether my app running directly with Kestral(without proxy server) or app running in front of IIS/Apache? If server is running beside proxy server, how do I know its name and version? If directly running from Kestral, how do I get Kestral version?

**Comment by davidfowl** [comment]
Why would you need to know that? What if you have another reverse proxy in front of IIS or Apache? Hopefully you don't have any code that depends on that and it's purely informational. You can get a type from kestrel and get the asssmbly version. 

PS: You are always at least behind kestrel.

**Comment by abcplex** [comment]
In short you are saying its not possible now(Is there any X-Forward-Server?). My use case is that, use middle-ware if running directly from Kestral otherwise use native web-server functionality. Second use case is informational for logging to check what my CMS customers are using.

**Comment by Tratcher** [comment]
Native web-server functionality? Such as?

**Comment by davidfowl** [comment]
No generic way to know that information.

**Comment by abcplex** [comment]
@Tratcher what do you mean? I am just asking whether there is something like X-Forwarded-WebServerName like we have X-Forwarded-For and X-Forwarded-Proto? I know Kestral web server always execute my code as a server but whether directly or indirectly? Thank you both

**Comment by davidfowl** [comment]
> @Tratcher what do you mean?

He's asking what do you do in the middleware when running directly or indirectly.

> I am just asking whether there is something like X-Forwarded-WebServerName like we have X-Forwarded-For and X-Forwarded-Proto?

There's nothing standard no, you can make up a header though.

> I know Kestral web server always execute my code as a server but whether directly or indirectly? 

Hard to know without setting that up explicitly or looking for other web server specific details (detect apache, iis, haproxy, ARR, etc)

**Comment by abcplex** [comment]
>> He's asking what do you do in the middleware when running directly or indirectly.

Like if Not Apache/IIS THEN UseStatismiddlware/UseCompression/UseCache and so on. Hopefully you got it what I mean :)

**Comment by Tratcher** [comment]
Ah, you want to conditionally add middleware to the pipeline. Note you don't have any request headers to read at startup, you only have configuration and environment variables. We detect we're running behind IIS (AspNetCoreModule) via environment variables it sets for us and add the middleware we need there (UseForwardedHeaders, etc.).

**Comment by abcplex** [comment]
@Tratcher thanks you mean https://github.com/aspnet/IISIntegration/blob/2f397d6f631247ed33050cb03c0f66d3963777ef/src/Microsoft.AspNetCore.Server.IISIntegration/WebHostBuilderIISExtensions.cs#L33-L37

**Comment by abcplex** [comment]
@Tratcher @davidfowl in classic ASP.NET we have SERVER_SOFTWARE https://github.com/aspnet/BasicMiddleware/blob/a5ff9d800374c60a92e8b1722166f41a6f7607bd/src/Microsoft.AspNetCore.Rewrite/Internal/ApacheModRewrite/ServerVariables.cs#L84-L85 and look like its not supported?

**Comment by Tratcher** [comment]
Yes, that was the code I was referring to.

Even if we had support for SERVER_SOFTWARE, it would always refer to Kestrel, not upstream servers/proxies.

**Comment by abcplex** [comment]
@Tratcher thanks :) just a final question how would you support SERVER_SOFTWARE? I mean any way to get the Kestral name with version? (One way is through assembly scanning I think)

**Comment by Tratcher** [comment]
We've discussed using IApplicationBuilder.ServerFeatures to advertise server information and capabilities at startup.
