### ISSUE TITLE
ASP.Net 1.0 Core app - HTTP Error 502.3 - Bad Gateway in AspNetCoreModule ErrorCode: 0x80072efe

### ISSUE THREAD

**Issue by gradom** [aspnet/Hosting#855]
I'm working on a .Net Core project for 4 months already. If I work in the "Debug" mode the application runs successfully  and publishing functions correctly. I published my project like the guidline on the asp.net core documentary: [https://docs.asp.net/en/latest/publishing/iis.html](url)

After starting the IIS, the application runs approximatily 5 sec. then I get the following error message: 
![image](https://cloud.githubusercontent.com/assets/22346527/18720817/ede33ab8-802d-11e6-99d5-4cf8561a4286.png)

In the event viewer I get a message which says that an error occurred in the KERNELBASE.dll (ErrorCode: 0xe0434352), the corrupt application is the dotnet.exe.
A subsequently event viewer entry says that the proccess started successfully and is listening on a port (Source: IIS AspNetCore Module).

Another problem is, when I'm enabeling the logging (the stdoutLogEnabled="true") in the web.config I get the following warning message: 

> Warning: Could not create stdoutLogFile \\?\C:\appname\logs\stdout_3052_2016921155154.log, ErrorCode = -2147024893.

The problem-solving approach I already tried is to set the user permissions from "IIS_IUSRS" to full control.

If you have an idea to solve the problems I would be pleased to hear it!
And please don't condemn my english - it's my first entry. Thx. ;)

**Comment by Tratcher** [comment]
This issue was moved to aspnet/IISIntegration#269
