### ISSUE TITLE
Windows 2008 R2 Publish Failed

### ISSUE THREAD

**Issue by danjford** [aspnet/Hosting#859]
Hi,

I can't seem to get my dotnet core app working on a `Windows 2008 R2` server. On publishing I get the following error:

```
C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Publishing.targets(408,5): Error : Cannot find drive. A drive with the name 'C' does not exist.
C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Publishing.targets(408,5): Error : Cannot find drive. A drive with the name 'C' does not exist.
C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Publishing.targets(408,5): Error : Cannot find drive. A drive with the name 'C' does not exist.
C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Publishing.targets(408,5): Error : An error occurred during publish.
Cannot bind argument to parameter 'FilePath' because it is null.

2>Publish failed due to build errors. Check the error list for more details.
========== Build: 1 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========
========== Publish: 0 succeeded, 1 failed, 0 skipped ==========
```

We've installed the dotnet core [hosting bundle](https://www.microsoft.com/net/download) and have used Visual Studio 2015's built in Publishing tool:

![image](https://cloud.githubusercontent.com/assets/7963046/19074069/4039abb4-8a36-11e6-91a5-bf03bfa6a98a.png)

When attempting to view the site, the page is just blank.

**Comment by Webbanditten** [comment]
Did you install .NET framework on the server? 
Otherwise .NET Framework 4.6.1 is available from here: https://www.microsoft.com/en-us/download/details.aspx?id=49982

**Comment by danjford** [comment]
After reinstalling the hosting bundle and setting up again, this no longer seems to be an issue.
