### ISSUE TITLE
Why is hosting environment default value "production"?

### ISSUE THREAD

**Issue by hlubovac** [aspnet/Hosting#863]
RE: https://github.com/aspnet/Hosting/blob/b6da89f54cff11474f17486cdc55c2f21f2bbd6b/src/Microsoft.AspNetCore.Hosting/Internal/HostingEnvironment.cs#L10

I'm curious if there is a reason for this. I tested launching the app without that setting in config, and - since the default is "production" - the danger is that a developer, intermittently, while having network access to production environment, may corrupt production data. IMO, there should not be default at all; if it has to be for some reason, then maybe "development".

Although this whole business of assuming certain business configuration is little unclean to me. We may have more than just the 3 environments, or we may refer to them using other names. Existing environment-related extension methods (IsDevelopment, etc) are just making this confusing. If you ask me, thanks for providing application-path information, but strongly-typing environment types just doesn't belong in this framework. Sorry if I sound uninformed; I based this comment by what's visible to me.

Thanks.

**Comment by hlubovac** [comment]
I guess I discovered a way to change that behavior and make inadvertent mistakes like I mentioned more obvious. So, sharing for those sharing the same concern:

`
            var defaults = new Dictionary<string, string> { { WebHostDefaults.EnvironmentKey, "Development" } };
            var configBuilder = new ConfigurationBuilder().AddInMemoryCollection(defaults)  ... 
`

**Comment by natemcmaster** [comment]
Here's more context: https://github.com/aspnet/Hosting/issues/272

**Comment by hlubovac** [comment]
Thanks - although, I didn't catch an explanation to why exactly it was changed to default to "production".

I just wrote code to change the default to empty/null and to raise an exception if the environment hasn't been specifically set either via env-var or main-args. I have something against black boxes silently falling back to some unobvious behavior: I'd rather have them insist on being explicitly told how to [behave]. But, that's just me :)

Thank you.

**Comment by hlubovac** [comment]
Not that I really want to beat this to death, but whatever happened to writing testable code and then making it difficult/impossible to swap the IHostingEnvironment instance here:

https://github.com/aspnet/Hosting/blob/b6da89f54cff11474f17486cdc55c2f21f2bbd6b/src/Microsoft.AspNetCore.Hosting/WebHostBuilder.cs#L40

Similar would go for `var services = new ServiceCollection();` within the same class.

I'm getting discouraged to use the `WebHostBuilder` class a little.
:)

**Comment by blowdart** [comment]
It was changed to production to be secure by default. This won't change.

**Comment by hlubovac** [comment]
I don't quite get that explanation still. What and how is getting "secure" by that property not being NULL by default?

**Comment by blowdart** [comment]
I am a little confused, which property? Or are you meaning, if the env variable is not there when you say property?

**Comment by hlubovac** [comment]
I used the word "property" to refer to the same thing you defined as "it" in your second to the last comment, sir.

**Comment by blowdart** [comment]
So, the reason we went with production by default is because both our templates, and in general other people's code add detailed error messages, debug logging, and other things that can cause information disclosure vulnerabilities (at best), or things like auth bypass at worst, depending on what you wrapped in an env.IsDevelopment() check.

By defaulting to production we remove that risk.

In addition launching from inside VS and VS Code sets the environment as development, and best practice generally acknowledges developers should not have every day access to production assets, the risk of defaulting to development is far greater than defaulting to release/production.

**Comment by muratg** [comment]
@hlubovac, to clarify @blowdart's point - assume the default is "Development" and you debugging reasons you log/print your connection string. Now this is fine, but if you deploy to your production environment, and forget to set the environment to "Production", you'll start leaking your app's secrets inadvertently.

Re your concern about possibly corrupting your production data -- I VERY strongly recommend against having production secrets on your development boxes. Regardless of the default this is always a big risk!

**Comment by hlubovac** [comment]
I still think that it shouldn't the business of this "platform" (as you call it) or a starter-project template to even care which logic executes and when/where. We didn't have the notion of business-environments for 15 years, and nobody asked .NET team to enforce it in any way. By "solving" the problem of having the project template potentially "suggest" that, e.g. showing a developer-error-page isn't appropriate in all environments, the platform introduces even a bigger one: mistakenly executing code against the production resources (like I described above), and - no, that doesn't even necessary has to mean that I'd have production-related secrets embedded into the source code either (I'll describe how in next paragraph). To expand on the enforced usage, now, that the 3 environments are "strong-typely" bound to launching http service (!?), people will be bound to actually use it, as it's very difficult to not be tempted, since it's impossible to exclude it - because Hosting assembly is somehow a dependency of Kestel (shouldn't it be the other way around, or we're still having problems naming "things" properly). Like I said, maybe the place I work at has been referring to what-you-call-production as "release" (or something else altogether) and, now that `IsProduction` is a part of the framework - unless I favor clutter - I might decide to force myself to use it, and - while I'm not realizing the consequences of commenting-out/removing that setting from launchSettings.json file, I might get myself fired. Finally, that "bigger problem introduced" relates to your template not being able to enforce that "don't embed production secrets in code", even when that's relevant.

And, here's the setup that I know of where no production secrets are embedded in the code, but it's still possible to do damage to production data (assuming developer's workstation has network access to it:

There's a company out there (and I'm sure it's only one of a kind) that likes to centralize database-connection-strings and host their delivery to applications behind a service. So, apps, at their startup, go "hey, conn-string service, gimme conn-string for [insert-environment-here]; I'm app [insert app id], here's my client cert as a proof, too" - and the service goes, "here you are". And then, I'm suddenly deleting customer's data by mistake (because I didn't realize I send the word "production" embedded into that get-conn-string request, if that's not clear by now).

I think your template should be just it. I think you should strive to convert your framework to a library and let me be in charge of what executes and when, as opposed to being called back. Let me use that dependency-injection and inject logging into Kestel if I want to (for example!), and not have you include it there anyway.

Sorry, this wasn't supposed to sound a like a rant. I'm trying to influence you to improve things and avoid creating complexity and confusion unnecessarily. :)

Thanks.

**Comment by blowdart** [comment]
VS has had the concept of different environments, via config transform since 2008.

**Comment by hlubovac** [comment]
I have yet to meet a serious development team who's using VS's "publish" feature to deploy to production.

**Comment by blowdart** [comment]
Indeed, you'd use CI instead. And that would hold the production secrets, rather than them being on a developers machine.

**Comment by hlubovac** [comment]
In the scenario that I described, there are no secrets on the developer's machine. All secrets are behind the service that delivers secrets driven by the value of "EnvironmentName". Perhaps it's a WTF not to host a separate secret-keeper service per business environment, but it's hypothetically how the described problem might occur - and how your template can't do a thing about even warning about it.

Notice how I'm referring to the "environment" in subject as "business environment"? Because that's really what it is. "Environment" by itself hints relation to the operating system to me. A platform/library of pretty much any kind shouldn't force how I organize my "business".

Like I said, I have a work-around to what I consider a problem here. If you're curious, here it is:

`

            var defaults = new Dictionary<string, string> { { WebHostDefaults.EnvironmentKey, string.Empty } };

            var configBuilder = new ConfigurationBuilder()
                .AddInMemoryCollection(defaults)
                .AddEnvironmentVariables("ASPNETCORE_"); // expected to provide a value for environment variable named "environment"

            var configuration = configBuilder.Build();

            string configDirectory = Directory.GetCurrentDirectory();

            // Mimicking the underlying framework to conversion the IConfiguration 
            // object to a strongly-typed container of the environment, in order to 
            // ensure that that value has been explicitly set:
            var options = new WebHostOptions(configuration);

            if (options.Environment.Length == 0)
                throw new Exception("Environment name not provided. Please define environment variable \"ASPNETCORE_ENVIRONMENT\" for the system or the executing user.");
            if (!this.ENVIRONMENTS.Contains(options.Environment.ToLower()))
                throw new Exception("Environment not supported: \"" + options.Environment + "\".");
`

Of course, it's also accompanied with about 25 lines of comments, with links to relevant source code here. Perhaps, over time (I literally just started experimenting with dotnetcore 2 days ago), I'll figure out a more elegant solution to guarantee an explicitly defined business-environment name, but that's what I do now to prevent "Production" to sneak in on me.

**Comment by muratg** [comment]
@hlubovac In the scenario you described, you still have one production secret on the desktop machine: the secret to get other secrets from "secret-keeper" service 😄   That's is NOT secure by any means, and I recommend keeping development/test secrets and production secrets with two different accounts/keys (whatever) on the "secret-keeper" service.

Back to the feature -- like you said you have a workaround for your own workload. You're not "forced" to use our way of approaching the environment names, and what's the default.  I believe we're just guiding folks to the right path (i.e. not expose their secrets.)  

We won't be removing this functionality or the extension methods, mainly because it's a breaking change, but also they are actually being used safely by internal and external customers.

**Comment by hlubovac** [comment]
Thank you for your time.

**Comment by muratg** [comment]
Re hosting being a Kestrel dependency, this is by design. Kestrel is only one of the web servers. (The other one we own is WebListener, which also depends on hosting.)  Anyone can take a dependency on Hosting (among other things) and write their web servers.  Let me know if this doesn't clarify the dependency direction for you.

**Comment by cwe1ss** [comment]
I had the same question a few months ago - it contains some more background: https://github.com/aspnet/Hosting/pull/720

We are also using certificates for authenticating with Azure Key Vault to get secrets. our developers should never have production certs on their machines, but we also think this default behavior is way too dangerous - that's why we decided not to use the built-in environment names - we use DEV/PROD instead. This way, using "Production" just throws on startup.

**Comment by muratg** [comment]
@cwe1ss, if your production secrets are not on the dev or test machines, why would this be dangerous?

**Comment by hlubovac** [comment]
@cweiss, I think I understand the dependency tree. That particular example is a little confusing because we usually "host a [kestrel] service", as opposed to "[kestrel-]serve a host".

I agree with you that business-environment secrets shouldn't cross business-environment boundaries. The example I gave you hypothetical, featuring a much bigger problem, introduced by the solution to forgetting to wrap `app.UseDeveloperExceptionsPage();` within a web.config settings, like we've done so far. It was so much easier to not include that snippet into the template, and instead advertise it via some blog, like everything else is done.

I haven't started researching your solution/suggestions to handling secrets in config files in general, so I can't relate to that at the moment.

**Comment by cwe1ss** [comment]
Because it's not 100% fool-proof. Our system will probably run for 10-15 years and it will contain ~100 services, so there might be this one Friday afternoon where I have to use the production certificate to debug a nasty bug and then I forget to delete the certificate. I don't want this to be the day where I also messed up my production DB because of that. :smile:

But yes, we are taking a few more precautions to make sure this can never happen. E.g. Right now, we still have all environment configurations checked in to the same repo - we'll move them into their own repo, ...

**Comment by hlubovac** [comment]
@cwe1ss, if for anything else, then because it's confusing. Configuration values should be defined by the entity in charge. In this context, the entity in charge is the application and not the "platform". I don't understand what in the world the "platform" needs to know the environment name for!? How'd that relevant to launching a TCP listener, please? Why do you think the platform should define the business process/workflow of the "entity in charge"? I don't understand why you're still defending this.

Sure, I get it: mistake has been made, too many apps out there that depend on this; you can't remove it; fine.

**Comment by cwe1ss** [comment]
@hlubovac I think you wanted to mention @muratg , right?

**Comment by hlubovac** [comment]
corrected; sorry; did that twice to you so far :)

**Comment by hlubovac** [comment]
yes, sorry; corrected

**Comment by muratg** [comment]
@hlubovac To be clear, I don't recommend using configuration files for production secrets -- use some other config mechanism. (If you're using Azure, it can be KeyVault or you can set up env vars on prod via Azure Portal).  For development secrets, again, I don't recommend keeping them in config files (because of the risk of accidentally checking them in).  Instead, use user-secrets tool.

Re your second point, everything is owned by application, platform does nothing special. We have a few extension points as part of the framework, and the templates use these as guidance. 

Also, I don't think our guidance is a mistake - templates are mainly to guide new apps. Folks who have existing conventions have all means of applying those conventions in ASP.NET Core as well. If we completely remove these and put the guidance on a blog, I'd bet that a lot of folks would have bigger issues, like exposing their secrets due to logging/diagnostics, or checking them in as config files in their repos. 

Perhaps we should write some documentation or a blog post about the design decisions on this to more clearly articulate what we tried to accomplish.  Do you think this would be useful?

Again, (unless I'm missing a point) I don't see any real danger/risk AS LONG AS dev boxes do not contain any production secrets. If that's the case, you have much bigger problems IMO.

**Comment by hlubovac** [comment]
I simply have no incentive to argue. Your reasoning is illogical to me. You don't seem to recognize that design to be anti-pattern, and then discussing further is pointless. I am sorry that I have to be so blunt.

Thank you.

**Comment by cwe1ss** [comment]
Secrets are just one side of this issue. There are many more environment specific settings which are not security-relevant - those that usually used to be in the AppSettings section of web.config (e.g. URIs, cache settings, ...). Each one of these could lead to unintended side effects if applied in the wrong environment.

Of course, it would be best to keep all of these things separated as well, but right now, you are [actively promoting](https://github.com/aspnet/Templates/blob/dev/src/BaseTemplates/StarterWeb/Startup.cs#L20) this pattern in your templates - maybe this is something that should be discussed?!

Also I think it is problematic/unexpected that the behavior of Visual Studio (which looks at launchSettings.json and therefore defaults to Development) and raw `dotnet run` usage (which doesn't look at this file and therefore defaults to Production) is different. 

I understand your reasons behind this and I understand that this can no longer be changed. I just wanted to provide more examples of IMO valid scenarios that might now be troublesome. Maybe we find some ways to improve this a bit.

**Comment by hlubovac** [comment]
@muratg, @blowdart - unrelated to the topic, but since you mentioned managing secrets, could you pass it to the proper group that "Installing the Secret Manager tool" section of [https://docs.asp.net/en/latest/security/app-secrets.html](https://docs.asp.net/en/latest/security/app-secrets.html) isn't quite complete (syntax isn't obvious/clear; no link to external document talking about defining "tools"; no example; following the pattern provided by the **template** doesn't work).

Thanks.

**Comment by blowdart** [comment]
That'll be @Rick-Anderson

**Comment by hlubovac** [comment]
Whatever did you mean... I'm not MS employee, don't know your organization (except that you only have 3 business environments: development, staging and production; it's a shame that you don't have one called "test", but now that makes all the sense), so I was asking you to pass that message through maybe an official internal request, as opposed to the optionally viewed public medium such as GitHub (you shouldn't assume my understanding of your internal rules, such as, maybe that you possibly treat GitHub as mandatory issue-tracker).

**Comment by blowdart** [comment]
I tagged Rick because he owns documentation.

**Comment by hlubovac** [comment]
Why bother the guy to feel obligated to read through all this thread, 100% irrelevant to what he needs to organize to get done? I think it would have been much easier if you fired up your internal-request tool, pasted the paragraph that I wrote, addressed it to him, and told me "it's done" - but whatever...

**Comment by blowdart** [comment]
You're welcome to your opinion, however this is out workflow.

As this as spun way out of control topic wise, and as the original question has been answered I'm closing this issue.

**Comment by hlubovac** [comment]
Touché, sir (defining business-environment names).

**Comment by hlubovac** [comment]
That's the way to get business done: sweep under the rug. Great job, @blowdart! Let's give you a raise.

**Comment by hlubovac** [comment]
Thanks for thumbs down. I will not undo what I said. I did that to show frustration related to @blowdart's closing the issue without asking interested parties if they agree with that plan (I clearly wouldn't, as I still find the current implementation in issue anti-pattern, in several locations, as a matter of fact).

**Comment by cwe1ss** [comment]
@hlubovac your communication style in this issue has also been an anti-pattern. :smile: maybe a nicer tone would have brought you further...

@blowdart should I create an issue in the template repo to discuss if using `appsettings.Environment.json` should be removed or do you think it's not worth it?

**Comment by blowdart** [comment]
@cwe1ss Sure, that's a different issue than this one.

**Comment by hlubovac** [comment]
@cwe1ss, you are absolutely right. My tone has been cruel. I'll disagree that a nicer tone would have made a difference, though: Mr. @blowdart had made it very clear at the very beginning that "this would not change". I'm actually surprised this issue hadn't been closed right after that message. Point taken, though, and thank you. Also, thank you for agreeing with me on the problem in issue.

**Comment by muratg** [comment]
@cwe1ss Yes, please do. I was planning to do it sometime today. [Repo: https://github.com/aspnet/templates]

**Comment by cwe1ss** [comment]
done! I hope the description is ok. -> https://github.com/aspnet/Templates/pull/678

**Comment by clement911** [comment]
I can see the argument for both sides and it seems to me there might be a simple solution:
Break it down into **2** different settings.

_EnvironmentName_ is changed to have no default. This will avoid accidentally hitting prod.

A new setting, let's call it _SecurityMode_ (I'm sure there is a better name) defaults to _Restricted_ and drives the visibility of detailed errors, stack traces and other secret revealing stuff. In the dev config files, it can be override to _Relaxed_

Ref https://github.com/aspnet/Templates/pull/678
