### ISSUE TITLE
[Question] Is it possible to mock external network dependencies for TestServer?

### ISSUE THREAD

**Issue by mclark1129** [aspnet/Hosting#864]
I'm trying to write Integration Tests for a WebAPI that uses the `OpenIdConnectMiddleware`.  I'd like to be able to accomplish this by using the exact same `Startup` class as we use with a live deployment, and just overriding services as necessary during the building process.  I'm struggling to figure out the best way to do this when the external dependency is out of my control, and isn't necessarily exposed as an Application Service that can easily be replaced.  

Is there some way that I could handle outbound network requests from a host running inside TestServer so that I might have a chance to mock out responses within my Tests?

**Comment by Tratcher** [comment]
TestServer is built to mock incoming requests, not outgoing. You need to mock the outgoing httpclient directly. This is how we do it in our OAuth provider tests:
https://github.com/aspnet/Security/blob/dev/test/Microsoft.AspNetCore.Authentication.Test/Facebook/FacebookMiddlewareTests.cs#L177
You could make the backchannel an injectable service where the default is a normal HttpClientHandler.

**Comment by mclark1129** [comment]
After making the backchannel injectable I was able to accommodate my specific testing scenario.
