### ISSUE TITLE
Provide a way to get access to the hosting service provider when configuring services

### ISSUE THREAD

**Issue by danroth27** [aspnet/Hosting#865]
This has come up a couple of times now:
- In MVC, we need to get access to the IHostingEnvironment in order to correctly load the MVC application parts. This is currently done with a [hack](https://github.com/aspnet/Mvc/blob/760c8f38678118734399c58c2dac981ea6e47046/src/Microsoft.AspNetCore.Mvc.Core/DependencyInjection/MvcCoreServiceCollectionExtensions.cs#L71)
- For ASP.NET Core modules we need some way to setup the hosting services for each module. This is also currently done with a [hack](https://github.com/danroth27/AspNetCoreModules/blob/master/src/Microsoft.AspNetCore.Modules/ModulesExtensions.cs#L27).

**Comment by muratg** [comment]
cc @glennc We'll need to design this for 1.2.

**Comment by muratg** [comment]
@glennc @danroth27 moving this to 2.1.0

@glennc we'll need to design what change is required here.

**Comment by muratg** [comment]
@danroth27 closing until we revisit modules. If this is required for anything else, please reopen and let us know.
