### ISSUE TITLE
Object disposal issues in WebHostBuilder

### ISSUE THREAD

**Issue by pakrym** [aspnet/Hosting#867]
Hosting service provider is never disposed.

When https://github.com/aspnet/DependencyInjection/issues/459 is fixed all services we register as instances need to be disposed in `WebHost`

**Comment by muratg** [comment]
@pakrym Triaging this for 1.1 since you already have the PR.

**Comment by pakrym** [comment]
https://github.com/aspnet/Hosting/pull/868
