### ISSUE TITLE
Handle SIGTERMs for graceful shutdown

### ISSUE THREAD

**Issue by halter73** [aspnet/Hosting#870]
@stepro pointed out it should now be possible to handle SIGTERMs in addition to the SIGINTs (CTRL+C) that we already hook for graceful shutdown.

> The managed API for SIGTERM is exposed by the [AssemblyLoadContext.Unloading](https://docs.microsoft.com/en-us/dotnet/core/api/system.runtime.loader.assemblyloadcontext#System_Runtime_Loader_AssemblyLoadContext_Unloading) event, which is raised when the [AppDomain.ProcessExit](https://msdn.microsoft.com/en-us/library/system.appdomain.processexit%28v=vs.110%29.aspx) event is raised. I know this only because I’ve seen it used in the VSTS agent codebase (see [this](https://github.com/Microsoft/vsts-agent/blob/master/src/Microsoft.VisualStudio.Services.Agent/HostContext.cs), line 44).
> You can see how coreclr maps SIGTERM to shutting down [here](https://github.com/dotnet/coreclr/blob/7dfb2ed8614dea8c2fe757592436a38694e91ebc/src/vm/exceptionhandling.cpp), line 170.

This should be especially useful for running in docker containers.

**Comment by davidfowl** [comment]
Do we want to handle both SIGTERM and SIGINT? Should they mean the same thing? Here are related issues:

- https://github.com/aspnet/Hosting/issues/516
- https://github.com/aspnet/Hosting/issues/59

**Comment by muratg** [comment]
cc @glennc

**Comment by stepro** [comment]
As it stands, .NET Core handles both SIGTERM and SIGINT (as well as most of the other Linux signals) in the sense that it registers for the signals. Whether it actually does something useful is up to whether the application listens on the necessary events and handles them appropriately.

Given this, ASP .NET should definitely gracefully stop the application on SIGTERM because the alternative (effectively, SIGTERM equals SIGKILL) is never going to be the desired behavior.

Aside from potential differences on what is output to a live console, SIGINT and SIGTERM should both stop the ASP .NET application. SIGINT works well for a dev scenario where you are locally running the process synchronously; SIGTERM is appropriate when running in the background or unattended in a server scenario.

**Comment by davidfowl** [comment]
I can't get this to work in a simple console app on OSX:

```C#
public class Program
{
    public static void Main(string[] args)
    {
        var ended = new ManualResetEventSlim();
        var starting = new ManualResetEventSlim();

        AssemblyLoadContext.Default.Unloading += ctx =>
        {
            System.Console.WriteLine("Unloding fired");
            starting.Set();
            System.Console.WriteLine("Waiting for completion");
            ended.Wait();
        };

        System.Console.WriteLine("Waiting for signals");
        starting.Wait();

        System.Console.WriteLine("Received signal gracefully shutting down");
        Thread.Sleep(5000);
        ended.Set();
    }
}
```

I tried using:

```
kill -SIGTERM {PID}
```

**Comment by muratg** [comment]
@davidfowl Does a console app catch SIGINT, though?

**Comment by davidfowl** [comment]
Handling Console.CancelKeyPress handles SIGINT but not this.

**Comment by muratg** [comment]
Bringing the bug back to 1.1 for further investigation.

**Comment by stepro** [comment]
The code I got to work pulls the AssemblyLoadContext in a different way:

AssemblyLoadContext.GetLoadContext(typeof(Program).GetTypeInfo().Assembly)

**Comment by halter73** [comment]
I just tried your program verbatim on Debian 8.2. Worked fine there. Maybe the issue you're running into is mac specific.

     ~/SigtermApp$ dotnet run
    Project SigtermApp (.NETCoreApp,Version=v1.1) was previously compiled. Skipping compilation.
    Waiting for signals
    Unloding fired
    Waiting for completion
    Received signal gracefully shutting down
    ~/SigtermApp$

**Comment by halter73** [comment]
BTW `kill <PID>` and `kill -SIGTERM <PID>` are the same.

**Comment by davidfowl** [comment]
Then it's an OSX specific problem. We should look into this.

/cc @kouvel any ideas?

**Comment by pakrym** [comment]
https://github.com/aspnet/Hosting/pull/876

**Comment by muratg** [comment]
@pakrym test in yet? This one good to close?

**Comment by pakrym** [comment]
@muratg tests is still pending

**Comment by Eilon** [comment]
@pakrym please label appropriately and close ASAP.

**Comment by pakrym** [comment]
https://github.com/aspnet/Hosting/pull/878

**Comment by Eilon** [comment]
@pakrym @muratg should this issue be marked as a `bug`?
