### ISSUE TITLE
[LTS patch] WebHost.Run() completes before ApplicationStopping

### ISSUE THREAD

**Issue by muratg** [aspnet/Hosting#873]
Original issue: https://github.com/aspnet/Hosting/issues/812, fixed in 1.1.0-preview1.

`ApplicationStopping` exits before `ApplicationStopped`, preventing app to take any measures it may need before getting stopped.  Fix is simple and low risk.

We'd like to bring this in an upcoming LTS-patch release.

cc @Eilon @DamianEdwards @davidfowl

**Comment by Eilon** [comment]
This patch is **approved**, please ensure it is merged into the correct branch and building as part of the patch train.

**Comment by JunTaoLuo** [comment]
This is completed in https://github.com/aspnet/Hosting/commit/da5ea830b50652c85a6c878831c04d455de84031.
