### ISSUE TITLE
Remove case-sensitivity from Configure{IHostingEnvironment.EnvironmentName}Services Lookup

### ISSUE THREAD

**Issue by carusology** [aspnet/Hosting#877]
**Problem**

There is inconsistent behavior around case-sensitivity with respect to `IHostingEnvironment.EnvironmentName`. If I set `ASPNETCORE_ENVIRONMENT` to `development`, `Development`, or `DEVELOPMENT`, `IHostingEnvironment.IsDevelopment()` will return `true` because it uses `StringComparison.OrdinalIgnoreCase` [here](https://github.com/aspnet/Hosting/blob/b6da89f54cff11474f17486cdc55c2f21f2bbd6b/src/Microsoft.AspNetCore.Hosting.Abstractions/HostingEnvironmentExtensions.cs#L77). This means in your `ConfigureServices` code in Startup.cs, as suggested in #252, you can do the following:

```
public class Startup {

    private IHostingEnvironment environment { get; }

    public Startup(IHostingEnvironment environment) {
        this.environment = environment;
    }

    public void ConfigureServices(IServiceCollection services) {
        if (this.environment.IsDevelopment()) {
            // development-specific services
        } else {
            // non-development-specific services
        }
    }

}
```

However, an alternative approach can be done by putting the environment name in the method name in the format of `Configure{IHostingEnvironment.EnvironmentName}Services`. Here's an example:

```
public class Startup {

    private IHostingEnvironment environment { get; }

    public Startup(IHostingEnvironment environment) {
        this.environment = environment;
    }

    public void ConfigureDevelopmentServices(IServiceCollection services) {
        // development-specific services
    }

    public void ConfigureServices(IServiceCollection services) {
        // non-development-specific services
    }

}
```

In order to use it this way, I must set `ASPNETCORE_ENVIRONMENT` to *exactly* `Development` for `ConfigureDevelopmentServices` to be ran because [the method name comparison is case-sensitive](https://github.com/aspnet/Hosting/blob/b6da89f54cff11474f17486cdc55c2f21f2bbd6b/src/Microsoft.AspNetCore.Hosting/Internal/StartupLoader.cs#L143). If you set it to any other case (`development`, `DEVELOPMENT`) the `ConfigureServices` method will be ran instead.

**Suggested Fix**

Change the comparison [here](https://github.com/aspnet/Hosting/blob/b6da89f54cff11474f17486cdc55c2f21f2bbd6b/src/Microsoft.AspNetCore.Hosting/Internal/StartupLoader.cs#L143) to use a regular expression that defines the environment name portion of the method name as a group, then extracts that group to do a case-insensitive comparison with the environment name. Something like this:

```
var myRegex = new Regex("$Configure(?<EnvironmentName>\w+)Services^")
var match = myRegex.Match(method.Name);
var isSuccess =
    match.Success && 
    StringComparer.OrdinalIgnoreCase.Equals(match.Groups["EnvironmentName"].Value, environmentName);
```

Then we can set `ASPNETCORE_ENVIRONMENT` without worrying about case, as we do when using the `IsDevelopment()` extension method.

**Comment by muratg** [comment]
@glennc This is a breaking change, though we can make this in 2.0.0.  Thoughts?

**Comment by NickCraver** [comment]
I'd agree on this for 2.x. It's the kind of fail that devs hit, have to dig on, and are just angrier when they find out why - definitely make it more intuitive.

**Comment by davidfowl** [comment]
We definitely shouldn't use rege my to defect it either....

**Comment by carusology** [comment]
@davidfowl I definitely don't care about the approach. Looking at the current code, it was one that would involve very little changes. Consistent case insensitivity is the only real goal of this issue.

**Comment by glennc** [comment]
I am ok with this for 2.x release. We should add it to the list of breaking changes we are considering.

To be clear. The goal is to make the method name comparison case insensitive. So that if I set `ASPNETCORE_ENVIRONMENT` to `deVelOpment` it would still match `ConfigureDevelopment` in my `startup.cs` and IsDevelopment would also return true. We aren't talking about trying to normalize names so that the method name has to be a particular casing.

**Comment by carusology** [comment]
@glennc That's what I would call the real issue, yes.

While I would certainly like to see a nudge towards normalized method names (hence the suggestion of a Regex instead of a simply adding StringComparison), I recognize that it would never be perfect since the correct pascal casing for a given environment name cannot be programmatically determined.

One last thing to highlight that is coupled to this issue: there are [other](https://github.com/aspnet/Hosting/blob/b6da89f54cff11474f17486cdc55c2f21f2bbd6b/src/Microsoft.AspNetCore.Hosting/Internal/StartupLoader.cs#L118) [methods](https://github.com/aspnet/Hosting/blob/b6da89f54cff11474f17486cdc55c2f21f2bbd6b/src/Microsoft.AspNetCore.Hosting/Internal/StartupLoader.cs#L124) that use the same [`FindMethod()`](https://github.com/aspnet/Hosting/blob/b6da89f54cff11474f17486cdc55c2f21f2bbd6b/src/Microsoft.AspNetCore.Hosting/Internal/StartupLoader.cs#L137) call that do the same case-sensitive comparison. Presumably they will get updated as well?

**Comment by muratg** [comment]
We'll need to change the following lines (and a few more) https://github.com/aspnet/Hosting/blob/dev/src/Microsoft.AspNetCore.Hosting/Internal/StartupLoader.cs#L97-L98https://github.com/aspnet/Hosting/blob/dev/src/Microsoft.AspNetCore.Hosting/Internal/StartupLoader.cs#L97-L98.

We'll attempt to get at this in 2.1.

**Comment by muratg** [comment]
This is a breaking change, though the triage thinks it's a low-risk one.

**Comment by jkotalik** [comment]
@muratg Do we compile a list of breaking changes as backreference?

**Comment by muratg** [comment]
@jkotalik We use the tag `breaking-change` on the issues that we can use to create the list.

**Comment by JunTaoLuo** [comment]
If this is a breaking change, you'll need to post an announcement in https://github.com/aspnet/announcements
