### ISSUE TITLE
Revisit IApplicationLifetime.StopApplication

### ISSUE THREAD

**Issue by davidfowl** [aspnet/Hosting#882]
This method call only works today if the `IWebHost` is run using `host.Run()`. It means that if somebody uses the `Start()`, `Dispose()` pattern this becomes completely ineffective and that's pretty broken. If we expose first class abstractions like this then they need to work no matter how the hosting logic is written. 

In this scenario, an application or a library needs a way to signal to to the host that it wants to shutdown via `IApplicationLifetime.StopApplication`. When that happens the webhost should unwind and perform graceful clean up (signal to the server that graceful shutdown begins).

We should also document on library components should handle shutdown/disposal of components.

**Comment by muratg** [comment]
https://github.com/aspnet/Hosting/pull/875?

**Comment by davidfowl** [comment]
@muratg yes

**Comment by davidfowl** [comment]
Closing this out, the decision we came to was that we would expose the `ApplicationStopping` on `IWebHost`. See https://github.com/aspnet/Hosting/issues/897. Basically StopApplication will request the `IWebHost` to stop running, the owner of the `IWebHost` can decide what to do.
