### ISSUE TITLE
IServer and IFeatureCollection

### ISSUE THREAD

**Issue by grahamehorner** [aspnet/Hosting#890]
currently the IFeatureCollection is located in the AspNetCore.Http namespace this implies that only Http Features can be hosted by an IServer implementation, please consider moving the IFeatureCollection to a more generic namespace so there is no need to reference AspNetCore.Http when developing non-http features.

**Comment by davidfowl** [comment]
This is a huge breaking change. I agree it's unfortunate but its hard to move at this point.

**Comment by grahamehorner** [comment]
@davidfowl do you think this could be done as part of #bedrock or in the v3.0 timeframe ?

Understand it a huge breaking change, but feel that it could help longer term as when .netcore developers start creating other types of servers FTP, SMTP etc.
