### ISSUE TITLE
IServer and IHttpApplication

### ISSUE THREAD

**Issue by grahamehorner** [aspnet/Hosting#891]
currently the IServer interface has a IHttpApplication, please consider changing this to a more generic IServerApplication to a more generic style and implementation of non-http applications.

**Comment by davidfowl** [comment]
Once we figure out what we're building we can take a look at this. This issue won't be that helpful until we write up the proposal.

**Comment by davidfowl** [comment]
This is a massive breaking change at this point so we can't break this now.

**Comment by grahamehorner** [comment]
@davidfowl do you it could be possible to do as part of #bedrock ?
