### ISSUE TITLE
ASPNet Core 1.01 App - Unable to start on Azure (HTTP 502.5) - Failed to start process with commandline '"dotnet" \\?\D:\home\site\wwwroot\Esoterix.Modle.Portalweb.dll', ErrorCode = '0x80004005'

### ISSUE THREAD

**Issue by tiefling** [aspnet/Hosting#892]
I am trying to deploy an aspnet core app to Azure using VSTS release. This seems to have gone through OK but when I try to start up the app I am presented with the HTTP 502.5 error...

Common causes of this issue:

The application process failed to start
The application process started but then stopped
The application process started but failed to listen on the configured port

Troubleshooting steps:

Check the system event log for error messages
Enable logging the application process’ stdout messages
Attach a debugger to the application process and inspect

There seems to be much written about IIS in this but not with Azure.

I managed to find an event log which threw out some XML repeatedly logging...

> Failed to start process with commandline '"%LAUNCHER_PATH%"
> %LAUNCHER_ARGS%', ErrorCode = '0x80070002'.

After more investigation I discovered that I needed to change the %LAUNCHER_PATH% and %LAUNCHER_ARGS% values myself. I've tried various changes to the web.config but no luck. My web.config now looks like this...

    <?xml version="1.0" encoding="utf-8"?>
    <configuration>
    
      
    
      <system.webServer>
        <handlers>
          <add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModule" resourceType="Unspecified"/>
        </handlers>
        <aspNetCore processPath="dotnet" arguments="site\wwwroot\Esoterix.Modle.Portalweb.dll" stdoutLogEnabled="true" stdoutLogFile="LogFiles\stdout" forwardWindowsAuthToken="false"/>
      </system.webServer>
    </configuration>

The paths are from the root of the Azure deployment which seems to work for the stdout log file path (I was getting errors reported with that) but not for the app itself. I'm still seeing the following error..

    <Event>
        <System>
            <Provider Name="IIS AspNetCore Module"/>
            <EventID>1000</EventID>
            <Level>0</Level>
            <Task>0</Task>
            <Keywords>Keywords</Keywords>
            <TimeCreated SystemTime="2016-11-28T19:31:32Z"/>
            <EventRecordID>1514022203</EventRecordID>
            <Channel>Application</Channel>
            <Computer>RD0004FFD7108D</Computer>
            <Security/>
        </System>
        <EventData>
            <Data>Failed to start process with commandline '"dotnet" site\wwwroot\Esoterix.Modle.Portalweb.dll', ErrorCode = '0x80004005'.</Data>
        </EventData>
    </Event>

Which is repeated 4 times

If I look in my stdout output I have the following...

> Failed to load the dll from [\\?\D:\home\site\wwwroot\hostpolicy.dll],
> HRESULT: 0x800700C1
> 
> An error occurred while loading required library hostpolicy.dll from
> [\\?\D:\home\site\wwwroot]

If I try running the exe directly with the web config here...

    <?xml version="1.0" encoding="utf-8"?>
    <configuration>
    
      
    
      <system.webServer>
        <handlers>
          <add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModule" resourceType="Unspecified"/>
        </handlers>
        <aspNetCore processPath="\\?\%home%\site\wwwroot\Esoterix.Modle.Portalweb.exe" arguments="" stdoutLogEnabled="true" stdoutLogFile="\\?\%home%\LogFiles\stdout" forwardWindowsAuthToken="false"/>
      </system.webServer>
    </configuration>

Then my stdout gives me the following error...

> Failed to load the dll from [\\?\D:\home\site\wwwroot\hostfxr.dll],
> HRESULT: 0x80070057
> 
> The library hostfxr.dll was found, but loading it from
> \\?\D:\home\site\wwwroot\hostfxr.dll failed
> 
>  - Installing .NET Core prerequisites might help resolve this problem.
> 
>      http://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409

**Comment by moozzyk** [comment]
Can you show your project.json? When you publish to Azure a post publish script should be invoked which fixes your web.config file. Because you ended up with %LAUNCHER_PATH% it did not happen. You can fix your web.config manually but what you put there depends on the framework you are targeting (full .NET vs. .NET Core) and the application type (standalone vs. shared) etc. In addition if you change web.config manually you may not be able to run the application from VS (it depends on %LAUNCHER_PATH%/%LAUNCHER_ARGS%) so it's better to fix the pospublish script.

**Comment by tiefling** [comment]
I don't think any kind of post publish script is running.

I'm running dotnet publish from VSTS Online using the arguments -c $(BuildConfiguration) -o $(build.artifactstagingdirectory)

Any idea how I trigger that?

My project.json is as follows...

```
{
    "userSecretsId": "aspnet-Esoterix.Modle-4f959c13-f1e4-4644-9514-f9e15f039700",

    "dependencies": {
        "Esoterix.Modle": {
            "target": "project"
        },
        "Microsoft.AspNetCore.Authentication.Cookies": "1.1.0-preview1-final",
        "Microsoft.AspNetCore.Diagnostics": "1.1.0-preview1-final",
        "Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore": "1.1.0-preview1-final",
        "Microsoft.AspNetCore.Identity.EntityFrameworkCore": "1.1.0-preview1-final",
        "Microsoft.AspNetCore.Mvc": "1.1.0-preview1-final",
        "Microsoft.AspNetCore.Mvc.Core": "1.1.0-preview1-final",
        "Microsoft.AspNetCore.Razor.Tools": "1.0.0-preview3-final",
        "Microsoft.AspNetCore.Routing": "1.1.0-preview1-final",
        "Microsoft.AspNetCore.Server.IISIntegration": "1.1.0-preview1-final",
        "Microsoft.AspNetCore.Server.Kestrel": "1.1.0-preview1-final",
        "Microsoft.AspNetCore.StaticFiles": "1.1.0-preview1-final",
        "Microsoft.EntityFrameworkCore.SqlServer": "1.1.0-preview1-final",
        "Microsoft.EntityFrameworkCore.SqlServer.Design": "1.1.0-preview1-final",
        "Microsoft.EntityFrameworkCore.Tools": "1.0.0-preview3-final",
        "Microsoft.Extensions.Caching.SqlServer": "1.1.0-preview1-final",
        "Microsoft.Extensions.Configuration.EnvironmentVariables": "1.1.0-preview1-final",
        "Microsoft.Extensions.Configuration.Json": "1.1.0-preview1-final",
        "Microsoft.Extensions.Configuration.UserSecrets": "1.1.0-preview1-final",
        "Microsoft.Extensions.Logging": "1.1.0-preview1-final",
        "Microsoft.Extensions.Logging.Console": "1.1.0-preview1-final",
        "Microsoft.Extensions.Logging.Debug": "1.1.0-preview1-final",
        "Microsoft.Extensions.Options.ConfigurationExtensions": "1.1.0-preview1-final",
        "Microsoft.NETCore.App": "1.1.0-preview1-001100-00",
        "Microsoft.VisualStudio.Web.BrowserLink.Loader": "14.1.0-preview1-final",
        "Microsoft.VisualStudio.Web.CodeGeneration.Tools": "1.0.0-preview3-final",
        "Microsoft.VisualStudio.Web.CodeGenerators.Mvc": "1.0.0-preview3-final"
    },

    "tools": {
        "Microsoft.Extensions.SecretManager.Tools": "1.0.0-preview3-final",
        "Microsoft.EntityFrameworkCore.Tools.DotNet": {
            "version": "1.0.0-preview3-final",
            "imports": "portable-net451+win8"
        }
    },

    "frameworks": {
        "netcoreapp1.0": {
            "imports": [
                "dotnet5.6",
                "portable-net45+win8"
            ]
        }
    },

    "buildOptions": {
        "emitEntryPoint": true,
        "preserveCompilationContext": true
    },

    "runtimes": {
        "win81-x64": {},
        "win81-x86": {}
    },

    "runtimeOptions": {
        "configProperties": {
            "System.GC.Server": true
        }
    },

    "publishOptions": {
        "include": [
            "wwwroot",
            "**/*.cshtml",
            "appsettings.json",
            "web.config"
        ]
    },

    "scripts": {
        "prepublish": [ "npm install", "gulp build-prod" ],
        "postpublish": [ "dotnet publish-iis --publish-folder %publish:OutputPath% --framework %publish:FullTargetFramework%" ]
    }
}
```

**Comment by moozzyk** [comment]
Looks like the tool that updates web.config when you publish is not configured in your project.json. 

You need to add the following line to your `tools` section:

    "Microsoft.AspNetCore.Server.IISIntegration.Tools": "1.0.0-preview2-final"

Also note that the version is intentionally `1.0.0-preview2-final` as .NET Core 1.1 does not seem to be deployed to VSTS yet. It is fine to run publish-iis tool using the .NET Core 1.0 though. 
You may find more details in the related issue: https://github.com/aspnet/Home/issues/1842

**Comment by tiefling** [comment]
After doing that (and a load of library updates too) my web,config now looks like this...

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <!--
    Configure your application settings in appsettings.json. Learn more at http://go.microsoft.com/fwlink/?LinkId=786380
  -->
  <system.webServer>
    <handlers>
      <add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModule" resourceType="Unspecified" />
    </handlers>
    <aspNetCore processPath=".\Esoterix.Modle.Portalweb.exe" arguments="" stdoutLogEnabled="true" stdoutLogFile="\\?\%home%\LogFiles\stdout" forwardWindowsAuthToken="false" />
  </system.webServer>
</configuration>
```

I am now getting the following...

```
<Events>
    <Event>
        <System>
            <Provider Name="IIS AspNetCore Module"/>
            <EventID>1001</EventID>
            <Level>0</Level>
            <Task>0</Task>
            <Keywords>Keywords</Keywords>
            <TimeCreated SystemTime="2016-11-28T23:15:50Z"/>
            <EventRecordID>1527480343</EventRecordID>
            <Channel>Application</Channel>
            <Computer>RD0004FFD7108D</Computer>
            <Security/>
        </System>
        <EventData>
            <Data>Process '6584' started successfully and is listening on port '19675'.</Data>
        </EventData>
    </Event>
</Events>
```

I have many other errors and issues to deal with that I expected (connection strings / SSL etc.) but I have running code. Thanks @moozzyk

**Comment by moozzyk** [comment]
See: https://github.com/aspnet/Home/issues/1842#issuecomment-265951372
