### ISSUE TITLE
Extending IApplicationLifetimeEvents

### ISSUE THREAD

**Issue by davidfowl** [aspnet/Hosting#893]
Related to https://github.com/aspnet/Hosting/commit/42594afd4253a7ab0292ac7d126678f9e91d42b4

After playing with this feature for a bit, it occurred to me that we might be able to do a few things with it:

- This might be the place we handle kicking off background tasks
- We might want to enable an API experience similar to QueuebackgroundWorkItem (in previous ASP.NET)
- This might be the place to application warm up so maybe OnApplicationStarted() it should be async? Even though startup isn't.
- Consider splitting interface for shutdown and startup events (if it makes sense).

**Comment by muratg** [comment]
@davidfowl I don't think there's anything left to do here (perhaps apart form app warm-up). Closing this, but feel free to file another one with any gaps.
