### ISSUE TITLE
Consider renaming the methods on IApplicationLifetimeEvents (and maybe the interface)

### ISSUE THREAD

**Issue by davidfowl** [aspnet/Hosting#895]
Instead of On* which looks like an event, maybe they should be proper method names (verbs).

```C#
public interface IApplicationLifetimeEvents
{
   // Maps to ApplicationStarted, this is where you populate caches etc (should it be async even though startup isn't).
   void InitializeApplication();

    // Maps to ApplicationStopping. Gives the application a chance to run logic before requests are drained.
   void StopApplication(); 
}
```

I can't think of a reason to handle ApplicationStopped. At that point the service provider is already disposed so you can't *really* call into anything safely.

**Comment by NickCraver** [comment]
+1 on stripping "On"

However, the `OnApplicationStopped` event was useful. We planned on using it for telemetry after moving There are many uses in hosting environments for this: telemetry, removal from the load balancer, shared cache notifications, anything with queues and master professing, etc. We even do things like stop logging errors while a shutdown occurs because they're so much racing happening as to be unpredictable.

Please don't remove this call...unless there's another equivalent in the pipe we can hook into here?

**Comment by davidfowl** [comment]
I'm on putting it back if we can find scenarios where it's usable. The fact that the service provider has already disposed everything is my motivation for removing it. If you call into things that have been disposed, they'll go boom.

**Comment by Tratcher** [comment]
Design review:
IHostedService
- ctor
- Start
- Stop
- Dispose (if IDisposable)

**Comment by benaadams** [comment]
Hmm... `Start` and `Stop` sound like commands rather than things happening.

Present participle better: `Starting` and `Stopping`?

**Comment by benaadams** [comment]
Hmm... `Start` and `Stop` sound like commands rather than things happening.

Present participle better: `Starting` and `Stopping` if early in pipeline?
Past tense if later `Started` and `Stopped`?

**Comment by davidfowl** [comment]
Thats the point. It's it's more like [IRegisteredObject](https://msdn.microsoft.com/en-us/library/system.web.hosting.iregisteredobject%28v=vs.110%29.aspx?f=255&MSPPError=-2147217396) in previous ASP.NET. It's a service that gets notified on Start up of the application (after listening) and after before dispose. It's explicitly *not* about application events, thats the fundamental change.

**Comment by benaadams** [comment]
Aha, gotcha. So its the declaration of the `Start` and `Stop` methods in the interface. Makes sense then 😄

**Comment by davidfowl** [comment]
Yep!
