### ISSUE TITLE
TestServer should call IHttpContextFactory.Create with valid featureCollection

### ISSUE THREAD

**Issue by cortex93** [aspnet/Hosting#896]
Hi,

I'm trying to set the TraceIdentifier from request headers early in the request processing before HostingApplication begins the scope and logs it.
To do so, I’m reading HttpContext.Request.Headers in a custom HttpContextFactory.Create method. While it works with Kestrel, it doesn't with TestServer.

From what I understand, TestServer do not populate HttpContext from the IFeatureCollection but it calls IHttpApplication.CreateContext with a fake RequestFeature and modify the returned HttpContext before calling IHttpApplication.ProcessRequestAsync.

If that's not a bug, what is the correct usage and how could I achieve my requirement

**Comment by cortex93** [comment]
In RequestState, setting the RequestFeature properties directly with the one from given request.
I do the same with response,and finally create the Context to set the abortedSource token on it.

This make it works but I really don't know the implication.

**Comment by Tratcher** [comment]
Yes, we could do that. The only reason it hadn't been done that way was that it was more convenient to set fields via the HttpContext. See https://github.com/aspnet/Hosting/blob/b6da89f54cff11474f17486cdc55c2f21f2bbd6b/src/Microsoft.AspNetCore.TestHost/ClientHandler.cs#L128-L138

**Comment by cortex93** [comment]
In fact, using the feature is also that convenient. Just replacing
```
Context = application.CreateContext(contextFeatures);
var httpContext = Context.HttpContext;
var serverRequest = httpContext.Request
```
with 
`var serverRequest = contextFeatures.Get<IHttpRequestFeature>();`

does the trick. QueryString is of different type so .Value will be required for QueryString.FromUriComponent

At the end, 
```
httpContext.Response.Body = _responseStream;
httpContext.Response.StatusCode = 200;
httpContext.RequestAborted = _requestAbortedSource.Token;
```

may be replace with
```
var responseFeature = contextFeatures.Get<IHttpResponseFeature>()
responseFeature.Body = _responseStream;
responseFeature.StatusCode = 200;
Context = application.CreateContext(contextFeatures);
Context.HttpContext.RequestAborted = _requestAbortedSource.Token;

```

**Comment by davidfowl** [comment]
@Tratcher let's make this change.

/cc @muratg
