### ISSUE TITLE
Add the default hosting services to IWebHost as directly accessible properties. IHostingEnvironment, ApplicationStopping, etc.

### ISSUE THREAD

**Issue by Tratcher** [aspnet/Hosting#897]
@davidfowl

**Comment by muratg** [comment]
@glennc FYI.

**Comment by davidfowl** [comment]
What's concerning about this change is the fact that our default services might grow over time. 

1. We can either leave it as it is and expose extension method (ZOMG we need extension properties)
2. We can add a few properties that we think are core to the usage of `IWebHost`, like `IHostingEnvironment` and `ApplicationStopping` and leave the rest as services.
3. We can do nothing and require even the most basic properties to be resolved via the service provider.

I'm leaning towards 2.

**Comment by muratg** [comment]
@davidfowl Do we want this?  1 or 2?

**Comment by davidfowl** [comment]
Nope
