### ISSUE TITLE
Azure deployment of asp.net core successds but obscured runtime error?

### ISSUE THREAD

**Issue by asadsahi** [aspnet/Hosting#899]
Azure deployment happened successfully, but running app gives following error:

![image](https://cloud.githubusercontent.com/assets/3470892/20936079/230f9fce-bbd9-11e6-98c8-58bd8990fb70.png)

I haven't upgraded to new csproj yet and running using project.json with .net core 1.1 framework and targetting following sdk in global.json to force it to use this version:

```
{
    "projects": [
    ],
    "sdk": {
        "version": "1.0.0-preview2-1-003177"
    }
}
```

No idea what this error means. Anyone is aware of this issue?

**Comment by andriysavin** [comment]
I saw such error when my app was crashing during start due to some exception. I recommend you to add the App Service integration (Microsoft.AspNetCore.AzureAppServicesIntegration package) and enable logging in the app settings like this:
![image](https://cloud.githubusercontent.com/assets/12996633/20937328/2ed7dcfc-bbef-11e6-853b-550143ae66dd.png)

**Comment by moozzyk** [comment]
Did you update package versions? Show your project.json. Also, turn on logging and see what exception you got.

**Comment by asadsahi** [comment]
@moozzyk @andriysavin , thanks for pointing out enabling the errors. My issue was a runtime error, which wasn't happening during dev or even in production build locally. Only when I was deploying to azure. Here is the code:

```
 services.AddDbContext<ApplicationDbContext>(options =>
            {
                string useSqLite = Configuration["Data:useSqLite"];
                if (useSqLite.ToLower() == "true")
                {
                    options.UseSqlite(Configuration["Data:SqlLiteConnectionString"]);
                }
                else
                {
                    options.UseSqlServer(Configuration["Data:SqlServerConnectionString"]);
                }

            });
```
So, I added UseSqlServer in options, but the "Microsoft.EntityFrameworkCore.SqlServer": "1.1.0",package wasn't added. So this was causing a runtime error, and only on Azure. Neither running locally nor a production build was causing any issues.

**Comment by andriysavin** [comment]
My understanding is that azure diagnostics is intended for eventual use, especially when an error happens earlier than an app is initialized, so app logging is not set up. While for regular logging of application events and errors different log providers should be used. But I would recommend to clarify that in docs.

**Comment by asadsahi** [comment]
Azure deployment is totally unstable with version change I believe.

After deployments been happening successfully now it is failing with this error:

![image](https://cloud.githubusercontent.com/assets/3470892/21287450/b07de234-c463-11e6-9351-b173250c4b19.png)


Even same framework, same project.json. Really annoyed with Azure deployments. Anybody can help please?

Thanks

**Comment by GuardRex** [comment]
`dotnet publish "AspNetCoreSpa.xproj" ...` ???

#### `dotnet publish [project]`
`[project]` ...
> This value can be a path to the project.json file or to the project directory that contains the project.json file.

https://docs.microsoft.com/en-us/dotnet/articles/core/tools/dotnet-publish

**Comment by asadsahi** [comment]
@GuardRex Thanks for trying this options however error was same:
`"AspNetCoreSpa.xproj does not contain a project.json file`

However, I tried removing xproj file from root of the project so that only project.json file exists. So I have one directory contains all the files with only project.json file at the root. (No xproj or any solution file either)

No I have two questions:

1) Do we have to have only project.json file event previously having xproj wasn't breaking azure deployment

2) With new csproj structure, do we need to prepare our project for future? How will it work with csproj file.

Thanks for your help.

**Comment by muratg** [comment]
We are closing this issue because no further action is planned for this issue. If you still have any issues or questions, please log a new issue with any additional details that you have.
