### ISSUE TITLE
Question : IIS dotnet.exe memory management

### ISSUE THREAD

**Issue by onesandzeros415** [aspnet/Hosting#900]
I apologize if this is a duplicate question however I've yet to find any concrete information on IIS dotnet.exe memory/cpu management.  According to @DamianEdwards from September 17,  2015 via [issue 364](https://github.com/aspnet/Hosting/issues/364) IIS is still managing the process. The AppPool settings that control recycling, memory limits, etc. still apply.
 
Does this apply to limiting memory/cpu consumption of the dotnet.exe process itself?  I'm curious as I've set a memory limit of 524 megabytes on an application pool and dotnet.exe is able to exceed this set limit.  Setting process affinity also does not appear to work on the dotnet.exe process. 

<img width="818" alt="dotnetmem" src="https://cloud.githubusercontent.com/assets/1730698/20991810/28ad2ece-bca6-11e6-901e-a31d88b32aa2.png">

Any clarification on memory/cpu management of the dotnet.exe process via IIS would be helpful.

**Comment by Tratcher** [comment]
This issue was moved to aspnet/AspNetCoreModule#51
