### ISSUE TITLE
Debugging MVC project

### ISSUE THREAD

**Issue by joshmouch** [aspnet/Hosting#901]
I've found a few articles on how to use Microsoft.AspNetCore.TestHost to test an ASP.Net Core project.

However, I can't find a way to actually step through the ASP.Net project code and/or break on an exception in that code.

Is there a way to do this?  If not, then I don't see how the library is any different than just CTRL-F5 on your ASP.Net project with a test configuration and then using an HttpClient.

**Comment by davidfowl** [comment]
> However, I can't find a way to actually step through the ASP.Net project code and/or break on an exception in that code.

What does the test host have to do with stepping through the ASP.NET source code?

> Is there a way to do this? If not, then I don't see how the library is any different than just CTRL-F5 on your ASP.Net project with a test configuration and then using an HttpClient.

Not sure I understand.

You can debug ASP.NET Core but that's unrelated to the TestHost...

**Comment by joshmouch** [comment]
Visual Studio has a "Debug Test" option that allows you to set breakpoints and step through code and break at exceptions.

If I create a test like this:
````
[Fact]
public void SomeTest() {
    var controller = new ControllerIWantToTest();
}
````
then I can set a breakpoint in that controller and look at the code.

My question is, if I use Microsoft.AspNetCore.TestHost, is there a way to set a breakpoint inside a controller?

**Comment by Tratcher** [comment]
I do that all the time, there should't be any special tricks to it. Set the breakpoint before starting debugging. When you do that does VS complain there's no symbols loaded for that file/breakpoint?

**Comment by joshmouch** [comment]
Huh.  It works now.  Go figure!
I was getting some issues with FileNotFound exceptions on some of the .Net Core dependencies.  Guess the problems were related.
