### ISSUE TITLE
Microsoft.AspNetCore.Hosting.WindowsServices  .NET Core Support

### ISSUE THREAD

**Issue by duthiega** [aspnet/Hosting#904]
Is there any plan to upgrade the above assembly to support .NET Core ? 

When trying to build a .NET Core Windows service I'm experiencing problems when inheriting from WebHostService which in turn Inherits from ServiceBase and receive the following error: 

The type 'ServiceBase' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.ServiceProcess, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.	ConsoleApp1..NETCoreApp,Version=v1.1

**Comment by davidfowl** [comment]
ServiceBase isn't ported to .NET Core. Would be good to file that on github.com/dotnet/corefx

**Comment by GuardRex** [comment]
See: https://github.com/dotnet/corefx/issues/6024

**Comment by muratg** [comment]
Backlogging until the required API is added

**Comment by Tratcher** [comment]
The API has been added: https://github.com/dotnet/corefx/pull/22920
Bumping from backlog for re-triage.

**Comment by davidfowl** [comment]
We should look at this for 2.1 now that the work is done.

/cc @DamianEdwards

**Comment by andymac4182** [comment]
Any chance of this making 2.0 @davidfowl as this is a major part of us not being able to easily move to dotnet core? We have moved to ASPNET Core 1.1 was just waiting for a good way to move the services to running against dotnet core without major changes.

**Comment by davidfowl** [comment]
2.0 is done.

**Comment by andymac4182** [comment]
No worries. :)

**Comment by muratg** [comment]
@JunTaoLuo this should be pretty straightforward (i.e. ~1hr job) to cross compile. If it takes more, let me know and we'll punt/close.

**Comment by lavinianastase** [comment]
Hi! Does the development team have an estimated date when Hosting.WindowsServices will be available on .NET Core 2.0? 
Thank you!

**Comment by JunTaoLuo** [comment]
It will be added in the 2.1 release. We are discussing plans on bringing it back to 2.0 as well see https://github.com/aspnet/Hosting/issues/1229.
