### ISSUE TITLE
Respect the order in which the methods in WebHostBuilder are called.

### ISSUE THREAD

**Issue by carlos-sarmiento** [aspnet/Hosting#905]
When doing integration testing (using the TestHost), sometimes I need to mock a dependency that is defined in the Startup class. The method I'm using right now is rather convoluted, involving creating a class that inherits the original Startup class and overriding the ConfigureServices method in order to inject the mocked dependencies.

I have to do it that way because doing this doesn't work:

    var server = new TestServer(new WebHostBuilder().UseStartup<Startup>().ConfigureServices(/* mocks configuration goes here*/));

In my testing, `ConfigureServices` is always called before the Startup class code; doesn't matter whether it is placed before or after the `UseStartup` call. This makes it very difficult to override injected dependencies, since the `ConfigureServices` method in the Startup class will always override the mocked dependencies.

I think that ASP.NET builder should respect the order of the calls, so that `UseStartup` is called first and `ConfigureServices` is called second.

**Comment by DamianEdwards** [comment]
The `ConfigureServices` method there isn't directly comparable to the `ConfigureServices` method you may have on a `Startup` class. Rather, it configures "host services", which are used during the host-building phase of the application, and copied into the application's eventual DI container, as configured by the `Startup.ConfigureServices` method (if present). So, this isn't just a case of method order being honored. These two mechanisms are actually separate (but related) thus honoring the call order here doesn't apply.

**Comment by carlos-sarmiento** [comment]
I understand. My question then would be: Is there a way to override dependencies defined in the Startup class for things like unit testing?

**Comment by carlos-sarmiento** [comment]
Also, I think it would be a good idea to clarify the names on these methods (or at least add your explanation to the documentation). The fact that they are named the same is confusing. I expected them both to do the same thing, and would not have expected them to be so subtly different.

**Comment by DamianEdwards** [comment]
I'm not aware of any way to alter the container after `Startup.ConfigureServices` has been called, but before the container has actually been built and then passed on to `Startup.Configure` from the outside via `TestHost`. Of course, you could always add this hook yourself in a custom version of `TestHost` (if it's not there already).

cc'ing @davidfowl in case he knows.

**Comment by davidfowl** [comment]
There's a way. If you add a custom `IServiceProviderFactory<IServiceCollection>` then you can get access to the service collection before the service provider has been built:

https://github.com/aspnet/Hosting/blob/2aff75154752c00b1a3834843312b8bbf5db55d8/src/Microsoft.AspNetCore.Hosting/WebHostBuilder.cs#L221

**Comment by jonaswikstrom** [comment]
Wow!

.NET-core is new for me and now trying things that I'm used to when using the ordinary .NET framework.  Integrationtesting through the TestServer is one of those things. I was glad when i found that TestServer is there also for .NET core.

Now trying to figure out injecting mocked services into TestServer. The way Carlos-sarmiento describes/asking about in this article was the natural way for me to think of it. A simple way to alter the IServiceCollection after it has been configured using a Startup. Yes, using a startup, the intention af an integrationtest is to alter as little as possible compared to the real setup.  

The answers you guys give in this article is mind blowing BAD!!!  If there is a question how anything works. Why can't anybody of you guys instead answer HOW to do it? @davidfowl, your answer is not an answer sorry!

**Comment by davidfowl** [comment]
There’s a new first class way to do this in 2.1 but it doesn’t look like the above (changing what ConfigureServices does it hugely breaking).

**Comment by pvasek** [comment]
If you want to override any of your services you can still build a wrapper around your Startup and use that instead. It's more work but seems to be working fine.

**Comment by Compufreak345** [comment]
@davidfowl 
As I am having this issues with my WebApplicationTestFixture, what would be the correct way to do it (I've already overriden CreateWebHostBuilder and ConfigureWebHost)?

Thanks!

**Comment by Shaddix** [comment]
@Compufreak345 I believe it's ``.ConfigureTestServices()``:
```
new TestServer(
  new WebHostBuilder()
    .UseEnvironment("Development")
    .UseStartup<Startup>()
    .ConfigureTestServices(serviceCollection => serviceCollection.AddSingleton...)
);
```
