### ISSUE TITLE
HTTP Error 403.14 - Forbidden ON ASP.NET core 1.1 windows 2016 IIS 10.0

### ISSUE THREAD

**Issue by enriqueescobar-askida** [aspnet/Hosting#914]
I have done the new setup fore netcore1.1
when deploying to `IIS:\Sites\<mySite>\<myVirtualDirectory>`
It raises HTTP Error 403.14 - Forbidden
When I double click on <Directory Browsing> to <Enable> it.
It allows to browse local directory.
Besides local user `<SYSTEM>` and `<IUSR>`
should the physical path belong to another user?

Thanks

**Comment by Tratcher** [comment]
IIS does not run as you, you need to give the app pool identity access to the directory.

@shirhatti what's the recommended user to give directory permissions to? This should be added to https://docs.microsoft.com/en-us/aspnet/core/publishing/iis.

I always give directory access to {my_machine}\IIS_IUSRS

**Comment by shirhatti** [comment]
You can ACL the directory to grant access to just the desired AppPool as opposed to IIS_USRS.
This information is captured in the docs- https://docs.microsoft.com/en-us/aspnet/core/hosting/apppool#securing-resources.

**Comment by Tratcher** [comment]
Ah, that would be good to link to from https://docs.microsoft.com/en-us/aspnet/core/publishing/iis

**Comment by shirhatti** [comment]
Created a linked doc bug so I can go ahead and close this issue.
