### ISSUE TITLE
Stop adding "http://localhost:5000" to empty IServerAddressesFeatures

### ISSUE THREAD

**Issue by halter73** [aspnet/Hosting#917]
Servers such as Kestrel and HttpSysServer should define their own default listening endpoints (which will likely still listen on port 5000) so that the servers don't have to assume that a single address of "http://localhost:5000" indicates that no listening endpoint has been configured.

[Here is the relevant line of code](https://github.com/aspnet/Hosting/blob/80ae7f056c08b740820ee42a7df9eae34541e49e/src/Microsoft.AspNetCore.Hosting/Internal/WebHost.cs#L245)

**Comment by halter73** [comment]
https://github.com/aspnet/KestrelHttpServer/pull/1312 is Kestrel's reaction to this proposed change. The Kestrel PR can be merged first, since adding "http://localhost:5000" to IServerAddressesFeature only results in a warning.

**Comment by shirhatti** [comment]
@Tratcher Do we have an issue to react to this in HttpSysServer as well?

**Comment by Tratcher** [comment]
https://github.com/aspnet/HttpSysServer/issues/297
