### ISSUE TITLE
Provide an easy way to define default environment to be used

### ISSUE THREAD

**Issue by NickAb** [aspnet/Hosting#919]
Currently default environment is hard coded as `Production` in [`HostingEnvironment`](https://github.com/aspnet/Hosting/blob/dev/src/Microsoft.AspNetCore.Hosting/Internal/HostingEnvironment.cs#L10). And both `HostingEnvironment` and `ConfigurationBuilder ` are hardwired in [`WebHostBuilder`](https://github.com/aspnet/Hosting/blob/dev/src/Microsoft.AspNetCore.Hosting/WebHostBuilder.cs#L41).

This leads to `Production` being used as default environment, which could lead to very unfortunate mistakes when environment variables are misconfigured in IIS web site and it tries to use production configs. I would prefer to set `Development` as a safer way to use when environment is not setup explicitly.

Is there any simple way to do it without inheriting from or reimplementing `WebBuilderHost`? If not, is there any plans to add a way to provide any means to customise default environment?

**Comment by davidfowl** [comment]
The default environment will always be "Production", there's been lots of discussion about this, see https://github.com/aspnet/Home/issues/712 for more information.

> Is there any simple way to do it without inheriting from or reimplementing WebBuilderHost? If not, is there any plans to add a way to provide any means to customise default environment?

There's a `UseEnvironment` extension method that you can use to explicitly set the environment. You can also set the  `ASPNETCORE_ENVIRONMENT` environment variable to change the defaults.

**Comment by khellang** [comment]
Also related; https://github.com/aspnet/Hosting/pull/720

**Comment by NickAb** [comment]
Sorry for dup. I guess simplest workaround is to set environment variable in `Program.cs` right before the `WebHostBuilder` is created.

**Comment by davidfowl** [comment]
or use the API

**Comment by NickAb** [comment]
As I understand, API (`UseEnvironment`) can only be used to set explicit environment programatically overriding any environment being set by `WebHostBuilder` in its constructor from `ASPNETCORE_ENVIRONMENT` environment variable. Meaning it does not allow setting custom default environment.

**Comment by davidfowl** [comment]
So you want a way to change the default while still allowing it to be overridden by an environment variable.

**Comment by NickAb** [comment]
Yes, I wanted to set default environment to `Development` before reading linked issues. But I have an internal project, where leaking of stack-traces, etc. is not a big security concern.
I think I will go another way by explicitly setting `ASPNETCORE_ENVIRONMENT` in `<environmentVariables>` section of `web.config` during deployment using `msdeploy` `-setParameter`.

Anyway, I think it would be nice to have `WebHostBuilder` constructor that takes `IHostingEnvironment` or `IConfigurationBuilder`, or both. As it gives more flexibility.

**Comment by davidfowl** [comment]
We could add another extension method, UseDefaultEnvironment.
