### ISSUE TITLE
Investigate adding IHttpContextAccessor by default

### ISSUE THREAD

**Issue by davidfowl** [aspnet/Hosting#922]
There have been some large improvements to the performance of async local in CoreCLR (see https://github.com/dotnet/coreclr/commit/29b13d32fc84d040e0771bd391a4d99503a0d7bc). It's worth taking a look and seeing what the performance hit is now with it added as a service by default.

Adding it by default would make it a bit nicer to use as the user wouldn't have to know the lifetime of the service to register (though we did hack that to make it work)

/cc @benaadams @mikeharder @Tratcher

**Comment by benaadams** [comment]
Its still the devil... make it a hosting flag which auto-registers it or something instead? (Or something alt-DI can trigger easily)

**Comment by benaadams** [comment]
To provide more sensible context; setting anything in async local moves all execution off the default execution context which has various optimizations; so they no longer apply.

**Comment by benaadams** [comment]
Would add `HttpContext` it to `RequestServicesFeature` work instead? As you are always paying the cost for that anyway...

**Comment by davidfowl** [comment]
How does that help?

**Comment by davidfowl** [comment]
We're not going to do this
