### ISSUE TITLE
Middleware making HttpClient request to running project when using Microsoft.AspNet.TestHost.TestServer

### ISSUE THREAD

**Issue by joshmouch** [aspnet/Hosting#927]
When you are running a test using a `TestServer`, what URL do you use within the ASP.Net Core project to access the server from inside a middleware component?  I know you can create an HttpClient and an HttpMessageHandler from an instance of the TestServer, but I have multiple cases where Middleware isn't allowing me to pass in an HttpClient or HttpMessageHandler.

The problem is that in my Startup.cs, I use `app.UseJwtBearerAuthentication`, which requires an "Authority" to be passed in.  The Authority server is hosted by the same (running) ASP.Net Core site  However, I can't find a way to make that work.

When you create a client from the TestServer instance, it shows the BaseAddress as "http://localhost", so I thought maybe I could use that, but when I try to make a request to that address, I just get a 404.

Another idea I had is that the TestServer can create an instance of `HttpMessageHandler`, and the `JwtBearerOptions` has a property call `BackchannelHttpHandler` I could set with the `HttpMessageHandler` instance.  But the problem is that the JwtBearerOptions are done being setup by the time I an able to get an instance of `HttpMessageHandler` from TestServer.

**Comment by muratg** [comment]
Here's a way you can do it: https://github.com/aspnet/Security/blob/dev/test/Microsoft.AspNetCore.Authentication.Test/Google/GoogleMiddlewareTests.cs#L304-L340

**Comment by joshmouch** [comment]
@muratg Thanks for the attempt, but this doesn't quite work for my scenario.
I got my scenario working like this:
1. Create a TestHttpMessageHandler that acts as nothing but a proxy to another HttpMessageHandler (more specifically, the ClientMessageHandler provided by Microsoft.AspNet.TestHost).  I just override SendAsync, do some reflection, and pass the request over to the wrapped instance's SendAsync method.
2. Create an instance of TestHttpMessageHandler.  This instance is not yet function since it has nothing to proxy requests to yet.
3. During TestServer creation, inject whatever HttpMessageHandler's I'll need to use in Startup.cs.
4. In Startup.cs, get and use the injected HttpMessageHandler's if they are available.  Again, these HttpMessageHandlers are not yet functional since they have no instance to proxy SendAsync calls to.
5. After the TestServer is created, call CreateHandler() on it to get an instance of ClientMessageHandler.
6. Assign this instance to the proxies I created in step #1.  All HttpMessageHandlers used in step #4 are now functional and are sending requests to the TestServer as they should.

**Comment by Mertsch** [comment]
I have found a way to do this without impacting my production code
```
protected override void ConfigureServices([NotNull] IServiceCollection services)
{
    base.ConfigureServices(services);

    services.AddSingleton(sp =>
    {
        WebApplicationFactory<Startup> factory = new WebApplicationFactory<Startup>()
            .WithWebHostBuilder(builder => builder.ConfigureServices(hostServices =>
            {
                hostServices.TryAddEnumerable(ServiceDescriptor.Singleton<IPostConfigureOptions<JwtBearerOptions>, JwtBearerOptionsTestConfigurator>(_ => new JwtBearerOptionsTestConfigurator(sp)));
            }));
        factory.ClientOptions.BaseAddress = new Uri("https://localhost");
        return factory;
    });
}
```
and
```
public sealed class JwtBearerOptionsTestConfigurator : IPostConfigureOptions<JwtBearerOptions>
{
    [NotNull]
    private readonly IServiceProvider serviceProvider;

    public JwtBearerOptionsTestConfigurator([NotNull] IServiceProvider serviceProvider)
    {
        this.serviceProvider = serviceProvider;
    }

    public void PostConfigure([CanBeNull] string name, [NotNull] JwtBearerOptions options)
    {
        WebApplicationFactory<Startup> webApp = this.serviceProvider.GetRequiredService<WebApplicationFactory<Startup>>();

        options.Authority = webApp.ClientOptions.BaseAddress.AbsoluteUri;
        options.BackchannelHttpHandler = webApp.Server.CreateHandler();
    }
}
```

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
