### ISSUE TITLE
MVC Controller discovery when using test server

### ISSUE THREAD

**Issue by ItsVeryWindy** [aspnet/Hosting#928]
I don't know if this is an issue with the test server or with the way mvc discovers controllers. I've got some controllers in a separate package that is used by my application. My application gets referenced by my test project which is using the test server. When running my application the controllers from the separate package work just fine, but when using the test server it isn't able to find them.

I was able to figure out that the IHostingEnvironment uses the assembly name of my application for the ApplicationName and that gets used by mvc to discover what assemblies to look for controllers in.

So I changed the ApplicationName using setting it using the WebHostBuilder.

builder.UseSetting(WebHostDefaults.ApplicationKey, Assembly.GetEntryAssembly().FullName)

and that seemed to fix the issue for me, but it would be nice if it just worked out of the box.

**Comment by Tratcher** [comment]
At a minimum it would be nice if we had a discoverable extension for this.

**Comment by kichalla** [comment]
@ItsVeryWindy could you share the repro code (how you are using in the Web App and in the test code) where you are seeing this issue. You can take a look at MVC's functional tests (using ApplicationPart)
https://github.com/aspnet/Mvc/blob/dev/test/Microsoft.AspNetCore.Mvc.FunctionalTests/MvcTestFixture.cs

**Comment by ItsVeryWindy** [comment]
@kichalla I've thrown together an example here
https://github.com/ItsVeryWindy/ControllerDiscoveryIssue

**Comment by JunTaoLuo** [comment]
It seems like you are missing the build option `"preserveCompilationContext": true` in your `project.json`. This means that while MVC is loading the startup assembly `ControllerDiscoveryIssue`, its dependency `Controllers` is not being loaded and therefor you are seeing the 404.

**Comment by JunTaoLuo** [comment]
@ItsVeryWindy I'm closing this since I verified that preserving the compilation context resolves your issue (at least in the repro you provided). Please re-open if there are other issues.

**Comment by ItsVeryWindy** [comment]
This seems to be broken again since moving to the csproj format, setting PreserveCompilationContext to true no longer fixes the issue.
