### ISSUE TITLE
WebHostBuilder allows creation only of a single instance of WebHost (1.1)

### ISSUE THREAD

**Issue by jaredcnance** [aspnet/Hosting#930]
Upgrading to 1.1 causes the following error in integration tests:
```
DotNetCoreDocsExampleTests.UserControllerIntegrationTests.Can_Get_User_ById [FAIL]
      System.AggregateException : One or more errors occurred. (WebHostBuilder allows creation only of a single instance of WebHost) (The follow
ing constructor parameters did not have matching fixture data: DocsFixture`3 fixture)
      ---- System.InvalidOperationException : WebHostBuilder allows creation only of a single instance of WebHost
      ---- The following constructor parameters did not have matching fixture data: DocsFixture`3 fixture
      Stack Trace:

        ----- Inner Stack Trace #1 (System.InvalidOperationException) -----
           at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
        /Users/jcnance/dev/DotNetCoreDocs/src/DotNetCoreDocs/DocsFixture.cs(31,0): at DotNetCoreDocs.DocsFixture`3..ctor()
```

For reference, the repository I'm working on is here: https://github.com/jaredcnance/DotNetCoreDocs/

And the changes I made while upgrading are here: https://github.com/jaredcnance/DotNetCoreDocs/commit/fc72ef576bea9b39a575a6d96432f66b04b69ca3

- There is a fixture class which creates the `TestServer` [in its constructor](https://github.com/jaredcnance/DotNetCoreDocs/blob/master/src/DotNetCoreDocs/DocsFixture.cs#L26). 
- The fixture implements `IDisposable` and [disposes of the server](https://github.com/jaredcnance/DotNetCoreDocs/blob/master/src/DotNetCoreDocs/DocsFixture.cs#L63).
- The fixture class is [inherited by the test classes](https://github.com/jaredcnance/DotNetCoreDocs/blob/master/example/DotNetCoreDocsExampleTests/TodoItemsControllerIntegrationTests.cs#L18). And the above error is thrown when I run `dotnet test`.

**Comment by davidfowl** [comment]
You need to make a new webhostbuilder and web host per test. I'm not super familiar with the lifetime of xunit structures.

**Comment by jaredcnance** [comment]
So, I verified that the fixture was being created twice, and implemented a collection [as described in the xunit docs](http://xunit.github.io/docs/shared-context.html). I now see that the fixture is only created once, and so `WebHostBuilder.Build()` is only called once. But I still get the error.

The following code runs once and returns the below output

```
_server = new TestServer(builder);

try 
{
    Console.WriteLine("Building...");
    _services = builder.Build().Services;
}
catch(Exception e)
{
    Console.WriteLine(e.Message);
    Console.WriteLine(e.StackTrace);
}
```

stdout -->
```
Building...
WebHostBuilder allows creation only of a single instance of WebHost
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at DotNetCoreDocs.DocsFixture`2..ctor() in /Users/jcnance/dev/DotNetCoreDocs/src/DotNetCoreDocs/DocsFixture.cs:line 34
```

**Comment by Tratcher** [comment]
`new TestServer(builder);` also calls Build.
https://github.com/aspnet/Hosting/blob/dev/src/Microsoft.AspNetCore.TestHost/TestServer.cs#L25

**Comment by jaredcnance** [comment]
That was it! Thanks for the help guys
