### ISSUE TITLE
Low compression issue - IIS & ASP.Net Core

### ISSUE THREAD

**Issue by sylvaincaillot** [aspnet/Hosting#934]
Hello,
I have developed the same application which delivers a JSON file in 2 different projects. One is based on ASP.Net MVC4 and the other is based on ASP.Net Core 1.1.0. The JSON generated by my controller is around 5Mo and its content-type is text/plain when returned to the client.

However when publishing the 2 apps, i have a difference of sizes for this file if it is compressed or not on both plateforms.

For ASP.Net Core, I have even tried to enable the compression middleware in the Startup.cs to see the difference:

```
    services.AddResponseCompression(
        options =>
            options.MimeTypes = ResponseCompressionMimeTypes.Defaults);

    app.UseResponseCompression()
       .UseStaticFiles();
```

This is the summary of my tests for my original 5Mo JSON returned to the client:

On my local IIS 7.5 with dynamic and static compression enabled, size of my JSON on:

- MVC4: 256Ko
- ASP.Net Core default: 1.3Mo
- ASP.Net core with compression middleware: 869Ko

On my production IIS 7.5 with dynamic and static compression enabled, size of my JSON on:

- MVC4: 136Ko
- ASP.Net Core default: 675Ko
- ASP.Net core with compression middleware: 869Ko

For MVC4, it seems that it is using full IIS compression capabilities.

For ASP.Net Core, when the compression is enabled in the Startup.cs, the size of the file is constant but not as small as it could be.

For ASP.Net Core, when the compression is not enabled in Startup.cs, the file is gzip by default but I am not sure it is even using the compression capabilities of the IIS server.

My question is what could I do to obtain a compressed JSON in ASP.Net Core as small as the one I obtained on my older plateform based on MVC4.

I tried to use RunIISPipeline as suggested [here](http://stackoverflow.com/questions/29156701/how-to-gzip-static-content-in-asp-net-core-in-a-self-host-environment) but it is no more available.

What are the best practices to publish on IIS an ASP.Net Core app and make sure that the compression is optimal?

Thanks

Sylvain

**Comment by Tratcher** [comment]
This issue was moved to aspnet/BasicMiddleware#205
