### ISSUE TITLE
Building and opening VS adds launchSettings

### ISSUE THREAD

**Issue by davidfowl** [aspnet/Hosting#938]
![image](https://cloud.githubusercontent.com/assets/95136/22859620/a5075872-f096-11e6-8097-57349e5607e6.png)

Is this supposed to be checked in or ignored?

/cc @Tratcher

**Comment by benaadams** [comment]
VS17 doing this to every project; thought it was just me doing something strange..!

**Comment by davidfowl** [comment]
hmm, might need to file this on aspnet/Tooling /cc @BillHiebert

**Comment by Tratcher** [comment]
A few samples need it to preserve settings, like Security. Not these though.

**Comment by BillHiebert** [comment]
@davidfowl - are these web projects? Non web projects (class libraries and console apps) shouldn't be adding a launchsettings.json file

**Comment by benaadams** [comment]
Might be it, TestSites are `<Project Sdk="Microsoft.NET.Sdk.Web">` and Sample which doesn't create it are `<Project Sdk="Microsoft.NET.Sdk">`

Thought before would get a `launchSettings.json` when trying to run using IIS Express choice as the run button, rather than just opening project? Might be misremembering.

**Comment by BillHiebert** [comment]
The launchsettings.json file has always been added when a web project is opened. We can certainly look into improving this going forward.

**Comment by davidfowl** [comment]
Something new is happening since the conversion. Maybe we need to update our git ignore files

**Comment by JunTaoLuo** [comment]
Or just put this file in your global git ignore file

**Comment by davidfowl** [comment]
I should *never* have to do that. It means something in our repository is broken.

**Comment by JunTaoLuo** [comment]
Usually it's not an interesting file so no harm in ignoring it. You can always override the ignore when you want to check it in. Otherwise, as you said, someone need to go through all the repos and add the ignore rule where appropriate.

**Comment by BillHiebert** [comment]
In Dev14 we had the notion of default profiles which wouldn't be persisted unless there were other changes. This is no longer the case for web projects, that feature was lost when the code was refactored. I am guessing this is what you are running into.

**Comment by Tratcher** [comment]
Some repos require it (e.g. Security) so we don't want a blanket ignore. They're part of the templates, we should just check them in.

**Comment by davidfowl** [comment]
For the 1% of repos that needxthem checked in sure. None of the rest need them

**Comment by Tratcher** [comment]
If we were consistent then we wouldn't have to keep having this discussion.

**Comment by davidfowl** [comment]
Keep having it? I haven't seen this discussed before so forgive me. We're going to gitignore these files and the security repo can force add them.

**Comment by BillHiebert** [comment]
I opened this bug to track: https://devdiv.visualstudio.com/web/wi.aspx?pcguid=011b8bdf-6d56-4f87-be0d-0092136884d9&id=384396

**Comment by glennc** [comment]
I don't think it adds any value to keep this open for tracking like we might normally do, so closing.
