### ISSUE TITLE
Add Platform lightup hook

### ISSUE THREAD

**Issue by glennc** [aspnet/Hosting#951]
https://github.com/dotnet/core-setup/issues/1597 allows us to do platform lightup on Azure.

We need to implement a hook that allows a server to inject packages and implement a package for Azure App Service that adds the Azure App Service logger.

This issue is for the hook. The implementation would go in the AzureIntegration repo.

**Comment by muratg** [comment]
@davidfowl when can I review the code? :)

**Comment by davidfowl** [comment]
I haven't been working on this.

**Comment by davidfowl** [comment]
Follow up items
- If the application throws and the hosting startup assembly throws the hosting startup errors aren't show in the error page.
- Review error messages and logged error experiences

**Comment by davidfowl** [comment]
@DamianEdwards and I agreed the exception behavior is correct. I don't think there's anything left to do here but remove the `/REVIEW:` from the codez

**Comment by Tratcher** [comment]
What was the rational?

**Comment by DamianEdwards** [comment]
Startup errors capturing is on by default with IIS integration and thus Azure. If it's on, and a loaded module fails, it's logged and the app runs as normal.

**Comment by davidfowl** [comment]
Am closing this bug (again). We can open new bugs as we find issues with the experience
