### ISSUE TITLE
First class Configuration and Logging in WebHostBuilder

### ISSUE THREAD

**Issue by glennc** [aspnet/Hosting#955]
We want to enable the following program main:

```csharp
public static void Main(string[] args)
        {
            var host = new WebHostBuilder()
                .UseContentRoot(Directory.GetCurrentDirectory())
                .UseConfiguration((configBuilder, env) => 
                {
                    configBuilder.AddJsonFile("appsettings.json", optional: false, reloadOnChange: true)
                                 .AddJsonFile($"appsettings.{env.EnvironmentName}.json", optional: true)
                                 .AddEnvironmentVariables()
                                 .AddCommandLine(args);
                })
                .UseLogging((factory, config) =>
                {
                    factory.AddFilter(config.GetSection("Logging"));
                    factory.AddConsole();
                    factory.AddDebug();
                })
                .UseIISIntegration()
                .UseStartup<Startup>()
                .UseKestrel()
                .Build();

            host.Run();
        }
```

This issue is to track the WebHostBuilder part of this.

**Comment by Tratcher** [comment]
* With an eye to removing these parts from Startup and exposing config via DI.

**Comment by cwe1ss** [comment]
Sounds great! How will users be able to get the configuration object?

**Comment by cwe1ss** [comment]
> With an eye to removing these parts from Startup and exposing config via DI.

Would I be able to resolve `IConfiguration` or would it be a separate type? My concern with IConfiguration are scenarios where applications use multiple independent configuration objects. (e.g. one for appSettings and one for secrets from Azure Key Vault). It might not be clear what gets injected when people use IConfiguration. Not sure if this is a real concern though?!

**Comment by glennc** [comment]
At the moment I think we will just put IConfigurationRoot in DI. We are hearing from many people that it's what they want.

Not completely obvious in this, but relevent to you @cwe1ss is that this will play into the other issue about deprecating AddProvider on LoggerFactory and allowing Serilog, NLog, etc to replace the LoggerFactory instead of having a provider.

**Comment by glennc** [comment]
Having IConfiguration in DI doesn't stop you from using multiple, but you would need to define them yourselves and pick which one is the one that goes into DI. Ideally use Options as well instead of Configuration directly.

**Comment by cwe1ss** [comment]
Yep, just wanted to point it out... it might not be an issue. 
Will you add IConfigurationRoot and IConfiguration? IConfiguration seems nicer to me for DI because it's the more generic interface. People who use 3rd party DI containers could probably do more stuff with it (e.g. Injecting just a section).

> Not completely obvious in this, but relevent to you @cwe1ss is that this will play into the other issue about deprecating AddProvider on LoggerFactory and allowing Serilog, NLog, etc to replace the LoggerFactory instead of having a provider.

Awesome!!

**Comment by cwe1ss** [comment]
PS: I'm using Options most of the time, yes. So again, not sure how important the IConfiguration scenario really is.
