### ISSUE TITLE
[Discussion] Hosting no longer adds default server address when no address is explicitly configured

### ISSUE THREAD

**Issue by JunTaoLuo** [aspnet/Hosting#956]
Discussion for https://github.com/aspnet/Announcements/issues/224.

**Comment by JunTaoLuo** [comment]
Our servers have been updated in https://github.com/aspnet/HttpSysServer/issues/297 and https://github.com/aspnet/HttpSysServer/issues/297 so if Kestrel or HttpSysServer is being used, no changes are required. 

If you are implementing a server and rely on the `IServerAddressesFeature` to be set by hosting, that will no longer be set and a default should be added when no address is configured. As an example:
```c#
var serverFeatures = featureCollection.Get<IServerAddressesFeature>();
if (serverFeatures .Addresses.Count == 0)
{
    ListenOn(DefaultAddress); // Start the server on the default address
    serverFeatures.Addresses.Add(DefaultAddress) // Add the default address to the IServerAddressesFeature
}
```

Note that for Kestrel and HttpSysServer, the priority for address resolution is 
1. Direct configuration via `KestrelServerOptions.Listen()` or `HttpSysOptions.UrlPrefixes.Add()`
2. List of addresses in `IServerAddressesFeature.Addresses`
3. Default address chosen by the server

**Comment by muratg** [comment]
We are closing this issue because no further action is planned for this issue. If you still have any issues or questions, please log a new issue with any additional details that you have.
