### ISSUE TITLE
Making windows service raises error from Nuget.

### ISSUE THREAD

**Issue by EmmaHansson** [aspnet/Hosting#965]
In Visual Studio 2017 Using nuget I tried to install Microsoft.AspNetCore.Hosting.WindowsServices.

But it was failed.

**Comment by muratg** [comment]
@EmmaHansson What exactly fails?  Does your app target .NET Core or .NET Framework?  Could you create a sample app and put it on a GitHub repo?

**Comment by timothy3001** [comment]
I have experienced the same issue. I'm targeting .NET Core, so I thought I should be able to install this from NuGet. 
I looked into the code here https://github.com/aspnet/Hosting/tree/dev/src/Microsoft.AspNetCore.Hosting.WindowsServices and I found, that one of the imports is System.ServiceProcess which is, as far as I know, not supported in .NET Core anyways. The targeted framework is set to net451 in that package.

I thought that all of the code in this repository should target .NET Core or did I get this wrong? I'm new to .NET Core and would be thankful for any advice.

Thanks in advance
Timo

**Comment by Tratcher** [comment]
Asp.net Core as a whole runs on both .Net and .Net Core, but some special features (like this package) only work on one or the other because of their dependencies. This package will only work on .Net, not Core.

**Comment by timothy3001** [comment]
Oh ok, thank you for your quick response. It's kinda confusing though reading the description of https://github.com/aspnet/home which states that ASP.NET Core can be used  in .NET Core and .NET.

Are you able to give an estimation about how many classes are actually able to be used in .NET Core? Like, is it rather 95% of all classes or rather 60% for example?

Thank you

**Comment by EmmaHansson** [comment]
It would be great if I can't use it Core, then I can't install it for Core.  I guess it should work for Core, if you use <TargetFramework>4.5.

**Comment by Tratcher** [comment]
This is the only package so far that only works on .Net, besides a few back compat packages.

Most other differences between frameworks are limited to individual method implementations.
