### ISSUE TITLE
TestServer - issue with Razor

### ISSUE THREAD

**Issue by rodchenkov** [aspnet/Hosting#966]
Hi All

I just got issue with TestServer in new xUnit Test csproj for csproj AspNetCore WebApplication (netcoreapp1.1)!

I found same issue here https://github.com/aspnet/Hosting/issues/954 but it is closed without any reply on when it will be fixed.

Please check and reply

**Comment by muratg** [comment]
Dup of https://github.com/aspnet/Hosting/issues/954. (It was recently reopened)
