### ISSUE TITLE
Server addresses configuration enhancements

### ISSUE THREAD

**Issue by JunTaoLuo** [aspnet/Hosting#968]
- Add `PreferConfig/PreferHostingUrls` to `IServerAddressesFeature` with a default value of false
- Add extension to `WebHostBuilder` to set this flag

**Comment by natemcmaster** [comment]
Followup: Kestrel https://github.com/aspnet/KestrelHttpServer/issues/1575

**Comment by JunTaoLuo** [comment]
Followup: HttpSysServer https://github.com/aspnet/HttpSysServer/issues/336
