### ISSUE TITLE
AspNetCore.TestHost.TestServer - Response.OnStarting() called twice for a single request

### ISSUE THREAD

**Issue by jimasp** [aspnet/Hosting#971]
I created an out-of-the-box template ASP.NET Core MVC web application in Visual Studio.

I then added a AspNetCore.TestHost.TestServer  and a parallel integration test to hit the home page. 
This works fine.

I then added a simple Middleware class with a Response.OnStarting() callback to add a header. 
Re-running the same test now results in exceptions when the headers are added:
"An item with the same key has already been added."

After adding some debug, I can see that Response.OnStarting() is being called more than once for the same request, so it is trying to update the response headers twice for a single request, causing the exception. Unfortunately, I can't see why Response.OnStarting() would be called twice. It seems the controller action is sometimes hit twice too, but that is not required to raise the exception.

If I run a non-parallel integration test, there are no exceptions.

If you have VS2015 and .net core tools installed, you can download the solution yourself and try it here:
[HeadersNoWorky.zip](https://github.com/aspnet/Hosting/files/857430/HeadersNoWorky.zip)

**Comment by davidfowl** [comment]
@jimasp any chance you can put this in a github repo?

**Comment by jimasp** [comment]
https://github.com/jimasp/HeadersNoWork

**Comment by Tratcher** [comment]
Does it behave any differently if you make your test fully async?

**Comment by jimasp** [comment]
@Tratcher - knocked up a quick async version here:
https://github.com/jimasp/HeadersNoWork/tree/fullasync

As you'd expect it spawns threads slightly differently so the behaviour is a little different, but the result is fundamentally the same, i.e. Response.OnStarting() is still called multiple times for a single request. 

i.e. the (simplified) debug output is like this for both cases:
###CTX:3278065, url:http://localhost:5000/3  (response.onstarting() called once for url /3)
###CTX:3278065, url:http://localhost:5000/3  (response.onstarting() called twice for url /3 - with same context object hashcode)
Exception: an item with the same key has already been added

**Comment by Tratcher** [comment]
This may be related to https://github.com/aspnet/Hosting/commit/b6da89f54cff11474f17486cdc55c2f21f2bbd6b. Can you give it one more try with 1.1?

**Comment by jimasp** [comment]
@Tratcher test project is only a month old, so it didn't occur to me someone would have used an old version! 
looking at that commit, it looks very likely to be the problem. 
on train, will try it when I get home and report back. 
thanks.

**Comment by jimasp** [comment]
@Tratcher  yep that fixed it, but strangely only in the full async stack branch.
I don't know why that would be? 

At any rate, it's good enough for me if you want to close the issue.
(My single test was actually simulating the test runner running 100+ integration tests in parallel in the real solution, 10 or so at a time - and that now all works).

Thank you. 
(/smackshead for not thinking to check the version...)
