### ISSUE TITLE
Shutdown Test fail on CI

### ISSUE THREAD

**Issue by jbagga** [aspnet/Hosting#974]
[ShutdownTest](https://github.com/aspnet/Hosting/blob/dev/test/Microsoft.AspNetCore.Hosting.FunctionalTests/ShutdownTests.cs#L19) is failing on the Ubuntu Universe CI test run.

http://aspnetci/viewLog.html?buildId=190441&tab=buildResultsDiv&buildTypeId=XPlat_Linux_UbuntuUniverseCoreCLR

@pakrym

**Comment by JunTaoLuo** [comment]
I found the problem.
