### ISSUE TITLE
Could WebHostExtensions.Run() use Logging?

### ISSUE THREAD

**Issue by gingters** [aspnet/Hosting#979]
Hello,

I have an issue with `WebHostExtensions.Run()` using `Console.WriteLine()` instead of writing its log entries to an ILogger instance, just like [this](https://github.com/aspnet/Hosting/blob/2bddba8f9023c0d14332b90235c7dffe16e3e353/src/Microsoft.AspNetCore.Hosting/WebHostExtensions.cs#L72-L73).

It seems pretty unintuitive that, after you already haved configured your logging etc. in the `WebHostBuilder.Build()` method, that the `.Run()` method after that should not be able to leverage this information.

So I would like to propose that the `WebHostExtensions.Run()` should try to resolve an ILogger from the `host.Services` just as it does with the hostingEnvironment and applicationLifetime, and use that if available. Only if there is no logger available it should fall back to writing to the Console directly.

What do you think about this? Could we make this happen?

**Comment by davidfowl** [comment]
How would you know if there's no logger available? Also these messages are for the developer. Do you have an actual issue with them being console writeline statements?

**Comment by cwe1ss** [comment]
I think it would be nice to have it sent to both. For remote loggers it would be an earlier "Hello World, I'm here" message. And I wouldn't remove the console output because it's a nice troubleshooting instrument e.g. in Service Fabric where you sometimes have to inspect console output etc.

**Comment by davidfowl** [comment]
The only problem is that by default you'd end up with this duplication of messages. Do you really think logging the bound end point information is useful for your logs? I can see the environment as the only thing being useful. The content root is a developer artifact as well. 

If this is a purist argument, then I get it but the practical side of me says this won't add much value.

**Comment by cwe1ss** [comment]
hmm.. true! My scenario is just an early out-of-the-box "Application started" logging message. But that's obviously something that can easily be done as the first thing in Startup as well.

**Comment by gingters** [comment]
The main issue is that these logs that are captured from the console are not as easily parsable as they could be, as these lines don't match the desired and configured console logger output format than all the other lines. This is desired for launching a service for automated tests and then simply capturing and analysing the console output instead of having to configure a certain file logger explicitely (which then would lack the environment and port information).

Also, knowing if no logging is available would be the case when no ILogger could be resolved?

**Comment by gingters** [comment]
Oh, and yes, if you deploy a command line tool that temporarily offers a web service, you actually don't want to print these lines in the the command prompt for the user. Wrapping that in something that calls `mytool.exe > nul 2>&1` would just be a ugly workaround for that. It would be great if there would be a way to at least disable the WriteLines for production, as we could log environment and port (and even ContentRootPath or shutdown message if desired) easily by our own when required.

That would be less effort and more convenient than to duplicate the complete Run extension.

**Comment by davidfowl** [comment]
@gingters Then use `Start()` instead of `Run`

**Comment by davidfowl** [comment]
> Also, knowing if no logging is available would be the case when no ILogger could be resolved?

No, that's not right. The logger can always be resolved, the producer and consumer of logs is completely decoupled.

**Comment by davidfowl** [comment]
How about we add a flag that says if hosting should prefer logging for this? That way we can just use that to determine if we should log or use console output?

**Comment by davidfowl** [comment]
We're going to move away from writing to the console when using the generic host

**Comment by tgourley** [comment]
I was about to put in an issue and it suggested this as related.  I noticed the discussion from 20 months ago, and then just so happened a comment from just 10 hours ago.

So when you say you are moving away from writing to the console, does that mean that it is moving towards using logging?

I know this is an old discussion, but I can provide a specific example where this would benefit us (going towards logging.)

We have a web application that loads dynamically on certain ports based on its "role".  This is a microservices application that can be a web app on port 6000 or an API app on port 7000 and others.  When running these services locally we run them on different ports.  When running in the cloud, these services run under different ports and sometimes the same ports but behind load balancers (no direct communication).

The output of the IWebHost.Run() (which just calls the RunAsync()) can help diagnose any url, ip address, or port configuration issues.  We use Serilog with several sinks to capture log data.

Right now, when the application runs, we get console output that looks like...
![image](https://user-images.githubusercontent.com/495655/48499170-d15fd800-e805-11e8-9e02-ca9ea8305020.png)

As you can see, the "Console.WriteLine(...)" areas are not part of the logging.

We can then also see those debug lines missing from our database table that captures the information.
![image](https://user-images.githubusercontent.com/495655/48499347-3ca9aa00-e806-11e8-82e5-7a47d2ecfd09.png)

**Comment by davidfowl** [comment]
Yes we’re going to use logging
