### ISSUE TITLE
Consider adding a UseRequestServices overload for multi-tennant support

### ISSUE THREAD

**Issue by HaoK** [aspnet/Hosting#98]
Potentially replacing this overload of UseRequestServices:

        public static IApplicationBuilder UseRequestServices(this IApplicationBuilder builder, Func<HttpContext, IServiceProvider> applicationServices)
        {
            builder.ApplicationServices = applicationServices;

            return builder.UseMiddleware(typeof(ContainerMiddleware));
        }

**Comment by HaoK** [comment]
RIP UseRequestServices

**Comment by DrLeh** [comment]
@HaoK what is the alternative to UseRequestServices in RC1+? I can't find any info on what to use instead.
