### ISSUE TITLE
Track recent breaking changes in `exceptions.net*.json` files

### ISSUE THREAD

**Issue by dougbu** [aspnet/Hosting#981]
This repo contains untracked breaking changes. To find and address them
1. Revert 387e2d8
2. Run `.\build.cmd /t:Pack` in projects 387e2d8 touched or `.\build.cmd /t:Package` in the repo root
3. Update `exceptions.net45.json` and `exceptions.netcore.json` to track the changes
4. If not already announced, suggest filing issues at https://github.com/aspnet/Announcements

**Comment by Eilon** [comment]
Moving to preview2.
