### ISSUE TITLE
The CGI application did not return a valid set of HTTP errors. A server acting as a proxy or gateway was unable to process the request due to an error in a parent gateway.

### ISSUE THREAD

**Issue by spaceman27** [aspnet/Hosting#983]
I am trying to deploy asp.net core project to iis 8.5. but got 
"The CGI application did not return a valid set of HTTP errors.
A server acting as a proxy or gateway was unable to process the request due to an error in a parent gateway."

```Web.config
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <system.webServer>
    <handlers>
      <add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModule" resourceType="Unspecified" />
    </handlers>
    <aspNetCore processPath=".\MyApp.exe" stdoutLogEnabled="false" stdoutLogFile=".\logs\stdout" >
		<environmentVariable name="ASPNETCORE_ENVIRONMENT" value="Production" />
	</aspNetCore>
  </system.webServer>
</configuration>
```
What could be possibly the root reason?
My app originally asp.net 5 with window authentication, was migrated to asp.net core 1.1.1

**Comment by davidfowl** [comment]
Check the event log for errors.

**Comment by muratg** [comment]
Closing this one. If you're still hitting this issue, please file another bug. Thanks.
