### ISSUE TITLE
Kestrel return 404 when is run as a windows service

### ISSUE THREAD

**Issue by cezarypiatek** [aspnet/Hosting#990]
Hi
I'm having trouble with running my asp.net core 1.1 application as a windows service (I'm using dot.net framework 4.6.2). My setup code looks as follows:

```csharp
Directory.SetCurrentDirectory(System.AppDomain.CurrentDomain.BaseDirectory);
 var host = new WebHostBuilder()
               .UseKestrel()
               .UseUrls("http://*:5000")               
               .UseContentRoot(Directory.GetCurrentDirectory())
               .UseIISIntegration()
               .UseStartup<Startup>()               
               .Build();
 host.RunAsService();
```

after installing my application as as a windows service (with sc create command) I'm getting 404 when requesting http://localhost:5000 address. The service is running and the response contains header "Server: Kestrel".  When I run my application as a regular console app (using host.Run() instead of host.RunAsService()) everything works as it should (http://localhost:5000 return my page)
What am I missing here? How to make my application work as a windows service?

**Comment by Tratcher** [comment]
The doc for this is almost ready. Your content root is most likely wrong.
https://github.com/aspnet/Docs/pull/3060/files#diff-3a33a1126f222fba5d3dac1f77cf8da5R42

**Comment by cezarypiatek** [comment]
I'm not convinced that the path is the problem. I attached debugger and check that it's ok (I've used also code from the link you provided and there is no difference in result).

**Comment by davidfowl** [comment]
You first step to diagnosing anything would be to enable logging. It should tell you exactly what's wrong.

**Comment by muratg** [comment]
Closing this one. Please file another bug if you still have issues.
